### ISSUE TITLE
Suggestion for a global appearance module

### ISSUE THREAD

**Issue by iv-nn** [nix-community/home-manager#1005]
For my own config I created an appearance module, to regroup font and colour choices and reuse them.
I have something like that :
```nix
{
  appearance = {
    font = {
      variable-width = {
        name = "Fira Sans";
        package = pkgs.fira;
      };

      monospace = {
        name = "Fira Code";
        package = pkgs.fira-code;
      };
    };

    colors = rec {
      color0 = "#282c34";
# …
      background = color0;
      foreground = color7;
      red = color1;
# …
    };
  };
}
```

What do you think about adding such a global module and having other modules use these values by default ?

Obviously this module would be totally optional and it should always be possible to overwrite these settings.

By default use monospace font in terminals / editors and variable width everywhere else. For the colours keep it simple, only background and foreground and maybe red and green for error and success where applicable.

**Comment by CRTified** [comment]
Might be highly related to https://github.com/rycee/home-manager/issues/361 - but I'd love such a module.

**Comment by rycee** [comment]
A possibility w.r.t colors is to standardize on the [base16](http://chriskempson.com/projects/base16/) naming. There is some existing work at https://github.com/atpotts/base16-nix/.

**Comment by iv-nn** [comment]
It seems I didn't do enough research before posting this.

So the basics would be to have a module to store font and color values using base16 naming.
Then we could add a `scheme` settings to chose a base16 colorscheme and set the colors accordingly.
And finally use base16 templates to apply those colors correctly to different program settings.

**Comment by sondr3** [comment]
This would be really neat, it's something I've been thinking of as well because I customize themes quite a lot and want to make the consistent across programs and machines. I think starting with the`base16`-naming scheme is a good idea.

**Comment by DamienCassou** [comment]
I also like the idea.

**Comment by wuyoli** [comment]
I would also like to have a module like this and could imagine implementing the colors-related part of something like this. I would go about doing this like suggested by implementing a [base16 Builder Function](https://github.com/chriskempson/base16/blob/main/builder.md) in Nix so the other modules could use it to get the rendered Template already at evaluation time.
But I'm relatively new to contributing to something like this and would likely need mentoring for this.
