### ISSUE TITLE
home-manager switch can't

### ISSUE THREAD

**Issue by gilescope** [nix-community/home-manager#1018]
```home-manager switch``` 
has the following:
```error: error parsing derivation '/nix/store/rbdbz54dgf3n3hfn6i0kjbpgqjq9rmar-home-manager-path.drv': expected string 'Derive(['```
which is not surprising as there's an empty file there.

Linux hung (nixos macbook) while a ```home-manager switch``` was happening creating the empty file. Now the above file is in the nix-store but with no contents and
```sudo nix-store --verify --check-contents --repair``` says it can't repair it?

Is there another command I can run to tell it to get itself back to a happy place?
(I also couldn't see from the command line --help how to go back a generation though I can list generations.)

I feel that if we're being idempotent and have hashes we should be able to recover from this kind of thing gracefully. (I'm conscious this might be a nixos issue rather than home-manager - so feel free to send me in that direction)

**Comment by rycee** [comment]
Yeah, this seems like a Nix issue with https://github.com/NixOS/nix/issues/1218 being very similar. I'm not certain what the best solution would be. Does a GC remove the file?

There is no tooling support for performing rollbacks but the output of `home-manager generations` includes the corresponding generation directory (called something like `/nix/store/…-home-manager-generation`) and inside it there is an executable called `activate`, you can run that to switch to that generation.

**Comment by gilescope** [comment]
I was guessing home-manager switch 12 would switch me to the 12th generation. If you’re ok with that I can try a PR?

**Comment by gilescope** [comment]
nix-garbage-collect fixed this. :-)
Phew! Wiuld it help if that could be suggested if we get errors like that...

**Comment by DieracDelta** [comment]
I'm encountering this error when I do `sudo nix-garbage-collect -d`. However, when I run `home-manager switch` or rebuild my system-wide configuration, I get no errors. Any idea what to do here?

**Comment by DieracDelta** [comment]
Solution was to iterate through the broken drvs and run `nix-store --delete --ignore-liveness`.

**Comment by kolaente** [comment]
I'm also hitting this. Additionally, `sudo nix-store --verify --check-contents --repair` says it can't repair the paths, garbage collect didn't remove it. It looks like repairing is returning the same error message as home manager is, so in order to repair it tries to evaluate it which makes repairing fail?
And when I try to switch back to the last home manager generation, I get `syntax error, unexpected $end`.

Any ideas?
