### ISSUE TITLE
fzf historyWidgetCommand doesn't seem to be working

### ISSUE THREAD

**Issue by thongpv87** [nix-community/home-manager#1020]
This is my fzf config:
```
programs.fzf = {
    enable = true;
    enableBashIntegration = true;
    enableZshIntegration = true;
    fileWidgetOptions = [ "--preview 'head {}'" ];
    historyWidgetCommand = "fc -l 1 | sort -r --key 2.1 -k1,1nr | uniq -f 1 | sort -rn";
  };
```

I have changed `historyWidgetCommand` to remove duplicated command but when I press CTRL+R, it seem not to be working. I tested my command with:
```
fc -l 1 | sort -r --key 2.1 -k1,1nr | uniq -f 1 | sort -rn | fzf
```
and I can confirm it was working as expected.

https://github.com/rycee/home-manager/blob/f487b527ec420b888c52df1c4f8c31439201edb7/modules/programs/fzf.nix#L112

**Comment by rycee** [comment]
I had a look at the fzf `key-bindings.bash` file and from what I can tell it doesn't look for a `FZF_CTRL_R_COMMAND` variable, only `FZF_CTRL_R_OPTS`. So I'm not sure how the option works.

@mogria Do you know how to get the `historyWidgetCommand` option to work?
