### ISSUE TITLE
WTF Module

### ISSUE THREAD

**Issue by evanjs** [nix-community/home-manager#1031]
[WTF](https://wtfutil.com/) ([GitHub](https://github.com/wtfutil/wtf)) is a dashboard utility that I feel would work well as a home-manager module. 

Configuration is done via YAML files, as documented [here](https://wtfutil.com/configuration/).

**Comment by pacien** [comment]
It could be implemented like the [alacritty module](https://github.com/rycee/home-manager/blob/115e76ae12a81bce5dcd19714cdeaaa8d5ca3ce8/modules/programs/alacritty.nix) (attrs + toJSON), but should also allow the definition of multiple config files for mulitple dashboards.
