### ISSUE TITLE
sway: configs default to modifiers in i3 options

### ISSUE THREAD

**Issue by lovesegfault** [nix-community/home-manager#1053]
The sway module should have its own `wayland.windowManager.sway.config.modifier`, and things like `wayland.windowManager.sway.config.floating.modifier` should default to it as opposed to using `i3.config.modifier` as it does now.

**Comment by lovesegfault** [comment]
I was going to fix this but now I see how sway's module was implemented and I no longer know what is right. I should be able to have different modifiers for `sway` and `i3` and that seems like not currently possible.

If that sounds reasonable I can do the work of splitting things

cc. @alexarice who did #829

**Comment by lovesegfault** [comment]
The core of this issue is incorrect.

Sway does not miss a modifier option, but the modules that it shares with `i3`, such as the floating one get default to the `i3` modifier as opposed to the `sway` one. Still an issue.

**Comment by alexarice** [comment]
The only issue I can see is that the `defaultText` attribute for `sway.config.floating.modifier` is incorrect. I am confused about the other issues as when I do `man home-configuration.nix` I can see separate options for `sway.modifier` and `i3.modifier`

**Comment by alexarice** [comment]
As far as I am aware you should be able to have completely separate configs for sway and i3. The only thing which is reused is the option definitions and some functions

**Comment by rycee** [comment]
Is it ok to close this now that #1054 is merged?

**Comment by alexarice** [comment]
I believe so though I don't exactly understand what @lovesegfault 's original problem was

**Comment by lovesegfault** [comment]
The issue was some sway config options have `i3`-related explanations/defaults which was confusing me. Here's another example:
```
       wayland.windowManager.sway.config.colors
           Color settings. All color classes can be specified using submodules with 'border', 'background', 'text', 'indicator' and 'childBorder' fields and RGB color hex-codes as values. See default values for the reference. Note
           that 'sway.config.colors.background' parameter takes a single RGB value. See https://i3wm.org/docs/userguide.html#_changing_colors.
```

(references i3, not sway, docs)

**Comment by alexarice** [comment]
This may be wrong but I still use the i3 docs as the "user guide" for sway configs, hence why the option refers to the i3 user guide. More generally most i3 config syntax should work in sway and so the i3 user guide is a good reference
