### ISSUE TITLE
powershell-core support 

### ISSUE THREAD

**Issue by 573** [nix-community/home-manager#1055]
Hi all,

is there a possibility to add powershell to programs ?
Would be great when working via WSL. I could make a symlink to the home-manager-managed Microsoft.PowerShell_profile.ps1 file and use it within Windows as well.

**Comment by rycee** [comment]
Hmm, I have no experience with powershell but I suppose it would be possible? I haven't heard anybody mention powershell before in relation to HM so if you want a module for it I think you might have to develop it yourself.
