### ISSUE TITLE
force override of certain files not managed by home-manager

### ISSUE THREAD

**Issue by feijoas** [nix-community/home-manager#1067]
I am configuring my user-dirs with `xdg.userDirs`. However gnome or somebody else modifies this file on a `home-manager switch` such that the switch fails.

Can I tell home-manager to override this file even if it is not managed by it?

**Comment by rycee** [comment]
You can give
```
xdg.configFile."user-dirs.dirs".force = true;
```
a try. Note, the `force` options is undocumented and its behavior may change.
