### ISSUE TITLE
support module on all platform(darwin, linux).

### ISSUE THREAD

**Issue by clojurians-org** [nix-community/home-manager#1071]
current i have  nix-darwin function included directly in home-manager fork and migration some nixos module to home-manager
then the module can run on darwin, and home-manager already have systemd support already:

i plan to support general service module that can work on mac and linux at the same time.
and reuse the nixos module directly without any modification in future.

this is the related change and module support,
i doubt whether your project accept those ideas so that i can merge into it.

https://github.com/clojurians-org/home-manager
home-manager -I home-manager=. -f larluo-conf/home.nix  switch
```
  services.redis = {
   enable = true ;
   dataDir = "/opt/nix-module/data/redis" ;
   unixSocket = "/opt/nix-module/run/redis.sock" ;
  } ;

  services.postgresql = { 
    enable = true ; 
    package = pkgs.postgresql_11 ;
    dataDir = "/opt/nix-module/data/postgresql" ;
  } ;

  services.mysql = {
    enable = true ;
    # package = pkgs.mysql80 ;
    package = pkgs.mysql57 ;
    dataDir = "/opt/nix-module/data/mysql" ;
    unixSocket = "/opt/nix-module/run/mysql.sock" ;
  } ;

  services.elasticsearch = {
    enable = true ;
    package = pkgs.elasticsearch7 ;
    dataDir = "/opt/nix-module/data/elasticsearch" ;
  } ;
  
  services.neo4j = {
    enable = true ;
    package = pkgs.neo4j ;
    directories.home = "/opt/nix-module/data/neo4j" ;
  } ;
```

**Comment by clojurians-org** [comment]
reuse nixos module directly:

https://github.com/clojurians-org/home-manager/blob/linux/modules/services/databases/mysql.nix

**Comment by rycee** [comment]
Yes, this would be very nice to have! And long ago Home Manager used a few NixOS modules in this way. Unfortunately we had to stop it because HM would break when the modules were changed in NixOS.

To do this safely would need some form of stable option set that both NixOS and Home Manager could use. Unfortunately that would be a large job which is unlikely to happen soon 🙁
