### ISSUE TITLE
Neovim module doesn't apply configuration

### ISSUE THREAD

**Issue by onny** [nix-community/home-manager#1072]
Hey,
I'm using the Neovim module like this:
```
        programs.home-manager.enable = true;

        programs.neovim = {
	  enable = true;
	  configure = {
	    packages.myVimPackage = with pkgs.vimPlugins; {
	      start = [
	        vim-nix 
	      ];
            };
            customRC = ''
	      set number
            '';
	   };
	};
```
Full config [here](https://git.project-insanity.org/onny/nixos-lappy/-/blob/master/home.nix). When I open a new terminal or reboot, there is none of the configs applied :( I see no numbers in neovim nor syntax highlighting in Nix files :(
I'm using termite with fish shell.

Best regards,
Jonas

**Comment by rycee** [comment]
@teto Do you know what's going on with this issue?

**Comment by teto** [comment]
Have you checked which neovim is launched (`readlink -f $(which nvim)`) ? try to open it and see what init.vim is launched. Also in nvim, you can run `:verbose set number?` to see if anything overrides it.

**Comment by onny** [comment]
Thank you teto for the response.
I tried ``whereis nvim``:
```
nvim: /nix/store/p3s2psd8a6ni37q1ysagjdarvi7cwkcn-user-environment/bin/nvim /nix/store/80f2pp7xx5clgwlxsl1dsldpp0s42qcb-system-path/bin/nvim
```
I could run both but none of them applies "set number" or highlights the nixOS syntax.
After manually type ``:verbose set number`` the numbers are shown.
There is no init.vim inside my home directory :(
```
fd --hidden init.vim .
```
No output :(

**Comment by teto** [comment]
these `nvim` executables should be wrappers that load their own `init.vim`. For instance you can
open `/nix/store/p3s2psd8a6ni37q1ysagjdarvi7cwkcn-user-environment/bin/nvim` with nvim and look for the vimrc etc.

I forked nixpkgs and modified the neovim code so you should see something different, but jst to give you an idea:
```
#! /nix/store/z4ajipns0l1s8b2lrgpy6nng4cys7h99-bash-4.4-p23/bin/bash -e
export NVIM_SYSTEM_RPLUGIN_MANIFEST='/nix/store/i40bz9kqcalwdpkz3gbf3sv547zskvf1-neovim-official-master/rplugin.vim'
exec -a "$0" "/nix/store/i40bz9kqcalwdpkz3gbf3sv547zskvf1-neovim-official-master/bin/.nvim-wrapped"  --cmd "source /nix/store/6dvf93ph3farqzj1vfa87kwv8hrmlhwk-init.vim" "$@"

```

**Comment by onny** [comment]
Oh you're right, there is something in it: ``bat /nix/store/p3s2psd8a6ni37q1ysagjdarvi7cwkcn-user-environment/bin/nvim -p``
```
#! /nix/store/715fljdrspphbdk255r729zxp4w7lcgk-bash-4.4-p23/bin/bash -e
export PATH=$PATH${PATH:+':'}'/nix/store/ji54l2nysbk17r4jm6djcdb4gi10f1v9-neovim-ruby-env/bin'
export GEM_HOME='/nix/store/ji54l2nysbk17r4jm6djcdb4gi10f1v9-neovim-ruby-env/lib/ruby/gems/2.6.0'
exec "/nix/store/x74imf48c7gv20mzm5i9hhzhc3h46g9m-neovim-unwrapped-0.4.3/bin/nvim"   --cmd "let g:loaded_node_provider=1" --cmd "let g:python_host_prog='/nix/store/xvp294mmp5rhbzqywnby48pig59f8qdy-neovim-0.4.3/bin/nvim-python'" --cmd "let g:python3_host_prog='/nix/store/xvp294mmp5rhbzqywnby48pig59f8qdy-neovim-0.4.3/bin/nvim-python3'" --cmd "let g:ruby_host_prog='/nix/store/xvp294mmp5rhbzqywnby48pig59f8qdy-neovim-0.4.3/bin/nvim-ruby'"  "$@"
```

**Comment by teto** [comment]
There should be a `-u /nix/store/generated-vimrc` which means there is a problem with home-manager. Look at neovim options in `man home-configuration.nix`, you can try to set `programs.neovim.extraConfig` instead of configure. I have longstanding changes for neovim I would like to submit to nixpkgs soon.

**Comment by teto** [comment]
do yo ustill have the issue ?
