### ISSUE TITLE
Missing zsh completion for `home-manager` itself

### ISSUE THREAD

**Issue by oxalica** [nix-community/home-manager#1075]
The tab-completion works on bash, but doesn't work on zsh.
It simply suggests files in CWD (the default completion).

**Comment by Sean1708** [comment]
If it's useful to anyone, I wrote my own [here](https://gitlab.com/seamsay/nix-configuration/-/blob/334d6fb6a1102fbc29fc0c6207b21711c39e3ce3/home/zsh.nix#L19-74) a while ago.

**Comment by oxalica** [comment]
@Sean1708 
Seems great. Would you mind sending an PR here?

**Comment by Sean1708** [comment]
I'm not really sure how I'd go about testing that the installation works properly without creating an entirely new user account, but feel free to take the code and submit the PR yourself or you can use my method of doing it until somebody more knowledgeable about testing HM itself comes along.
