### ISSUE TITLE
systemd: permit duplicate attributes in services

### ISSUE THREAD

**Issue by dominikh** [nix-community/home-manager#1083]
Options in systemd services needn't be unique. For example, a service can have multiple `ExecStartPost` options, with one command per option. Systemd will execute all commands.

However, home-manager cannot currently generate such services. Attempting to use a list simply concatenates all the values to one value.

It looks like calling `lib.generators.toINI` with `listsAsDuplicateKeys = true` should support this for free, but I haven't tested that. It's also not a backwards-compatible change.

**Comment by erikarvstedt** [comment]
As a workaround, you can do
```
ExecStartPost = "cmd1 ; cmd2 ; ...";
```
Note the extra spaces surrounding the semicolons.

**Comment by sumnerevans** [comment]
Looks like this may already be implemented: https://github.com/nix-community/home-manager/blob/master/modules/systemd.nix#L18

I think you can just do: `ExecStartPost = [ "cmd1" "cmd2" ];`.
