### ISSUE TITLE
Support for starting ssh-agent?

### ISSUE THREAD

**Issue by wpcarro** [nix-community/home-manager#1087]
I cannot find anywhere in the home-manager codebase that supports starting `ssh-agent`.

I found options for configuring `gpg-agent` to emulate `ssh-agent`. For the past two days, I've experimented with this option, but for now I would rather use `ssh-agent` alone.

Does home-manager currently support users who want to use `ssh-agent` without `gpg-agent`?

**Comment by rycee** [comment]
No, I haven't heard of anybody working on ssh-agent support. I've used gpg-agent with SSH support for a long time now since I use gpg a lot anyway.

**Comment by wpcarro** [comment]
Thank you for informing me. I'll submit a PR to support `ssh-agent` and ensure that the options for enabling `ssh-agent` and `gpg-agent` are mutually exclusive.

**Comment by znewman01** [comment]
I'd love this is you're still working on it! I assume you've seen the [NixOS ssh-agent support](https://github.com/NixOS/nixpkgs/blob/3420bd63b9bbd4eb4e544b898a072c6fbbc9cfa9/nixos/modules/programs/ssh.nix#L244).

**Comment by Ericson2314** [comment]
I think this should stay open? Any user service that NixOS supplies is a smell and home-manager should do it instead.

**Comment by otopetrik** [comment]
For those trying to use `services.gpg-agent.enableSshSupport` for ssh-agent functionality, note that it does not currently implement the full functionality of `ssh-agent`.

When using `ecdsa_sk` keys (hardware U2F devices) it fails with:
```
Could not add identity "/home/nixos/.ssh/id_ecdsa_sk": agent refused operation
```
Details at https://dev.gnupg.org/T5494

**Comment by lheckemann** [comment]
I've opened #4178 implementing this.
