### ISSUE TITLE
Handle Network Manager user connections

### ISSUE THREAD

**Issue by Shou** [nix-community/home-manager#1092]
Would be sweet if we could handle Network Manager's user connections from Home Manager. I use NixOS myself so I can do it on a system level but there are use cases for people who just use Home Manager on top of a non-NixOS system to get things like WiFi, VPNs, etc set up.

**Comment by rycee** [comment]
Yup. It would be nice to have support for this. I'm unlikely to work on it for a long time, though. Might be an interesting project for some interested person 🙂
