### ISSUE TITLE
programs.emacs.package doesn't play nicely with emacs-overlay.

### ISSUE THREAD

**Issue by spacekitteh** [nix-community/home-manager#1111]
When you use programs.emacs, it uses its own `emacsWithPackages`. When you then use the package creation functions in emacs-overlay, it adds another emacsWithPackages layer. This ends up causing the install to fail, as it tries to reference unknown files.

**Comment by terlar** [comment]
This is still potentially an issue. Personally I worked around it by using `services.emacs` instead.

```
{
  services.emacs = {
    enable = true;
    package = emacsOverlayPackage;
  };
}
```
