### ISSUE TITLE
Login manager "Failed to start session" without xterm enabled

### ISSUE THREAD

**Issue by JustinLovinger** [nix-community/home-manager#1116]
On newer versions of NixOS with up to date `system.stateVersion`, without the option `services.xserver.desktopManager.xterm.enable = true;`, the login manager cannot start home-manager sessions.

XTerm is no longer the default session on NixOS.

**Comment by ardumont** [comment]
Indeed, I had to update my nixos configuration on 20.03 with this [1]
But i'm not sure that's an issue with home-manager.

Maybe an entry in the FAQ.md file could help ;)

[1] [https://github.com/ardumont/dot-files/blob/master/etc/nixos/myrkr/xsession.nix#L20-L23

**Comment by endgame** [comment]
I found that `services.xserver.desktopManager.xterm.enable = true;` sufficed.
