### ISSUE TITLE
fontconfig conflicting definitions when using nixos module

### ISSUE THREAD

**Issue by jwijenbergh** [nix-community/home-manager#1118]
When using ```fonts.fontconfig.enable = true;``` to let home manager handle fontconfig configuration, I get the following error:

```
error: The option `home-manager.users.jerry.fonts.fontconfig.enable' has conflicting definitions, in `/etc/nixos/home/home.nix' and `/nix/store/x82h5sl2gp3y48lj62pnh4ga1ln5bdx3-source/nixos'.
(use '--show-trace' to show detailed location information)
```

I am using the nixos module to import my home-manager configuration in my ```configuration.nix```, I assume this error is there because nixos has its own ```fonts.fontconfig.enable``` setting which has a different definition.

Is it possible to define my fonts in ```home.packages``` and let them still be discovered in my system? Manually running ```fc-cache -f``` is an option, but this resulted in some packages still not finding my fonts. Maybe ```fonts.fontconfig``` can be renamed in home-manager?

For completeness, [here](https://github.com/jwijenbergh/nixos-config) is my nixos configuration (```home/home.nix``` is where I want to add the fontconfig setting)

**Comment by rycee** [comment]
Actually, it is not a conflict with the NixOS `fonts.fontconfig.enable` option but rather a conflict with the assignment set in the HM NixOS module:
https://github.com/rycee/home-manager/blob/5969551a5cc52f9470b5ff5ca01327bf4bda82c1/nixos/default.nix#L25-L28

The value in the NixOS module should probably be set using `mkDefault` but for now you can add `fonts.fontconfig.enable = lib.mkForce true` as a work-around.

**Comment by jwijenbergh** [comment]
> Actually, it is not a conflict with the NixOS `fonts.fontconfig.enable` option but rather a conflict with the assignment set in the HM NixOS module:
> 
> https://github.com/rycee/home-manager/blob/5969551a5cc52f9470b5ff5ca01327bf4bda82c1/nixos/default.nix#L25-L28
> 
> The value in the NixOS module should probably be set using `mkDefault` but for now you can add `fonts.fontconfig.enable = lib.mkForce true` as a work-around.

Thanks for the quick reply!
Using ```lib.mkForce true``` works for me. I will leave this issue open in the case you want to make a change in the nixos module. You may also close this issue.
