### ISSUE TITLE
Use XDG Base Directories for newsboat configuration

### ISSUE THREAD

**Issue by splintah** [nix-community/home-manager#1124]
Currently, the newsboat module places its configuration in `~/.newsboat` ([relevant part of module](https://github.com/rycee/home-manager/blob/dd93c300bbd951776e546fdc251274cc8a184844/modules/programs/newsboat.nix#L97-L121)), but newsboat supports the XDG Base Directory Specification according to the [documentation](https://github.com/newsboat/newsboat/blob/master/doc/newsboat.asciidoc#xdg-base-directory-support). It would be nice if the newsboat module placed its configuration files in `xdg.configHome` instead.

**Comment by teto** [comment]
go ahead, gate it behind a home.stateVersion so that it doesn't randomly break user configs

**Comment by sumnerevans** [comment]
This was closed by https://github.com/nix-community/home-manager/pull/1919.
