### ISSUE TITLE
XDG user-dirs doesn't seem to be working

### ISSUE THREAD

**Issue by mtreca** [nix-community/home-manager#1159]
I tried to enable the xdg-user-dirs module, but programs do not seem to be picking it up at all (Desktop and Downloads keep being created in my home directory). I tried manually running `xdg-user-dirs` to no avail. This is the configuration I used:

```nix
    home-manager.users.vxid.xdg.userDirs = {
      enable = true;
      documents = "$HOME/usr/doc";
      download = "$HOME/tmp";
      pictures = "$HOME/usr/img";
      desktop = "$HOME";
      music = "/dev/null";
      publicShare = "/dev/null";
      templates = "/dev/null";
      videos = "/dev/null";
    };
```

[This issue](https://github.com/NixOS/nixpkgs/issues/33282) in nixpkgs does solves my issue though, but it is outside of the scope of home-manager, hence this issue.

**Comment by dmarcoux** [comment]
I have the same issue. This is my configuration. Running `xdg-user-dirs-update` does nothing.

```
  home.packages = [ pkgs.xdg-user-dirs ];

  xdg = {
    # Enable management of XDG base directories
    enable = true;
    # Enable management of user directories
    userDirs = {
      # Setup default user directories (Desktop, Documents, Downloads, Music, Pictures, Public, Templates and Videos)
      enable = true;
      # Setup extra user directories
      extraConfig = {
        XDG_AUDIO_DIR = "$HOME/Audio";
        XDG_PROJETS_DIR = "$HOME/Projets";
      };
    };
  };

  # Generate the user directories defined above with `xdg.userDirs`
  home.activation.xdg-user-dirs-update = lib.hm.dag.entryAfter ["writeBoundary"] ''
    $DRY_RUN_CMD ${pkgs.xdg-user-dirs}/bin/xdg-user-dirs-update
  '';
```

**Comment by oxalica** [comment]
It seems to be intentional, since `xdg-user-dirs-update` is for **generating a new** `user-dirs.dirs` which is now already managed by home-manager.
The code simply disable `xdg-user-dirs-update` when `xdg.userDirs.enable = true`.

https://github.com/rycee/home-manager/blob/b3bbc8b769285ea3e811bc3408c4479451608088/modules/misc/xdg-user-dirs.nix#L103

See also: https://manpages.ubuntu.com/manpages/xenial/man5/user-dirs.conf.5.html

**Comment by smaximov** [comment]
The XDG module bundled with home-manager works out of the box for me (no need to touch NixOS config or explicitly install the `xdg-user-dirs` package):

``` nix
{
  xdg = {
    enable = true;

    userDirs = {
      enable = true;
      desktop = "$HOME/desktop";
      download = "$HOME/downloads";
      documents = "$HOME/docs";
      templates = "$HOME/templates";
      music = "$HOME/media/music";
      videos = "$HOME/media/videos";
      pictures = "$HOME/media/pictures";
      publicShare = "$HOME/share/public";
    };
  };
}
```

As @oxalica said, there's no need to invoke `xdg-user-dirs-update` manually.

**Comment by mtreca** [comment]
Thank you all for the replies. I am testing your solutions now and will be reporting back.

**Comment by albakham** [comment]
I am not really sure whether it is working or not. home-manager is actually generating two files, with a config similar to @smaximov:

`.config/user-dirs.conf`, with:
```
enabled=False
```

and `.config/user-dirs.dirs`, with:
```
XDG_DESKTOP_DIR=$HOME/Bureau
XDG_DOCUMENTS_DIR=$HOME/Documents
XDG_DOWNLOAD_DIR=$HOME/Téléchargements
XDG_MUSIC_DIR=$HOME/Musique
XDG_PICTURES_DIR=$HOME/Images
XDG_PUBLICSHARE_DIR=$HOME/Public
XDG_TEMPLATES_DIR=$HOME/Modèles
XDG_VIDEOS_DIR=$HOME/Vidéos
```

It seems okay, but for example, Thunar doesn't show any specific icons on these directories (I remember it used to work), sometimes a ~/Desktop directory is created and this folder have a specific icon...

**Comment by smaximov** [comment]
> home-manager is actually generating two files, with a config similar to @smaximov:

As far as I understand, this is how it should be. `enabled=False` tells `xdg-user-dirs-update` (which is typically run on user login) not change the XDG user dirs configuration, because it's already managed by `home-manager`.

> It seems okay, but for example, Thunar doesn't show any specific icons on these directories

Sorry, I don't use Thunar. I've been using this setup for a couple of weeks and haven't had any issue so far.

**Comment by benneti** [comment]
I ran into this,too.
What helped for me was to one time overwrite the `.config/user-dirs.conf`with `enabled=True` and then launch my file manager (nautilus) and then disable it again. For some reason after this it also recognized the folders.
