### ISSUE TITLE
Configuring XDG Portals?

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#1167]
Hi. As I'm attempting to adopt home-manager, I am unsure of how to adapt my xdg portal configuration to user-specific home-manager configuration instead.

What is the user-specific HM equivalent of this?
```
    xdg.portal.enable = true;
    xdg.portal.gtkUsePortal = true;
    xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-wlr ];
```

I can try to hack on this myself, if it's just missing. Pointers appreciated, this is day 1 with H-M for me.

**Comment by worldofpeace** [comment]
Aren't xdg portals just a system service?

**Comment by colemickens** [comment]
I don't really know much about XDG Portals or how they work or how they're expected to be run. It just seems odd that I'm coordinating everything user-oriented (sway, etc) using Home-Manager, but yet this other critical part of my desktop (xdg portals, if I get them working) is configured at the system level.

But I also might be thinking about this wrong? Or just over-doing my cleanliness of separating user/hm-specific stuff?

**Comment by lobre** [comment]
Same as you @colemickens, I don't much about those underlying layers, but I also try to have a pure user-oriented configuration through home-manager (that could apply both on a NixOS or another distro).

That was working pretty well with i3 (and X), without any specific changes system-wise. But now that I also switched to sway (and Wayland), I am struggling to have the same result, especially with screen sharing.

Maybe somebody can shed light on this question? Is there a chance to have portals/Pipewire/JACK configured at the user level (through hm)? Or are there technical reasons that wouldn't allow that?

**Comment by terlar** [comment]
When I read about some details about the PipeWire they talk about it being a User service (https://wiki.archlinux.org/index.php/PipeWire). With this information I started digging into it, but didn't get it fully working yet, I wonder if it is the dbus stuff that I am missing, what I am testing is the screen-sharing. The services seem to be running, but I don't get the window where I can select the thing to share. One thing to note is that this is Ubuntu 20.04 LTS, so not sure if that is causing extra issues. Before when I had it working I was using NixOS and not the things as a user service.

Also note that this is for Gnome, but should be basically the same for the `wlr`, I guess dropping the `gnome-remot-desktop`, `gnome-shell` and `xdg-desktop-portal-gtk`, replacing the latter with `xdg-desktop-portal-wlr`.

Here is what I have so far:
```nix
{ config, pkgs, ... }:

let
  joinedPortals = pkgs.symlinkJoin {
    name = "xdg-portals";
    paths = [
      pkgs.gnome3.gnome-remote-desktop
      pkgs.gnome3.gnome-shell
      pkgs.xdg-desktop-portal-gtk
    ];
  };
in {
  home.sessionVariables = {
    GTK_USE_PORTAL = "1";
    XDG_DESKTOP_PORTAL_DIR =
      "${joinedPortals}/share/xdg-desktop-portal/portals";
  };

  home.packages = with pkgs; [
    pipewire
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    wl-clipboard
  ];

  systemd.user.services.pipewire = {
    Unit = {
      Description = "Multimedia Service";
      Requires = [ "pipewire.socket" ];
    };

    Service = {
      Type = "simple";
      Environment =
        "PIPEWIRE_CONFIG_FILE=${config.xdg.configHome}/pipewire/pipewire.conf";
      ExecStart = "${pkgs.pipewire}/bin/pipewire";
      Restart = "on-failure";
    };

    Install = {
      Also = [ "pipewire.target" ];
      WantedBy = [ "default.target" ];
    };
  };

  xdg.configFile = {
    "pipewire/pipewire.conf".text = ''
      set-prop link.max-buffers 16 # version < 3 clients can't handle more

      add-spa-lib audio.convert* audioconvert/libspa-audioconvert
      add-spa-lib api.alsa.* alsa/libspa-alsa
      add-spa-lib api.v4l2.* v4l2/libspa-v4l2
      add-spa-lib api.libcamera.* libcamera/libspa-libcamera
      add-spa-lib api.bluez5.* bluez5/libspa-bluez5
      add-spa-lib api.vulkan.* vulkan/libspa-vulkan
      add-spa-lib api.jack.* jack/libspa-jack
      add-spa-lib support.* support/libspa-support

      load-module libpipewire-module-rtkit # rt.prio=20 rt.time.soft=200000 rt.time.hard=200000
      load-module libpipewire-module-protocol-native
      load-module libpipewire-module-profiler
      load-module libpipewire-module-metadata
      load-module libpipewire-module-spa-device-factory
      load-module libpipewire-module-spa-node-factory
      load-module libpipewire-module-client-node
      load-module libpipewire-module-client-device
      load-module libpipewire-module-portal
      load-module libpipewire-module-access
      load-module libpipewire-module-adapter
      load-module libpipewire-module-link-factory
      load-module libpipewire-module-session-manager

      create-object spa-node-factory factory.name=support.node.driver node.name=Dummy priority.driver=8000

      exec ${pkgs.pipewire}/bin/pipewire-media-session
    '';

    "systemd/user/pipewire.socket".source =
      "${pkgs.pipewire}/share/systemd/user/pipewire.socket";
    "systemd/user/sockets.target.wants/pipewire.socket".source =
      "${pkgs.pipewire}/share/systemd/user/pipewire.socket";

    "systemd/user/default.target.wants/gnome-remote-desktop.service".source =
      "${pkgs.gnome3.gnome-remote-desktop}/share/systemd/user/gnome-remote-desktop.service";
    "systemd/user/gnome-remote-desktop.service".source =
      "${pkgs.gnome3.gnome-remote-desktop}/share/systemd/user/gnome-remote-desktop.service";

    "systemd/user/xdg-desktop-portal.service".source =
      "${pkgs.xdg-desktop-portal}/share/systemd/user/xdg-desktop-portal.service";
    "systemd/user/default.target.wants/xdg-desktop-portal.service".source =
      "${pkgs.xdg-desktop-portal}/share/systemd/user/xdg-desktop-portal.service";
    "systemd/user/xdg-document-portal.service".source =
      "${pkgs.xdg-desktop-portal}/share/systemd/user/xdg-document-portal.service";
    "systemd/user/default.target.wants/xdg-document-portal.service".source =
      "${pkgs.xdg-desktop-portal}/share/systemd/user/xdg-document-portal.service";
    "systemd/user/xdg-permission-store.service".source =
      "${pkgs.xdg-desktop-portal}/share/systemd/user/xdg-permission-store.service";
    "systemd/user/default.target.wants/xdg-permission-store.service".source =
      "${pkgs.xdg-desktop-portal}/share/systemd/user/xdg-permission-store.service";

    "systemd/user/xdg-desktop-portal-gtk.service".source =
      "${pkgs.xdg-desktop-portal-gtk}/share/systemd/user/xdg-desktop-portal-gtk.service";
    "systemd/user/graphical-session.target.wants/xdg-desktop-portal-gtk.service".source =
      "${pkgs.xdg-desktop-portal-gtk}/share/systemd/user/xdg-desktop-portal-gtk.service";
  };
}
```

**Comment by berbiche** [comment]
`xdg-desktop-portal-wlr` won't work on Gnome because it's the wlroots implementation of `xdg-desktop-portal`.

**Comment by terlar** [comment]
The example was specifically for GNOME and not using wlr. However I still didn’t get it fully working at the time. But I believe it is not that far off. And if we get it working it should be working with the wlr version as well.

I will probably look into this when I have some time.

**Comment by mightyiam** [comment]
I'd be willing to pair up if anyone who knows more about these technologies than me is interested.

**Comment by bb010g** [comment]
Could this be reopened?

**Comment by sjcobb2022** [comment]
Any luck with this? I've been transferring my hyprland config to nixOS and this is a bit of a blocker. Pipewire has been fairing fine, however Hyprland recommends use xdg-desktop-portal-hyprland, and it's a bummer that I can't configure it in home-manager.

I _was_ able to get it running on the system level, by setting `xdg.extraPortals` in my main config.

**Comment by Misterio77** [comment]
With the new 1.18 version, it is now much easier to configure it through the user env only. I have an MVP on my dots right now, will polish it and open up a PR later today!
