### ISSUE TITLE
feature request: sway keybindings should support --locked

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#1176]
Sway allows keybindings to work on the lock screen if they are specified with `--locked`.

This is important for me because sometimes I grab my laptop and walk away, possibly with all outputs disabled, possibly with swaylock active. For now I can switch to a TTY and kill swaylock, of course, so it's not a big deal.

**Comment by billop** [comment]
`bindsym` has many other options that are useful, I feel like they should all be supported really. I don't like having to use `extraConfig` anytime I want to use `bindsym` with a flag.

**Comment by regnat** [comment]
Fwiw it's “supported” (note the quotes though :wink:) in that you can do for example `wayland.windowManager.sway.keybindings."--locked XF86AudioPlay" = "exec ${pkgs.playerctl}/bin/playerctl play-pause";`

**Comment by berbiche** [comment]
I have a PR (not yet completed) that would allow using flags while retaining the default values.

A keybinding would become `"my-key" = { flags = [ "--locked" ]; value = "exec something" };`.

I still have to figure out how to properly support the current recommended way of using the default keybindings (`lib.mkDefault`) while not introducing a breaking change and to allow using the default keybindings with additional flags.

**Comment by sumnerevans** [comment]
@berbiche did you ever figure out a way to implement the `flags` attribute for keybindings?

**Comment by berbiche** [comment]
> @berbiche did you ever figure out a way to implement the `flags` attribute for keybindings?

@sumnerevans 
Nope, I couldn't find a way to make this work while remaining backward compatible.
The solution would need
- to work with `mkDefault` (per the docs) to allow users to reuse the default keybinding while adding their own keybinding
- to support removing a default keybinding by setting it to null
- to allow adding flags to a preexisting binding
- to remove flags `mkForce []`

The only solution that I could think of at the time was writing my own type to support these features (which means handling value merging, etc.).
It was too complex so I stopped working on a backward solution.

My work can be found on my `sway-i3-keybinding` branch: https://github.com/berbiche/home-manager/commits/sway-i3-keybindings
