### ISSUE TITLE
`.zshrc` is not sourced correctly because of symlinks

### ISSUE THREAD

**Issue by piegamesde** [nix-community/home-manager#1199]
When I set `dotDir = ".config/zsh";`, the `.zshrc` won't load anymore. I tracked it down to the following: `source .zshrc` doesn't work for some reason depending on the location of the directory it is in. So sourcing `~/.zshrc` works, but `~/.config/zsh/.zshrc/` doesn't.

What I mean with "doesn't work": I mainly tested for aliases and custom functions. Things like themes and plugins seem to work nevertheless.

**Comment by piegamesde** [comment]
After some further testing, sourcing `.zshrc` doesn't fully work depending on the symlink chain that points to the file and the name of the file that is sourced:

- `~/.zshrc -> /nix/store/home-manager-files/.zshrc -> /nix/store/hm_.zshrc` doesn't work
- `~/.zshrc -> /nix/store/hm_.zshrc` works
- `~/.zshrc2 -> /nix/store/home-manager-files/.zshrc -> /nix/store/hm_.zshrc` works (!)

**Comment by piegamesde** [comment]
I think this may be caused by #1088

**Comment by uvNikita** [comment]
I also have `dotDir = ".config/zsh";` in my personal config, with custom aliases and function and it works as it should.

Note that if you change dotDir parameter, you don't really need `~/.zshrc` or, rather, it should be here instead: `~/.config/zsh/.zshrc`. You should only have `~/.zshenv` file in your home directory with the content that looks similar to this:
```
source $HOME/.config/zsh/.zshenv
```

The rest of zsh configuration should reside in `~/.config/zsh`
