### ISSUE TITLE
A small lack of uniformity among options with similar purpose (settings VS extraConfig)

### ISSUE THREAD

**Issue by AndersonTorres** [nix-community/home-manager#1200]
Hello, people!

Well, it isn't a serious bug per se, but I think it can be a bit illogical because of lack of uniformity.

There are those two lines. 

- The configuration options in rtorrent are called "settings"

  https://github.com/rycee/home-manager/blob/115e76ae12a81bce5dcd19714cdeaaa8d5ca3ce8/modules/programs/rtorrent.nix#L15

  The same in neomutt, noti, password-store, qutebrowser, starship, vim, dunst, xscreensaver, etc.

- The configuration options in sway are called extraConfig

  https://github.com/rycee/home-manager/blob/8c920682e6ed3b0c6cc86c85741f8d4d8c03fb59/modules/services/window-managers/i3-sway/sway.nix#L368

This way, it can be a bit confusing: "Is it sway settings or config the name of that option?"

If they had the same naming, as "extraConfig", it would lessen the mental burden. Setting it as a rule would help the users to remember "well, I need to configure this, then I will just use extraConfig".

Thanks in advance, and sorry my bad English.

**Comment by iv-nn** [comment]
I think `settings` is meant to be a nix attribute set, which is then formatted to the program configuration syntax, whereas `extraConfig` is just a bunch of strings in the configuration syntax directly appended to the config.

`extraConfig` should be of type `lines` and `settings` should be of type `attrs`, `attrsOf` or `submodule`.

So probably `rtorrent`'s `settings` should be called `extraConfig` and `notmuch`'s `extraConfig` should be called `settings` the rest of your examples are fine but I didn't check every modules. I don't know if this is worth breaking people configuration, maybe with a deprecation warning.

For further reading: [RFC 42](https://github.com/NixOS/rfcs/pull/42).

**Comment by duardo345** [comment]
U

**Comment by AndersonTorres** [comment]
As I am not a user of HM anymore, I have no interest here. Therefore I will close it.
