### ISSUE TITLE
Document Development Environment

### ISSUE THREAD

**Issue by poelzi** [nix-community/home-manager#1215]
Please document how a checkout of home-manager can be used instead of channels.

It is not easy to start hacking on home-manager if you can't get it running without channels.

**Comment by rycee** [comment]
Did you check the [contribution guidelines](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#fork-and-create-a-pull-request)? If so, could you describe a bit what was unclear about it and we'll see about improving it for the future.

**Comment by frankie131310** [comment]
I humble myself to you positive enrgy and talk to me
