### ISSUE TITLE
Picom not starting automatically

### ISSUE THREAD

**Issue by b1ackshadow** [nix-community/home-manager#1217]
I am using unstable channels for both hm and nixpkgs.
This is my picom config 
`services.picom= {
    enable = true;
    inactiveOpacity = "0";
    activeOpacity = "1";#"0.90";
    opacityRule = [ "100:class_g = 'Google-chrome'" "100:class_g = 'Alacritty'" "60:class_g = 'rofi'"];
    fade = true;
    vSync = true;
    shadow = true;
    fadeDelta = 4 ;
    fadeSteps = ["0.02" "0.02"];
    blur = true;
    backend = "glx";
    inactiveDim = "0.2";
    extraOptions = ''
        frame-opacity = 1;
        blur-background = true;
        blur-kern = "7x7box";
        blur-background-exclude = [];
    '';
  };
`
Picom is not starting automatically like it was used to.

**Comment by lobre** [comment]
I also have the same behavior. @b1ackshadow, do you still see this problem?

**Comment by 06kellyjac** [comment]
Could you run `systemctl --user status picom.service`? Just the config alone isn't much to go off of.

---

Also I've tried to format your nix to make it a bit easier to read. Does this look right?

```nix
{ pkgs, ... }:

{
  services.picom = {
    enable = true;
    inactiveOpacity = "0";
    activeOpacity = "1"; #"0.90";
    opacityRule = [ "100:class_g = 'Google-chrome'" "100:class_g = 'Alacritty'" "60:class_g = 'rofi'" ];
    fade = true;
    vSync = true;
    shadow = true;
    fadeDelta = 4 ;
    fadeSteps = ["0.02" "0.02"];
    blur = true;
    backend = "glx";
    inactiveDim = "0.2";
    extraOptions = ''
      frame-opacity = 1;
      blur-background = true;
      blur-kern = "7x7box";
      blur-background-exclude = [];
    '';
  };
}
```

**Comment by lobre** [comment]
It does not give much info.

```
$ systemctl --user status picom.service
● picom.service - Picom X11 compositor
   Loaded: loaded (/nix/store/bbzk76iphmcp63irkywrjvih379mcaiz-picom.service/picom.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2020-09-08 12:43:21 CEST; 7s ago
  Process: 5007 ExecStart=/nix/store/bl6mmjfjp61r6l6xz0wn44w000yy3d7l-picom/bin/picom --config /nix/store/gim8hlcxvj928yrbqvzbjvkbgjca1wly-picom.conf (code=killed, signal=TERM)
 Main PID: 5007 (code=killed, signal=TERM)

Sep 08 12:43:21 ncyl3168-linux systemd[3005]: Started Picom X11 compositor.
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: Stopping Picom X11 compositor...
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: Stopped Picom X11 compositor.
```

Otherwise, here is the output of `journalctl --user -u picom.service --since today`

```
Sep 08 12:40:47 ncyl3168-linux systemd[3005]: Started Picom X11 compositor.
Sep 08 12:40:48 ncyl3168-linux picom[3503]: [ 08/09/20 12:40:48.500 win_clear_flags WARN ] Flags cleared on a destroyed window 0x0020006f ([i3 con] container around 0xc99bb0)
Sep 08 12:41:29 ncyl3168-linux picom[3503]: [ 08/09/20 12:41:29.074 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00200074 ([i3 con] container around 0xc9d0a0)
Sep 08 12:41:35 ncyl3168-linux picom[3503]: [ 08/09/20 12:41:35.600 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00200098 ([i3 con] container around 0xd64800)
Sep 08 12:43:11 ncyl3168-linux picom[3503]: [ 08/09/20 12:43:11.103 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00200093 ([i3 con] container around 0xd70f60)
Sep 08 12:43:14 ncyl3168-linux picom[3503]: [ 08/09/20 12:43:14.338 win_clear_flags WARN ] Flags cleared on a destroyed window 0x002000a6 (Re: [rycee/home-manager] Picom not starting
Sep 08 12:43:15 ncyl3168-linux picom[3503]: [ 08/09/20 12:43:15.530 x_fetch_region ERROR ] Failed to fetch rectangles (No error)
Sep 08 12:43:15 ncyl3168-linux picom[3503]: X connection to :0 broken (explicit kill or server shutdown).
Sep 08 12:43:15 ncyl3168-linux systemd[3005]: picom.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 12:43:15 ncyl3168-linux systemd[3005]: picom.service: Failed with result 'exit-code'.
Sep 08 12:43:18 ncyl3168-linux systemd[3005]: picom.service: Service hold-off time over, scheduling restart.
Sep 08 12:43:18 ncyl3168-linux systemd[3005]: picom.service: Scheduled restart job, restart counter is at 1.
Sep 08 12:43:18 ncyl3168-linux systemd[3005]: Stopped Picom X11 compositor.
Sep 08 12:43:18 ncyl3168-linux systemd[3005]: Started Picom X11 compositor.
Sep 08 12:43:18 ncyl3168-linux picom[4975]: [ 08/09/20 12:43:18.800 main FATAL ERROR ] Can't open display.
Sep 08 12:43:18 ncyl3168-linux systemd[3005]: picom.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 12:43:18 ncyl3168-linux systemd[3005]: picom.service: Failed with result 'exit-code'.
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: picom.service: Service hold-off time over, scheduling restart.
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: picom.service: Scheduled restart job, restart counter is at 2.
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: Stopped Picom X11 compositor.
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: Started Picom X11 compositor.
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: Stopping Picom X11 compositor...
Sep 08 12:43:21 ncyl3168-linux systemd[3005]: Stopped Picom X11 compositor.
```

**Comment by 06kellyjac** [comment]
Nothing obvious pops out. Maybe try using picom with the default config? (e.g. just do `picom.enable = true;`, nothing else)
Also maybe try patch in the `--show-all-xerrors` & `--log-level TRACE` flags to get more detailed logs? (I don't think these can be set with the config file, need to be cli args AFAIK.

**Comment by lobre** [comment]
Thanks for the ideas. I have tried to add these options into the `extraOptions` and they seem to be applied. But nothing interesting happens.

In fact, it seems the service does not even try to start at boot because there is no log at all in `journalctl` until I try to start the service manually.

Maybe the problem is not really caused by picom but maybe by the user systemd. I need to dig more.

**Comment by 06kellyjac** [comment]
`extraOptions` writes to your config file. I dont think those options work in the file.
https://github.com/nix-community/home-manager/blob/master/modules/services/picom.nix#L50

**Comment by lobre** [comment]
Yes, but they do work in the configuration file apparently.

E.g. https://github.com/yshui/picom/blob/c4369ec756d3f7bdc1f3110ade32c89959c99a98/picom.sample.conf#L354

**Comment by 06kellyjac** [comment]
Ah nice.

Have you had any luck running the same command as the systemd service manually?

**Comment by lobre** [comment]
I did, and it worked successfully. So that's why I am not sure the problem is directly related to picom itself.

Because it is just the service that does not start. If I start it manually, or if I launch the exec command in the service, everything runs smoothly.

**Comment by lobre** [comment]
Still having the issue but as of now, I am quick fixing it by launching `systemctl --user restart picom.service` within the startup section of my i3wm.

**Comment by guillermofbriceno** [comment]
I'm having the same issue. Currently trying to get it working with just `services.picom.enable = true` but the service is still not starting automatically. 

`journalctl --user -u picom.service --since today` (same thing over and over):
```
May 01 14:49:43 prelude picom[12863]: [ 05/01/2021 14:49:43.946 main FATAL ERROR ] Can't open display.
May 01 14:49:43 prelude systemd[971]: picom.service: Main process exited, code=exited, status=1/FAILURE
May 01 14:49:43 prelude systemd[971]: picom.service: Failed with result 'exit-code'.
May 01 14:49:44 prelude systemd[971]: Stopped Picom X11 compositor.
```

If I run `systemctl --user status picom.service` right after boot:
```
● picom.service - Picom X11 compositor
     Loaded: loaded (/nix/store/lvx67hxwsjy8g8n4q7n2797a6kmpsk9x-home-manager-files/.config/systemd/user/picom.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
```

Unlike @lobre, running `systemctl --user start picom.service` does not work for me. Another `systemctl --user status picom.service` after that shows:
```
● picom.service - Picom X11 compositor
     Loaded: loaded (/nix/store/lvx67hxwsjy8g8n4q7n2797a6kmpsk9x-home-manager-files/.config/systemd/user/picom.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2021-05-01 14:57:01 MDT; 1s ago
    Process: 2280 ExecStart=/nix/store/4fg4js6nwplkf0x8fq2zwwvxn3a0hvrq-picom-8/bin/picom --config /nix/store/wplbz2q9bp5syxjifwwbaxqkalv91h6w-picom.conf (code=exited, status=1/FAILURE)
   Main PID: 2280 (code=exited, status=1/FAILURE)
```

The weird thing is manually running the command systemd uses works fine with no errors: `/nix/store/4fg4js6nwplkf0x8fq2zwwvxn3a0hvrq-picom-8/bin/picom --config /nix/store/wplbz2q9bp5syxjifwwbaxqkalv91h6w-picom.conf `

**Comment by berbiche** [comment]
@guillermofbriceno 
The downside of starting a service as a systemd unit is that environment variables exposed to the executable are those available in the user systemd session.

As can be seen in the log, picom cannot connect to the X display which hints that the DISPLAY environment variable is missing.
The "solution" is to run `systemcl --user import-environment XAUTHORITY DISPLAY` as early as possible in your user's session.

Graphical applications like picom are typically bound to `graphical-session.target` in their systemd service. This target has to be explicitly started (typically using `systemctl --user start graphical-session.target` or starting another target bound to `graphical-session.target`).

**Comment by guillermofbriceno** [comment]
@berbiche adding `systemcl --user import-environment XAUTHORITY DISPLAY` at startup worked. Thanks.
