### ISSUE TITLE
How exactly does the mimeApps system work?

### ISSUE THREAD

**Issue by loewenheim** [nix-community/home-manager#1220]
It might be that this isn’t actually a problem with `home-manager`, but that I’m misunderstanding something about the whole `mime` infrastructure in general. Here’s what the relevant section of my `home.nix` says:
```
xdg.mimeApps = {
  enable = true;
  associations.added = { "application/pdf" = [ "mupdf.desktop" "evince.desktop" ]; };
  associations.removed = { "application/pdf" = "calibre-ebook-viewer.desktop"; };
  defaultApplications = { "application/pdf" = "evince.desktop"; };
};
```

The removed association is because I want my system to stop trying to open pdfs with `calibre`. As a result, `.config/mimeapps.list` contains
```
[Added Associations]
application/pdf=mupdf.desktop;evince.desktop

[Default Applications]
application/pdf=evince.desktop

[Removed Associations]
application/pdf=calibre-ebook-viewer.desktop
```
But `xdg-mime query default "application/pdf"` says `okular-2.desktop`, even though `okular` isn’t even installed, and `xdg-open <some pdf file>` results in it getting opened in `calibre`.

**Comment by terlar** [comment]
That should work, if I remember correctly the xdg mime stuff can have other files as well, perhaps some application you have added have added a file that is preferred. Perhaps you have a `desktop-mimeapps.list` where `desktop` is your `XDG_CURRENT_DESKTOP`. There might also be `defaults.list`, see:
https://wiki.archlinux.org/index.php/XDG_MIME_Applications

For me this works:
```
λ rg -A6 mimeApps config/home/common.nix
34:  xdg.mimeApps = {
35-    enable = true;
36-    defaultApplications = {
37-      "x-scheme-handler/mailto" = "emacsmail.desktop";
38-      "application/pdf" = "emacsclient.desktop";
39-    };
40-  };
λ cat ~/.config/mimeapps.list
[Added Associations]

[Default Applications]
application/pdf=emacsclient.desktop
application/xhtml+xml=org.qutebrowser.qutebrowser.desktop
text/html=org.qutebrowser.qutebrowser.desktop
text/xml=org.qutebrowser.qutebrowser.desktop
x-scheme-handler/ftp=org.qutebrowser.qutebrowser.desktop
x-scheme-handler/http=org.qutebrowser.qutebrowser.desktop
x-scheme-handler/https=org.qutebrowser.qutebrowser.desktop
x-scheme-handler/mailto=emacsmail.desktop

[Removed Associations]
λ xdg-mime query default application/pdf
emacseditor.desktop
```
