### ISSUE TITLE
can not sign with gpg

### ISSUE THREAD

**Issue by ZerataX** [nix-community/home-manager#1240]
As I mentioned in https://github.com/rycee/home-manager/issues/908#issuecomment-627356608
I am currently unable to use gpg to sign anything. 
I first noticed this when I wanted to create a signed commit:
```console
$ git commit -S -m "test"
error: gpg failed to sign the data
fatal: failed to write commit object
```
So I tried to do a clearsign:
```console
$ gpg --clearsign test.txt 
gpg: using "44F7B7979D3A27B189E0841E8333735E784DF9D4" as default secret key for signing
gpg: signing failed: End of file
gpg: test.txt: clear-sign failed: End of file
```
Which apparently according to the arch wiki seems to be related to pinentry.

I tried to reload the gpg-agent with:
```console
$ gpg-connect-agent reloadagent /bye
OK
```
And tried to enabled services.gpg-agent in my home-manager configuration all of which didn't change anything. I don't have anything related to gpg in my nixos configuration.

Next I tried to set different pinentry flavors, since I read that while apparently the default is now pinentry-gtk2, pinentry-gnome could cause the exact problem I am dealing with.

I did this with first with:
```nix
{
  services.gpg-agent = {
    enable = true;
    extraConfig = ''
      pinentry-program ${pkgs.pinentry-curses}/bin/pinentry-curses
    '';
  };
}
```
And then with `pinentryFlavor`, but that also didn't help.

This is currently in my home.nix:
```nix
{
programs.gpg = {
  enable = true;
  settings = {
    default-key = "44F7B7979D3A27B189E0841E8333735E784DF9D4";
  };
};

services.gpg-agent = {
  enable = true;
  defaultCacheTtl = 36000;
  maxCacheTtl = 36000;
  defaultCacheTtlSsh = 36000;
  maxCacheTtlSsh = 36000;
  enableSshSupport = true;
  pinentryFlavor = "curses";
};  
}
```

Using gtk2 or gnome instead of curses also didn't fix it.

**Comment by melg8** [comment]
I've encountered same issue.

**Comment by ratsclub** [comment]
I have the exact same issue, but for some reason it works on emacs and after putting my password through emacs it works as expected,

**Comment by ian-h-chamberlain** [comment]
I have a very similar problem on a headless system (trying to use `pinentry-curses`), although in my case this works:
```sh
printf 'test' | gpg --clearsign
```

However I still see the error when committing:
```
error: gpg failed to sign the data
fatal: failed to write commit object
```
which makes me think that it's more of a git <-> gpg integration issue than related to pinentry.

**Comment by ZerataX** [comment]
Not sure when exactly, but this seems to be resolved for me. will edit this post later with the versions it works for me.

**Comment by berbiche** [comment]
@ZerataX Is the issue at hand resolved?

The option https://nix-community.github.io/home-manager/options.html#opt-services.gpg-agent.pinentryFlavor to set the pinentry program to use was merged months ago.

**Comment by dtomvan** [comment]
Is there a workaround for this? I'm experiencing the same error in git, and `gpg --clearsign` fails with:
```
gpg: signing failed: No pinentry
gpg: [stdin]: clear-sign failed: No pinentry```

I do have `gnupg`, `pinentry` in my `home.packages` and `programs.git` contains:
```
  programs.git = {
    enable = true;
    package = pkgs.gitAndTools.gitFull;
    delta = { enable = true; };
    signing = {
       key = "7A984C8207ADBA51";
       signByDefault = true;
    };
    userEmail = "18gatenmaker6@gmail.com";
    userName = "Tom van Dijk";
    extraConfig = {
<...>
```
