### ISSUE TITLE
Installing zsh plugins from nixpkgs

### ISSUE THREAD

**Issue by ShrykeWindgrace** [nix-community/home-manager#1251]
Hi!

I am trying to install a zsh plugin from nixpgs (`nixpkgs.zsh-fast-syntax-highlighting`) via `programs.zsh.plugins = [ nixpkgs.zsh-fast-syntax-highlighting ]` in my home.nix.

Upon switch, however, I get the following error:

```console
The option `programs.zsh.plugins.[definition 1-entry 1].__ignoreNulls' defined in `$HOME/.config/nixpkgs/home.nix' does not exist.
```
If I install this plugin via `plugins = [{name= "..."; src = "..."; sha256= "..."; rev ="...";}];` the installation and .zshrc generation seems ok.

Is there a way to pull this (and other) plugin directly from nixpkgs? Maybe I am just missing something in my configuration? I admit that my knowledge of nix is quite limited=)

Setup: Ubuntu18 as base system, home-manager from master, nixpkgs-unstable.

**Comment by uvNikita** [comment]
It would be nice to support plugins from nixpkgs, but it the meantime you can try to use something like this:

```
  programs.zsh.plugins = [
      {
        name = "zsh-fast-syntax-highlighting";
        src = "${nixpkgs.zsh-fast-syntax-highlighting}/share/zsh/site-functions";
      }
  ];
```

**Comment by ShrykeWindgrace** [comment]
@uvNikita Indeed, this trick works. In this particular case, however, I had to write it as
```nix
programs.zsh.plugins = [
      {
        name = "fast-syntax-highlighting";
        src = "${nixpkgs.zsh-fast-syntax-highlighting}/share/zsh/site-functions";
      }
  ];
```
Note the diff in `name` attribute. I do not know why it is like this, maybe `name` should be equal to `repo`, not to `pname`?
