### ISSUE TITLE
home-manager 20.03 seems to bork vscode extension paths

### ISSUE THREAD

**Issue by chessai** [nix-community/home-manager#1260]
if i have any extensions whatsoever, the build fails. example with bbenoist.Nix:

```
...
extensions = with pkgs.vscode-extensions; [
  bbenoist.Nix
];
...
```

```
sudo nixos-rebuild switch
...
error: opening directory '/nix/store/zhw3nfbja303q0xcnyhz1bqalzjs5m8i-vscode-extension-bbenoist-Nix-1.0.1/share/vscode/extensions': No such file or directory
(use '--show-trace' to show detailed location information)
```

The home-manager that i am pulling is:

```
https://github.com/rycee/home-manager/archive/release-20.03.tar.gz
```

**Comment by chessai** [comment]
I am not a regular vscode user, just use it sometimes for work when i need to do typescript. however i am really interested in the new haskell IDE stuff. is there anything i can do to help move this along?

**Comment by rycee** [comment]
Unfortunately I imagine the fastest path to resolving this issue would be to create a PR. I imagine it shouldn't be too hard, just to change some strings in the `vscode.nix` file.

**Comment by chessai** [comment]
Yes, I know it would take a PR. I don't think I was clear. I don't
understand the underlying issue, so I am more asking for pointers on how to
debug the issue myself.

**Comment by teto** [comment]
still an issue ?

**Comment by wmertens** [comment]
I think this is still an issue, see https://github.com/NixOS/nixpkgs/issues/83288

**Comment by wmertens** [comment]
It seems that the problem might be resolved by using the vscode-with-extensions package instead of the current ad-hoc extensions solution, as described at https://nixos.wiki/wiki/Vscode#Managing_extensions
