### ISSUE TITLE
systemd.user.services.<name>.description type error

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [nix-community/home-manager#1263]
The command `nix-shell '<home-manager>' -A install` will give me this strange error : https://gist.github.com/SCOTT-HAMILTON/4b1895bf6b72b641d9683d167d8c056b

Here is the concerned module : https://github.com/SCOTT-HAMILTON/nur-packages-template/blob/master/modules/day-night-plasma-wallpapers.nix#L33

**Comment by SCOTT-HAMILTON** [comment]
And here is the home.nix https://gist.github.com/SCOTT-HAMILTON/a82bb8a0d93c208c744898cfb07973e9

**Comment by rycee** [comment]
The `day-night-plasma-wallpapers.nix` file looks like a NixOS module, not a Home Manager one. The [`systemd.user.services`](https://rycee.gitlab.io/home-manager/options.html#opt-systemd.user.services) option in Home Manager is just a direct representation of a systemd INI service file.

**Comment by SCOTT-HAMILTON** [comment]
Same error with this home-manager module : https://github.com/SCOTT-HAMILTON/nur-packages-template/blob/master/modules/day-night-plasma-wallpapers-home-manager.nix

**Comment by SCOTT-HAMILTON** [comment]
The error is the same but with systemd.user.timers.<name>.enable https://termbin.com/866x

**Comment by rycee** [comment]
Please don't use a paste bin for short messages. It's a hassle having to go to some random website just to look at a few lines of text.

The error is

```
error: The option value `systemd.user.timers.day-night-plasma-wallpapers.enable' in `/home/scott/.config/nixpkgs/home.nix' is not of type `attribute set of boolean or signed integer or string or list of boolean or signed integer or stringss'.
(use '--show-trace' to show detailed location information)

There are 111 unread and relevant news items.
Read them by running the command 'home-manager news'
```

which seems to suggest you are trying to assign something to

```
systemd.user.timers.day-night-plasma-wallpapers.enable
```

which will not work with Home Manager. That looks like something you would write in NixOS.

**Comment by SCOTT-HAMILTON** [comment]
I guess it's fixed as my home-manager now works, I don't remember what I did. Thanks anyway.
