### ISSUE TITLE
`services.lorri.enable` creates a service that doesn't see my channels

### ISSUE THREAD

**Issue by NobbZ** [nix-community/home-manager#1265]
The `lorri daemon` started through the created service uses the systems channel (20.03) rather than my users (unstable).

If though I temporarily disable the systemd managed `lorri daemon` and start one in a shell, this deamon uses the correct channel.

**Comment by Kloenk** [comment]
Do you mean nixpkgs channel? Did you see the option `home-manager.useGlobalPkgs` under nixos? or are you not using nixos?

**Comment by NobbZ** [comment]
I'm on nixOS, though manage my HM "per user" in `home.nix`, not as a module in my `configuration.nix`.

**Comment by NobbZ** [comment]
And yes, I'm talking about `nixpkgs` channel.

Under "normal" circumstances I access the systems channel as `nixos`, the users channel as `nixpkgs`. `nix-channels --list` doesn't even tell me anything about the `nixos` one:

```plain
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixos-unstable
```

**Comment by Kloenk** [comment]
Could you please try to exchange your home-manager with this one? `https://github.com/kloenk/home-manager/archive/lorri-env.tar.gz`. Maybe that will work

**Comment by rycee** [comment]
I imagine this is related to `NIX_PATH` not being imported into the systemd user session. You can try adding

```
systemd.user.services.lorri.Service.Environment = [ "NIX_PATH=…" ];
```

where `…` is the output of `echo $NIX_PATH` in a shell.

**Comment by Kloenk** [comment]
You could of course directly set it in the `home.nix file`, I forgot. my patched home-manager version does the same.

To make in dynamic (and impure) you can use `${builtins.getEnv "NIX_PATH"}` as the `NIX_PATH`

**Comment by NobbZ** [comment]
Thanks, adding to `systemd.user.services.lorri.Service.Environment` seems to do the trick.

Perhaps this can be abstracted behind another option?

**Comment by Kloenk** [comment]
A own option for this would be great. It would not destroy the current setting of the environment, and also we could default to a sane option like the default path of channels. This would make it all pure, if we don't have to use builtins.readEnv. Will see if a have the time to create a PR.

 Are there other services which needs this environment variable? Then we should make it a global option

**Comment by rycee** [comment]
I suspect the best solution would be set `NIX_PATH` using PAM instead of in the shell, which would avoid the need for a lorri specific solution. The NixOS setup does set it with PAM it omits the `~/.nix-defexpr/channels` directory for some reason and only includes the system level ones.

Alternatively, I think one could use [environment.d](https://www.freedesktop.org/software/systemd/man/environment.d.html).

**Comment by Kloenk** [comment]
Is PAM forwarded into systemd?

**Comment by PierreR** [comment]
To use the `systemd.user.services.lorri.service.environment` workaround do I need to patch the lorri service module locally  (by copy/pasting it) ?

**Comment by PierreR** [comment]
Anyhow, doing so, works for me.
That issue hit me hard ... My overlays defined in NIX_PATH was silently ignored in Lorri ...

**Comment by PierreR** [comment]
@rycee Do you thing a PR to pass the NIX_PATH as a parameter to modules/services/lorri.nix would be useful ?

**Comment by Kloenk** [comment]
> @rycee Do you thing a PR to pass the NIX_PATH as a parameter to modules/services/lorri.nix would be useful ?

I think it is a better approach to run `systemctl --user set-environment NIX_PATH=$NIX_PATH` somewhere, so this config is not set into the nix store.

**Comment by rycee** [comment]
@Kloenk Yeah, I believe PAM sets the environment variables before the systemd user session starts. You should see the values it sets by running

```console
$ systemctl --user show-environment | grep NIX_PATH
```

So I suspect the best course of action would be to see why NixOS doesn't add the user's channels to `NIX_PATH` using PAM. And for non-NixOS users to see if it would work to set up `NIX_PATH` using `pam.sessionVariables`.

**Comment by DamienCassou** [comment]
@rycee I tried what you suggest but it fails:

```session
$ systemctl --user show-environment | grep NIX_PATH
NIX_PATH=/home/cassou/.nix-defexpr/channels

$ cat ~/.pam_environment 
NIX_PATH OVERRIDE="/home/cassou/Documents/projects/nix-system"
```
