### ISSUE TITLE
i3/sway run checks and support variable declaration ?

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#1273]
I've tried updating my i3 configuration in order to use sway. 

1/ As a first remark I used many i3 variables and beceause extraConfig is appended, sway could not use the variables (they need to be defined before use apparently). One can use nix variables instead. Alternatively we could add a "config.variables" section (feel free to ignore).

2/ Also, I ended up running `sway -C` a few times. It would be nice to run `sway -C` automatically as part of the module.

**Comment by Kloenk** [comment]
Running sway -C is not supported by sway in a nix sandbox, which would be needed to run the test. See https://github.com/swaywm/sway/issues/4691
