### ISSUE TITLE
Emacs plugins not working when using emacs from unstable

### ISSUE THREAD

**Issue by dwarfmaster** [nix-community/home-manager#1300]
### Issue description

I am using home-manager with nixos-19.09. However, I needed an emacs plugin that is not yet in nixos-19.09, but is present in nixos-unstable. To use it, I set `programs.emacs.package` to `unstable.emacs`, where `unstable` is a loaded instance of nixos-unstable. Yet it is unable to find the plugin.

I could confirm in the nix repl that the package is indeed here. I believe the reason it does not find it is because in the following : 

```nix
{
  emacsPackages = let epkgs = pkgs.emacsPackagesGen cfg.package;
    in epkgs.overrideScope' cfg.overrides;
}
```

`emacsPackagesGen` is taken from `pkgs`, and not the nixpkgs tree `cfg.package` comes from. I am not sure how to fix it however.

#### Maintainer CC

@rycee @adisbladis @Jomik 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 19.09.2350.d011e474945 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(luc): `""`
 - channels(root): `"nixos-19.03.173374.3924b344254"`
 - nixpkgs: `/home/luc/.config/nixpkgs/exposed/nixpkgs`
```

**Comment by adisbladis** [comment]
1. `19.09` is unsupported (I don't know what the support matrix for home-manager looks like, but it is unsupported upstream).
It's not even guaranteed to receive security updates.

2. Either you could do something similar as we do in [the emacs overlay](https://github.com/nix-community/emacs-overlay/blob/e4e8f8fcba0b06681165f52bc6f79a8445a4143c/default.nix#L83) and override the `emacsPackagesFor` function which is the entry point for all `emacsWithPackages` variants or you could use the emacs overlay as-is.

**Comment by dwarfmaster** [comment]
I forgot to update to 20.03 🤦 I managed to work around it by using the right `emacsWithPackages` as package, so it's not really blocking. It's just that I felt the behaviour is surprising, but feel free to close the issue if you think it's not worth fixing.
