### ISSUE TITLE
Add option to enable zsh-syntax-highlighting

### ISSUE THREAD

**Issue by davegallant** [nix-community/home-manager#1321]
### Issue description

Exposing a `enableSyntaxHighlighting` to enable [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) would be convenient.

This is something that is in [nixos/modules/program/zsh](https://github.com/NixOS/nixpkgs/blob/ae94e8923240f7ff7e82abf4783ef4318b8c4464/nixos/modules/programs/zsh/zsh-syntax-highlighting.nix#L10).

#### Maintainer CC

@uvNikita
@rycee

#### Technical details

I am new to nix, but was able to workaround this by the following:

```
programs.zsh = {
  enable = true;

  localVariables = {
    ZSH_DISABLE_COMPFIX = "true";
  };

  initExtra = ''
    source ${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  '';

  plugins = [
    {
      name = "syntax-highlighting";
      src = "${pkgs.zsh-syntax-highlighting}/share/zsh/site-functions";
    }
  ];
};
```

**Comment by ShrykeWindgrace** [comment]
Relevant recent issue: #1251 . It has a similar workaround for `nixpkgs.zsh-fast-syntax-highlighting`, but without extra steps in `initExtra`

**Comment by davegallant** [comment]
> Relevant recent issue: #1251 . It has a similar workaround for `nixpkgs.zsh-fast-syntax-highlighting`, but without extra steps in `initExtra`

Was unaware of this other highlighter. Works well also :)
