### ISSUE TITLE
Support configuring xdg+pipewire for Sway screensharing.

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#1328]
### Issue description

I am cleaning up some Firefox tabs and am reminded of:
 https://github.com/calbrecht/nixpkgs-overlays

It seems like we ought to be able to support this configuration with home-manager modules.

cc: @calbrecht

**Comment by colemickens** [comment]
The readme: https://github.com/calbrecht/nixpkgs-overlays/blob/cf2317a0eb520faa73fa58700e40d71c61fbbe9c/Readme.md

**Comment by calbrecht** [comment]
@colemickens, thanks. To be honest, i don't use home-manager and i do not intend to. Also it is possible to have it configured through nixos/configuration.nix like shown in the Readme.

Where do you see the benefits of a home-manager based configuration?

Maybe i should put a warning in the Readme too, but while writing here i feel like mentioning that this setup is still a bit unstable is a good thing.

I am able to screencast quite well with firefox if i do not haste, meaning wait for the services to be settled, firefox having loaded all tabs, system is not too heavy under load etc. etc. Nevertheless am i experiencing GPU crashes or sudden desktop exiting sometimes (around twice a week) :)

**Comment by colemickens** [comment]
Hi @calbrecht. If you're not using HM already, then this probably wouldn't really be applicable to you, and that's okay. It seems that some things just simply wind up duplicated between nixpkgs and home-manager.

IMO, since these are user-level services and related to my user/WM/etc config, it logically "goes in Home-Manager".

I think if this were merged any time soon it would need big caveat warnings. I was hoping things would stabilize by time we were ready to merge anything into nixpkgs/hm.

**Comment by calbrecht** [comment]
@colemickens, i see. If there is something i can help with, i would be happy to offer assistance.

Yesterday, i did compile the latest firefox-77 with the latest pipewire-3 patch from fedora. All seems good so far. I'll update my repo soon.

**Comment by terlar** [comment]
This will also be useful for people not on NixOS, if you use Home Manager together with a generic Linux distribution. I did look into this a bit a while ago, but didn’t get it fully working and was not proficient enough in the pipewire-stuff.
