### ISSUE TITLE
Write note in README about backups

### ISSUE THREAD

**Issue by rycee** [nix-community/home-manager#133]
A backup of a home directory will include link to the Nix store, which most likely will be dead in a restore situation. It may be necessary to clean these up manually. Also it is very important to back up the HM configuration. Need to note this in the README. See #123 for discussion.

**Comment by nonsequitur** [comment]
We could delay work on the cleanup instruction (or script?) until we have a stable home-file marker format. 
I'll submit my single-link patch soon, maybe this can settle the issue.

**Comment by rycee** [comment]
Yes, that sounds good 👍
