### ISSUE TITLE
[Question] programs.zsh.promptInit required for powerlevel10k ?

### ISSUE THREAD

**Issue by PierreR** [nix-community/home-manager#1338]
### Issue description

I am trying to install powerlevel10k with the home-manager. But this snippet does not seem to work:
```
  config = {
    programs.zsh = {
      enable = cfg.enable;
      oh-my-zsh.enable = true;
      oh-my-zsh.custom = "$HOME/.zsh_custom";
      oh-my-zsh.theme = "${cfg.zshTheme}";
      initExtra = ''
        [ "${cfg.zshTheme}"  == "powerlevel10k" ] && source ${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme
     '';
    };
  };
```

The error I have:
```
/nix/store/m6gvpz4n02svmc1vi8p07pzslaygrwq5-oh-my-zsh-2020-02-07/share/oh-my-zsh/oh-my-zsh.sh:source:118: no such file or directory: /nix/store/m6gvpz4n02svmc1vi8p07pzslaygrwq5-oh-my-zsh-2020-02-07/share/oh-my-zsh/themes/powerlevel10k.zsh-theme
```

### Meta
zsh module

#### Maintainer CC
@carlostome 
@rycee @uvNikita

### Technical details

[The nixpkgs derivation](https://github.com/NixOS/nixpkgs/blob/e76f83c266f7b03afe798cfcd9ff068ac369d5e4/pkgs/shells/zsh/zsh-powerlevel10k/default.nix#L4) suggests to use `programs.zsh.promptInit` but it does not seems to be exposed in the zsh module of the home-manager.
I haven't found much help on the web:
https://www.reddit.com/r/NixOS/comments/fenb4u/zsh_with_ohmyzsh_with_powerlevel10k_in_nix/

Thanks for your help.

**Comment by PierreR** [comment]
Would `zplug` be a better option ?

**Comment by 06kellyjac** [comment]
Here's a pretty bare-bones version of my config that works

```nix
{ config, pkgs, ... }:

{
  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    dotDir = ".config/zsh"; # Already prepends $HOME

    initExtraBeforeCompInit = ''
      # p10k instant prompt
      local P10K_INSTANT_PROMPT="${config.xdg.cacheHome}/p10k-instant-prompt-''${(%):-%n}.zsh"
      [[ ! -r "$P10K_INSTANT_PROMPT" ]] || source "$P10K_INSTANT_PROMPT"
    '';

    plugins = with pkgs; [
      {
        file = "powerlevel10k.zsh-theme";
        name = "powerlevel10k";
        src = "${zsh-powerlevel10k}/share/zsh-powerlevel10k";
      }
      {
        file = "p10k.zsh";
        name = "powerlevel10k-config";
        src = ../config/zsh/p10k; # Some directory containing your p10k.zsh file
      }
    ];

    initExtra = ''
      # blah blah
    '';
  };
}
```

Whenever I want to run `p10k configure` again I make sure to `unset POWERLEVEL9K_CONFIG_FILE` so it dumps it in `~/.config/zsh/p10k.zsh` or point it somewhere else as by default it'll try overwriting the config I've put in the plugins which goes in the nix store so it's Read Only.
Or you could just avoid the plugin/derivation method and add `source ./some/location/p10k.zsh` in your `initExtra` and `p10k configure` can continue to overwrite it.

I'm considering making a home-manager module for configuring p10k similar to the emacs init.d module @rycee has in a GitLab repo but it's a pretty big undertaking, lots of settings.

**Comment by nrdsp** [comment]
Appending the following line manually alone seems to work in my case: 

`initExtra = "source ${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme";`
