### ISSUE TITLE
programs.feh.keybindings does not support multiple keys for one value

### ISSUE THREAD

**Issue by eyadsibai** [nix-community/home-manager#1366]
in feh, you can have more than one key corresponding to the same action, but in Nix home manager ```programs.feh.keybindings``` you can only have one value per action (one key only)

**Comment by olmokramer** [comment]
A bit of a hack, but what has worked for me is to just put multiple keys, separated with whitespace, in the string for a command. E.g.

```
{
  programs.feh.keybindings = {
    menu_parent = "h Left";
    menu_down = "j Down";
    menu_up = "k Up";
    menu_child = "l Right";

    prev_img = "h Left";
    next_img = "l Right";

    zoom_out = "j Down";
    zoom_in = "k Up";
  };
}
```
