### ISSUE TITLE
redshift day and night mixed up

### ISSUE THREAD

**Issue by codygman** [nix-community/home-manager#1368]
### Issue description

I think there's an issue for this that was fixed in nixpkgs (edit: it's NixOS/nixpkgs#45994)

THis config:

```
redshift = {
      enable = true;
      latitude = "32.7767";
      longitude = "96.7970";
      brightness = {
        # Day and night mixed up, lol
        day = "0.4";
        night = "0.8";
      };
      tray = false;
      provider = "manual";
      temperature = {
        # Day and night mixed up, lol
        night = 5501;
        day = 3501;
      };
    extraOptions = ["-v"];
    }
```

results in:

```
Jul 01 22:45:27 razer redshift[25399]: Waiting for initial location to become available...
Jul 01 22:45:27 razer redshift[25399]: Location: 32.78 N, 96.80 E
Jul 01 22:45:27 razer redshift[25399]: Color temperature: 6500K
Jul 01 22:45:27 razer redshift[25399]: Brightness: 1.00
Jul 01 22:45:27 razer redshift[25399]: Status: Enabled
Jul 01 22:45:27 razer redshift[25399]: Period: Daytime
Jul 01 22:45:27 razer redshift[25399]: Color temperature: 3501K
Jul 01 22:45:27 razer redshift[25399]: Brightness: 0.40
```

#### Maintainer CC

@rycee 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1977.1dadefec574 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(cody): `"home-manager"`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rycee** [comment]
Curious, the module seems to follow what the redshift manual and `-h` output says.

https://github.com/rycee/home-manager/blob/7f7348b47049e8d25fb5b98db1d6215f8f643f0d/modules/services/redshift.nix#L150-L153

Vs.

```console
$ redshift -h | grep -e 'Color temperature' -e 'Screen brightness'
  -b DAY:NIGHT	Screen brightness to apply (between 0.1 and 1.0)
  -t DAY:NIGHT	Color temperature to set at daytime/night
```

But the actual behavior of redshift is the opposite?

**Comment by colemickens** [comment]
Redshift works correctly for me. And I'm confused. The linked issue in nixpkgs is about geoclue2 not working?

Also, the log seems to match the config?

```
Jul 01 22:45:27 razer redshift[25399]: Period: Daytime
Jul 01 22:45:27 razer redshift[25399]: Color temperature: 3501K
Jul 01 22:45:27 razer redshift[25399]: Brightness: 0.40
```

seems to say its going into daytime mode, and for daytime you defined:
```
brightness.day = "0.4";
temperature.day = 3501;
```

**Comment by codygman** [comment]
I'll try again to verify. Looking at my git logs I had it the other way around a while. I've been `systemctl --user stop redshift`'ing for so long I can't say for sure :sweat_smile:

**Comment by codygman** [comment]
I think this was user error.
