### ISSUE TITLE
programs.zplug always attempt to install plugins even when up to date

### ISSUE THREAD

**Issue by Macavirus** [nix-community/home-manager#1378]
### Issue description

The zplug module will always attempt to install new plugins, thus printing an extraneous line to the terminal every time you open it. Normally this is friendly behaviour -- if there is a new plugin to install, it happens automatically without user intervention, however the vast majority of the time, there will be no plugins to install, and thus the warning is annoying.

This will output `[zplug] no packages to install` every time you open a terminal.

#### Maintainer CC

@s1341

**Comment by s1341** [comment]
@Macavirus what do you suggest we do instead?

**Comment by Macavirus** [comment]
I believe @Vonfry has a suggested fix but didn't open a PR for it? https://github.com/rycee/home-manager/compare/master...Vonfry:fix/zplug-dir-and-quiet

It just needs to run `zplug check` on startup and then only run `zplug install` if `zplug check` returns falsy.

**Comment by Vonfry** [comment]
@Macavirus  Because I do not ues zplug any more, the script isn't tested. Could you test it and make a pr?
