### ISSUE TITLE
programs.chromium.extensions is broken on Linux

### ISSUE THREAD

**Issue by bb2020** [nix-community/home-manager#1383]
### Issue description

It looks like `programs.chromium.extensions` is broken for `pkgs.google-chrome` package. It generates extension json files in `~/.config/google-chrome/External Extensions` while they should be in `/opt/google/chrome/extensions` or in `/usr/share/google-chrome/extensions` according to [this document](https://developer.chrome.com/extensions/external_extensions). Is it possible to write outside of the home directory with home-manager? 

Edit: Currently using system-wide policy option of NixOS. [Here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/chromium.nix) is the implementation.

#### Maintainer CC
@rycee @tadfisher

**Comment by ivankovnatsky** [comment]
I'm using myself system-wide config with extraOpts and extensions, and wanted to try it out home-manager config. But google-chrome did not pick up my extensions due to this, I guess.

**Comment by bb2020** [comment]
It looks like `home-manager` is kinda out of options at this point because Chrome reads policy files from system paths (`/opt` or `/usr`). Maybe the option should be removed from `home-manager`.

**Comment by ivankovnatsky** [comment]
this appears to be broken for chromium as well.

**Comment by bb2020** [comment]
I am closing this because a fix is created in #1383.

**Comment by bb2020** [comment]
I am closing this because a fix is created in #1867.

**Comment by kuzzmi** [comment]
I'm guessing I'm late to the party, but right now, if I use a plain simple `programs.google-chrome.enable = true`, I'm getting an error related to the `extensions` field being removed.
At the moment it seems to be impossible to install `google-chrome` via home-manager.
Perhaps I did something wrong, but I'm setting up a completely fresh machine from scratch.

**Comment by bb2020** [comment]
I suppose you can only customize `chormium` that way. If you just want to install `google-chrome`, then this should be enough.
```
nixpkgs.config.allowUnfree = true;
home.packages = with pkgs; [ google-chrome ];
```

**Comment by bb2020** [comment]
You are probably using `programs.chromium.package = pkgs.google-chrome;` and have set `programs.chromium.extensions` somewhere else. These two are now mutually exclusive.

**Comment by kuzzmi** [comment]
> You are probably using `programs.chromium.package = pkgs.google-chrome;` and have set `programs.chromium.extensions` somewhere else. These two are now mutually exclusive.

Not really, I had a bare configuration file with only a few lines, one of which was `programs.google-chrome.enable = true;`. Extensions were not set anywhere. It did work with installing `google-chrome` through `home.packages` tho. For me that's fine, so I can at least reply here.
But I probably mistakenly assumed, that `programs.google-chrome.enable = true;` should do basically the same thing, according to the *.nix file I found in this repo.

**Comment by Malix-Labs** [comment]
See #9117
