### ISSUE TITLE
Documentation and tests are only built against stateVersion 18.09

### ISSUE THREAD

**Issue by alexarice** [nix-community/home-manager#1389]
### Issue description

The default for stateVersion is 18.09 meaning that the online documentation for home-manager only documents this state version as far as I am aware. Tests are also only built against 18.09 though I think this is less of a problem as a test can probably specify a stateVersion.

**Comment by rycee** [comment]
Ideally the option documentation should show the behavior for all applicable state versions. For example, see [`home.homeDirectory`](https://rycee.gitlab.io/home-manager/options.html#opt-home.homeDirectory).

Similarly, tests should in an ideal world cover different state versions. See the [newsboat tests](https://github.com/rycee/home-manager/tree/master/tests/modules/programs/newsboat), for example.

**Comment by alexarice** [comment]
Have hit some problems with doing this in #1386. I wonder if it would be easier to have a copy of the documentation for each stateVersion?
