### ISSUE TITLE
Gammastep: needs module (and design input!)

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#1396]
### Issue description

Gammastep is the fork of redshift with Wayland support merged in. I think we should have a module for it since the config path is changed from redshift's.

Shall we duplicate the module, or add a toggle to the Redshift package to output the config to the gammastep location if the user opts for it?

cc: @rycee it looks like you added the redshift module initially.

**Comment by colemickens** [comment]
Gammastep is here: https://gitlab.com/chinstrap/gammastep

**Comment by alexarice** [comment]
Don't really mind which design decision is chosen but it would be good to get a module
