### ISSUE TITLE
"onchange" command doesn't work when using as nixos module.

### ISSUE THREAD

**Issue by btwiusegentoo** [nix-community/home-manager#1399]
### Issue description

Hi! when I use as nixos module I have a problem.
Looks like most modules work as excepted but when I'm using xsession.windowManager.xmonad.config and edit the file, doesn't auto recompile and restart as excepted.
I looked xmonad.nix code and looks like it uses `home.file.".xmonad/xmonad.hs".onChange` to detect file change and recompile/restart.
I also have <code>".xmonad/xmobar.hs".onChange =</code> in my home.nix that I personally use but doesn't work.
so it's not a module specific issue.
Sorry if this is my misunderstanding and there are option or something to make work.
I don't have idea what is wrong.

#### Maintainer CC
I will not mention because I don't think it's a module specific isuue. and I don't have idea what is causing the issue.
Edit: I think actually it is a module. maybe files.nix? but there are not meta.maintainers.

#### Technical details
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-devcopying path '/nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"` - host os: `Linux 5.7.9, NixOS, 20.03.2611.bb8f0cc2279 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2611.bb8f0cc2279"`
 - channels(btw): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by yurrriq** [comment]
I have the same problem.
