### ISSUE TITLE
Can't start Calibre

### ISSUE THREAD

**Issue by a12l** [nix-community/home-manager#1402]
### Issue description

When I try to start Calibre with the command `/nix/store/ndrpw1f3l5scfp69rlchkfpp75pj2gpq-user-environment/bin/calibre` I get the error message

```
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
fish: “/nix/store/ndrpw1f3l5scfp69rlch…” terminated by signal SIGABRT (Abort)
```

I've installed Calibre by adding 

```
{ pkgs, ... }:

{
	home =
	{
		packages = with pkgs;
		[
			calibre
		];
	};

	targets.genericLinux.enable = true;
}
```

to my `home.nix` file. Note that the above isn't my complete config. You can find my current `home.nix` file in [my Gitlab repo](https://gitlab.com/inquisitiv3/configuration.nix/-/blob/8e2bcc64398b2f2105b765205ed491717e9fb043/.config/nixpkgs/machines/machine0000/home.nix).

#### Maintainer CC

N/A

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.9-200.fc32.x86_64, Fedora, 32 (Thirty Two)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(alo): `"home-manager-20.03, nixpkgs-20.09pre234801.1facbd61b17"`
 - nixpkgs: `/home/alo/.nix-defexpr/channels/nixpkgs`
```

**Comment by rycee** [comment]
Unfortunately I believe this is more a limitation of Nix than HM. It may be possible that HM could help out a bit by, e.g., setting up [nixGL](https://github.com/guibou/nixGL) or something but I would not be able to help much with that since I only use NixOS. I would suggest asking about this in the #nixos channel on [freenode.net](https://freenode.net/) and see if anybody there knows about using OpenGL programs on non-NixOS systems.

**Comment by slashformotion** [comment]
Still not working
