### ISSUE TITLE
Inconsistent HiDPI xsession.pointerCursor.size

### ISSUE THREAD

**Issue by lzmartinico** [nix-community/home-manager#1406]
### Issue description
On a  HiDPI NixOS laptop with i3wm and no Desktop manager, the size of the cursor as set in xsession.pointerCursor is not consistent. In particular, I get the correct size of cursor on the i3 desktop, i3bar, and applications such as Emacs and zathura; but others like xterm and applications using GTK or QT keep the smaller cursor. LightDM also seem to use the smaller cursor, but that might be expected for the xsession variable.
Additional settings
```
xsession.pointerCursor = {
  package = pkgs.gnome3.gnome_themes_standard;
  size = 32;
  theme = "Adwaita";
}; 
gtk.iconTheme = {
  package = pkgs.gnome3.gnome_themes_standard;
  name = "Adwaita";
};
gtk3.extraConfig = {
  gtk-cursor-theme-name = "Adwaita"; 
  gtk-cursor-theme-size = 32;
};
```
Setting variable XCURSOR_SIZE does not seem to have any effect

#### Maintainer CC

@rycee 

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.18, NixOS, 20.03.2625.9ea61f7bc44 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(s1443541): `""`
 - channels(root): `"nixos-20.03.2625.9ea61f7bc44, home-manager-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Algram** [comment]
I have exactly the same problem with sway.

**Comment by Mic92** [comment]
In firefox all gtk settings in this regard where ignored or only applied partially `layout.css.devPixelsPerPx` in the end did the trick: https://wiki.archlinux.org/index.php/HiDPI#Firefox

**Comment by lzmartinico** [comment]
For me the `layout.css.devPixelsPerPx` seems to scale everything but the cursor
