### ISSUE TITLE
Unable to control nested tmux sessions with shortcut key defined in home-manager tmux config

### ISSUE THREAD

**Issue by starcraft66** [nix-community/home-manager#1411]
### Issue description

When setting the tmux `shortcut` key, a config option is generated that binds `C-<shortcut key>` to switch to the last window. This effectively prevents you from pressing `C-<shortcut key>` multiple times successively to control nested tmux sessions.

As seen: https://github.com/rycee/home-manager/blob/master/modules/programs/tmux.nix#L72

**Comment by berbiche** [comment]
Resolved in https://github.com/nix-community/home-manager/pull/1254
