### ISSUE TITLE
qsyncthing tray service is starting too early

### ISSUE THREAD

**Issue by jackmac92** [nix-community/home-manager#1425]
### Issue description
I'm using the syncthing service with tray enabled, but every time I login I get this alert.
![image](https://user-images.githubusercontent.com/2984710/89133703-10f3b980-d4ec-11ea-9d17-d9c12191e62d.png)

This can be resolved by running `systemctl --user restart qsyncthingtray.service`, so I suspect it is running too early.

I'm messing around with it in a forked branch but no luck on fixing yet. I was thinking making it run After (as opposed to PartOf) `graphical-session.target` should fix it, but that wasn't working for me.

#### Maintainer CC
@rycee 

#### Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-7634-generic, Pop!_OS, 20.04 LTS`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(jmccown): `"home-manager, nixpkgs-20.09pre236408.43dd81b3fe8"`
 - nixpkgs: `/home/jmccown/.nix-defexpr/channels/nixpkgs`
```

**Comment by andresilva** [comment]
Duplicate of #603.
