### ISSUE TITLE
Sponsorship options

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#1432]
I'm not able to find any information on how to sponsor development of home-manager. I imagine that a number of us would be happy to pitch in for home-manager if there was a convenient option to sponsor the project!

**Comment by rycee** [comment]
There are not really any particular expenses involved in developing HM so I don't have any particular interest in figuring out how sponsoring would work. Feel free to donate the money to some good cause of your choice 🙂

**Comment by samuela** [comment]
That's very humble of you @rycee! I'll direct my donations to https://opencollective.com/nixos, and I challenge others to do the same!
