### ISSUE TITLE
[vscode] Live Share extension doesn't work

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#1435]
(### Issue description
I'm trying to add the VSCode Live Share extension, but home-manager isn't happy about it:
```
  programs.vscode = {
    enable = true;
    extensions = [
      pkgs.vscode-extensions.bbenoist.Nix
      pkgs.vscode-extensions.ms-vsliveshare.vsliveshare
    ];
  };
```
The `bbenoist.Nix` install works great on its own, but I'm getting an error with the vsliveshare extension:
```
❯ home-manager switch
error: attribute 'ms-vsliveshare' missing, at /home/skainswo/.config/nixpkgs/home.nix:51:7
(use '--show-trace' to show detailed location information)

There are 11 unread and relevant news items.
Read them by running the command 'home-manager news'.
```

#### Maintainer CC
@hyperfekt @rycee @pasqui23 @pwm 

#### Technical details

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-42-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(skainswo): `"home-manager, nixpkgs-20.09pre237385.be42a66cd30"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs`
```

**Comment by pwm** [comment]
Hey @samuela , I'm far from a pro, but on 1st glance vsliveshare is not in https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/default.nix ?

I personally use `extensionsFromVscodeMarketplace` like this:
https://github.com/pwm/nix-home/blob/master/home.nix#L109-L115
which, as you can see, pulls in the extensions I use from here:
https://github.com/pwm/nix-home/blob/master/vscode/extensions.json

**Comment by samuela** [comment]
Thanks @pwm ! I'm not able to find documentation for that option anywhere. How does it work? Are those SHA's for git commits, or something else?

**Comment by samuela** [comment]
Also is it possible to mix `extensionsFromVscodeMarketplace` and extensions from https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/default.nix?

**Comment by pwm** [comment]
@samuela There might be a better way but how I did it was to:
1. Install the required plugins from inside VSCode (ie. no nix)
2. Download and run https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/update_installed_exts.sh
which will produce a json with the extensions including their hashes
3. Save the json and use it with `extensionsFromVscodeMarketplace` like I did in my home nix

Re possible to mix: I believe yes but I think `extensionsFromVscodeMarketplace` supersedes the nixpkgs one, ie. they work the same but the former pull it straight from the source.

**Comment by samuela** [comment]
Gotcha, this seems sufficiently complex I think I may just not track my vscode extensions with home-manager.  I misunderstood the docs as supporting arbitrary extensions from the official marketplace with the `pkgs.vscode-extensions.*.*` syntax.

**Comment by pwm** [comment]
Fair. In my experience, after the initial setup, it's not too bad, unless you often experiment with lots of new extensions/replace them. I tend to use the set so i very rarely have to touch the nix config.

**Comment by teto** [comment]
liveshare is available in unstable and since then I haven't had any trouble with liveshare so closing this. Feel free to reopen if that's not the case for you.

**Comment by analognightmare** [comment]
I found this while trying to get Live Share to work with home-manager:

```
  programs.vscode = {
    enable = true;
    extensions = [
      unstable.vscode-extensions.bbenoist.Nix
      unstable.vscode-extensions.vscodevim.vim
      unstable.vscode-extensions.matklad.rust-analyzer
      unstable.vscode-extensions.ms-vsliveshare.vsliveshare
    ];
  };
```

And when I start vscode the extension is installed: 

![2020-12-12-195628_1082x483_scrot](https://user-images.githubusercontent.com/20466293/102001896-46878b00-3cb4-11eb-8b77-62190ea57506.png)

But unfortunately, it won't let me start/join a session and a popup informs me that: 

>We were unable to install support for joining sessions using a browser link. You may be missing key Linux libraries. Install them now?

If I click yes the installation fails (which I am not surprised by). Any idea what I am doing wrong here?

**Comment by analognightmare** [comment]
Happy to make a new issue for this, too :)
