### ISSUE TITLE
dropbox: add an option for DISPLAY

### ISSUE THREAD

**Issue by bbigras** [nix-community/home-manager#1437]
### Issue description

Currently dropbox runs with DISPLAY unset. I'm guessing to make it runs headlessly. (or is it because of an upstream bug @eyJhb?)

Would it make sense to have an option to set DISPLAY and `WantedBy = [ "graphical-session.target" ]`? And maybe the 'gi' dependency.

Was first discussed in https://github.com/rycee/home-manager/issues/1419

I was using the following before and I think it was working well:

```nix
systemd.user.services.dropbox = {
  Unit = {
    Description = "Dropbox";
  };
 Install = {
    WantedBy = [ "graphical-session.target" ];
  };
 Service = {
    Environment = "QT_PLUGIN_PATH=/run/current-system/sw/${pkgs.qt5.qtbase.qtPluginPrefix}:QML2_IMPORT_PATH=/run/current-system/sw/${pkgs.qt5.qtbase.qtQmlPrefix}";
    # environment = {
    # QT_PLUGIN_PATH = "/run/current-system/sw/" + pkgs.qt5.qtbase.qtPluginPrefix;
    # QML2_IMPORT_PATH = "/run/current-system/sw/" + pkgs.qt5.qtbase.qtQmlPrefix;
    # };
    ExecStart = "${pkgs.dropbox.out}/bin/dropbox";
    ExecReload = "${pkgs.coreutils.out}/bin/kill -HUP $MAINPID";
    KillMode = "control-group"; # upstream recommends process
    Restart = "on-failure";
    PrivateTmp = true;
    ProtectSystem = "full";
    Nice = 10;
  };
};
```

**Comment by eyJhb** [comment]
Basically we need the upstream Dropbox-cli, to have the `gi` support that it needs, then we can stop unsetting the DISPLAY :)
As we are only doing it, because of that bug...
