### ISSUE TITLE
dconf.settings isn't fully declarative (old stuff can remain)

### ISSUE THREAD

**Issue by bjornfor** [nix-community/home-manager#1444]
### Issue description

`dconf.settings` isn't fully declarative, as in removing a previously configured setting from home-manager does not reset the dconf setting back to its default value.

As a workaround I'm manually removing ~/.config/dconf/user to ensure no stale settings are present on my system.

Perhaps the module can keep track of which keys a generation touches and reset the keys that are missing from the new generation?

#### Maintainer CC

@gnidorah @rycee 

#### Technical details
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.03.git.b50d558 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.1950.48723f48ab9"`
 - nixpkgs: `/etc/current-nixpkgs`
```

**Comment by rycee** [comment]
Yeah, I think HM could write the key names into a file in the generation directory. During the activation it could then reset the keys that were in the old but not new generation. I'm unlikely to find the time to work on this, though.

**Comment by bjornfor** [comment]
I don't think this is solved.

**Comment by bjornfor** [comment]
Thanks for fixing it!

**Comment by rycee** [comment]
@bjornfor Hope it works for you. Many thanks to @ilkecan for taking the time to fix it 👍
