### ISSUE TITLE
Nushell on macOS does not find config file

### ISSUE THREAD

**Issue by davidarmstronglewis** [nix-community/home-manager#1458]
It looks like on macOS, nushell will look for a config file at `/Users/$USER/Library/Preferences/org.nushell.nu/config.toml` rather than the standard XDG config location as this modules assumes here: https://github.com/rycee/home-manager/blob/6cf6b587b575493e7718bf08b209013d7dcf4d58/modules/programs/nushell.nix#L65

Not sure if there's a Nix standard way to place config files in their respective directory in `~/Library/Preferences`, but it's a pretty standard practice to do that. For more context, I do have `XDG_CONFIG_HOME` set to `/Users/$USER/.config`, but nushell doesn't seem to respect that.

**Comment by marsam** [comment]
upstream issue https://github.com/nushell/nushell/issues/893

Apple explicitly advises against creating [files in `Preferences` subfolder](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1):
>This directory contains app-specific preference files. You should not create files in this directory yourself. Instead, use the NSUserDefaults class or CFPreferences API to get and set preference values for your app.In iOS, the contents of this directory are backed up by iTunes and iCloud.

**Comment by davidarmstronglewis** [comment]
Ooh, I had not realized that directory is specifically for Applications that have a Bundle Identifier. It makes sense to keep this issue open until upstream has addressed the issue, but feel free to disagree and close this issue.
