### ISSUE TITLE
Installation fails on WSL1

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-community/home-manager#1459]
### Issue description

After https://github.com/rycee/home-manager/commit/2bcd96928e1f831f8cedff76ac733df9f1f5e0fe home-manager fails to install (``nix-shell '<home-manager>' -A install``) on WSL1 with the following error:
```
created 178 symlinks in user environment
The databases in [/nix/store/jscl146ck7x85xhvdzjivfycy71pddi7-home-manager-path/share/applications] could not be updated.
builder for '/nix/store/izcysksz370mvylvpcsfa8wnmldbb4v8-home-manager-path.drv' failed with exit code 1
cannot build derivation '/nix/store/wkmr0cf1szbmqkcng1d5mf1fh7hhhl61-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/wkmr0cf1szbmqkcng1d5mf1fh7hhhl61-home-manager-generation.drv' failed
```

#### Maintainer CC

@rycee @Kha 

#### Technical details

WSL 1 on Windows 10.0.19041.450
Ubuntu 20.04.1
Nice 2.3.7 installed via the install script from nixos.org

**Comment by holmesmr** [comment]
I had the same issue on WSL2, after failing once I was able to get it to install successfully by applying this workaround here:
https://github.com/rycee/home-manager/issues/1392#issuecomment-671054406

**Comment by rycee** [comment]
I committed 209fb62d4983f1219f10b2e89debd169549161b1, which may or may not fix this. Please update an give it a try.

**Comment by SuperSandro2000** [comment]
This bug seems to be fixed in my limited testing but another occured:

```
error: path '/nix/store/7kcwvlmijrlqmk1ivh7fqi2ynfzncigp-news-unread-ids' is not valid
...
/nix/store/ygmhhwb0xrdfx6b4vcsnnhiqsiv07zrb-home-manager/bin/home-manager: line 127: /tmp/home-manager-build.QMqpVaZXaK/news-info.sh: No such file or directory
```

It does not seem to be fatal. The installation did not abort and it did not occur after a second installation try.
