### ISSUE TITLE
No programs.bash.enableCompletion?

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#1464]
### Issue description

I'm experimenting with home-manager outside of NixOS using Debian. I'm trying to have home-manager handle has many things as possible. I can't find the configuration to have home-manager enable bash completions.

What about adding the following to `programs.bash.bashrcExtra` or similar?

```
      . ${pkgs.bash-completion}/share/bash-completion/bash_completion
```

I can send a PR if you want.

NixOS has bashCompletion enabled by default.

#### Maintainer CC

/cc @rycee 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09.git.f4195a89195 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `""`
 - nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`

**Comment by acowley** [comment]
This was very helpful for me, thank you!

**Comment by berbiche** [comment]
> What about adding the following to `programs.bash.bashrcExtra` or similar?
> 
> ```
>       . ${pkgs.bash-completion}/share/bash-completion/bash_completion
> ```
> 
> I can send a PR if you want.

Was a PR ever created?

**Comment by DamienCassou** [comment]
I never got any answer so I never sent a PR.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
