### ISSUE TITLE
How to migrate to a new computer?

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#1467]
### Issue description

Scenario: I have home-manager running on a laptop and configured to handle most of my setup (bash, profile, xsession, WM, ...). I got a new laptop.

I can't just rsync my HOME directory because this copies many (home-manager managed) symlinks that would be broken on the target machine.

If I start by installing home-manager on the new laptop, I need to copy my home-manager configuration to be able to have my configuration on the new laptop. When I'm done setting up my environment, I still can't copy my old HOME directory to the new laptop because this would override the newly generated configuration file symlinks. (If the home-manager's configuration is exactly the same, you should get identical nix paths between the 2 computers in which case overriding the symlinks is fine).

**Comment by cole-h** [comment]
All I would do is copy your `home.nix` and related files (or even the entire `~/.config/nixpkgs`) to the `~/.config/nixpkgs` on your other machine and install home-manager as normal. Is there any reason this wouldn't/doesn't work for you?

**Comment by DamienCassou** [comment]
> All I would do is copy your home.nix and related files (or even the entire ~/.config/nixpkgs) to the ~/.config/nixpkgs on your other machine and install home-manager as normal. Is there any reason this wouldn't/doesn't work for you?

This would work perfectly. And then you need to copy all the data that is not handled by home-manager (e.g., music, documents, photos). You can't just copy your HOME directory from one machine to the other one because this would overwrite the home-manager  generated symlinks.

**Comment by rycee** [comment]
FWIW I use Unison to synchronize my two main laptops and exclude the HM managed files by interpolating
```
hmFilesIgnorePatterns =
  concatStringsSep "\n"
  (map (file: "ignore = Path ${file.target}")
  (filter (file: !file.recursive)
  (mapAttrsToList (_: file: file) config.home.file)));
```
into the generated Unison profile. I imagine something similar should be possible with rsync.

**Comment by DamienCassou** [comment]
This makes a lot of sense, thank you.
