### ISSUE TITLE
Can both file.<name>.source and lib.mkAfter + file.<name>.text be used?

### ISSUE THREAD

**Issue by shadowrylander** [nix-community/home-manager#1476]
Hello!

What the title says; can I add text to the resulting target file along with the contents of the source file, using `file.<name>.text = lib.mkAfter '' [...] ''`? I'm currently trying to, but it doesn't seem to be working.

Any help will be greatly appreciated!

**Comment by rycee** [comment]
No, you have to use either `source` or `text`. I guess you can use [`builtins.readFile`](https://nixos.org/manual/nix/stable/#builtin-readFile) to read the file and concatenate with the string. Something like `text = builtins.readFile … + "…";`

**Comment by shadowrylander** [comment]
Ah; in that case will the `target` attribute still work? And would it be possible to implement the previous feature?

**Comment by rycee** [comment]
Yes, the target attribute determines there the result should be placed.

**Comment by shadowrylander** [comment]
Right! Thanks for the help! I'll go ahead and close this now!

**Comment by shadowrylander** [comment]
Crap. Didn't actually close this.
