### ISSUE TITLE
Status-notifier-watcher startup timings issue.

### ISSUE THREAD

**Issue by meck** [nix-community/home-manager#1480]
### Issue description

Recently on on unstable the `status-notifier-watcher` stopped showing any icon, I managed to get it working by crudely delaying the start of the services:

```
systemd.user.services.network-manager-applet.Service.ExecStartPre = "${pkgs.coreutils}/bin/sleep 2";
systemd.user.services.ubdiskie.Service.ExecStartPre = "${pkgs.coreutils}/bin/sleep 2";
systemd.user.services.pasystray.Service.ExecStartPre = "${pkgs.coreutils}/bin/sleep 2";
systemd.user.services.blueman-applet.Service.ExecStartPre = "${pkgs.coreutils}/bin/sleep 2";
``` 
I tried setting `After` to `status-notifier-watcher.service` but that dident help.

#### Maintainer CC
@pltanton 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 20.09pre242714.a31736120c5 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre242714.a31736120c5, home-manager"`
 - channels(meck): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pltanton** [comment]
I guess it is somehow relates to #1312. Maybe we should create an extra target for status-notifier-watcher and depend on it for widget services? 

@rycee as I can see not every service respects delay in status-notifier-watcher's service and starts before status-notifier-watcher finish initialization. Widget services just ignoring the WantedBy directive.

**Comment by NickHu** [comment]
I propose that we revert https://github.com/nix-community/home-manager/commit/02c1f8d416d55d8bc8d4de62f65f62fef40e5e80

For me, it creates more problems it solves; it stops
* pasystray
* udiskie
* network-manager-applet

from appearing at startup
