### ISSUE TITLE
Add new maintainer to home-manager team

### ISSUE THREAD

**Issue by Mic92** [nix-community/home-manager#1481]
To scale review of pull requests we should increase the maintainer team.
Post here if you want to join the team or you want to propose others:

https://github.com/orgs/nix-community/teams/home-manager/members

**Comment by kalbasit** [comment]
@Mic92 I was part of the maintenance team in the old home, please add me to the team here.

:tada:

**Comment by rycee** [comment]
Unfortunately I can't recall exactly who had committer access in the old repo but I think at least @uvNikita, @teto, @Infinisil, and @kalbasit should be added as members.

**Comment by Mic92** [comment]
@rycee I made you nix-community owner, so you can also add people to the home-manager team.

**Comment by Mic92** [comment]
I invited all the folks you mentioned.

**Comment by NickHu** [comment]
I'd be happy to help maintain by reviewing and merging PRs; I've contributed a bit to home-manager and I'm keen to help out more.

**Comment by Mic92** [comment]
@rycee I would leave it to to you to add new maintainers in the future.

**Comment by rycee** [comment]
@Mic92 Cool, thanks for setting things up!

**Comment by Mic92** [comment]
@NickHu I invited you to nix-community, as mentioned I leave it to @rycee to add you to home-manager.

**Comment by teto** [comment]
I would like to suggest @sumnerevans too.

**Comment by Mic92** [comment]
Invited.

**Comment by ncfavier** [comment]
I'd like to apply to become a maintainer, I hope this is the right place to do so.

I think there's a lot of weight on @rycee's shoulders at the moment and I think I can help reduce the load. I like working on core stuff like the module system, NixOS/nix-darwin modules, the flake and documentation, but not only.

My PRs: https://github.com/nix-community/home-manager/pulls?q=is%3Apr+author%3Ancfavier

**Comment by berbiche** [comment]
I believe @ncfavier would make a good maintainer and a good addition to the team.
I have read many of their PRs on both nixpkgs and Home Manager and they were all high quality, with little to no changes required to be merged.
@ncfavier has a deep understanding of the module system and everything around as seen by their contribution to nixpkgs, HM, search.nixos.org, nix, etc.

**Comment by ncfavier** [comment]
Thanks for the invite, @rycee!
