### ISSUE TITLE
Generalize native messaging host modules

### ISSUE THREAD

**Issue by Myhlamaeus** [nix-community/home-manager#1487]
### Issue description

I'd like to add another module for a [native messaging host](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) (specifically, I'd like to add tridactyl-native); however, the currently sole native messaging host module [browserpass](/nix-community/home-manager/blob/master/modules/programs/browserpass.nix) defines its [manifests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#App_manifest) inline.

I have a few questions regarding the design of a generalized native messaging host module:

1. Should it be per browser (eg `programs.firefox.nativeMessagingHosts.browserpass = …`) or unified (eg `nativeMessagingHosts.browserpass = { browsers = [ "firefox" … ]; … }`?)
2. Should the module accept an attrset which gets turned into JSON or a package which contains the manifest? Perhaps both?
  * The attrset would use nix modules, so it would be validated and allow merging, but we'd have to either do something like `removeAttrs ["name"] (fromJSON (readFile "${pkgs.browserpass}/lib/browserpass/hosts/firefox/com.github.browserpass.native.json"))` or specify the manifest manually.
  * For the package we would probably link all files matching `/lib/browserpass/hosts/firefox/*.json` for Firefox and `/lib/browserpass/policies/chromium/*.json` for Chromium-based browsers.
3. Should modules for native messaging hosts be named after the extension (eg `tridactyl`) or the package containing the host (eg `tridactyl-native`?)

#### Maintainer CC

@rycee (due to Firefox)

**Comment by teto** [comment]
NB: edited your message to have a numbered list

1. I hardly see any advantage about unifying ? in which case keep them per-browser.

Dont know enough about the rest to comment. I don't see any problematic issue though.

**Comment by WhiteAbeLincoln** [comment]
The nixpkgs firefox package already supports browserpass and tridactyl-native. They seem to be using the per browser configuration (you set config.firefox.enableBrowserpass = true). Unfortunately, the home-manager firefox package doesn't allow setting those options. #1586 might be related
