### ISSUE TITLE
`programs.zsh.enable = false` after enabling leaves it in /etc/shells

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#1489]
### Issue description

If I have `programs.zsh.enable = true;`, do a switch, then set it to `false`, do another switch, I still have 
```
skainswo@skainswo-X58A-UD3R:~$ cat /etc/shells
# /etc/shells: valid login shells
/bin/sh
/bin/bash
/bin/rbash
/bin/dash
/usr/bin/tmux
/home/skainswo/.nix-profile/bin/zsh
skainswo@skainswo-X58A-UD3R:~$ 
```

#### Maintainer CC

@rycee 
@dawidsowa 
@uvNikita 
@dermetfan 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-45-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(skainswo): `"home-manager, nixpkgs-20.09pre242495.3c0e3697520"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs
```

**Comment by rycee** [comment]
Home Manager never touches anything outside `$HOME`, the `/etc/shells` file is managed through the NixOS `programs.zsh` options.

**Comment by samuela** [comment]
I'm actually running on Ubuntu 20.04 though. There must be a way that /etc/shells was indirectly changed by the `programs.zsh.enable = true;` home-manager option.

**Comment by samuela** [comment]
I'm guessing this is due to https://github.com/nix-community/home-manager/issues/1488#issuecomment-693715154 so I'm going to close.
