### ISSUE TITLE
Impossible to restart gpg-agent.service after manually stopping it

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#1490]
### Issue description

Run `systemctl --user stop gpg-agent.service`

Try to restart it.

I can't figure it out. Every time just doesn't start gpg, and then when I run a `gpg` command, it just starts gpg-agent incorrectly without access to pinentry and it doesn't work.

AFAICT I have to restart my session to get things working again which is very annoying. 

Am I doing something wrong?

**Comment by colemickens** [comment]
see https://gist.github.com/colemickens/7370bd12a3a10f4422ded1dd3790b7f5

**Comment by colemickens** [comment]
Yeah, so then I run a gpg command, then `gpg-agent.service` is supposedly running... and yet...

```
Sep 11 01:31:56 slynux gpg-agent[1479]: scdaemon[1479]: sending signal 12 to client 1054
Sep 11 01:31:56 slynux gpg-agent[1479]: scdaemon[1479]: ccid open error: skip
Sep 11 01:31:56 slynux gpg-agent[1479]: scdaemon[1479]: ccid open error: skip
Sep 11 01:31:56 slynux gpg-agent[1054]: DBG: detected card with S/N D2760001240102010006071267080000
Sep 11 01:31:56 slynux gpg-agent[1479]: [115B blob data]
Sep 11 01:31:56 slynux gpg-agent[1054]: can't connect to the PIN entry module '/nix/store/yvnd02rbdsin2waamh9>
Sep 11 01:31:56 slynux gpg-agent[1479]: scdaemon[1479]: PIN callback returned error: IPC call has been cancel>
Sep 11 01:31:56 slynux gpg-agent[1479]: scdaemon[1479]: app_auth failed: IPC call has been cancelled
Sep 11 01:31:56 slynux gpg-agent[1054]: smartcard signing failed: No pinentry
Sep 11 01:31:56 slynux gpg-agent[1054]: ssh sign request failed: No pinentry <GPG Agent>
```

**Comment by olmokramer** [comment]
Not a direct answer to your question, but I hope it helps anyway: when I want to restart `gpg-agent` I run `gpgconf --kill gpg-agent`. The next time I run a gpg command the agent is started with pinentry access. This also works when gpg has been updated, i.e. it will start the new version of the agent.

If you already know this, this doesn't work for you, or you still want to get to the bottom of this issue, I think [line 26 of your gist](https://gist.github.com/colemickens/7370bd12a3a10f4422ded1dd3790b7f5#file-gistfile1-txt-L26) tells you why it will not restart, although I have no clue how to work around that, and a quick google didn't give much results.

**Comment by olmokramer** [comment]
PS looks like it's [this line](https://github.com/nix-community/home-manager/blob/master/modules/services/gpg-agent.nix#L210) that's causing it. You could try to disable it. Or maybe restarting the socket instead of the service will work?

**Comment by rycee** [comment]
Yes, the service is socket activated and is not intended to be started directly. For pinentry you may need to adjust [`services.gpg-agent.pinentryFlavor`](https://rycee.gitlab.io/home-manager/options.html#opt-services.gpg-agent.pinentryFlavor)?

**Comment by colemickens** [comment]
I think this is what happens:
- somehow `gpg-agent` is no longer alive
- someone, something, somewhere triggers `gpg`, it notices it's not running **and gpg launches the agent itself**
- everything from here is not going to go well

I suspect this is related to (among others) https://github.com/NixOS/nixpkgs/issues/97861#issuecomment-691637202 and https://github.com/NixOS/nixpkgs/issues/35464

The fix:
- don't let gpg start gpg-agent, always do it yourself.

I think, *think* this is a general fix for a lot of the misc gpg/pin-entry issues *especially in cases where a reboot helps*.

```
sudo pkill gpg-agent
systemctl --user restart gpg-agent.socket gpg-agent-extra.socket  gpg-agent-ssh.socket
```
