### ISSUE TITLE
Creating arbitrary file in home directory

### ISSUE THREAD

**Issue by btomasini** [nix-community/home-manager#1493]
### Issue description

This is a support question.  How do I use nix via home manager to create an abitrary text file?  In my case, I want the following content at `~/.ideavimrc` :

```
map <C-k> <C-w>k
map <C-j> <C-w>j
map <C-l> <C-w>l
map <C-h> <C-w>h
let mapleader=","
inoremap jj <ESC>
```
Any help or pointers would be appreciated.

**Comment by cole-h** [comment]
You're probably looking for [`home.file.<name>.text`](https://rycee.gitlab.io/home-manager/options.html#opt-home.file._name_.text) -- more specifically, `home.file.".ideavimrc".text`.

**Comment by btomasini** [comment]
Thank you! That looks like it should do what I want. I am new to nix and am unsure where to go next to discover the structure and syntax of the rest of the expression, including where to put the actual contents of the file. Where can I find such documentation?

**Comment by cole-h** [comment]
I actually linked to the documentation in my earlier comment. Here is an example of how I use `.text` and `.source`.

https://github.com/cole-h/nixos-config/blob/2ba44b448792ac7c811a673a9d34c6c4b8b4d8b6/users/vin/modules/gpg.nix#L4-L18

**Comment by btomasini** [comment]
Thank you. The example above with the multiple file paths and text is helpful.
