### ISSUE TITLE
Customizable .xprofile and .Xresources file location

### ISSUE THREAD

**Issue by soulsoiledit** [nix-community/home-manager#1505]
`.Xresources` and `.xsession` file location should be able to be configured to write to other locations such as `XDG_CONFIG_HOME/X11/.xsession` This would be helpful for users that want to follow XDG Base Directory specifications and avoid cluttering `$HOME`.

**Comment by rycee** [comment]
Perhaps `xsession.scriptPath` would work? For `~/.Xresources` it is the location expected by NixOS so you'd have to change it there first.

**Comment by soulsoiledit** [comment]
`xsession.scriptPath` works nicely. Does `.xprofile` have a similar issue where it's expected in that location by NixOS?

**Comment by rycee** [comment]
For `~/.xprofile` yes, it is referred to at that path in NixOS. It also references `~/.xsession` so if you change that value you will also have to create a custom desktop manager session. Something like https://discourse.nixos.org/t/opening-i3-from-home-manager-automatically/4849/8

**Comment by soulsoiledit** [comment]
Alright, thanks for the help! Your answer in that link seems to be what I'm looking for.
