### ISSUE TITLE
What is the intended way to use the stable version in NixOS 20.03 wtih flakes?

### ISSUE THREAD

**Issue by loewenheim** [nix-community/home-manager#1511]
### Issue description
The `bqv-flakes` branch is deprecated, `release-20.03` does not support flakes, and `master` is not compatible with NixOS 20.03. What is to be done? Should flake support be backported to the `release-20.03` branch?

**Comment by cole-h** [comment]
A backport PR should be opened. Should be as easy as copying the `flake.nix` (and adding `flake.lock` to `.gitignore`).

**Comment by loewenheim** [comment]
I've opened a PR. It wasn't quite as easy as adding `flake.nix`—some lines in other files had to be changed. It currently works on my machine :)

**Comment by cole-h** [comment]
Ah, right, I forgot about the other changes that made this possible. Oops.

**Comment by loewenheim** [comment]
Since `20.09` is out, this is moot.
