### ISSUE TITLE
[Feature Request] Control coc-nvim settings from home manager

### ISSUE THREAD

**Issue by sherubthakur** [nix-community/home-manager#1513]
### Issue description

This is a feature request. I have been using coc and right now it manages most of it's stuff using `coc-settings.json`. Now by default this will be outside of home-managers control. Which I am not a fan of. So I have been coping over that file from my settings [here](https://github.com/sherubthakur/dotfiles-NixOS/commit/b1b1bf2b34c5fe5dfa75d772032ff1d529f3032f). 
Now to the request. Do you think that we can provide first class support to configure coc with a settings file?

```nix
  programs.neovim = {
    enable = true;
    vimAlias = true;
    coc = {
        enable = true;
        plugins = with pkgs.vimPlugins; [ ...];
        settings = ./nvim/coc-settings;
    };
 };
``` 

#### Maintainer CC

No meta field is this module. The people who have touched the module include. @rycee , @teto , @Gerschtli , @rvolosatovs .

#### Technical details

Don't believe that this is required. `nix-shell -p nix-info --run "nix-info -m"`

Note: If this is something that you think we can add to this project, then I would like to contribute (assuming this is something simple and someone is willing to hand-hold through this task)!

**Comment by Gerschtli** [comment]
Hey, this seems to me like a valid approach. But I never used coc so there might be more input required from your side what needs to be configured.

So first off, what are the options you think are necessary? Do we really need a plugins list under the coc key or could you just use the plugins or configure options which are already present under programs.neovim? Is the settings file a valid json file and should its contents also be managed with nix? And what would be the structure of this settings file?

**Comment by sherubthakur** [comment]
Hey @Gerschtli

> So first off, what are the options you think are necessary?

I like to configure everything using vim config files. Coc's readme also suggests that. https://github.com/neoclide/coc.nvim#example-vim-configuration.

> Do we need a plugins list under the COC key or could you just use the plugins or configure options which are already present under programs.neovim?

This one is interesting as initially, COC used to manage its plugins. I believe it can still do but also allows for a vim plugin manager to do so, as outlined [here](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions). I have been personally using the vim default list in my nix config without any problems. So I believe that this should not be a problem. Still, I want to share the resources if someones else knows better.

> the settings file a valid JSON file? And what would be the structure of this settings file?

The settings file is a `jsonc` file (which is a superset of JSON). You can read about it [here](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file).

> and should its contents also be managed with nix?

I would like that yes. Given that it has info of your LSP-clients, which is an indispensable part of someone's dotfiles.

To start with I believe that only giving the ability to manage coc-settings file as a first-class config prop would be great. My assumption is that will help most people.

Does this cover all the concerns that you had?

P.S. I was not expecting such a quick response. So kudos on that!

**Comment by Gerschtli** [comment]
Alright, then I would suggest the following steps:

Check if the basic coc vim plugins are already present and built correctly in nixpkgs because this would be a requirement for this module.

After that you can start building a prototype of this module. I would suggest introducing a new option like programs.neovim.cocSettings which just accepts types.attrs. You can then easily translate this attribute set to json via nix builtins.

For the installation of the coc plugin, you either add it to programs.neovim.plugins as soon as cocSettings is set or provide a separate flag, I don't which ones better. Is coc usable without this file?

One thing to keep in mind: With config.neovim.configure this module enables a more customized plugin management where you can't easily inject the coc plugin, so add a hint in the option description.

Thank you for the kind words :)

**Comment by sherubthakur** [comment]
> Check if the basic coc vim plugins are already present and built correctly in `nixpkgs` because this would be a requirement for this module.

I believe that it is true, I have been using a few myself and they work perfectly fine, [coc plugins I use](https://github.com/sherubthakur/dotfiles-nixos/blob/master/home.nix#L263)

> After that you can start building a prototype of this module

Not sure what that means. 

> I would suggest introducing a new option like programs.neovim.cocSettings which just accepts types.attrs. You can then easily translate this attribute set to JSON via nix builtins.

I hope I will be able to figure this out.

> For the installation of the coc plugin, you either add it to programs.neovim.plugins as soon as cocSettings is set or provide a separate flag, I don't which ones better. Is coc usable without this file?

Given that coc can work out of the box without the settings file (although most people will probably need this at some point), I was thinking of a separate flag. Thoughts? Next, I should be able to dig up some areas where something similar is being done to guide me through.

I will try to get to this on the weekend, most likely. Also can you help me with
- suggestions on what language features I must absolutely know in order to achieve this?
- Code documentation / examples that can help me understand how it all works, coding guidelines, etc.

What I had in mind was breaking this task up (baby steps)
1. Just focus on adding an option like `programs.neovim.plugins.coc.enble` which can take a boolean value. The scope for this task would be to add the plugin to the list based on if this flag is set or not.
2. Then add ability to add a json file which will be copied over to the appropriate location on `switch`.
3. Then I add the ability to also use `types.attrs` in addition to file location (2nd task).

Does this look reasonable? How would you prefer it, all pieces as a single PR or multiple PRs. (I personally like small PRs).

Disclaimer: This would be my first time delving into something outside of web-dev stuff. So I might just get stuck! Please help me out in such cases.

**Comment by mogria** [comment]
I've been testing nvim-coc for some time so this may be helpful. I use this snippet in my home manager configuration to set the nvim-coc configuration for PHP autocompletion.

```
  xdg.configFile."nvim/coc-settings.json".text = ''
  {
    "suggest.enablePreview":  true,
    "diagnostic.displayByAle": true,
    "codeLens.enable": true,
    "languageserver": {
      "intelephense": {
          "command": "intelephense",
          "args": ["--stdio"],
          "filetypes": ["php"],
          "initializationOptions": {
              "storagePath": "/tmp/intelephense"
          }
      }
    },
  }
  '';
```

Then there's the builtin function `builtins.toJSON`

**Comment by Gerschtli** [comment]
Sorry for the late reply.

I think the basic concepts you need to grasp are how to define a module and a bit more related to your issue: understand how the neovim module works. I think most of the concepts needed for your case are understandable just by reading the module.

Instead of multiple PRs I would suggest one where one can see the whole solution. This allows a more in-depth discussion if needed and does not require home-manager to support the json file input **and** the attrs option in the final module as backwards compatibility is a thing to consider.

So to start, just read the neovim module and maybe some others in home-manager. Afterwards create all needed options, add coc to plugin list and create the config file in the `config` section, test it and create a PR :)

If you have questions to a problem you are facing, don't hesitate to ask :)

**Comment by sherubthakur** [comment]
@mogria apologies on the late reply I was stuck with some work.
I am doing something similar in my dotfiles too. I plan to do support for file and attribute set (which will later be converted to a JSON). As outlined in ----

> 2. Then add the ability to add a json file which will be copied over to the appropriate location on switch.
> 3. Then I add the ability to also use types.attrs in addition to a file location (2nd task).

If you are hinting at something else, then I am not sure I was able to understand. Are you suggesting this feature would be a welcome addition for you too (It sure is for me) or something else?

@Gerschtli no probs, I myself did not get a chance to work on this.

> Instead of multiple PRs I would suggest one where one can see the whole solution.

Cool. That reasoning also makes sense to me. I will try to get to this feature as soon as possible.

**Comment by mogria** [comment]
@sherubthakur I was considering whether using `builtins.toJSON` to generate the JSON file from a nix expression. The other option, as you suggested would be to add a JSON file to be copied when building the home-manager configuration.


Should this go into the neovim module or into a separate `nvim-coc` module or something?

As I'm interested in this feature, I'd like to help out if possible.
