### ISSUE TITLE
Fail to use master branch for flake.

### ISSUE THREAD

**Issue by LEXUGE** [nix-community/home-manager#1519]
### Issue description

Since `bqv-flake` is deprecated, I am trying to migrate to master branch. However, as I used it like that in README, it gave me errors like:
```
at: (211:11) in file: /nix/store/g1k7afvd578l1gqyljia2ycj1irxc91x-source/modules/modules.nix

   210|         else
   211|           <nixpkgs>);
      |           ^
   212|       _module.args.pkgs = lib.mkDefault pkgs;

cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)
```

The code https://github.com/nix-community/home-manager/blob/84bcce3c252b9e6736a455b02a991b6a220dda8a/modules/modules.nix#L211 should not reference to `<nixpkgs>`. I am not sure what's going on here.

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.6, NixOS, 21.03.20200915.441a7da (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `"nixos-21.03pre243690.441a7da8080, nixpkgs-21.03pre243690.441a7da8080"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rycee** [comment]
Do you have `home.stateVersion = "20.09";` in your configuration?

**Comment by LEXUGE** [comment]
Yes, that's exactly where the problem originated. Thanks.
