### ISSUE TITLE
Single keybind in sway config removes rest

### ISSUE THREAD

**Issue by timsofteng** [nix-community/home-manager#1520]
Hello. When I try to map just one single shortcut in `config.keybindings` of `sway` it works but removes all sway's bindings. However I do not want to rewrite all keybindings for few custom options in config. Can I somehow prevent this behavior?

**Comment by alexarice** [comment]
See https://rycee.gitlab.io/home-manager/options.html#opt-wayland.windowManager.sway.config.keybindings . You can use `lib.mkOptionDefault` to not override all the keybindings
