### ISSUE TITLE
Sway binding question

### ISSUE THREAD

**Issue by timsofteng** [nix-community/home-manager#1521]
Hello.
Can you help me please?
Here is sample of raw sway config. 
How can I bind something like this in `home-manager` keybindings for sway? 
`bindsym --release Print exec grim -g \"$(slurp)" - | wl-copy`

Thanks

**Comment by berbiche** [comment]
Something like the following would work.

``` nix
let
  grim = "${pkgs.grim}/bin/grim";
  slurp = "${pkgs.slurp}/bin/slurp";
in
wayland.windowManager.sway.config.keybindings = {
  "--release Print" = ''exec ${grim} -g \"$(${slurp})" - | wl-copy''
}
```

I'm not sure what the `exec` part is going to expand to, but the keybinding is valid.
You can have as many modifiers as you want: `"--release --locked --no-repeat Print" = "....."`

I plan on opening a PR tomorrow to validate the configuration at build time.

**Comment by timsofteng** [comment]
> Something like the following would work
> 
> ```nix
> let
>   grim = "${pkgs.grim}/bin/grim";
>   slurp = "${pkgs.slurp}/bin/slurp";
> in
> wayland.windowManager.sway.config.keybindings = {
>   "--release Print" = ''exec ${grim} -g \"$(${slurp})" - | wl-copy''
> }
> ```
> 
> I'm not sure what the `exec` part is going to expand to, but the keybinding is valid.
> You can have as many modifiers as you want: `"--release --locked --no-repeat Print" = "....."`
> 
> I plan on opening a PR tomorrow to validate the configuration at build time.

Thanks. It works. But can I do it without variables declaration?

**Comment by berbiche** [comment]
1. You could replace the variables in the `exec` command with their value
2. If you add `grim` and `slurp` to your `home.packages`, then these packages will be made available in your environment and to Sway. The downside is that the dependence on these programs become implicit and thus if you ever remove these packages from your `home.packages` you will have a breakage
