### ISSUE TITLE
Can't set NIX_PATH in xsession managed by home-manager

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#1528]
### Issue description

I'm using home-manager on Fedora. I can't find any way to configure `NIX_PATH` to the value I want on X. Nevertheless, `NIX_PATH` has the proper value in ttys.

My `~/.xsession` is generated by home-manager. I have set the following variables to the value I want (i.e., `/home/cassou/Documents/projects/nix-system`):

- `pam.sessionVariables.NIX_PATH`
- `systemd.user.sessionVariables.NIX_PATH` 
- `home.sessionVariables.NIX_PATH`

Here is a shell session after a reboot:

```session
$ echo $NIX_PATH
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs:/nix/var/nix/profiles/per-user/root/channels:/home/cassou/.nix-defexpr/channels

$ cat ~/.pam_environment 
NIX_PATH OVERRIDE="/home/cassou/Documents/projects/nix-system"

$ cat ~/.config/environment.d/10-home-manager.conf 
NIX_PATH=/home/cassou/Documents/projects/nix-system

$ systemctl --user show-environment | grep NIX_PATH
NIX_PATH=/home/cassou/Documents/projects/nix-system

$ grep NIX_PATH ~/.nix-profile/etc/profile.d/hm-session-vars.sh 
export NIX_PATH="/home/cassou/Documents/projects/nix-system"

$ grep NIX_PATH ~/.nix-profile/etc/profile.d/nix.sh 
    # Append ~/.nix-defexpr/channels to $NIX_PATH so that <nixpkgs>
    export NIX_PATH=${NIX_PATH:+$NIX_PATH:}$HOME/.nix-defexpr/channels
```

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.11-200.fc32.x86_64, Fedora, 32 (Workstation Edition)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `""`
 - nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`

**Comment by evanjs** [comment]
Per the [IRC](https://logs.nix.samueldr.com/home-manager/2020-09-28#4032544;), this seems to have been solved by setting `xsession.profileExtra` and `xsession.initExtra`, though I am unsure if both or only one of these options is required.

**Comment by DamienCassou** [comment]
I wouldn't say "solved", but you indeed gave me a workaround :-).
