### ISSUE TITLE
`neovim` module should also provide a runtime option

### ISSUE THREAD

**Issue by cole-h** [nix-community/home-manager#1534]
### Issue description

Seeing https://github.com/NixOS/nixpkgs/pull/98506 (and the runtime option's support for adding tree-sitter grammars), it would be great to have this in home-manager as well. `:TSInstall rust` doesn't work, because it tries to move the grammar.so to `/nix/store/..........-vim-pack-dir/pack/home-manager/start/nvim-treesitter/parser/rust.so` (which obviously fails).

#### Maintainer CC
cc @teto 

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.10-zen1, NixOS, 21.03.20200929.dirty-cosmere (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200923_8d9402f`
 - channels(vin): `""`
 - channels(root): `""`
 - nixpkgs: `/home/vin/.config/nixpkgs/compat`

**Comment by teto** [comment]
with home-manager you could do  `home.file."${config.xdg.configHome}/nvim/parser/c.so".source = "${pkgs.tree-sitter.builtGrammars.c}/parser";`.
My idea with the neovim module was to get a temporary workaround while making it possible to generate a user runtime somewhere in the store, that could be leveraged later by home-manager as well.

**Comment by cole-h** [comment]
That indeed works. Thanks! I guess the runtime option isn't necessary (yet), then :)

**Comment by cideM** [comment]
FYI `:TSInstall rust` should actually work in Nix since I added a few lines of code to `treesitter` so it adds parsers to `XDG_DATA_HOME/nvim/share` when the default location is not writable

**Comment by teto** [comment]
shouldn't it install it in XDG_DATA_HOME/nvim/parser ?
