### ISSUE TITLE
[Question] direnv without home-manager managing my .bashrc

### ISSUE THREAD

**Issue by pmiddend** [nix-community/home-manager#1539]
### Issue description

Not sure if this is a bug or an oversight, so I hope posting this here is okay.

I'm not managing my `.bashrc` with home-manager (it's provided by my distribution and I'm hesitant to replace it). I did source the `hm-environment` thingy in `.profile`, though. I activated direnv's bash integration (via the home-manager configuration option `enableBashIntegration`) and then switched to a new profile. This doesn't work, however, because the bash integration writes to `.bashrc` (via `programs.bash.initExtra`).

Shouldn't there be a setting "home manager manages bashrc" or something, so we can have bashrc additions without home-manager completely replacing the file? Am I overlooking something?

**Comment by piegamesde** [comment]
I think the best way would be to have the distribution's `bashrc` at the global location (`/etc/` or the like), so that you are free to manage you local one through home-manager.

A quick fix however is to simply redirect the text to a file that you source (untested code):

```nix
home.file.".profile.d/bash_init_extra".text = config.programs.bash.initExtra;
```
