### ISSUE TITLE
Start system i3 but do generate config file

### ISSUE THREAD

**Issue by bobismijnnaam** [nix-community/home-manager#1541]
### Issue description

I am (mostly) happily using home-manager on ubuntu (20.04). I also have my i3 configured in `home-manager`to have the config file generated by `home-manager`, which is what I want and like. But, it also means when I run `home-manager switch`, the nix i3 is started, which is what I don't want. Instead, I would like home-manager to either:

1. Not restart i3.
2. Restart i3 using the i3 installed by ubuntu, not nix.

The reason I want to use the ubuntu i3 is because I think nix i3 cannot find the nvidia drivers, which I think make it stutter sometimes. (Any tips on investigating this are welcome, but it wasn't the primary purpose of making this issue.)

Is there a way to tell `home-manager` to do one of the above options? If not, if I were to add it, would it be a welcome contribution? Or is this very much against the idea of nix/`home-manager`? If trying to do this is against the idea of nix/`home-manager`, what could be a better way to approach this?

#### Maintainer CC

@alexarice 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-48-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(bobe): `"home-manager-20.03, nixpkgs-20.03.3087.b4db68ff563"`
 - nixpkgs: `/home/bobe/.nix-defexpr/channels/nixpkgs`
```

**Comment by alexarice** [comment]
From what I can see the nix `i3` shouldn't be starting. The module uses the nix `i3-msg` to give a reload message to the running `i3`.

**Comment by bobismijnnaam** [comment]
I see, then the stray i3 version in my `.nix-profile` is not the problem. Thank you for having a look.
