### ISSUE TITLE
Feature request: systemd user mounts

### ISSUE THREAD

**Issue by vojta001** [nix-community/home-manager#1542]
Hello,
I would very much appreciate being able to set systemd user mount units using home manager the same way as we set services, timers etc. For me, it looks like it is just about doing minor tweaks in `modules/systemd.nix` and adding a new line to

[https://github.com/nix-community/home-manager/blob/4ebb7d1715d77269e8bf0eea3c84c8f8e8cd5caa/modules/systemd.nix#L210-L225](https://github.com/nix-community/home-manager/blob/4ebb7d1715d77269e8bf0eea3c84c8f8e8cd5caa/modules/systemd.nix#L210-L225)

however, I would like to ask you, whether it is that simple.

**Comment by berbiche** [comment]
Closing since #1629 was merged
