### ISSUE TITLE
Feature request: create a file instead of linking it

### ISSUE THREAD

**Issue by voobscout** [nix-community/home-manager#155]
set ```security.pam.mount.enable = true;``` in global config and try this:

```nix
  home.file.".pam_mount.conf.xml".text = ''
    <?xml version="1.0" encoding="utf-8" ?>
    <!DOCTYPE pam_mount SYSTEM "pam_mount.conf.xml.dtd">
    <pam_mount>
      <volume fstype="fuse" path="encfs#/home/%(USER)/Yandex.Disk/vault" mountpoint="/home/%(USER)/.vault" options="nosuid,nodev" />
    </pam_mount>
    '';
```

Since now, the ".pam_mount.conf.xml" is a link to nix store, upon login, pam_mount doesn't work.

It's not really a problem of home-manager, but there's lots of code relying on files not being links, hence it'd be great to have some kind of mechanism for catering to this aforementioned code.

**Comment by rycee** [comment]
Yeah, I've been thinking about this, eventually I think we'll support this. It needs some careful thought though to be able to keep track of which files are managed by HM. In particular,

For now, though, I'd suggest to create the file "manually" using an activation script. Something like
```nix
{
  # …

  home.activation.createMyFiles = dagEntryAfter ["writeBoundary"] ''
    cp ${dotfiles/pam_mount.conf.xml} $HOME/.pam_mount.conf.xml
  '';

  # …
}
```

**Comment by voobscout** [comment]
Thanks for reply!
what should be done to make "undefined variable ‘dagEntryAfter’" disappear? I'm new to nix, I see that this is defined in lib/dag.nix, but how to use it?

**Comment by rycee** [comment]
For now you can try putting
```
{ lib, ... }:

with import <home-manager/modules/lib/dag.nix> { inherit lib; };
```
at the top of your configuration. This will hopefully be simplified a bit before too long.
