### ISSUE TITLE
`programs.starship.settings.character.symbol` no longer has any effect

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#1550]
### Issue description

The `programs.starship.settings.character.symbol` option used to work just fine, but now has no effect. For example,
```nix
  programs.starship = {
    enable = true;
    # See https://github.com/ohmyzsh/ohmyzsh/issues/6985#issuecomment-692576751.
    settings.character.symbol = "!";
  };
```
used to work, but now I just get the default:
```
~
❯ 
```

#### Maintainer CC
@marsam 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-48-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(skainswo): `"home-manager, nixpkgs-21.03pre245942.89281dd1dfe"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs`
```

**Comment by marsam** [comment]
Hi, thanks for the heads up. This is due the recent breaking changes in StarShip 0.45.0 https://starship.rs/migrating-to-0.45.0/#character
Can you give the following a try?
```diff
--- /tmp/old.nix
+++ /tmp/new.nix
@@ -1,5 +1,5 @@
   programs.starship = {
     enable = true;
     # See https://github.com/ohmyzsh/ohmyzsh/issues/6985#issuecomment-692576751.
-    settings.character.symbol = "!";
+    settings.character.success_symbol = "[!](bold green)";
   };
```

**Comment by samuela** [comment]
@marsam Nice, that works!

**Comment by marsam** [comment]
Cool! would you mind closing this issue?

**Comment by samuela** [comment]
Sute, but can we deprecate `programs.starship.settings.character.symbol` and update the docs first?

**Comment by marsam** [comment]
Oh I forgot about that. yes, we should update the docs
Currently, I'm brief on time, so I wont address it until the weekend

**Comment by samuela** [comment]
Also just realized that this doesn't change the failure symbol correspondingly, eg. 

<pre><font color="#06989A"><b>~</b></font> on <font color="#3465A4"><b></b></font> 
<font color="#4E9A06"><b>&gt;</b></font> ctrl-c

<font color="#06989A"><b>~</b></font> on <font color="#3465A4"><b></b></font> 
<font color="#CC0000"><b>❯</b></font> 

</pre>

**Comment by marsam** [comment]
addressed by https://github.com/nix-community/home-manager/pull/1670
