### ISSUE TITLE
home-manager xdg config placed in wrong directory

### ISSUE THREAD

**Issue by ztlevi** [nix-community/home-manager#1554]
### Issue description

Move the discussion here since this might be a bug or behavior change recently.

My home-manager’s home is defined under `/Users/ztlevi/Users/ztlevi`.

```hljs
ztlevi/.config/zsh took 2s
➜ pwd
/Users/ztlevi/Users/ztlevi/.config/zsh

ztlevi/.config/zsh
➜ ll
lrwxr-xr-x 100 ztlevi staff 12 Oct 21:18 extra.zshenv -> /nix/store/7pjlbwcvm5wql7cp4lmla6ccqixd0f6q-home-manager-files/Users/ztlevi/.config/zsh/extra.zshenv
lrwxr-xr-x  99 ztlevi staff 12 Oct 21:18 extra.zshrc -> /nix/store/7pjlbwcvm5wql7cp4lmla6ccqixd0f6q-home-manager-files/Users/ztlevi/.config/zsh/extra.zshrc
```

My home definition is over here [https://github.com/ztlevi/nix-dotfiles/blob/f053169c2d87a45757a460b5d2616470d7163f94/options.nix#L71-L86 2](https://github.com/ztlevi/nix-dotfiles/blob/f053169c2d87a45757a460b5d2616470d7163f94/options.nix#L71-L86)

#### Maintainer CC

Idk. Maybe someone helps me cc people who are aware of this.

#### Technical details

 - system: `"macos 10.15.6"`
 - host os: `macos`
 - multi-user?: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels: 
```
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

**Comment by anhdle14** [comment]
I have the same issue as well :(
