### ISSUE TITLE
Allow skipping the emacsWithPackages for the programs.emacs.finalPackage

### ISSUE THREAD

**Issue by terlar** [nix-community/home-manager#1556]
### Issue description
When I am using `emacsWithPackagesFromUsePackage` from [emacs-overlay](https://github.com/nix-community/emacs-overlay) I get a derivation that has already provided packages with `emacsWithPackages`. 

It works somewhat fine using that as `programs.emacs.package`, but gets a bit confusing since it is wrapping the already wrapped emacs and the issue is that the `EMACSLOADPATH` env variable becomes `emacsdepsdrv1out::emacsdepsdrv2out:`. When you have a termination like that, emacs load path itself will be added at the first empty load path, causing the packages from drv2 load after emacs builtin packages. This means you will get outdated version of org-mode etc.

Therefore I think it would be best if it was either possible to skip the emacsWithPackages for the finalPackage or if it was possible to override finalPackage.

I could set finalPackage, if I don’t enable the `programs.emacs.enable` and manually add it to `home.packages` instead. But the `services.emacs.enable` breaks as it checks that `programs.emacs.enable` is true.

#### Technical details
 Not relevant, but will do when I get to my computer.

**Comment by terlar** [comment]
Any idea what approach would be desired @rycee ? 

I can do the work, just wonder which approach is the most suitable to fit into home-manager.

I searched through the repo for the `finalPackage` convention to see if it was solved somewhere, but it is not so widespread (only emacs/nvim). Thanks!

**Comment by rycee** [comment]
Sorry for the delay. Yeah, I imagine that the `programs.emacs` module is not very useful if one uses `emacsWithPackagesFromUsePackage`.

I suspect the best would be to add a `services.emacs.package` option and default it to `config.programs.emacs.finalPackage` if `config.programs.emacs.enable == true`. Then you could override the package with your `emacsWithPackagesFromUsePackage` result and not use `programs.emacs` at all. It should be quite simple to implement.

I did consider the idea of making `programs.emacs` aware of `emacsWithPackagesFromUsePackage` but that would probably be quite tricky to do in a nice way. It might be worth considering adding a HM module in the `emacs-overlay` repo, though? I could add some nice wrapping of `emacsWithPackagesFromUsePackage` and assign the result package to the new `services.emacs.package` option.

**Comment by berbiche** [comment]
@terlar I think this can be closed now?

**Comment by terlar** [comment]
Yes, thank you for the reminder.
