### ISSUE TITLE
tmux - move config to XDG compliant location

### ISSUE THREAD

**Issue by peterhoeg** [nix-community/home-manager#1558]
### Issue description

tmux 3.1b supports the hardcoded location `~/.config/tmux/tmux.conf` in addition to `~/.tmux.conf` but the next version will honour `$XDG_CONFIG_DIR` so let's start using that instead.

I'll self-assign but if anyone else wants to, feel free.

@marsam @jorsn

**Comment by peterhoeg** [comment]
https://github.com/tmux/tmux/blob/master/Makefile.am#L14-L16

**Comment by teto** [comment]
XDG supports always gets a hourra from me. Go ahead and maybe add the change behind a stateVersion check.

**Comment by Ambroisie** [comment]
@peterhoeg the version on 20.09 is now 3.1c, what else is needed to add support for this?

**Comment by marsam** [comment]
A patch for this could be:
```diff
--- a/modules/programs/tmux.nix
+++ b/modules/programs/tmux.nix
@@ -335,10 +335,9 @@ in
         };
       })
 
-      # config file ~/.tmux.conf
-      { home.file.".tmux.conf".text = mkBefore tmuxConf; }
+      { xdg.configFile."tmux/tmux.conf".text = mkBefore tmuxConf; }
       (mkIf (cfg.plugins != []) configPlugins)
-      { home.file.".tmux.conf".text = mkAfter cfg.extraConfig; }
+      { xdg.configFile."tmux/tmux.conf".text = mkAfter cfg.extraConfig; }
     ])
   );
 }
```

but I'd wait until 3.2 is released because it adds `$XDG_CONFIG_HOME` to the search paths https://github.com/tmux/tmux/commit/f87be8d0521436c47151233f781794dee94fc1df, otherwise it would break if anyone sets `xdg.configHome` to a different path.

**Comment by NickCao** [comment]
Now that tmux 3.2 has been released, maybe we can make some progess?
[tmux: 3.1c -> 3.2](https://github.com/NixOS/nixpkgs/pull/119322)
