### ISSUE TITLE
use home-manager with nix 3 (on nixos)

### ISSUE THREAD

**Issue by 06kellyjac** [nix-community/home-manager#1561]
### Issue description

When I set my system wide `nix` package to `nix` 3 `home-manager` is still using `nix` stable
`nix.package = pkgs.nixUnstable;`

#### Maintainer CC

@rycee 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 21.03pre246543.24c9b05ac53 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager, nixos-21.03pre246543.24c9b05ac53, nixos-hardware"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

(I've currently not got `nix.package = pkgs.nixUnstable;` in my nixos config)

I install home-manager using channels:

nixos `configuration.nix`
```nix
{ config, pkgs, ... }:

let
  # ...
  hm = import <home-manager> {};
in {
  nix.package = pkgs.nixUnstable;
  # ...
  environment.systemPackages = with pkgs; [
    # ...
    hm.home-manager
  ];
  # ...
  system.stateVersion = "20.09";
}
```

**Comment by pickfire** [comment]
Home manager seemed to be running since I installed home manager before I switched to `nixUnstable`. But I cannot switch profile anymore.
```
error: --- Error -------------------------------------------------------- nix-env
profile: '/nix/var/nix/profiles/per-user/user/profile' is incompatible with 'nix-
env'; please use `nix profile` instead
```

**Comment by tgunnoe** [comment]
I have this error as well

**Comment by Tchekda** [comment]
Same here : 
```
$ nix-shell '<home-manager>' -A install

Creating initial Home Manager generation...

/nix/store/gxkhfsla7d3pxv9nx78hd1k34fx4jbsx-home-manager-generation
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix-env
profile '/nix/var/nix/profiles/per-user/tchekda/profile' is incompatible with 'nix-env'; please use 'nix profile' instead
```

**Comment by teto** [comment]
I use home-manager as a module with nixUnstable. My config is a bit of a mess but it usually works https://github.com/teto/home/blob/master/flake.nix

**Comment by berbiche** [comment]
Home Manager still uses nix-env to install the environment and with all the recent flake PRs this can be closed.
