### ISSUE TITLE
Auto repeat and interval

### ISSUE THREAD

**Issue by pickfire** [nix-community/home-manager#1568]
### Issue description

Add support for `services.xserver.autoRepeatDelay` and `services.xserver.autoInterval`. These settings may be different for users and a global settings probably would not be good.

**Comment by berbiche** [comment]
> These settings may be different for users and a global settings

Considering how home-manager is already user-centric and does not modify anything outside of the user's home, the option would not pose any problem.

It's just a question of doing an `xset r rate <rate> <delay>` somewhere.

**Comment by berbiche** [comment]
It could fit here: https://github.com/nix-community/home-manager/blob/28eb093a1e6999d52e60811008b4bfc7e20cc591/modules/xsession.nix#L88-L111
