### ISSUE TITLE
programs.firefox.profiles is not working for non-default profiles (Non-NixOS)

### ISSUE THREAD

**Issue by WolfangAukang** [nix-community/home-manager#1569]
### Issue description

I am trying to set up Firefox according to the home-manager settings. I can enable it and configure the extensions with no problem, but I am not able to set up profiles, except for the default one.

Here are the settings I'm trying to use:

```
...
firefox = {
      enable = true;
      enableGnomeExtensions = true;
      extensions = with pkgs.nur.repos.rycee.firefox-addons; [
        auto-tab-discard
        https-everywhere
        privacy-badger
        ublock-origin
      ];
      # TODO: Does not work from here.
      profiles = {
        default = {
          name = "Sandbox";
        };
        personal = {
          id = 1001;
          name = "Personal";
        };
      };
    };
...
```

I was thinking it would be related to #1216, but as said before, it is working with the default profile.

So, if I open Firefox and put `about:profiles`, this is what I get:
![Ekrankopio de 2020-10-24 09-39-25](https://user-images.githubusercontent.com/8378365/97085804-e4c47200-15dc-11eb-9cfe-e5d1d0ef23d0.png)

If I list the contents of `~/.mozilla/firefox`, I can see the profile folders being generated accordingly though:

```
ls .mozilla/firefox/
default  personal  profiles.ini
```

Finally, if I run `firefox -P <profile-name>`, no luck

```
> firefox -P Personal > /dev/null
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
```
But if I run `firefox --profile /home/bjorn/.mozilla/firefox/personal`, it throws the following errors, although it opens a window with the default profile:
```
console.error: SearchCache: "_readCacheFile: Error reading cache file:" (new Error("", "(unknown module)"))
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
```

What might be the cause of this issue?

#### Technical details

```
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/m52v606f8ni9gs7zl20bjqrbz09wx979-nix-info
copying path '/nix/store/m52v606f8ni9gs7zl20bjqrbz09wx979-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-7642-generic, Pop!_OS, 20.04 LTS`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(bjorn): `"home-manager, nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/home/bjorn/.nix-defexpr/channels/nixpkgs`
```

**Comment by berbiche** [comment]
Profile ids need to be sequential. This is currently undocumented in HM since this behavior is not documented by Firefox?

For instance, your default profile would have `id = 0`, your second profile would need to have `id = 1` and so on.

**Comment by WolfangAukang** [comment]
Can confirm this helped. It would be good to have this documented in Home Manager, something on the lines of "you are free to assign any number as the id as long as it is sequential".

Going to close this one. Thank you @berbiche.
