### ISSUE TITLE
Plasma browser integration extension does not work with the firefox installed by home-manager

### ISSUE THREAD

**Issue by poscat0x04** [nix-community/home-manager#1586]
### Issue description

The extension plasma-browser-integration does not work with firefox installed by home-manager but does work with the system's firefox (`/run/current-system/sw/bin/firefox`)(they are using the same package `pkg.firefox`)

**Comment by f4814** [comment]
Temporary workaround: `cp /run/current-system/sw/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json ~/.mozilla/native-messaging-hosts`

**Comment by CRTified** [comment]
That workaround works for me. I implemented it by adding this option, pulling `org.kde.plasma.browser_integration.json` from the package:
```nix
home.file.".mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json".source = "${pkgs.plasma-browser-integration}/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json";
```

In my opinion, it would be reasonable to either add an option to `enablePlasmaIntegration`, similar to `enableGnomeExtensions`, as [the firefox wrapper in nixpkgs already supports it](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/wrapper.nix#L68) (but I do not know if that would already solve the problem).

**Comment by WhiteAbeLincoln** [comment]
I solved this by copying the firefox module from home-manager and adding an option for an extraConfig, which gets passed to the package directly. This is what is already being done for the AdobeFlash and gnome extension options, they are just listed explicitly.

```diff
diff --git a/modules/programs/firefox.nix b/../dotfiles/program/firefox/module.nix
index eafeef4..91d6532 100644
--- a/modules/programs/firefox.nix
+++ b/../dotfiles/program/firefox/module.nix
@@ -3,6 +3,7 @@
 with lib;
 
 let
+  program-name = "firefox-custom";
 
   inherit (pkgs.stdenv.hostPlatform) isDarwin;
 
@@ -67,14 +66,14 @@ in
   meta.maintainers = [ maintainers.rycee ];
 
   imports = [
-    (mkRemovedOptionModule ["programs" "firefox" "enableGoogleTalk"]
+    (mkRemovedOptionModule ["programs" program-name "enableGoogleTalk"]
       "Support for this option has been removed.")
-    (mkRemovedOptionModule ["programs" "firefox" "enableIcedTea"]
+    (mkRemovedOptionModule ["programs" program-name "enableIcedTea"]
       "Support for this option has been removed.")
   ];
 
   options = {
-    programs.firefox = {
+    programs.${program-name} = {
       enable = mkEnableOption "Firefox";
 
       package = mkOption {
@@ -215,20 +207,11 @@ in
         description = "Attribute set of Firefox profiles.";
       };
 
-      enableAdobeFlash = mkOption {
-        type = types.bool;
-        default = false;
-        description = "Whether to enable the unfree Adobe Flash plugin.";
-      };
-
-      enableGnomeExtensions = mkOption {
-        type = types.bool;
-        default = false;
+      extraPackageConfig = mkOption {
+        type = types.attrsOf types.anything;
+        default = {};
         description = ''
-          Whether to enable the GNOME Shell native host connector. Note, you
-          also need to set the NixOS option
-          <literal>services.gnome3.chrome-gnome-shell.enable</literal> to
-          <literal>true</literal>.
+          Additional config options expected by the Firefox package
         '';
       };
     };
@@ -271,10 +254,7 @@ in
     home.packages =
       let
         # The configuration expected by the Firefox wrapper.
-        fcfg = {
-          enableAdobeFlash = cfg.enableAdobeFlash;
-          enableGnomeExtensions = cfg.enableGnomeExtensions;
-        };
+        fcfg = cfg.extraPackageConfig;
 
         # A bit of hackery to force a config into the wrapper.
         browserName = cfg.package.browserName

```

Use it by setting `programs.firefox-custom.extraPackageConfig.enablePlasmaIntegration = true`

**Comment by WhiteAbeLincoln** [comment]
Ideally we should open a pull request to make this a supported option. Rather than adding new options that get passed to the package wrapper, we should allow the user to pass in their own config, which allows for changes to the package without home-manager needing to be updated.

**Comment by WhiteAbeLincoln** [comment]
This also allowed me to add the tridactyl native messenger, which is another option that's supported in the nixpkgs firefox, but not here.

**Comment by berbiche** [comment]
I personally pass arguments like so:
``` nix
{
  programs.firefox.package = pkgs.firefox.override {
    cfg = {
      enableFXCastBridge = true;
      # other stuff
    };
  };
}
```
Note, the override does not trigger a rebuild of `firefox-unwrapped`, it only affects the wrapper.

**Comment by WhiteAbeLincoln** [comment]
Ah, I didn't know that was an option, I'll see if that works for me

— Abe White

**Comment by Ambroisie** [comment]
@berbiche I am trying to make `tridactyl-native` work on my `home-manager` configuration using your technique, however it does not seem to be working (asking `tridactyl` with the `:native` command tells me that it is not installed).

Is this an actual fully declarative setup, or is there something that I am missing?

**Comment by berbiche** [comment]
> @berbiche I am trying to make `tridactyl-native` work on my `home-manager` configuration using your technique, however it does not seem to be working (asking `tridactyl` with the `:native` command tells me that it is not installed).
> 
> Is this an actual fully declarative setup, or is there something that I am missing?
> 
> 

Sorry, I don't know.
I would suggest opening an issue on nixpkgs since the issue seems to be with the firefok package.

**Comment by poscat0x04** [comment]
this issue still exists

**Comment by ThibaultLemaire** [comment]
@berbiche 's [solution](https://github.com/nix-community/home-manager/issues/1586#issuecomment-736730953) works for me !

**Comment by ambroisie** [comment]
I think the issue can be closed, I do not experience this issue with `trydactyl-native`, when using the `cfg.package` override method.

**Comment by SuperSandro2000** [comment]
> Edit: supported configuration options can be found when grepping for `cfg` in [NixOS/nixpkgs@`c8a7e4d`/pkgs/applications/networking/browsers/firefox/wrapper.nix](https://github.com/NixOS/nixpkgs/blob/c8a7e4da0aac942485aad983a806840660fc9660/pkgs/applications/networking/browsers/firefox/wrapper.nix)
> 
> ```nix
> {
>   programs.firefox.package = pkgs.firefox.override {
>     cfg = {
>       enablePlasmaBrowserIntegration = true;
>     };
>   };
> }
> ```

This still needs to be implemented.

**Comment by ambroisie** [comment]
@SuperSandro2000 what do you mean?

**Comment by SuperSandro2000** [comment]
A home manager option to just enable this like there is for gnome.

**Comment by ambroisie** [comment]
I'm of the opinion that we can document it, point out how to find all options in nixpkgs (as package overrides are not documented in any meaningful way), but we should not write an option for each of the possible overrides, which are painful to keep in sync with nixpkgs.

**Comment by drupol** [comment]
When adding:

![image](https://user-images.githubusercontent.com/252042/170864322-86fb46ec-9148-4de8-a4a4-7408eb1bb296.png)

Then trying to `nixos-rebuild`, I get:

```
$ sudo nixos-rebuild switch --upgrade-all --flake path:///home/pol/Code/drupol/nixos-x260/ -v
$ nix --extra-experimental-features nix-command flakes build --out-link /tmp/nixos-rebuild.iCufm5/nixos-rebuild path:///home/pol/Code/drupol/nixos-x260/#nixosConfigurations."x260".config.system.build.nixos-rebuild -v
$ exec /nix/store/kl66mgvpiqnffql0ypsxll310zczinsf-nixos-rebuild/bin/nixos-rebuild switch --upgrade-all --flake path:///home/pol/Code/drupol/nixos-x260/ -v
building the system configuration...
Building in flake mode.
$ nix --extra-experimental-features nix-command flakes build path:///home/pol/Code/drupol/nixos-x260/#nixosConfigurations."x260".config.system.build.toplevel -v --out-link /tmp/nixos-rebuild.BtNQ90/result
error: attribute 'gtk3' missing

       at /nix/store/ny7x54058ki7k1d3ny0jx5h6kw926mxv-source/pkgs/applications/networking/browsers/firefox/wrapper.nix:186:23:

          185|       nativeBuildInputs = [ makeWrapper lndir jq ];
          186|       buildInputs = [ browser.gtk3 ];
             |                       ^
          187|
(use '--show-trace' to show detailed location information)
```

**Comment by drupol** [comment]
Adding

```nix
home.file.".mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json".source = "${pkgs.plasma-browser-integration}/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json";
```

Made it work ! Thanks @CRTified !

**Comment by x10an14** [comment]
For posterity. and those looking for a "complete" and "purely HM" soution:

![2022-09-10T00:56:04,168999909+02:00](https://user-images.githubusercontent.com/710608/189456276-f78f6e89-f830-4483-b2aa-2a7479f1a01d.png)

<details><summary>Code paste</summary>

```
{config, pkgs, ...}:
{
  programs.firefox = {
    enable = true;
    package = pkgs.firefox.override {
      cfg = {
        # Set nixkgs.legacyPackages.$system.pkgs.firefox.* options:

        # Enable pass-ff extension native messaging
        extraNativeMessagingHosts = [pkgs.passff-host];
      };
    };
  };

  # Install pass-ff extension required file:
  home.file.".mozilla/native-messaging-hosts/passff.json".source = "${pkgs.passff-host}/share/passff-host/passff.json";
}
```

</details>

**Comment by x10an14** [comment]
> For posterity. and those looking for a "complete" and "purely HM" soution:

Oops - wrong GH issue thread /embarassed. Tangentially related though.

**Comment by pluiedev** [comment]
Just for reference — since [nixpkgs commit `60421a1`], the `enablePlasmaBrowserIntegration` option has been deprecated. You should now do:
```nix
{pkgs, ...}: {
	programs.firefox.package = pkgs.firefox.override {
		cfg.nativeMessagingHosts.packages = [pkgs.plasma5Packages.plasma-browser-integration];
	};
	# ...
}
```

**Comment by woile** [comment]
For future reference, with `home-manager` this is what worked for me:

```nix
{
  programs.firefox.enable = true;
  programs.firefox.nativeMessagingHosts = [
    pkgs.firefoxpwa
    pkgs.kdePackages.plasma-browser-integration
  ];
}
```

And do not confuse with [programs.firefox](https://search.nixos.org/options?channel=unstable&query=programs.firefox.) on NixOS, which has a different interface.

**Comment by devurandom** [comment]
Instead of adding `pkgs.kdePackages.plasma-browser-integration` manually, I append the packages NixOS sets automatically:
```nix
{
  programs.firefox.nativeMessagingHosts = [
    # ...
  ] ++ osConfig.programs.firefox.nativeMessagingHosts.packages;
}
```
