### ISSUE TITLE
neovim's `viAlias`, `vimAlias` does not create symlinks.

### ISSUE THREAD

**Issue by jechol** [nix-community/home-manager#1590]
### Issue description

neovim's `viAlias`, `vimAlias` does not create symlinks.

#### Maintainer CC

@rvolosatovs
@uvNikita

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-52-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(jechol): `"home-manager, nixpkgs-21.03pre250093.0da76dab4c2"`
 - nixpkgs: `/home/jechol/.nix-defexpr/channels/nixpkgs`

**Comment by cole-h** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/102605.

**Comment by nasadorian** [comment]
@cole-h Is `nix-channel --update && home-manager switch` the correct way to get this update? So far I'm not seeing the symlink for `vim` working.

**Comment by cole-h** [comment]
That's because no channels have updated since that PR was merged. You'll have to wait for the next channel bump, whenever that is.

**Comment by nasadorian** [comment]
Thanks! Do I also need to switch to the `nix-community/home-manager` channel for recent updates? I'm still on the `rycee` one.

**Comment by cole-h** [comment]
The `rycee` one will redirect to this, but you should switch.

The channel I'm talking about are the nixos/nixpkgs channels, since the fix was made there. Updating your home-manager channel will not change that.

**Comment by nasadorian** [comment]
👍 Noted

**Comment by jechol** [comment]
@cole-h Thanks. Closing issue.
