### ISSUE TITLE
IDREF attribute linkend references an unknown ID "opt-home.file._name__.source"

### ISSUE THREAD

**Issue by Kronk74** [nix-community/home-manager#1592]
### Issue description

Hello, I'm new with Nixos and I'm trying to create a work environment with Nixos from scratch. 
I want to use home-manager to configure a personal configuration, but I've got this error below. 
I changed my nix channel to 20.09 as explained in another similar issue that I saw but the problem is still here. 
Any idea ?

`[tom@tomixos:~]$ home-manager switch 
these derivations will be built:
  /nix/store/2ms4h8fmzaqfap5g059mnkabhw25d0nm-manual-combined.drv
  /nix/store/6f69sdhn32v0v4cqhd0bw5fgpx2s39n8-manual-olinkdb.drv
  /nix/store/cb7ghfjr8xp1g5293rrxcv8ccjhqxid1-man-pages.drv
  /nix/store/gqnz8gnz15mx9pc0yy82ahiq6z8vrfrj-home-manager-path.drv
  /nix/store/8dnxj4mw2c6jcli2g9i9nizwng1vx3cx-activation-script.drv
  /nix/store/kdjq07x7c769hmh6bjjn0xh3czhflh3f-home-manager-generation.drv
building '/nix/store/2ms4h8fmzaqfap5g059mnkabhw25d0nm-manual-combined.drv'...

/nix/store/8a4av253s8bl6rmzz3lv5gbwwz1rpfpj-manual-combined/manual-combined.xml:11069: element xref: validity error : IDREF attribute linkend references an unknown ID "opt-home.file._name__.source"
 11065  <simpara>This release has the following notable changes:</simpara>
 11066  <itemizedlist>
 11067  <listitem>
 11068  <simpara>
 11069  The <xref linkend="opt-home.file._name__.source"/> option now allows source files to be
 11070  hidden, that is, having a name starting with the <literal>.</literal> character. It
 11071  also allows the source file name to contain characters not typically

/nix/store/8a4av253s8bl6rmzz3lv5gbwwz1rpfpj-manual-combined/manual-combined.xml fails to validate
builder for '/nix/store/2ms4h8fmzaqfap5g059mnkabhw25d0nm-manual-combined.drv' failed with exit code 3
cannot build derivation '/nix/store/cb7ghfjr8xp1g5293rrxcv8ccjhqxid1-man-pages.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/gqnz8gnz15mx9pc0yy82ahiq6z8vrfrj-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kdjq07x7c769hmh6bjjn0xh3czhflh3f-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/kdjq07x7c769hmh6bjjn0xh3czhflh3f-home-manager-generation.drv' failed
`

#### Maintainer CC

@rycee 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(tom): `"home-manager-20.09, nixos-20.09.1500.edb26126d98"`
 - channels(root): `"nixos-20.09.1500.edb26126d98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rycee** [comment]
Duplicate #1479
