### ISSUE TITLE
gnome-keyring doesn't set SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by bbigras** [nix-community/home-manager#1600]
### Issue description

If I run `systemctl status --user gnome-keyring` I see `SSH_AUTH_SOCK` but it's not set in my session. Is gnome-keyring expected to not set it?

#### Maintainer CC

@rycee

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-zen1, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre249162.1dc37370c48"`
 - channels(bbigras): `"home-manager"`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by berbiche** [comment]
I wonder whether this is the result of an upstream change since this used to work few weeks ago (in terms of nixpkgs unstable revisions)

**Comment by bbigras** [comment]
Can you reproduce @berbiche? I'm always wondering if the problem is only on my side.

**Comment by berbiche** [comment]
Yeah, I've had this problem for ~2 months maybe.
Never figured out what the issue was.

**Comment by woffs** [comment]
I have that problem, too. Working around with home.sessionVariables.SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"

**Comment by terlar** [comment]
Funny how I have the opposite problem, I constantly find gnome-keyring override this variable but in fact I want to use the one from gnupg. On NixOS it was possible by dropping in a desktop file in the profile and on Ubuntu I had to resort to adding it to the very last step in my shell init
