### ISSUE TITLE
alot should put the primary email first in account configuration

### ISSUE THREAD

**Issue by dcbaker** [nix-community/home-manager#1601]
### Issue description
Alot (the email client) sets the send mail address by default to the first entry in it's configuration, home-manger enters these in alphabetical order, which means that if my primary account is called "my_email" and my work account is called "acorp" then alot will always offer "acorp" as the first option, even though I've set the `primary` field to true only in "my_email".

**Comment by teto** [comment]
agreed, do you want to do it :) ?
