### ISSUE TITLE
Configuration of openssh via home-manager

### ISSUE THREAD

**Issue by 573** [nix-community/home-manager#1604]
Would it be possible to configure (manage /etc/ssh/sshd_config) OpenSSH via home-manager on a non-NixOS, using just nix ?

Thought loosely about two approaches

1) Similar to pkgs.kakoune-unwrapped using kind of a `myOpenssh = let sshd_config = ... in pkgs.openssh ...`
2) Configure pkgs.openssh inline somehow as in home.packages = [ ( ...<do config stuff>... in pkgs.openssh ) ]; 

but then again I wouldn't know how to do or if that's kind of crazy.

Could someone help with this or point at things ?

**Comment by berbiche** [comment]
`home-manager` only manages user-level configuration, so anything that resides in the user's home directory

**Comment by 573** [comment]
@berbiche makes perfect sense, hence the name *home*-manager I guess.

In my case I will resort to a managed custom location of the `sshd_config` file. Probably would be possible to write a derivation wrapping the sshd executable to use that location but that's beyond my ambitions right now.

```
xdg = {
    enable = true;
    configFile = {
      "ssh/sshd_config".text = ''
# ${xdg.configHome}/ssh/sshd_config
# config values ...
      '';
    };
};
```
