### ISSUE TITLE
Can no longer use `null` as `config.wayland.windowManager.sway.package`

### ISSUE THREAD

**Issue by jshholland** [nix-community/home-manager#1611]
### Issue description

Commit 7c3c64208e5696cac0e5bb70ac7d4cd04427882d changed a reference to `${pkgs.sway}` to point to `${cfg.package}` instead, to avoid redownloading a vanilla sway package if the user had customised that option. However, if the user has set that to null to use the NixOS wrapper, evaluation fails as it can't coerce the null to a string in the `onChange` script:
```
cannot coerce null to a string, at /nix/var/nix/profiles/per-user/root/channels/home-manager/modules/services/window-managers/i3-sway/sway.nix:398:18
```

The documentation for the `config.wayland.windowManager.sway.package` option should either be changed to explain that it can't be null any more, or a check for null should be done before attempting to interpolate in the  `onChange` script.

#### Maintainer CC

@alexarice (maintainer) @rycee (committed 7c3c642)

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03pre251971.a371c107116 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre252083.2deeb58f494, home-manager"`
 - channels(josh): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jshholland** [comment]
As a side-note, it's unclear to me what the difference is to the system-level NixOS sway wrapper and the home-manager one. At a quick glance, it seems like the home-manager one can replicates everything that the system one can do, but I'm not sure which one is better to use.

**Comment by alexarice** [comment]
This was probably an oversight when making the commit, though I think the home-manager wrapper has changed a lot since the advice to use the nixos one was made. The option to put the package as null might not be necessary anymore

**Comment by rycee** [comment]
Ah, sorry for the breakage. I'll revert the change and instead solve the problem I had in a different way.

**Comment by jshholland** [comment]
Thanks, that error is now solved.

However, there's a new one, also related to usage of `cfg.package`:
```
building '/nix/store/i3l7hqp9aj1gxlxss5jqgdl8an5cy3ns-sway-config.drv'...
building '/nix/store/a5mqfnhji9q37y8vajngzx1wk62fxmrj-options-db.xml.drv'...
/build/.attr-0: line 5: sway: command not found
Sway configuration validation failed
For a verbose log of the failure, run 'sway --config /nix/store/7lh3dacsdmxbchbk8wffsgkfc6cjaiwa-sway.conf --validate --debug'
builder for '/nix/store/i3l7hqp9aj1gxlxss5jqgdl8an5cy3ns-sway-config.drv' failed with exit code 1
cannot build derivation '/nix/store/5rm6ddi58g2pfyzb0xk39xvj2jlk3z0b-activation-script.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0nqfma86njhixa252z8nq51wmfpfhnhb-home-manager-files.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7kj4nc3bja16nk77ns56rp35c5i6cg8j-home-manager-generation.drv': 1 dependencies couldn't be built
```

Looking at the `checkSwayConfig` config definition on [lines 293-306 of sway.nix](https://github.com/nix-community/home-manager/blob/master/modules/services/window-managers/i3-sway/sway.nix#L293-L306), the `buildInputs` option is set to just `cfg.package`, which is null in my configuration. Presumably this is why it can't find the sway binary to check the config.

**Comment by berbiche** [comment]
See #1613

**Comment by rycee** [comment]
@jshholland Should be fixed now. Please give it a try.

**Comment by jshholland** [comment]
Yep, all fixed now. Thanks a lot!
