### ISSUE TITLE
--dry-run option not respected on darwin

### ISSUE THREAD

**Issue by kfiz** [nix-community/home-manager#1615]
### Issue description
Executing ``home-manager build --dry-run`` starts building packages on darwin. My expectation would be a behavior in line of with e.g. ``nix-env -f '<nixpkgs>' -iA package --dry-run``

#### Maintainer CC
@rycee

**Comment by berbiche** [comment]
Glancing at the installation script, I think `--dry-run` is only used when removing generations

**Comment by kfiz** [comment]
If this is how ``--dry-run`` is supposed to work, then I think this should be clarified in the ``man`` and ``help`` pages. + I would then add a feature request to implement a "proper" dry-run functionality. ;-)

**Comment by wlcx** [comment]
This is still a valid issue - `--help` gives no indication that `-n` is only for removing generations. I was trying to use it with `home-manager switch` and it gives the impression of doing nothing.
