### ISSUE TITLE
request: add a wlsunset service/module

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#1625]
### Issue description

It would be nice to have a module for `wlsunset`. Particularly because it's a light C application rather than requiring python (redshift, gammastep)

`wlsunset` is already in nixpkgs.

**Comment by colemickens** [comment]
I guess this will probably look a lot like `mako` does after this PR is complete: https://github.com/nix-community/home-manager/pull/1622

**Comment by matrss** [comment]
Hey, sorry for this mess, I didn't expect force pushing on my fork to spam this issue... I took the liberty to just go ahead and implement a module for `wlsunset` over at #1627, I hope that was ok. Would be great if you could take a look and see if this is what you had in mind.
