### ISSUE TITLE
msmtp fails with broken pipe error

### ISSUE THREAD

**Issue by MaxSchlueter** [nix-community/home-manager#1635]
### Issue description

With msmtp version 1.8.13 sending emails outputs an error (but succeeds in sending out the email):

`/nix/store/k89nm2jva0qmvd970f84wq2iq1iwm9bs-bash-4.4-p23/bin/bash: line 0: echo: write error: Broken pipe`

I figured out that this is because of the `passwordeval` option, removing the newline from the command output makes the error disappear. As of version 1.8.0 the newline is also not required anymore: https://marlam.de/msmtp/news/msmtp-1-8-0/

Something has changed in the implementation of the `passwordeval` option in the latest version of msmtp, since I don't see this error with version 1.8.12. Should this be fixed upstream or in home manager, e.g. not outputting the newline when msmtp version >= 1.8.0?

**Comment by delehef** [comment]
I experience the same error.

It can be worked around by adding `| tr -d '\\n'` at the end of your usual `passwordCommand`.

**Comment by berbiche** [comment]
@delehef are you using Home Manager 20.09? The fix was not backported to this release.

**Comment by delehef** [comment]
Ah, I see.

My bad, sorry for the noise.
