### ISSUE TITLE
gpg: cannot use multiple trusted-key

### ISSUE THREAD

**Issue by ju1m** [nix-community/home-manager#1644]
### Issue description
This should be allowed:
```
programs.gpg.settings.trusted-key = [
  "0xXXXXXXXXXXXXXXXX" 
  "0xYYYYYYYYYYYYYYYY" 
];
```
### Workaround
As a workaround, one can directly concatenate to `.gnupg/gpg.conf`:
```
home.file.".gnupg/gpg.conf".text = ''
  trusted-key 0xXXXXXXXXXXXXXXXX
  trusted-key 0xYYYYYYYYYYYYYYYY
'';
```

### Suggestion
`home-manager` could use `pkgs.lib.generators.toKeyValue` which has a `listsAsDuplicateKeys` option.

```
home.file.".gnupg/gpg.conf".text =
  pkgs.lib.generators.toKeyValue {
    mkKeyValue = key: value:
      if builtins.isString value
      then "${key} ${value}"
      else pkgs.lib.optionalString value key;
    listsAsDuplicateKeys = true;
  } {
  trusted-key = [
    "0xXXXXXXXXXXXXXXXX" 
    "0xYYYYYYYYYYYYYYYY" 
  ];
};
```
This also enables to print subkeys' fingerprint like this:
```
with-fingerprint = [ true true ]:
```

#### Maintainer CC
@SuprDewd @offlinehacker

**Comment by berbiche** [comment]
Would you be up to resolve this issue @ju1m?

**Comment by ju1m** [comment]
@berbiche thank you but I'm fine with the workaround and I've already given all what I can to help the maintainers improve the interface.
