### ISSUE TITLE
attribute 'anything' missing for neovim

### ISSUE THREAD

**Issue by Kazimazi** [nix-community/home-manager#1645]
Neovim wouldn't rebuild since 44f9d68d8c21aecda1cde153b72af5e99d367afe.
The error I get: 
```
at: (159:30) in file: /nix/store/gai9x1179xfn69rcnyxblp24wg55gsll-source/modules/programs/neovim.nix

   158|       configure = mkOption {
   159|         type = types.attrsOf types.anything;
      |                              ^
   160|         default = { };

attribute 'anything' missing
```
I have neovim configured with `extraConfig` and `plugins` options, which exclude `configure`
Poke: @berbiche

**Comment by berbiche** [comment]
If you track home-manager's master branch then we assume you also use nixpkgs-unstable.
I think it's now documented in the README?

There is two (easy) solutions:
1. Change your nixpkgs channel to nixpkgs-unstable
2. Change your home-manager channel to a versioned one (20.09 for instance) and make sure the nixpkgs version is the same release

**Comment by Kazimazi** [comment]
ahhh you are right changed hm to follow unstable, everything works

**Comment by akavel** [comment]
**NOTE:** Even with NixOS 20.09 and home-manager 20.09, this still didn't work for me when using *nixUnstable* (a.k.a. *nixFlakes*) in `/etc/nixos/configuration.nix`. Disabling *nixUnstable* made `home-manager switch` work again. (I think switching back to *nixUnstable* afterwards should be ok.)
