### ISSUE TITLE
~/.nix-profile not in path

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#1646]
I've tried for the first time a HM installation on ubuntu (multi-user install), with a nix installed by *apt*. 
I tried to do it with flakes since that's what I use on nixos.

It works well with one twist, the packages installed by home-manager are not in PATH which can be confusing.

I've searched if it was the nix-installer that added ~/.nix-profile or home-manager but I couldn't find where it was set and why it works for others.

**Comment by mjlbach** [comment]
Related, https://github.com/nix-community/home-manager/issues/688

I usually add `source $HOME/.nix-profile/etc/profile.d/nix.sh` which adds this to PATH

**Comment by teto** [comment]
thanks that looks very promising I will test and report.

**Comment by berbiche** [comment]
@teto update?
