### ISSUE TITLE
gh cli auth login does not work with the provided package.

### ISSUE THREAD

**Issue by dotKuro** [nix-community/home-manager#1654]
### Issue description

Running `gh auth login` for the first time after setting `programs.gh.enable = true;` in your home.nix will crash the gh cli with following error:

```
failed to authenticate via web browser: open /home/dotkuro/.config/gh/config.yml: read-only file system
```

#### Maintainer CC

@Gerschtli 

#### Technical details

I investigated the source code of the gh cli and it seems that it not only writes the hosts.yaml which is for authentication (and should not be managed from the package which is correct :+1: ) but it also writes the config.yaml and will fail to do so, because the file is managed from the package. This will cause the gh cli to crash and stop the authentication. 

I don't think that there is a way for a package to handle this correctly, I just wanted to document this issue. If anything the gh source code would need to be changed to not crash in this situation (which I think is reasonable, because people should be able to manage their configs them selfes), but I don't think this has a great chance of happening.

A current workaround would be: 
  - install the program by adding it to the home.packages list
  - login in with the cli
  - delete the config.yaml file
  - remove gh from the home.packages and use progams.gh.enable instead

**Comment by drewrisinger** [comment]
@dotKuro thanks for the workaround, I found the same issue yesterday. Have you filed an upstream issue at https://github.com/cli/cli? A quick search through the issues didn't find any related to this issue, so it's probably worth opening at least before assuming they won't fix.

**Comment by EncodePanda** [comment]
But the issue seems that the configuration of gh module in home-manager points to a file in storage, thus it can not be modified by gh

**Comment by Gerschtli** [comment]
Probably you should not try to use home-manager to manage gh config file when using gh tool to manage its config.. I do not know any way to fix this.

**Comment by EncodePanda** [comment]
Hmm... I'm confused :) 
Just to clarify: When enabling `gh` in `home-manager, you have few options you can modify (like git protocol to use) and once you `home-manager switch` it will translate that to a `.config/gh/config.yml` . But that config does not hold secretes (obviously) so when you run `gh` for the first time, it tries to modify this `config.yml` (to add missing bits). But since the file is just a symlink to store, this operation fails. I think this makes `gh` not suitable for `home-manager`. I'm actually installing  it via `home.packages`

**Comment by dotKuro** [comment]
@EncodePanda That is almost correct: Actually the secret of `gh` is stored in a seperate file to the config. Therefore the config can be managed using home manager, but when starting `gh` for the first time and creating a secret `gh` crashes in the moment it would create the config, because `gh` works internally in a way that it cannot write the secret with out having write permissions for the config file. It is just a little weird, but the config and the secret of `gh` are two different files.

**Comment by EncodePanda** [comment]
@dotKuro yes, you are 100% correct, maybe it is worth creating a ticket in gh

**Comment by samuela** [comment]
For anyone following along with the workaround, you have to add `pkgs.gitAndTools.gh` to `home.packages`, not `pkgs.gh`.

**Comment by samuela** [comment]
Bump, still an issue. I think we should either clearly document this behavior and/or open an issue upstream on gh.

**Comment by sumnerevans** [comment]
Also, since https://github.com/NixOS/nixpkgs/pull/109396, `gh` is in top-level `pkgs`.

**Comment by shinzui** [comment]
This is still an issue.

**Comment by sullyj3** [comment]
Created the upstream issue [here](https://github.com/cli/cli/issues/4955)

**Comment by sullyj3** [comment]
This has now been fixed

**Comment by berbiche** [comment]
Thanks for the update.
Now we just have to wait for it to reach nixpkgs.

**Comment by samuela** [comment]
This still hasn't reached nixpkgs AFAICT (just got the error now). Is there anything we can do to hasten it making it into nixpkgs?

**Comment by Invariance-NaN** [comment]
> This still hasn't reached nixpkgs AFAICT (just got the error now). Is there anything we can do to hasten it making it into nixpkgs?

@samuela are you sure it's this specific issue? I'm getting a similar error, but it's for `~/.config/git/config`, rather than `~/.config/gh/config.yml`.
