### ISSUE TITLE
simple way to declare options for all users

### ISSUE THREAD

**Issue by nrdxp** [nix-community/home-manager#1661]
I am looking for a simple way to set any option for all configured users. So in one file I would have my shared user configurations, and in other files I would have my per user configurations.

Is there a simple way to acheive this? Or could the feature possible be added?

**Comment by olmokramer** [comment]
Assuming you use Home Manager as a NixOS module, you could do something like below to set `services.foo.option` to `"value"` for all users configured in `config.users.users`

```nix
{ config, lib, ... }:

{
  home-manager.users =
    lib.filterAttrs (_: lib.getAttr "isNormalUser")
      (lib.mapAttrs (_: _: {
        services.foo.option = mkForce "value";
      }) config.users.users);
}
```

**Comment by berbiche** [comment]
Outside of olmokramer's answer, this would require adding a new option to the `home-manager` module, something like `home-manager.defaultModules`?

**Comment by nrdxp** [comment]
@olmokramer, your answer seems to cause infinite recursion in my setup.

**Comment by berbiche** [comment]
`home-manager.sharedModules` resolves the issue.

Closing this.
