### ISSUE TITLE
Installation failed. 'anything' missing, at ..."programs/matplotlib.nix"

### ISSUE THREAD

**Issue by bobfp** [nix-community/home-manager#1665]
### Issue description

Following the readme, and home-manager fails on installation.

```[bob@nixos:~]$ nix-shell '<home-manager>' -A install

Creating initial Home Manager configuration...

Creating initial Home Manager generation...

error: attribute 'anything' missing, at /nix/store/10p6r10mg4rcjn2y9r3zncxy0y813fqm-home-manager/home-manager/modules/programs/matplotlib.nix:26:28
(use '--show-trace' to show detailed location information)

There are 133 unread and relevant news items.
Read them by running the command 'home-manager news'.


Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

I have no clue what matplotlib is. It's not being referenced in any config files.
This is on a clean nixos install with minimal packages.

#### Technical details

``` 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.83, NixOS, 20.09.2290.647cc06986c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"home-manager, nixos-20.09.2290.647cc06986c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
 ```

**Comment by rycee** [comment]
You are using the master branch of Home Manager with the 20.09 branch of NixOS, which won't work because Home Manager master uses features that are only available on the unstable branch of NixOS.

You'll want to use the release-20.09 branch of Home Manager instead. See the installation instructions for more on how to do that.

**Comment by bobfp** [comment]
Thanks, that was it!
I updated the readme with language that might be less confusing. Feel free to close it if you disagree.
#1666

**Comment by a-h** [comment]
I did exactly the same thing. For anyone else that's wondering how to fix it:

Remove the old channel:

```
nix-channel --remove home-manager
```

And add the release version instead.

```
nix-channel --add https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz home-manager
```
