### ISSUE TITLE
Collision installing gc and clang

### ISSUE THREAD

**Issue by louhmmsb** [nix-community/home-manager#1668]
Just installed nixos, liked everything until now, but I can't install gcc and clang together, I get the following collision error:

`these derivations will be built:
  /nix/store/0cm7cchzzq21jsr7fdy9xbvmficjjqgz-home-manager-path.drv
  /nix/store/fy7z99h5x6r0qp2xm5qyiacxgn1z1g24-activation-script.drv
  /nix/store/mzrvxjh872m62qjkdky28qfp8277mryk-home-manager-generation.drv
building '/nix/store/0cm7cchzzq21jsr7fdy9xbvmficjjqgz-home-manager-path.drv'...
collision between `/nix/store/azayfhqyg9mjyv6rv9bcypi6ws8aqfmy-gcc-wrapper-9.3.0/bin/c++' and `/nix/store/16nynmdq4plmkhr6kg0isv0c21i7xsz5-clang-wrapper-7.1.0/bin/c++'
builder for '/nix/store/0cm7cchzzq21jsr7fdy9xbvmficjjqgz-home-manager-path.drv' failed with exit code 25
cannot build derivation '/nix/store/mzrvxjh872m62qjkdky28qfp8277mryk-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/mzrvxjh872m62qjkdky28qfp8277mryk-home-manager-generation.drv' failed`

**Comment by rycee** [comment]
Yeah, I guess it is a bit unfortunate that these packages packages both provide a c++ binary. Generally, though, it shouldn't be necessary to install a compiler in the user profile. Instead it is typically best to have a nix-shell setup for development. See, e.g., https://nixos.wiki/wiki/C for some descriptions. Also you might get help in #nixos on freenode.

**Comment by berbiche** [comment]
@louhmmsb hi, have you been able to resolve this issue?

**Comment by DearRude** [comment]
Any updates on this?

**Comment by berbiche** [comment]
This is expected, any two packages providing the same paths, when installed together in `home.packages`, `environment.systemPackages` or anything else that makes a directory tree of symbolic links, will clash and produce this error.

I highly recommend learning how to use [nix shells](https://nixos.wiki/wiki/Development_environment_with_nix-shell) to get around the need to have both in your global environment.

**Comment by delet-this** [comment]
> This is expected, any two packages providing the same paths, when installed together in `home.packages`, `environment.systemPackages` or anything else that makes a directory tree of symbolic links, will clash and produce this error.

Having both gcc and clang as is in `environment.systemPackages` works fine, but not when installed in `home.packages`. However, for some reason manually setting the priority e.g. `(hiPrio gcc)` makes the `bin/c++` conflict resolve with `home.packages` as well, allowing both packages to be installed.
