### ISSUE TITLE
Waybar module: add support for multiple instances of a bar module

### ISSUE THREAD

**Issue by jwijenbergh** [nix-community/home-manager#1682]
### Issue description
In waybar multiple instances of the same bar module can be defined by the following syntax:

```
"modules-right": ["battery", "battery#bat2"],
"battery": {
    "bat": "BAT1"
},
"battery#bat2": {
    "bat": "BAT2"
}
```
(taken from https://github.com/Alexays/Waybar/wiki/Configuration#multiple-instances-of-a-module),

When translating this to the nix module we get the following:
```
modules-right = [ "battery" "battery#bat2" ];
modules = {
  "battery" = {
    bat = "BAT1";
  };
  "battery#bat2" = {
    bat = "BAT2";
  };
};
```

When applying this, we get the following warning:
`The custom module 'battery#bat1' defined in 'programs.waybar.settings.[].modules' is not a valid module name. A custom module's name must start with 'custom/' like 'custom/mymodule' for instance`

While this is only a warning it is still annoying that we get this whenever we build the system, even though it is a perfect valid module. Any way https://github.com/nix-community/home-manager/blob/06543644266edcf845ac912002868246b58d19e6/modules/programs/waybar.nix#L43 can be adapted to allow for this syntax?

#### Maintainer CC
@berbiche 

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.84, NixOS, 20.09.2344.a3a3dda3bac (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2344.a3a3dda3bac, nixos-hardware, nixos-unstable-21.03pre257780.e9158eca70a, nixpkgs-unstable-21.03pre259358.b67ba0bfcc7"`
 - channels(jerry): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
Thanks. I will fix the check to account for specifying a CSS class.

**Comment by jwijenbergh** [comment]
Thanks @berbiche & @rycee for the quick response and fix. It works perfectly!
