### ISSUE TITLE
Error: "The option `home-manager.users.my-username.nixpkgs' does not exist"

### ISSUE THREAD

**Issue by pinpox** [nix-community/home-manager#1683]
### Issue description

When using the flakes [example](https://github.com/nix-community/home-manager#nix-flakes) from the `README.md`, I get an error when deploying the configuration:

```
The option `home-manager.users.pinpox.nixpkgs' does not exist. Definition values:
- In `/nix/store/3xscsdjqy9vkjrgxfzlxrapn14widcps-source/games.nix':
    {
      config = {
        retroarch = {
          enableBeetleLynx = true;
          enableBeetlePCEFast = true;
    ...
```

The lines causing errors are the ones referencing `nixpkgs.` e.g.:
```
  nixpkgs.config.retroarch = {
```
Or overlays defined like this:
```nix
  nixpkgs.overlays = [
    (self: super: {
      generated-gtk-theme = self.stdenv.mkDerivation rec {
        name = "generated-gtk-theme";
         ...
      };
    })
  ];
```

Not sure if this might be an error on my side, but how do I tell home-manger what nixpkgs to use?

In my system's configuration `flake.nix` I'm doing this:
```nix
      kartoffel = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./machines/kartoffel/configuration.nix
          ./machines/kartoffel/hardware-configuration.nix

          # User Profiles
          ./modules/user-profiles/pinpox.nix
          # Modules
          ./modules/bluetooth.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.pinpox = nixos-home.nixosModules.desktop;
          }
        ];
      };
```
### Meta

The full relevant configuration files are [here](https://github.com/pinpox/nixos/blob/0169e416974a458fa677b15246c4da5306c78829/flake.nix#L108) and [here](https://github.com/pinpox/nixos-home/blob/5398edebd3c02f15b2d395bdd55c5e88ab8daa59/flake.nix#L10)

The home-manager configuration works fine without using flakes, but I'm trying to deploy it with the system configuration as a flake, like shown in the README.

#### Maintainer CC
@rycee 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03.20201209.e9158ec (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rycee** [comment]
You cannot use `nixpkgs` options together with `home-manager.useGlobalPkgs`:
https://github.com/nix-community/home-manager/blob/5263fe459413a411e51355bfae5b5673b481dbe3/nixos/default.nix#L52-L56

You could try moving the
```
  nixpkgs.overlays = [
    (self: super: {
      generated-gtk-theme = self.stdenv.mkDerivation rec {
        name = "generated-gtk-theme";
         ...
      };
    })
  ];
```
configuration to the system level.

**Comment by rycee** [comment]
If the package needs values from the user configuration then you could try to define the package in the system configuration such that it takes the values as arguments. Similar to [`gtk.nix` in theme-base16](https://gitlab.com/rycee/nur-expressions/-/blob/6388aab2d86f518f85b267d594b00d99caa6e666/hm-modules/theme-base16/gtk.nix).

**Comment by pinpox** [comment]
>  This disables the Home Manager

Sorry, I didn't see that. But If I understand correctly, setting `useGlobalPkgs = true;` is required when using home-manager as a flake, correct?

**Comment by rycee** [comment]
Sorry, I don't know if `useGlobalPkgs` is necessary. Perhaps @roosemberth or @berbiche can say?

**Comment by pinpox** [comment]
@rycee Sorry to bother you, but I can't figure out how to get it working from your example. I modifyied the `flake.nix` in my home-manager repo to provide an output called `vars` which contains some variables like colors that I want to use in a package that is in the system-configuration repository.
```nix
{
  description = "A very basic flake";

  outputs = { self, nixpkgs }: {

    # packages.x86_64-linux.hello = nixpkgs.legacyPackages.x86_64-linux.hello;

    # defaultPackage.x86_64-linux = self.packages.x86_64-linux.hello;
    nixosModules = {
      desktop = { imports = [ ./home.nix ]; };
      server = { imports = [ ./home-server.nix ]; };
      vars = { imports = [ ./vars.nix ]; };
    };
  };
}

```

The system configuration then defines `vars` like this:
```nix
# pinpox-nixos/flake.nix

{
  description = "My machines";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager";
    nixos-home.url = "github:pinpox/nixos-home";
  };

  outputs = { self, nixos-home, home-manager, nixpkgs }:
  let
    # import colors
    vars = nixos-home.nixosModules.vars;
    desktopConfig = nixos-home.nixosModules.desktop;
  in
  {
    nixosConfigurations = {

      kartoffel = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./machines/kartoffel/configuration.nix

          ... other modules

          ./modules/generated-gtk.theme.nix
          home-manager.nixosModules.home-manager
          {
            # inherit vars;
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.pinpox = desktopConfig;
          }
        ];
      };
    };
  };
}
```

I tried follow your example for the `generated-gtk-theme.nix` module which is now in the system-wide repo.
```nix
# pinpox-nixos/modules/generated-gtk-theme.nix

{ config, pkgs, lib, ... }:
let
  themePkg = pkgs.callPackage ../packages/generated-gtk-theme { inherit vars; };
in {

  nixpkgs.config.packageOverrides = pkgs: rec {
    generated-gtk-theme = themePkg;
  };

  environment.systemPackages = with pkgs; [ generated-gtk-theme ];
}
```

But `{inherit  vars; }` errors, saying that the `vars` is undefined:
```
at: (3:64) in file: /nix/store/jw97hslzwpj4df13qnny6czgfdhcdp9x-source/modules/generated-gtk.theme.nix

     2| let
     3|   themePkg = pkgs.callPackage ../packages/generated-gtk-theme { inherit vars; };
      |                                                                ^
     4| in {

undefined variable 'vars'
```
Could you help me out here? I've been trying different approaches and combinations of options for hours and have no clue what I'm doing wrong.

**Comment by berbiche** [comment]
@rycee not sure about `useGlobalPkgs`.

@pinpox I don't see the `vars` variable in `pinpox-nixos/modules/generated-gtk-theme.nix`

**Comment by rycee** [comment]
I was thinking of something more along the lines of
```
nixpkgs.config.packageOverrides = pkgs: rec {
  generated-gtk-theme = pkgs.callPackage ../packages/generated-gtk-theme { vars = {}; };
};
```
in the system configuration and
```
gtk.theme.package = pkgs.generated-gtk-theme.override {
  vars = {
    # The actual colors.
    …
  };
};
```

**Comment by pinpox** [comment]
@rycee I've decided to revert my decision and keep using home-manager separately. The good news is, I got the gtk theme to build like you suggested! But adding home-manager as a flake is causing a lot of problems I didn't think about e.g.
- home-manager config needs to be pure: Stuff like fetchGit now will require a sha256, because flakes require pure inputs
- I have to use globalPkps as far as I can tell: Flakes don't allow for NIX_PATH since that's not pure either, so without globalPkgs the config fails to build.
- I need to change my (working) home-manager config quite a bit and I'm not sure I can keep it independent of the system configuration: I purpously have the user-specific stuff in a separate repo, so I can also use it for non-nixos machines. Not sure how to do this with flakes

The main reason I started investigating this was so that it can be deployed automatically on all servers. Since the setup is simple (just install home-manager, clone repo, switch to it) I'll just accept that I have to do that manually.

If someone has an example of a working solution I'll still be very curious on how it works.  I pretty sure there is a clean way of doing this, but I'm at this point not "fluent" with nix and nixos enough to find it. Thanks for all the help!

**Comment by roosemberth** [comment]
> Sorry, I don't know if useGlobalPkgs is necessary. Perhaps @roosemberth or @berbiche can say?

It's necessary since `<nixpkgs>` cannot be looked-up in pure evaluation mode (default when evaluating flakes).

**Comment by rycee** [comment]
With state version 20.09 or later, HM shouldn't use `<nixpkgs>` and instead use the path of the given `pkgs` argument. See https://github.com/nix-community/home-manager/blob/9d53afb709de005cd36886fa3f3d35243af7f67e/modules/modules.nix#L217-L221

So perhaps it would in principle, be possible to use `useGlobalPkgs = false`?

**Comment by roosemberth** [comment]
That's right, after setting `home-manager.users.foo.home.stateVersion = "20.09";`, I can remove `useGlobalPkgs` (and hence use `home-manager.users.foo.nixpkgs.config.allowUnfree = true;`).

**Comment by roosemberth** [comment]
The following flake.nix works:

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-20.09";
  inputs.home-manager.url =
    "github:nix-community/home-manager/release-20.09";
  inputs.home-manager.inputs.nixpkgs.follows = "nixpkgs";

  outputs = { self, nixpkgs, home-manager }: let
    defFlakeSystem = baseCfg: nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [({ ... }: {
        imports = [
          baseCfg
          home-manager.nixosModules.home-manager
          {
            #home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
          }
        ];
        # Let 'nixos-version --json' know the Git revision of this flake.
        system.configurationRevision = nixpkgs.lib.mkIf (self ? rev) self.rev;
        nix.registry.nixpkgs.flake = nixpkgs;
      })];
    };
  in {
    nixosConfigurations = {
      test = defFlakeSystem {
        imports = [
          {
            boot.loader.grub.device = "nodev";
            fileSystems."/".device = "/dev/sda2";
            home-manager.users.foo.home.stateVersion = "20.09";
            home-manager.users.foo.nixpkgs.config.allowUnfree = true;
            users.extraUsers.foo.extraGroups = ["wheel"];
            users.extraUsers.foo.isNormalUser = true;
            users.extraUsers.foo.password = "roos";
            users.mutableUsers = false;
          }
        ];
      };
    };
  };
}
```

**Comment by pinpox** [comment]
@roosemberth @rycee Awesome! I got it working and really don't know how to thank you, I had just about surrendered on getting this to work!

@rycee Would you be interested in a documentation for this? I can't yet say that I fully understand everything that is happening here, but if you think It could be useful for other people migrating to flakes I'd contribute a PR with more infos for the README

**Comment by rycee** [comment]
I think it would be great to have more documentation in general so any contribution is more than welcome, but I would much prefer it going in the manual instead of the already overloaded README file.

**Comment by rycee** [comment]
I'll close this issue since it seems to be resolved. Any (much appreciated) documentation improvements should go in a different issue or PR.

**Comment by pinpox** [comment]
@rycee Leave the Issue closed, just a small question: what's your workflow for editing the manual currently? The [linked](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#add-relevant-documentation) [docbook.rocks](https://docbook.rocks/) seems down and I'm not sure where this sections should go.

**Comment by rycee** [comment]
@pinpox Yeah, I noticed that the server is down a while ago, created https://github.com/grahamc/docbook.rocks/issues/2 for it. May have to link somewhere else. In any case, the documentation is more and more moving to [asciidoc](https://asciidoc.org/) so it should be fine to use that. I think it might be best to create a new chapter in the manual for the Flake stuff, could copy over the things from the readme there and expand as necessary. To add a chapter would just entail creating a `flake.adoc` file (similar to, e.g., `faq.adoc`) and an `<xi:include href="flake.xml" />` entry in `manual.xml`.
