### ISSUE TITLE
battery module

### ISSUE THREAD

**Issue by nico202** [nix-community/home-manager#170]
When not using a DE, it's difficut to have some useful utilities. The one I miss most by using i3, for example, is the low-battery check / ibernation and so on.

Maybe we could find a useful script and plug it in as a module. Right now I'm just using:
 
```nix
 systemd.user.services.check-low-battery = {
    Unit = {
      Description = "Home Manager Check Low Battery";
      # # To show notifications using notify-send
      # Requires = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      Environment = "PATH=${pkgs.libnotify}/bin";
      ExecStart = let
      script = ''
#!${pkgs.bash}/bin/bash
BATTINFO=$(${pkgs.acpi}/bin/acpi -b)
if [[ $(echo $BATTINFO | ${pkgs.gnugrep}/bin/grep Discharging) &&
$(echo $BATTINFO | ${pkgs.coreutils}/bin/cut -f 5 -d " ") < 00:30:00 ]]; then
DISPLAY=:0.0 ${pkgs.libnotify}/bin/notify-send "low battery" "$BATTINFO"
fi
'';
      in "${pkgs.writeScriptBin "check-low-battery" script}/bin/check-low-battery";
      IOSchedulingClass = "idle";
    };
  };
  systemd.user.timers.check-low-battery = {
    Unit = {
      Description = "Home Manager Check Low Battery";
      # # To show notifications using notify-send
      # Requires = [ "graphical-session.target" ];
    };

    Timer = {
      OnCalendar = "*:0/1";
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };
```
maybe somebody has better ideas /knowledge
  
edit: fixed timer

**Comment by rycee** [comment]
I searched around for a nice solution for the battery monitoring. Many seem to use something along the lines of your shell solution. I did find [Battery Monitor](https://github.com/maateen/battery-monitor/) which in principle looks nice but it doesn't appear to be in Nixpkgs. Having a quick look at the code it seems to make quite a few assumptions about system paths so adding it may not be the simplest.
