### ISSUE TITLE
Suggestion: msmtp writes account config before extraConfig

### ISSUE THREAD

**Issue by Vonfry** [nix-community/home-manager#1707]
Currently, it loads `programs.msmtp.extraConfig` before `accounts.<name>.msmtp.extraConfig`. Some one may want to code some `account <new> : <old one>` which cannot be done easily in `accounts.<name>.msmtp.extraConfig`

https://github.com/nix-community/home-manager/blob/cf5dad76c1ee452224da39f13129c4ff84351a5c/modules/programs/msmtp.nix#L37-L39

**Comment by Vonfry** [comment]
Now, the feature can be worked as following:
```
  xdg.configFile."msmtp/config".text = with lib; mkAfter
    (concatStringsSep "\n"
      (map aliasesToMsmtp config.<name>.net.email.aliases));
```

But it may be better to use extraConfig option instead of this.

**Comment by rycee** [comment]
I think the `extraConfig` has to stay at the top since the `defaults` section otherwise wouldn't apply to the generated accounts.

Maybe the simplest would be to create an option `extraAccounts` that goes at the end of the file?
