### ISSUE TITLE
Possible to implement force option for programs as well?

### ISSUE THREAD

**Issue by shadowrylander** [nix-community/home-manager#1709]
### Issue description

As the title states, I was wondering whether it would be possible to implement a `force` option for programs as well, such as `emacs.force = true;`, which would forcibly [re]create `.emacs.d`; this is so that, if I have a previously existing dotfiles structure that I've migrated to home-manager (as I have), I can replace the original files all in one go, as well as any files created automatically by other applications without my knowledge.

**Comment by rycee** [comment]
Perhaps the `-b` option would be sufficient? Something like `home-manager -b bck switch` to move the existing file out of the way.

See the description for `-b extension` here: https://rycee.gitlab.io/home-manager/tools.html#idm140737311939088

**Comment by shadowrylander** [comment]
Is there a way to use this with the NixOS config itself while rebuilding?

**Comment by berbiche** [comment]
IIRC `home-manager.backupExtension`

**Comment by shadowrylander** [comment]
Is that in the appendix? Where could I find similar options?

**Comment by berbiche** [comment]
Sorry, the option `home-manager.backupFileExtension` is only available when using `home-manager` as a NixOS module or a nix-darwin module.
The only other possibility is what rycee is recommending.

**Comment by shadowrylander** [comment]
Oh, no, that's what my question was referring to initially.
