### ISSUE TITLE
parcellite: add clipit support

### ISSUE THREAD

**Issue by nico202** [nix-community/home-manager#171]
https://github.com/rycee/home-manager/blob/aa1bf31bcbf44ae4722c4514210bdfa8273e4497/modules/services/parcellite.nix#L8

Clipit is a fork of parcellite, I prefer it since it has more functionalities. Maybe a general "clipboard manager" module with a selectable package among the ones available under nixpkgs would be better

Thanks, Nicolò

**Comment by makefu** [comment]
This is what i use in my configuration:
```nix
  systemd.user.services.clipit = {
    Unit = {
      Description = "clipboard manager";
      After = [ "graphical-session-pre.target" ];
      PartOf = [ "graphical-session.target" ];
    };

    Install = {
      WantedBy = [ "graphical-session.target" ];
    };

    Service = {
      Environment = ''
        XDG_DATA_DIRS=/etc/profiles/per-user/makefu/share GDK_PIXBUF_MODULE_FILE=${pkgs.librsvg.out}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
      '';
      ExecStart = "${pkgs.clipit}/bin/clipit";
      Restart = "on-abort";
    };
```
The `GDK_PIXBUF_MODULE_FILE` seems to be very important to show the correct icon. i'd love to see a better way to handle it. When gdk-pixbuf version changes this has to be changed as well.

**Comment by nico202** [comment]
Don't need to hardcode it maybe
```bash
$(find ${pkgs.libsrvg} -type f -name loaders.cache)
```

**Comment by nico202** [comment]
neither icon and gtk theme are working

**Comment by makefu** [comment]
weirdly it works for me ... i am using awesomewm in my setup
