### ISSUE TITLE
neovim extraPackages option doesn't play well with direnv

### ISSUE THREAD

**Issue by jlesquembre** [nix-community/home-manager#1739]
### Issue description

https://github.com/nix-community/home-manager/pull/1522 added a new option for neovim: `extraPackages`, that pre-pends some binaries to PATH. The problem is that it doesn't play well with direnv.
If I `cd` to a project, `direnv` automatically prepends some binaries to my PATH, but the wrapper script for neovim can potentially override the binaries added by direnv.
IMO, the `extraPackages` option should provide fallbacks, but the dependencies for a specific project declared with `direnv` should have a higher priority.

I suggest that we append to PATH instead of prepending. The only necessary change will to replace the `--prefix` here:
https://github.com/nix-community/home-manager/blob/8e0c1c55fbb7f16f9fd313275ddf63c97b34394c/modules/programs/neovim.nix#L246
with `--suffix`

That change also makes the behavior similar to the nixpkgs wrapper for neovim:

https://github.com/NixOS/nixpkgs/blob/d2e5ecabd2eb0ead2557f46fb3c5307bc67e43f2/pkgs/applications/editors/neovim/utils.nix#L95-L97

If that change sounds reasonable, I can create a PR

#### Maintainer CC
@beardhatcode 
@teto

**Comment by teto** [comment]
> MO, the extraPackages option should provide fallbacks, but the dependencies for a specific project declared with direnv should have a higher priority.

I tend to agree (though it's debatable). The most versatile way would be to allow home-manager to pass additionnal arguments directly to the wrapper.

**Comment by beardhatcode** [comment]
I also like this idea, I don't this would cause problems for anyone. Could you make a PR @jlesquembre

**Comment by teto** [comment]
I will most likely submit a neovim PR  soon, I can fix this along the way.
