### ISSUE TITLE
neovim: Some plugins doesn't work with config

### ISSUE THREAD

**Issue by thiagokokada** [nix-community/home-manager#1744]
### Issue description

I was migrating my configuration file to `programs.neovim` module and found issues in some plugins.

Minimal example:

```nix
{
  programs.neovim = {
    enable = true;

    extraConfig = ''
    '';

    plugins = with pkgs.vimPlugins; [
      {
        plugin = rainbow_parentheses;
        config = ''
          autocmd VimEnter * if &syntax != "off" | RainbowParentheses | endif
        '';
      }
      {
        plugin = onedark-vim;
        config = ''
          colorscheme onedark
        '';
      }
    ];
  };
}
```

Try to launch `nvim` and you will see tons of errors. You can comment one or another plugin to see individual errors.

If you don't try to configure those plugins they work fine if you call them manually (like `:RainbowParenthesisToggle` or `:set colorscheme onedark`), but of course this is manual process that nobody wants.

I think maybe those plugins are being lazy loaded? I switched to alternatives for now and it works, but it would be still interesting to fix this issue.

#### Maintainer CC

@teto @berbiche @rycee 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.7-zen1, NixOS, 20.09.2660.da3378c4aaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2660.da3378c4aaf"`
 - channels(thiagoko): `"home-manager-20.09, nixos-20.09.2660.da3378c4aaf, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by teto** [comment]
looking into this.

**Comment by thiagokokada** [comment]
As a workaround using `vim-plug` instead of native Neovim plugin manager works: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#managing-plugins-with-vim-plug

So maybe the issue is in the way those packages are packaged :thinking: ?

**Comment by teto** [comment]
hum I have a messy neovim setup and it seems to work fine. Are you able to debug this yourself ?  I can do the fixes afterwards.
It would help to see those errors.
What you describe make it sound like the plugins end up in the opt/ folder of packpath (but it's fine here). Could you look at the value of `:set packpath?` and check to see where your plugins are ?

**Comment by thiagokokada** [comment]
I think I understood the issue with `onedark` at least: https://github.com/joshdick/onedark.vim#installation

It seems it needs to manually copy `colors/onedark.vim` to a specific location, and afterwards you load the plugin. For some reason or another, `vim-plug` loads it correctly without any special procedure (maybe because this plugin is made to work with `vim-plug`?).

**Comment by teto** [comment]
please check the output of `:set packpath?` and also the value of `head nvim` if it's a wrapper or not. Maybe you could post the content of your ~/.config/nvim/init.vim

**Comment by thiagokokada** [comment]
```
packpath=/nix/store/yqdc53vp44p8mdq910ppszgyj2xfb962-vim-pack-dir,~/.config/nvim,/etc/xdg/nvim,~/.nix-profile/etc/xdg/nvim,/etc/profiles/per-user/thiagoko/etc/xdg/nvim,/nix/var/nix/profiles/default/etc/xdg/nvim,/run/current-system/sw/etc/xdg/nvim,~/.local/share/nvim/site,/nix/store/2yhzfickvq4lizss8gnbs4j1vi9n4bvh-desktops/share/nvim/site,~/.nix-profile/share/nvim/site,/etc/profiles/per-user/thiagoko/share/nvim/site,/nix/var/nix/profiles/default/share/nvim/site,/run/current-system/sw/share/nvim/site,/nix/store/zad527ykhg6fqvnx6rj3c161gr2kmqy1-neovim-unwrapped-0.4.4/share/nvim/runtime,/run/current-system/sw/share/nvim/site/after,/nix/var/nix/profiles/default/share/nvim/site/after,/etc/profiles/per-user/thiagoko/share/nvim/site/after,~/.nix-profile/share/nvim/site/after,/nix/store/2yhzfickvq4lizss8gnbs4j1vi9n4bvh-desktops/share/nvim/site/after,~/.local/share/nvim/site/after,/run/current-system/sw/etc/xdg/nvim/after,/nix/var/nix/profiles/default/etc/xdg/nvim/after,/etc/profiles/per-user/thiagoko/etc/xdg/nvim/after,~/.nix-profile/etc/xdg/nvim/after,/etc/xdg/nvim/after,~/.config/nvim/after
```

> Maybe you could post the content of your ~/.config/nvim/init.vim

I don't have one. I am not using `release-20.09`, and also can't backport the changes from `unstable` because some recent change in this module breaks it.

**Comment by teto** [comment]
if you look into /nix/store/yqdc53vp44p8mdq910ppszgyj2xfb962-vim-pack-dir can you see onedark in a `start` folder ? 
Instead of init.vim, look at /nix/store/lnc81pzbkvpgplbz9rm70bdklsg1qig4-vimrc.
I use only master but I can help you troubleshoot the issue.

**Comment by thiagokokada** [comment]
Well, it is really an issue with the `onedark-vim` itself. Following the `README.md` instructions, this works:

```nix
{
  configure = {
    customRC = ''
      packadd! onedark-vim
      colorscheme onedark
    '';
    packages.myVimPackage = with pkgs.vimPlugins; {
      opt = [ onedark ];
    };
  };
}
```

**Comment by teto** [comment]
but in the initial case, the plugins should appear in `start` and not `opt` that's probably why you see the error messages: the plugins are not loaded.

**Comment by thiagokokada** [comment]
This was the first think I tried @teto like I said in OP. And they also appeared fine in `start` directory.

I think this workaround of putting it in `opt` and calling `packadd! onedark-vim` is needed because of this split between the plugin and color directories.

**Comment by thiagokokada** [comment]
Just to completeness, I put `onedark` again in `start` and removed `packadd! onedark-vim` and got the same errors.

```
#! /nix/store/a3fc4zqaiak11jks9zd579mz5v0li8bg-bash-4.4-p23/bin/bash -e
export GEM_HOME='/nix/store/x6lzgy86ynmyzizwq26zzyvph30f2cfr-neovim-ruby-env/lib/ruby/gems/2.6.0'
export PATH=$PATH${PATH:+':'}'/nix/store/x6lzgy86ynmyzizwq26zzyvph30f2cfr-neovim-ruby-env/bin'
export NVIM_SYSTEM_RPLUGIN_MANIFEST='/nix/store/jn3yxn93abidrfqcjz3svw6g7dccp3vm-neovim-0.4.4/rplugin.vim'
export PATH='/nix/store/z1qvlavy35wanw5k54fvvfffws5bvigj-coreutils-8.31/bin:/nix/store/96kxirn7wzyb7jwbcknw48h1s2gf76h6-ctags-816/bin:/nix/store/ibnbgpvrh8shpqi26hn2vn1dwya04ap5-fzf-0.22.0/bin:/nix/store/vcsiys3jk8ql3q7fmvpm381lad8v5sll-git-2.29.2/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/zad527ykhg6fqvnx6rj3c161gr2kmqy1-neovim-unwrapped-0.4.4/bin/nvim"  '--cmd' 'let g:loaded_node_provider=1' '--cmd' 'let g:python_host_prog='\''/nix/store/jn3yxn93abidrfqcjz3svw6g7dccp3vm-neovim-0.4.4/bin/nvim-python'\''' '--cmd' 'let g:python3_host_prog='\''/nix/store/jn3yxn93abidrfqcjz3svw6g7dccp3vm-neovim-0.4.4/bin/nvim-python3'\''' '--cmd' 'let g:ruby_host_prog='\''/nix/store/jn3yxn93abidrfqcjz3svw6g7dccp3vm-neovim-0.4.4/bin/nvim-ruby'\''' -u /nix/store/dw0cpayh5nglxl0qzascl5pnpyyh45hy-vimrc "$@"
```

```
" configuration generated by NIX
set nocompatible






set packpath^=/nix/store/7kd6n86n4cpfq1gan5rc4d2kww70g65z-vim-pack-dir
set runtimepath^=/nix/store/7kd6n86n4cpfq1gan5rc4d2kww70g65z-vim-pack-di
```

```
❯ ls /nix/store/m1qkpzca8ckhr4n1wr3q3yfhq6xlf375-vim-pack-dir/pack/myVimPackage/start
auto-pairs  fzf-vim        rainbow        vim-better-whitespace  vim-fugitive   vim-lastplace  vim-sleuth    vim-vinegar
autoswap    lightline-vim  undotree       vim-commentary         vim-gitgutter  vim-polyglot   vim-sneak
fzf         onedark-vim    vim-automkdir  vim-endwise            vim-gutentags  vim-repeat     vim-surround
```

Welp, this is bizarre. Just because I added `onedark-vim` to `start` my `vimrc` didn't generated :thinking: ? If I move it to `opt` everything works as expected.

**Comment by thiagokokada** [comment]
Closing this since it looks like a problem with the plugin itself, not the module.

**Comment by teto** [comment]
seems like you hit https://github.com/nanotee/nvim-lua-guide#a-note-about-packages (which I wasn't aware at the time )

**Comment by refaelsh** [comment]
> seems like you hit https://github.com/nanotee/nvim-lua-guide#a-note-about-packages (which I wasn't aware at the time )

Link is broken.
