### ISSUE TITLE
Crash during home-manager switch with 20.09 channel

### ISSUE THREAD

**Issue by svrana** [nix-community/home-manager#1747]
### Issue description

Running home-manager switch -v has started to result in:

nix-build: src/libfetchers/tarball.cc:67: nix::fetchers::DownloadFileResult nix::fetchers::downloadFile(nix::ref<nix::Store>, const string&, const string&, bool, const Headers&): Assertion `request.expectedETag == res.etag' failed.
nix-build: src/libfetchers/tarball.cc:67: nix::fetchers::DownloadFileResult nix::fetchers::downloadFile(nix::ref<nix::Store>, const string&, const string&, bool, const Headers&): Assertion `request.expectedETag == res.etag' failed.
/home/shaw/.nix-profile/bin/home-manager: line 99: 26385 Aborted                 (core dumped) nix-build "<home-manager/home-manager/home-manager.nix>" "${extraArgs[@]}" "${PASSTHROUGH_OPTS[@]}" --argstr confPath "$HOME_MANAGER_CONFIG" --argstr confAttr "$HOME_MANAGER_CONFIG_ATTRIBUTE"
/home/shaw/.nix-profile/bin/home-manager: line 127: /tmp/home-manager-build.r740q71bRD/news-info.sh: No such file or directory

I'm using 20.09 channels for both home-manager and nixos/nixpkgs, i.e.,

cat .nix-channels
https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz home-manager
https://nixos.org/channels/nixos-20.09 nixpkgs
https://nixos.org/channels/nixos-unstable nixpkgs-unstable

Link to home-manager from .nix-defxpor/channels: 

I do use an occasional package from unstable.

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.91, NixOS, 20.09.2660.da3378c4aaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-20.09.2660.da3378c4aaf"`
 - channels(shaw): `"home-manager-20.09, nixpkgs-20.09.2660.da3378c4aaf, nixpkgs-unstable-21.03pre265130.f217c0ea7c1"`
 - nixpkgs: `/home/shaw/.nix-defexpr/channels/nixpkgs`

**Comment by svrana** [comment]
2.4pre... will try downgrading that as I'm not yet on the flake train so don't need it.

**Comment by berbiche** [comment]
@svrana see #1742

**Comment by rycee** [comment]
This is unrelated to Home Manager, see #1742.

**Comment by berbiche** [comment]
Closing as duplicate, feel free to continue the discussion over on #1742 if you need any help
