### ISSUE TITLE
KDE configuration file format

### ISSUE THREAD

**Issue by boredom101** [nix-community/home-manager#1750]
### Issue description
I was thinking the first step to adding support for kde config is to add support functions for the file format.
KDE uses a format similar to ini, but with a few specific things. Like internationalization built-in.
I could implement the function if it is desired.

**Comment by rycee** [comment]
@boredom101, you should consider adding that function to the
generators.nix file in Nixpkgs. There is already a toGitINI in there, so I imagine that a toKdeINI would be welcome. Then the functionality would be available to the entire Nix community, not just Home Manager.

**Comment by berbiche** [comment]
See #607
