### ISSUE TITLE
spotifyd updated config format from INI to TOML

### ISSUE THREAD

**Issue by jackmac92** [nix-community/home-manager#1754]
My spotifyd is broken due to a panic reading the config, tracking the error down it seems to be because spotifyd switched from ini to toml for config, causing issues with unquoted strings.

I think I could apply how home-manager writes toml [here in direnv](https://github.com/nix-community/home-manager/blob/118b36bf454556f93acc0bde526e8c85858f6e3b/modules/programs/direnv.nix#L76) to the [spotifyd module](https://github.com/nix-community/home-manager/blob/db88b625f9230154878db56e934e940d84f153bc/modules/services/spotifyd.nix#L10)

Does that sound right? I can send a PR if it does

**Comment by thiagokokada** [comment]
Yeah, looks good.
