### ISSUE TITLE
qutebrowser: newer version needs "load_autoconfig"

### ISSUE THREAD

**Issue by pmiddend** [nix-community/home-manager#1774]
### Issue description

Newer qutebrowser versions (I've tested with v2.0.1) show the following message on startup:

![2021-02-03_08-28](https://user-images.githubusercontent.com/178496/106712952-fe248380-65f9-11eb-8a5a-494e15473c73.png)

So we need some Nix configuration setting to get rid of it. I simply did the following:

```
  programs.qutebrowser = {
    enable = true;
    keyBindings = {
      normal = {
        "m" = "spawn mpv {url}";
      };
    };
    extraConfig = "config.load_autoconfig()";
  }
```

#### Maintainer CC

@seylerius @JonathanReeve @iv-nn @terlar @JustinLovinger 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-38-generic, Ubuntu, 20.04.1 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(pmidden): `"home-manager, nixpkgs-21.03pre267618.eca54e37ae5"`
 - nixpkgs: `/home/pmidden/.nix-defexpr/channels/nixpkgs`

**Comment by terlar** [comment]
Yeah, noticed this myself. I think we might want to introduce a boolean option that will add this to the config and either default to true or false, whatever makes sense.

**Comment by JustinLovinger** [comment]
@terlar I think that's a good approach. I'm inclined to default it to false (don't load settings from GUI), because GUI setting won't be in your Nix configuration and could cause reproducibility issues.

**Comment by pmiddend** [comment]
Thanks @berbiche  for fixing this!
