### ISSUE TITLE
newsboat: error when using external xdg-utils

### ISSUE THREAD

**Issue by jonjonw** [nix-community/home-manager#1777]
### Issue description

You can no longer use home-manager when using external xdg-utils.

When running `home-manager switch` I get the error:

```
error: attribute 'xdg-utils' missing, at /home/jon/.nix-defexpr/channels/home-manager/modules/programs/newsboat.nix:74:22
(use '--show-trace' to show detailed location information)
```

#### Maintainer CC
@rycee @MasseR 

#### Technical details

It looks like the offending line is `default = "${pkgs.xdg-utils}/bin/xdg-open";`. If you're running xgd-utils externally from nix and do not have the xdg-utils package installed in nix, if gives the error.

I tried setting `programs.newsboat.browser = "/usr/bin/xdg-open";` but still get the error (I guess the statement for the default still gets executed even if a value is set.

Output of `nix-shell -p nix-info --run "nix-info -m"`:

```
these paths will be fetched (40.99 MiB download, 179.31 MiB unpacked):
  /nix/store/25qhsb4lx6h9qxd2zs5y0vzqvqmj3njm-bash-interactive-4.4-p23-info
  /nix/store/3h27w2frml5vyim2sgadgc6z3bas19gv-nix-info
  /nix/store/7d2w3lafm8cla7n6ii5jskhsnqg4zv3a-stdenv-linux
  /nix/store/83zz05y2rh15y108ydkcmz3pl7bddccz-bash-interactive-4.4-p23-doc
  /nix/store/b96dqbx6pri2xp2xxlq6i269virrdaw6-gcc-wrapper-9.3.0
  /nix/store/bwxxmzqfnzdpkljsdw94sygi82fmjslb-bash-interactive-4.4-p23-dev
  /nix/store/g4c5gpchg4k21wwb99d224qqlp5wwrhh-bash-interactive-4.4-p23-man
  /nix/store/ip7xkk70anay3k7bp2cr6aqdg0mcdja2-binutils-wrapper-2.31.1
  /nix/store/jwcfz0gj6gkpivssldi024q3g6p5vklc-linux-headers-5.9.8
  /nix/store/kcp0y7g1ir4dxq2gqz687i4vb7gqy8s0-binutils-2.31.1
  /nix/store/myska9y3fhkymhkp6rn3zqrgjwyq9wx3-glibc-2.32-10-dev
  /nix/store/q7549l3ybw3r0zh6r7rfgv81qm5gz8cn-expand-response-params
  /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0
copying path '/nix/store/83zz05y2rh15y108ydkcmz3pl7bddccz-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/bwxxmzqfnzdpkljsdw94sygi82fmjslb-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/25qhsb4lx6h9qxd2zs5y0vzqvqmj3njm-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/g4c5gpchg4k21wwb99d224qqlp5wwrhh-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/kcp0y7g1ir4dxq2gqz687i4vb7gqy8s0-binutils-2.31.1' from 'https://cache.nixos.org'...
copying path '/nix/store/q7549l3ybw3r0zh6r7rfgv81qm5gz8cn-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/jwcfz0gj6gkpivssldi024q3g6p5vklc-linux-headers-5.9.8' from 'https://cache.nixos.org'...
copying path '/nix/store/3h27w2frml5vyim2sgadgc6z3bas19gv-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/myska9y3fhkymhkp6rn3zqrgjwyq9wx3-glibc-2.32-10-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ip7xkk70anay3k7bp2cr6aqdg0mcdja2-binutils-wrapper-2.31.1' from 'https://cache.nixos.org'...
copying path '/nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/b96dqbx6pri2xp2xxlq6i269virrdaw6-gcc-wrapper-9.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7d2w3lafm8cla7n6ii5jskhsnqg4zv3a-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.12-zen1-1-zen, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(jon): `"home-manager"`
 - channels(root): `"nixpkgs-21.03pre258655.00941cd747e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by berbiche** [comment]
Caused by https://github.com/nix-community/home-manager/pull/1775 ?
cc @rycee

**Comment by rycee** [comment]
Try updating your Nixpkgs channel. The package attribute name changed from `xdg_utils` to `xdg-utils` recently.

**Comment by jonjonw** [comment]
Thanks, I did run `nix-channel --update ` before getting the error but running it as root fixed the problem.

ie:
```sh
sudo nix-channel --update
```

**Comment by ryanbooker** [comment]
This is happening on macOS. `sudo nix-channel --update` didn't help (it created some extra warnings about name collisions.)

**Comment by berbiche** [comment]
@ryanbooker 
> This is happening on macOS. `sudo nix-channel --update` didn't help (it created some extra warnings about name collisions.)

Try the command without `sudo`.

Nix channels are user-level, so if you run `nix-channel --update`, it only updates the channel for the current user, and `sudo nix-channel --update` updates the root user's channels.

**Comment by ryanbooker** [comment]
I had to add a `nixpkgs` to my user channels, the default installation (whenever I did that) seems to have created `channels_root` pointing to a whatever the version was when I installed… Neither `sudo nix-channels --update` nor `nix-channels --update` seemed to effect the version it was pointing to.

**Comment by berbiche** [comment]
@ryanbooker you probably had the same issue as https://github.com/nix-community/home-manager/issues/1779#issuecomment-774392535

**Comment by worldofpeace** [comment]
This pinned issue is closed.

**Comment by ElvishJerricco** [comment]
I tried to update to 21.05 today on both nixos and home-manager and ran into this issue (nixpkgs branch nixos-21.05, home-manager branch release-21.05).
