### ISSUE TITLE
Getting newsboat.nix error when trying to merge home.nix into configuration.nix

### ISSUE THREAD

**Issue by stelcodes** [nix-community/home-manager#1779]
### Issue description
I'm trying to merge my home.nix with my configuration.nix and I'm getting this error:
```
$ sudo nixos-rebuild switch
building Nix...
building the system configuration...
error: undefined variable 'xdg-utils' at /etc/nixos/configuration.nix:123:5
```
When I print out the stack trace, it shows this at the end:
```
while evaluating the attribute 'default' at /nix/store/2b4x8ihgb0fck3w5p80kmr36s2x7gqv3-source/modules/programs/newsboat.nix:74:9:
attribute 'xdg-utils' missing, at /nix/store/2b4x8ihgb0fck3w5p80kmr36s2x7gqv3-source/modules/programs/newsboat.nix:74:22
```
I know it's related to bbb6d30001369c323a66f5b1d9d8c3b9a19a8ee8 but I'm not sure how to fix it.

#### Maintainer CC
@rycee

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.92, NixOS, 21.03pre265961.891f607d530 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre265961.891f607d530"`
 - channels(stel): `"home-manager, nixos-21.03pre265961.891f607d530"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Also just want to say, I absolutely *love* nix, huge thanks to everyone involved. I hope to start contributing soon.

**Comment by cole-h** [comment]
Dupe of https://github.com/nix-community/home-manager/issues/1777.

**Comment by stelcodes** [comment]
Thank you! `sudo nix-channel --update` works

**Comment by d1egoaz** [comment]
going to try to see how can I get this fixed in MacOS, the sudo command doesn't work

```
sudo nix-channel --update
warning: the group 'nixbld' specified in 'build-users-group' does not exist
warning: unable to download 'https://github.com/rycee/home-manager/archive/master.tar.gz': SSL peer certificate or SSH remote key was not OK (60); retrying in 263 ms
...
```
I tried using an existing certificate, but it didn't work

**Comment by berbiche** [comment]
@d1egoaz the thing with Nix channels is that they are account-specific. So the `root` user will have its own channels and your main user as well.

You should try doing a regular `nix-channel --update` and see if it works.

**Comment by d1egoaz** [comment]
> @d1egoaz the thing with Nix channels is that they are account-specific. So the `root` user will have its own channels and your main user as well.
> 
> 
> 
> You should try doing a regular `nix-channel --update` and see if it works.

Thanks, Yeah, I actually run daily the regular update and home switch, it didn't work. I got the xdg-utils error

**Comment by berbiche** [comment]
@d1egoaz what channel are you using? Home Manager's master branch requires an unstable branch like nixpkgs-unstable, nixos-unstable or something else.

**Comment by d1egoaz** [comment]
> @d1egoaz what channel are you using? Home Manager's master branch requires an unstable branch like nixpkgs-unstable, nixos-unstable or something else.

These were my channels

```
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixpkgs https://releases.nixos.org/nixpkgs/nixpkgs-21.03pre260775.2080afd0399
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable
```

I noticed that I was using `https://github.com/rycee/` I changed it for https://github.com/nix-community, andit worked!

Thanks @berbiche

**Comment by d1egoaz** [comment]
> @d1egoaz what channel are you using? Home Manager's master branch requires an unstable branch like nixpkgs-unstable, nixos-unstable or something else.

These were my channels

```
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixpkgs https://releases.nixos.org/nixpkgs/nixpkgs-21.03pre260775.2080afd0399
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable
```

I noticed that I was using `https://github.com/rycee/` I changed it for https://github.com/nix-community, andit worked!

Thanks @berbiche

**Comment by d1egoaz** [comment]
```
╰─✘ nix-channel --update                                              
unpacking channels...

╰─○ nix-shell '<home-manager>' -A install --show-trace

Creating initial Home Manager generation...

error: attribute 'xdg-utils' missing, at /nix/store/rb5n9adibkpzggrcmxg498sa8kkyapyk-home-manager/home-manager/modules/programs/newsboat.nix:74:22
(use '--show-trace' to show detailed location information)

There are 96 unread and relevant news items.
Read them by running the command 'home-manager news'.


Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
                                                                                                                                                   
╰─✘ nix-channel --list 
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixpkgs https://releases.nixos.org/nixpkgs/nixpkgs-21.03pre260775.2080afd0399
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable
```

**Comment by berbiche** [comment]
Your `nixpkgs` channel seems to be pinned to a specific commit. Delete it and re-add it

**Comment by d1egoaz** [comment]
That did it! thanks! 🙏

**Comment by novafacing** [comment]
Could we just change the offending line to:

```default = if builtins.hasAttr "xdg-utils" pkgs then "${pkgs.xdg-utils}/bin/xdg-open" else "${pkgs.xdg-utils}/bin/xdg-open";```

To prevent this from happening regardless of whether users are on old or new channels? That might be too naive, but does work for me. I've been seeing quite a few people in IRC having this issue as well and having no idea where to start (it's not immediately obvious to casual users that home-manager is involved at all).
