### ISSUE TITLE
Improving the management of shell environments on Non-NixOS

### ISSUE THREAD

**Issue by colinxs** [nix-community/home-manager#1782]
### Issue description

Originally commented on #797 and copied below:

I know this issue is closed, but the solution described by the @bgamari's [comment](  https://github.com/nix-community/home-manager/pull/797#issuecomment-544783247), which is now merged [here](https://github.com/nix-community/home-manager/blob/98d030f723e0a4a446e56b276573efb8bef422f5/modules/targets/generic-linux.nix#L41), has an annoying side effect in that any variables defined by `${profileDirectory}/etc/profile.d/hm-session-vars.sh` overwrite those set in `home.sessionVariables`. So if a user defines `home.sessionVariables = { NIX_PATH = ...; }` then it won't have any effect.

A possible alternative is to place:
```
${optionalString (config.targets.genericLinux)  "if [ -e path/to/nix.sh ]; then . path/to/nix.sh; fi"
```

At the top of `hm-session-vars.sh` (adding the additional check that the path exists).

On a related note, `"${profileDirectory}/etc/profile.d/nix.sh"` doesn't exist for a multi-user Nix install. The path should instead be `/etc/profile.d/nix.sh`. Perhaps we could add a `targets.genericLinux.isMultiUser` enable option and use it like:
```
... = let
  etcNixPath = if cfg.multiUser then "/etc/profile.d/nix.sh" else "${profileDirectory}/etc/profile.d/nix.sh";
in '' 
  if [ -e "${etcNixPath}" ]; then
    . "${etcNixPath}"
  fi
'';
```

There's been some [talk](https://github.com/NixOS/nix/issues/3630) in nixos/nix about better alternatives.

#### Maintainer CC

@Gerschtli for `targets.genericLinux`
@rycee for `home.sessionVariables`

**Comment by colinxs** [comment]
Accidentally clicked "submit" before finishing, whoops!

**Comment by Fuzen-py** [comment]
This issue is still relevant, further discussion appears to have been started in #2012
