### ISSUE TITLE
disabledModules not working when using HM as a NixOS module

### ISSUE THREAD

**Issue by thiagokokada** [nix-community/home-manager#1792]
### Issue description

I am trying to backport some modules from unstable in HM `release-20.09` in my WIP Flake based NixOS/HM configuration. I am trying to keep both HM standalone and as a NixOS module as close as possible in configuration.

The issue is in what I am trying to do here: https://github.com/thiagokokada/nix-configs/commit/e628d2ef21a77a8f00538a4a7aae6bc655102683#diff-3802086929d8fa5ef96d3fde6ef3deaa276509760bc03919b07552b960fcb076R5-R6. This works in standalone mode but not in HM as a NixOS module, returning this error:

```
$ nixos-rebuild build-vm --flake '.#desktop'
building the system configuration...
error: --- ThrownError -------------------------------------------------------------------------------------------------------------- nix
The option `home-manager.users.thiagoko.programs.mpv.enable' in `/nix/store/v9ngxqny70y7chhc9brp3pqwx2jcns4n-source/modules/programs/mpv.nix' is already declared in `/nix/store/l82yrf9fpmpzhy125a4y1g8yqsj6a7i3-source/modules/programs/mpv.nix'.
(use '--show-trace' to show detailed location information)
make: *** [Makefile:9: build-vm-desktop] Error 1
```

I also tried to set `disabledModules` as:

```
disabledModules = [ "${inputs.home}/modules/programs/mpv.nix" ];
```

I even tried:

```
disabledModules = [ "/nix/store/l82yrf9fpmpzhy125a4y1g8yqsj6a7i3-source/modules/programs/mpv.nix" ];
```

However I got the same result.

#### Maintainer CC

@rycee @berbiche 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.7-zen1, NixOS, 20.09.3072.d4c29df154d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-20.09.3072.d4c29df154d"`
 - channels(thiagoko): `"home-manager-20.09, nixos-20.09.2947.2b9daa020d4, nixos-unstable, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
Home Manager's configuration is evaluated separately using `evalModules` https://github.com/nix-community/home-manager/blob/87e2ec341bfda373d50ab58529b4bbb0eb9eb9a0/modules/default.nix#L32-L37 so `disabledModules` has no effect when used in the context of NixOS

**Comment by thiagokokada** [comment]
Is there any way to disable a module them : 🤔?

**Comment by berbiche** [comment]
@thiagokokada can you try adding `disabledModules = "path-to-mpv"` inside a Home Manager module?

**Comment by thiagokokada** [comment]
@berbiche I didn't really understand the proposed workaround? You mean creating a fork of home-manager with `disabledModules` somewhere, pointing it to my Flakes and using it instead :thinking: ?

**Comment by berbiche** [comment]
I recommend trying the `disabledModules` option in your Home Manager configuration and see if it works.

**Comment by thiagokokada** [comment]
> I recommend trying the `disabledModules` option in your Home Manager configuration and see if it works.

But this is what I am doing. I am calling `disabledModules` inside HM configuration.

**Comment by berbiche** [comment]
Looked up the documentation about `disabledModules` and it takes a relative path?
I'm not sure HM supports `disabledModules`.

**Comment by thiagokokada** [comment]
Yeah, it does, because it works when HM is used as a standalone.

Also this: https://github.com/nix-community/home-manager/pull/653

**Comment by berbiche** [comment]
``` nix
{ config, modulesPath, ... }:
{
  disabledModules = map (x: "${modulesPath}/x") [ "programs/mpv.nix" ];
}
```

Untested

**Comment by thiagokokada** [comment]
> ```nix
> { config, modulesPath, ... }:
> {
>   disabledModules = map (x: "${modulesPath}/${x}") [ "programs/mpv.nix" ];
> }
> ```
> 
> Untested

```
$ nixos-rebuild build-vm --flake '.#desktop'
warning: Git tree '/home/thiagoko/Projects/nix-configs' is dirty
building the system configuration...
warning: Git tree '/home/thiagoko/Projects/nix-configs' is dirty
error: --- EvalError ---------------------------------------------------------------------------------------------------------------- nix
at: (262:28) in file: /nix/store/535zcvkghsjqbxk33w41jk9l3wrxpy6n-source/lib/modules.nix

   261|         value = builtins.addErrorContext (context name)
   262|           (args.${name} or config._module.args.${name});
      |                            ^
   263|       }) requiredArgs);

infinite recursion encountered
```

**Comment by thiagokokada** [comment]
As a workaround for this issue I am now maintaining a fork of release-20.09 with backports from things that I wanted from unstable.

Still this is not an ideal solution, so if there is some way to make this work it would be great.

**Comment by lilyball** [comment]
The problem is home-manager does not define `modulesPath` as a special arg when used as a NixOS (or nix-darwin) module, it only defines it when used standalone. This seems like a huge oversight.

In the meantime, you should be able to get around this by adding the following to your NixOS config:

```nix
{
  home-manager.extraSpecialArgs.modulesPath = <home-manager/modules>;
}
```

**Comment by berbiche** [comment]
@lilyball would you like to make a PR?

**Comment by lilyball** [comment]
This is still an issue for nix-darwin.

**Comment by lilyball** [comment]
@thiagokokada Unfortunately no, I can't. I can tell you that `extraSpecialArgs.modulesPath = <home-manager/modules>;` works wonderfully in my local setup, so I believe just copying the nixos changes to the nix-darwin file should work.

**Comment by thiagokokada** [comment]
Ok, opened a PR: https://github.com/nix-community/home-manager/pull/2375

However I can't test it. So it would be nice if someone using nix-darwin could test it.

**Comment by lilyball** [comment]
`darwin-rebuild check` works with it
