### ISSUE TITLE
VSCode expects writable settings.json

### ISSUE THREAD

**Issue by andyrichardson** [nix-community/home-manager#1800]
### Issue description

Some basic functionality like zooming (`cmd =` on macOS) requires writing to the `settings.json` file - otherwise an error toast is shown and zooming does not occur.

#### Maintainer CC

@kubukoz
@berbiche 
@rycee 

#### Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.3.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(andyrichardson): `"nixpkgs-21.03pre269341.f6803b46e8a, darwin"`
```

**Comment by andyrichardson** [comment]
I'm not too hot on Nix - is it possible to allow writing to specific files in the nix store?

If so, would a `writable` option to the file utility be an option [(similar to how `executable` works)](https://github.com/nix-community/home-manager/blob/7e5fee4268f53be8758598b7634dff8b3ad8a22b/modules/lib/file-type.nix#L50)

**Comment by kubukoz** [comment]
I don't know Nix that well but I think it would be a disaster, because changing the contents of the file should change the hash, and following that, the location of the file. Also, rebuilding the HM config would overwrite any changes there.

The real problem is this, I think: https://github.com/microsoft/vscode/issues/38177 - zoom should be a local setting.

You can work around this by changing the workspace's `.vscode/settings.json` and adding a zoomLevel override in there - that's how I'm dealing with this, anyway.

**Comment by kubukoz** [comment]
I created an issue to track this problem in vscode: https://github.com/microsoft/vscode/issues/116701

**Comment by andyrichardson** [comment]
@kubukoz a huge thanks for following up on this issue!

If for some reason the team aren't able to work around this constraint, I wonder if something like [mkOutOfStoreSmLink](https://github.com/nix-community/home-manager/blob/master/modules/files.nix#L42) would do the job?

**Comment by kubukoz** [comment]
> I wonder if something like mkOutOfStoreSmLink would do the job?

I wouldn't be surprised if these files are read-only as well. In general, I think mutability doesn't belong in Nix and your best bet if you want to allow it is to either:

- write an activation script for Home Manager that will create a file with the appropriate contents, which will not have to be in the Nix store, and will be possible to write to
- use a separate script (not in Home Manager) to generate the file on demand and resign from HM managing your settings - this way you're less likely to overwrite changes made by the editor.

All in all, making the file editable means you'll overwrite it whenever you build your HM config / run the tool that generates it. It's probably against Nix philosophy of reproducible builds and immutable hashes for contents, so the options are limited here...

If you want to keep your configs in sync between different machines (and store them somewhere as a backup), there's an experimental (but from what I hear, quite stable) Settings Sync feature in vscode now - you won't be able to use Nix goodies like functions or inputs from the rest of the HM config, but at least it won't randomly revert your changes when you call some other tool :)

**Comment by teto** [comment]
It's controversial/almost philosophical but I like to have the possibility to have an hybrid configuration, to quickly itereate on something before moving parts of the config to nix. Rebuilding via nix is just too slow. My typical example would be neovim but vscode would be similar, even worse as the program expects to be able to write in the file too.

**Comment by kubukoz** [comment]
I have similar feelings. For quick iteration, I sometimes change things in my workspace settings, but having the ability to include multiple sources of global config would be nice to have as well. I'm pretty sure this would require changes in vscode itself though.

**Comment by berbiche** [comment]
I was thinking about this and it would be great if VSCode supported a way to layer multiple configuration files such that default settings could be provided and overridden in the user's configuration.

**Comment by kamadorueda** [comment]
This is my workaround:

```nix
{
    home = {
      activation = {
        afterWriteBoundary = {
          after = [ "writeBoundary" ];
          before = [ ];
          data = ''
            find ~/.config/Code | while read -r path
            do
              $DRY_RUN_CMD chmod --recursive +w \
                "$(readlink --canonicalize "$path")"
            done
          '';
        };
      };
  };
};
```

**Comment by andyrichardson** [comment]
I've done [something similar here](https://github.com/andyrichardson/dotfiles/blob/28c3630e71d65d92b88cf83b2f91121432be0068/nix/home/vscode.nix#L5).

Closing for now

**Comment by kubukoz** [comment]
FYI it seems like the zoom setting doesn't actually have to be persisted anymore. I'm able to change zoom without a `settings.json` file present, or witohut containing the zoomLevel setting, with no errors visible or changes to the global config.

**Comment by DavHau** [comment]
I'm running into this with the setting `editor.action.toggleColumnSelection`. Whenever I press the toggle shortcut, it wants to write to the settings.json and change the setting `editor.columnSelection`.
Vscode not being able to write to that file renders that feature unusable.

Can we please re-open this issue?

I fully agree with the idea with immutable settings, but the software vscode `IS NOT` compatible to a read-only settings.json, therefore the settings should be made mutable `by default` until vscode changes it's behavior.

I just spent 2h debugging this. This is a horrible UX.
Having a read-only config here will likely make many people waste their time debugging. It should not be like that by default.

The settings could still be `semi immutable`, by wrapping vscode, so on each launch it overwrites the `settings.json` with content from the store. Important is only that it is temporarily writable.

**Comment by kamadorueda** [comment]
@DavHau This is my vscode: https://github.com/kamadorueda/machine/tree/main/nixos-modules/editor

The workaround I do there is: I build everything purely (sandbox, fixed output derivations), and on system activation I just copy $out into a writable folder in the file system so vscode is happy

Any time I reload the system, such folder is deleted and recreated, so it's immutable at build but mutable at runtime, nice

**Comment by DavHau** [comment]
I tried to replicate that, but I always get this error:
`Existing file '/home/grmpf/.config/VSCodium/User/settings.json' is in the way of '/nix/store/g11ym4g7a287cwc010xw5hz3xh8a8ic9-home-manager-files/.config/VSCodium/User/settings.json'`

This must be because the `home.file` entry created by the vscode module still tries to create this file. It doesn't seem to be possible to remove the `home.file` entry.

**Comment by DavHau** [comment]
OK, this here fixed it for me:
```nix
{
    home.activation.boforeCheckLinkTargets = {
      after = [];
      before = [ "checkLinkTargets" ];
      data = ''
        userDir=/home/grmpf/.config/VSCodium/User
        rm -rf $userDir/settings.json
      '';
    };

    home.activation.afterWriteBoundary = {
      after = [ "writeBoundary" ];
      before = [];
      data = ''
        userDir=/home/grmpf/.config/VSCodium/User
        rm -rf $userDir/settings.json
        cat \
          ${(pkgs.formats.json {}).generate "blabla"
            programs.vscode.userSettings} \
          > $userDir/settings.json
      '';
    };
}
```

But still, I think this should be fixed in the module permanently.
An afternoon of debugging should not be necessary to unbreak vscode features.

**Comment by davesmith00000** [comment]
@DavHau would you mind explaining your solution a little? (I'm a nix noob...)

It appears to do exactly what I need which is to remove the `settings.json` file/symlink and then re-export it from the `programs.vscode.userSettings` property.

The problems I'm having, in order, are (I'm on manjaro linux using home manager if it makes a different...):

1. It doesn't work as-is (I have replaced the home dir naturally).
2. When I run it what I actually get is an error: `undefined variable 'programs'` inside the string interpolation bit.
3. If I try to google any of this I get nothing useful back, nothing on: `pkg.formats`, or the `generate` method so that I can work out whether the value `blabla` needs to be something meaningful.

I'm sure this will turn out to be something daft, but any help would be appreciated. Thanks in advance. :pray:

**Comment by rgbatty** [comment]
Huge thanks to @DavHau & @davesmith00000 for their posted solutions. I mixed these a little bit into a general VS Code module that I thought might be useful for anyone seeking to use other pkg versions or systems with optional mutability. Unfortunately the logic for Darwin is a bit different, so I pulled path resolution from the original HM module. This could easily be extended to cover other settings files like snippets and keybinds.

Long term, most of this feels fairly boilerplate and easily addable to the core HM module. My only complaint with this implementation is that it still overrides the symlink no matter what, but thats more of an issue with my general comfort level in Nix. 😅 

```nix
{ config, lib, pkgs, ... }:

with lib;
let
  cfg = config.modules.home.editors.vscode;
  vscodePname = config.programs.vscode.package.pname;

  configDir = {
    "vscode" = "Code";
    "vscode-insiders" = "Code - Insiders";
    "vscodium" = "VSCodium";
  }.${vscodePname};

  sysDir = if pkgs.stdenv.hostPlatform.isDarwin then
    "${config.home.homeDirectory}/Library/Application Support"
  else
    "${config.xdg.configHome}";

  userFilePath = "${sysDir}/${configDir}/User/settings.json";
in {
  options.modules.home.editors.vscode = {
    enable = mkEnableOption "VS Code";
    mutable = mkEnableOption "Mutable configuration";
  };

  config = mkIf cfg.enable {
    home = {
      activation = mkIf cfg.mutable {
        removeExistingVSCodeSettings = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
          rm -rf "${userFilePath}"
        '';

        overwriteVSCodeSymlink = let
          userSettings = config.programs.vscode.userSettings;
          jsonSettings = pkgs.writeText "tmp_vscode_settings" (builtins.toJSON userSettings);
        in lib.hm.dag.entryAfter [ "linkGeneration" ] ''
          rm -rf "${userFilePath}"
          cat ${jsonSettings} | ${pkgs.jq}/bin/jq --monochrome-output > "${userFilePath}"
        '';
      };
    };

    programs.vscode = {
      enable = true;
      extensions = import ./extensions.nix { inherit pkgs; };
      package = pkgs.vscodium;
      userSettings = import ./settings.nix;
    };
  };
}

```

**Comment by MatrixManAtYrService** [comment]
I agree with @DavHau, if there's a solution to this, we ought to make it part of the package instead of collecting individual one-off's.  Sadly I'm not quite ready to take on that job.
 
 @andyrichardson, what do you think about reopening this in hopes that that happens?

**Comment by andyrichardson** [comment]
Hey hey! I'm not invested in the Nix ecosystem anymore. I'll leave it up to the maintainers to re-open if they feel it's something that can be acted upon 👍

**Comment by piousdeer** [comment]
I made a more general-purpose module that extends `home.file`-like options with a `mutable` option. If enabled, it replaces the file's symlink with a writable copy of itself on each activation. The module and its usage with VS Code can be found here: https://gist.github.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa

**Comment by cartercook** [comment]
@piousdeer 's modules worked for me like so:

**home.nix**
```nix
{ config, lib, pkgs, ... }:
{
  ... home manager stuff ...
  imports = [
    # Source: https://gist.github.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa
    # Make vscode settings writable

    (import (builtins.fetchurl {
      url = "https://gist.githubusercontent.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa/raw/41e569ba110eb6ebbb463a6b1f5d9fe4f9e82375/mutability.nix";
      sha256 = "4b5ca670c1ac865927e98ac5bf5c131eca46cc20abf0bd0612db955bfc979de8";
    }) { inherit config lib; })

    (import (builtins.fetchurl {
      url = "https://gist.githubusercontent.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa/raw/41e569ba110eb6ebbb463a6b1f5d9fe4f9e82375/vscode.nix";
      sha256 = "fed877fa1eefd94bc4806641cea87138df78a47af89c7818ac5e76ebacbd025f";
    }) { inherit config lib pkgs; })
  ];
  ... home manager stuff ...
}
```

I have home manager installed via the home-manager tool (i.e. flake), but this should work for any installation.

**Comment by cartercook** [comment]
I have @piousdeer 's answer working like so:

**home.nix**
```nix
{ config, lib, pkgs, ... }:
{
  ... home manager stuff ...
  
  imports = [
    # Source: https://gist.github.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa
    # Make vscode settings writable

    (import (builtins.fetchurl {
      url = "https://gist.githubusercontent.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa/raw/41e569ba110eb6ebbb463a6b1f5d9fe4f9e82375/mutability.nix";
      sha256 = "4b5ca670c1ac865927e98ac5bf5c131eca46cc20abf0bd0612db955bfc979de8";
    }) { inherit config lib; })

    (import (builtins.fetchurl {
      url = "https://gist.githubusercontent.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa/raw/41e569ba110eb6ebbb463a6b1f5d9fe4f9e82375/vscode.nix";
      sha256 = "fed877fa1eefd94bc4806641cea87138df78a47af89c7818ac5e76ebacbd025f";
    }) { inherit config lib pkgs; })
  ];
  
  ... home manager stuff ...
}
```

I'm using the standalone home manager installation (`home-manager` command + flake) but this should work for any installation.

**Comment by bemyak** [comment]
A slightly modified version of the @davesmith00000's solution, which is arguably more robust:
```nix
home.activation.makeVSCodeConfigWritable =
  let
    configDirName = {
      "vscode" = "Code";
      "vscode-insiders" = "Code - Insiders";
      "vscodium" = "VSCodium";
    }.${programs.vscode.package.pname};
    configPath = "${config.xdg.configHome}/${configDirName}/User/settings.json";
  in
  {
    after = [ "writeBoundary" ];
    before = [ ];
    data = ''
      install -m 0640 "$(readlink ${configPath})" ${configPath}
    '';
  };
```

> Note: If you're putting this in the same file where `programs.vscode` is defined, make sure that the whole attribute set is recursive i.e., add `rec` before the opening curly bracket.

**Comment by joscha** [comment]
> A slightly modified version of the @davesmith00000's solution, which is arguably more robust:
> 
> ```nix
> home.activation.makeVSCodeConfigWritable =
>   let
>     configDirName = {
>       "vscode" = "Code";
>       "vscode-insiders" = "Code - Insiders";
>       "vscodium" = "VSCodium";
>     }.${programs.vscode.package.pname};
>     configPath = "${config.xdg.configHome}/${configDirName}/User/settings.json";
>   in
>   {
>     after = [ "writeBoundary" ];
>     before = [ ];
>     data = ''
>       install -m 0640 "$(readlink ${configPath})" ${configPath}
>     '';
>   };
> ```
> 
> > Note: If you're putting this in the same file where `programs.vscode` is defined, make sure that the whole attribute set is recursive i.e., add `rec` before the opening curly bracket.

@bemyak thanks for this - it seem to generate a `configPath` that points to`~/.config/Code/User/settings.json` - `${config.xdg.configHome}` seems to point to my `~/.config` dir - I am assuming it should point elsewhere?
The script then fails with: `install: cannot stat '': No such file or directory`

**Comment by sliedes** [comment]
There's a lot of things in VSCode that seem to assume writable config, and I doubt upstream is interested in changing it. For example, with home-manager, I'm completely unable to toggle things like showing whitespace only diffs in diff view.

I appreciate that this is a hard problem (and still prefer to configure my vscode using home manager). While recreating a mutable file at every build (and thus discarding previous changes, also instantly changing every running vscode's state!) is also surprising, I'd argue that it would still be a less broken default in the case of vscode than the current home-manager default.

**Comment by OliverJAsh** [comment]
Has anyone figured out a workflow to diff the writable config file with Nix's original version of the file? That would help with backporting new config to Nix.

This would be great: https://github.com/nix-community/home-manager/issues/7617
