### ISSUE TITLE
offlineimap: ~/.config/offlineimap/get_settings.pyc takes precedence over settings generated by home-manager

### ISSUE THREAD

**Issue by markusscherer** [nix-community/home-manager#1802]
### Issue description

When using `offlineimap`, `home-manager` generates a python file in `~/.config/offlineimap/get_settings.py`. When running `offlineimap`, a compiled python file under `~/.config/offlineimap/get_settings.pyc` is created. The problem now is, that if the python file changes (e.g. by setting `programs.offlineimap.pythonFile`) `offlineimap` still prefers the compiled file which is not recompiled. Maybe this is because the file in the nix store is always older (01.01.1970) than the compiled file (This is just a guess, I didn't check it).

A solution would probably be to delete `~/.config/offlineimap/get_settings.pyc` if `~/.config/offlineimap/get_settings.py` changed (doing this manually it a passable workaround).

#### Maintainer CC

@teto @rycee 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 20.09.2624.1eff582e7ea (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(markus): `"home-manager-20.09, nixos-20.03.3324.929768261a3, unstable-21.03pre267812.7cbec40a095"`
 - channels(hmtest): `"home-manager-20.09"`
 - channels(root): `"nixos-20.09.2624.1eff582e7ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
or one could configure python to ignore the generated bytecode/force its installation.

**Comment by teto** [comment]
offlineimap is already pretty slow so the difference should not be notable. Otherwise is there a way to generate the .pyc in advance and link it so that the presence of a preexisting `pyc` file warns the user ?

**Comment by markusscherer** [comment]
I'm be no means a python person but it seems one can generate the python files by `python2 -m py_compile <filenames>`.
Unfortunately I know too little about `home-manager` to generate/compile files by invoking external commands. Is there any way to access the build phases like in a derivation?

Anyway, a solution that also seems to work (inspired by the way a similar thing is handled in the `xmonad` module) would be:

```nix
    xdg.configFile."offlineimap/get_settings.py".onChange = ''
      echo "Recompiling ${config.xdg.configHome}/offlineimap/get_settings.py"
      $DRY_RUN_CMD ${pkgs.python2}/bin/python2 -m py_compile "${config.xdg.configHome}/offlineimap/get_settings.py"
      '';
```

This seems to generate exactly the files `offlineimap` would generate and propagates changes done via `programs.offlineimap.pythonFile`. What's also nice is, that this shows syntax errors in the provided python file (although it would of course be nice if the build would fail if there were syntax errors).

**Comment by markusscherer** [comment]
After some trial and error I came to this solution, which compiles the `get_setting.py` file and links the result to `~/.config/offlineimap/get_settings.pyc`

```nix
    xdg.configFile."offlineimap/get_settings.py".text = cfg.pythonFile;
    xdg.configFile."offlineimap/get_settings.pyc".source = "${
        pkgs.runCommandLocal "get_settings-compile" {
          nativeBuildInputs = [ pkgs.python2 ];
        } ''

          mkdir -p $out/bin
          cat > $out/bin/get_settings.py <<EOF059b874057eea8419a280b82ad8772ac
          ${cfg.pythonFile}
          EOF059b874057eea8419a280b82ad8772ac

          python2 -m py_compile $out/bin/get_settings.py
           ''
      }/bin/get_settings.pyc";
```

Comments on how to make the code more idiomatic are of course appreciated!

**Comment by rycee** [comment]
@markusscherer Untested but perhaps

```nix
    xdg.configFile."offlineimap/get_settings.py".text = cfg.pythonFile;
    xdg.configFile."offlineimap/get_settings.pyc".source = "${
        pkgs.runCommandLocal "get_settings-compile" {
          nativeBuildInputs = [ pkgs.python2 ];
          pythonFile = cfg.pythonFile;
          passAsFile = [ "pythonFile" ];
        } ''
          mkdir -p $out/bin
          cp $pythonFilePath $out/bin/get_settings.py
          python2 -m py_compile $out/bin/get_settings.py
           ''
      }/bin/get_settings.pyc";
```

Nice work!
