### ISSUE TITLE
Misleading error message "outside $HOME"

### ISSUE THREAD

**Issue by dschrempf** [nix-community/home-manager#1807]
Hi!

I realized that when using the following configuration (note that the target is the same; it shouldn't be):
```
  home.file.Music.source = config.lib.file.mkOutOfStoreSymlink "~/Music";
  home.file.Music.target = "testMusic";

  home.file.Sheets.source = config.lib.file.mkOutOfStoreSymlink "~/Sheets";
  home.file.Sheets.target = "testMusic";
```
Home Manager gives the following error:
```
Error installing file 'testMusic' outside $HOME
```
This is not true and actually misleading (although it is great that Home Manager does throw an error).

**Comment by berbiche** [comment]
Hi, is this related to #1808?

**Comment by dschrempf** [comment]
I don't think so. Both folders exist.

**Comment by berbiche** [comment]
I tested the behavior with the `target` and `source` in the `tests/modules/files/out-of-store-symlink` and it won't work as you think.

The tilde is not expanded when making a symbolic link so you would need to use `mkOutOfStoreSymlink "${home.homeDirectory}/Music"`.

As for the `Error installing file`, it did not occur in the test file.

**Comment by dschrempf** [comment]
Thanks for looking into this!

Hm, I am not sure about that. If I use the code posted above, I get the exact error message, and it is misleading.

 The fact that `~` does not work is a different issue, it should probably lead to a different, informative error (or warning) message.

Further, if I use two fully specified (existing) paths, I still get the error message:
```
  home.file.Music.source = config.lib.file.mkOutOfStoreSymlink /home/dominik/Music;
  home.file.Music.target = "testMusic";

  home.file.Sheets.source = config.lib.file.mkOutOfStoreSymlink /home/dominik/Sheets;
  home.file.Sheets.target = "testMusic";
```
```
Error installing file 'testMusic' outside $HOME
```

**Comment by dschrempf** [comment]
Hm I didn't test this again now, but I don't think it is resolved. Please correct me if this is the case.

**Comment by berbiche** [comment]
Rycee recently rewrote the comparison and symlink logic, is this still reproducible / an issue?

**Comment by dschrempf** [comment]
I still get
```
error: builder for '/nix/store/41l7ap1lcjy3ksyfa8m8j20l9328hjcz-home-manager-files.drv' failed with exit code 1;
       last 1 log lines:
       > Error installing file 'testMusic' outside $HOME
       For full logs, run 'nix log /nix/store/41l7ap1lcjy3ksyfa8m8j20l9328hjcz-home-manager-files.drv'.
error: 1 dependencies of derivation '/nix/store/cphafmfhhx7pm88wzrl01h3lamz8msqw-home-manager-generation.drv' failed to build
```

**Comment by rycee** [comment]
Thanks for the report. I've added an assertion now which should output an error message along the lines of

```
Conflicting managed target files: baz

This may happen, for example, if you have a configuration similar to

    home.file = {
      conflict1 = { source = ./foo.nix; target = "baz"; };
      conflict2 = { source = ./bar.nix; target = "baz"; };
    }
```

**Comment by citriqa** [comment]
definitely still an issue as per comment above, kindly reopen the issue.

**Comment by nuclear06** [comment]
It seems to be the same problem. If two services have the same target, the build fails and throws a misleading error message indicating it's out of $HOME.
![Image](https://github.com/user-attachments/assets/30b13115-7daf-4c5a-a7ae-8bd60fbe405d)

<details>
  <summary>Log</summary>
  <pre>
    > Building NixOS configuration
warning: Git tree '/etc/nixos' is dirty
Using saved setting for 'extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=' from ~/.local/share/nix/trusted-settings.json.
Using saved setting for 'substituters = https://nix-community.cachix.org https://mirrors.ustc.edu.cn/nix-channels/store https://hyprland.cachix.org' from ~/.local/share/nix/trusted-settings.json.
evaluation warning: 'buildFHSUserEnvBubblewrap' has been renamed to 'buildFHSEnvBubblewrap' and will be removed in 25.11
these 7 derivations will be built:
  /nix/store/y98hqgws0dnzkmy3kmawv2kp7cjfmafs-hm_themes.drv
  /nix/store/015vr4ningl4b2mapqzwa89y7h1vvhkv-home-manager-files.drv
  /nix/store/dlk2jb152r78i7i2r0jbjm9zr5bydpsv-home-manager-generation.drv
  /nix/store/ywgp48qsxf64jglh7f2agvivdaxyrckw-unit-home-manager-saniter.service.drv
  /nix/store/7wxlnfmjyqli943px9nyxd9k6az0dpck-system-units.drv
  /nix/store/43qcnz1xc2f3a2dz86h18gn3w5vlq9li-etc.drv
  /nix/store/q0rd2d8h2v971agxvgk0cb4l1js9rd62-nixos-system-BlueDeep-25.05.20250205.1da52dd.drv
hm_themes> building '/nix/store/y98hqgws0dnzkmy3kmawv2kp7cjfmafs-hm_themes.drv'
home-manager-files> building '/nix/store/015vr4ningl4b2mapqzwa89y7h1vvhkv-home-manager-files.drv'
home-manager-files> Error installing file '.config/systemd/user/blueman-applet.service' outside $HOME
error: builder for '/nix/store/015vr4ningl4b2mapqzwa89y7h1vvhkv-home-manager-files.drv' failed with exit code 1;
       last 1 log lines:
       > Error installing file '.config/systemd/user/blueman-applet.service' outside $HOME
       For full logs, run 'nix log /nix/store/015vr4ningl4b2mapqzwa89y7h1vvhkv-home-manager-files.drv'.
error: 1 dependencies of derivation '/nix/store/dlk2jb152r78i7i2r0jbjm9zr5bydpsv-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ywgp48qsxf64jglh7f2agvivdaxyrckw-unit-home-manager-saniter.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7wxlnfmjyqli943px9nyxd9k6az0dpck-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/43qcnz1xc2f3a2dz86h18gn3w5vlq9li-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q0rd2d8h2v971agxvgk0cb4l1js9rd62-nixos-system-BlueDeep-25.05.20250205.1da52dd.drv' failed to build
  </pre>
</details>

**Comment by bwfiq** [comment]
I had the same issue while installing Hyprland on latest home-manager

**Comment by urioTV** [comment]
Issue still present. I wanted to reuse my old config which used this method and now i get this weird outside $HOME error.

**Comment by Phosphorescentt** [comment]
I have also found this issue attempting to `mkOutOfStoreSymlink` my tmux config. Setting `xdg.configFile."tmux/tmux.conf".enable = false` fixes it.

**Comment by andreaskrath** [comment]
Bumping to say that I also experienced this - underlying it was because of Stylix files being generated, but the error message is in no way an indication of what is actually going on.

**Comment by WebInspectInc** [comment]
I just experienced this error while trying to update my system. I was configuring neovim using this config:

```
home.file.".config/nvim" = {
  source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/config/nvim";
};
```

And I got the "outside $HOME" error. Very confusing. Fortunately I was able to remove the above three lines and change my config to this:

```diff
- home.file.".config/nvim" = {
-  source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/config/nvim";
- };
programs.neovim = {
    enable = true;
+   extraConfig = lib.fileContents ../config/nvim/init.lua;
};
```

I don't know why `mkOutOfStoreSymlink` stopped working suddenly, but this seems like a better solution anyway, and fixes it quite nicely.
