### ISSUE TITLE
mkOutOfStoreSymlink does not check if file exists

### ISSUE THREAD

**Issue by dschrempf** [nix-community/home-manager#1808]
If I use an in-store link, I get an error when setting
```
  home.file.Music.source = ~/Music2;
  home.file.Music.target = "testMusic";
```
(The directory or file `~/Music2` does not exist).

However, when setting
```
  home.file.Sheets.source = config.lib.file.mkOutOfStoreSymlink "~/Music2";
  home.file.Sheets.target = "testMusic2";
```
I get a dangling symlink `~/testMusic2` and no error.

Is it possible, to check for the existence of the given path, even for out of store symlinks? (I know, it is discouraged to use out of store symlinks, but some of my configurations are just too large or too volatile to have them in store. In this case it would be nice to know, when some files are not present.).

**Comment by dschrempf** [comment]
Actually, I just noticed that I was using a string for the second example.

`home.file.<name>.source` does not accept a string at all, only a path. mkOutOfStoreSymlink accepts both.

To be honest, I am pretty confused about when to use a `path` ans when to use a `string`... Sometimes they seem to be coerced automatically, sometimes not.

**Comment by berbiche** [comment]
- A `path` explicitly imports the path in the Nix store
- A string may or may not be coerced to a `path` and imported it to the store, it depends on the code using the string.

`builtins.pathExists` is available though it's impure and wouldn't work when checking a file that is outside of a flake's directory.

**Comment by dschrempf** [comment]
> A string may or may not be coerced to a path and imported it to the store, it depends on the code using the string.

It seems that many times, when a function takes an argument of type path, a string will do (but sometimes not). Or am I wrong? How can I find this out for a specific function? (Do I really have to check the code?) Is it recommended to use paths or strings? Why is it even allowed to use a string when a path is required? Sorry to bombard you with these unrelated questions.

May I ask: Why do you think that it should not check for the existence of a file?

**Comment by berbiche** [comment]
> Why do you think that it should not check for the existence of a file?

One use-case for such links is to create the directory at runtime.

The build machine is not necessarily the host machine when using Home Manager as a NixOS/Darwin module.

> when a function takes an argument of type path, a string will do

If a string is appended to a path, then you still have a path.

> Why is it even allowed to use a string when a path is required?

https://github.com/NixOS/nixpkgs/blob/fca104c1e10fe287e9e41e16403595186a8ab12e/lib/types.nix#L343-L347

Paths can be coerced to strings and vice-versa.

**Comment by dschrempf** [comment]
OK I see. I will use a private function that uses `builtins.pathExists`.

>https://github.com/NixOS/nixpkgs/blob/fca104c1e10fe287e9e41e16403595186a8ab12e/lib/types.nix#L343-L347
Paths can be coerced to strings and vice-versa.

OK I just had a look. The code explains why I got an error when using "~/asdf". Functions using paths only accept strings corresponding to absolute paths.

This opens another question: Why did
```
  home.file.Sheets.source = config.lib.file.mkOutOfStoreSymlink "~/Music2";
```
work then? It also expects a path, and the string is not an absolute path. Sorry to bother you, but I am used to strong type systems and it seems there is a lot of confusion when types are coerced automatically...

**Comment by berbiche** [comment]
> This opens another question: Why did
> 
> ```
>   home.file.Sheets.source = config.lib.file.mkOutOfStoreSymlink "~/Music2";
> ```
> 
> work then? It also expects a path, and the string is not an absolute path. Sorry to bother you, but I am used to static type systems and it seems there is a lot of confusion when types are coerced automatically...

Sorry, I don't have the answer to that question.

> OK I see. I will use a private function that uses `builtins.pathExists`.

I will close the issue since it's resolved

**Comment by dschrempf** [comment]
Thanks a lot for your help @berbiche!
