### ISSUE TITLE
shell agnostic aliases

### ISSUE THREAD

**Issue by Sohalt** [nix-community/home-manager#1809]
### Issue description

I think it would be very useful to have an option to set aliases independent of a specific shell, similar to how `environment.shellAliases` in nixos works for all shells (bash, zsh, fish), so modules can set aliases without having to know if they should use `programs.bash.shellAliases`, `programs.zsh.shellAliases`, or `programs.fish.shellAliases`.

Not sure where to best place that option. Maybe `home.shellAliases`?

What do you think about the suggestion in general?

**Comment by berbiche** [comment]
Some more ideas:
- Global `enableShellIntegrations` that would enable (`mkDefault true`) `enableFishIntegration`, `enableZshIntegration` and `enableBashIntegration` on all modules (the user would still need to `programs.<name>.enable = true;`)

**Comment by berbiche** [comment]
A temporary solution to @Sohalt suggestions is to set the aliases for one shell and reuse them with `programs.${SHELL}.shellAliases = config.programs.bash.shellAliases` (if the aliases are defined under the bash module and `$SHELL` is one of zsh or fish).



> Another idea:
> 
>     * Global `enableShellIntegrations` that would enable (`mkDefault true`) `enableFishIntegration`, `enableZshIntegration` and `enableBashIntegration` on all modules (the user would still need to `programs.<name>.enable = true;`)

I'll move this to a new issue.

**Comment by rycee** [comment]
Having a `home.shellAliases` seems OK by me. The only worry I would have is if different shells have incompatible escaping rules, but I imagine at least bash and zsh should be safe.

**Comment by rycee** [comment]
I think this is still valuable.

**Comment by ilkecan** [comment]
It looks like this should have been closed by #2347.
