### ISSUE TITLE
How to use overlays to install neovim nightly

### ISSUE THREAD

**Issue by noib3** [nix-community/home-manager#1815]
### Issue description

I'm trying to install neovim nightly (version 0.5.0) through an overlay, but after googling everywhere for the past hour I still can't get this to work. The latest release neovim release (the one on the unstable channel) is at 0.4.4. This is a stripped down version of my `home.nix` with the relevant bits:
```nix
{ config, pkgs, ... }:

let
  unstable = import <nixos-unstable> { config = { allowUnfree = true; }; };

in {
  home = {
    username = "nix";
    homeDirectory = "/home/nix";
    stateVersion = "21.03";

    packages = with pkgs; [
      neovim
    ];
  };

  nixpkgs.overlays = [(
    self: super: {
      neovim = unstable.neovim;
    }
  )];

  programs.home-manager.enable = true;
}
```

I'm sorry if this is a basic question but I just got into the nix ecosystem and I'm still not sure how all the pieces fit together.

**Comment by berbiche** [comment]
@noib3 Hi, I think you would need to use https://github.com/nix-community/neovim-nightly-overlay just like you currently do with `unstable`
