### ISSUE TITLE
services.gpg-agent: Export `GPG_TTY` for Fish shells

### ISSUE THREAD

**Issue by bnjmnt4n** [nix-community/home-manager#1816]
### Issue description

The gpg-agent service exports `GPG_TTY` for bash-compatible shells (https://github.com/nix-community/home-manager/blob/7e5fee4268f53be8758598b7634dff8b3ad8a22b/modules/services/gpg-agent.nix#L9-L14), but that syntax does not work for FIsh.

Would a PR adding lines for `programs.fish.initExtra` be acceptable? Not sure if this is a good solution, seeing that it creates a separate branch of code.

#### Maintainer CC

@rycee

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.17, NixOS, 21.05.20210217.6b1057b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(bnjmnt4n): `""`
 - channels(root): `"nixos-21.03pre269343.758b29b5a28"`
 - nixpkgs: `/nix/store/srvplqq673sqd9vyfhyc5w1p88y1gfm4-source`
 -

**Comment by rycee** [comment]
Sure, adding a line for `programs.fish.initExtra` in `gpg-agent.nix` would be welcome.

**Comment by dhoppe** [comment]
@bnjmnt4n Is there a particular reason why this optional command is not part of your pull request?
https://github.com/nix-community/home-manager/blob/master/modules/services/gpg-agent.nix#L15-L16
