### ISSUE TITLE
kitty: Font size should not be part of name

### ISSUE THREAD

**Issue by loewenheim** [nix-community/home-manager#1827]
### Issue description
The [documentation of `programs.kitty.font.name`](https://nix-community.github.io/home-manager/options.html#opt-programs.kitty.font.name) currently looks like this:
```nix
programs.kitty.font.name

    The family name and size of the font within the package.

    Type: string

    Example: "DejaVu Sans 8" 
```
However, contrary to the example, `kitty` does not expect the font size to be a part of the name. `font.name` corresponds to `font_family` in `kitty.conf`; the size has its own option `font_size`. I suggest adding a corresponding option `font.size` to the `kitty` module in home-manager.
#### Maintainer CC

@iv-nn 

#### Technical details
```
- system: `"x86_64-darwin"`
 - host os: `Darwin 20.3.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(sebastian): `"home-manager-20.09, nixpkgs-20.09.3270.721312288f7"`
 - nixpkgs: `/Users/sebastian/.nix-defexpr/channels/nixpkgs`
```

**Comment by teto** [comment]
Not sure it needs a new option as with the new `settings` option it is straightforward to set this:
```
    settings = {
      bold_font  = "auto";
      italic_font = "auto";
      bold_italic_font = "auto";
      font_size = 12;
```
The doc may need adjustment though. PR welcome

**Comment by loewenheim** [comment]
Fair point, but on the other hand, there is already a submodule for `font`

**Comment by teto** [comment]
indeed. PR welcome

**Comment by berbiche** [comment]
Closing this since https://github.com/nix-community/home-manager/pull/1848 was merged.
