### ISSUE TITLE
home.sessionVariables is ignored

### ISSUE THREAD

**Issue by pinpox** [nix-community/home-manager#1830]
### Issue description

I'm trying to set `$ZDOTDIR`, so that it has the correct value when loggin in on the the tty. For that I'm setting:
```nix
  home.sessionVariables = {

    # Workaround for alacritty
    LIBGL_ALWAYS_SOFTWARE = "1";
    EDITOR = "nvim";
    VISUAL = "nvim";
    ZDOTDIR = "/home/pinpox/.config/zsh";
  };
```

But the `echo $ZDOTDIR` returns an empty string when logging in on the tty or via SSH:
```
pinpox@kartoffel>  ssh localhost                                               
Last login: Fri Feb 26 00:06:06 2021
pinpox@kartoffel> echo $ZDOTDIR                                                                           

pinpox@kartoffel>                                                                                         

```
Not sure if this is a bug or I am doing something wrong. Where/how do I have to set environment variables so they get set correctly at login? (**before** running `startx` e.g.)

#### Maintainer CC
@rycee

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05.20210224.f6b5bfd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `""`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/store/zfmxqr26bm36kmk22x2zsk0qbcd559qs-source`

**Comment by teto** [comment]
ZDOTDIR was tricky https://github.com/nix-community/home-manager/issues/219, not sure where we stand now

**Comment by voobscout** [comment]
all sessionVariables are ignored completely everywhwere, doesn't matter how one logs in, with displaymanager / ssh / console.

**Comment by berbiche** [comment]
> @voobscout  all sessionVariables are ignored completely everywhwere, doesn't matter how one logs in, with displaymanager / ssh / console.

Can you create a new issue to track the specific problem that occurs on your system?
Thanks
