### ISSUE TITLE
neovim: is init.vim all we can get?

### ISSUE THREAD

**Issue by noib3** [nix-community/home-manager#1834]
### Issue description

The neovim module seems to lack support for writing code to files other than `init.vim`. For example, many neovim users put filetype specific settings inside the `after/ftplugin` directory, or they might use the `autoload` directory for functions that only need to be sourced when called.

This sort of directory hierarchy is standard in (neo)vim and there should be some way to follow it when using the neovim module.

#### Maintainer CC

@rycee 
@teto

**Comment by teto** [comment]
The good thing about loading the user init.vim is that now you are free to setup your dotfiles there whichever way you want. I symlink some of them via stow and for dynamic files I use home-manager. For instance for treesitter grammars:
` home.file."${config.xdg.configHome}/nvim/parser/c.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-c}/parser";`

**Comment by noib3** [comment]
> The good thing about loading the user init.vim is that now you are free to setup your dotfiles there whichever way you want

Could you elaborate on that? When I open a python file I know that neovim will automatically run (if present) the code inside `after/ftplugin/python.vim`. How would you replicate that behaviour with a single init.vim?

The only way to do what I described above with a single init.vim is to put all the could that I'd have inside `after/ftplugin/python.vim` inside some function, and then call that function with an `autocmd Filetype python ...`, which is bad because it forces you to put everything in one place instead of being able to modularize a config into its independent parts.

I know I could just divide my config into multiple files and manually source them from my init.vim, but vim's file system provides much more than that.

**Comment by teto** [comment]
so you can do
`home.file."${config.xdg.configHome}/nvim/after/ftplugin/python.vim".text = content of your file`

**Comment by noib3** [comment]
@teto thanks, I'm new to nix/home-manager and I didn't know you could do that.

If I choose to manage neovim myself instead of using the module, is there a way to get the native neovim lsp client to work? For example, I have `vimls` listed as a language server in neovim config (right [here](https://github.com/noib3/dotfiles/blob/7cb52907fd711bf0fae056332d2f892aed0418b4/defaults/nvim/lua/config/lsp.lua#L38)), and in my `home.nix` I have, among other things:
```
home.packages = with pkgs; [
  ...
  nodejs
  nodePackages.vim-language-server
  ...
];
```
however the server doesn't seem to be recognized, and if I edit a new `test.vim` the output of `:LspInfo` is
![Screenshot 2021-03-01 at 15 41 18](https://user-images.githubusercontent.com/59321248/109512820-c697e280-7aa4-11eb-87d6-d49c9faa2b16.png)

**Comment by teto** [comment]
if you check your logs ? (you can type `gf` over the filename). Seems like it doesn't load your lsp config at all otherwise it would display vimls as a compatible one. Try to simplify/fix your init.lua

**Comment by noib3** [comment]
@teto turns out I wasn't loading the `nvim-lspconfig` plugin. Now I am but I'm getting this error on startup:

![Screenshot 2021-03-02 at 16 47 14](https://user-images.githubusercontent.com/59321248/109674567-4db58b00-7b77-11eb-9e8a-8ed523816304.png)

the file in question is [this](https://github.com/noib3/dotfiles/blob/master/defaults/nvim/lua/config/lsp.lua) one, in particular line 2 which is
```lua
vim.lsp.callbacks["textDocument/publishDiagnostics"] = function() end
```
there seems to be some kind of problem with the `vim.lsp.callbacks` function. I'm using the neovim nightly build from https://github.com/nix-community/neovim-nightly-overlay.

**Comment by teto** [comment]
try `vim.lsp.handlers["textDocument/publishDiagnostics"]`, callbacks was renamed to handlers a few months ago.
