### ISSUE TITLE
rofi: configuration format has changed

### ISSUE THREAD

**Issue by srid** [nix-community/home-manager#1836]
### Issue description

home-manager generates old configuration format for rofi, which leads to this complaint in stderr:

```
(process:11380): Rofi-WARNING **: 11:37:15.065: Please upgrade: rofi -upgrade-config.
```

The new config file is named [`config.rasi`](https://wiki.archlinux.org/index.php/Rofi#Configuration) (not `config` - which home-manager generates as a symlink to read-only store), and running the above command will generate the .rasi file, overriding home-manager's config.

#### Maintainer CC

@thiagokokada 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0, NixOS, 21.05pre272380.f6b5bfdb470 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre272380.f6b5bfdb470, home-manager, nixos-hardware, nixpkgs-master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by thiagokokada** [comment]
We already generate a `config.rasi` file since PR #1736. You're probably using an older version of Home-Manager, maybe from release 20.09 instead of master.

**Comment by srid** [comment]
Hmm, for some reason using `https://github.com/nix-community/home-manager/archive/master.tar.gz` as the nix channel is not bringing in the latest master branch.

**Comment by srid** [comment]
I've switched away from using nix-channel to resolve this.
