### ISSUE TITLE
Bash aliases aren't expanded in functions

### ISSUE THREAD

**Issue by ncfavier** [nix-community/home-manager#1843]
https://github.com/nix-community/home-manager/blob/e72e241d7a602559285205820cfd708282a4197a/modules/programs/bash.nix#L174-L185

Because of the surrounding `if` statement, and because of how Bash parsing works, alias expansion in the entire statement occurs using the aliases *that were defined before the statement*, e.g. those in /etc/bashrc.

This means that, if I defined `programs.bash.shellAliases.bar = "baz";` and `programs.bash.initExtra = "foo() { bar; }";`, then my `foo` function wouldn't work properly as `bar` would not get expanded to `baz`.

The usual way to solve this is to replace the `if` statement with something like `[[ $- == *i* ]] || return` at the top of bashrc, but this in turn means that we lose the ability to expand `programs.bash.bashrcExtra` with commands that should be run by non-interactive shells (is there even a use case for that?).

A possible solution would be to do something like

```nix
{
  home.file.".bashrc".text = ''
    ${cfg.nonInteractiveLoginInit}
    [[ $- == *i* ]] || return
    ${historyControlStr}
    ${shoptsStr}
    ${aliasesStr}
    ${cfg.initExtra}
  '';
}
```

CC @rycee

**Comment by berbiche** [comment]
@ncfavier would you like to open a PR?

**Comment by ncfavier** [comment]
Done.
