### ISSUE TITLE
git: Change the order of sections

### ISSUE THREAD

**Issue by jokogr** [nix-community/home-manager#1845]
### Issue description

I cannot alter the order of sections in the git config file, they are always put in alphabetical order.

I would like to use an includeIf section in my git config, so that I can override my user details, e.g., my desired global gitconfig would like like this:

```
[user]
	email = "xxx"
	name = "xxx"

[includeIf "gitdir:~/custom/"]
	path = "~/custom/.gitconfig"
```

#### Maintainer CC

@rycee 

#### Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixpkgs-21.05pre270820.4ef6da455e9"`
 - channels(joko): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by berbiche** [comment]
Are you using `includes` option of `programs.git`?

https://github.com/nix-community/home-manager/blob/e72e241d7a602559285205820cfd708282a4197a/modules/programs/git.nix#L327-L338

The generated includes are "appended" to the `git/config` file (line 336-337).

**Comment by jokogr** [comment]
🤦 totally missed that and had put the configuration setting as an attribute in `extraConfig`. Sorry for the spam.
