### ISSUE TITLE
Regression in modules/programs/gpg.nix: Generating duplicate keys clobbers keys that expect lists

### ISSUE THREAD

**Issue by seylerius** [nix-community/home-manager#1859]
### Issue description

In PR https://github.com/nix-community/home-manager/pull/1814, which fixes the inability to duplicate single-item keys like `trusted-key` reported in https://github.com/nix-community/home-manager/issues/1644 by making all list types convert to duplicate keys when the config file is generated, the merged change unfortunately breaks usage of keys that expect a list type. 

Here is my GnuPG configuration in my `home.nix`:

```nix
programs.gpg = {
    enable = true;
    settings = {
      personal-cipher-preferences = [ "AES256" "AES192" "AES" ];
      personal-digest-preferences = [ "SHA512" "SHA384" "SHA256" ];
      personal-compress-preferences = [ "ZLIB" "BZIP2" "ZIP" "Uncompressed" ];
      default-preference-list = [
        "SHA512"
        "SHA384"
        "SHA256"
        "AES256"
        "AES192"
        "AES"
        "ZLIB"
        "BZIP2"
        "ZIP"
        "Uncompressed"
      ];
      cert-digest-algo = "SHA512";
      s2k-digest-algo = "SHA512";
      s2k-cipher-algo = "AES256";
      charset = "utf-8";
      fixed-list-mode = true;
      no-comments = true;
      no-emit-version = true;
      keyid-format = "0xlong";
      list-options = "show-uid-validity";
      verify-options = "show-uid-validity";
      with-fingerprint = true;
      require-cross-certification = true;
      no-symkey-cache = true;
      use-agent = true;
      throw-keyids = true;
    };
  };
```

#### Testing and workaround

To test the configuration, I ran `gpg -v --symmetric /tmp/foo` (using a test file containing only `foo`). The result I got used the cipher option `AES`, when it should have used `AES256`.

```
~ λ gpg -v --symmetric /tmp/foo
gpg: pinentry launched (28141 qt 1.1.0 /dev/pts/2 dumb :0)
gpg: using cipher AES
gpg: writing to '/tmp/foo.gpg'
```

Concatenating the lists with `lib.concatStringsSep " " [ ... ]` is a viable workaround for now, and produces the correct test result:

```
~ λ gpg -v --symmetric /tmp/foo
gpg: pinentry launched (31545 qt 1.1.0 /dev/pts/3 dumb :0)
gpg: using cipher AES256
File '/tmp/foo.gpg' exists. Overwrite? (y/N) y
gpg: writing to '/tmp/foo.gpg'
```

#### Theories

What seems to be happening under the hood here is that repeated invocations of list-type options like `personal-cipher-preferences` replace prior values. This means that the least-preferred option specified in every such preference list will instead be treated as the only preference. 

#### Suggestions

I don't know how many single-item keys can be invoked repeatedly like `trusted-key` can, in `gpg.conf`. If it's comparatively few, we're likely better off special-casing those to duplicate if they're provided as lists. On the other hand, if lots of options can be invoked repeatedly, and comparatively few expect lists, then we're likely better off special-casing those list-expecting keys to concatenate as space-separated strings. This may require some investigation, and I'm not _entirely_ sure where to look.

#### Maintainer CC

@berbiche @SuprDewd @offlinehacker

#### Technical details

```~ λ nix-shell -p nix-info --run "nix-info -m"```

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.2, NixOS, 21.05pre274338.102eb68ceec (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre274338.102eb68ceec"`
 - channels(seylerius): `"home-manager, nixos-20.09-20.09.3383.37b47da04ca, nixpkgs-master, nur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
This is not a regression. Lists were not supported prior to #1814.

Support for lists was added to allow for duplicate keys.

**Comment by berbiche** [comment]
@seylerius would it be sufficient to update the documentation to resolve this issue for you?

**Comment by berbiche** [comment]
@seylerius friendly ping :)

**Comment by seylerius** [comment]
Yes, definitely. A documentation update clarifying all this would be excellent.
