### ISSUE TITLE
QSyncthingTray is no longer actively maintained

### ISSUE THREAD

**Issue by plabadens** [nix-community/home-manager#1860]
### Issue description

QSyncthingTray, which is used for the tray in the `syncthing` module, is no longer actively maintained: [QSyncthingTray](https://github.com/sieren/QSyncthingTray). It's also marked as broken in nixpkgs since this PR:  https://github.com/NixOS/nixpkgs/commit/3a325159c5647883524b634941e6cb4dc27fe572

Would it make sense to move to an alternative like [syncthingtray](https://github.com/Martchus/syncthingtray)? That one in particular seems to have similar functionality, platforms (incl. macOS) and dependencies (also QT-based).

#### Maintainer CC

@rycee

**Comment by berbiche** [comment]
@plabadens would you like to open a PR? :smiley:

**Comment by plabadens** [comment]
Sure, I'll have a look at it. It doesn't seem too complicated.

**Comment by berbiche** [comment]
@plabadens
Already implemented in #1257

**Comment by plabadens** [comment]
> Already implemented in #1257

Thanks for the heads up. Hopefully it will get merged soonish.
