### ISSUE TITLE
attribute pname missing

### ISSUE THREAD

**Issue by jpotier** [nix-community/home-manager#1868]
### Issue description

```
building Nix...
building the system configuration...
error: attribute 'pname' missing, at /var/src/home-manager/modules/programs/tmux.nix:9:49
(use '--show-trace' to show detailed location information)
```

This started happening a couple of days ago. In my /var/src/home-manager I have the current master tip checked out. I'm on NixOS unstable, but cannot update because of this.

Enabling:

```nix
program.tmux.enable = true;
```

is enough to trigger this behavior.

#### Maintainer CC

Last person to touch tmux.nix is @toonn (problem is probably not coming from your change, but who knows)

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre276379.266dc8c3d05"`
 - channels(eeva): `""`
 - nixpkgs: `/nix/store/sig1vywg7gjgnq8igj9203zjrlcim1vl-nixpkgs-src`

**Comment by toonn** [comment]
Weird, it's as if it's expecting the module to have a pname attribute which is only for packages afaik? No idea why it's happening.

**Comment by jpotier** [comment]
I think I've found the problem: I have a custom tmux plugin defined like so:

```nix
      programs.tmux.plugins = with pkgs.tmuxPlugins; [
        (pkgs.stdenv.mkDerivation {
          pluginName = "nord";
          src = pkgs.fetchFromGitHub {
            owner = "arcticicestudio";
            repo = "nord-tmux";
            rev = "4e2dc2a5065f5e8e67366700f803c733682e8f8c";
            sha256 = "0l97cqbnq31f769jak31ffb7bkf8rrg72w3vd0g3fjpq0717864a";
          };
        })
      ];
```

For some reason, this is not good enough anymore, it needs `pname` and other stuff too nowadays

**Comment by jpotier** [comment]
(rant)

there's a nice `mkTmuxPlugin` function [there](https://github.com/timstott/nixpkgs/blob/daea4b1134f46c39a886143a0cbcb55d95d54529/pkgs/misc/tmux-plugins/default.nix#L15), but it's not exported :'(
