### ISSUE TITLE
shell completion not enabled on Ubuntu

### ISSUE THREAD

**Issue by srid** [nix-community/home-manager#1871]
### Issue description

`programs.password-store` installs and configures password-store, but it would be great if it also enabled shell completion on bash, etc. The NixOS module does this exactly.

#### Maintainer CC

@pacien 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72-microsoft-standard-WSL2, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(srid): `"home-manager, nixpkgs-21.05pre275813.c5147860e23"`
 - nixpkgs: `/home/srid/.nix-defexpr/channels/nixpkgs`
```

**Comment by rycee** [comment]
I can't find any NixOS module for password-store, do you have its path in Nixpkgs?

In any case, the shell completion files should be installed with the package, not handled externally. So I think a change of the pass package would be a better solution than changing Home Manager.

**Comment by pacien** [comment]
The home-manager password-store module adds the pass package to the home packages.
This package already contains the completion files for bash, fish and zsh,
which should automatically be linked and already be discovered by those shells.

Fish already seem to use the pass completion file on my machine without any special setup.

I don't see any equivalent module in NixOS either.

**Comment by srid** [comment]
Sorry, I meant the package `pass`.

> This package already contains the completion files for bash, fish and zsh,
which should automatically be linked and already be discovered by those shells.

I use `bash` on Ubuntu (WSL on Windows), and have home-manager's bash enabled:

```nix
    bash = {
      enable = true;
    };
```

This generates a .bashrc that contains:

```bash
if [[ :$SHELLOPTS: =~ :(vi|emacs): ]]; then
  . /nix/store/m64g9nbqz6hlm1kj8d2nfrv9mpjng44h-fzf-0.25.1/share/fzf/completion.bash
  . /nix/store/m64g9nbqz6hlm1kj8d2nfrv9mpjng44h-fzf-0.25.1/share/fzf/key-bindings.bash
fi
```

Perhaps this explains the issue? Why is `pass` not on this list?

**Comment by srid** [comment]
By the way, this happens for `git` as well. But `fzf -<TAB>` works.  My home.nix is here: https://github.com/srid/home.nix/blob/66b551c/home.nix

**Comment by srid** [comment]
Confirmed this to happen on Ubuntu, independent of WSL.

**Comment by kamadorueda** [comment]
something like:

```
for completion_script in ~/.nix-profile/share/bash-completion/completions/*
do
  source "${completion_script}"
done
```

should do, but yes, it would be nice to have it built-in

**Comment by elebeaup** [comment]
I have the same issue but on fish shell. The password store autocompletion is not enabled when the password store module is enabled. Note that the package pass contains the completion files for fish.
```
$ ls /nix/store/5gmdr40ibd7qahy5kjk0z87sfjzfi8s9-password-store-1.7.4/share/fish/vendor_completions.d/
pass.fish
```

**Comment by aslibman** [comment]
> something like:
> 
> ```
> for completion_script in ~/.nix-profile/share/bash-completion/completions/*
> do
>   source "${completion_script}"
> done
> ```
> 
> should do, but yes, it would be nice to have it built-in

Thought the home-manager bash module's [enableCompletion](https://github.com/nix-community/home-manager/blob/bb4b25b302dbf0f527f190461b080b5262871756/modules/programs/bash.nix#L32) would handle this, but couldn't get it to source the completion files. Ended up using the above workaround instead. +1 to this getting fixed.
