### ISSUE TITLE
home-manager instantiate fails if configuration sets programs.vim.package

### ISSUE THREAD

**Issue by Fendse** [nix-community/home-manager#1875]
### Issue description

If the home-manager configuration sets the `programs.vim.package` attribute, `home-manager instantiate` fails with the error message "The option \`programs.vim.package\` is read-only, but is set multiple times."

#### Maintainer CC

@uvNikita 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.92, NixOS, 20.09.2750.85abeab48b5 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2750.85abeab48b5, home-manager, unstable-21.03pre265961.891f607d530"`
 - channels(fendse): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Fendse** [comment]
A minimal configuration file that exhibits this issue for testing purposes: https://gist.github.com/Fendse/f4629e5d063333970687003226b60eaa

**Comment by teto** [comment]
some options are readonly, it's just for you to be able to retreive the vim package configured by home-manager. If you want to pass a different vim , I think you should do it via an overlay
