### ISSUE TITLE
`sharedModules` are not passed `pkgs` arg

### ISSUE THREAD

**Issue by nrdxp** [nix-community/home-manager#1878]
When using home-manager from NixOS, and attempting to use the option `sharedModules` added in #1793, modules defined therein are not passed the `pkgs` arg. Not sure if this is entirely isolated to `sharedModules` as #1767 seemed to have a similar problem.

## reproduce
setup a minimal nixos config as outlined in the [doc](../blob/master/README.md#nix-flakes).

Add a module to `sharedModules`:
```nix
{
  home-manager.sharedModules = [ ({ pkgs, ... }: { home.packages = [ pkgs.hello ]; }) ];
}
```
profit!

**Comment by berbiche** [comment]
```
home-manager.sharedModules  = [ ({ pkgs, ... }: { home.packages = [ pkgs.hello; ] }) ];
```

Is the example incorrect?

**Comment by nrdxp** [comment]
> Is the example incorrect?
Sorry, I edited the issue description with a proper example, thank you.

**Comment by Pacman99** [comment]
I can't come up with a good explanation as to why this this problem exists. Maybe someone with a better understanding of the module system might have an idea. I thought `_module.args` can be set in any module and all other modules would have access to those args.

**Comment by Pacman99** [comment]
I think I figured out the issue, its because of the type of `sharedModules` is `functionTo` and it fails while running the merge function of the `functionTo` type. So I think the best solution would be to switch it to `listOf anything`. I just tested on devos, and the module is getting pkgs now.
