### ISSUE TITLE
waybar doesn't recognice clock#date

### ISSUE THREAD

**Issue by Dschorim** [nix-community/home-manager#1884]
### Issue description

When using "clock#date" or "clock#time" inside of programs.waybar.settings.modules, home-manager gives me a warning 
trace: warning: The custom module 'clock#date' defined in 'programs.waybar.settings.[].modules' is not a valid module name. A custom module's name must start with 'custom/' like 'custom/mymodule' for instance
but these module names exist in waybar

#### Maintainer CC

@plabadens 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.24, NixOS, 20.09.3547.9b8530e3721 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.3547.9b8530e3721, nixos-unstable-21.05pre277486.f5e8bdd07d1"`
 - channels(me): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
This was fixed in f4b5ae026cb61b46fb447df5f783547ae2501861 which unfortunately isn't in Home Manager 20.09.

Since these are warnings, they can be safely ignored.

The other option is to upgrade to Home Manager unstable, but you would then need to upgrade your entire system to unstable.

**Comment by berbiche** [comment]
Closing this as a solution has been provided.
