### ISSUE TITLE
Termite unconditionnaly sets up VTE hook

### ISSUE THREAD

**Issue by Ambroisie** [nix-community/home-manager#1909]
### Issue description

Reopening because I accidentally closed the previous one when trying to edit it.

Since 67ebe16b406950651de09448cd5afdb437545be6, the `termite` module sets up VTE integration unconditionally. This is fine, but documented nowhere, furthermore, given that we have a module dedicated to VTE integration, I think it would be better to use that instead. Right now the issue about `PROMPT_COMMAND` mentioned in that file is not handled in the `termite` module

#### Maintainer CC

@zimbatm I guess, given that he authored the change

**Comment by Ambroisie** [comment]
For future reference, there's a `Reopen issue` button *at the bottom* of the page, instead of having two of the same issue :upside_down_face:...

**Comment by zimbatm** [comment]
Sounds good, I'm happy if you make the integration more flexible.

**Comment by Ambroisie** [comment]
I will submit a PR to enable it by default when `termite` is enabled.
