### ISSUE TITLE
For Firefox make it possible to set settings user pref type

### ISSUE THREAD

**Issue by rhoriguchi** [nix-community/home-manager#1914]
Make it possible to set the `user.js` setting pref type. Firefox has these [types](https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig#w_functions-of-autoconfig). What would be needed is to make it possible to set the `pref` type on this [line](https://github.com/nix-community/home-manager/blob/be56b6f2c5df6a4da8c91d4a3174f77d66c35533/modules/programs/firefox.nix#L58).

In my opinion, if you manage firefox with home-manager it should be `lockPref`, that way all configured options are immutable.

**Comment by berbiche** [comment]
Hi @rhoriguchi,

If I understand correctly, this seems to already be possible using `programs.firefox.profiles.<name>.extraConfig` where `profiles` is an attribute set of profiles.

https://github.com/nix-community/home-manager/blob/be56b6f2c5df6a4da8c91d4a3174f77d66c35533/modules/programs/firefox.nix#L54-L62

where the `extraPrefs` argument comes from `extraConfig`:

https://github.com/nix-community/home-manager/blob/be56b6f2c5df6a4da8c91d4a3174f77d66c35533/modules/programs/firefox.nix#L315

**Comment by rhoriguchi** [comment]
This is my current setup:
- [base repository](https://github.com/rhoriguchi/nixos-setup/blob/master/configuration/users/rhoriguchi/firefox/default.nix)
- [work repository](https://github.com/rhoriguchi/nixos-setup-work/blob/master/rhoriguchi/firefox/default.nix). 

What I want to achieve is that `lockPref` is set on all values so that I can later overwrite a couple of values in my work config.

---

An option would be to use `extraConfig` and use `lockPref` to lock all values and then use `replaceStrings` in my work config. But that solution is not that nice.

**Comment by rhoriguchi** [comment]
I've looked into this a bit more. This needs to happen in the firefox package itself. I'm not sure how I can overlay it so that I can overwrite `"${pkgs.firefox}/lib/firefox/defaults/pref/autoconfig.js"`.

Somewhere here I would assume:
https://github.com/nix-community/home-manager/blob/be56b6f2c5df6a4da8c91d4a3174f77d66c35533/modules/programs/firefox.nix#L281-L289

Other changes:

https://github.com/nix-community/home-manager/blob/be56b6f2c5df6a4da8c91d4a3174f77d66c35533/modules/programs/firefox.nix#L54-L62
```nix
  mkSettingJs = type: prefs: extraPrefs: ''
    // Generated by Home Manager.

    ${concatStrings (mapAttrsToList (name: value: ''
      ${type}("${name}", ${builtins.toJSON value});
    '') prefs)}

    ${extraPrefs}
  '';
```

https://github.com/nix-community/home-manager/blob/be56b6f2c5df6a4da8c91d4a3174f77d66c35533/modules/programs/firefox.nix#L315

```nix
            text = mkSettingJs "user_pref" profile.settings profile.extraConfig;
```

Add something like this to be able to configure that file:
```nix
      autoConfig = mkOption {
        type = mkOption {
          type = types.enum [ "clearPref" "defaultPref" "lockPref" "pref" ];
          default = "lockPref";
          description = "Sets the <link xlink:href="https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig#w_functions-of-autoconfig">auto config</link> setting type for all settings.";
        };

        settings = mkOption {
          settings = mkOption {
            type = with types; attrsOf (either bool (either int str));
            default = {};
            example = literalExample ''
              {
                "browser.startup.homepage" = "https://nixos.org";
                "browser.search.region" = "GB";
                "browser.search.isUS" = false;
                "distribution.searchplugins.defaultLocale" = "en-GB";
                "general.useragent.locale" = "en-GB";
                "browser.bookmarks.showMobileBookmarks" = true;
              }
            '';
            description = "Attribute set of Firefox preferences for all users.";
          };

          extraConfig = mkOption {
            type = types.lines;
            default = "";
            description = "Extra preferences to add to <filename>autoconfig.js</filename>."
          };
        };
      };
```

**Comment by berbiche** [comment]
If I understand correctly, you want an option to configure the autoconfig.js file?
In that case, you should open a feature request or a PR on nixpkgs with the desired functionality then HM could expose options to configure the new settings.
