### ISSUE TITLE
option 'home.homeDirectory' is not of type 'path'

### ISSUE THREAD

**Issue by mjlbach** [nix-community/home-manager#1931]
### Issue description

This seems to be a regression from 348b5a5, `home-manager switch` fails with 
```
error: A definition for option `home.homeDirectory' is not of type `path'. Definition values:
       - In `/nix/store/wjalf5il10ajlb8ymsr2zv0bhaynpd4b-source/modules/home-environment.nix': ""
(use '--show-trace' to show detailed location information)
 ```
Note, I am using a flake. This is the relevant section (and my home-directory still exists ofc)
https://github.com/mjlbach/nix-dotfiles/blob/16cdd3510fb6e5e8a55bda4df1839de51a8e7cc2/nixpkgs/flake.nix#L73-L96

#### Maintainer CC

@fricklerhandwerk 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.13-300.fc34.x86_64, Fedora, 34 (Workstation Edition)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(michael): `"nixpkgs-21.05pre278688.c0e88185200"`
 - channels(root): `"nixpkgs-21.03pre262018.cc8db6e19b8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Note, I am using a flake so the above is marginally useful re channels.

**Comment by simonc-cn** [comment]
https://github.com/nix-community/home-manager/commit/348b5a5a6945a1b345bf650e50d4c2ad1fe9d9b8 is the culprit; the first comment on the commit mentions the problem.

**Comment by rycee** [comment]
I found some issues with the option documentation that I've fixed now. Dunno if it will have an effect on your configuration but you can give the latest master a try.

**Comment by mjlbach** [comment]
Seems fixed! Thank you :)

**Comment by NickCao** [comment]
By the way, it seems that gpg-agent is broken. Maybe some missing changes to the systemd unit file?

**Comment by fricklerhandwerk** [comment]
`systemd.user.sessionVariables` are not accessible under macOS (no `systemd`), so we have to use both.
