### ISSUE TITLE
Unable to configure some starship options

### ISSUE THREAD

**Issue by liketechnik** [nix-community/home-manager#1935]
### Issue description

Some starship options require to have `\[` inside of strings (cf. https://starship.rs/config/#example-49). I tried various escapes, but either got more than one backslash in the generated toml file (e. g. "\\]" -> `\\]` or "\\\\]" -> `\\\\]`) or none ("\]" -> "]").
 

### Meta

I'm not 100% sure this is the right place to file this issue, because the issues seems to be caused by `pkgs.formats.toToml`/`builtins.toJSON` rather than the starship module itself.

#### Maintainer CC

@marsam 

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.111, NixOS, 20.09.20210413.dec334f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(florian): `"nixpkgs-21.05pre282548.4c87cb87a2d"`
 - nixpkgs: `/home/florian/.nix-defexpr/channels/nixpkgs`

**Comment by berbiche** [comment]
I don't seem to encounter this issue in my starship configuration.

When using double single-quote strings, backslashes are escaped i.e `''\'' == "\\"` and `''\\'' == "\\\\"`

Here's an excerpt from my configuration:
``` nix
{
  settings.time.format = "[\\[$time\\]]($style) ";
  settings.character = {
    error_symbol = ''[\$](bold red)'';
    success_symbol = ''[\$](bold green)'';
  };
  settings.git_status.format = "([\\[$conflicted$deleted$modified$untracked$ahead_behind\\]]($style) )";
}
```

**Comment by liketechnik** [comment]
That's weird. I have 
```nix
      time = {
        disabled = false;
        format = "🕙[\\[$time\\]]($style) ";
        time_format = "%H:%M:%S";
      };
```
in my nix configuration.
Activating it results in 
```toml
[time]
disabled = false
format = "🕙[\\[$time\\]]($style) "
time_format = "%H:%M:%S"
```
in `~/.config/starship.toml`.
This gets displayed as `🕙[]()  ❯` by starship.

**Comment by berbiche** [comment]
The icon at the beginning could be the culprit?

To test: move the symlink `mv ~/.config/starship.toml{,.bak}`, copy the file `cp ~/.config/starship.toml{.bak,}`, modify the config file and starship should reload the prompt automatically. You can experiment with this and figure out the right escaping to use.

**Comment by liketechnik** [comment]
To rule out bugs in an old version of starship (nixos 20.09 ships 0.44, unstable has 0.52) I changed the starship package to the unstable version. This didn't fix the issue, but I've made an interesting observation, due to starship providing a `timings` subcommand in more recent versions:
```
~ via 🐏 4GiB/15GiB | 0B/18GiB via tab florian/
[]()  ❯ starship timings

 Here are the timings of modules in your prompt (>=1ms or output):
 tab           -  29ms  -   tab florian/
 directory     -   2ms  -   ~
 battery       -   1ms  -
 memory_usage  -  <1ms  -   using 35% | 0% mem
 line_break    -  <1ms  -   \n
 time          -  <1ms  -   [13:48:31]
 character     -  <1ms  -   ❯

~ via 🐏 4GiB/15GiB | 0B/18GiB via tab florian/
[]()  ❯
```
So somehow the time isn't displayed correctly when displayed as a bash prompt. I'm using the `programs.starship.enableBashIntegration` option to use starship for my prompt.

**Comment by liketechnik** [comment]
I fixed the issue by using the starship version from the unstable branch. 

Nevertheless, thank you very much for your help figuring out this issue :)
