### ISSUE TITLE
i3 / sway font configuration is misleading

### ISSUE THREAD

**Issue by alarsyo** [nix-community/home-manager#1937]
#### Font size placement

[The description and example](https://github.com/nix-community/home-manager/blob/6aa6556bcab6dc0f6398b4daa8404d788fd7a6a2/modules/services/window-managers/i3-sway/lib/options.nix#L13-L17) for the `i3.config.fonts` (respectively `sway`) option is misleading. I just spent 30 minutes debugging a font display issue before opening [the i3 documentation](https://i3wm.org/docs/userguide.html#fonts) and realizing the example and description were wrong :smile: .

Specifically, the i3 documentation example shows that **only one** font size can be passed in the entire line, after a comma separated list of font families, so the following example:

```nix
[ "FontAwesome 10" "Terminus 10" ]
```

should be

```nix
["FontAwesome" "Terminus 10" ]
```

to require the FontAwesome and Terminus fonts, in size 10.

Note that this makes the semantics of the `fonts` option weird, as only the last font in the list should have a size.

How about introducing `fontSize` as an additional option, and append it at the end of the line, to guarantee correctness? This would break backwards compatibility though, unless it's not appended when unset.

#### Description is wrong about font ordering

Additionally, the description states:

> The order here is important (e.g. icons font should go before the one used for text).

While it's true that the order is important, icons fonts should go **after** the one used for text, at least in my testing. Putting FontAwesome first leads i3 to use it for text as well, and it's not a monospace font.

### Illustration of the font size issue

1. With this in my configuration, and font-awesome installed from nixpkgs, I get the correct behavior:

```nix
{
  bars = [
    {
      statusCommand = "i3status-rs ${barConfigPath}";
      fonts = [ "DejaVuSansMono" "FontAwesome5Free 9" ];
    }
  ];
}
```

![image](https://user-images.githubusercontent.com/15170378/115309416-88e23c80-a16c-11eb-9425-ea511cd91e87.png)

Note the correct volume muted icon.

2. With this configuration:

```nix
{
  bars = [
    {
      statusCommand = "i3status-rs ${barConfigPath}";
      fonts = [ "DejaVuSansMono 9" "FontAwesome5Free 9" ];
    }
  ];
}
```

I get this:

![image](https://user-images.githubusercontent.com/15170378/115309545-be872580-a16c-11eb-897c-7b485c5ef039.png)

The font isn't DejaVuSansMono, probably because i3 parsed the font line `DejaVuSansMono 9, FontAwesome5Free 9` differently and didn't find a match for `DejaVuSansMono 9`. The icon is still fine though.

3. Finally using this configuration:

```nix
{
  bars = [
    {
      statusCommand = "i3status-rs ${barConfigPath}";
      fonts = [ "FontAwesome5Free 9" "DejaVuSansMono 9" ];
    }
  ];
}
```

I get 
![image](https://user-images.githubusercontent.com/15170378/115309800-0f971980-a16d-11eb-8a91-40b9ab61042d.png)

Note the broken volume mute icon, because this time it's FontAwesome that isn't found correctly because of the extra font size added.

#### Maintainer CC

@alexarice @sumnerevans for sway, couldn't find any maintainer for i3wm.

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05.20210410.a73020b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `"nixos-21.05pre283367.0a5f5bab0e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alarsyo** [comment]
Note that I don't know if sway follows the same behavior, as I'm using i3.

**Comment by alarsyo** [comment]
Also, the `[<style options>]` mentioned in the i3 doc would also need their own parameter, as they also need to be specified after the last font family, like so:

```
[ "DejaVuSansMono" "Terminus Bold Semi-Condensed 10"]
```

otherwise they'd get intertwined with commas as well

**Comment by alexarice** [comment]
Perhaps a good solution would be to have each font in a separate "font" statement as the examples are. I'm not sure if this actually works (in sway or i3) but if it did I think this would sort the issues. I'm not sure about adding a `fontSize` option as I presume it is fine for you to have different fonts at different sizes at the same time

**Comment by alarsyo** [comment]
I'll try that and get back to you 😄

**Comment by alarsyo** [comment]
Unfortunately it looks like i3 overrides the previous font configuration line, only the last `font` line is used, from what I could see during my tests

**Comment by sumnerevans** [comment]
I confirmed that this issue exists on sway as well. Maybe it's worth separating out that config option into `fontNames` and `fontSize` or something along those lines?

**Comment by alarsyo** [comment]
Thanks for taking the time to check! I've only been using home manager for a week, but I do think it'd be worthwhile. Happy to provide a tentative implementation in a PR if you think that's a good solution

**Comment by sumnerevans** [comment]
@alarsyo I'm working on a PR right now. I'll add you as a reviewer.
