### ISSUE TITLE
i3 module uses deprecated settings new_window, new_float

### ISSUE THREAD

**Issue by alarsyo** [nix-community/home-manager#1938]
### Issue description

The i3wm module generates a configuration file [that uses `new_window` and `new_float`](https://github.com/nix-community/home-manager/blob/6aa6556bcab6dc0f6398b4daa8404d788fd7a6a2/modules/services/window-managers/i3-sway/i3.nix#L160-L165). These settings have been deprecated, as noted [in the documentation](https://i3wm.org/docs/userguide.html#_default_border_style_for_new_windows), and should now use the [same options as sway](https://github.com/nix-community/home-manager/blob/6aa6556bcab6dc0f6398b4daa8404d788fd7a6a2/modules/services/window-managers/i3-sway/sway.nix#L268-L273).

The deprecation is [3 years old](https://github.com/i3/i3/commit/f8d6c10d7c34fd9510fc220ebf14d8cde5866708), effective since i3 v4.15 released in march 2018, so this should be a relatively low impact change.

#### Maintainer CC

No maintainer for i3wm :(

**Comment by teto** [comment]
PR welcome
