### ISSUE TITLE
`xresources.properties` generates file with wrong permissions

### ISSUE THREAD

**Issue by IvarWithoutBones** [nix-community/home-manager#1940]
### Issue description
When setting my `Xresources` through home-manager. the file generated ends up having the wrong permissions assigned to it.
Because of this, `xrdb` cannot modify/open the file, leaving the generation to fail.

```
~ > home-manager switch
/nix/store/740j7ql9g87mcc42x8ykhmb39mbzhwss-home-manager-generation
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating linkGeneration
Cleaning up orphan links from /home/ivv
No change so reusing latest profile generation 4
Creating home file links in /home/ivv
Activating onFilesChange
/nix/store/rg7ca74ggnfj2vgbp0gb9vgcasdi0ami-xrdb-1.2.0/bin/xrdb: Permission denied
/nix/store/rg7ca74ggnfj2vgbp0gb9vgcasdi0ami-xrdb-1.2.0/bin/xrdb: can't open file '/home/ivv/.Xresources'
~ > cat .Xresources
cat: .Xresources: Permission denied
~ > ls -l .Xresources
lrwxrwxrwx 1 ivv users 74 Apr 21 23:58 .Xresources -> /nix/store/pxhlgi93msxv65irnn6k8yb0w8qbpbhv-home-manager-files/.Xresources
~ > sudo cat .Xresources
[sudo] password for ivv:
background: #2f343f
...
```

#### Maintainer CC

@rycee 

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.13, NixOS, 21.05pre283367.0a5f5bab0e0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ivv): `"home-manager, nixpkgs-21.05pre283745.93184413f21"`
 - channels(root): `"nixos-21.05pre283367.0a5f5bab0e0"`
 - nixpkgs: `/home/ivv/.nix-defexpr/channels/nixpkgs`

**Comment by rycee** [comment]
Hmm, not certain why this would happen. The only thing I can think of is that there is something wrong with your Nix store. All files inside the Nix store should be world readable. The symlink HM creates doesn't add or remove any permissions.

What does `ls -l $(readlink -f ~/.Xresources)` say?

**Comment by IvarWithoutBones** [comment]
After removing home-manager and all it's generations, and than running `nix-collect-garbage`, the issue still seemed to occur. After changing one of the values of `xresources.properties`, it seemingly magically resolved itself.

My guess is that home-manager was pulling a cached `.Xresources` files, which somehow had wrong permissions assigned to it. I'd imagine this cached item would get removed afer removing all home-manager generations and running `nix-collect`garbage`, but I guess it didn't.

I have no idea why this happened, but everthing does seem to work fine now.
