### ISSUE TITLE
Neovim test is broken

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#1942]
### Issue description

@teto I think your recent change to neovim in nixpkgs broke one of the test case.

See the build log in https://github.com/nix-community/home-manager/pull/1939/checks#step:7:1669 and #1941

```
neovim-plugin-config: FAILED
Expected /dev/fd/63 to be same as /nix/store/1hm86ygdj96jh1105bm4zfn584wmsvan-plugin-config.vim but were different:
--- actual
+++ expected
@@ -0,0 +1,22 @@
+" configuration generated by NIX
+set nocompatible
+
+
+
+
+
+
+set packpath^=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vim-pack-dir
+set runtimepath^=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vim-pack-dir
+
+filetype indent plugin on | syn on
+
+
+" This should be present in vimrc
+" vim-commentary {{{
+" This should be present too
+autocmd FileType c setlocal commentstring=//\ %s
+autocmd FileType c setlocal comments=://
+
+" }}}
+
For further reference please introspect /nix/store/l0pwmyf3s7gl8wy99j6mjx6hl7vnvrkq-nmt-report-neovim-plugin-config
```

### Meta

@teto @mjlbach

**Comment by teto** [comment]
Yeah it's top be expected, the `filetype indent plugin on | syn on` should have disappeared and possibly the 
```
+" configuration generated by NIX
+set nocompatible
```
too

**Comment by teto** [comment]
@rycee is that diff normal ? Looks like it is comparing against an empty file even though the init.vim exists and is generated.

**Comment by sumnerevans** [comment]
What does the `assertFileExists` function do? Maybe it gobbles up the stream from the stdin redirection before the diff that gets shown to the user?
