### ISSUE TITLE
Cannot install Home Manager on Solus - nix-build: command not found

### ISSUE THREAD

**Issue by FrankelJb** [nix-community/home-manager#1958]
### Issue description

I have installed Nix on `Solus` using the [quick install](https://nixos.org/download.html#nix-quick-install). When I try to install Home Manager using the installation instructions in the README. However, I get the following error and cannot proceed. I tried to install in a virtual machine on KVM and encountered the same error.

```
beans@solus ~ $ nix-shell '<home-manager>' -A install

Creating initial Home Manager generation...

/nix/store/z09qnf51zvn7rmd7mliij75p97jbhf50-home-manager/bin/home-manager: line 114: nix-build: command not found
/nix/store/z09qnf51zvn7rmd7mliij75p97jbhf50-home-manager/bin/home-manager: line 114: nix-build: command not found
/nix/store/z09qnf51zvn7rmd7mliij75p97jbhf50-home-manager/bin/home-manager: line 127: /run/user/1000/home-manager-build.brsvYkagEK/news-info.sh: No such file or directory

Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

I have checked that `nix-build` is installed:

```
beans@solus ~ $ nix-build --version
nix-build (Nix) 2.3.10
```

#### Technical details

```
beans@solus ~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.12-177.current, Solus, 4.2`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(beans): `"home-manager-20.09, nixpkgs-20.03.3328.6d1a044fc9f"`
 - nixpkgs: `/home/beans/.nix-defexpr/channels/nixpkgs`
```

**Comment by berbiche** [comment]
Do you have the profile.sh thingy in your user's `~/.bashrc`? Otherwise `nix-build` and other commands are not added to your PATH and thus unavailable to the Home Manager script.

**Comment by FrankelJb** [comment]
RTFM. That solved the problem. Closing as resolved

**Comment by kenota** [comment]
@berbiche @FrankelJb can you share what `profile.sh` thingy is?

**Comment by FrankelJb** [comment]
@kenota check [the end of part 2](https://github.com/nix-community/home-manager#installation). You need to add `export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH` to your `bashrc` (whatever shell you're using)

**Comment by kenota** [comment]
@FrankelJb ah, I see. Thank you for the reply. 

I did that initially, but it did not fix things for me. I am still getting same errors. Seems that something breaks when nix-shell is invoked, because I do have nix-build available in my path in my shell.

Will keep digging.

**Comment by kenota** [comment]
For anybody having the similar issues and stumbling upon this: I managed to find the culprit on my machine. For some reason, during the installation, the following line was not added to my bashrc:

```sh
if [ -e /Users/kenota/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/kenota/.nix-profile/etc/profile.d/nix.sh; fi;
```

After adding this line - installation is working correctly.
