### ISSUE TITLE
Firefox profile is not being created

### ISSUE THREAD

**Issue by gbaranski** [nix-community/home-manager#1961]
### Issue description

Firefox profile is not being created after `home-manager switch`. When launching firefox it automatically creates new profile named `<random_hash>.default`, and because of that extensions don't want to work.

#### Maintainer CC

@rycee 

#### Technical details

```
[gbaranski@xps ~] nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.13, NixOS, 20.09.3933.00f9323c271 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(gbaranski): `"home-manager, nixpkgs-21.05pre285721.39a51c9923e"`
 - channels(root): `"nixos-20.09.3933.00f9323c271, nixos-unstable-21.05pre284379.93de027ee04"`
 - nixpkgs: `/home/gbaranski/.nix-defexpr/channels/nixpkgs`
```

Firefox configuration:
```nix
{ config, pkgs, ... }:
let
  nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
    inherit pkgs;
  };
in
{
  home.sessionVariables.BROWSER = "firefox";
  programs.firefox = {
    enable = true;
    extensions = with nur.repos.rycee.firefox-addons; [
      vimium
      ublock-origin
    ];
    package = pkgs.wrapFirefox pkgs.firefox-unwrapped {
      forceWayland = true;
      extraPolicies = {
        ExtensionSettings = {};
      };
    };
    profiles = {
      home = {
        settings = {
          "apz.gtk.kinetic_scroll.enabled" = false;
          "general.smoothScroll" = false;
          "browser.download.dir" = "${config.home.homeDirectory}/dl";
        };
      };
    };
  };
}
```

**Comment by gbaranski** [comment]
Issue resolved, it turned out that `home-manager switch` failed every time because of missing `gnome3.dconf` dependency, but the error was not colored in red so I thought that's just warning. I've found about this after uninstalling home-manager and installing again where none of my program configurations were restored.

**Comment by berbiche** [comment]
Was dconf missing from the home-manager binary's environment or was it an issue in your configuration?

**Comment by gbaranski** [comment]
> Was dconf missing from the home-manager binary's environment or was it an issue in your configuration?

It was issue with my configuration.
