### ISSUE TITLE
Make lua library available at runtime

### ISSUE THREAD

**Issue by ashinkarov** [nix-community/home-manager#1964]
### Issue description

I want to include a plugin for neovim that relies on a certain lua library to be present at runtime.  Specifically, I need a `luautf8` library, for lua version 5.1, as this is the one that is built into neovim.

First, I can verify that a clean installation of neovim (via home-manager), launched in the `nix-shell -p lua51Packages.luautf8` can access the desired lua library:
```bash
nvim -c "lua require('lua-utf8')" -c "q"
```
runs successfully.  Now, I am trying to achieve similar behavior, but without explicit `nix-shell -p ...`.

Following the lua and home-manager docs, I have created the following overlay in `home.nix`:
```nix
  # Overlay
  nixpkgs.overlays = [
    (self: super: {
      mylua = pkgs.lua5_1.withPackages (ps: [ ps.luautf8 ]);
    })
  ];
```
then, I have added `mylua` to extraPackages of neovim like so:
```nix
  programs.neovim = {
    enable = true;
    vimAlias = true;
    extraPackages = [ 
      pkgs.mylua
    ];
  };
```
while this builds successfully, neovim cannot access `lua-utf8` and `nvim -c "lua require('lua-utf8')" -c "q"` fails with an error.

As a final sanity check, if I add `pkgs.mylua` to `home.packages`, I can run lua, and it can access the library.

#### Maintainer CC

Not sure, but it seems that @ThibautMarty committed neovim.nix.

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.29, NixOS, 21.05pre282843.dcdf30a78a5 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(tema): `"home-manager"`
 - channels(root): `"nixos-21.05pre282843.dcdf30a78a5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
cc @teto

**Comment by teto** [comment]
extraPackages just adds the package into the PATH of neovim. You could adjust the LUA_PATH in the neovim/wrapper, override the lua environment of neovim to add this package etc. These previous solutions seem a bit hackish though. What plugin do you want to install ? so that I can try on my machine.

**Comment by ashinkarov** [comment]
Right, so you are saying that additionally to `rubyEnv` and `python3Env` we could have `luaEnv` in the definition of `makeNeovimConfig`?

As for the package, I am writing a wrapper for my own plugin: https://github.com/ashinkarov/nvim-agda
So far, I have the following definition that seem to work:
```nix
  nvim_agda = pkgs.vimUtils.buildVimPlugin {
    name = "nvim-agda";
    src = pkgs.fetchFromGitHub {
      owner = "ashinkarov";
      repo = "nvim-agda";
      rev = "master";
      sha256 = "1wwmpd3b9kqih46xls3w8kkyjxmn9wsqagx7lgn8gs2wm5xrs1rm";
    };
    # This doesn't help
    # propagatedBuildInputs = [ pkgs.mylua ];
  };

```
However, the content of the plugin is irrelevant to the problem.  The point is to make neovim load the lua library with `:lua require('lua-utf8')`.

**Comment by teto** [comment]
something like that yes. 
In HM , there is 
```
extraMakeWrapperArgs = lib.optionalString (cfg.extraPackages != [ ])
    ''--suffix PATH : "${lib.makeBinPath cfg.extraPackages}"'';
```
you oculd patch home-manager to add an `" --suffix LUA_PATH ";" "${luaPackages.luautf8}"`  in the wrapper arguments.
I asked about the plugin because I expect lua plugins to rely  more and more on other lua libraries so we will need to come up with something cleaner later, probably the luaEnv you mentioned. If you want to submit a nixpkgs PR, you can assign it to me.

**Comment by ashinkarov** [comment]
Ok, here is my initial experiment with extending HM with extraLuaPackages.  While it solves my problem, there is an annoying problem that I'd like to get an advice for.
```diff
diff --git a/modules/programs/neovim.nix b/modules/programs/neovim.nix
index e5b2c0c..b29d593 100644
--- a/modules/programs/neovim.nix
+++ b/modules/programs/neovim.nix
@@ -22,6 +22,14 @@ let
     merge = mergeOneOption;
   };

+  extraLua51PackageType = mkOptionType {
+    name = "extra-lua51-packages";
+    description = "lua5.1 packages in lua5_1.withPackages format";
+    check = with types;
+      (x: if isFunction x then isList (x pkgs.lua51Packages) else false);
+    merge = mergeOneOption;
+  };
+
   pluginWithConfigType = types.submodule {
     options = {
       config = mkOption {
@@ -66,6 +74,12 @@ let
   extraMakeWrapperArgs = lib.optionalString (cfg.extraPackages != [ ])
     ''--suffix PATH : "${lib.makeBinPath cfg.extraPackages}"'';

+
+  mkLuaPath = lib.makeSearchPathOutput "lib/lua/5.1/?.so" "lib/lua/5.1/?.so";
+
+  extraMakeWrapperLuaArgs = lib.optionalString (cfg.extraLuaPackages != [ ])
+    ''--suffix LUA_CPATH ";" "${mkLuaPath cfg.extraLuaPackages}"'';
+
 in {
   options = {
     programs.neovim = {
@@ -152,6 +166,17 @@ in {
         '';
       };

+      extraLuaPackages = mkOption {
+        type = with types; either extraLua51PackageType (listOf package);
+        default = (_: [ ]);
+        defaultText = "ps: []";
+        example = literalExample "(ps: with ps; [ luautf8 ])";
+        description = ''
+          A function in lua5_1.withPackages format, which returns a
+          list of Lua packages required for your plugins to work.
+        '';
+      };
+
       package = mkOption {
         type = types.package;
         default = pkgs.neovim-unwrapped;
@@ -267,7 +292,7 @@ in {
     programs.neovim.finalPackage = pkgs.wrapNeovimUnstable cfg.package
       (neovimConfig // {
         wrapperArgs = (lib.escapeShellArgs neovimConfig.wrapperArgs) + " "
-          + extraMakeWrapperArgs;
+          + extraMakeWrapperArgs + " " + extraMakeWrapperLuaArgs;
       });

     programs.bash.shellAliases = mkIf cfg.vimdiffAlias { vimdiff = "nvim -d"; };
```

The thing is that `mkLuaPath` has to know whether the lua package is providing an `*.so` or `*.lua` file(s), and set either LUA_PATH or LUA_CPATH, otherwise the interpreter gets confused and die.  One could surely construct these checks manually, however, I am wondering whether a similar functionality already exists in HM or nixpkgs.

If the code above looks ok, I can open a work-in-progress PR.
