### ISSUE TITLE
Document unclear on how to use targets.darwin.keybindings

### ISSUE THREAD

**Issue by jwiegley** [nix-community/home-manager#1973]
I have several keybindings that I use, which I was installing manually before under nix-darwin. I'd like to switch to use the new feature of home-manager, but I can't figure out where to put the attribute definition. What should it look like inside my home.nix?

**Comment by jwiegley** [comment]
https://github.com/jwiegley/nix-config/blob/master/config/home.nix#L93 is where I'd like to define it, or thereabouts.

**Comment by sumnerevans** [comment]
Is this the documentation you are looking for? https://github.com/nix-community/home-manager/blob/master/modules/targets/darwin/keybindings.nix#L11

I think that this brings up a bigger issue which is that the documentation doesn't seem to show Darwin-only options.

**Comment by rycee** [comment]
I believe the locally generated documentation should include the Darwin options. I.e., the documentation that shows up when running
- `home-manager-help` (if `manual.html.enable = true`) or
- `man home-configuration.nix` (if `manual.html.enable = true`).

We just don't generate the darwin documentation in the documentation pipeline. I hope to eventually fix that.

**Comment by sumnerevans** [comment]
Hmm... I tried setting `manual.html.enable`, but it didn't seem to change the documentation that was created.

I think that the reason that the pipeline doesn't generate the docs is because the pipeline is running on Linux, so none of the modules that are gated on `hostPlatform.isDarwin` are loaded.

**Comment by rycee** [comment]
@sumnerevans Yeah, because it is a bit tricky to generate the Darwin documentation on GNU/Linux I've avoided that. I imagine the ideal would be to have a single documentation with the Linux and Darwin options in two separate appendices. This would require reworking the documentation infrastructure, though.

A simpler solution for now may be to simply set up a darwin pipeline that builds its own documentation and pushes it to https://nix-community.github.io/home-manager/darwin or something.

**Comment by jwiegley** [comment]
I read the documentation on what it *does*, I still have no idea how/where to declare these settings in my `home.nix` so that home-manager accepts them.

**Comment by rycee** [comment]
Ah, right! Sorry, I misunderstood. Unfortunately I have no experience about the use of this module but from what I can tell something like
```
targets.darwin.keybindings = {
  "^u" = "deleteToBeginningOfLine:";
};
```
should work. But the module providing these options is only available if `pkgs.stdenv.hostPlatform.isDarwin == true`, perhaps this condition fails some reason?

Perhaps @midchildan has some insights?

**Comment by jwiegley** [comment]
Here's what I get using the above form:
```
Vulcan ~ $ u vulcan switch
HOSTNAME=vulcan
CACHE=vulcan
BUILDER=vulcan
make: Entering directory '/Users/johnw/src/nix'

┌────────────────────────────────────────────────────────────────────────────┐
│ >>> darwin-rebuild switch                                                  │
└────────────────────────────────────────────────────────────────────────────┘
building the system configuration...
error: The option `home-manager.users.johnw.targets' does not exist. Definition values:
- In `/Users/johnw/src/nix/config/darwin.nix':
    {
      darwin = {
        keybindings = {
          "^/" = "undo:";
          "^a" = "moveToBeginningOfLine:";
    ...
(use '--show-trace' to show detailed location information)
make: *** [Makefile:82: switch] Error 1
make: Leaving directory '/Users/johnw/src/nix'
```

**Comment by jwiegley** [comment]
In `darwin.nix` I have:
```
  home-manager = {
    # useUserPackages = true;
    useGlobalPkgs = true;
    users.johnw = import ./home.nix;
  };
```

And in `home.nix` you can see the settings here: https://github.com/jwiegley/nix-config/blob/master/config/home.nix#L719

**Comment by jwiegley** [comment]
I wonder if mixing nix-darwin and home-manager is part of the problem?

**Comment by rycee** [comment]
Good question. The only reason I can think for you not having those options available is that the platform is misdetected for some reason. The detection is done through `pkgs.stdenv.hostPlatform.isDarwin` and since `useGlobalPkgs` is enabled, the `pkgs` will come from nix-darwin. But I would be very surprised if nix-darwin ends up a disabled `isDarwin` 🙂

Could you try adding something like

    home.file.HMHOST.text = with pkgs.stdenv.hostPlatform; "${system} - ${toString isDarwin}";

to your configuration and see what HM thinks you are running?

**Comment by jwiegley** [comment]
```
Vulcan ~ $ cat HMHOST
{"isDarwin":true,"system":"x86_64-darwin"}
```

**Comment by midchildan** [comment]
At a glance, the [configuration posted by @jwiegley](https://github.com/jwiegley/nix-config/blob/d25f4aab2daa9a83a319bc0ea806a16a597579b9/config/home.nix#L614-L641) looks correct to me.

I also use it for [my own configuration](https://github.com/midchildan/dotfiles/blob/02183d028a323209f3ae926fed03c34cc3d44729/home/.config/nixpkgs/home.d/dotfiles/profiles/desktop.nix#L130-L133), and it's working as intended:

```console
❯ cat ~/Library/KeyBindings/DefaultKeyBinding.dict
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>^u</key>
	<string>deleteToBeginningOfLine:</string>
	<key>^w</key>
	<string>deleteWordBackward:</string>
</dict>
</plist>
```

**Comment by midchildan** [comment]
I experimented with a smaller configuration for better illustration of how it's supposed to work:

```console
❯ cat key.nix
{ ... }:

{
  targets.darwin.keybindings = {
    "^u" = "deleteToBeginningOfLine:";
    "^w" = "deleteWordBackward:";
  };
}
```

With the above configuration, HM generates the following configuration:

```console
❯ home-manager build -f key.nix
/nix/store/q3glfwxh09lyrfnjlb8wxn5xr6zpqs3d-home-manager-generation

There are 8 unread and relevant news items.
Read them by running the command 'home-manager news'.

❯ tail result/activate

noteEcho Activating onFilesChange


noteEcho Activating setCocoaKeybindings
$VERBOSE_ECHO "Configuring keybindings for the Cocoa Text System"
$DRY_RUN_CMD install -Dm644 $VERBOSE_ARG \
  "/nix/store/20c5blg70izn54hphxqmirhrdpazqr8g-DefaultKeybinding.dict" "/Users/midchildan/Library/KeyBindings/DefaultKeyBinding.dict"


❯ cat /nix/store/20c5blg70izn54hphxqmirhrdpazqr8g-DefaultKeybinding.dict
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>^u</key>
	<string>deleteToBeginningOfLine:</string>
	<key>^w</key>
	<string>deleteWordBackward:</string>
</dict>
</plist>
```

**Comment by midchildan** [comment]
@jwiegley I think I found the source of the error. It looks like your copy of HM has the Darwin code disabled. https://github.com/jwiegley/home-manager/blob/0cc4f09518d5fef2a70c89431a3278b116f54871/modules/modules.nix#L215

**Comment by jwiegley** [comment]
I have a feeling then that this has to do with using home-manager by way of nix-darwin, rather than directly...

**Comment by jwiegley** [comment]
@midchildan Oh wow, that would be funny if weren't so sad. My apologies everyone. This is something I had to disable many months ago due to a conflict in application linking, but which should no longer be necessary. Thank you for the bountiful help!

**Comment by rycee** [comment]
Nice find @midchildan, much appreciated that you took the time to find the cause!
