### ISSUE TITLE
session's $PATH does not include nix-profile or cfg.sessionPath anymore

### ISSUE THREAD

**Issue by xvello** [nix-community/home-manager#1999]
### Issue description

After upgrading home-manager today, the xsession `$PATH` does not include the right folders anymore. I am running KDE Neon (with a Ubuntu 20.04 system base).

Although interactive shells have the right path, plasmashell and krunner cannot start applications installed via home-manager, as their $PATH is incorrect.

### Logs from `~/.xsession-errors`:

Before (correct, includes `~/.nix-profile/bin` and my custom `~/.config/nixpkgs/bin` from cfg.sessionPath):
> dbus-update-activation-environment: setting PATH=/home/xavier/.nix-profile/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xavier/.config/nixpkgs/bin

After (incorrect):
> dbus-update-activation-environment: setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

### Possible cause

I suspect a regression has been introduced by https://github.com/nix-community/home-manager/pull/1797, as my `hm-session-vars.sh` got this new line at the end:

> export $(/nix/store/bmvjq883zj2vxgynl8p47za39lrg0ypi-systemd-247.6/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)

Running this script on my system resets `$PATH` to the hardcoded initial list matching my distribution's `/etc/environment` file:

```
$ /nix/store/bmvjq883zj2vxgynl8p47za39lrg0ypi-systemd-247.6/lib/systemd/user-environment-generators/30-systemd-environment-d-generator
LOCALE_ARCHIVE_2_27=/nix/store/7dz31dq4n1r0wqq3r28r7975cql68n8w-glibc-locales-2.32-40/lib/locale/locale-archive
NIX_PATH=/home/xavier/.nix-defexpr/channels:/home/xavier/.nix-defexpr/channels:/home/xavier/.nix-defexpr/channels
QT_ACCESSIBILITY=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
```

#### Maintainer CC

@tadfisher author of https://github.com/nix-community/home-manager/pull/1797
@berbiche who reviewed and merged

Is it intentional to call `30-systemd-environment-d-generator` at the very end, or would it make sense to call it earlier, so that `cfg.sessionVariables` and `cfg.sessionPath` can still override it?

As sourcing the nix PATH [is also done in sessionVariablesExtra](https://github.com/nix-community/home-manager/blob/23769994e8f7b212d9a257799173b120ed87736b/modules/targets/generic-linux.nix#L42-L47), ordering them correctly might prove tricky.

#### Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/rcw3a87m7jycgr6hfbg6zrnr3fj6wg20-nix-info
copying path '/nix/store/rcw3a87m7jycgr6hfbg6zrnr3fj6wg20-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-50-generic, KDE neon, 5.21`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(xavier): `"home-manager, nixpkgs-21.05pre288317.357e6b3560f"`
 - nixpkgs: `/home/xavier/.nix-defexpr/channels/nixpkgs`
```

**Comment by tadfisher** [comment]
@rycee This was added specifically as a universal mechanism to configure XDG system directory variables (`XDG_DATA_DIR`, `XDG_CONFIG_DIR`) while having them available in both the systemd user session and login shells. The background of this is [this issue](https://github.com/nix-community/home-manager/issues/284) requesting support for Gnome Shell extension configuration. This works fine as-is on NixOS, because nothing is setting `PATH` in [environment.d](https://www.freedesktop.org/software/systemd/man/environment.d.html), but it looks like Ubuntu does. Personally I would prefer to use the system's mechanism of setting PATH for user sessions, which is `environment.d` for Ubuntu, but this configuration is non-obvious, so I would be fine with reverting #1797 in favor of a more targeted solution.

@xvello Can you check [these directories](https://www.freedesktop.org/software/systemd/man/environment.d.html) on your system for a config file that sets `PATH`? You should be able to override it with `systemd.user.sessionVariables.PATH`.

**Comment by ony** [comment]
I would expect that [`systemd-environment-d-generator`](https://www.freedesktop.org/software/systemd/man/systemd-environment-d-generator.html#) mostly used to populate environment from scratch like [user service environment](https://www.freedesktop.org/software/systemd/man/environment.d.html) where newly started process have no environment to inherit it from. Hence, I expect plain assignments being used often.  

I also expect that if intention of  `environment.d` was to set also variables for user shell, then it will be run alongside with other [environment generators](https://www.freedesktop.org/software/systemd/man/systemd.environment-generator.html#) during login procedure via something like [`pam_systemd`](https://www.freedesktop.org/software/systemd/man/pam_systemd.html#Environment). And if it is not happening, then maybe split between user session and user services is intended. I think decision about changing that might require more thoughts and not necessary should block exposing some XDG variables to services :wink: .

**Comment by terlar** [comment]
I agree that if we do decide to revert, let’s keep the XDG variables parts and only get rid of the `30-systemd-environment-d-generator` part.

**Comment by berbiche** [comment]
@tadfisher instead of reverting everything, would it be enough to revert only what @terlar suggested?

**Comment by rycee** [comment]
Yes, please do that. In principle perhaps `systemd-environment-d-generator` is OK to use in the user session but I think it needs to be done after careful consideration.

**Comment by xvello** [comment]
@tadfisher do have the bandwidth to re-scope #2001 to just the 30-systemd-environment-d-generator part, or do you want me to open a PR to do so?

My current workaround on ubuntu is to comment out the PATH export from `/etc/environment`, but it's very hacky.

**Comment by tadfisher** [comment]
I've udpated #2001 to revert the usage of `30-systemd-environment-d-generator`. `xdg.systemDirs` now also exports its variables via `home.sessionVariables` to achieve the same effect.

**Comment by berbiche** [comment]
#2001 was merged. Is there anything else that needs to be done?

**Comment by xvello** [comment]
Works good now, my PATH has all expected elements in the right order. Thanks!

**Comment by d12frosted** [comment]
When using `fish` as user shell my `PATH` is still in the incorrect order:

```
$ echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Library/Apple/usr/bin /usr/local/MacGPG2/bin /Library/TeX/texbin /Users/d12frosted/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin
```

Notice that `/usr/bin` comes before `.nix-profile/bin`, which shadows `coreutils`. 

When I change my shell to `bash` everything seems fine (except for duplicating entries):

```
$ echo $PATH
/Users/d12frosted/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/d12frosted/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin
```

I am installing `home-manager` via `flake` and my current commit is 6a471f1b1111408d541caf04e64650813bfb22ac, which is the first child of 01ec2aaefeeed45764841cf42e1de56e01209e66.

Any suggestions?
