### ISSUE TITLE
xdg.configFile.<name>.onChange always triggered

### ISSUE THREAD

**Issue by jakzale** [nix-community/home-manager#2004]
### Issue description

`xdg.configFile.<name>.onChange` gets executed always if

- `users.users.<username>.home` is not set, or
- `xdg.configFile.<name>.source` is pointing at a directory.

Regarding the former:
- `users.users.<username>.home` is not set in default configuration (at least in `nix-darwin`),
-  it's default value is `/var/empty`,
- [`homeDir`](https://github.com/nix-community/home-manager/blob/db00b39a9abec04245486a01b236b8d9734c9ad0/modules/files.nix#L9) is set to `var/empty`,
- [`cmp`](https://github.com/nix-community/home-manager/blob/db00b39a9abec04245486a01b236b8d9734c9ad0/modules/files.nix#L241) ends up comparing against `/var/empty/.config/<name>` which does not exists, so
- `xdg.configFile.<name>.onChange` always trigger.

Regarding the latter:
- assuming that `users.users.<username>.home` is properly set,
- [`cmp`](https://github.com/nix-community/home-manager/blob/db00b39a9abec04245486a01b236b8d9734c9ad0/modules/files.nix#L241) ends up comparing a nix path, which is a directory and a link
- `cmp` returns an error code `2` and prints to stderr `... : Is a directory`
- `xdg.configFile.<name>.onChange` always trigger.

#### Maintainer CC

@rycee 

#### Technical details

```
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(jakub): `"darwin, home-manager, nixpkgs-21.05pre287374.1c16013bd6e"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/jakub/.nix-defexpr/channels/nixpkgs`

```

**Comment by sumnerevans** [comment]
For the first issue, I feel like just setting the `users.users.<username>.home` variable would be the appropriate solution here?

For the second issue, I don't think there's a ton we can do about that. It's very nontrivial to walk the tree to do a proper directory comparison, I think.

**Comment by jakzale** [comment]
> For the first issue, I feel like just setting the users.users.<username>.home variable would be the appropriate solution here?

Yes, that works.  Maybe adding a note in the docs would be suitable as well.

> For the second issue, I don't think there's a ton we can do about that. It's very nontrivial to walk the tree to do a proper directory comparison, I think.

I was thinking about replacing `cmp` with `diff -qr`.  Would that work?

**Comment by berbiche** [comment]
I'm not sure but since HM 20.09 we don't use a default username anymore though I might be wrong

**Comment by rycee** [comment]
@jakzale Just opened #2031, would you mind trying it out?

**Comment by jakzale** [comment]
@rycee sure.

**Comment by jakzale** [comment]
@ryce this works on my end.

However, I am slightly puzzled by the fact that I cannot repro the original issue with `cmp`:
- I can verify that the call to `cmp` in the activation script generated in `/nix/store` will return a non-zero result (because it is comparing a directory on the LHS, but
- in the `Activating onFilesChange` step there is nothing being run...

**Comment by spacekitteh** [comment]
> About the recursive check it may work OK but I think we should bail if `home.file.<name>.recursive` is used. Tomorrow I'll see if I can get something working.

So this broke my emacs config! Reproducing the comment from the commit:

Why is this? It has really screwed up my emacs config process. I use the onChange hook to delete the tangled config code in my ~/.config/emacs/; and I have a multi-layer directory structure.
