### ISSUE TITLE
Sourcing of nix.sh should be at the top of hm-session-vars.sh (and should take into account single vs multi-user installs)

### ISSUE THREAD

**Issue by colinxs** [nix-community/home-manager#2012]
### Issue description

`targets.generic-linux` currently contains the following:
```
    home.sessionVariablesExtra = ''
      . "${pkgs.nix}/etc/profile.d/nix.sh"
      # reset TERM with new TERMINFO available (if any)
      export TERM="$TERM"
    '';

    # We need to source both nix.sh and hm-session-vars.sh as noted in
    # https://github.com/nix-community/home-manager/pull/797#issuecomment-544783247
    programs.bash.initExtra = ''
      . "${pkgs.nix}/etc/profile.d/nix.sh"
      . "${profileDirectory}/etc/profile.d/hm-session-vars.sh"
    '';
```

There are two issues with this:
1) `"${pkgs.nix}/etc/profile.d/nix.sh"` is only correct for a single-user installation. On a multi-user install it should be either "${pkgs.nix}/etc/profile.d/nix-daemon.sh" or even better "/etc/profile.d/nix.sh" (which makes more sense given this is system-level configuration).'
2) Adding those lines with "sessionVariablesExtra" and "bash.initExtra" means they get tossed into their corresponding sources in whatever order they were loaded, making it difficult to override anything set in nix.sh/nix-daemon.sh. This is especially problematic for nix-daemon.sh, which sets `PATH`.

Possible solutions:

1) Add a `home.sessionVariablesExtraFirst` which goes at the top of the file so that `targets.generic-linux` can source nix.sh/nix-daemon.sh first. Then expose an option like `generic-linux.multiUser = {true || false}` or try and detect if it's a multi-user install at runtime (perhaps copying whatever logic `nix-info` performs, see below).
2) Manually recreate the logic in nix.sh/nix-daemon.sh as a separate module and don't source nix.sh/nix-daemon.sh directly
3) ???

#### Maintainer CC

No maintainer but tagging @rycee since this broadly effects users.

#### Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-7614-generic, Pop!_OS, 20.10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixpkgs-21.05pre281670.842f900e73c"`
 - nixpkgs: `/nix/store/8xvwfm02dicgbpkyyaqi0961nd01r8g0-source`
```

**Comment by berbiche** [comment]
Extra ccs (hopefully they won't mind): @terlar @tadfisher

**Comment by colinxs** [comment]
Another possible solution (and perhaps a module worth having anyways) is a `programs.nix` module that I cooked up today and have been using without issue. It handles the above issue and manages `NIX_PATH`, `NIX_PROFILES`, and `NIX_SSL_CERT_FILE` along with ~/.nix-defexpr.

Here it is: https://gist.github.com/colinxs/2898ecfb610ee613fef1329fe2c821d4

**Comment by pecigonzalo** [comment]
I believe this issue is still relevant
