### ISSUE TITLE
Disable default config feature

### ISSUE THREAD

**Issue by timsofteng** [nix-community/home-manager#2014]
Hello. I want to manage config for sway as plain file so I add it as `xdg.configFile` . But I got conflict of configs if sway module is enabled.
Is it any way to solve this conflict? I would save everything else module settings except config file to use my own.

Thanks.

**Comment by rycee** [comment]
Maybe something like `xdg.configFile."…".source = mkForce …` would work.

**Comment by timsofteng** [comment]
> Maybe something like `xdg.configFile."…".source = mkForce …` would work.

Got error
![image](https://user-images.githubusercontent.com/51912173/118472920-12584080-b712-11eb-9f53-8384894cb208.png)

**Comment by timsofteng** [comment]
BTW it would be nice to check priority. If user set something like `xdg.confiFIle` or `home.file` then home-manager config should not be created in that directories.

**Comment by berbiche** [comment]
> 
> 
> > Maybe something like `xdg.configFile."…".source = mkForce …` would work.
> 
> Got error
> ![image](https://user-images.githubusercontent.com/51912173/118472920-12584080-b712-11eb-9f53-8384894cb208.png)

@timsofteng try `lib.mkForce`.
You may need to add `lib` to the function "param" (assuming at the top): `{ config, lib, pkgs, ... }:`.

**Comment by timsofteng** [comment]
> > > Maybe something like `xdg.configFile."…".source = mkForce …` would work.
> > 
> > 
> > Got error
> > ![image](https://user-images.githubusercontent.com/51912173/118472920-12584080-b712-11eb-9f53-8384894cb208.png)
> 
> @timsofteng try `lib.mkForce`.
> You may need to add `lib` to the function "param" (assuming at the top): `{ config, lib, pkgs, ... }:`.

Unfrortunately it doesn't help.
In addition I find this solution slightly weiird.

**Comment by berbiche** [comment]
@timsofteng were you able to resolve your problem?

**Comment by timsofteng** [comment]
@berbiche the problem still exist
