### ISSUE TITLE
Syntax check shell scripts where possible (solution provided)

### ISSUE THREAD

**Issue by colinxs** [nix-community/home-manager#2015]
### Issue description

Quite a few times I've made a typo when configuring any one of ZSH/Bash/hm-session-vars.sh and didn't find out
until booting to wonderful message telling me my (.profile|.zlogin|etc) is corrupted. At that point I have to jump into a terminal,
fix the bug, and reboot. This tends to happen at the worst times.

To avoid this, I've added the following to my configuration:
```
home.activation.verifyBash =
  let
    exclude = [ "SC1090" ];
    exe = "${lib.getBin pkgs.shellcheck}/bin/shellcheck";
    check = shell: relPath:
      let path = config.home.path + "/${relPath}";
      in
      ''
        if [ -e ${path} ] \
          && ! ${exe} --shell=${shell} --exclude=${lib.concatStringsSep "," exclude} ${path}; then 
          errorEcho "Problem detected in ${path}"
          exit 1
        fi
      '';
  in
  lib.hm.dag.entryBefore [ "writeBoundary" ] ''
    ${check "bash" ".bashrc"}
    ${check "bash" ".bash_profile"}
    ${check "bash" ".bash_logout"}
    ${check "sh" ".profile"}
  '';
home.activation.verifyHMSessionVars =
  let
    path = config.home.path + "/etc/profile.d/hm-session-vars.sh";
    exclude = [ "SC1090" ];
    exe = "${lib.getBin pkgs.shellcheck}/bin/shellcheck";
  in
  lib.hm.dag.entryBefore [ "writeBoundary" ] ''
    if ! ${exe} --shell=sh --exclude=${lib.concatStringsSep "," exclude} ${path}; then 
      errorEcho "Problems detected in ${path}"
      exit 1
    fi
  '';
home.activation.verifyZSH = 
  let
    check = name: ''
      if ! ${zsh}/bin/zsh -n "${config.home.file."${relToDotDir name}".source}"; then
        errorEcho "Problem detected in ${config.home.file."${relToDotDir name}".source}"
        exit 1
      fi
    '';
  in
  lib.hm.dag.entryBefore [ "writeBoundary" ] ''
    ${check ".zshenv"}
    ${check ".zshrc"}
    ${lib.optionalString (cfg.profileExtra != "") (check ".zprofile")}
    ${lib.optionalString (cfg.loginExtra != "") (check ".zlogin")}
    ${lib.optionalString (cfg.logoutExtra != "") (check ".zlogout")}
  '';
```

If this is something worth having in home-manager (possible between a `check = true` option), I could make a PR.

**Comment by uvNikita** [comment]
I might be wrong here, but I think check like this can be done in nix build time, so even before activation. Similar to [writeShellScript](https://github.com/NixOS/nixpkgs/blob/ff6d2142ce18b323165a772a8d3f77fed86fa233/pkgs/build-support/trivial-builders.nix#L215) from nixpkgs.

I guess we could even use `writeShellScript` somewhere here to leverage its syntax checking: https://github.com/nix-community/home-manager/blob/6a471f1b1111408d541caf04e64650813bfb22ac/modules/programs/bash.nix#L192

**Comment by colinxs** [comment]
Yup, you totally can. This was just easier to do without changing
home-manager internally. Perhaps we could add a "home.file.checkPhase"
exactly how writeShellScript does it.

It would be nice to have a hook for "home.path" as well. That would let you
perform checks that require more than a single file. It would also let you
compile zsh scripts as I suggested elsewhere (zsh will bundle the entire
tree of sourced files into a single file).

**Comment by rycee** [comment]
Yeah, `writeShellScript` was my first idea as well and I've added that now. I think that resolves this issue but feel free to reopen if you disagree.

About `checkPhase` and similar for the `home.file` option, I'd prefer to avoid that and instead suggest using a function like `writeShellScript`.

And about modifying the result of `home.path`, this can be done by `home.extraProfileCommands`. It is marked as an internal option but I think it should be just fine to use in general.

**Comment by colinxs** [comment]
@rycee Not to nitpick, but I'm not sure `writeShellScript` is really what we want. Init scripts like .bashrc aren't really meant to be executable. Also, hm-session-vars.sh should really by `sh`-compliant, not `bash`-compliant and `writeShellCheck` does it's check with `bash -n`. systemd + friends commonly run using `sh`/`dash`.

I know you didn't like the `home.file.foo.checkPhase` idea, but what if that simply forwards to `pkgs.writeTextFile` which already has a `checkPhase`? That would allow you to use `sh -n` for hm-session-vars.sh as well as support zsh (via `zsh -n`). It also opens the path checking other file types. 

Of course that means you don't get `writeShellScript`'s check for free, but given that it's a single line of code I think it's manageable?

**Comment by rycee** [comment]
@colinxs Agreed that `writeShellScript` is not ideal but I think the appropriate solution would be to introduce in Nixpkgs functions like `writeShellText` (which is like `writeShellScript` but with `executable = false` and without a shebang) and `write{Dash,Zsh}{Script,Text}`, which would be much like their `writeShell*` counterparts but using dash and zsh instead.

I'd like to avoid introducing this functionality in HM because such functions would be of use across various Nix related projects, not just HM.

**Comment by colinxs** [comment]
Done: https://github.com/NixOS/nixpkgs/pull/123608

I agree nixpkgs would be a better home, so let's see what folks say!
