### ISSUE TITLE
Swaylock doesn't work in sway module

### ISSUE THREAD

**Issue by timsofteng** [nix-community/home-manager#2017]
I've сonfigured sway as wiki described:
https://nixos.wiki/wiki/Sway

But swaylock doesn't take my password. It print error even on correct one.
If I sway module enabled in nixos it works fine.

**Comment by berbiche** [comment]
You need to enable `programs.sway.enable = true` in your NixOS configuration otherwise swaylock does not have access to PAM to verify your user's credentials.
Under the hood, it sets `security.wrappers.swaylock.something` to allow the swaylock program access to PAM or to enable the suid functionality.

I might be wrong about the details.

**Comment by timsofteng** [comment]
> You need to enable `programs.sway.enable = true` in your NixOS configuration otherwise swaylock does not have access to PAM to verify your user's credentials.
> Under the hood, it sets `security.wrappers.swaylock.something` to allow the swaylock program access to PAM or to enable the suid functionality.
> 
> I might be wrong about the details.

But there is module for `sway` in `home-manager` as well. I supposed it should work same as nixos module...

**Comment by sumnerevans** [comment]
Well, I think it's because there are some things which the home-manager module cannot provide. For example, I am pretty sure that the PAM stuff must be configured system-wide.

**Comment by berbiche** [comment]
Closing this since there's nothing HM can do to fix the situation.

**Comment by Eisfunke** [comment]
By the way: the relevant PAM option from NixOS's sway config is here: https://github.com/NixOS/nixpkgs/blob/a575c243c23e2851b78c00e9fa245232926ec32f/nixos/modules/programs/sway.nix#LL137C5-L137C41

No need to set `programs.sway.enable` on the NixOS level, simply setting `security.pam.services.swaylock = {};` on the NixOS level suffices for swaylock to work (e.g. here in my [personal config](https://git.eisfunke.com/config/nixos/-/blob/84cb974f7096cb8cf515795cc577e6e40f807e74/src/configuration.nix#L41)).
