### ISSUE TITLE
Emacs service restart results in a server without a socket

### ISSUE THREAD

**Issue by TLATER** [nix-community/home-manager#2018]
### Issue description

With the emacs user service, running `systemctl --user restart emacs` after emacs was initially started results in a daemon without a socket if `emacs.socketActivation = true`.

That is, running with this config:

```nix
{ ... } : { 
  programs.emacs = {
    enable = true;
    package = pkgs.local.emacs;
  };

  services.emacs = {
    enable = true;
    client = {
      enable = true;
      arguments = [ "--no-wait" "--create-frame" ];
    };
    socketActivation.enable = true;
  };
}
```

To fix the service, making sure the emacs service is fully stopped and then restarting the socket will fix the problem.

I'm not sure how to approach this, I guess the problem is that emacs takes over the socket and then deletes it when it shuts down, which systemd doesn't expect? I can't find anything relevant in the `systemd.socket` documentation.

#### Maintainer CC

- @tadfisher 

#### Technical details

See [my flake](https://github.com/tlater/dotfiles) for the exact details:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16, NixOS, 20.09.20210512.327368f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-20.09.2750.85abeab48b5, nixos-hardware"`
 - channels(tlater): `"nixpkgs-21.05pre272788.870dbb751f4"`
 - nixpkgs: `/home/tlater/.nix-defexpr/channels/nixpkgs`

**Comment by rycee** [comment]
I don't know about Emacs deleting the socket but if the service is socket activated then I imagine it would make sense to have `RefuseManualStart=true` in the service definition?

**Comment by TLATER** [comment]
Hm, I'm not sure what that would be useful for. Should the socket not be handed over with a manual start? It seems to behave just fine when I try manually starting emacs with a running socket, no duplicate emacs instances are created and emacsclient connects to the emacs daemon normally.

The behavior I'm seeing also occurs when I'm purely relying on the socket, after the first stop of `emacs.service` it's impossible to re-launch any way except if `emacs.socket` is restarted. Using `systemctl --user restart` is just a bit easier to explain.

**Comment by berbiche** [comment]
> I imagine it would make sense to have `RefuseManualStart=true` in the service definition?

Oh, that would be a good addition.
I've encountered @TLATER's problem more than once.

This option would force the user to instead restart the socket instead of the systemd service.

**Comment by tadfisher** [comment]
ACK: Seems like a simple change. If someone doesn't PR it I can get to it this weekend.

**Comment by TLATER** [comment]
From digging around systemd, it seems like the real problem is that emacs cleans up its socket file while systemd expects it to stick around. Given that, disallowing the service restart for now makes sense, and I suppose I'll take the socket wrangling problem upstream.

Upstream emacs has a [systemd unit](http://git.savannah.gnu.org/cgit/emacs.git/tree/etc/emacs.service), by the way, which does not use the `(kill-emacs)` hack, and it uses `Type=notify`, which makes systemctl block appropriately; are we using the current unit because the emacs wiki documents it or is there another reason? It would be nice to stick a little closer to upstream.

The upstream unit is plagued by the same issue, so there's no workaround of emacs not cleaning up sockets if it's SIGTERMed or anything.

**Comment by rycee** [comment]
I think we typically would like to use a systemd unit that match upstream as much as possible, and if Emacs supports `Type=notify` that seems ideal.

**Comment by rycee** [comment]
Should be closable since #2034 is in master.
