### ISSUE TITLE
XDG user-dirs.conf permanently disabled

### ISSUE THREAD

**Issue by stelcodes** [nix-community/home-manager#2021]
Sorry for not using a template, I’m on my phone. I’m trying to enable xdg.userDirs but it seems like this line is preventing it from ever being enabled? Maybe I’m misunderstanding something. Cheers

https://github.com/nix-community/home-manager/blob/3612ca58e8d592e58762da9ea650f82b9c7c05d9/modules/misc/xdg-user-dirs.nix#L111

**Comment by sumnerevans** [comment]
@pacien as maintainer

**Comment by pacien** [comment]
This line prevents the `xdg-user-dirs-update` command from overwriting the configuration defined through home-manager.
It doesn't prevent it from being enabled.

From `man 5 user-dirs.conf`:

```
enabled=boolean
When set to False, xdg-user-dirs-update will not change the XDG user dirs configuration.
```
