### ISSUE TITLE
plasma-browser-integration fails to work. 

### ISSUE THREAD

**Issue by kingDaniel2004** [nix-community/home-manager#2029]
Hi there, I'm having a little issue with making `plasma-browser-integration` work in `nixos` (home.nix). The firefox extension fails to connect to the "native host".

![image](https://user-images.githubusercontent.com/55865975/118894748-d91afe80-b8d2-11eb-8d98-35e255ad3201.png)

When I try to install firefox via `home.packages`,  `plasma-browser-integration` totally works. However, it does not work when it installed it via `programs.firefox` in `home.nix`

![image](https://user-images.githubusercontent.com/55865975/118895814-e0dba280-b8d4-11eb-8795-fe87e93c54d9.png)

NOTE: `nixpkgs.config.firefox.enablePlasmaBrowserIntegration = true;` is included in home.nix. 

full config -> https://github.com/kingDaniel2004/.dotfiles/blob/master/nixOS/users/dani/home.nix 
package infos 
![image](https://user-images.githubusercontent.com/55865975/118896001-3fa11c00-b8d5-11eb-8152-e55847e3741f.png)

Thanks.

**Comment by ambroisie** [comment]
You can should try doing the following configuration in your `home.nix`:

```nix
config.programs.firefox = {
  enable = true;

  package = pkgs.firefox.override {
    cfg = {
      enablePlasmaBrowserIntegration = true;
    };
  };
};
```

**Comment by kingDaniel2004** [comment]
> You can should try doing the following configuration in your `home.nix`:
> 
> 
> 
> ```nix
> 
> config.programs.firefox = {
> 
>   enable = true;
> 
> 
> 
>   package = pkgs.firefox.override {
> 
>     cfg = {
> 
>       enablePlasmaBrowserIntegration = true;
> 
>     };
> 
>   };
> 
> };
> 
> ```

I tried this but no success. Nothing changed. But the config built without any error.

**Comment by knopki** [comment]
> Hey thanks for the respons. I tried this but no success. Nothing changed. But the config built without any error.

It's broken on `release-20.09` and resolved some time ago on `master`. If you won't update, you can try this temporary workaround:

```nix
{
# plasma 
home.file.".mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json".source = "${pkgs.plasma-browser-integration}/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json";
# others
home.file.".mozilla/native-messaging-hosts/com.github.browserpass.native.json".source = "${pkgs.browserpass}/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json";
home.file.".mozilla/native-messaging-hosts/tridactyl.json".source = "${pkgs.tridactyl-native}/lib/mozilla/native-messaging-hosts/tridactyl.json";
}
```

**Comment by kingDaniel2004** [comment]
> ```nix
> home.file.".mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json".source = "${pkgs.plasma-browser-integration}/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json";
> ```

Thank you so much, knopki :+1:  adding the following line works.
