### ISSUE TITLE
Neovim giving erroneous errors re: Python2

### ISSUE THREAD

**Issue by harris-chris** [nix-community/home-manager#2082]
### Issue description

Hello - I've recently updated my channel and am having some issues with neovim. If I add neovim to my home.nix with minimal config:

```
{
  programs.neovim = {
    enable = true;
  };
}
```

I then run home-manager switch and get
`error: Python2 support has been removed from neovim, please remove withPython and extraPythonPackages.`

I do not have either of these packages anywhere in my config - grep-ing for either of them reveals nothing.

Thanks for any assistance.

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.11pre293730.1ca6b0a0cc3 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(chris): `"home-manager-20.09, nixos-21.05pre285574.8e4fe32876c"`
 - channels(root): `"nixos-21.11pre293730.1ca6b0a0cc3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
Hi @harris-chris,

Are you using the unstable nixos/nixpkgs channel? This is a requirement of following Home Manager's "master" branch.

Otherwise you can use the same release of Home Manager as the channel you are using.

``` terminal
$ nix-channel --list
home-manager    https://.....

$ nix-channel --remove home-manager

# Update '21.05' in the command to the release you need
$ nix-channel --add 'https://github.com/nix-community/home-manager/archive/refs/heads/release-21.05.tar.gz' home-manager

$ nix-channel --update
```

(I may have made a mistake in the command, I am using the mobile GitHub app)

**Comment by harris-chris** [comment]
@berbiche - thank you - that works great.
