### ISSUE TITLE
dunst can't access pulseaudio when launched as user service

### ISSUE THREAD

**Issue by nodeven** [nix-community/home-manager#2083]
### Issue description
When dunst is launched as systemd user service (with `services.dunst.enable = true;` in home.nix) it and its child processes can't access pulseaudio. 
Access to pulseaudio is needed for audio notifications.
Running dunst manually works as expected.

`User = username` in service file probably solves this issue. 
#### Maintainer CC
@rycee 

#### Technical details
`~/.config/dunst/dunstrc`:
```conf
...
[sound_notification]
    summary = "*"
    script = ~/bin/sound_notification
...
```

`~/bin/sound_notification`:
```bash
#!/bin/sh

paplay ~/.local/share/sounds/freedesktop/stereo/bell.oga
```

Output from log file after notification pops up:
```
jun 07 16:02:09 hostname dunst[23040]: Connection failure: Connection refused
jun 07 16:02:09 hostname dunst[23040]: pa_context_connect() failed: Connection refused
```
---
`nix-shell -p nix-info --run "nix-info -m"` output:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.268, NixOS, 21.05.650.eaba7870ffc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.650.eaba7870ffc"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
> `User = username` in service file probably solves this issue. 

Home Manager only manages user files (things under /home/your-user) so the systemd service is already running as your user.

The problem looks like a misconfigured environment.
IIRC the pulseaudio socket is created in `XDG_RUNTIME_DIR/pulse`, where XDR_RUNTIME_DIR is usually `/run/user/$(id -u)/`.

The XDG_RUNTIME_DIR variable is automatically exposed by the systemd user session, without any configuration.

So another environment variable is required and I am not sure which.

**Comment by nodeven** [comment]
Oops, my fault. 
Problem is solved by adding the user to `audio` group. Looks like user services can't access pulseaudio's socket if user is not member of this group. Even if user can access it manually.

**Comment by berbiche** [comment]
> 
> 
> Oops, my fault.
> Problem is solved by adding the user to `audio` group. Looks like user services can't access pulseaudio's socket if user is not member of this group. Even if user can access it manually.

That's good to know.

It was apparently documented:
> You may need to add users to the audio group for them to be able to use audio devices:
> ```
> users.extraUsers.alice.extraGroups = [ "audio" ... ];
> ```
source: https://nixos.wiki/wiki/PulseAudio
