### ISSUE TITLE
mkOutOfStoreSymlink doesn't work as expected with a flake setup

### ISSUE THREAD

**Issue by folke** [nix-community/home-manager#2085]
### Issue description

I'm currently migrating my dotfiles to Nix using nix-darwin and the home-manager module.

One problem I'm having is that `mkOutOfStoreSymlink` doesn't seem to work when using flakes.

In the example below, the `.config/alacritty` directory will link to the flake sources (`/nix/store/54vrjl9afxg7ckb5waxy3w521f3mpi3j-hm_alacritty`) instead of the original directory in my `~/projects/dot/config/alacritty`.

```nix
 xdg.configFile."alacritty".source = config.lib.file.mkOutOfStoreSymlink ../../config/alacritty;
```

Is there any way to do what I want with the `flake.nix` setup?

**Comment by cole-h** [comment]
`mkOutOfStoreSymlink` also supports strings, so you can hardcode it as `mkOutOfStoreSymlink "${config.home.homeDirectory}/projects/dot/config/alacritty"`. If the location ever changes, you'll have to change it then as well.

**Comment by folke** [comment]
@cole-h that's exactly how I solved it :)

Closing this issue.

**Comment by andyrichardson** [comment]
@folke when providing a string argument, the link would then point to the source file within your home directory?

I've tried using a string but it's making no difference (NixOS)

```nix
xdg.configFile."Code/User/settings.json".source = config.lib.file.mkOutOfStoreSymlink  "${config.home.homeDirectory}/dev/dotfiles/nix/config/settings.json";
```

```sh
ls -l /home/andy/.config/Code/User/settings.json 
lrwxrwxrwx 1 andy users 94 Jun 15 12:39 /home/andy/.config/Code/User/settings.json -> /nix/store/9qqncknpzrfhw21kwa9k634ady5lm0bk-home-manager-files/.config/Code/User/settings.json
```

**Comment by folke** [comment]
You need to use a full path. That works in my case

**Comment by amardeep** [comment]
This is what i use currently:

- My flakes git repo is generally checkout in `$HOME/.dotfiles`. I create an option for this location which gives me the flexibility to override it for a particular host if needed:

```nix
  options = {
    dotfiles = lib.mkOption {
      type = lib.types.path;
      apply = toString;
      default = "${config.home.homeDirectory}/.dotfiles";
      example = "${config.home.homeDirectory}/.dotfiles";
      description = "Location of the dotfiles working copy";
    };
  };
```

Then, I use this option whenever i want to create a symlink to a file, for eg.

```nix
xdg.configFile."wezterm".source = config.lib.file.mkOutOfStoreSymlink "${config.dotfiles}/config/wezterm";

home.file.".p10k.zsh".source = config.lib.file.mkOutOfStoreSymlink "${config.dotfiles}/config/zsh/p10k.zsh";
```

**Comment by alexjp** [comment]
> Nix beginner here. I was baffled to see `mkOutOfStoreSymlink` symlinking to the store, regardless of whether or not I used a string. As already pointed out in [#2085 (comment)](https://github.com/nix-community/home-manager/issues/2085#issuecomment-861427318), the `mkOutOfStoreSymlink` function will **not** produce a direct symlink from source to target. Instead it will produce a **chain** of symlinks:
> 
> ```mermaid
> graph LR
>     source --> store --> target
> ```
> I lost about an hour before I realized what was going on. 🤦. Hopefully this saves someone else the time I wasted.

IMHO that is to be expected.

But you can achieve what you want (direct link bypassing the store) by using the `home.activation` scripts, example:

```
home.activation = {
   directlink = lib.hm.dag.entryAfter [ "writeBoundary" ] (''
     $DRY_RUN_CMD ln -sfvn /home/something/in/your/home /home/to/another/place
   '');
 };
```

Note: you can choose when to activate the script besides the "writeBoundary".

**Comment by codethief** [comment]
Another Nix newbie here. I'm with @maresb on this one, this is mind-boggling. How hard can it be to create a simple symlink in the home dir?¹ 

@alexjp 

> But you can achieve what you want (direct link bypassing the store) by using the home.activation scripts, example:

But then (if I have to create all symlinks by hand in some shell script anyway), to me there is hardly a point in using home-manager in the first place.

---

¹): On a related note, it took me hours to figure out how to create & populate a `~/.dotfiles` folder on the target host that is an actual writable copy and doesn't symlink to the Nix store… (Solution: Use a `home.activation` script with an appropriate shell script.)

**Comment by maresb** [comment]
I think it's just a simple docs issue. I don't have time to look into it right now, but if I remember correctly, `mkOutOfStoreSymlink` is only documented with a comment in the source code. To prevent my confusion, it probably would have been sufficient if a comment were added to clarify that the symlink is a chain via the store rather than a direct out-of-store symlink.

**Comment by zaporter** [comment]
If anyone else hits this issue, I was inspired by @amardeep 's answer and wrote a wrapper that also allows for relative imports:
Example:
```nvim
  xdg.configFile."nvim/lua" = {
    source = config.lib.my.setupSymlinkRel ./config/lua;
  };
```

This ensures that I am still free to move around my folders within my nix config and don't have to hardcode paths down into my dotfiles.

Code:

```nix
{
  config,
  pkgs,
  lib,
  ...
}:
with lib; let
  cfg = config.my; # (Note: I prefix all my vars with "my". You don't have to do this)
in {
  options = {
    my.setupPath = lib.mkOption {
      type = lib.types.path;
      apply = toString;
      default = "${config.home.homeDirectory}/YOUR-DIR-NAME";
      example = "${config.home.homeDirectory}/YOUR-DIR-NAME";
      description = "Location of the working copy";
    };
  };

  config = {
    # Extracts the relative location from the store path automatically
    # and builds a out of store symlink
    lib.my.setupSymlinkRel = relativePath: let
      # Convert basePath to string - will be something like /nix/store/hash-source/home/global/nvim
      baseStr = toString relativePath;
      # Extract the part after "-source/"
      parts = lib.splitString "-source/" baseStr;
      relPart =
        if builtins.length parts > 1
        then builtins.elemAt parts 1
        else "";
    in
      config.lib.file.mkOutOfStoreSymlink "${cfg.setupPath}/${relPart}";
  };
}
```


I don't know how fragile this is. I don't imagine home manager or nix is going to change the path format anytime soon... but worth being wary.

**Comment by Lillecarl** [comment]
@zaporter The real solution is to stop using flakes. It took me years to realize they're absolutely crap and brings nothing to the table. See [flake-compatish](https://github.com/lillecarl/flake-compatish) for something flake compatible that doesn't evaluate from store or do other outright stupid things.

default.nix (in your repo)
```nix
let
  flake-compatish = import (
    builtins.fetchTree {
      type = "github";
      owner = "lillecarl";
      repo = "flake-compatish";
      ref = "main";
    }
  );

  flake = flake-compatish ./.;
in
flake.impure
```
Then you can ```nixos-rebuild switch --file . --attr nixosConfigurations.$hostname``` and not worry about any limits flakes impose on you anymore
