### ISSUE TITLE
Direnv: `enableFlakes` as part of `enableNixDirenvIntegration`

### ISSUE THREAD

**Issue by toastal** [nix-community/home-manager#2087]
### Issue description

I use Flakes in my devShell environments. I've recently started getting issues like:

```
direnv: using flake
error: 'print-dev-env' is not a recognised command
Try '/nix/store/njkm9z03dv77my6my4s4b0kchzk166g2-nix-2.3.12/bin/nix --help' for more information.
error: 'flake' is not a recognised command
Try '/nix/store/njkm9z03dv77my6my4s4b0kchzk166g2-nix-2.3.12/bin/nix --help' for more information.
```

https://github.com/NixOS/nixpkgs/blob/fa8de42e2ade7eb3530a4170afa7cd943e11f764/pkgs/tools/misc/nix-direnv/default.nix#L7

The nixpkg config for Direnv allows a `useFlakes` to enable `nixUnstable`. It seems like `programs.direnv` should as well. Maybe I  am missing how this configuration works though.

**Comment by berbiche** [comment]
Hi,

You will need to configure flake support on your system, [see this (unofficial) wiki page about it](https://nixos.wiki/wiki/Flakes).

**Comment by toastal** [comment]
Yes, I have it both at the OS-level and added to that local config
