### ISSUE TITLE
If system hostname is X then do A else do B ?

### ISSUE THREAD

**Issue by Kreyren** [nix-community/home-manager#2088]
Is there a way to do conditionals in nix using home-manager?

I want to use one configuration directory for all my systems with them having a different set of packages and their configuration

**Comment by berbiche** [comment]
Hi @Kreyren,

First off, is this a flake configuration?
If so, you can make as many entries as you want in your `flake.nix` `outputs.homeManagerConfiguration` as you need for each system.

Otherwise, you could read the hostname using `builtins.getEnv "HOSTNAME"`, however this is impure and will not work with `--pure` evaluation.

**Comment by Kreyren** [comment]
> First off, is this a flake configuration?
If so, you can make as many entries as you want in your flake.nix outputs.homeManagerConfiguration as you need for each system. @berbiche

Can you elaborate? I would like this to be two independent configurations:
- System -> To configure the runtime and services
- User -> non-root configuration only of the user environment

**Comment by rycee** [comment]
Generally speaking I would advice against trying to use the same configuration file for multiple systems. It is more robust to create one configuration fle per system/user and them import common functionality into those files.

See [How to set up a configuration for multiple users/machines?](https://nix-community.github.io/home-manager/index.html#_how_to_set_up_a_configuration_for_multiple_users_machines) for a bit more.

**Comment by kalbasit** [comment]
Checkout https://github.com/kalbasit/soxincfg and which uses https://github.com/SoxinOS/soxin for an example on how to do this.

As @rycee said, it's bot recommended to use one file in the way that you describe. Instead, your flake should declare its own modules (say one for i3, another for vim, etc...) and each host would enable what it needs.

In soxin, I do that primarily using profiles, say my laptop is a workstation with work active on it, another only personal and a server with no GUIs whatsoever. 

Hope that helps.

**Comment by berbiche** [comment]
Closing this. Feel free to reopen if you still need help.
