### ISSUE TITLE
Foot "error: no configuration found, using defaults"

### ISSUE THREAD

**Issue by RosarioPulella** [nix-community/home-manager#2090]
### Issue description

Foot shows an error message if it can't find a configuration file. Maybe we should create `xdg.configFile."foot/foot.ini"` even if `programs.foot.settings` is an empty attribute set.

![screenshot](https://user-images.githubusercontent.com/7164552/121385071-cc5c5a00-c916-11eb-884c-f8da034c2948.png)

#### Maintainer CC

@plabadens

**Comment by berbiche** [comment]
Hi,

PR welcome :)

https://github.com/nix-community/home-manager/blob/42847469b3f65a363dc52b66be09d0ac4edcc55c/modules/programs/foot.nix#L54-L56

We would only need to drop the `mkIf` part.

**Comment by RosarioPulella** [comment]
I got something already. Changed the tests. Submitting soon.

**Comment by plabadens** [comment]
> I got something already. Changed the tests. Submitting soon.

Ah, yes. That would be appreciated, there are some edge cases that I didn't account for. This would also be a candidate for a simple test, maybe?
