### ISSUE TITLE
rsibreak missing its icon/graphics on notification bar

### ISSUE THREAD

**Issue by league** [nix-community/home-manager#2092]
### Issue description

This is extremely minor. I'm using KDE Plasma desktop, and have set `services.rsibreak.enable = true`. It starts up properly, but a gap appears in the notification bar where its icon/indicator should be. When I hover over it, the rsibreak tooltip appears, and I can right-click it to access the menu.

The icon appears properly when rsibreak is installed either in `home.packages` or `environment.systemPackages`. So that's a simple workaround. But I'm wondering if the issue occurs for anyone else, or if there's some way that rsibreak should be wrapped or if there's an environment variable that would help it find its graphics without being installed as such. If it's a problem that others have had to work around too, maybe we should just add the `home.packages` setting to the module itself?

#### Maintainer CC

@c0deaddict 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.20210608.f2c9d56 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `""`
 - channels(league): `""`
 - nixpkgs: `/nix/store/76w1zdmpcnwyp270qi182zcs0yqpcyb7-source`

**Comment by berbiche** [comment]
Hi @league,

I think HM symlinks all icons in one big folder in the store that is exposed through environment variables.
When a package is not added to `home.packages`, its icon is never added to the folder.

Would you like to submit a PR adding the package to `home.packages`?
