### ISSUE TITLE
dconf.settings: issues with JSON-like values

### ISSUE THREAD

**Issue by lbssousa** [nix-community/home-manager#2096]
### Issue description
I'm debugging some dconf2nix issues related to JSON-like entries (https://github.com/gvolpe/dconf2nix/issues/37 and https://github.com/gvolpe/dconf2nix/issues/39). For example, a dconf entry like this:
```
[org/gnome/shell/extensions/sound-output-device-chooser]
ports-settings='{"version":2,"ports":[]}'
```
is currently translated to this:
```
# Generated via dconf2nix: https://github.com/gvolpe/dconf2nix
{ lib, ... }:

let
  mkTuple = lib.hm.gvariant.mkTuple;
in
{
  dconf.settings = {
    "org/gnome/shell/extensions/sound-output-device-chooser" = {
      ports-settings = ''
        {"version":2,"ports":[]}
      '';
    };
  };
}
```

However, when I import this configuration to my home.nix and run `home-manager switch`, it ends up with the following error message:
```
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating dconfSettings
error: Key file contains line “'” which is not a key-value pair, group, or comment
```

A possible workaround to avoid this error is removing the line breaks within the quotes, like this:
```
ports-settings = ''{"version":2,"ports":[]}'';
```
but I think this should not be needed.

#### Maintainer CC
@rycee @gvolpe

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.11.20210606.fbfb794 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
Hi,

The issue seems to be that multiline strings written in that fashion have a leading newline.

I don't use the dconf module/configuration so I don't know whether HM could always strip the first newline of a string.

It could break some wild configuration out there I suppose.

**Comment by lbssousa** [comment]
> The issue seems to be that multiline strings written in that fashion have a leading newline.
You mean a trailing newline, right? I can confirm, by simulating in `nix repl` that something like
```
# Generated via dconf2nix: https://github.com/gvolpe/dconf2nix
{ lib, ... }:

let
  mkTuple = lib.hm.gvariant.mkTuple;
in
{
  dconf.settings = {
    "org/gnome/shell/extensions/sound-output-device-chooser" = {
      ports-settings = ''
        {"version":2,"ports":[]}
      '';
    };
  };
}
```
may lead to the following dconf setting:
```
[org/gnome/shell/extensions/sound-output-device-chooser]
ports-settings='{"version":2,"ports":[]}
'
```

The question is: whose is the responsability from removing this trailing newline: from HM itself (may it break other HM settings), from HM dconf module (can it be done for this module only) or from dconf2nix?

**Comment by gvolpe** [comment]
It would be great if this could be supported directly in the `dconf` module of HM. A multiline string is ideal for long JSON data. Otherwise, a single-liner JSON could be really long, and potentially unreadable.

**Comment by sumnerevans** [comment]
One option is to apply the `builtins.toJSON` function to a Nix attrset and assigning the resulting string to `ports-settings`.

**Comment by rycee** [comment]
I didn't do the assert, instead literal newlines will now be escaped in the INI file. With any luck that will resolve this issue.
