### ISSUE TITLE
mpv allow for options without values

### ISSUE THREAD

**Issue by ZerataX** [nix-community/home-manager#2098]
### Issue description

mpv has a few options like `no-pause` that don't take a parameter.
If I create a config with for example:
```nix
{
  programs.mpv = {
    enable = true;
    config = { no-pause = true; };
  };
}
```
I get this error
```
~/.config/mpv/mpv.conf:128: setting option no-pause='yes' failed.
Error parsing option pause (option doesn't take a parameter)
```

Maybe I am missing something, but I don't see how I would configure this.

#### Maintainer CC
@tadeokondrak @thiagokokada

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.42, NixOS, 21.05.906.cedcf2565c6 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.906.cedcf2565c6, nixos-hardware, nixos-unstable-21.11pre294109.fbfb79400a0"`
 - channels(kaine): `"home-manager-21.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lunik1** [comment]
You should be able to use the empty string, e.g.

```nix
{
  programs.mpv = {
    enable = true;
    config = { no-pause = ""; };
  };
}
```

**Comment by ZerataX** [comment]
yes that does work, thank you!
it would maybe be neat to add this to the example, since it doesn't seem that obvious to me, but maybe that's just me.

**Comment by sumnerevans** [comment]
> it would maybe be neat to add this to the example, since it doesn't seem that obvious to me, but maybe that's just me.

Feel free to send a patch updating the example.
