### ISSUE TITLE
programs.zsh.enable = true; doesn't install all required files

### ISSUE THREAD

**Issue by flexagoon** [nix-community/home-manager#2101]
### Issue description

If I put `programs.zsh.enable = true;` in my NixOS system config it installs a bunch of stuff like the default theme and command_not_found_handler. home-manager doesn't do that

#### Maintainer CC

@bb010g @rycee @oxalica @pinpox @NickHu 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.42, NixOS, 21.11pre294801.432fc2d9a67 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre294801.432fc2d9a67"`
 - channels(flexagoon): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
Hi @flexagoon,

I don't know the difference between the Home Manager module and the NixOS one, but HM does not ship with the same features.
The features you expect are most likely available behind a `programs.<something>.enable = true` and `programs.<something>.enableZshIntegration = true`.

Can you define exactly what you are expecting to have available?

**Comment by flexagoon** [comment]
Oh, sorry, I already figured it out myself

**Comment by pinpox** [comment]
@flexagoon what settings did you end up using for the `command_not_found` handler?

**Comment by flexagoon** [comment]
@pinpox I just used `programs.zsh.enable` in my system config. I had an issue with one plugin after that, but I fixed it by overriding keybinds set by the default config.
