### ISSUE TITLE
Can't build home-manager: /nixos/modules/installer/tools/nixos-option' is forbidden in restricted mode

### ISSUE THREAD

**Issue by ratsclub** [nix-community/home-manager#2111]
### Issue description

When building a HM configuration through flakes with the command `nix build .#homeConfigurations.home.activationPackage` I'm getting the following error:

```
error: access to path '/nix/store/mn2xjw5xb0v7n2bnhl8w4nbxpqv82zsg-p5d2qhw8hw4ishxpwznx2lm48jgwqb3d-source/nixos/modules/installer/tools/nixos-option' is forbidden in restricted mode
```

I was using the commit 63af2d3e4cac0a84a87b72be0135f5bcec5a9d5d and rolling back to e92f5bb79e8c72b6afd64d3b6e4614669fcc1518 fixed it.

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.11.20210613.fa0326c (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.11pre295280.fa0326ce523"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
cc @bb010g

**Comment by fufexan** [comment]
I have the same issue. I've tested multiple combinations of `nixpkgs-unstable` and `home-manager` and have come to the conclusion that [the latest commit](https://github.com/nix-community/home-manager/commit/63af2d3e4cac0a84a87b72be0135f5bcec5a9d5d) is at fault. Specifically [this line](https://github.com/nix-community/home-manager/commit/63af2d3e4cac0a84a87b72be0135f5bcec5a9d5d#diff-aac03a529e226886e5cc231d5655c1eb7c5b412d1411469d8b2d09976e0dd8f1R15):
```nix
  callPackage "${pkgs.path}/nixos/modules/installer/tools/nixos-option" { };
```
I don't know anything about it, but it may help you guys pinpoint the problem. Cheers.

**Comment by berbiche** [comment]
The fix is simple:

`callPackage (pkgs.path + "/nixos/modules/installer/tools/nixos-option") { }`.

How to test:

``` terminal
$ nix shell --argstr system "$(nix eval --impure --raw --expr builtins.currentSystem)" --expr '
{ system }:
let
  a = builtins.getFlake "github:nixos/nixpkgs/6aa2bb6a818d12d4cf296f736263011611cf2610";
  pkgs = import a { inherit system; };
in
pkgs.callPackage (pkgs.path + "/nixos/modules/installer/tools/nixos-option") {}
'

$ man nixos-option
Works!!
```

If the `callPackage` in the expression above is changed to `callPackage "${pkgs.path}/....."` evaluation will fail :)

**Comment by berbiche** [comment]
To comment on the fix, I think `callPackage` is not allowed to import strings in pure evaluation or whatever restricted mode flakes are using.
