### ISSUE TITLE
[Duscussion] Wrap program with config in store instead of creating symlinks?

### ISSUE THREAD

**Issue by oxalica** [nix-community/home-manager#2129]
`home-manager` supports custom config for many programs. But usually they are implemented by creating symlinks in the location where programs expect them to be, pointing to the generated config in store.

There is another way to achieve it, which is what `vim_configurable.customize` does. It instead wraps `vim` to directly use the generated vimrc in store, completely getting rid of `~/.vimrc`. Many programs support passing the path of config file through arguments or environment variables, like `alacritty`'s `--config-file` and `tmux`'s `-f`.

I personally prefer the second solution since it minimize the impure work (managing symlinks during activation), and also kind of "normalizing" config paths of programs which don't respect XDG spec.

**Comment by berbiche** [comment]
See https://github.com/nix-community/home-manager/issues/2107
