### ISSUE TITLE
Polybar & i3 support

### ISSUE THREAD

**Issue by bruce** [nix-community/home-manager#213]
(First of all, thanks for home-manager; it is fantastic!)

I'm encountering a problem running polybar's i3 integration when polybar is run as a service.

For some reason, running polybar using systemd (home-manager's service configuration) doesn't show the i3 module, but running the polybar `script` manually in a terminal does. Restarting the service with `systemctl --user restart polybar.service` doesn't help either.

Here's what I think are the pertinent pieces of my `home.nix` (note `polybar` is using `i3Support = true`):

```

  home.packages = [
    pkgs.i3
    # other packages...
  ];

  xsession = {
    enable = true;
    windowManager.command = "i3";
  };

  services.polybar = {
    enable = true;
    package = pkgs.polybar.override {
      i3Support = true;
      alsaSupport = true;
      iwSupport = true;
      githubSupport = true;
    };
    config = {
      "bar/top" = {
        monitor = "eDP1";
        width = "100%";
        height = "3%";
        radius = 0;
        # Just sticking them together in the center for now
        modules-center = "date i3";
      };
      "module/date" = {
        type = "internal/date";
        internal = 5;
        date = "%Y-%m-%d";
        time = "%H:%M";
        label = "%date% %time%";
      };
      "module/i3" = {
        type = "internal/i3";
        scroll-up = "i3wm-wsnext";
        scroll-down = "i3wm-wsprev";
      };
    };
    script = ''
    polybar top &
    '';
  };
```

Stopping the service and running the following from a terminal, the i3 module shows up in polybar just fine:

```sh
$ polybar top &
```

Any ideas in what I might be missing?

**Comment by bruce** [comment]
@nico202 Oops, thanks. I'll close this issue and watch that one. 🍻

**Comment by nico202** [comment]
The fix proposed (prepand PATH like `script = ''PATH=$PATH:${pkgs.i3}/bin polybar bar &'';` is almost working, I just needed to restart the polybar service with i3 with:

>	      { command = "systemctl --user restart polybar"; always = true; notification = false; }

 else it would polybar i3 module stops working every time you restart i3

**Comment by bruce** [comment]
Actually now I'm not sure this is the same issue. I wasn't seeing the communication error in the other issue (maybe it just wasn't getting there), it was just silently not showing the i3 module.

On startup, only my date module is displayed. If I look at the service status, it looks like it started fine:

```
$ systemctl --user status polybar.service
● polybar.service - Polybar status bar
   Loaded: loaded (/nix/store/kigglmlliv443kh0wad8zi1yjksilmg6-polybar.service/polybar.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-02-16 16:50:44 PST; 27s ago
  Process: 1047 ExecStart=/nix/store/g8cr75xl3js252ccjmy1g1x672j9bkz9-polybar-start/bin/polybar-start (code=exited, status=0/SUCCESS)
 Main PID: 1048 (polybar)
   CGroup: /user.slice/user-1000.slice/user@1000.service/polybar.service
           └─1048 polybar top

Feb 16 16:50:44 morrigan systemd[986]: Starting Polybar status bar...
Feb 16 16:50:44 morrigan systemd[986]: Started Polybar status bar.
```

If I look at the script it's running, I can see it's using the workaround mentioned in the other issue (which I think is, again, a workaround for a different problem):

```
$ cat /nix/store/g8cr75xl3js252ccjmy1g1x672j9bkz9-polybar-start/bin/polybar-start 
#!/nix/store/jgw8hxx7wzkyhb2dr9hwsd9h2caaasdc-bash-4.4-p12/bin/bash

PATH=$PATH:/nix/store/yfnjlbf6nfan2iw99jr0cp669qmh6l7d-i3-4.14.1/bin polybar top &
```

If I stop the service and run the script manually, polybar starts up with the i3 module visible and working:

```
$ systemctl --user stop polybar.service
$ /nix/store/g8cr75xl3js252ccjmy1g1x672j9bkz9-polybar-start/bin/polybar-start 
```

**Comment by bruce** [comment]
The only thing I can think of that might be related (just because it's related to systemd) is the warning I get running `home-manager switch` under `Activating reloadSystemD`:

```
$ home-manager switch
Starting home manager activation
Activating checkPolybar
Activating checkLinkTargets
Activating writeBoundary
Activating linkGeneration
Cleaning up orphan links from /home/bruce
No change so reusing latest profile generation 65
Creating home file links in /home/bruce
Activating reloadSystemD
User bruce not logged in. Skipping.
Activating applyPolybar
Activating uninstallHomeManager
Activating installPackages
replacing old ‘home-manager-path’
installing ‘home-manager-path’

There are 6 unread and relevant news items.
Read them by running the command 'home-manager news'.
```

Seeing `User bruce not logged in. Skipping.` is odd, considering:

```
$ whoami
bruce
```

**Comment by uvNikita** [comment]
Everything seems to be correct except the warning about not logged in user. I'm not sure what can cause this, but maybe @rycee has some insight on it.

As for polybar, what messages do you see (e.g. by running `journalctl --user -f`) when you are trying to restart polybar service?

**Comment by rycee** [comment]
The `User bruce not logged in. Skipping` message is new from when the nixos module branch got merged. It is printed by this code:

https://github.com/rycee/home-manager/blob/f2265b10e4eb48c66d334fa1d90bebb4affbec69/modules/systemd.nix#L164-L170

Basically, the message must mean that the `who | grep -q '^bruce '`call must have failed, which strikes me as odd. I've never run into a situation where `who` does not print a logged in user. Maybe there is a better way to tell if a user is having an active login? Maybe `loginctl` is the correct command to use for this purpose?

**Comment by bruce** [comment]
@rycee That may be a better option:

```sh
$ nixos-version
17.09.2853.b222a0713f4 (Hummingbird)

$ who

$ loginctl list-users
       UID USER            
      1000 bruce           

1 users listed.
```

FWIW, it seems like with the PATH workaround, this issue is only showing up on startup; after I restart the service it seems to be working now (?). I'm not sure why.

**Comment by teto** [comment]
I also noticed `User teto not logged in. Skipping.`. It's not in any specific "warning" color so I might have skipped it previously. `who` also returns nothing.

**Comment by rycee** [comment]
I've added #215 that tries to solve this in a third way by asking the user systemd daemon directly whether it is running. The previous check whether the user is logged in was more of a guess that if the user is logged in then systemd is probably running.

In my testing this seems to work well but maybe somebody can think of some issue with this approach?

**Comment by rycee** [comment]
That said (now that I've actually read through this thread) I'm not certain the change in #215 is related to the issue at hand.

The `User bruce not logged in. Skipping.` message would mainly mean that `systemctl --user daemon-reload` isn't executed by the activation script and new/changed service files may therefore not be discovered. On the next login it should be all good, though.

@bruce If you first run `systemctl --user daemon-reload` and then `systemctl --user restart polybar.service`, does it work better?

**Comment by bruce** [comment]
@rycee It seems to work fine after `systemctl --user restart polybar.service` anyway now (as I noted in my last comment, the failure of the i3 module to work only seems to happen immediately after login).

**Comment by uvNikita** [comment]
@bruce Do you have `startup = { command = "systemctl --user restart polybar"; always = true; notification = false; }
` in your i3 configuration as @nico202 mentioned? See https://github.com/rycee/home-manager/issues/195 issue for the explanation why it is still required.

**Comment by bruce** [comment]
@uvNikita I don't, and I noticed the same issue when my laptop wakes up as well, so that seems like the likely culprit. I'll try that today and report back.

**Comment by myme** [comment]
I'm having this issue as well, and I know the probable cause. Hint is in @nico202's comment:

> The fix proposed (prepand PATH like `script = ''PATH=$PATH:${pkgs.i3}/bin polybar bar &'';` is almost working, I just needed to restart the polybar service with i3 with:
>
> ```nix
>  { command = "systemctl --user restart polybar"; always = true; notification = false; }
> ```
>
> else it would polybar i3 module stops working every time you restart i3

The `i3` module in `polybar` needs to connect to the `i3` socket, and it does so by invoking `i3 --get-socketpath`. This doesn't work of course if `i3` is not running at the time. I'm currently running `i3` as [the window manager](https://wiki.archlinux.org/index.php/KDE#Use_a_different_window_manager) in a `KDE` session. KDE spawn off `i3` fairly late while initializing the graphcial session. However, looking at the default `~/.xsession` I think this would apply there as well:

```sh
if [ -z "$HM_XPROFILE_SOURCED" ]; then
  . ~/.xprofile
fi
unset HM_XPROFILE_SOURCED

systemctl --user start hm-graphical-session.target

/nix/store/0za5mlg7xklkl2pnhrn682lhr92pw9gs-i3-gaps-4.17/bin/i3

systemctl --user stop graphical-session.target
systemctl --user stop graphical-session-pre.target

# Wait until the units actually stop.
while [ -n "$(systemctl --user --no-legend --state=deactivating list-units)" ]; do
  sleep 0.5
done
```

Now one hack is of course to restart the polybar service whenever `i3` (re)starts, like the quoted comment. But here might be better ways to solve this timing interdependency?

**Comment by justin-gerhardt** [comment]
Adding `systemd.user.services.polybar.Unit.After = [ "graphical-session.target" ];` seems to be forcing polybar to start after i3.

It does mean the service file includes 
```
[Install]
WantedBy=graphical-session.target

[Unit]
After=graphical-session-pre.target graphical-session.target
PartOf=graphical-session.target
```
which looks concerning like a dependency cycle but I'm not quite sure of the finer points of systemd and it is working.

**Comment by arcnmx** [comment]
I [use this to fix it](https://github.com/arcnmx/nixexprs/blob/07e50ffc9f077359db8704a892f6ca2631d439bf/modules/home/i3.nix#L20), it might be worth me turning it into a PR?
