### ISSUE TITLE
allow disabling the `.cache/.keep` symlink

### ISSUE THREAD

**Issue by zseri** [nix-community/home-manager#2132]
### Issue description

I want to create a symlink from `.cache` to another directory on another device to avoid excessive writes to an SSD. it works fine almost with the following config:
```nix
{ config, pkgs, ... }: {
  xdg = {
    enable = true;
    cacheHome = "/mnt/cache/rest/zseri/.cache";
  };

  home.file = {
    ".cache".source = config.lib.file.mkOutOfStoreSymlink "/mnt/cache/rest/zseri/.cache";
  } // { ... }; # more entries follow
}
```

But this has the consequence that `$HOME/mnt/cache/rest/zseri/.cache/.keep` is created, which also shouldn't happen.
I just want to avoid creation of any such `.cache/.keep` at all.
If I remove the change of `xdg.cacheHome`, it tries to create `.cache/.keep` at the symlink destination, which is catched because it modifies files outside of the home directory.

#### Maintainer CC

No one is mentioned in `modules/misc/xdg.nix`
@rycee

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.44, NixOS, 21.11.20210619.96b4d11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210621_610baf3`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`

**Comment by berbiche** [comment]
Hi,

Can you try `home.files.".cache/.keep".source = lib.mkForce null`?

**Comment by zseri** [comment]
```
error: A definition for option `home-manager.users.zseri.home.file./mnt/cache/rest/zseri/.cache/.keep.source' is not of type `path'. Definition values:
       - In `<unknown-file>': null
```

**Comment by berbiche** [comment]
> ```
> error: A definition for option `home-manager.users.zseri.home.file./mnt/cache/rest/zseri/.cache/.keep.source' is not of type `path'. Definition values:
>        - In `<unknown-file>': null
> ```

Hum, can you try `homes.files.".cache/.keep" = lib.mkForce { }`;?

**Comment by zseri** [comment]
```
error: The option `home-manager.users.zseri.home.file./mnt/cache/rest/zseri/.cache/.keep.source' is used but not defined.
```

**Comment by berbiche** [comment]
@rycee do you have any idea how this can be done besides adding an option to disable the default behavior?

**Comment by zseri** [comment]
> ```
> error: A definition for option `home-manager.users.zseri.home.file./mnt/cache/rest/zseri/.cache/.keep.source' is not of type `path'. Definition values:
>        - In `<unknown-file>': null
> ```

isn't this aspect rather easily fixable by broadening the allowed types the type?

**Comment by rycee** [comment]
@zseri Sorry about the delay. Using symlinks for this purpose seems inappropriate, have you considered using overlayfs?

**Comment by zseri** [comment]
overlayfs for this purpose seems inappropriate because I want to write to all layers transparently, and afaik overlayfs doesn't allow a per-directory split. (I do not want to merge two `.cache` folder, I only want to basically "move it"... Maybe I'll try returning to bind mounts...)
