### ISSUE TITLE
Make installing gnome-terminal optional when enabled

### ISSUE THREAD

**Issue by Scoder12** [nix-community/home-manager#2143]
### Issue description

When using home-manager on non-nixos, it is redundant to install the `gnome-terminal` package when `programs.gnome-terminal` is enabled, because it is already installed through the OS. Installing it also pulls in a lot of gnome related dependencies which wastes install time / disk space. 

#### Maintainer CC

@rycee @kamadorueda 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-7614-generic, Pop!_OS, 20.10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.13`
 - channels(scoder12): `"home-manager"`
 - channels(root): `"nixpkgs-21.11pre297712.c6a049a3d32"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by berbiche** [comment]
An alternative would be to use an overlay in your `configuration.nix` or `home.nix` and to make the package call whatever `gnome-terminal` program is available in your `$PATH`;

``` nix
{
  nixpkgs.overlays = [ (self: super: {
    gnome.gnome-terminal = super.writeShellScript "dummy-gnome-terminal" "exec /usr/bin/env gnome-terminal";
  })];
}
```

**Comment by rycee** [comment]
Yes, an overlay is the best solution. I wouldn't like to open the flood gates for this type of impure option, once one package has a "skip package install" option people will be asking it for all modules. I'm OK with it being a bit painful to avoid getting the package from Nixpkgs 🙂

**Comment by Scoder12** [comment]
Thanks for the tip. I managed to get it to work with a few tweaks:
```nix
{
 nixpkgs.overlays = [ 
   (self: super: { 
     gnome = super.gnome // { 
       gnome-terminal = super.writeShellScriptBin "dummy-gnome-terminal" 
         "exec /usr/bin/env gnome-terminal"; 
     }; 
   }) 
 ]; 
}
 ```
