### ISSUE TITLE
E739: Cannot create directory:

### ISSUE THREAD

**Issue by f1rssov** [nix-community/home-manager#2148]
[coc.nvim] creating data directory: /Users/f1rssov/.config/coc
Error detected while processing /Users/f1rssov/.vim/plugged/coc.nvim/plugin/coc.vim[50]..function coc#rpc#start_server[13]..coc#util#get_data_home:
line   16:
E739: Cannot create directory: /Users/f1rssov/.config/coc
Press ENTER or type command to continue[coc.nvim]: internal/fs/utils.js:314

Help me plz

**Comment by berbiche** [comment]
Hi, how is this error related to Home Manager?

Can you provide the full context of your installation per the default issue template i.e. your nix-channels and system os?

**Comment by f1rssov** [comment]
> Hi, how is this error related to Home Manager?
> 
> Can you provide the full context of your installation per the default issue template i.e. your nix-channels and system os?

Hi, I solved this problem, but when I open .cpp file this issue appear 
<img width="567" alt="Снимок экрана 2021-06-29 в 22 18 34" src="https://user-images.githubusercontent.com/86555365/123854907-f27a8600-d927-11eb-9fc3-5d5f7cb53a5d.png">

**Comment by sumnerevans** [comment]
Still looks unrelated to home-manager. Closing unless you can provide more details of why this is related to home-manager.
