### ISSUE TITLE
clangd was not found on your PATH. :CocCommand clangd.install will in stall 12.0.0.

### ISSUE THREAD

**Issue by f1rssov** [nix-community/home-manager#2155]
I tried to install auto complete on vim. When I open .cpp file this issue appears.

<img width="573" alt="Снимок экрана 2021-07-01 в 16 53 52" src="https://user-images.githubusercontent.com/86555365/124135903-eb20bd00-da8c-11eb-84d7-4498f4cfb286.png">

**Comment by berbiche** [comment]
Hi,

Can you please open your issues on the CoC issue tracker' https://github.com/neoclide/coc.nvim ?

This isn't related to the Home Manager project as we have told you in the previous issue.
