### ISSUE TITLE
make: *** No rule to make target `main.c', needed by `hello'.  Stop.

### ISSUE THREAD

**Issue by f1rssov** [nix-community/home-manager#2156]
My main.c :
`/*
 * main.c
 */
#include <stdio.h>
int main()
{
	printf("Hello World!\n");
	return 0;
}`

My makefile: 
hello: main.c
	gcc -o hello main.c

**Comment by berbiche** [comment]
See #2148 #2155.

**Comment by f1rssov** [comment]
> See #2148 #2155.

?
