### ISSUE TITLE
vscode doesn't work with the 2.3.14 aarch64-darwin update

### ISSUE THREAD

**Issue by ryanbooker** [nix-community/home-manager#2163]
### Issue description

vscode doesn't work with the 2.3.14 aarch64-darwin update

error: attribute 'aarch64-darwin' missing, at /nix/store/z493dlsk54zqdhp6d2vrll5836xpdc1c-nixpkgs-21.11pre300283.f930ea227ce/nixpkgs/pkgs/applications/editors/vscode/vscode.nix:6:10

**Comment by berbiche** [comment]
Hi,

Can you report this on the Nixpkgs repo (<https://github.com/nixos/nixpkgs/issues>)?

I don't think HM can do anything to resolve this issue.
