### ISSUE TITLE
spotifyd doesn't seem to install

### ISSUE THREAD

**Issue by milogert** [nix-community/home-manager#2164]
### Issue description

I have the following config for `spotifyd`:

```nix
services.spotifyd = {
  enable = true;

  settings = {
    username = "my-username@my-email.com";
    password = "secret-password";
    device_name = "theseus";
  };
};
```

It's inside `home-manager.users.milo` and the things adjacent the above config (for instance `home.packages`) are getting configured properly.

After building and switching configuration there is no mention of the `spotifyd` service starting and I cannot find any mention of it inside `/etc/systemd`

I am happy to provide more information, since I am sure I am doing something wrong here, I just don't know what!

#### Maintainer CC

@jackmac92 @smaximov 

#### Technical details

- system: `"x86_64-linux"`
- host os: `Linux 5.10.45, NixOS, 21.11.20210705.3e0ce8c (Porcupine)`
- multi-user?: `yes`
- sandbox: `no`
- version: `nix-env (Nix) 2.4pre20210601_5985b8b`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by berbiche** [comment]
Hi @milogert,

Systemd has a concept of a system session and user sessions.

Services running in the system session are only defined in `/etc/systemd/` on NixOS.

Home Manager only manages user settings and services.
Therefore, Home Manager does not create any system services.

Systemd expects user services to be in `$XDG_CONFIG_HOME/systemd/user/` (usually `~/.config/systemd/user`).
This is where you'll find Home Manager services.

To inspect the state of user services you have to use the `--user` flag with `systemct` e.g. `systemctl --user status playerctld`.

**Comment by milogert** [comment]
Well, that was the problem! I just wasn't using the `--user` flag. Thanks for the help!
