### ISSUE TITLE
Recent change to nixpkgs nixos-option not reflected in home-manager

### ISSUE THREAD

**Issue by houstdav000** [nix-community/home-manager#2170]
### Issue description

In the following commit, nixos-option was made its own package:
[https://github.com/NixOS/nixpkgs/commit/8da27ef161e8bd0403c8f9ae030ef1e91cb6c475](https://github.com/NixOS/nixpkgs/commit/8da27ef161e8bd0403c8f9ae030ef1e91cb6c475)

but in [home-manager/default.nix](https://github.com/nix-community/home-manager/blob/master/home-manager/default.nix), it still is using the old path method.

Encountered on attempts to install home-manager or update flakes.

#### Maintainer CC

@rycee 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43.3-microsoft-standard-WSL2, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(david): `"home-manager, nixpkgs-21.11pre301372.8da27ef161e"`
 - nixpkgs: `/home/david/.nix-defexpr/channels/nixpkgs`

**Comment by rycee** [comment]
Should be fixed now, thanks for the report.
