### ISSUE TITLE
hm prepends HOME to zsh.dotDir value

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#219]
I want to set ` programs.zsh.zdotdir = "${config.xdg.configHome}/zsh";` but the hm module prepends $HOME for whatever reason.
`  zdotdir = "$HOME/" + cfg.dotDir;`
I don't see why we should prepend $HOME and would like to remove it but that may break some configs. Any input ? I guess I could set ` programs.zsh.zdotdir = "../../${config.xdg.configHome}/zsh";` but that doesn't feel good.

**Comment by teto** [comment]
the` "../../${config.xdg.configHome}/zsh"` trick doesn't seem to do it either: 
`Error installing file '../../home/teto/.config/zsh/.zshenv' outside $HOME`
guess that's the one
```
          # Figure out the real absolute path to the target.
          local target
          target="$(realpath -m "$out/$relTarget")"

          # Target path must be within $HOME.
          if [[ ! $target == $out* ]] ; then
            echo "Error installing file '$relTarget' outside \$HOME" >&2
            exit 1
          fi

```

**Comment by gmarmstrong** [comment]
If (and only if) `${config.xdg.configHome}` is guaranteed to be `$HOME/.config`, then you can set `programs.zsh.dotDir = ".config/zsh"`. This is because `dotDir` is relative to `~`.

**Comment by rycee** [comment]
Does https://github.com/rycee/home-manager/pull/891 improve this? It still includes the

    zdotdir = "$HOME/" + cfg.dotDir;

line so I guess it doesn't close this issue?

**Comment by fzakaria** [comment]
@rycee is there a reason why the ZSH module places the zshrc file in $HOME rather then set $ZDOTDIR to the /nix/store output?
I'm thinking of https://nixos.wiki/wiki/Wrappers_vs._Dotfiles

**Comment by rycee** [comment]
@fzakaria Sorry, no idea. I don't know anything about zsh.

**Comment by pinpox** [comment]
`$ZDOTDIR` is not being set for me at all recently. I'm using this:
```nix
  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    enableCompletion = true;
    autocd = true;
    dotDir = ".config/zsh";

    # More stuff ...
```

But running `echo $ZDOTDIR` returns nothing. The problem seems to only exist when loggin in via ssh. On the regular terminal (alacritty) it works fine. Do I have to set anything else for it to work over SSH?

Without the correct value for `$ZDOTDIR` my `.zshrc` which lies in that directory is not being sourced. Running `source .config/zsh/.zshrc` loads everything correctly, I'd just like it to pick it up automatically.
