### ISSUE TITLE
[discussion] why is the nixos-HM integration via systemd indirected

### ISSUE THREAD

**Issue by zseri** [nix-community/home-manager#2191]
### Issue description

On NixOS, with HM integrated into a flakes setup as a module, a systemd service is created which runs the home-manager activation script both at boot and when switching the config. After looking a bit into it, in particular to manually reconstruct which nixos generation corresponds to which HM generation, I grepped through the systemd units created for HM activation and discovered that they call an `-activate-` script in the nix store, which basically just contains three lines:
1. `bash -el` hashebang line
2. `echo Activating home-manager configuration for <USER>`
3. `exec /nix/store/<HASH>-home-manager-generation/activate`

I don't really understand why this indirection is there, e.g. why does the systemd script not directly invoke the `...-home-manager-generation/activate` script (esp. because the echo line is pretty redundant given that the systemd service is already named after HM + username, and it even scrolls out of the log displayed by `systemctl status`).

I would propose getting rid of this indirection (e.g. replacing the `ExecStart=` line which currently calls the script directly with the imo appropriate `ExecStart=.../-home-manager-generation/activate`), as it makes keeping track of current HM generations without activating all the present system generations unnecessarily harder, and I can't see any benefit of it (for now; maybe someone can convince me otherwise...).

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.11.20210716.92b3227 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210715_db4d4cf`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`

**Comment by IvanMalison** [comment]
Agreed, Also for me I get a non-zero exit code with the current setup, and needed this change: https://github.com/nix-community/home-manager/pull/2184 to get it to work at all.

**Comment by berbiche** [comment]
I think bash is used in order to inherit some environment variables before running the script.

The `-e` options makes the script exit whenever an error is encountered and not handled.
In other words, `return 1 || true` works but `return 1` would abort the script.

The `-l` option is to force the script to be a login shell.

My guess is that you (@zseri and @IvanMalison) are using custom activation scripts that produce an error that is not handled correctly.

**Comment by zseri** [comment]
@berbiche The guess that I'm using custom activations script(s) is afaik incorrect. The activate script also succeeds (and the systemd unit often/almost always also succeeds, when it isn't blocked (in my case sometimes) by xmonad, which likes to override the precompiled executable...). My point is that it makes it harder to keep track of HM generations. If it just requires a login shell, why doesn't the systemd unit just call "bash -l /nix/store/...-home-manager-generation/activate" itself? Or does it really require to be spawned as forked from bash? If so, why?

**Comment by rycee** [comment]
I can't recall the exact process that lead to the current implementation. As far as I can tell, the most important thing is that it runs a login shell. Whether that's done in a script or directly probably doesn't matter particularly much. If you prefer to have the script directly in the `ExecStart` then that should be fine, feel free to try it out for a while and open a PR if it work out well.

**Comment by berbiche** [comment]
> `bash -l /nix/store/...-home-manager-generation/activate"`

That seems like a good solution to the problem.

Besides the systemd service logs are not shown when nixos is activating the unit (whether it succeeds or fails).

**Comment by IvanMalison** [comment]
> I think bash is used in order to inherit some environment variables before running the script.

This is not a good solution. Relying on a login shell to populating variables to do something that is part of a setup script seems very not nix-y to me. Any dependencies that are needed in the activation script ought to be stated explicitly.
