### ISSUE TITLE
htop: some settings are ignored if "fields" is not explicitly set

### ISSUE THREAD

**Issue by Patagonicus** [nix-community/home-manager#2192]
### Issue description

Some htop settings are ignored if `fields` is not explicitly set in `programs.htop.settings`.

This was quite confusing at first. I set `color_scheme`, `header_margin`, `leftMeters` and `rightMeters` in my config, but `header_margin` was being ignored by htop while the rest of the settings were applied just fine.

Turns out, this is caused by `Settings_read` in htop's source specifically [returning if `fields` was read or not](https://github.com/htop-dev/htop/blob/e8f27ebc2616f875c00d814ab7f29d107e4998c1/Settings.c#L256). If not, a handful of settings are [set to default values](https://github.com/htop-dev/htop/blob/e8f27ebc2616f875c00d814ab7f29d107e4998c1/Settings.c#L467-L476), but others are left in whatever state they currently are. I don't know why only some settings are set in that case.

The home-manager documentation does not say that all `fields` needs to be included for certain other settings to be honored.

I'm not exactly sure what the right solution here is. It depends a bit on if this is considered a bug in htop (possible, but I assume it's not since htop is somewhat clear that the htoprc shouldn't be modified by hand). Possible solutions I see:

* Least effort: add a note to the documentation saying that `fields` should always be included if `settings` is set.
* Somewhere in between: add an assertion to make sure `settings` contains a non-empty `fields`.
* Nicer, but more effort: check if `settings` contains `fields` and if not add a default value.
* Maybe better, but unclear if possible: convince htop maintainers that this is a bug and should be fixed. Possibly send a patch.

I can try my hand at least at the first three options, but I haven't touched C in a while so I'm not sure I could write a patch for htop itself. Just let me know which option you'd like to go with.

I configure my home-manager as part of my NixOS config with lots of shared modules, but I think this should work as a minimal example:

```
{
  programs.htop = {
    enable = true;
    settings = {
      header_margin = false;
    };
  };
}
```

`htop` will still show a header margin. Adding `fields = with config.lib.htop.fields; [ PID ];` to `settings` makes `htop` respect the header margin setting.

#### Maintainer CC

Don't see `meta.maintainers` in the htop module, but @bjpbakker has touched it last.

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1510.a165aeceda9 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"home-manager-21.05, nixos-21.05.1510.a165aeceda9, nixos-unstable-21.11pre302265.c6c4a3d45ab"`
 - channels(philipp): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjpbakker** [comment]
Thanks for reporting this, and sorry about my late response.

I can reproduce this, and will push a fix for our htop configurtion (default value for fields, if unset). I'll try to address it upstream too.

**Comment by Patagonicus** [comment]
Sounds good, thanks! It's not a big problem for me, I have my workaround now (and it was broken for a long time before I even bothered to look into it :D).
