### ISSUE TITLE
neovim xdg_data_dirs performance degradation

### ISSUE THREAD

**Issue by yourfavouriteuncle** [nix-community/home-manager#2193]
In case anyone notices large regressions in neovim startup performance (neovim had a 4 second startup on my machine):

```lua
cmd([[
set runtimepath=$HOME/.config/nvim,$HOME/.local/share/nvim/site,$VIMRUNTIME
let &packpath=&runtimepath
]])
```
the XDG_DATA_DIRS of nixos are many, and they're all picked up by the `runtimepath`, which makes the startup go up tremendously

**Comment by teto** [comment]
where does the change in perf come from ? is that a 0.5 change or nixos change ? 4s is painful xD
