### ISSUE TITLE
bug: programs.neovim: regression in #2053

### ISSUE THREAD

**Issue by colinxs** [nix-community/home-manager#2208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

#2053 swapped `extraConfig` and `pluginConfig` so that `extraConfig` comes last. This breaks existing configs in ways that aren't easily fixable, for example:
```
" extraConfig
let mapleader = " "
" pluginConfig (neoterm)
nnoremap <silent> <Leader>tt  <Cmd>Ttoggle<CR>
```
Correctly binds `<Space>tt` to `Ttoggle`, while
```
" pluginConfig (neoterm)
nnoremap <silent> <Leader>tt  <Cmd>Ttoggle<CR>
" extraConfig
let mapleader = " "
```
does not.

The only way AFAIK to get the original behavior is to create a "dummy" plugin whose `pluginConfig` is the body of `extraConfig` and place that plugin at the head of `programs.neovim.plugins`. 

To make things easier, could a `programs.neovim.extraConfigFirst` be added?

### Maintainer CC

@teto 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-7620-generic, Pop!_OS, 20.10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixpkgs-21.05pre291295.efee454783c"`
 - nixpkgs: `/nix/store/hv23pdsi6n7z96pkljv25lfrfh1mnzz7-source`
```

**Comment by teto** [comment]
indeed. I still think it's best to have extraConfig at the end.
If you pass `configure = { beforePlugins = ''let mapleader = " " ''; }` it should work (not tested). I will probably have a look at the module this WE, I want to add some stuff and maybe return a readonly string of the generated config that people can leverage to write in a file they decide ( to address hybrid setups like mine with lua + vimscript).

**Comment by teto** [comment]
does https://github.com/nix-community/home-manager/pull/2213 work for you ? (read the commit message)
