### ISSUE TITLE
bug: can't link folders that are git submodules

### ISSUE THREAD

**Issue by jvanbruegge** [nix-community/home-manager#2217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am trying to link a wallpaper folder with `home.file`:
```nix
home.file.wallpapers = {
  source = ./wallpapers;
  target = ".config/sway/wallpapers";
  recursive = true;
};
```
The `wallpapers` folder is a git submodule that is checked out normally

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.51, NixOS, 21.11.20210721.1610540 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jvanbruegge** [comment]
My workaround so far is this:
```nix
  home.activation = {
    cloneWallpapers = lib.hm.dag.entryAfter ["writeBoundary"]
      ''
      $DRY_RUN_CMD [ ! -e ${config.xdg.configHome}/sway/wallpapers ] && git clone git@github.com:jvanbruegge/wallpapers.git ${config.xdg.configHome}/sway/wallpapers || true
      '';
  };
```

**Comment by rycee** [comment]
I'm afraid you will have to provide more information. I tried doing the same sort of setup with a git submodule and it worked without any issues.

**Comment by jvanbruegge** [comment]
I had to move away from a submodule for different reasons, so I will just close this for now
