### ISSUE TITLE
bug: System XKB options are reset by default

### ISSUE THREAD

**Issue by sigprof** [nix-community/home-manager#2219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After #2160 was merged (or, in my case, after it was backported to release-21.05), if `home.keyboard` is not set in the Home Manager configuration, any XKB options that are set at the OS level (e.g., `services.xserver.xkbOptions` in NixOS) are reset when logging in to the xsession managed by Home Manager. This is especially bad with options like `grp:*` or `lv3:*`, which are required for some languages.

The obvious workaround is either fully configuring the keyboard using `home.keyboard` (but it currently has some problems, e.g., #1638, therefore the OS level options are more reliable), or setting `home.keyboard = null;` explicitly — the code in `modules/xsession.nix` has `mkIf (config.home.keyboard != null)` around the `setxkbmap` service definition: https://github.com/nix-community/home-manager/blob/5f433eb164832fc507c3e1ba2a798f8c00578316/modules/xsession.nix#L102

However, was the behavior change for this case really intended? A more logical behavior if `home.keyboard` is not set at all is to leave the system configuration alone; however, the default value for that option is `{}`, not `null`, therefore the above `mkIf` check allows the `setxkbmap` command to run, but before #2160 that command just did not do anything, and now it resets XKB options.

Some other code which deals with `home.keyboard` checks for both `null` and `{}`: https://github.com/nix-community/home-manager/blob/fa483b82ab35c670de12a022d7c57237c3b31008/modules/services/xcape.nix#L68

### Maintainer CC

@rycee @ncfavier 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.20210724.973910f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - nixpkgs: `/nix/store/v39bvqmsb5qqd7xacc5van16i7lbf89i-source`
```

**Comment by ncfavier** [comment]
I don't see a reason for `home.keyboard` to be nullable. I think`{}` should disable the setxkbmap service.

**Comment by dschrempf** [comment]
I was having the same issue some time ago, and set `home.keyboard = null;` in my configuration.

See also this commit: https://github.com/nix-community/home-manager/commit/4971b9cad07dfe247f7d970b6823540f767df249

**Comment by yurrriq** [comment]
I just wanted to chime in and say that #2160 was an unpleasant surprise for me, too.
