### ISSUE TITLE
bug: misplaced volnoti `pacakge` option

### ISSUE THREAD

**Issue by mightyiam** [nix-community/home-manager#2224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

https://rycee.gitlab.io/home-manager/options.html

![Screen Shot 2021-07-28 at 14 55 48](https://user-images.githubusercontent.com/635591/127285927-69efbca8-78d4-46f0-896c-341d79b9988c.png)

https://nix-community.github.io/home-manager/options.html

### Maintainer CC

@IvanMalison ?

### System information

```markdown
Irrelevant.
```

**Comment by IvanMalison** [comment]
I'll fix this tomorrow. My bad.
