### ISSUE TITLE
meta: rycee.net Matrix server is down

### ISSUE THREAD

**Issue by sumnerevans** [nix-community/home-manager#2226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

https://federationtester.matrix.org/#rycee.net reports

![image](https://user-images.githubusercontent.com/16734772/127374066-60ba6437-fc67-45fe-922c-054b886804be.png)

### Maintainer CC

@rycee this is causing users to not be able to join #hm:rycee.net on Matrix. (We should add extra `via=` arguments to help alleviate server outages.)

### System information

```markdown
NA
```

**Comment by rycee** [comment]
Ah, right. Didn't realize Matrix worked like that for public rooms 😕 It's not possible to join the IRC bridge either?

In any case, I'll see if I can find somebody to go power cycle the computer in my apartment. It went down a few days ago for some reason. If that doesn't work then I'm afraid it'll have to wait until I get back, probably sometime in September or October. Feel free to ditch the room for another one if you want.

**Comment by rycee** [comment]
Should be up now. I'll see about moving to more reliable hosting in the next few weeks.
