### ISSUE TITLE
bug: sxhkd doesn't work

### ISSUE THREAD

**Issue by winston0410** [nix-community/home-manager#2234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am unable to start sxhkd. I have the following config for it.

```nix
    services.sxhkd = {
      enable = true;
      extraConfig = ''
        control + n
            xte "key Down"
      '';
    };
```
The keybinding is not working. I have then checked `ps aux | grep sxhkd` and `systemctl | grep sxhkd`, yet it returns nothing.

### Maintainer CC

@berbiche @rycee 

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.32 MiB unpacked):
  /nix/store/7gdji02y6rbnzv5mcxcf3mwksk785y8j-stdenv-linux
  /nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
copying path '/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/7gdji02y6rbnzv5mcxcf3mwksk785y8j-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1408.9376bf7b342 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(hugosum): `"home-manager-21.05, nixos-21.05.1408.9376bf7b342, unstable-21.11pre301044.87807e64a5e"`
 - channels(root): `"home-manager-21.05, nixos-21.05.1408.9376bf7b342, unstable-21.11pre301439.f9e81f7ad87"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jackmac92** [comment]
I have the same issue

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-7620-generic, Pop!_OS, 21.04`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(jmccown): `"home-manager, nixpkgs-21.11pre304920.dd98b100651"`
 - nixpkgs: `/home/jmccown/.nix-defexpr/channels/nixpkgs`
```

**Comment by winston0410** [comment]
@jackmac92 I think all my services, other than `sxhkd` defined by home-manager doesn't work, is that the same for you?

**Comment by jackmac92** [comment]
my home-manager services seem to work fine, actually using a cusotm xshkd systemd service as a workaround

**Comment by rycee** [comment]
Unfortunately, the sxhkd service is a bit special in that it is started from `.xsession` and will therefore not start up unless HM is managing the X session. Perhaps that is the case here?

**Comment by winston0410** [comment]
@jackmac92 Yes I think that the case. I have read through the PR of why they have decided to move `sxhkd` from systemd service to `xsession`, and you can copy and put that command in `services.xserver.displayManager.sessionCommands`, if you want to avoid `xsession`
