### ISSUE TITLE
Support fusuma

### ISSUE THREAD

**Issue by winston0410** [nix-community/home-manager#2237]
### Description

I have searched and checked that [fusuma](https://github.com/iberianpig/fusuma) is not supported by home-manager. I have tried to write a service config by myself but no luck.  I wish it can be completed and be included in home-manager.

https://discourse.nixos.org/t/how-to-start-a-daemon-properly-in-nixos/14019/13

**Comment by iosmanthus** [comment]
Can this help you? https://github.com/iosmanthus/nixos-config/blob/main/home/fusuma.nix

**Comment by rycee** [comment]
@iosmanthus Your module looks good, with a few improvements I think it could be added to HM. If you can, feel free to open a PR.

**Comment by ShamrockLee** [comment]
This module seems quite useful for laptop users, and there's an existing implementation (by @iosmanthus).

It would be great to have it in the HM configuration.

**Comment by iosmanthus** [comment]
@winston0410 @ShamrockLee FYI: https://github.com/nix-community/home-manager/pull/2726

**Comment by iosmanthus** [comment]
Should be closed by https://github.com/nix-community/home-manager/pull/2726
