### ISSUE TITLE
bug: when using `useGlobalPkgs` `nixpkgs` is not passed to home manager config.

### ISSUE THREAD

**Issue by yisraeldov** [nix-community/home-manager#2243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When using the nix darwin package setting
```nix
 home-manager.useGlobalPkgs = true; 
```

Causes `nixpackages` not to be passed to `home-manager.users.<user>`

doing something like:

```nix
  home-manager.users.yisraeldov = import ./home.nix ;
```

with the top of `home.nix`

```nix

{ config, pkgs, ... }:
with builtins;
with import <nixpkgs> { };

let
  unstable = import <nixos-unstable> { };
in {

  nixpkgs.config.allowUnfreePredicate =  pkg:
     builtins.elem (lib.getName pkg) [ "slack" "steam" ];

```

Cause an error :

```
error: The option `home-manager.users.yisraeldov.nixpkgs' does not exist. Definition values:
- In `/Users/yisraeldov/.nixpkgs/darwin-configuration.nix':
    {
      config = {
        allowUnfreePredicate = <function>;
      };
    }
(use '--show-trace' to show detailed location information)

```

### Maintainer CC

@berbiche 
@rycee 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 20.4.0, macOS 11.3.1`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.14`
 - channels(yisraeldov): `"darwin, home-manager, nixos-unstable-21.11pre304061.dd14e5d78e9, nixpkgs-21.11pre304539.0ffdd74547b"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/yisraeldov/.nix-defexpr/channels/nixpkgs`
```

**Comment by berbiche** [comment]
Hi,

If you use the `useGlobalPgks` option, then the `nixpgks` option becomes unconfigurable.

You must set `nixpgks` options outside your home.nix.

``` nix
{
  home-manager.useGlobalPkgs = true;

  nixpgks.config.allowUnfreePredicate = ...;

  home-manager.users.<user> = import ./home.nix;
}
```

**Comment by yisraeldov** [comment]
got it, this should probably be added to the documentation some where.

**Comment by rycee** [comment]
The documentation of the [`home-manager.useGlobalPkgs`](https://nix-community.github.io/home-manager/nixos-options.html#nixos-opt-home-manager.useGlobalPkgs) option already says

> This disables the Home Manager options `nixpkgs.*`.

Suggested improvements to make it more clear would be appreciated.
