### ISSUE TITLE
bug: dconf quoted string values not recognized

### ISSUE THREAD

**Issue by parthy** [nix-community/home-manager#2249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Using `dconf2nix`, I generated my settings and deployed them using home-manager. I've noticed, that a particular setting didn't stick: `/org/gnome/desktop/session/idle-delay`. After comparing `dconf dump /` before and after setting the value in the GUI, I noticed a subtle difference:

When it works, the value reads as `uint32 0`. After running `home-manager switch`, it is `'uint32 0'`:

```bash
$ dconf read /org/gnome/desktop/session/idle-delay
uint32 0
$ home-manager switch
$ dconf read /org/gnome/desktop/session/idle-delay
'uint32 0'
```

If i understand the code correctly, those quotes are added explicitly in `mkString`. But according to this experiments, that shouldn't be done for at least this value.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.1970.11c662074e2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(parthy): `"home-manager-21.05"`
 - channels(root): `"nixos-21.05.1970.11c662074e2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sumnerevans** [comment]
How is this a home-manager bug? This seems like it would be a dconf2nix bug.

**Comment by parthy** [comment]
I couldn't find a way to write a dconf section for home-manager that wouldn't result in this bug, even if created by hand instead of using dconf2nix. The issue is (from what I can see) in the implementation of mkString.

**Comment by parthy** [comment]
I looked into this a bit more and it seems that only the integer values that are expanded into `uint32 X` or `int64 Y` and therefore represented by strings cause problems. In contrast to other strings, they are not quoted in the dconf settings.

A quick hack in the dconf module makes the setting work for me (but I'm fully aware that's not a particularly nice change):

```patch
diff --git a/modules/misc/dconf.nix b/modules/misc/dconf.nix
index e8a04de..a8fe323 100644
--- a/modules/misc/dconf.nix
+++ b/modules/misc/dconf.nix
@@ -8,7 +8,7 @@ let
 
   toDconfIni = generators.toINI { mkKeyValue = mkIniKeyValue; };
 
-  mkIniKeyValue = key: value: "${key}=${toString (hm.gvariant.mkValue value)}";
+  mkIniKeyValue = key: value: "${key}=${toString ((if (builtins.isString value && (builtins.match "[u|]int[0-9]{1,2}.*" value) != null) then value else hm.gvariant.mkValue value))}";
 
 in {
   meta.maintainers = [ maintainers.gnidorah maintainers.rycee ];

```

**Comment by rycee** [comment]
If you want to write an uint32 value then the best bet is to use the `mkUint32` function, e.g.

    ….idle-delay = lib.hm.gvariant.mkUint32 0

With any luck that should make dconf interpret it correctly.

You can see the different functions in the [Option Types](https://nix-community.github.io/home-manager/index.html#sec-option-types) section in the manual.

**Comment by rycee** [comment]
I'll close this since I believe the `mkUint32` solution is the correct one.

**Comment by parthy** [comment]
Oh ok, now I get it. Thank you very much for figuring this out and reporting the issue in `dconf2nix`! It works perfectly now.

**Comment by orowith2os** [comment]
Just came across this when setting idle-delay on my own system. 

```
      # Ten minutes to screen shutoff. See Settings -> Power -> Screen Blank.
      "org/gnome/desktop/session".idle-delay = lib.hm.gvariant.mkUint32 600;
```

I think it would be useful if home-manager did this by itself, or warned if types didn't match up here.
