### ISSUE TITLE
bug: programs.bat.config doesn't support listing the same flag multiple times

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#2262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The `programs.bat.config` option is an `attrsOf str`. This means that every flag can be listed at most once (or twice, if the flag has both short and long versions). But there are flags that support multiple values, which require specifying the flag anew each time. Most of the flags that work this way don't make much sense in a config file, but the one that does is `--map-syntax`, which maps glob patterns to syntax definitions.

For example, I might want to have a config file that looks like

```bash
--map-syntax "*.jenkinsfile:Groovy"
--map-syntax ".myignore:Git Ignore"
--map-syntax "*.build:Python"
```

But I can't do this with `programs.bat.config`.

This should be solvable by making the type `attrsOf (either str (listOf str))` and then building the config file such that if the value is a list, the flag is repeated once per element. With that change I could write the above config as

```nix
{
    programs.bat.config = {
        map-syntax = [
            "*.jenkinsfile:Groovy"
            ".myignore:Git Ignore"
            "*.build:Python"
        ];
    };
}
```

### Maintainer CC

@marsam

### System information

```markdown
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.14`
 - channels(lily): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre308173.10bb0364861"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by lilyball** [comment]
Side note: It also looks like it isn't attempting to escape the values. Bat parses config lines using normal shell quoting rules (e.g. a line like `--style=pl"ain"` parses just fine). This means if I stick a quote in my value, it's going to be parsed incorrectly. This could be fixed by replacing `"${v}"` with `${lib.escapeShellArg v}`.

**Comment by rycee** [comment]
Good idea, will have a quick look.

**Comment by rycee** [comment]
Should be fixed now.
