### ISSUE TITLE
[Discussion] What's the possible impact of changing the output of lib.format.yaml?

### ISSUE THREAD

**Issue by lucasew** [nix-community/home-manager#2270]
JSON is a subset of the YAML 1.2 spec but the YAML generated by the generate function although correct is not YAMLish in appearance. What is the possible impact to this repo if merging this PR?

https://github.com/NixOS/nixpkgs/pull/133807

**Comment by sumnerevans** [comment]
I don't think that there should be any problems with that. As long as we are not using the YAML generator anywhere that we should be using the JSON formatter, it should be fine.
