### ISSUE TITLE
Link to contribution guidelines doesn't show the contribution guidelines

### ISSUE THREAD

**Issue by dominikh** [nix-community/home-manager#2273]
When filing an issue, GitHub says 

>  Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/nix-community/home-manager/blob/72f3bc6fa461a2899a06c87c137c7135e410e387/CONTRIBUTING.adoc). 

but because that file is a symlink, GitHub only shows the name of the target: 
![image](https://user-images.githubusercontent.com/39825/129487609-89da3a72-32e9-4851-a40e-97ccdffde198.png)

This makes the guidelines more difficult to discover.

**Comment by rycee** [comment]
Thanks for letting us know, I think this should be resolved now.
