### ISSUE TITLE
Setting the light/dark theme

### ISSUE THREAD

**Issue by Ericson2314** [nix-community/home-manager#2278]
### Description

The internet tells me to put

```ini
[Settings]
gtk-application-prefer-dark-theme = true
```
in `~/.config/gtk-3.0/settings.ini`

Should we have a module for this (and the Qt equivalent?)

**Comment by Ericson2314** [comment]
http://bhepple.com/doku/doku.php?id=sway:dark-mode is perhaps helpful.

**Comment by sumnerevans** [comment]
You can use
```
gtk = {
  enable = true;
  gtk3.extraConfig = {
    gtk-application-prefer-dark-theme = 1;
  };
};
```
to accomplish this, currently.

**Comment by Ericson2314** [comment]
Belated thanks!
