### ISSUE TITLE
bug: xdg.mimeApps seems to override xdg.desktopEntries

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/home-manager#2281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am trying to add the configuration for org-roam protocol according to [the manual](https://github.com/org-roam/org-roam/blob/master/doc/org-roam.org#linux):

```
 xdg = {
    enable = true;

    desktopEntries = {
      orgProtocol = {
        name = "org-protocol";
        exec = "emacsclient %u";
        icon = "emacs-icon";
        type = "Application";
        terminal = false;
        mimeType = [ "x-scheme-handler/org-protocol" ];
      };
    };

    mimeApps = {
      enable = true;
      defaultApplications = {
        "x-scheme-handler/org-protocol" = [ "org-protocol.desktop" ];
      };
    };
  };
```
After running `home-manager switch` I don't have the `~/.local/share/applications/org-protocol.desktop` but there is the same `mimeapps.list` symlink there as in `~/.config`:

```
$ ls -l ~/.local/share/applications
total 4
lrwxrwxrwx 1 alex users 102 Aug 19 15:47 mimeapps.list -> /nix/store/lwaa0lnwwqfz55yix9h5jq6n203vx30d-home-manager-files/.local/share/applications/mimeapps.list

$ ls -l ~/.config/mimeapps.list
lrwxrwxrwx 1 alex users 84 Aug 19 15:47 /home/alex/.config/mimeapps.list -> /nix/store/lwaa0lnwwqfz55yix9h5jq6n203vx30d-home-manager-files/.config/mimeapps.list
```

### Maintainer CC

@rycee @Gerschtli @pacien 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre308897.e41ba381140"`
 - channels(alex): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
I believe the desktop entries are installed in your Nix profile, so
perhaps it is at

    ~/.nix-profile/share/applications/org-protocol.desktop

?

Do you see any problem beside the desktop being missing from ~/.local?
What does

    $ xdg-mime query default x-scheme-handler/org-protocol

say?

**Comment by alexvorobiev** [comment]
There is `~/.nix-profile/share/applications/orgProtocol.desktop` so it didn't use the `name` attribute of the entry, so the behavior doesn't seem to match the comment https://github.com/nix-community/home-manager/blob/5f433eb164832fc507c3e1ba2a798f8c00578316/modules/misc/xdg-desktop-entries.nix#L14.

```
$ xdg-mime query default x-scheme-handler/org-protocol
orgProtocol.desktop
```
Again, the wrong name despite the setting in `mimeApps`. The `mimeapps.list` file is correct though (ignoring the bad second location under `~/.local/share/applications`):

```
[Added Associations]

[Default Applications]
x-scheme-handler/org-protocol=org-protocol.desktop

[Removed Associations]
```


Do `desktopEntries` and `mimeApps` conflict somehow?

**Comment by rycee** [comment]
The full comment is

>`desktopName` on makeDesktopItem is controlled by `name`. This is what we'd commonly consider the name of the application. `name` on makeDesktopItem is controlled by this module's key in the attrset. This is the file's filename excluding ".desktop".

so the file name is determined by the name of the attribute in `xdg.desktopEntries`. So if you want "org-protocol" you'd have to use

    org-protocol = {

Unfortunately, beside this I can't help much since I don't use these modules and don't really know how they work 😕

**Comment by alexvorobiev** [comment]
Changing the name of the attribute fixed the name of the desktop file but it is still probably not in the location where Firefox can find it because trying to open org-protocol:// URLs does nothing.

**Comment by akho** [comment]
Have you launched the Emacs server? (or set up `services.emacs`)

I have this in my Emacs setup, and it works perfectly:

```
    services.emacs.enable = true;

    programs.emacs = {
      enable = true;
      extraPackages = epkgs: with epkgs; [ vterm pdf-tools ];
    };

    xdg.desktopEntries.org-protocol-handler = {
      name = "Org Protocol";
      exec = "${config.programs.emacs.finalPackage}/bin/emacsclient -c %u";
      mimeType = [ "x-scheme-handler/org-protocol" ];
      icon = "emacs";
      settings.NoDisplay = "true";
    };
```

**Comment by alexvorobiev** [comment]
The culprit turned out to be the `org-protocol-handler` attribute (I used ` orgProtocol` instead).
