### ISSUE TITLE
bug: NeoVim PackerCompile command create ~/.config/nvim/plugins directory permission error

### ISSUE THREAD

**Issue by c4dr01d** [nix-community/home-manager#2282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I just switched my neovim configuration from vimscript to pure lua, when I copy my config to my home-manager configuration, after build and switching, I open nvim, run `:PackerUpdate` update package and run `:PackerCompile` to generate newest packer_compiled.lua, neovim report:
```
E5108: Error executing lua Vim:E739: Cannot create directory /home/c4droid/.config/nvim/plugin: permission denied
```

### Maintainer CC

@teto

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.13.12-arch1-1, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixpkgs-21.11pre309670.253aecf69ed"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by berbiche** [comment]
Hi,

Can you paste the permissions on the folder in the neovim config folder?

`ls -lA ~/.config/nvim`

**Comment by c4dr01d** [comment]
@berbiche 
```
lrwxrwxrwx 1 c4droid c4droid 75 Aug 21 20:26 /home/c4droid/.config/nvim -> /nix/store/hqc157prabkmsh4b6hbh5kmqsqkjihz0-home-manager-files/.config/nvim
```

**Comment by berbiche** [comment]
> @berbiche 
> ```
> lrwxrwxrwx 1 c4droid c4droid 75 Aug 21 20:26 /home/c4droid/.config/nvim -> /nix/store/hqc157prabkmsh4b6hbh5kmqsqkjihz0-home-manager-files/.config/nvim
> ```

This is weird. The folder should not be symlinked, only files contained within.

Can you post your neovim configuration?
Do you make use of `xdg.configFile` or `home.file` in your nix configuration for neovim?

**Comment by c4dr01d** [comment]
@berbiche Here is [NeoVim config](https://github.com/c4dr01d/flakes/tree/master/dotfiles/neovim) and [home.nix](https://github.com/c4dr01d/flakes/blob/master/role/awesome/home.nix)

**Comment by berbiche** [comment]
@c4dr01d 
> @berbiche Here is [NeoVim config](https://github.com/c4dr01d/flakes/tree/master/dotfiles/neovim) and [home.nix](https://github.com/c4dr01d/flakes/blob/master/role/awesome/home.nix)

Line 6 of your home.nix is the issue.
You have `xdg.configFile."nvim".source = ...`, this will make the nvim folder a symlink to the nix store and thus make it unwritable.

The solution is to tell HM to copy every file with `xdg.configFile."nvim".recursive = true`.
This will not make the top folder a symlink so you will be able to write to `~/.config/nvim`.

**Comment by c4dr01d** [comment]
@berbiche I'll try it later, thanks for your answer

**Comment by c4dr01d** [comment]
@berbiche OK, set recursive to true is worked
