### ISSUE TITLE
bug: `-b` backup option not working

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I just tried
```
❯ home-manager switch
/nix/store/v31s5ny06wr3p1bhz4524vpkxfad7d7b-home-manager-generation
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Existing file '/home/skainswo/.config/systemd/user/auto-fix-vscode-server.service' is in the way of '/nix/store/aqqb3qkgjmhggy0mrffzp7vm0lwyhbfp-home-manager-files/.config/systemd/user/auto-fix-vscode-server.service'
Please move the above files and try again or use -b <ext> to move automatically.

There are 140 unread and relevant news items.
Read them by running the command 'home-manager news'.
```
Ok, fair enough. There's conflicting files so I need to use the backup `-b` flag:
```
❯ home-manager switch -b backup
/nix/store/v31s5ny06wr3p1bhz4524vpkxfad7d7b-home-manager-generation
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Existing file '/home/skainswo/.config/systemd/user/auto-fix-vscode-server.service' is in the way of '/nix/store/aqqb3qkgjmhggy0mrffzp7vm0lwyhbfp-home-manager-files/.config/systemd/user/auto-fix-vscode-server.service'
Please move the above files and try again or use -b <ext> to move automatically.

There are 140 unread and relevant news items.
Read them by running the command 'home-manager news'.
```
What? But I did use the `-b` flag...

### Maintainer CC

@nyarly @rycee @Infinisil 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 20.09.3301.42809feaa9f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3301.42809feaa9f, nix-ld"`
 - channels(skainswo): `"home-manager-20.09, nixpkgs-unstable-21.11pre292293.84aa23742f6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sumnerevans** [comment]
I think it may need to be before the `switch`:

```shell
$ home-manager -b bak switch
```

but don't quote me on thta.

**Comment by masaeedu** [comment]
For posterity: `home-manager -b bak switch` doesn't work either.

**Comment by samuela** [comment]
Still an issue AFAIK

**Comment by nyarly** [comment]
@samuela @masaeedu Do you get this error on any attempt to use `-b`, or only those collisions? Are there other existing backups there? Have you tried `-b bak2` for instance?

**Comment by mccurdyc** [comment]
I tried installing home-manager from the following channels and this appears to still be an issue:
- `master` - `nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager`
- `20.05` - `nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz home-manager`

Let me know if there is more system info that would be helpful

---
```
% home-manager switch -b backup
...
Existing file '/home/mccurdyc/.zshrc' is in the way of '/nix/store/fh2fkzg87mmv5pkfqc6nakv3cbn179n4-home-manager-files/.zshrc'
Please move the above files and try again or use 'home-manager switch -b backup' to back up existing files automatically.
```

Also tried:

```
% home-manager switch -b bak
% home-manager switch -b bak2
% home-manager -b bak switch
```

Thanks in advance!

**Comment by nyarly** [comment]
I've been using `-b` pretty consistently since it was added and haven't seen this issue. There's clearly some greater context to this.

**Comment by busybox11** [comment]
Just ran into this issue on an Arch system, `-b hmbak` did not do anything. Running against latest unstable.

I also got the same error with `.zshrc`, which I currently have symlinked to a local copy of my dotfiles repo, manually managed via Git. 

It looks like `home-manager -b` **does not handle symlinks** of files and directories, but fails with the same message as before, which is confusing.

Removing via `rm` the symlinked `.zshrc` and replacing it with a copy via `cp` works as expected. AFAIK this is not explicitly documented (at least I couldn't find a simple source).

The CLI error does not account for symlinks, it only says the file would be clobbered. Haven't looked into HM's source yet, so I'm not sure why it fails - not sure if it would be relevant/simple to implement proper error reporting for this type of failures.
