### ISSUE TITLE
document Gnome-terminal options properly 

### ISSUE THREAD

**Issue by Lescurel** [nix-community/home-manager#2299]
### Description

The gnome-terminal options documentation is lacking explanations and good examples, and good error messages/default behaviors. 

#### Lacking of example/sensible default values: 
- the `colors.palette` option does not specify in which order the colors of the palette are, nor the number of required colors. 
- the `visibleName` could be set by default to the name of the profile attribute in the nix config
- if only one profile is created, the `default` option could be set to `true` by default.  

#### Lack of good error message:
- it is required to have at least one profile with the option `default` set to `true`. If not, the following error will be thrown : 
```
list index 0 is out of bounds, at /nix/var/nix/profiles/per-user/root/channels/home-manager/modules/programs/gnome-terminal.nix:329:19
```

I'm sure there might be more example, when browsing through the doc, the examples were quite scarce. 

I'm willing to take charge of that issue and make those improvements, I'm just documenting those surprising behaviours in an issue if anyone encounters them.

**Comment by berbiche** [comment]
Thanks, more documentation is always welcome.

As for the issue with no profile having "default" set, an assertion could be added.
I think we have a pattern for this in other modules.

**Comment by edgar-vincent** [comment]
This is still relevant.
