### ISSUE TITLE
bug: programs.fish.functions indents the first line of the body, but not the rest

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#2303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

If I use `programs.fish.functions` to define a multi-line function, the resulting function indents the very first line of the body but not the rest. This is because the body is included on an indented line as though it were a single-line string:

https://github.com/nix-community/home-manager/blob/21a2ff449620a9cb91802f9d1a9157b2ae8c6b39/modules/programs/fish.nix#L422-L424

This doesn't affect usage, but it does look odd when I view a function's definition with `type foo`. Ideally the function body would be run through `fish_indent` but that would require depending on `fish` at build-time and I'm not sure if that's a reasonable thing to do.

This could be handled by splitting the body on lines and prepending the indentation to each line.

### Maintainer CC

@ryanorendorff @cole-h

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.15`
 - channels(lily): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre308937.69789171027"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by berbiche** [comment]
Hi,

We have some modules where we output pretty strings, so it's definitely doable.
I changed it from a bug to a feature request since you are requesting a cosmetic change.

This would go well with #2417.

**Comment by cole-h** [comment]
I've seen a similar function at: https://github.com/NixOS/nixpkgs/blob/b165ce0c4efbb74246714b5c66b6bcdce8cde175/nixos/modules/services/networking/multipath.nix#L9-L13

Maybe this could be used / help with the implementation.

**Comment by lilyball** [comment]
I was considering this again, and perhaps the best solution is to take all of the fish `xdg.configFile`s that currently set `text` and instead have them set `source` to a derivation that pipes the text through `${programs.fish.package}/bin/fish_indent`. This will indent the file correctly regardless of what the input text is, meaning the inputs to these files don't have to care about their own indentation, and especially any code provided by users (e.g. `programs.fish.interactiveShellInit`) doesn't have to care about indentation.

**Comment by lilyball** [comment]
Oh no. A stale bot? And one that aggressively closes after only 7 days?! I hate this.

This is still an issue.

**Comment by lilyball** [comment]
This is still an issue and it still annoys me.

**Comment by lilyball** [comment]
This still bothers me. It shouldn't be hard to pass the function bodies through `fish_indent`, but I am not able to make a PR at this time.

**Comment by matthewess** [comment]
I am very interested in this, and have some spare time to put a PR together.

**Comment by ncfavier** [comment]
Was this fixed by https://github.com/nix-community/home-manager/pull/3455?

**Comment by lilyball** [comment]
@ncfavier It looks like yes! Thank you
