### ISSUE TITLE
bug: `programs.starship` shell init uses direct package path instead of path via profile

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#2316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The `programs.starship` module installs shell integration using `${cfg.package}/bin/starship`. Because of this, the shell hooks are installed using the absolute nix store path to starship. The result of this is when I install a new version of starship, all of the hooks continue to reference the old version. And if I update my starship config to use modules/keys that are newly added, the existing shells will log a warning and not use the new config. For example, I just updated my config to define `git_status.up_to_date` and now all of my existing shells, on first prompt after the update, print

```
[WARN] - (starship::configs::git_status): Unknown config key 'up_to_date'
```

New shells work, but the existing ones don't, and I shouldn't have to respawn all of my shells.

Instead of referencing starship by package path, this module should set up the shell config using `"${config.home.profileDirectory}/bin/starship`, which will work as the module also installs starship into `home.packages`. Doing it this way means shells will automatically pick up whatever the latest installed version of starship is, which means they'll stay in sync with the installed config.

Caveat: After doing so, uninstalling starship will cause existing shells to have their prompt break. But that should not be a surprising consequence of uninstalling the program that provides the prompt.

### Maintainer CC

@marsam

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.15`
 - channels(lily): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre312229.08ef0f28e3a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rycee** [comment]
Ah, interesting problem. Have you confirmed that changing the

    ${config.home.profileDirectory}/bin/starship

command resolves the issue?

I'm asking because I noticed that running

```console
$ /home/rycee/.nix-profile/bin/starship init bash | grep bin/starship | sed 's/^ *//'
source <("/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" init bash --print-full-init)
source /dev/stdin <<<"$("/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" init bash --print-full-init)"
```

and

```console
$ "/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" init bash --print-full-init | grep bin/starship | sed 's/^ *//'
STARSHIP_START_TIME=$("/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" time)
STARSHIP_END_TIME=$("/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" time)
PS1="$("/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" prompt --status=$STARSHIP_CMD_STATUS --jobs="$NUM_JOBS" --cmd-duration=$STARSHIP_DURATION)"
PS1="$("/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" prompt --status=$STARSHIP_CMD_STATUS --jobs="$NUM_JOBS")"
STARSHIP_START_TIME=$("/nix/store/7nj8v98xi9i6a9w5n7k7mfqalbp0rfva-starship-0.54.0/bin/starship" time)
```

seem to indicate that running the command from the profile path wouldn't avoid the reference into the Nix store.

**Comment by lilyball** [comment]
Here's what I get:

```console
$ starship init bash | grep bin/starship | sed 's/^ *//'
source <(/etc/profiles/per-user/lily/bin/starship init bash --print-full-init)
source /dev/stdin <<<"$(/etc/profiles/per-user/lily/bin/starship init bash --print-full-init)"
```

(`starship` resolves to `/etc/profiles/per-user/lily/bin/starship`, and using the absolute path behaves the same)

If I resolve the symlink and run it from the nix store path, I get the bad version:

```console
$ /nix/store/5adjlvmlhrxj2z9bdq4prw8sb9ngm91l-home-manager-path/bin/starship init bash | grep bin/starship | sed 's/^ *//'
source <(/nix/store/5adjlvmlhrxj2z9bdq4prw8sb9ngm91l-home-manager-path/bin/starship init bash --print-full-init)
source /dev/stdin <<<"$(/nix/store/5adjlvmlhrxj2z9bdq4prw8sb9ngm91l-home-manager-path/bin/starship init bash --print-full-init)"
```

From your output, I'm wondering if you have wrapper scripts in the mix somewhere? A single wrapper script is supposed to forward argv0, but if you have a wrapper script that executes a wrapper script that executes the binary, the argv0 forwarding doesn't work (last time I checked, `bash` ignores the input argv0 when a script is invoked via `exec`; I'm really not sure what's going on here, even just `exec ./foo.sh` causes `$0` to be the absolute path to the script whereas running `./foo.sh` causes `$0` to be `./foo.sh`).

**Comment by rycee** [comment]
Curious, something is making starship pick up the absolute path. There is no wrapper script or anything like that in the way:

```console
$ cd ~

$ ln -s $(nix-build '<nixpkgs>' -A nixpkgs-unstable.starship)/bin/starship starship

$ ./starship init bash | grep bin/starship | sed 's/^ *//'
source <(/nix/store/3w56zdxnyld1f29d5sbf8l7690afdw3i-starship-0.57.0/bin/starship init bash --print-full-init)
source /dev/stdin <<<"$(/nix/store/3w56zdxnyld1f29d5sbf8l7690afdw3i-starship-0.57.0/bin/starship init bash --print-full-init)"

$ file starship
starship: symbolic link to /nix/store/3w56zdxnyld1f29d5sbf8l7690afdw3i-starship-0.57.0/bin/starship

$ file /nix/store/3w56zdxnyld1f29d5sbf8l7690afdw3i-starship-0.57.0/bin/starship
/nix/store/3w56zdxnyld1f29d5sbf8l7690afdw3i-starship-0.57.0/bin/starship: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/73k2knwhv4zzizsjr1g1dqjvzkamx8bd-glibc-2.33-49/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```

In any case, since it won't hurt I'll make the module use `${config.home.profileDirectory}/bin/starship` instead.

**Comment by bestlem** [comment]
I am usinx nix 2.17 and nix-darwin (and DeterministicSystems nix installer)

The directory ~/.nix-profile has now been moved to ~/.local/state/nix/profile but the reference in config.fish still points to ~/.nix-profile 

I would also note that all the other tools loaded into fish like direnv zoxide all give the nix store path. Why is starship the only program to have this issue. If it had been left as before then the new config.fish would have worked.
