### ISSUE TITLE
bug: Mcfly enableBashIntegration erroring

### ISSUE THREAD

**Issue by benaduggan** [nix-community/home-manager#2319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

It appears the init script is failing, and I believe to have traced it to this PR #2301 which now results in this error message when run in just bash

![image](https://user-images.githubusercontent.com/5338872/132704567-1b4f1ca6-6ef7-4209-9198-30fcd61b7711.png)

Because the command init fails, the rest of my .bashrc wasn't evaluated leaving me without nix/home-manager in my path. 

To work around right now I just have `source <(mcfly init bash)` in my bash initExtra and disabled the enableBashIntegration flag for now

### Maintainer CC

@marsam

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-34-generic, Ubuntu, 20.04.3 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(bduggan): `"home-manager, kwbauson-cfg, nixpkgs-21.11pre313466.bc06c93905f"`
 - nixpkgs: `/home/bduggan/.nix-defexpr/channels/nixpkgs`
```

**Comment by benaduggan** [comment]
Actually, I may have lied. Enabling the mcfly program at all is messing up my environment 😬

![image](https://user-images.githubusercontent.com/5338872/132707320-0c1c6839-17de-4c2b-b582-2d01312b5a9d.png)

**Comment by marsam** [comment]
@benaduggan this issue should be fixed by https://github.com/NixOS/nixpkgs/pull/137577. Would you mind testing it and closing this issue if it's solved?

**Comment by benaduggan** [comment]
@marsam It worked! 🥳  Thanks so much for the quick response time 😄
