### ISSUE TITLE
wish: better document how home-manager managers dotfiles in the README

### ISSUE THREAD

**Issue by markstos** [nix-community/home-manager#2342]
The README mentions "dotfiles" in the first sentence of the README, but then not again.

Before someone installs `home-manager` it would be useful to know some details about how it manages dotfiles.

**Comment by heitorPB** [comment]
And also: can I "export" regular dotfiles from home-manager to use them in non nix linuxes?

**Comment by berbiche** [comment]
> And also: can I "export" regular dotfiles from home-manager to use them in non nix linuxes?

Not yet, it might come if someone implements it #2417

**Comment by fricklerhandwerk** [comment]
@heitorPB The question is why you would even want a non-Nix Linux. (Sure, I get it, you don't always own the host system.) In a perfect world we could have per-user Nix installations and the question of portability would be moot.
