### ISSUE TITLE
bug: direnv is enabled even if enableFishIntegration is set to false

### ISSUE THREAD

**Issue by winterqt** [nix-community/home-manager#2357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When enabling `programs.direnv` with the Fish shell, the setting `enableFishIntegration` has to be `true` (which is it by default, but I've explicitly set it to `false`) for direnv to activate.

Or... so one would think.

If I set just `programs.direnv.enable = true;`, my Fish shell picks up the hook *somehow* (it's not present in `config.fish`!) and begins to use it. I have absolutely no clue how this is possible considering functions aren't even inherited by child shells.

I reproduced this by:
1. Enabling direnv and its Fish integration
2. Disabling just the Fish integration

### Maintainer CC

@rycee

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 20.6.0, macOS 11.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(winter): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/p6cjkwimwlkd4nyfckmx884gh0vnksas-source`
```

**Comment by sumnerevans** [comment]
That's because `programs.direnv.enableFishIntegration` option is `true` by default: https://rycee.gitlab.io/home-manager/options.html#opt-programs.direnv.enableFishIntegration

**Comment by winterqt** [comment]
> That's because `programs.direnv.enableFishIntegration` option is `true` by default: https://rycee.gitlab.io/home-manager/options.html#opt-programs.direnv.enableFishIntegration

@sumnerevans I've explicitly set `programs.direnv.enableFishIntegration ` to `false`, and the sourcing of the hook is not in my `config.fish`.

**Comment by winterqt** [comment]
```
exec-fork: Fork #1, pid 9865: spawn external command '/nix/store/bnn2mcl2zp6m4gfyhpzs64rlwbcj2fvb-direnv-2.28.0/bin/direnv' from '/Users/winter/.nix-profile/share/fish/vendor_conf.d/direnv.fish'
```

Content is:
```fish
/nix/store/bnn2mcl2zp6m4gfyhpzs64rlwbcj2fvb-direnv-2.28.0/bin/direnv hook fish | source
```

This would be why. Don't think there's any way around this expect removing the `enableFishIntegration` option, since the `source` in `config.fish` is made redundant by this.

**Comment by rycee** [comment]
Agreed, if the package now makes fish automatically enable direnv then we can't do much on our end. Instead of removing the option entirely it may be good to keep it but make it read-only with a description indicating that the module always will be active for fish.

**Comment by Steven0351** [comment]
I'm finding this autosourcing of direnv in fish not happening in my configuration on macOS (x86_64-darwin) and am having to add the following manually to my interactiveShellInit:
```fish
direnv hook fish | source
```
Otherwise, direnv is not activating for me. Not a huge deal to add that to my home-manager fish config, but it makes me wonder if the behavior outlined in this issue is still the case given that @leifhelm also saw the same after the patch was merged?

**Comment by leifhelm** [comment]
Adding this to your config should solve this as outlined in #2408.
```nix
{
  environment.pathsToLink = [ "/share/fish" ];
}
```

**Comment by Steven0351** [comment]
> Adding this to your config should solve this as outlined in #2408.
> 
> ```nix
> {
>   environment.pathsToLink = [ "/share/fish" ];
> }
> ```

I think this solution assumes I'm using nix-darwin? I'm currently just using home-manager standalone
