### ISSUE TITLE
bug: The taskwarrior module breaks `task context`

### ISSUE THREAD

**Issue by thufschmitt** [nix-community/home-manager#2360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The `taskwarrior` module creates an immutable `.taskrc`. However, this (silently) breaks the `task context` command which expects to write the current context in the rc file.

For example, given a configuration containing:

```nix
{
  programs.taskwarrior = {                                                                                                                   
    enable = true;                                                                                                                           
    extraConfig = ''
      context.test.read = -test
    '';  
}
```

The context `test` will be available, but trying to apply it won’t work:

```console
$ task context test                              
Context 'test' set. Use 'task context none' to remove.
$ task context show
No context is currently applied.
```

### Maintainer CC

cc @minijackson 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.14.1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.4pre20210910_ff09acd`
 - nixpkgs: `/nix/store/hvn7lj6rafw33s1isrd57vmn9b639s8i-c8xp0yrqs7rpiq5yyxwmm7g3wn8mlxwd-source`
```

**Comment by bbigras** [comment]
Could home-manager create a writable `.taskrc` with an include pointing to the immutable config file?

**Comment by regnat** [comment]
> Could home-manager create a writable .taskrc with an include pointing to the immutable config file?

Yes it can indeed. That’s actually how I worked around the issue in my config:

```nix
{
  # Workaround https://github.com/nix-community/home-manager/issues/2360
  home.file.".taskrc".target = ".taskrc_";
  home.activation = {
    regenDotTaskRc = lib.hm.dag.entryAfter ["writeBoundary"] ''
      $DRY_RUN_CMD echo "include ~/.taskrc_" > ~/.taskrc
    '';
  };
}
```

I didn’t bother upstreaming though it because that’s quite ugly.

**Comment by bbigras** [comment]
@thufschmitt in my case it seems I needed to use `xdg.configFile."task/taskrc".target = "task/taskrc_";` but it works. Thank you very much!

**Comment by berbiche** [comment]
> @thufschmitt in my case it seems I needed to use `xdg.configFile."task/taskrc".target = "task/taskrc_";` but it works. Thank you very much!

Would anyone like to submit a PR that replaces the main file so that it sources the generated configuration?

**Comment by mainrs** [comment]
@berbiche I can do that. Just to have the right idea. The proposed solution would generate the file as `.taskrc_`. And in a hook I'd have to create the real configuration file instead.

> [...] that it sources the generated configuration?

This is what confused me. If I'd create `.taskrc` and source `.taskrc_`, it's the same problem again: `.taskrc` is not writable.

**Comment by bbigras** [comment]
With https://github.com/nix-community/home-manager/issues/2360#issuecomment-1009723929 , the file should be writable:

```
❯ ls -l
.rw-r--r-- 31 bbigras  3 fév 11:48 taskrc
lrwxrwxrwx 83 bbigras  3 fév 11:48 taskrc_ -> /nix/store/fiymjwdffjsmvwyas96gn525hwhkw1p3-home-manager-files/.config/task/taskrc_
❯ cat -p taskrc
include ~/.config/task/taskrc_
```

**Comment by mainrs** [comment]
Ah, I missed the `echo`, my bad! I'll get to it later on this day!
