### ISSUE TITLE
bug: kitty / pkill not fpound

### ISSUE THREAD

**Issue by eraserhd** [nix-community/home-manager#2366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Output from `darwin-rebuild switch`:

```
Creating profile generation 614
Creating home file links in /Users/jfelice
Activating onFilesChange
/nix/store/izia6lzw85ny6q0s13k9qr42zs6p2g48-home-manager-generation/activate: line 194: /nix/store/l30m61xqxghm9bi7vcicb7f78s2scr6a-procps-1003.1-2008/bin/pkill: No such file or directory
```

The code in `activate`:
```
if (( ${changedFiles['.config/kitty/kitty.conf']} == 1 )); then
  if [[ -v DRY_RUN || -v VERBOSE ]]; then
    echo "Running onChange hook for" '.config/kitty/kitty.conf'
  fi
  if [[ ! -v DRY_RUN ]]; then
    /nix/store/l30m61xqxghm9bi7vcicb7f78s2scr6a-procps-1003.1-2008/bin/pkill -USR1 -u $USER kitty || true

  fi
fi
```

It really doesn't exist:
```
[1] jfelice@C02CW0J5ML87 dotfiles (develop)
ᐅ ls /nix/store/l30m61xqxghm9bi7vcicb7f78s2scr6a-procps-1003.1-2008/bin/     
ps     sysctl top    watch

```

### Maintainer CC

cc @Misterio77 This was introduced by #2361 

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210922_bcd73eb`
 - channels(root): `"nixpkgs-20.09pre240394.ca3fa9c32a4"`
 - nixpkgs: `/nix/store/ppr73jij9dqckjjnp6ssgafhcsh9n99w-source`


Note: I'm using flakes and I'm on nixpkgs `master`.
```

**Comment by Misterio77** [comment]
Thanks for the report.

That's weird, it seems `${pkgs.procps}` is resolving to the `unixtools.procps` package on your machine, but not on mine. Maybe something darwin specific?

**Comment by Misterio77** [comment]
I wonder if there's any nix package that provides `pkill` on both linux and darwin... hm

**Comment by rycee** [comment]
I created a PR to make the `onChange` Linux only for now.

**Comment by rycee** [comment]
Merged now, we can figure out a way to make it work on Darwin in a separate issue. I'm reluctant to use the global `pkill`, at least not through `PATH`. My hope is to in the future make the activation script not use PATH at all.

**Comment by rycee** [comment]
Btw, a cross-platform alternative may be something like
```
${pkgs.killall} -s USR1 -u $USER kitty
```
(completely untested).
