### ISSUE TITLE
./result/sw/bin/darwin-rebuild switch --flake .#xxxx

### ISSUE THREAD

**Issue by zxfstd** [nix-community/home-manager#2377]
### Description
error: not linking environment.etc."ssl/certs/ca-certificates.crt" because /etc/ssl/certs/ca-certificates.crt already exists, skipping...
existing file has unknown content 40c8f77ca27478cea900ec65a3683800104d68b633749b4a8bb419b9c73bb684, move and activate again to apply

**Comment by berbiche** [comment]
Hi,

`environment.etc.` is not a valid Home Manager option.

As the error message clearly shows, Nix Darwin or your configuration is trying to overwrite a file that already exists.

I recommend moving the issue to the nix-darwin repo for their help or asking for help on Matrix (links are available on their respective git repo).
