### ISSUE TITLE
feature: using home-manager solely for configuration management in the home directory

### ISSUE THREAD

**Issue by poscat0x04** [nix-community/home-manager#2378]
### Description

I personally prefer using only `environment.systemPackages` to install packages. It would be nice to have an option to disable the package installation options (`home.packages`) in modules as much as possible. I tried set set `home.packages = mkForce [];` but it causes a build failure
```
rmdir: failed to remove '/nix/store/r8hlvla31xq9awcwhr1jjrc1gznfdmg7-home-manager-path/lib/fontconfig': No such file or directory
```
when building home-manager-path.

**Comment by rycee** [comment]
#2379 may help with the fontconfig issue.

Generally speaking, though, I would recommend against using `home.packages = mkForce []` since it may break modules that use `home.packages` to provide things in the user profile.

**Comment by ShamrockLee** [comment]
IMO, this would require modification on the implementation of individual modules, considering that some packages may require information such as the version from the specified package.

There may be a global options that indicates this preference, though.
