### ISSUE TITLE
bug: programs.neovim.coc.enable dosen't load CoC

### ISSUE THREAD

**Issue by izik1** [nix-community/home-manager#2386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Title, elaborating:
Attempted to enable CoC for neovim via `programs.neovim.coc.enable`, but CoC didn't seem to be loading. Turns out it _definitely_ wasn't. Nothing showed up in the sourced files, functions, commands, etc... Adding the plugin (copied almost verbatim from below) directly to my neovim plugins via `programs.neovim.plugins` _did_ load it though. https://github.com/nix-community/home-manager/blob/d9fe208f3ccd7047a29eb31fd0cd3191c4445323/modules/programs/neovim.nix#L278

Even more confusingly, the settings (`programs.neovim.coc.settings`) _were_ copied over without issue.

Aside: `programs.neovim.coc.enable` should probably enable `programs.neovim.withNodeJs`, since it's required.

Relevant part of my [dotfiles](https://gitlab.com/izik1/nixos-dotfiles/-/blob/9bd8f8d44c42860333206009cc721a651646f89f/roles/user/neovim/default.nix#L10-28)

### Maintainer CC

@teto (as the last person who touched it)

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.70, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211001_4f49615`
 - channels(root): `"nixos-21.11pre320334.82155ff501c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by izik1** [comment]
By "last person who touched it" I mean the neovim package in general. Sorry for the confusion.

**Comment by cherryblossom000** [comment]
This issue still persists.

`nix-info -m` output:
- system: `"x86_64-darwin"`
- host os: `Darwin 21.2.0, macOS 10.16` (I'm actually using macOS 12.1 and I'm not sure why `nix-info` gets it wrong)
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.5.1`
- channels(myusername): `"darwin, home-manager, nixpkgs-22.05pre340506.5c37ad87222"`
- channels(root): `"darwin, home-manager, nixpkgs-22.05pre340506.5c37ad87222"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by addict3d** [comment]
I tried to enable `neovim.coc` and am seeing:

> [coc.nvim] "node" is not executable, checkout https://nodejs.org/en/download/
