### ISSUE TITLE
Ability to set permissions

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#242]
The files generated by home-manager seem to be 777 here which is kind of annoying but also pose problems for some programs. I have an MSMTP error apparently related to its config being world readable.
I wonder how to fix it. For now I guess I will use the hacky way and link the file/copy it in activationScripts but a long term soluton would be welcome.

Related: https://github.com/rycee/home-manager/pull/59

**Comment by eraserhd** [comment]
It looks like this no longer works.

**Comment by rycee** [comment]
The "source as string trick" was intentionally broken. Instead use `mkOutOfStoreSymlink` like so
https://github.com/nix-community/home-manager/blob/4cc1b77c3fc4f4b3bc61921dda72663eea962fa3/tests/modules/files/out-of-store-symlink.nix#L11
