### ISSUE TITLE
bug: setting gtk-3 theme has no effect

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/home-manager#2424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am trying to set gtk-3 theme to solarized dark. Here is the code I added:
```
  gtk = {
    enable = true;

    gtk3.extraConfig = {
      gtk-application-prefer-dark-theme = true;
    };

    theme = {
      package = pkgs.numix-solarized-gtk-theme;
      name = "Numix Solarised";
    };
  };
```
The snippet has no effect - the theme is the default grey one, `~/.config/gtk-3.0` is empty, and at the `home-manager switch` prints this at the end:

```
Activating dconfSettings
error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

### Maintainer CC

@ncfavier 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.73, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11pre323790.5f0194220f2"`
 - channels(alex): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alexvorobiev** [comment]
@sumnerevans Thanks! That helped with the error message (there are none now) but I still see the default theme. There are files in `~/.gtk-3.0` now:
```
$ ls -l ~/.config/gtk-3.0
total 8
lrwxrwxrwx 1 alex users 86 Oct 29 13:39 gtk.css -> /nix/store/vf5p932w42ywc4kzr5ajvpibq4wwyfib-home-manager-files/.config/gtk-3.0/gtk.css
lrwxrwxrwx 1 alex users 91 Oct 29 13:39 settings.ini -> /nix/store/vf5p932w42ywc4kzr5ajvpibq4wwyfib-home-manager-files/.config/gtk-3.0/settings.ini
```
The `settings.ini` has these lines
```
[Settings]
gtk-application-prefer-dark-theme=true
gtk-theme-name=Numix Solarised
```
The `gtk.css` is empty.

**Comment by berbiche** [comment]
I don't think the gtk.css is ever generated

**Comment by alexvorobiev** [comment]
It turned out Numix documentation can't be used with the package from nixpgks. The correct theme names from the package look like this: "NumixSolarizedDarkBlue". After I changed it everything started to work as expected.
