### ISSUE TITLE
bug: the order matters in for some htop settings

### ISSUE THREAD

**Issue by ju1m** [nix-community/home-manager#2426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

`programs.htop.settings` being an attrset it sorts the options in lexicographic order, but options like `header_layout` must appear before other options like `colum_meters_0`, otherwise the layout is not setup as expected.
A workaround is to set such options (or all of them) like so:
```
xdg.configFile."htop/htoprc".text = lib.mkBefore ''
  header_layout=two_50_50
'';

```

### Maintainer CC

@bjpbakker

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.14.14, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/nix/store/207g891ryh3bjw8ayvwbq4nba2siwm2j-s324kk3cb3c3r9ll68rjg95anm7vmzm8-nixpkgs-patched`
```

**Comment by bjpbakker** [comment]
Thanks for reporting @ju1m. I have a PR pending to solve this, and will backport the fix to stable when it gets merged.
