### ISSUE TITLE
bug: zoxide: no match found

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#2429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I've added
```
  programs.zoxide = {
    enable = true;
    enableZshIntegration = true;
    enableBashIntegration = true;
  };
```
to my config.
zoxide is in PATH
```
$ zoxide -h 
zoxide v0.7.8
```
```
which z         
z () {
	__zoxide_z "$@"
}
```
just calling `z` is fine but `z toto` returns `zoxide: no match found`

### Maintainer CC

@maram

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.14.15, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/home/teto/nixpkgs`
```

**Comment by berbiche** [comment]
Hi,

If you do `zi`, this should show you an interactive prompt to select entries.

The path might not have been "indexed"/"learned" yet.

**Comment by teto** [comment]
indeed, it's just a normal warning from zoxide. I got confused thinking it couldn't find zoxide :s sorry
