### ISSUE TITLE
Question: how to manage config for something not installed via Nix

### ISSUE THREAD

**Issue by Smaug123** [nix-community/home-manager#2441]
Feel free to close this without comment if you don't have the bandwidth to answer; I'm sure I can find an answer, it's just going to take me a while on my own.

Can I easily hook into home-manager's "put everything into position" logic it does at the end? I'm on Darwin, and I have a file I want to have symlinked to from certain well-known locations on my machine. I've hacked something in with `pkgs.runCommandLocal` to put the symlinks into place, but I'm falling at the final hurdle because the Nix users don't have perms to access my `~/Library`. It would be easier if I could somehow add something to home-manager's existing logic. I see `home.activation.checkLinkTargets` is doing something that must conceptually be nearby, but I'm afraid the exact flow is escaping me at the moment.

# Appendix: background of the problem I'm trying to solve

JetBrains Rider stores its configuration in a well-known location (`~/Library/Application Support/JetBrains/Rider<version>/resharper-host/GlobalSettingsStorage.DotSettings`). I want to install Rider outside the Nix ecosystem, but have home-manager manage that settings file. I've got something that would work (https://github.com/Smaug123/nix-dotfiles/blob/7cd4c074c53d3232ad0247b26666d859ffa9a044/rider/rider.nix) except for me not being able to give sudo perms to the builder user. It's nasty and imperative, but I think it's not doing anything that home-manager doesn't already do; basically it's replacing an existing configuration file with a symlink to a dotfile in the Nix store.

**Comment by berbiche** [comment]
Hi,

An activation script such is probably the best solution considering that you want to also backup the settings.

Here's a Home Manager module to give you an idea of how to do it:

```nix
{ config, lib, ... }:

{
  home.activation.jetbrains-rider-settings = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    # The content of your bash script here.
    # You have access to $HOME and other regular environment variables
  '';
}
```

If you don't want to copy the content of the script, you can use `entryAfter ... (builtins.readFile ./path-to-my-script)` instead.

**Comment by berbiche** [comment]
It's also possible to use `home.file.`  (and also easier to use) but it will not backup your changed settings unless configured too.

**Comment by Smaug123** [comment]
Amazing - it works! Thanks very much :) 

For those who arrive from the future, a complete (if currently very hacky) solution is https://github.com/Smaug123/nix-dotfiles/compare/d483b6fa126aecaa6d095e68ee56353dcb086513..940a0f64b236344e24003ab32597654d0fe1578e .
