### ISSUE TITLE
bug: Session vars are loaded in different startup scripts in Bash and ZSH

### ISSUE THREAD

**Issue by sagikazarmark** [nix-community/home-manager#2445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I don't know if this behavior classifies as a bug, but there is certainly a discrepancy between how session is loaded between Bash and ZSH.

**History**

Looking through some history, I found that in #183 it was concluded that loading the session should be moved from `.zshenv` to somewhere else. `.zprofile` came up, but in #190 loading the `hm-session-vars.sh` file was moved to `.zshrc` instead.

I couldn't find the final argument for that decision, but [this comment](https://github.com/nix-community/home-manager/issues/183#issuecomment-359381272) states (incorrectly I believe) that `.zprofile` is sourced after `.zshrc` whereas it is sourced _before_ `.zshrc` and only in login shells.

As of today, `hm-session-vars.sh` is still sourced in [.zshrc](https://github.com/nix-community/home-manager/blob/70c5b268e10025c70823767f4fb49e240b40151d/modules/programs/zsh.nix#L495)

**What does Bash do?**
Bash has a similar concept of startup scripts:

- `.profile` (or some alternatives) are loaded in login shells
- `.bashrc` is loaded in interactive shells

As of today `hm-session-vars.sh` is sourced in [.profile](https://github.com/nix-community/home-manager/blob/70c5b268e10025c70823767f4fb49e240b40151d/modules/programs/bash.nix#L190)

As a side note, session variables passed to `programs.bash` are also added to `.profile`.

**Why is it important?**
As I hinted above, different startup scripts are loaded at different times:

- `.profile` and `.zprofile` are loaded in _login_ shells (when you login from terminal, open an ssh session, etc)
- `.bashrc` and `.zshrc` are loaded in _interactive_ shells

Putting graphical interfaces aside for a moment, there are four cases to be examined:

- interactive, login shell: they work the same way
- interactive, non-login shell: Bash will inherit env vars, ZSH will load them (essentially the same, given Bash is the child of a Bash login shell)
- non-interactive, non-login shell: Both will inherit env vars from parent
- non-interactive, login shell: Bash will load env vars, but ZSH will not

Whether loading env variables in login shells or non-login interactive shells for the first time is the correct solution is a question. Personally, I tend to lean towards loading env vars in login shells, because you should be able to set them once and then forget about them (again, putting graphical user interfaces aside for a moment)

**A word about graphical environments**
Some are capable of loading `.profile` (or alternative scripts in the HOME dir), so if someone uses Bash and a desktop environment that can load `.profile`, they are already in good place. Alternatively, they can always just source `.profile` in whatever script they use on GUI launch (`.xinitrc`, `.xprofile`, etc).

ZSH users will have to create either `.profile` or source `.zprofile`.

But I think this is also pointing towards using startup scripts that are loaded in login shells.

**Conclusion**

I can't say objectively that the current solution is wrong, only that I think using `.zprofile` would be a more correct place for session loading.

Also, currently Bash and ZSH differ in behavior: Bash loads session in `.profile` (login shells), ZSH in `.zshrc` (interactive shells).

What do you think?

### Maintainer CC

Pinging @uvNikita as he made the change referenced above

Pinging @rycee and @Infinisil as they were the other participants in the conversation referenced above

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(marksk): `"home-manager, nixpkgs-21.11pre327016.550dab224a2"`
 - nixpkgs: `/Users/marksk/.nix-defexpr/channels/nixpkgs`
```

**Comment by uvNikita** [comment]
It's been awhile since I looked into session variables in ZSH. Looking at the comment I wrote in #190, according to https://zsh.sourceforge.io/Intro/intro_3.html:

> `.zprofile` is similar to `.zlogin`, except that it is sourced before `.zshrc`

So seems like you right about the order being `.zprofile` -> `.zshrc`.

Then it follows with this:
> `.zlogin` is not the place for alias definitions, options, environment variable settings, etc.; as a general rule, it should not change the shell environment at all. Rather, it should be used to set the terminal type and run a series of external commands 

I'm not 100% sure, but I think that was the reason I moved the session loading to `.zshrc`. That said, I'm not sure how relevant this information still is.

**Comment by sagikazarmark** [comment]
Thanks for the quick answer @uvNikita !

Interesting, I can find that page in the latest documentation. Ther is this one, but it no longer mentions anything about what zlogin should be used for: https://zsh.sourceforge.io/Doc/Release/Files.html

I also found a FAQ entry that specifically says that env var exports can be in zprofile: https://zsh.sourceforge.io/FAQ/zshfaq03.html#l19

Tinally, I've done a quick research on the internet and it seems that people often use zprofile to do that.

**Comment by sagikazarmark** [comment]
One thing I forgot to mention: an obvious argument against using `.zprofile` is any changes to it only takes effect when the user logs out and logs in again.

**Comment by jian-lin** [comment]
I am in favor of `.zprofile` since many programs replying on environment variables use non-interactive shell, e.g. display managers and [this one](https://github.com/nix-community/home-manager/blob/63dccc4e60422c1db2c3929b2fd1541f36b7e664/modules/services/emacs.nix#L126) (although that's not zsh but bash).

If no one objects, I am willing to submit a PR.

**Comment by jian-lin** [comment]
PR is submittd #2708
