### ISSUE TITLE
bug: I ran updates and `syncthing` was de-activated on my machines

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#2447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Yeah, I don't know what's up, but I just applied updates and found `syncthing` on the ground on a variety of my machines.

### System information

```markdown
cole@xeep ~
❯ nix-shell -p nix-info --run "nix-info -m"    
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:25:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                         ^
```
```

**Comment by berbiche** [comment]
Is it an upstream issue? The syncthing module hasn't been touched recently.
![image](https://user-images.githubusercontent.com/20448408/140634187-bd6b4de6-2965-4a91-8920-7cc3e905f68b.png)
