### ISSUE TITLE
`-b` switch with OS flakes

### ISSUE THREAD

**Issue by johnrichardrinehart** [nix-community/home-manager#2452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm using home-manager with nix system flakes and I'm getting errors on `nixos-rebuild switch --flake`:
```bash
...
...
Nov 08 12:14:18 nixos hm-activate-ardan[247372]: Existing file '/home/ardan/.config/gtk-3.0/settings.ini' is in the way of '/nix/store/8dz44vpmij16bplzznw7sqnh660g3s17-home-manager-files/.config/gtk-3.0/settings.ini'
Nov 08 12:14:18 nixos hm-activate-ardan[247372]: Existing file '/home/ardan/.xmonad/xmonad-x86_64-linux' is in the way of '/nix/store/8dz44vpmij16bplzznw7sqnh660g3s17-home-manager-files/.xmonad/xmonad-x86_64-linux'
Nov 08 12:14:18 nixos hm-activate-ardan[247372]: Please move the above files and try again or use -b <ext> to move automatically.
...
...
```

Using the `-b` switch isn't really an option since I'm using `nixos-rebuild switch --flake` (the `home-manager` module implicitly applies my new users' configurations).

At first this only happened with one user and `xmonad`, but I added a 2nd user - so, now it happens sporadically with 0, 1, or both users (0 is the success case). I also added a GTK dependency to my system so now it breaks that, too.

What do I need to patch in the `home-manager` module so that `-b` will be used automatically by `nixos-rebuild switch --flake`?

### Maintainer CC

@peterhoeg @timokau @rycee

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `""`
 - nixpkgs: `/nix/store/k52v788y1q5jb6ksnbw0nk2b380j899i-source`
```

**Comment by olmokramer** [comment]
Looks like the [`home-manager.backupFileExtension`](https://nix-community.github.io/home-manager/nixos-options.html#nixos-opt-home-manager.backupFileExtension) option does what you're asking for.

**Comment by johnrichardrinehart** [comment]
@olmokramer You're absolutely right! Thanks!

```bash
$ git --no-pager diff HEAD
diff --git a/flake.nix b/flake.nix
index e905e9f..c5cbda1 100644
--- a/flake.nix
+++ b/flake.nix
@@ -29,6 +29,7 @@
             users.john = ./users/john.nix;
             users.ardan = ./users/ardan.nix;
             extraSpecialArgs = { photo = photoDerivation; };
+            backupFileExtension = "hm.bkp";
           };
         };

$ ls -lh ~/.xmonad/xmonad-x86_64-linux*
lrwxrwxrwx 1 john users   90 Nov 10 14:19 /home/john/.xmonad/xmonad-x86_64-linux -> /nix/store/v5hqgcdx44jfgipf0yxxvdyh7c5ky8ab-home-manager-files/.xmonad/xmonad-x86_64-linux
-rwxr-xr-x 1 john users 4.7M Nov 10 11:18 /home/john/.xmonad/xmonad-x86_64-linux.hm.bkp
```

I'm wondering if this will fail to apply in the future because a file with that path already exists, now. What do you think?

**Comment by olmokramer** [comment]
Hmm [it looks like it will still fail if the backup already exists](https://github.com/nix-community/home-manager/blob/bb72555852c0dc397ca65ba21c6317cada7e3058/modules/files.nix#L113-L132), though this is the first time I'm looking at this part of the home manager source code so I might be wrong.

Maybe instead of just failing when the backup already exists, home manager could try `backup=$targetPath.$HOME_MANAGER_BACKUP_EXT.$i` for some incrementing integer `$i`, or even `backup=$targetPath.$HOME_MANAGER_BACKUP_EXT.$(date +$date_format)` a few times until it finds a filename that does not exist. Although both solutions are obviously impure...

**Comment by johnrichardrinehart** [comment]
Yeah, that's what I was thinking, too. It'll take time to discover if we're right, since it's hard to reproduce this case. I *would* like an option that says "please overwrite files if you're having a difficult time applying the configuration".

@rycee How do you think we should handle this? It seems applications are changing (overwriting) files which need to be managed by home-manager, so home-manager systemd service can't start successfully. `-b` just delays a conflict by one system rebuild.

**Comment by kclejeune** [comment]
> Hmm [it looks like it will still fail if the backup already exists](https://github.com/nix-community/home-manager/blob/bb72555852c0dc397ca65ba21c6317cada7e3058/modules/files.nix#L113-L132), though this is the first time I'm looking at this part of the home manager source code so I might be wrong.
> 
> Maybe instead of just failing when the backup already exists, home manager could try `backup=$targetPath.$HOME_MANAGER_BACKUP_EXT.$i` for some incrementing integer `$i`, or even `backup=$targetPath.$HOME_MANAGER_BACKUP_EXT.$(date +$date_format)` a few times until it finds a filename that does not exist. Although both solutions are obviously impure... Or it could implement an extra option to force override already existing backup files.

I can't really comment on the rationale for not creating another backup file if the backup filepath already exists, but can confirm from my own usage that the current behavior _will not_ overwrite a backup file, and requires the user to remove it manually.

**Comment by johnrichardrinehart** [comment]
@kclejeune Yeah, I ran into this when I tried to apply recently. So, I can confirm what you're saying. I'd like two additional features from `home-manager` regarding this behavior:
1. Force overwrite option - potentially dangerous
2. Multiple backups, incrementing the suffix index as needed

**Comment by berbiche** [comment]
Created a feature request with your comment @johnrichardrinehart.

**Comment by johnrichardrinehart** [comment]
Thanks!
