### ISSUE TITLE
File in home-manager build (not linked)

### ISSUE THREAD

**Issue by jordanisaacs** [nix-community/home-manager#2456]
### Description

Is it possible to link a file to the home-manager build that isn't linked to the home directory? I need to store some state for a home manager module I am building so I can clean up on new generations (see: https://github.com/jordanisaacs/homeage/issues/8). However, as it is only used during the activation script I don't need it to be exposed as a home file.

**Comment by rycee** [comment]
Sure, you can add it to the `home-manager-generation` derivation using `home.extraBuilderCommands`.

See, e.g.,
https://github.com/nix-community/home-manager/blob/7ef3db3730d7bddad471372ed823c770634933a7/modules/manual.nix#L60-L65

You can in the activation script access the activating generation path using `$newGenPath` and the previous generation path using `$oldGenPath`. If there is no previous generation (e.g., during a fresh install) then the variable will be unset. You can guard using something like
```bash
if [[ ! -v oldGenPath ]]
```

**Comment by jordanisaacs** [comment]
Exactly what I was looking for thanks!
