### ISSUE TITLE
The `~/.config/nixpkgs/flake.nix` path is too generic

### ISSUE THREAD

**Issue by rycee** [nix-community/home-manager#2466]
Instead of `~/.config/nixpkgs/flake.nix` we should make `home-manager` look for a more specific path, for example, `~/.config/nixpkgs/home-flake.nix`.

Since HM is not the true owner of the `~/.config/nixpkgs` path we should be careful about the files we expect there.

**Comment by berbiche** [comment]
I don't think this is an issue since we can share the `outputs` section of the flake with whatever nixos intends to do.
