### ISSUE TITLE
bug: collision between different site-functions for zsh.

### ISSUE THREAD

**Issue by ShrykeWindgrace** [nix-community/home-manager#2478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Upon `home-manager switch`:
```console
error: collision between `/nix/store/apqgis7h9y3qf5bgmg5fxh6vgzm6fnmp-nix-zsh-completions-0.4.4/share/zsh/site-functions/_nix' and `/nix/store/8prj68amdnllrw7bnqgvllw8593809m4-nix-2.4/share/zsh/site-functions/_nix'
```

Both `zsh` and `nix` are managed via Home-Manager:
```nix
home.packages = [pkgs.nix];
programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
}
```

If I put `programs.zsh.enableCompletion = false;`, the switch goes smoothly, but the autocompletions for `nix` do not function correctly (however this could be related to other parts of my config...).

### Maintainer CC

Zsh seems to be quite actively developed by multiple people, and the `meta.maintainers` does not seem to be filled in for `zsh`.

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
<...>
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-87-generic, Ubuntu, 18.04.6 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels($USER): `"home-manager, nixgl, nixpkgs-21.11pre330734.5cb226a06c4"`
 - nixpkgs: `$HOME/.nix-defexpr/channels/nixpkgs`
```

**Comment by DAlperin** [comment]
Just installed home-manager, been tearing my hair out. I'm gonna try and run through some of the latest commits and see if I can find a version of programs.zsh that works

**Comment by antifuchs** [comment]
I believe this may be fixed in https://github.com/NixOS/nixpkgs/pull/146030 - I made that for nix-darwin, but it might fix home-manager too.

**Comment by ShrykeWindgrace** [comment]
@antifuchs Indeed, your patch fixed the problem in my setup, thanks a lot!

**Comment by berbiche** [comment]
Closing since the fix is available in all nix channels.

**Comment by EncodePanda** [comment]
I'm getting this error on nix 2.8. I've installed home-manager but I can not use zsh anymore because when I do 

```
  programs.zsh = {
    enable = true;
```

I'm getting

```
error: packages '/nix/store/5yqdvnkmkrhl36xh0qy31pymdphjimdd-nix-2.8.0/share/zsh/site-functions/_nix' and '/nix/store/2j5a0jldhnj7p6sg6rq3arpm4lkprm1h-home-manager-path/share/zsh/site-functions/_nix' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
error: builder for '/nix/store/wi1adjfrkrydk7qcx4a40lfhy53dwy65-user-environment.drv' failed with exit code 1
```

**Comment by EncodePanda** [comment]
> Closing since the fix is available in all nix channels.

@berbiche which fix?

**Comment by berbiche** [comment]
@EncodePanda the one described here: https://github.com/nix-community/home-manager/issues/2478#issuecomment-972691346

**Comment by pecigonzalo** [comment]
> I'm getting this error on nix 2.8. I've installed home-manager but I can not use zsh anymore because when I do
> 
> ```
>   programs.zsh = {
>     enable = true;
> ```
> 
> I'm getting
> 
> ```
> error: packages '/nix/store/5yqdvnkmkrhl36xh0qy31pymdphjimdd-nix-2.8.0/share/zsh/site-functions/_nix' and '/nix/store/2j5a0jldhnj7p6sg6rq3arpm4lkprm1h-home-manager-path/share/zsh/site-functions/_nix' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
> error: builder for '/nix/store/wi1adjfrkrydk7qcx4a40lfhy53dwy65-user-environment.drv' failed with exit code 1
> ```

Im on the same boat, I tried some overlays to change the prios, but its not working.
