### ISSUE TITLE
bug: Can't add custom themes to `bat`, including the example

### ISSUE THREAD

**Issue by emeinhardt** [nix-community/home-manager#2482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am using `home-manager` as a `NixOS` module. `bat` is working - and in general, so are all other elements of the `home-manager`-managed elements of the configuration are working fine, as far as I can tell. 

I am trying to add a custom theme, am having trouble getting it to work, and am trying to get the example custom theme taken from [the stock example](https://github.com/nix-community/home-manager/blob/master/modules/programs/bat.nix#L38-L43) to work.

This `bat` configuration:
```
...
home-manager.users.emeinhardt = {
  ...
  programs.bat = {
    enable = true;
    config = {
      # theme = "Monokai Extended Bright";
      theme = "dracula";
    };
    themes = {
      dracula = builtins.readFile (pkgs.fetchFromGitHub {
        owner = "dracula";
        repo = "sublime";
        rev = "26c57ec282abcaa76e57e055f38432bd827ac34e";
        sha256 = "019hfl4zbn4vm4154hh3bwk6hm7bdxbr1hdww83nabxwjn99ndhv";
      } + "/Dracula.tmTheme");
  };
 ...
};
```
gives expected (successful) console output from `sudo -i nixos-rebuild ...`, but subsequent calls to e.g. `bat ~/.ssh/config` start with
`[bat warning]: Unknown theme 'dracula', using default.
...`

`ls -la ~/.config/bat/themes` yields
```
lrwxrwxrwx 97 emeinhardt 16 Nov 21:48 dracula.tmTheme -> /nix/store/hj4lgs7zahl23ppdkvph5glsmwdia41k-home-manager-files/.config/bat/themes/dracula.tmTheme
```

`bat --list-themes` does not show anything but the default themes.

`bat cache --build` yields
```
No syntaxes were found in '/home/emeinhardt/.config/bat/syntaxes', using the default set.
Writing theme set to /home/emeinhardt/.cache/bat/themes.bin ... okay
Writing syntax set to /home/emeinhardt/.cache/bat/syntaxes.bin ... okay
Writing metadata to folder /home/emeinhardt/.cache/bat ... okay
```

I hope I'm doing something wrong, but this doesn't seem like expected behavior.

### Maintainer CC

@lugray

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.69, NixOS, 21.05.3468.92609f3d9bc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(emeinhardt): `""`
 - channels(root): `"home-manager-21.05, nixos-21.05.3468.92609f3d9bc, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
I took a look at Bat's source code and it defers loading/parsing of theme files to the `syntect` Rust library.
This library uses `WalkDir` to discover files in a given directory and AFAIK it does not follow symbolic links unless told to do so.

https://github.com/trishume/syntect/blob/ec62d80e33eeaf6ea3868fab452824789b672b49/src/highlighting/theme_set.rs#L25-L34
https://github.com/BurntSushi/walkdir#example-follow-symbolic-links

I suppose an issue could be opened in https://github.com/trishume/syntect and linked here.

**Comment by rycee** [comment]
I don't believe the themes end up symlinked directories, just direct symlinks to the files. Maybe it is necessary to run `bat cache --build` to make the theme available.

**Comment by emeinhardt** [comment]
@rycee If I understand `ls -la` output, the `ls -la ~/.config/bat/themes` output in my original post shows that a `.tmTheme` was generated and then directly symlinked from a nix store location to `~/.config/bat/themes/dracula.tmTheme`. 

Unfortunately, no amount of running `bat cache --build` (followed optionally by `sudo -i nixos-rebuild ...` +/- rebooting) changes the result of `bat --list-themes` (it still only contains the prepackaged defaults). The output of `bat cache --build` is also always what's shown in my original post.

@berbiche I can open an issue with `syntect` soon-ish and link to that here.

**Comment by rycee** [comment]
Curious, it seems to work for me:
``` console
$ ls -l .config/bat/themes/HmBase16.tmTheme 
lrwxrwxrwx 98 rycee 16 Nov 19:27 .config/bat/themes/HmBase16.tmTheme -> /nix/store/3z8anbv17pad801vllrwynibmfiyi07g-home-manager-files/.config/bat/themes/HmBase16.tmTheme

$ bat --list-themes | grep HmBase
HmBase16

$ bat --version
bat 0.18.2
```

I'm on Nixpkgs 21.05. Perhaps there is some difference in behavior between versions?

**Comment by emeinhardt** [comment]
The `bat` version on my machine is same as yours. I guess the difference could either be a change in what `home-manager` is doing or in something specific to the theme in question. 

Can you get the stock `dracula` example from documentation to work on your setup? 

I don't think I understand enough about `nix`to faithfully port what you're doing [here](https://gitlab.com/rycee/nur-expressions/blob/master/hm-modules/theme-base16/bat.nix) to my config, but I can try and work with the same source repository you're grabbing base-16 from.

**Comment by berbiche** [comment]
I tested on my side with the example and it seems to work.

> I don't believe the themes end up symlinked directories, just direct symlinks to the files. Maybe it is necessary to run bat cache --build to make the theme available.

Indeed, you are right.
