### ISSUE TITLE
bug: xdg.systemdirs.data does not work when genericLinux is enabled

### ISSUE THREAD

**Issue by dmayle** [nix-community/home-manager#2489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The generic linux config uses a hardcoded xdg.systemdirs.data setting which ignores the setting provided in the home-manager config.

I'm trying to get the sway.desktop session file into XDG_DATA_DIRS so that it gets picked up by the system display manager, but my changes have no effect.

The line in question: https://github.com/nix-community/home-manager/blob/master/modules/targets/generic-linux.nix#L34

### Maintainer CC

@rycee (no maintainers line, but pulled from last couple of commits)

### System information

```markdown
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.46-5bookworm1-amd64, Debian GNU/Linux, 12 (bookworm)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(douglas): `"home-manager, nixgl, nixpkgs-21.11pre332093.7fad01d9d5a"`
 - nixpkgs: `/home/douglas/.nix-defexpr/channels/nixpkgs`
```

**Comment by terlar** [comment]
Hmm, I thought the module system would merge all the occurrences of the same attribute...

**Comment by terlar** [comment]
I just tested this and it works for me. With this config:
```
{
  targets.genericLinux.enable = true;
  xdg.systemDirs.data = [ "/can/you/find/me" ];
}
```

I get:
```
$ grep /can/you/find/me result/home-files/.config/environment.d/10-home-manager.conf
XDG_DATA_DIRS=/can/you/find/me:${NIX_STATE_DIR:-/nix/var/nix}/profiles/default/share:/home/terje.larsen/.nix-profile/share:/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
```

**Comment by dmayle** [comment]
You're absolutely right.  I had to logout and log back in for it to take effect.  My fault, I thought that it would take effect with the instantiation of a new shell.
