### ISSUE TITLE
Systemd services for Qt apps fail to start

### ISSUE THREAD

**Issue by uvNikita** [nix-community/home-manager#249]
After upgrade to 18.03 services that use Qt libs fail to start with the following error:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
Reinstalling the application may fix this problem.
```
This effects `owncloud` and `qsyncthingtray` services on my laptop. Interesting that starting the application from the shell works, so it's probably not nixpkgs issue.

**Comment by uvNikita** [comment]
Log output of `owncloud-client.service` with `QT_DEBUG_PLUGINS=1`:
```
systemd[6355]: Started Owncloud Client.
owncloud[13458]: QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/cb3slv3szhp46xkrczqw7mscy5mnk64l-coreutils-8.29/lib/qt-5.10/plugins/platforms" ...
owncloud[13458]: QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/364b5gkvgrm87bh1scxm5h8shp975n0r-findutils-4.6.0/lib/qt-5.10/plugins/platforms" ...
owncloud[13458]: QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/s63b2myh6rxfl4aqwi9yxd6rq66djk33-gnugrep-3.1/lib/qt-5.10/plugins/platforms" ...
owncloud[13458]: QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/navldm477k3ar6cy0zlw9rk43i459g69-gnused-4.4/lib/qt-5.10/plugins/platforms" ...
owncloud[13458]: QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/dzrd8yxh9r1bwisphg3z47dxrxlgskv1-systemd-237/lib/qt-5.10/plugins/platforms" ...
owncloud[13458]: QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/iwgn08hf6957nbjv0hyr0x1lqk2w7zpj-owncloud-client-2.3.4/bin/platforms" ...
owncloud[13458]: This application failed to start because it could not find or load the Qt platform plugin "xcb"
owncloud[13458]: in "".
owncloud[13458]: Reinstalling the application may fix this problem.
systemd[6355]: owncloud-client.service: Main process exited, code=killed, status=6/ABRT
systemd[6355]: owncloud-client.service: Failed with result 'signal'.
```

**Comment by uvNikita** [comment]
Something is definitely missing in the environment. Starting owncloud with the clean environment fails with the same error:

```
$ env -i /nix/store/iwgn08hf6957nbjv0hyr0x1lqk2w7zpj-owncloud-client-2.3.4/bin/owncloud                                                                      
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
[1]    25686            env -i
```

**Comment by uvNikita** [comment]
For some reason, owncloud requires `PATH` to be set. Starting owncloud with clean `PATH` fails:
```
$ PATH="" /nix/store/iwgn08hf6957nbjv0hyr0x1lqk2w7zpj-owncloud-client-2.3.4/bin/owncloud
```
But adding user profile bin folder fixes the problem:
```
$ PATH="$HOME/.nix-profile/bin" /nix/store/iwgn08hf6957nbjv0hyr0x1lqk2w7zpj-owncloud-client-2.3.4/bin/owncloud
```

**Comment by rycee** [comment]
Hrm, this seems unfortunate. Does the service work if the systemd service file is changed to include something like
```
Environment = "PATH=%h/.nix-profile/bin";
```
?

**Comment by uvNikita** [comment]
Yes, it starts correctly with PATH set in the environment.

I wonder why it requires something from there. Running strace shows only one access to `$HOME/.nix-profile/bin` and it's lsb_release binary that doesn't exist there:

```
$ PATH="$HOME/.nix-profile/bin" /run/current-system/sw/bin/strace -f /nix/store/<hash>-owncloud-client-2.3.4/bin/owncloud 2>&1 | grep ".nix-profile/bin"
[pid  2502] statx(AT_FDCWD, "/home/user/.nix-profile/bin/lsb_release", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdde252800) = -1 ENOENT (No such file or directory)
^C
```

**Comment by rycee** [comment]
Curious. I know there is some plugin mechanism in qt that makes things a bit tricky. I believe we've also run into some issues when qt programs are installed through `users.users.<name?>.packages`.

@ttuegel We're having a mystery here :-) Hopefully you have the time to have a look at this thread and see if you recognize the issue and if you have any recommended way to run QT programs as systemd services. In short, do you happen to know why Qt applications seem to be runnable with a non-empty PATH but not with an empty one?

**Comment by uvNikita** [comment]
I created a PR to apply the workaround until we will fix it properly.

**Comment by ttuegel** [comment]
> In short, do you happen to know why Qt applications seem to be runnable with a non-empty PATH but not with an empty one?

@rycee Qt applications read `PATH` to recognize their installed plugins. Qt applications are not expected to run directly from the Nix store; they need to be installed into an environment so that their plugins are installed through `propagatedUserEnvPkgs`.

**Comment by ttuegel** [comment]
@rycee Yes, the preferred thing to do is install in `~/.nix-profile` and run from there.
