### ISSUE TITLE
bug: firefox: no user.js is created when only bookmarks are specified

### ISSUE THREAD

**Issue by benjaminor** [nix-community/home-manager#2492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

currently with the firefox configuration, when only the bookmarks are specified and profile.settings == {} and profile.extraConfig == "", no user.js is generated.

example config:
```nix
programs.firefox = {
    profiles = {
         standard = {
          bookmarks = {
            leoItalian = {
              keyword = "li";
              url = "https://dict.leo.org/italienisch-deutsch/%s";
						};
				};
		};
	};
};
```

possible fix: change line https://github.com/nix-community/home-manager/blob/c82bc787b8990c89f2f7d57df652ce2424129b92/modules/programs/firefox.nix#L374 to
`mkIf (profile.settings != { } || profile.extraConfig != "" || profile.bookmarks != {} ) {`

### Maintainer CC

@rycee

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.14.14-1-default, openSUSE Tumbleweed, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixpkgs-21.11pre294471.51bb9f3e9ab"`
 - channels(ben): `"home-manager"`
 - nixpkgs: `/nix/store/2d7a1m9cd99nvgl9cb6v9v1i24dvbgn6-nixpkgs-src`
```

**Comment by berbiche** [comment]
Hi,

Thanks for submitting this issue and finding out the source of the problem.
Would you like to submit a PR that fixes this or would you rather have someone else do it?

**Comment by benjaminor** [comment]
sure, done. I don't think this one-liner change warrants an extra test, but if you disagree I'm more than happy to provide one.
