### ISSUE TITLE
bug: himalaya connot build TOML config

### ISSUE THREAD

**Issue by tasmo** [nix-community/home-manager#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When trying to `switch` with `accounts.email.accounts.<name>.himalaya.enable = true;` the following error is resulting.

Tried to switch `programs.himalaya.settings` on and off with same error message.

```
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
```

### Maintainer CC

@ambroisie

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.10.79, NixOS, 21.11 (Porcupine)`
- sandbox: `yes`
- version: `nix-env (Nix) 2.4`
```

**Comment by sumnerevans** [comment]
Whoever fixes this should add a test to ensure we don't have regressions.

**Comment by ambroisie** [comment]
@tasmo can you share what settings you're using?

**Comment by tasmo** [comment]
@ambroisie Sure. Put [everything related in a Gist](https://gist.github.com/tasmo/66edc9259a42e098dbc85815c411c3f7) and stripped private parts.

**Comment by ambroisie** [comment]
@tasmo your problem comes from `imap-port` for `tasmo` being `null`.

As for a fix, we might be able to put a warning/error that no values in the `settings` should be `null`. However I feel like this should probably belong to `nixpkgs`' `formats.toml` itself.

@sumnerevans what do you think? Add a warning? Change the default value for `imap.port`? Also I am not sure how to test a configuration which cannot be built.

**Comment by tasmo** [comment]
Yes, when I put the IMAP port number in the configuration is built properly.

Wouldn't it be a good solution to use port `993` by default when `accounts.email.accounts.<name>.imap.tls.enable` is set to `true`?

**Comment by liff** [comment]
The [description of `imap.port`](https://github.com/nix-community/home-manager/blob/master/modules/accounts/email.nix#L123-L126) says that default is used when it’s `null`. Other programs [seem to respect that](https://github.com/search?q=repo%3Anix-community%2Fhome-manager+imap.port&type=code).
