### ISSUE TITLE
Dumb Symlinks

### ISSUE THREAD

**Issue by Krutonium** [nix-community/home-manager#2518]
So basically I have a game I want to have the config for centralized. I also want that game to be able to update it's own config. Seems reasonable, yes?

So what I've done is in my `home.nix` I've defined  `home.file.".config/OpenRCT2/config.ini".source = ./config/openrct2.conf` - which almost works, except instead of it being a link to the original, it appears that home-manager copies it elsewhere, and then links that. This would be fine, except as i said I need the game to be able to edit it's own config, and I want to be able to commit it to GitHub easily.

```
config.ini -> /nix/store/wqdjm5w54va5qgbdvhzqm7k5nwsz5qxs-home-manager-files/.config/OpenRCT2/config.ini
```

Is there a way around this, or a flag I don't know about?

(Also while I'm here, how do I set my cursors? (gtk.cursorTheme doesn't exist))

**Comment by berbiche** [comment]
Hi,

Have you tried using `config.lib.hm.mkOutOfStoreSymlink`?
This will allow you to create a symlink to a file.

Note however that you cannot use a path literal and will to use an absolute path (`"${config.home.homeDirectory}/my-home-manager-config/openrct2.conf"`).

See #2085

**Comment by Krutonium** [comment]
Okay, so how does that work though? 
`"${config.home.homeDirectory}/my-home-manager-config/openrct2.conf"`
Appears to only specify the source, but not the destination?

**Comment by berbiche** [comment]
> Okay, so how does that work though? `"${config.home.homeDirectory}/my-home-manager-config/openrct2.conf"` Appears to only specify the source, but not the destination?

See this reply in the thread linked in my original answer: https://github.com/nix-community/home-manager/issues/2085#issuecomment-861427318

**Comment by Krutonium** [comment]
Oh I see, Thanks!
