### ISSUE TITLE
mpd can't access pulseaudio when launched as user service

### ISSUE THREAD

**Issue by CarlosLoboxyz** [nix-community/home-manager#2529]
My issue here is pretty much the same thing thing as #2083 but the solution is not working:
when i tried to open `ncmpcpp` at startup this is the output of `systemctl --user status mpd`

`exception: Failed to open "Pulseaudio" (pulse); failed to connect: Connection refused`

However, this is solved if i run `systemctl --user start pulseaudio` or if i open firefox and play a video.

My configuration below:

`users.nix`
```nix
# Services provided by home manager
home-manager.users.MyUser.services = {
   mpd = {
      enable = true;
         extraConfig = ''
	    audio_output {
	       type "pulse"
	       name "Pulseaudio"
	       server "127.0.0.1"
	    }
	 '';
   };
...
```
`configuration.nix`
```nix
hardware.pulseaudio = {
   enable = true;
   extraConfig = "load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1";
};

users = {
   users.Myuser = {
      isNormalUser = true;
      extraGroups = [ "wheel" "audio" ];
   };
};
```

**Comment by berbiche** [comment]
Hi,

If you use `groups` in a shell, what's the output?
If the "audio" group is missing you have to log out and log in.

**Comment by CarlosLoboxyz** [comment]
audio already shows up in the output of `groups`

**Comment by berbiche** [comment]
From a quick search I found two possible solutions:
1. If you remove `server "127.0.0.1"` line from your config, does it work correctly?
2. If you add `listen=127.0.0.1` to the pulseaudio module parameter, does it work? (Might need a restart of pulseaudio, not sure)

**Comment by CarlosLoboxyz** [comment]
> If you remove server "127.0.0.1" line from your config, does it work correctly?

That actually works, thanks :smile:
