### ISSUE TITLE
bug: [firefox] cannot enable tridactyl native

### ISSUE THREAD

**Issue by Sweenu** [nix-community/home-manager#2530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have the following config:
```
    programs.firefox = {
      enable = true;
      package = pkgs.firefox.override {
        cfg = { enableTridactylNative = true; };
      };
    };
```
When building the conf, I have the following error:
```
error: attribute 'gtk3' missing

       at /nix/store/cvcnw3lnf3p76dd697l84qvyj5srql4k-source/pkgs/applications/networking/browsers/firefox/wrapper.nix:193:23:

          192|       nativeBuildInputs = [ makeWrapper lndir ];
          193|       buildInputs = [ browser.gtk3 ];
             |                       ^
          194|
```
I have looked at the different issues and PRs related to firefox native messaging hosts. I also read [this issue in nixpkgs](https://github.com/NixOS/nixpkgs/issues/141088) which is similar to my case, but I still don't understand what I am doing wrong. 
Be it a bug or not, I think the documentation should be updated if this is not the way to enable native messaging hosts anymore.

### Maintainer CC

@rycee @ambroisie 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211126_55275fc`
 - channels(root): `"nixos-21.11pre331460.931ab058daa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
Hi,

What is your `home.stateVersion`?

You should only override the `firefox-unwrapped` package.

**Comment by Sweenu** [comment]
22.05.
When overriding firefox-unwrapped I have the following error:
```
error: anonymous function at /nix/store/cvcnw3lnf3p76dd697l84qvyj5srql4k-source/pkgs/applications/networking/browsers/firefox/common.nix:6:1 called with unexpected argument 'cfg'

       at /nix/store/cvcnw3lnf3p76dd697l84qvyj5srql4k-source/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|

```
(I replaced firefox by firefox-unwrapped in my conf above)

**Comment by berbiche** [comment]
I made a mistake in my first post, since `home.stateVersion` 19.09, you need a wrapped package (which was already the case).

The only thing that comes to mind is an issue with your channels configuration or maybe a breaking change in the Firefox package.

**Comment by Sweenu** [comment]
Okay my bad, sorry for the noise. Because `system.stateVersion`'s default was 22.05 I assumed this was also the case for `home.stateVersion` but the default is 18.09.

**Comment by TheOPtimal** [comment]
I'm also having this issue. Home and system stateversions are 21.11

**Comment by ParetoOptimalDev** [comment]
I think there is an assumption of knowledge that is preventing others finding this issue from solving their own. I eventually figured out that using firefox-unwrapped consists of:

```diff
  programs.firefox = {
    enable = true;
-   package = pkgs.firefox;
+   package = pkgs.firefox-unwrapped;
}
```
