### ISSUE TITLE
programs.vim should add options to use vim-plug or vam to install plugins

### ISSUE THREAD

**Issue by soulomoon** [nix-community/home-manager#2531]
### Description
programs.vim should add options to use vim-plug or vam to install plugins. 
`pkgs.vim_configurable.customize` provides it. It should be make available in programs.vim too.

**Comment by soulomoon** [comment]
After study through source code of pkgs.vim_configurable and programs.vim, I discover I can use `vim-plug` to install by customizing packageConfigurable. But I still think it should be an easy way to do it than warp up pkgs.vim_configurable.
```
	packageConfigurable = pkgs.vim_configurable // {
		customize = (args: pkgs.vim_configurable.customize (pkgs.lib.recursiveUpdate args {
		vimrcConfig.plug.plugins = args.vimrcConfig.packages.home-manager.start;
		vimrcConfig.packages.home-manage.start = [ ];
		}));
	};
```

**Comment by teto** [comment]
why do you want to handle plugins via plug or vam rather than the native package system ? I am wary of supporting too many things in home-manager as (neo)vim presents seemingly infinite extendibility. This kind of suble optimization could live in a dedicated vim module extension for home-manager in a separate repository.

**Comment by teto** [comment]
I've removed pathogen support from nixpkgs, doing the same with vam at the moment, and possibly will do the same with vim-plug, as this increased maintainance cost. I am not a 100% against supporting plugin managers in HM but I dont really see the point as nix already does it and if you want vim-plug, then install vim-plug and use imperatively, no need for nix code (I do that with packer). Such an implementation would probably live best in a flake.
