### ISSUE TITLE
gtk should support Cursor Themes

### ISSUE THREAD

**Issue by Krutonium** [nix-community/home-manager#2533]
Right now, the gtk.* has
```
  gtk.enable = true;
  gtk.theme.name = "Sweet-Dark";
  gtk.iconTheme.name = "Obsidian-Purple";
```
Which is great, however I feel it should be vastly expanded, including 

```
gtk.cursorTheme
gtk.applicationTheme #Yes it's different
gtk.soundTheme
gtk.shellTheme
```
And perhaps even a wallpaper setting.

Also I havn't seen it, but if it doesn't exist, a way to enable and disable extensions as well.

**Comment by Krutonium** [comment]
![options](https://user-images.githubusercontent.com/3945538/144731094-e5bbc4c9-3171-456d-bf08-6edee6bd7998.png)
These exist in Tweak Tool but I'd honestly love to be able to set it and have it be perfect from then on.

**Comment by berbiche** [comment]
There's a PR implementing support for cursors here https://github.com/nix-community/home-manager/pull/2481

**Comment by Krutonium** [comment]
Given the existence of the PR - Which appears to have stalled in December of 2021 but is ready to merge otherwise, I'm going to close this. (Could someone please look into that?)
