### ISSUE TITLE
bug: senpai new config format

### ISSUE THREAD

**Issue by toastal** [nix-community/home-manager#2534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

https://github.com/NixOS/nixpkgs/pull/148667#event-5716391903

I merged a new version of [senpai](https://git.sr.ht/~taiite/senpai). Big changes include migrating from YAML to SCFG and supporting a password cmd option.

From their docs:

```shell-session
$ cat <<EOF >~/.config/senpai/senpai.scfg
address chat.sr.ht
nickname senpai
password "my password can't be this cute (2010)"
# alternatively, specify a command to fetch your password:
# password-cmd  gopass show irc/<username>
EOF
```

### Maintainer CC

@malte-v 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.5-zen1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211126_55275fc`
 - channels(root): `"home-manager, nixos-22.05pre335103.6daa4a5c045, nixpkgs-mozilla"`
 - channels(toastal): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Thanks for the ping!

CC module maintainer @malte-v

**Comment by berbiche** [comment]
Should we delete the module if nobody has stepped up to correct the configuration format change?

**Comment by jleightcap** [comment]
I'm happy to pick up maintenance. Considering the format has changed to the in-house [scfg](https://git.sr.ht/~emersion/scfg), two possible options:

1. Include a generator in nixpkgs's [lib/generators.nix](https://github.com/NixOS/nixpkgs/blob/master/lib/generators.nix) for scfg files; then use that.
2. Just use a format string in-line with the (pretty small) number of relevant config options.

**Comment by samhh** [comment]
Still relevant.
