### ISSUE TITLE
bug: tmux bindings don't have notes, so they don't show up in `C-b ?`

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#2540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

tmux 3.1 added the ability to attach notes to key bindings, with notes for all the default bindings. It also changed `C-b ?` to only list bindings with notes (this is `tmux list-keys -N`). It's still possible to list keys without notes using `tmux list-keys -Na`, but there's no binding for this.

The problem is home-manager includes its own key bindings, but these don't have notes, meaning they won't show up in `C-b ?`. Personally I think it was a mistake for tmux to suppress keys without notes by default, but perhaps this was done to try and force everyone to use notes?

In any case, home-manager's tmux module needs to attach notes to its keys. Otherwise they're not sufficiently discoverable for users. It should copy the current notes for any keys whose action has a default key binding, and use something sensible for any other keys.

This change should be safe to do on release branches from `release-20.09` onwards, as `nixos-20.09` contains tmux 3.1c (`nixos-20.03` has tmux 3.0a so that's too old for this).

### Maintainer CC

@marsam @toonn @expipiplus1

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 21.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.4`
 - channels(lily): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre329221.c11d08f0239"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by lilyball** [comment]
Argh, stale bots are the bane of my existence. Everything it says is a lie. People treat closed issues as _closed_, not as potential issues that were just shelved.

> Closed issues stay in the system for people to search, read, cross-reference, or even reopen

This especially is wrong. I'm the author of this issue and even I can't reopen it!

Stale bots only serve to make users feel like their issues don't matter and discourage future issues. This is actually a pretty significant issue with the `tmux` module. My `list-keys` binding now hides most of my bound keys.

**Comment by lilyball** [comment]
Hell, this issue is still even labeled as `triage`. Why the hell is the stale bot closing issues that were _never even triaged_?!?

**Comment by berbiche** [comment]
Sorry about the situation.

**Comment by toonn** [comment]
@lilyball, #2742 does address this, maybe that at least reduces the frustration.

**Comment by lilyball** [comment]
@toonn That's wonderful, thanks for linking it 💕 I checked latest master but didn't think to check open PRs.

Also I apologize for my tone in my above comments. I was quite cranky but that's not an excuse.
