### ISSUE TITLE
Support multiple home profiles

### ISSUE THREAD

**Issue by dguibert** [nix-community/home-manager#2542]
### Description

On a machine I want to deploy 2 different profiles managed by home-manager.
For now I managed to do that by defining `NIX_PROFILE` for the nix profile (`nix-env -i ...`) but the home-manager profile (`/nix/var/nix/profiles/per-user/$USER/home-manager`) is hard-coded. And its generation is updated whenever I updated either profile.

PS: my $HOME is shared on a cluster with x86_64 and aarch64 hosts. On profile per cpu architecture.

Is there any issue to introduce an option for the profile name?
(I could provide a patch... soon, I hope)

**Comment by rycee** [comment]
Yeah, this is a desirable feature and I'm hoping to find time to work on it. See https://github.com/nix-community/home-manager/pull/1156 for existing work.

**Comment by dguibert** [comment]
Great, I searched but missed it.
I'll try to test it and give feedback.

**Comment by rycee** [comment]
Note that the branch in the PR is very old and needs some work to get up-to-date. If you want to test it I would recommend doing so in a sandbox environment.

In any case, much appreciated that you are showing interest in this. I believe this feature is really nice and would open up quite a few future possibilities, so any additional eyes is very helpful.
