### ISSUE TITLE
bug: waybar assertion failure on 22.05

### ISSUE THREAD

**Issue by boppyt** [nix-community/home-manager#2546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

On 22.05, the `settings.[].modules` assertion fails even on a config with modules declared directly into `settings`, and a blank config like `[{}]`.

### Maintainer CC

@berbiche 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.7-xanmod1-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/store/4x5zgkr8p2d05az0ihdqzzbrmag2p7b8-source`
```

**Comment by berbiche** [comment]
Sorry, I could not reproduce this issue on either `home.stateVersion` `22.05` or `21.11` with unit tests.

**Comment by boppyt** [comment]
Hmm, can you provide the config that you used to test this? Wonder if its a problem with my config.

**Comment by berbiche** [comment]
I tested both scenarios by modifying the test case here: https://github.com/nix-community/home-manager/blob/7c320a53254609d9814280a34e312b7f00fd160b/tests/modules/programs/waybar/deprecated-modules-option.nix
and running `nix-shell -I nixpkgs=channel:nixos-unstable --pure tests -A run.waybar-deprecated-modules-option` from the Home Manager repo root.

**Comment by akkesm** [comment]
I am experiencing the same bug, the breaking pr is #2547 as everything worked before it.
My config looks [like this](https://gist.github.com/akkesm/ddce88f390004f46bbb5e64c3fc6fa71).

I also tried formatting it like the one @berbiche uses in his dotfiles, and it still failed the assertion.

My issue is only on 22.05; on 21.11 it works both with and without `modules`.

**Comment by berbiche** [comment]
Hi,

Just making sure when you say "22.05" do you mean `home.stateVersion` or using the Home Manager release 22.05 (master)?
I suppose you mean the first one but I just want to make sure I understand the situation correctly.

**Comment by akkesm** [comment]
Yes sorry for the confusion. I have set `home.stateVersion` to 22.05.
I'm using flakes, right now I've pinned HM to the last commit before this change (on master), otherwise I follow the master branch (HEAD).

**Comment by boppyt** [comment]
Nice, now we know this is a real issue.

I even tried rewriting my whole configuration thinking my flake was messed up. Would love to see this fixed!

**Comment by berbiche** [comment]
I have finally been able to reproduce this issue.
I will submit a fix.
