### ISSUE TITLE
bug: Unable to use firefox-bin with home-manager.

### ISSUE THREAD

**Issue by quantmint** [nix-community/home-manager#2559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am unable to use firefox-bin with home manager. I have tried to set `package = pkgs.firefox-bin` but it doesn't work and i get an error : [errors.txt](https://github.com/nix-community/home-manager/files/7713866/errors.txt)

### Maintainer CC

@benjaminor 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.6-xanmod2-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"home-manager, nixos-22.05pre337103.581d2d6c9cd"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
Hi,

What is your `home.stateVersion`?

I use firefox-bin in my configuration with no errors.

**Comment by quantmint** [comment]
I have just changed my home.stateVersion and everything works now, thank you.

> Hi,
> 
> What is your `home.stateVersion`?
> 
> I use firefox-bin in my configuration with no errors.
