### ISSUE TITLE
bug: zsh aliases aren't picked up by syntax highlighting when using hm module

### ISSUE THREAD

**Issue by lockejan** [nix-community/home-manager#2561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hey, the zsh.enableSyntaxHighlighting directive loads the corresponding plugin at a suboptimal time.
Meaning, aliases aren't picked up correctly by the syntax highlighting plugin and because of that remain falsely displayed in red.

I also tested it against the manual zsh plugin approach provided by home-manager with zsh.plugins = [ ... ] 

This resulted in a working zsh setup, where even the aliases are parsed correctly by the syntax highlighting plugin.

### Maintainer CC

@davegallant 

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(lockejan): `"home-manager, nixpkgs-22.05pre338285.c473cc87147"`
 - channels(root): `"nixpkgs-22.05pre336690.f225322e3be, darwin, home-manager-21.05"`
 - nixpkgs: `/Users/lockejan/.nix-defexpr/channels/nixpkgs`
```

**Comment by davegallant** [comment]
I'm unable to reproduce this on darwin or linux. `shellAliases` defined in the zsh module are highlighted in green.

**Comment by lockejan** [comment]
Thank you for testing.
I rechecked and found that the issue holds only true for an edge case.
It's reproducible on mac and linux.

## How to reproduce:

Linux docker setup:
1. `docker run -it --rm nixos/nix:2.3.16`
2. `nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager`
3. `nix-channel --update`
4. `nix-shell '<home-manager>' -A install`
5. `nix-env -iA nixpkgs.vim nixpkgs.ncurses`

Minimal working example to be added to the default home-manager conf:

```nix
  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    enableCompletion = true;
    enableSyntaxHighlighting = true;
    shellAliases = {
      update = ''
        nix-channel --update && home-manager switch && lsp-update
      '';
       lsp-update = ''
        cd ~/.cache/nvim/nlua/sumneko_lua &&
        git pull &&
        cd 3rd/luamake &&
        compile/install.sh &&
        cd ../.. &&
        ./3rd/luamake/luamake rebuild && cd '';
     };
};
```

Default commands are picked up and highlighted in green.
The configured alias `update` and `lsp-update` aren't picked up and displayed in red.
However, I found that `lsp-update` is responsible for that.
If lsp-update is omitted from the update alias, update gets correctly highlighted.
So it boils down to the content of lsp-update.
I guess it might be an issue in the plugin itself then.🤔

**Comment by lockejan** [comment]
I also tested it with home-managers plugin mechanism and the issue persists.
It's obviously a plugin-issue then.
Already opened an issue in the repo: https://github.com/zsh-users/zsh-syntax-highlighting/issues/847
