### ISSUE TITLE
bug: wayland.windowManager.sway.xwayland = false does not deactivated xwayland

### ISSUE THREAD

**Issue by genofire** [nix-community/home-manager#2567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

no line with `xwayland disable`appears in `~/.config/sway/config`

### Maintainer CC

@alexarice @sumnerevans 

### System information

```markdown
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/4i653qmy6rs7r3m6zh60j0nwnnc5gi6k-bash-interactive-5.1-p12-dev
copying path '/nix/store/4i653qmy6rs7r3m6zh60j0nwnnc5gi6k-bash-interactive-5.1-p12-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-22.05pre338278.b0bf5f888d3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sumnerevans** [comment]
Setting it to false just makes it so that `xwayland` is not installed. But I think it's reasonable to also do `xwayland disable`.

**Comment by genofire** [comment]
Other applications could also install X wayland - and to it is installed and started
