### ISSUE TITLE
bug: bspwm pkgs don't create ~/.config/bspwm/bspwmrc config file

### ISSUE THREAD

**Issue by ajmasia** [nix-community/home-manager#2573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Trying to use `bspwm` managed by `home-manager`, the `~/.config/bspwm/bspwmrc` config file it's not created.

This is my config:

```nix
  xsession = {
    enable = true;

    windowManager.bspwm = {
      enable = true;
  
      startupPrograms = [
        "pgrep -x sxhkd > /dev/null || sxhkd"
        "pkill picom"
        "picom --experimental-backends"
        "feh $HOME/Pictures/nix-wallpaper-simple-dark-gray.png"
        "$HOME/.config/polybar/launch.sh"
      ];
      settings = {
        "border_width" = 0;
        "window_gap" = 9;
        "pointer_follows_monitor" = true;
        "focus_follows_pointer" = true;
      };
      monitors = {
        "" = [ "1" "2" "3" "4" ];
      };
      rules = ''
        {
          "mumble" = {
            "state" = "floating";
            "follow" = true;
            "focus" = true;
          };
        }
      '';
    };
  };
```

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(ajmasia): `""`
 - channels(root): `"nixos-21.11.334247.573095944e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
What's your `xdg.configHome`? Anything relevant in the logs?

**Comment by ajmasia** [comment]
> xdg.configHome

I don't have it defined, but other packages generate their configuration files in .config automatically

**Comment by ncfavier** [comment]
Make sure you're using the latest version of home-manager (release-21.11 or master). The bspwm module only writes its config to `$XDG_CONFIG_HOME` since https://github.com/nix-community/home-manager/commit/e70524cd2b50682fcb55fc799e7391dc18375903.

**Comment by ncfavier** [comment]
Did this solve your issue? Please close if it did
