### ISSUE TITLE
Requesting a gpg release-21.11 backport from master

### ISSUE THREAD

**Issue by kciredor** [nix-community/home-manager#2575]
Hi,

Would it be possible to backport the new programs.gpg from [master](https://github.com/nix-community/home-manager/blob/master/modules/programs/gpg.nix) to [release-21.11](https://github.com/nix-community/home-manager/blob/release-21.11/modules/programs/gpg.nix)?

I love the mutableKeys and mutableTrust additions and can't wait to use them. Afaik there's no way to mix home-manager stable and unstable definitions in my NixOS configuration.

Thanks!
kciredor

**Comment by rycee** [comment]
Sure, sounds like a good idea and I haven't heard of any problems with that feature. Have backported those commits now.

Btw, it is actually possible to [replace modules](https://nixos.org/manual/nixos/stable/index.html#sec-replace-modules) but it can occasionally be a bit tricky.

**Comment by kciredor** [comment]
Thanks @rycee, works great!
