### ISSUE TITLE
bug: can't install unfree packages when using as NixOS module

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#2581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm trying to use home-manager in the NixOS configuration module mode. However, I'm having trouble dealing with unfree packages. In particular I'm seeing errors like the following: 
```
❯ sudo nixos-rebuild switch --upgrade   
unpacking channels...
building Nix...
building the system configuration...
error: Package ‘vscode-1.63.2’ in /nix/store/av33qdgbb93wba7lyn9ql6bbwjjz6f23-nixos-21.11.334639.9ab7d12287c/nixos/pkgs/applications/editors/vscode/vscode.nix:45 has an unfree license (‘unfree’), refusing to evaluate.

a) To temporarily allow unfree packages, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_UNFREE=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

Alternatively you can configure a predicate to allow specific packages:
  { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
      "vscode"
    ];
  }

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```
No problem, I'll just add `nixpkgs.config.allowUnfree = true;` to `/etc/nixos/configuration.nix` as point (b) suggests... But this doesn't work either. I still see the exact same error.

Here's my complete `/etc/nixos/configuration.nix`: https://gist.github.com/samuela/ba408d77d4a9f4691d8b53c9b1aa029d

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.05.4361.43bbfd4994c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334639.9ab7d12287c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
Hi,

> By default, Home Manager uses a private pkgs instance that is configured via the home-manager.users.<name>.nixpkgs options.
> To instead use the global pkgs that is configured via the system level nixpkgs options, set `home-manager.useGlobalPkgs = true;`
> This saves an extra Nixpkgs evaluation, adds consistency, and removes the dependency on NIX_PATH, which is otherwise used for importing Nixpkgs.

**Comment by samuela** [comment]
This is very confusing. Could we fix the error message to reflect this? I know that the error message lives in nix and not home-manager but the whole thing makes for a very confusing user experience.

**Comment by berbiche** [comment]
> Could we fix the error message to reflect this?

There's no way for Home Manager to detect if an unfree package is being evaluated. So it's not possible unfortunately.

We can't change the default value of the option either because it would break previously working configurations.

**Comment by Deuxis** [comment]
I just encountered this issue when using home manager as nixos module. I added an unfree package to my user's `home.packages`, and it ignored the global `nixpkgs.config.allowUnfree = true;` *and* the `allowUnfree = true;` in my user's `~/.config/nixpkgs/config.nix`. As an experiment I created a file `/root/.config/nixpkgs/config.nix` (since as a module home-manager is run as part of nixos-rebuild which I run as root) and that worked.

I just followed your advice and set `home-manager.useGlobalPkgs = true;` which also worked and allowed me to get rid of that weird root config file, but I assume the above is not intended behaviour.

**Comment by denizdogan** [comment]
I think this might be the same issue as #2942 which is more active

**Comment by vinicius507** [comment]
I have this same issue now.

For some reason it ignores `nixpkgs.config.allowUnfree[Predicate]` settings even with `home-manager.useGlobalPkgs = true`.

I've had to re-evaluate nixpkgs:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    home-manager,
    ...
  } @ inputs: let
    inherit (self) outputs;

    system = "x86_64-linux";
  in {
    nixosConfigurations = {
      host = nixpkgs.lib.nixosSystem {
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true; # This works.
        };
        modules = [
          # The following is ignored by hm
          {
            nixpkgs.config.allowUnfree = true;
            nixpkgs.config.allowUnfreePredicate = _: true;
          }
          # [...]
        ];
        specialArgs = {inherit inputs outputs;};
      };
    };
  };
}
```

**Comment by AkechiShiro** [comment]
This issue is still relevant today and can be still reproduced.

**Comment by teto** [comment]
reimporting nixpkgs and having home-manager using the generated pkgs set works as a nixos module 
`home-manager.useGlobalPkgs = true;`. See https://nix-community.github.io/home-manager/#sec-install-nixos-module .
