### ISSUE TITLE
Pass config.security.wrapperDir

### ISSUE THREAD

**Issue by puuuuh** [nix-community/home-manager#2583]
### Description

Now i cant get wrapperDir, so i have to hardcode this path in my configs

**Comment by berbiche** [comment]
Can you provide more information about your system?

Home Manager is a standalone tool and unless you use it in as a NixOS/nix-darwin module it's not possible to retrieve global configuration option.

If you are using the Home Manager module, you can access global configuration by adding `nixosConfig` in your `home.nix` parameters (i.e. `{ config, lib, pkgs, nixosConfig, ... }: `). You can then access `nixosConfig.security.wrapperDir`.

**Comment by puuuuh** [comment]
> Can you provide more information about your system?
> 
> Home Manager is a standalone tool and unless you use it in as a NixOS/nix-darwin module it's not possible to retrieve global configuration options.
> 
> If you are using the Home Manager module, you can access global configuration by adding `nixosConfig` in your `home.nix` parameters (i.e. `{ config, lib, pkgs, nixosConfig, ... }: `). You can then access `nixosConfig.security.wrapperDir`.

https://github.com/puuuuh/nixos-config/blob/master/users/puh/home.nix

**Comment by berbiche** [comment]
Closing this issue since a "solution"/explanation is provided in https://github.com/nix-community/home-manager/issues/2583#issuecomment-1000556046.
