### ISSUE TITLE
No tests for `meta` attributes in modules

### ISSUE THREAD

**Issue by LunNova** [nix-community/home-manager#2588]
Lots of the `meta.maintainers` values were invalid. I've raised a PR to fix them #2587, it'd also be nice to make sure they continue being valid in the future.

I'm not sure how to test them automatically.

Running `nix eval .#homeConfigurations.user` with the unprivileged flakes setup without the `.activationPackage` will fail for any incorrect maintainers entries, but I don't understand why (and ran into this by accident), and it will still fail without any wrong maintainers entries due to missing `meta.doc`.

```
$ nix eval .#homeConfigurations.lun
error: The option `meta.doc' is used but not defined.
```

**Comment by rycee** [comment]
Yes, this is a good point. I added a CI step to validate the maintainers field so hopefully we'll notice any problems in the future.

About evaluating the configuration, I think it may be difficult to do that using a plain `nix eval` without going through the `evalModules` function. Even the output of `evalModules` will probably not eval cleanly, you'll need to look at the `config` attribute of the output.
