### ISSUE TITLE
bug: password store settings are not created

### ISSUE THREAD

**Issue by timhae** [nix-community/home-manager#2589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I specify settings like this:
```
  programs = {
    password-store = {
      enable = true;
      settings = {
        PASSWORD_STORE_DIR = "/home/tim/repos/password-store";
        PASSWORD_STORE_GENERATED_LENGTH = "50";
        PASSWORD_STORE_CLIP_TIME = "42";
      };
    };
```
unfortunately they are not replicated in the generated wrapper file which looks like this:
```
...
  15   │ PREFIX="${PASSWORD_STORE_DIR:-$HOME/.password-store}"
  16   │ EXTENSIONS="${PASSWORD_STORE_EXTENSIONS_DIR:-$PREFIX/.extensions}"
  17   │ X_SELECTION="${PASSWORD_STORE_X_SELECTION:-clipboard}"
  18   │ CLIP_TIME="${PASSWORD_STORE_CLIP_TIME:-45}"
  19   │ GENERATED_LENGTH="${PASSWORD_STORE_GENERATED_LENGTH:-25}"
  20   │ CHARACTER_SET="${PASSWORD_STORE_CHARACTER_SET:-[:punct:][:alnum:]}"
...
```
my config is [here](https://github.com/timhae/nixconfig), please let me know if I made some configuration mistakes there, I am fairly new to flakes.

### Maintainer CC

@pacien 

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.87, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(tim): `"home-manager-21.05"`
 - channels(root): `"nixos-21.11.334684.1158f346391, nixos-unstable-21.11pre301414.45fc7d4a35c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
Hi,

I believe the pass module adds the environment variables to your shells directly instead of the wrapper.

It is possible you won't see the change in your shells until you log out and log in again.

**Comment by timhae** [comment]
Hey, thanks for your prompt feedback. Unfortunately I do not see the corresponding variables even after a reboot. Do I need to enable them somewhere else?

**Comment by pacien** [comment]
> I believe the pass module adds the environment variables to your shells
> directly instead of the wrapper.

This is correct.

I'm not sure whether we should change this to set those settings in a wrapper.
This would avoid polluting the whole user environment, but this would require
using a specific wrapped version of `pass` consistently everywhere.

> Unfortunately I do not see the corresponding variables even after a reboot.
> Do I need to enable them somewhere else?

Home Manager sets the session environment variables only if your shell is also
fully managed by Home Manager. If this is not the case, you can manually source
`hm-session-vars.sh`. For more details, see [5.2. Why are the session variables
not set?][hm-5.2].

[hm-5.2]: https://rycee.gitlab.io/home-manager/index.html#_why_are_the_session_variables_not_set

**Comment by timhae** [comment]
Thanks for the hint. My `.nix-profile` folder only contains a `manifest.nix` file and no `etc/profile.d/hm-session-vars.sh` so I can not source this file. It does exist in my nix store but is not linked somewhere in my `.nix-profile` folder. I can also not find it in `/nix/var/nix/profiles/per-user/tim/`.

**Comment by timhae** [comment]
The environment variables are set when using home manager to manage my shell. Please feel free to reopen the issue if it is still relevant for you and thanks a lot for your quick help.
