### ISSUE TITLE
Add support for system-wide changes when used as a NixOS module

### ISSUE THREAD

**Issue by KFearsoff** [nix-community/home-manager#2594]
### Description

Right now, Home Manager only provides the functionality of managing the userspace. Thanks to the clever design of Nix and the ability to create systemd units in userspace, it can do a lot, but it is not without limitations.

One example of where it matters would be Sway. It depends on OpenGL being available and fails to launch without it: #2150 . Please note the suggestion to set `hardware.opengl.enable = true;` in NixOS config. [NixOS Sway module](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/programs/sway.nix) does this for you, but [HM Sway module](https://github.com/nix-community/home-manager/blob/master/modules/services/window-managers/i3-sway/sway.nix) doesn't. I discovered that when I stumbled upon the same problem.

There are two problems in particular. The first one is the UX one: I see the option `enable`, I assume that if I set it to true, then Sway will be working. If I don't have OpenGL, then the build should fail with an error message or enable OpenGL, more on that later. The second problem is modularity: I want my Sway config to be [in a single file](https://github.com/KFearsoff/NixOS-config/blob/01897226d77d7b1a10a3e063bea9a7579e64919e/modules/sway/default.nix), but it is not really feasible to declare both the config and the OpenGL in the same file:

1. It isn't really possible to do with `home-manager.users.<user>.wayland.windowManager.sway = import ./sway.nix;`, since there isn't an escape hatch that would allow one to configure the NixOS module from inside of the HM module.
2. Using `imports = [ ./sway.nix ];` is also not really an option, since then you'd have to specify `home-manager.users.<user>` by hand. Which is not a good solution for multi-user systems. 
3. Use `imports = [ ./sway.nix ];` and wrap `home-manager.users.$user` inside of the foreach statement that cycles through the users declared in the current config. I don't even think that's possible.

### Proposition

Home Manager should allow to address NixOS system config from inside of the modules when used as a NixOS module. Maybe modules should have something like `extraSystemConfig` as an escape hatch. Preferably, modules that depend on the system configuration should also change it accordingly: such as installing OpenGL. That would also solve #2205 .

**Comment by KFearsoff** [comment]
After looking into it a little bit more, Sway in particular suffered a lot from the lack of NixOS integration: #1288 and NixOS/nixpkgs#89179. The proposed solution was to delegate installation to NixOS and configuration to HM, which is fine, but I think it's missed potential.

On the implementation side, I see HM module already has `nixosConfig` in `specialArgs`. That should mean that it's already possible to affect the system in modules that have `specialArgs`, so all that needs to be done is to pass `specialArgs` to Sway module and to configure the system accordingly, unless I'm missing something. Doesn't sound terribly hard, I think I'll manage making a pull request, so I am waiting for a green light on that.

That said, I want to hear opinions on whether that's a desirable feature. After all, HM's purpose is to configure user environment - it might be out of scope to affect the system environment, even if by proxy. It also increases the maintanence burden on HM until it is officially integrated. 

I personally consider HM to be an essential part of NixOS, so I would like to see tighter integration. In case that's not a feature that should be added, I still propose adding a `wayland.windowManager.sway.extraNixosConfiguration` option that would let the user access the `specialArgs.nixosConfig`. That would essentially be a middle ground where tighter integration is possible, but it is entirely optional.

**Comment by berbiche** [comment]
> Home Manager should allow to address NixOS system config from inside of the modules when used as a NixOS module

While you have mentioned valid usecases (configuring opengl drivers, swaylock issue), I personally disagree and think Home Manager should remain independent of the rest of the system.

On the technical side, I don't know how it would be possible with the nixpkgs module system to add some custom global configuration from the user.
Nix is a functional language with no mutable data-structures, so it is not possible to "modify" the `nixosConfig` attribute set.

**Comment by KFearsoff** [comment]
> On the technical side, I don't know how it would be possible with the nixpkgs module system to add some custom global configuration from the user. Nix is a functional language with no mutable data-structures, so it is not possible to "modify" the `nixosConfig` attribute set.

That's true. I forgot about that detail. Well, then that's not happening.

There's another way to deal with the issue I have, though. It is not as clean, but I discovered that I actually can divide HM into multiple files. So the following:
```{
  config = {
    hardware.opengl.enable = true;
      home-manager.users.username  = {
        wayland.windowManager.sway.enable = true;
      };
    };
  };
}```
is possible. I think I can turn it into a function too, passing in the `username`, so that `home-manager.users."${username}"` generalizes nicely. That solves the secondary issue I had, and I'd say it's good enough for me.

I think the issue can be closed.

**Comment by terlar** [comment]
You could do this if you want it to apply to all the users:
```
{
  config = {
    hardware.opengl.enable = true;
    home-manager.sharedModules = [
      {
        wayland.windowManager.sway.enable = true;
      }
    ];
  };
}
```
