### ISSUE TITLE
Make `syncthing` command configurable

### ISSUE THREAD

**Issue by sir4ur0n** [nix-community/home-manager#2598]
### Description
Currently the `syncthing` command is [hardcoded](https://github.com/nix-community/home-manager/blob/master/modules/services/syncthing.nix#L60) to `"${pkgs.syncthing}/bin/syncthing -no-browser -no-restart -logflags=0"`.

How about making this configurable, similarly to `syncthing.tray.command`?

Use case I have: currently, integrating with a tray application, e.g. `pkgs.syncthing-tray`, does not work because `syncthing-tray` requires the `syncthing` API key.

Of course I can retrieve the **current** API key through the syncthing website (e.g. http://localhost:8384/ / actions / advanced / GUI / Api Key) but this key will most likely change on every computer `syncthing` I run, so I don't want to hardcode it in `syncthing.tray.command` with the `-api` flag.

I would prefer to pass an API key to **both** `syncthing` and `syncthing-tray`:
```nix
  services.syncthing =
    let apiKey = "whateverApiKeyIWish"; in
  {
    enable = true;
    # The current option that is missing
    command = "${pkgs.syncthing}/bin/syncthing -no-browser -no-restart -logflags=0 --gui-apikey=${apiKey}";
    tray = {
      enable = true;
      command = "syncthing-tray -api ${apiKey}";
      package = pkgs.syncthing-tray;
    };
  };
```

**Comment by rycee** [comment]
With the latest master you should be able to add

    services.syncthing.extraOptions = [ "--gui-apikey=${apiKey}" ];

**Comment by sir4ur0n** [comment]
I realize how late I am, but I wanted to thank you for adding this :pray:
