### ISSUE TITLE
bug: --version is a hidden parameter

### ISSUE THREAD

**Issue by davidak** [nix-community/home-manager#2604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The parameter `--version` exists, to show the version, but it is not shown in man page or help.

parameter:

https://github.com/nix-community/home-manager/blob/19d95258ac63ff8c5d920a136d4780ad07affee5/home-manager/home-manager#L582-L585

missing in

https://github.com/nix-community/home-manager/blob/1a6df903e320eb848c02a343141a11afefe4a73f/home-manager/completion.bash
https://github.com/nix-community/home-manager/blob/c7592b747b332eded1a1728e87abbc6e66b934f4/docs/man-home-manager.xml
...

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.11, nixos-21.11.334797.6979c0e49bb, nixos-hardware, nixos-unstable-22.05pre340469.cb372c3b888"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Tested with latest version from nixpkgs https://github.com/NixOS/nixpkgs/pull/152243.
```

**Comment by rycee** [comment]
Haven't noticed before, thanks for point it out 🙂 Should be fixed now.
