### ISSUE TITLE
Darwin: Ability to set -currentHost defaults

### ISSUE THREAD

**Issue by Atemu** [nix-community/home-manager#2615]
### Description

I don't know when this became common but, in newer macOS versions, some preferences go to `~/Library/Preferences/ByHost/$filename.$UUID.plist` (i.e. `~/Library/Preferences/ByHost/com.apple.controlcenter.00000000-0000-0000-0000-00000000.plist`) now.

These can be accessed using `defaults -currentHost`, i.e. `defaults read -currentHost com.apple.controlcenter`. This is the place `BatteryShowPercentage` lives in macOS 11 for instance.

As a HM user, I want to be able to set these defaults just like the regular ones.

@midchildan

**Comment by midchildan** [comment]
Ah, I was wondering why the `BatteryShowPercentage` option seemingly vanished. I'll look into this.

**Comment by Atemu** [comment]
Not stale, see PR above.
