### ISSUE TITLE
Alacritty module doesn't write a YAML config file

### ISSUE THREAD

**Issue by JonathanReeve** [nix-community/home-manager#2620]
Unless I'm missing something, Alacritty requires its config file to be in YAML. But [the Alacritty module has it outputting JSON](https://github.com/nix-community/home-manager/blob/c751aeb19e84a0a777f36fd5ea73482a066bb406/modules/programs/alacritty.nix#L59). Thus, configuration with home-manager doesn't work. 

A fix would be to change this so that it outputs YAML instead of JSON.

**Comment by berbiche** [comment]
Hi,

YAML is a superset of JSON therefore the configuration generation works without problems.

We have to use `toJSON` to generate the configuration because it is not possible to have hexadecimal/unicode escaping in Nix strings and we need to patch the output.

**Comment by JonathanReeve** [comment]
I guess there's something else making it so this configuration doesn't work, in that case. I'll open a different issue about that.
