### ISSUE TITLE
bug: only `home.stateVersion = "20.09";` can be used, no higher version

### ISSUE THREAD

**Issue by papojari** [nix-community/home-manager#2622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm trying to set my `home.stateVersion` to `22.05` but I get this error:
```
warning: Git tree '/git-repos/home-manager-config' is dirty
error: The option `home.stateVersion' has conflicting definition values:
       - In `/nix/store/rrl1iip4n6pa5vkfldqp01ljyv7jraa1-source/users/default/home.nix': "22.05"
       - In `<unknown-file>': "20.09"
(use '--show-trace' to show detailed location information)
```
Other version like `21.05` also don't work. Only `20.09`. I don't know where `<unknown-file>` is.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(papojari): `"nixos-22.05pre338911.03ec468b140"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
You want to update your home-manager to get this change https://github.com/nix-community/home-manager/blob/master/modules/misc/version.nix#L17

**Comment by papojari** [comment]
I already have Home Manager version 22.05 installed though

**Comment by SuperSandro2000** [comment]
Did you set it in flake.nix like this?

```nix
home-manager.lib.homeManagerConfiguration {
 stateVersion = nixpkgs.lib.version;
};
```

**Comment by papojari** [comment]
`nixpkgs.lib.version` is `"22.05pre-git"` for me so that does not work. However setting it to `"22.05"` manually in the flake works. Before I tried to set it in an imported `home.nix`.

**Comment by papojari** [comment]
Having
```nix
home-manager.lib.homeManagerConfiguration {
 stateVersion = nixpkgs.lib.version;
};
``` work would obsviously still be nice. How can I do that?

**Comment by berbiche** [comment]
Hi,

Have you grepped in your configuration for "20.09"?
Home Manager does not set a default state version.

**Comment by mainrs** [comment]
I'm new to home-manager and nix. Shouldn't the stateVersion be kept as-is anyway? At least that's what the comments always said : )

**Comment by SuperSandro2000** [comment]
> I'm new to home-manager and nix. Shouldn't the stateVersion be kept as-is anyway? At least that's what the comments always said : )

Well, yes and no. If you are bumping it you may need to manually fix or move things but for ease many people familiar with those things and developing just bump it all the time.

**Comment by berbiche** [comment]
> Having
> 
> ```nix
> home-manager.lib.homeManagerConfiguration {
>  stateVersion = nixpkgs.lib.version;
> };
> ```
> 
> work would obsviously still be nice. How can I do that?

I don't think it's possible unless you parse the version string.

You can use `lib.versions.splitVersion` or a regex with `builtins.match`.
`lib.versions.splitVersion lib.version == [ "22" "05" "pre" "git" ]` (in my situation).

Closing this issue. Feel free to reopen.

**Comment by edio** [comment]
This is issue is closed, but the linked PR is still not merged, and I still observe the buggy behavior.

Any updates on this? What is the suggested workaround?
