### ISSUE TITLE
bug: `programs.skim` still uses `pkgs.skim` instead of deferring to `programs.skim.package`

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#2627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The `programs.skim` module just gained a `programs.skim.package` option (#2619). Unfortunately it still references `pkgs.skim` for its shell completions and key bindings instead of using `config.programs.skim.package` for those.

Every reference to `pkgs.skim` in the `programs.skim` module config should be replaced with `cfg.package` instead.

### Maintainer CC

@liff @berbiche

### System information

```markdown
Mostly irrelevant. home-manager is `github:nix-community/home-manager/f3be3cda6a69365f2acecc201b3cd1ee4f6d4614`.
```

**Comment by berbiche** [comment]
Whoops, I'll make a PR swiftly.
