### ISSUE TITLE
`programs.man` should have a `package` option

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#2634]
### Description

The `programs.man` module should have a `package` option that lets me change the package added to `home.packages`. This should not affect `programs.man.generateCaches` as that uses `pkgs.man-db` directly anyway rather than the `pkgs.man` that is put in `home.packages`.

The reason here is I need to wrap `bin/man` to set a custom `MANPATH` (macOS `man` inserts Apple developer tools libraries into the default path but man-db doesn't know how to do this), but using an overlay to replace the package forces rebuilds of dependents (in my case that causes 67 rebuilt derivations). I can't just set this as a session variable as it needs to be calculated every time `man` is invoked (other env vars and system configuration influence the resulting developer tools paths).

**Comment by brendanzab** [comment]
> The reason here is I need to wrap `bin/man` to set a custom `MANPATH` (macOS `man` inserts Apple developer tools libraries into the default path but `man-db` doesn't know how to do this)

@lilyball Just curious how you ended up doing this, if you managed to at all? I’ve been running into a similar issue on macOS, of `man` not knowing about the macOS command line tools: https://github.com/LnL7/nix-darwin/issues/474#issuecomment-1222014104. I tried doing something like this in my nix-darwin `shellInit`s:

```
export MANPATH="''${MANPATH+$MANPATH:}$(xcode-select --print-path)/usr/share/man"
```

But running `manpath` resulted in a complaint that I was setting `$MANPATH` manually, meaning the nix manpaths were lost:

```
$ manpath
.manpath-wrapped: warning: $MANPATH set, ignoring /nix/store/5zvcc873vn0sp9jnksflfkmcmnj29f7v-man-db-2.10.2/etc/man_db.conf
/Library/Developer/CommandLineTools/usr/share/man
```

...which lead me down the route of searching for stuff related to `man-db`, which was appearing in `man manpath`:

```
$ nix why-depends --derivation ./result /nix/store/5zvcc873vn0sp9jnksflfkmcmnj29f7v-man-db-2.10.2/
warning: Git tree '/Users/brendan/Developer/personal/home' is dirty
/nix/store/y5k2lv4i3rhj47z78ysvrarlz0l7v13c-darwin-system-22.05.20220816.a82127c+darwin4.80871c7.drv
└───/nix/store/c4c4khmfb7zjqflkcj83qvdh7lf57i0k-activation-brendan.drv
    └───/nix/store/1c6zkamw86fshigg14ybzhp2y91as437-home-manager-generation.drv
        └───/nix/store/dxpxv1ghm7wkl1ambvwfzv5qdsgw25v5-home-manager-path.drv
            └───/nix/store/x8na3qamickr4bvii555yi0aj6z8ha3s-man-db-2.10.2.drv
```

**Comment by brendanzab** [comment]
Oh, I think I figured it out! I added the following to my `nix-darwin` configuration:

```nix
{
  environment.etc."man_db.conf".text = ''
    # Sourced from ${pkgs.man}/etc/man_db.conf

    ${lib.readFile "${pkgs.man}/etc/man_db.conf"}

    # Further additions

    # Manual pages for nix-darwin (from https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/man-db.nix)
    MANPATH_MAP /run/current-system/sw/bin /run/current-system/sw/share/man
    MANPATH_MAP /run/wrappers/bin          /run/current-system/sw/share/man

    # Manual page caches for nix-darwin
    MANDB_MAP /run/current-system/sw/share/man /var/cache/man/nixos

    # Manual pages for macOS (from /usr/local/man --where)
    MANPATH_MAP /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/bin /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man
    MANPATH_MAP /Library/Developer/CommandLineTools/usr/bin                 /Library/Developer/CommandLineTools/usr/share/man
    MANPATH_MAP /usr/bin                                                    /Library/Developer/CommandLineTools/usr/share/man

    # Manual page caches for macOS-related manpaths
    MANDB_MAP /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man /var/cache/man/CommandLineToolsSDK
    MANDB_MAP /Library/Developer/CommandLineTools/usr/share/man                 /var/cache/man/CommandLineTools
  '';
}
```
