### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by mainrs** [nix-community/home-manager#2636]
Hello!

I wanted to contribute back and fully translate the project into German. In German we have to ways to address people. One is formal and one is more casual. Do you have a preference for one of them? I'd personally go for the more formal one, but I know that some CLIs from from Ubuntu do use the more casual one.

Almost all OS do also use the more formal one.

**Comment by rycee** [comment]
Thanks for wanting to contribute, it is much appreciated! I don't think I have any particular preference. That said, the existing English text is quite informal and it would probably be nice to keep that tone in other languages. But I imagine it would be possible to do so while still addressing the reader in a formal way?

**Comment by mainrs** [comment]
Thanks for the feedback! Yep, that is possible :)

**Comment by Mic92** [comment]
I would say formal German would make more sense. The nix community is more technical oriented, while Ubuntu has a more for "humans" approach.

**Comment by rycee** [comment]
Thanks @Mic92 and @mainrs. Then I think formal is the way to go.
