### ISSUE TITLE
Add option to sway.extraConfig to appear at the top of the config file

### ISSUE THREAD

**Issue by JonathanReeve** [nix-community/home-manager#2652]
### Description

When [using Pywal with Sway](https://github.com/dylanaraps/pywal/wiki/Customization#sway), Pywal has you load a sway include file at the beginning of the config file. This doesn't seem to be possible with the current home-manager setup, since `sway.extraConfig` adds stuff to the bottom of the file, but the Pywal include needs to be at the top of the file.

If there weree an option on sway.extraConfig, or a new option, sway.extraConfigEarly, that would allow for this Pywal include.

**Comment by jakobkukla** [comment]
I would love to have this exact feature in the bspwm module.

**Comment by berbiche** [comment]
> I would love to have this exact feature in the bspwm module.

Would you mind creating another feature request for bspwm?
It would be easier to track each feature requests separately.

**Comment by JonathanReeve** [comment]
This issue is not stale—we're just waiting on #2847.

**Comment by JonathanReeve** [comment]
Again, this issue is not stale, we're still waiting on #2847.

**Comment by teto** [comment]
now that we have earlyExtraCofig AND a pywal module in HM, do you want to have another look @JonathanReeve ?

**Comment by JonathanReeve** [comment]
Yep I think this is done!
