### ISSUE TITLE
How to install derivations?

### ISSUE THREAD

**Issue by andreicek** [nix-community/home-manager#2653]
### Description

How can I install packages like `pkgs.beam.packages.erlangR20.elixir_1_6`?

By installing `elixir_1_6` you get a version built by the current erlang.

Thanks!

**Comment by berbiche** [comment]
Hi,

This can be achieved by adding packages to `home.packages = [ ]`.

This option, like most other options, can be used in multiple files.

For instance, `foo.nix` could contain:

``` nix
{ pkgs, lib, config, ... }:

{
  home.packages = [ pkgs.hello ];
}
```

and `bar.nix`:

``` nix
{ pkgs, lib, config, ... }:

{
  home.packages = [ pkgs.git ];
}
```

The `home.nix` would only need to import both files:

``` nix
# home.nix
{ pkgs, lib, config, ... }:

{
  imports = [ ./foo.nix ./bar.nix ];
}
```

**Comment by andreicek** [comment]
Thanks! This ended up working for me:

```
  home.packages = with pkgs; [
    beam.packages.erlangR22.elixir_1_12
  ];
```
