### ISSUE TITLE
bug: The option `services.dnsmasq' does not exist.

### ISSUE THREAD

**Issue by shirakaba** [nix-community/home-manager#2670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Given this Home Manager config:

```nix
{ config, pkgs, ... }:

let
  homeDirectory = "/Users/jwork";
in
# https://nix-community.github.io/home-manager/options.html
{
  home.username = "jamie";
  home.homeDirectory = homeDirectory;

  # https://search.nixos.org/packages?channel=unstable
  home.packages = [
    pkgs.dnsmasq
  ];
  services.dnsmasq = {
    enable = false;
  };
  home.stateVersion = "22.05";
  programs.home-manager.enable = true;
}
```

... It says that `services.dnsmasq` does not exist, despite my having seen it used by other people on NixOS:

https://github.com/NixOS/nixpkgs/issues/104181
https://github.com/NixOS/nixpkgs/issues/27504
https://github.com/NixOS/nixpkgs/issues/20863

```
➜  ~ home-manager switch
error: The option `services.dnsmasq' does not exist. Definition values:
       - In `/Users/jwork/Documents/git/nixpkgs/home.nix':
           {
             dnsmasq = {
               enable = false;
             };
           }
```

Am I misunderstanding something about home-manager? How should I configure dnsmasq through home-manager if not this?

### Maintainer CC

@eelco
@fpletz
@globin

### System information

```markdown
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(jamie): `"home-manager"`
 - channels(root): `"nixpkgs-22.05pre337993.e6df26a654b"`
 - channels(jwork): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
```

**Comment by anubhavkini** [comment]
This isn't possible through home-manager since it is designed for configuring user environments and not the system.
The examples that you have listed are NixOS configurations and not home-manager configurations.
It should be possible for you to configure `dnsmasq` through [nix-darwin](https://github.com/LnL7/nix-darwin) on macOS.

**Comment by rycee** [comment]
Indeed, as @anubhavkini said. It is not possible to configure dnsmasq or other system level services through Home Manager.
