### ISSUE TITLE
bug: services.nextcloud-client doesn't necessarily open proper file manager

### ISSUE THREAD

**Issue by witchof0x20** [nix-community/home-manager#2671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The nextcloud desktop client uses xdg-mime to determine which file manager to open. However, the module only adds `${config.home.profileDirectory}/bin` to the PATH. So in the case that xdg-utils is not installed via home-manager, the Nextcloud client falls back to firefox on my system.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.93-hardened1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335574.32aa3d78297"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by witchof0x20** [comment]
```nix
home.packages = with pkgs; [ xdg-utils ]
```
 fixes it on my system at least

**Comment by berbiche** [comment]
Hi,

I think this issue should be transferred to https://github.com/nixos/nixpkgs/issues to have the package's `xdg-mime`/`xdg-open` call substituted.

**Comment by Kranzes** [comment]
Fix has already been addressed on https://github.com/NixOS/nixpkgs/pull/162019. This issue can be closed.
