### ISSUE TITLE
Showing home-manager log when using as NixOS module...?

### ISSUE THREAD

**Issue by VergeDX** [nix-community/home-manager#2672]
### Description
When using home-manager as NixOS module, I noticed the pretty hm logs is missing.
Unfortunately, I'm using "/ on tmpfs" pattern, and I'm not finding a way to use hm alone.

I know the hm log will print in journal, I can add an `system.activationScripts` step back.
But this way is hacky, and missing pretty color output : (

**Comment by mainrs** [comment]
Would you mind sharing the script that re-enables hm logs?

**Comment by berbiche** [comment]
Didn't realize this was a duplicate of #2464.

Closing.
