### ISSUE TITLE
Is there a way to create symlinks?

### ISSUE THREAD

**Issue by broccoli5** [nix-community/home-manager#2673]
I'm using Gnome and I would like to symlink `$HOME/Pictures/Wallpapers` with `$HOME/.local/share/background` so that I don't have to manually add my Wallpapers to Gnome and duplicate them in the process. I have looked through the docs, all I found was the `home.file` option, but nothing about symlinks.

If there currently isn't a way to do it, it would IMO make a neat feature.

**Comment by SuperSandro2000** [comment]
Sounds like you want to use ``https://nix-community.github.io/home-manager/options.html#opt-home.file``.

**Comment by broccoli5** [comment]
@SuperSandro2000 I did see that, but how would I go about making the symlink? Do I have to create it with `ln` and then use `home.file.<name>.source` to place it?

**Comment by Enzime** [comment]
You can use `config.lib.file.mkOutOfStoreSymlink` to create the symlink, in my `dotfiles` I use the following line:

```nix
{
      xdg.configFile."nixpkgs".source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles";
}
```

**Comment by broccoli5** [comment]
@Enzime thanks! I totally forgot that there are function in Nix 🤦
