### ISSUE TITLE
bug: ${config.xdg.userDirs.<dir-name>} does not expand to a full path

### ISSUE THREAD

**Issue by broccoli5** [nix-community/home-manager#2676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

So, I am probably using this in a way that wasn't intended. I want to symlink `$HOME/.local/share/backgrounds` with `$HOME/Pictures/Wallpapers` so it makes sense to use `${config.xdg.userDirs.pictures}/Wallpapers` instead of `${config.home.homeDirectory}/Pictures/Wallpapers`. But `${config.xdg.userDirs.pictures}` expands to `$HOME/Pictures` instead of the full path, breaking the symlink.

Side note: why `xdg.userDirs` does not set the session variables? I would expect them to be set by this option, sourcing `$HOME/.config/user-dirs.dirs` with zshenv (in my case) seems like a hack

### Maintainer CC

@pacien

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(broccoli): `"home-manager"`
 - channels(root): `"nixos-21.11.335526.6c4b9f1a2fd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mainrs** [comment]
Maybe the issue lies in how the values are defined?

https://github.com/nix-community/home-manager/blob/a52aed72c84a2a10102a92397339fa01fc0fe9cf/modules/misc/xdg-user-dirs.nix#L41-L45

https://github.com/nix-community/home-manager/blob/a52aed72c84a2a10102a92397339fa01fc0fe9cf/modules/misc/xdg.nix#L45-L52

As far as I know, `types.str` do not get expanded.

**Comment by broccoli5** [comment]
@mainrs These option are for setting the values in `$HOME/.config/user-dirs.dirs` So it makes sense that they would set them as strings and not the full path, even tho it does not really matter because it's set per user anyway.

I will make a feature request because the xdg options are kinda confusing, they don't actually set the environmental variables (which I would expect, especially because `$XDG_CONFIG_HOME` and etc are actually set by the xdg module), and aren't usable in the config because as I said they don't expand to the full path, which is a shame

**Comment by mainrs** [comment]
Ah, I missed that, thanks for explaining!
