### ISSUE TITLE
Improve docs to include how to update

### ISSUE THREAD

**Issue by DanielSiepmann** [nix-community/home-manager#2685]
### Description

I'm very new to home-manager and also new to nix itself. I followed the docs at https://nix-community.github.io/home-manager/index.html and everything works fine.

What I miss is: "How to update". How do I keep my system up to date when using home-manager? Do I need to run the following?

```bash
nix-channel --update \
   && nix-env -ia nixpkgs.nix nixpkgs.cacert \
   && home-manager switch \
   && home-manager expire-generations '-30 days' \
   && nix-env --delete-generations +5 \
   && nix-store --gc
```

Or something else? One told me that home-manager can maintain nix itself, so I guess it would be okay to just run:
```bash
nix-channel --update \
   && home-manager switch \
   && home-manager expire-generations '-30 days' \
   && nix-store --gc
```

But I am not sure how to maintain nix via home-manager, as I would first need to uninstall via `nix-env` which will leave me in a state where I no longer can run `home-manager switch`? But adding it to the packages to install will result in:

```
home-manager switch
/nix/store/sq8i2sjs4jjfah5i0k5fhqp673s95nq1-home-manager-generation
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
building '/nix/store/3zqah9crzalwb9mc75dw7xrgiv04wg3g-user-environment.drv'...
error: packages '/nix/store/bvx4mfgm9xigdnm95l6fwnxl84cjywzg-nix-2.5.1-man/share/man/man5/nix.conf.5.gz' and '/nix/store/blk20z0vsca2p66aqpj3iqgw7j30djmi-home-manager-path/share/man/man5/nix.conf.5.gz' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
error: builder for '/nix/store/3zqah9crzalwb9mc75dw7xrgiv04wg3g-user-environment.drv' failed with exit code 1

Oops, nix-env failed to install your new Home Manager profile!

Perhaps there is a conflict with a package that was installed using
"nix-env -i"? Try running

    nix-env -q

and if there is a conflicting package you can remove it with

    nix-env -e {package name}

Then try activating your Home Manager configuration again.
```

Would be really cool to extend docs for that use case, so newcomers are able to get started as well as to maintain their system.

**Comment by DanielSiepmann** [comment]
Not sure if home-manager auto updates all packages on `home-manager switch` and one only needs to run `nix-channel --update`. But that could be added to the docs as well.

**Comment by berbiche** [comment]
Hi,

Welcome to the Nix community!

Home Manager indeed lacks documentation about the "typical" workflow a user could have with it.
When using channels, it is sufficient to run `nix-channel --update` before doing a `home-manager {switch,build,instantiate}`.

> But I am not sure how to maintain nix via home-manager, as I would first need to uninstall via `nix-env` which will leave me in a state where I no longer can run `home-manager switch`?

I checked in my virtual machine with `nix-env -qAp` and I only have `home-manager-path` installed for my current user on a multi-user install of Nix (Nix with a daemon).

My root user has `nix-2.5.1` installed, which makes the binary available in `/nix/var/nix/profiles/default/bin/nix`.

I think you can add Nix in your `home.packages` after removing the package from your user environment with `nix-env -e nix`.

**Comment by DanielSiepmann** [comment]
Hey :)

Thanks for feedback. I'll create a PR for the "update" part withi ndocs.

I switched to an older generation still including nix. That allowed me to run `home-manager switch` which maintains nix itself. I could then uninstall nix via `nix-env`. I guess your VM only includes nix, not NixOS? I won't retry the setup again right now and would close with the linked PR. My root user doesn't have nix at all. I'm running Nix as package manager on my Ubuntu and installed for my primary user only.

It's not a good idea to add multiple issues within a single issue on GitHub ;) And I don't think it is a big problem anyway, as no one else opened an issue yet.
