### ISSUE TITLE
Table of contents for Appendix A. Configuration Options

### ISSUE THREAD

**Issue by andrewhamon** [nix-community/home-manager#2689]
### Description
I'm a pretty new user of home manager, and I love it. Unfortunately, it is very hard to discover all the possible configuration options. They are all listed in [Appendix A. Configuration Options](https://nix-community.github.io/home-manager/nix-darwin-options.html), but it is an extremely long page.

It's fine if you already know what you are looking for, but for a new user like me, it is very hard to get a sense of what all is possible with home manager.

**Comment by rycee** [comment]
@mipmip made a nice interactive search page which may be more like what you are looking for: https://mipmip.github.io/home-manager-option-search/

It's still relatively new but I imagine it, or something like it, will become more or less the preferred method of searching for options in the future.

**Comment by andrewhamon** [comment]
To reiterate, the shortfall here is for "discovery" -- e.g. I just want to browse around. The page you linked is great, but is mostly an improvement over CMD+F in the browser, e.g. primarily geared for when you know what you are looking for.

My best bet seems to be just browsing the source code. e.g. browsing `modules/programs` seems to be the best way to get an overview of all the programs currently supported without having to wade through all the config options of each program.

For me that's actually perfectly sufficient, but it sure feels like I have to source dive for all things nix, far more so than any other ecosystem I've encountered so far, and perhaps isn't the greatest for newcomers.
