### ISSUE TITLE
bug: "error: attribute 'formats' missing" when trying to import mkLiteral for configuring Rofi

### ISSUE THREAD

**Issue by Soupstraw** [nix-community/home-manager#2691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I tried to set the `programs.rofi.theme` option to what is shown in the example:
```
{ config, pkgs , lib , ... }:
let
  home-manager = builtins.fetchTarball "https://github.com/nix-community/home-manager/archive/master.tar.gz";
in
{
  imports =
    [
      (import "${home-manager}/nixos")
    ];


  home-manager.users.sherk = {
    programs.rofi.enable = true;
    programs.rofi.theme = let
      inherit (config.lib.formats.rasi) mkLiteral;
    in {
      "*" = {
        background-color = mkLiteral "#000000";
        foreground-color = mkLiteral "rgba ( 250, 251, 252, 100 % )";
        border-color = mkLiteral "#FFFFFF";
        width = 512;
      };
    
      "#inputbar" = {
        children = map mkLiteral [ "prompt" "entry" ];
      };
    
      "#textbox-prompt-colon" = {
        expand = false;
        str = ":";
        margin = mkLiteral "0px 0.3em 0em 0em";
        text-color = mkLiteral "@foreground-color";
      };
    };
  };
}
```

When I try to rebuild home-manager, I get this error:
`error: attribute 'formats' missing, at /etc/nixos/home.nix:179:16`

### Maintainer CC

@thiagokokada @ncfavier @ayyess 

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(sherk): `"home-manager-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
You're using the wrong `config`: `lib.formats.rasi` is defined in home-manager, not in NixOS.

You can fix this with `home-manager.users.sherk = ({ config, ... }: { ... });`

**Comment by Soupstraw** [comment]
> You're using the wrong `config`: `lib.formats.rasi` is defined in home-manager, not in NixOS.
> 
> You can fix this with `home-manager.users.sherk = ({ config, ... }: { ... });`, or alternatively use `config.home-manager.users.sherk.lib.formats.rasi`.

This fixed it for me, thanks :)
