### ISSUE TITLE
bug: The use of `shellDryRun` breaks my build

### ISSUE THREAD

**Issue by Sciencentistguy** [nix-community/home-manager#2693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

#2668 appears to have broken my system. 

```
➜ darwin-rebuild switch
building the system configuration...
error: attribute 'shellDryRun' missing

       at /nix/var/nix/profiles/per-user/root/channels/home-manager/modules/programs/bash.nix:12:9:

           11|     checkPhase = ''
           12|       ${pkgs.stdenv.shellDryRun} "$target"
             |         ^
           13|     '';
(use '--show-trace' to show detailed location information)
```

### Maintainer CC

The PR was sent by @ncfavier and merged by @rycee 

### System information

```markdown
- system: `"aarch64-darwin"`
- host os: `Darwin 21.3.0, macOS 12.2`
- multi-user?: `yes`
- sandbox: `no`
- version: `nix-env (Nix) 2.5.1`
- channels(jamie): `"darwin, home-manager"`
- channels(root): `"darwin, home-manager, nixpkgs-22.05pre346058.bc59ba15b64"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
You should update your version of nixpkgs: as mentioned in the PR you found, this relies on a very recent change.

**Comment by Sciencentistguy** [comment]
This still occurs after running `sudo nix-channel --update && nix-channel --update`.

**Comment by ncfavier** [comment]
Could you maybe have set up your channels wrong? The name `nixpkgs-22.05pre346058.bc59ba15b64` seems to suggest that your nixpkgs channel is pinned to a particular (21 days old) version.

**Comment by Sciencentistguy** [comment]
I'm not sure how that happened, but yes it would appear that my channels got confused. Deleting and re-adding nixpkgs-unstable as a channel fixed it. Thanks!

**Comment by lucperkins** [comment]
@Sciencentistguy I got bitten by this as well, in #2699. Glad I searched the issues before filing one 😄 Is there any specific reasoning behind not pinning Nixpkgs to a specific commit for each version of Home Manager?

**Comment by Sciencentistguy** [comment]
I wonder if it's possible, and if so how, to pin the nixpkgs that home-manager uses, without using channels

**Comment by ncfavier** [comment]
There was some discussion about pinning in https://github.com/nix-community/home-manager/pull/2371#issuecomment-939193974

**Comment by lucperkins** [comment]
@Sciencentistguy I actually pin my Nixpkgs inside my Home Manager config: https://github.com/lucperkins/nix-home-manager-config/blob/main/home.nix#L4-L5. For Home Manager I think you'd really only have to do this in `default.nix`:

```nix
let
  nigpkgsRev = "...";
  pkgs = import (fetchTarball "https://github.com/nixos/nixpkgs/archive/${nigpkgsRev}.tar.gz") {};
in rec {
  docs = with import ./docs { inherit pkgs; }; {
    html = manual.html;
    manPages = manPages;
    json = options.json;
    jsonModuleMaintainers = jsonModuleMaintainers; # Unstable, mainly for CI.
  };

  home-manager = pkgs.callPackage ./home-manager { path = toString ./.; };

  install =
    pkgs.callPackage ./home-manager/install.nix { inherit home-manager; };

  nixos = import ./nixos;

  path = ./.;
}

```
