### ISSUE TITLE
More consistent XDG support

### ISSUE THREAD

**Issue by broccoli5** [nix-community/home-manager#2694]
### Description

The XDG module should set the environment variables for user directories if the option `xdg.userDirs.enable` is set to `true`, this would make it more consistent because the XDG module already sets some user specific variables like `XDG_CONFIG_HOME`:

https://github.com/nix-community/home-manager/blob/9d369c75ce2fdeb296ad42bcdc8c1a523c494550/modules/misc/xdg.nix#L89-L93

Currently the user directories aren't really usable in the configuration itself as they do not expand to the full path as theyr type is `types.str` :

https://github.com/nix-community/home-manager/blob/a52aed72c84a2a10102a92397339fa01fc0fe9cf/modules/misc/xdg-user-dirs.nix#L41-L45

This can be easily fixed by changing theyr type to `types.path` (this shouldn't cause any issues as they are defined per user anyway), which would again align with other XDG variables like `XDG_CONFIG_HOME`:

https://github.com/nix-community/home-manager/blob/a52aed72c84a2a10102a92397339fa01fc0fe9cf/modules/misc/xdg.nix#L45-L52

There could be a option to not set the environment variables for user directories, but as I see it would be pointless because once you want to manage them in your config you probably want them to be accessible system wide

**Comment by mainrs** [comment]
That explains why some scripts stopped working when I switched to Home Manager. I didn't even think about checking these. I can open a PR and set them inside of `sessionVariables`. However, I am not sure if the second change would be considered a breaking change. I am still not /that/ familiar with the nix language itself.
