### ISSUE TITLE
bug: flakes + home manager error when "Starting Home Manager activation"

### ISSUE THREAD

**Issue by ahmedelgabri** [nix-community/home-manager#2715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I get this error after running `darwin-rebuild switch --flake .` on my dotfiles after updating my flakes today https://github.com/ahmedelgabri/dotfiles/commit/8036ca33bfd0fad07b67bfd7d5d326ebca69d032

```
Activating home-manager configuration for ahmed
Starting Home Manager activation
error: getting status of '/private/tmpahmed': No such file or directory
```

Seems like a `/` is missing because `/private/tmpahmed` is `/private/tmp` + `$USER`

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(ahmed): `"darwin, nixpkgs-21.03pre262129.5000e5707bc"`
 - nixpkgs: `/nix/store/fbcgjqs34vllzzppa1y213fbxx01sxn7-source`
```

**Comment by berbiche** [comment]
Hi Ahmed,

Do you use custom activation scripts in your configuration?
This is the first time this issue has been brought up and I cannot reproduce this on my Darwin machines.

**Comment by ahmedelgabri** [comment]
Hi @berbiche, 

I do yes https://github.com/ahmedelgabri/dotfiles/search?q=activationScripts but none of them touches `/tmp` & they seem to be running fine because I see the output from them before reaching this step.

**Comment by ahmedelgabri** [comment]
I updated my flakes again today & it seems that it's resolved now. So I will close this.
