### ISSUE TITLE
bug: home-manager does not create any files (no errors)

### ISSUE THREAD

**Issue by marcosrdac** [nix-community/home-manager#2721]
### Is there an existing issue for this? No

- [x] I have searched the existing issues

### Issue description

For some reason home-manager does not create any files in my configuration anymore. Here is my `home.nix` at `/home/marcosrdac/.config/nixpkgs/home.nix`:

```nix
{ config, pkgs, ... }:

{
  home.username = "marcosrdac";
  home.homeDirectory = "/home/marcosrdac";
  home.stateVersion = "21.05";
  home.packages = with pkgs; [ ];        # packages are installed correctly
  programs.home-manager.enable = true;

  home.file."test".text = "a test";      # file is not generated

  xsession.enable = true;
  xsession.scriptPath = ".hm-xsession";  # file is not generated

  xsession.windowManager.bspwm = {
    enable = true;                       # config not generated
    settings = { "split_ratio" = 0.6; };
    monitors = { };
    rules = { };
    extraConfig = "";
    startupPrograms = [ "sxhkd" ];
  };

  programs.git = {
    enable = true;                       # git still asks for me to configure it manually 
    userName = "marcosrdac";
    userEmail = "marcosrdac@gmail.com";
    aliases = { };
  };
}
```

Here is home-manager output:

```
adam% home-manager switch
trace: warning: literalExample is deprecated, use literalExpression instead, or use literalDocBook for a non-Nix description.
/nix/store/rsk6zqbzf6lgda6rr98b6218s2i9sn2f-home-manager-generation
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating linkGeneration
Cleaning up orphan links from /home/marcosrdac
```

I am using flakes, but when I remove it, everything stays the same.

My home-manager version is:"home-manager-2021-03-21". I tried to use other versions installed here too, but the problem persists.

What could I be doing wrong? I was able to write to a file some days ago, but then now I can't.

I appreciate your time!

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 21.05.20220115.0fd9ee1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(marcosrdac): `""`
 - channels(root): `"nixos-21.11.335820.521e4d7d13b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sheeldotme** [comment]
I'm experiencing the same issue:

```
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(sheelpatel): `""`
 - channels(root): `""`
 - nixpkgs: `/Users/sheelpatel/.config/nixpkgs/nixpkgs.nix`
```

The home-manager configuration: https://github.com/sheeldotme/bonobo/blob/home-files/home.nix

**Comment by sheeldotme** [comment]
In my case it looks like the files are generated at `/nix/store/...-home-manager-generation/home-files`, they just aren't linked / copied to `$HOME`.

**Comment by marcosrdac** [comment]
@sheeldotme did you have a previous problem in which home-manager stoped working and you re-linked home-manager yourself? I solved a problem like this in the past and I wonder if it is related to our condition.

**Comment by marcosrdac** [comment]
> @sheeldotme did you have a previous problem in which home-manager stoped working and you re-linked home-manager yourself? I solved a problem like this in the past and I wonder if it is related to our condition.

In my case, home-manager could not find a "home-manager/home-manager/home-manager.nix" and I solved it using another version of home-manager that was on the store.

**Comment by sheeldotme** [comment]
@marcosrdac I don't recall any manually linking.  I also noticed the following in your output that doesn't show up for me, so it seems my issue is likely different from yours:
```
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
```

**Comment by marcosrdac** [comment]
Today I created a new test user and run home-manager from unstable channel and everything worked well there.

Then I tried to remove my user from system config, remove all my user files, apply the garbage collector to my nix store, then adding my user again in the config, rebuild the system and try using home-manager from unstable there, just like in my test user. But the problem persists on my user (marcosrdac).

When I rebuilded my configs with my new user again, it printed `reviving marcosrdac...`. I believe NixOS is retrieving my user from somewhere of home-manager is still searching for it in some place...

**Comment by marcosrdac** [comment]
I believe the problem is that I cannot remove the home-manager generation I am on. It is always read. How can I remove my current generation?

I cannot do that this way:

```sh
adam% home-manager generations                                                
2022-02-14 20:46 : id 28 -> /nix/store/arkjribgznwwmpsiv5yjd6r21id480xy-user-environment
adam% home-manager remove-generations 28                                      
Cannot remove the current generation 28
```

And a `home-manager uninstall` will not remove it either... :(

**Comment by marcosrdac** [comment]
Okay, I got it:

```sh
$ rm /nix/var/nix/profiles/per-user/marcosrdac/home-manager*
$ rm /nix/var/nix/gcroots/per-user/marcosrdac/current-home
```

Then running home-manager again worked as expected.
