### ISSUE TITLE
mu should include aliases when initializing the database

### ISSUE THREAD

**Issue by exzombie** [nix-community/home-manager#2724]
Looking at how the [list of addresses is constructed](https://github.com/nix-community/home-manager/blob/master/modules/programs/mu.nix#L20), it appears that aliases are not taken into account. Without this, `mu` is unable to recognize all personal addresses.

**Comment by ShamrockLee** [comment]
@KarlJoad

**Comment by KarlJoad** [comment]
Correct. Aliases were not taken into account when this module was created, only the primary email address of each email account.

**Comment by sumnerevans** [comment]
closed by https://github.com/nix-community/home-manager/pull/2748
