### ISSUE TITLE
bug: starship settings are required to be unique in home-manager attrsets, but not in starship config 

### ISSUE THREAD

**Issue by Fidgetcetera** [nix-community/home-manager#2730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Some starship config, keyly `battery.display`, is allowed to be set multiple times, but not in `programs.starship.settings`. 

Example config according to [starship docs](https://starship.rs/config/#battery-display):
```
[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]] # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"
discharging_symbol = "💦"

# when capacity is over 30%, the battery indicator will not be displayed
```

vs, say, my nix config: 
```
programs.starship.settings.battery = {
	display = {
		threshold = 10;
		style = "bold red";
	};
	display = {
		threshold = 99;
		style = "bold yellow";
	};
};
```
which of course leads to 
`attribute 'style' at /home/fidgetcetera/Synced Nix Configs/shared-configs/common.nix:60:8 already defined at /home/fidgetcetera/Synced Nix Configs/shared-configs/common.nix:64:8`

This seems to relate to #2519 but it also seems separate enough to need its own issue.

### Maintainer CC

@marsam 

### System information

```markdown
~ 
took 512ms 
💤😈🐲🍰🌑🌺🐯|🔮 nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/977rrqjf3hfda1qbqlpp2pz22m6phczy-bash-interactive-5.1-p8-dev
copying path '/nix/store/977rrqjf3hfda1qbqlpp2pz22m6phczy-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.99, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(fidgetcetera): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/sbgwfjabaxp6mc46fd59ba59px3gj1lj-nixpkgs`
```
```

**Comment by berbiche** [comment]
Hi,

Have you tried using a list with `programs.starship.settings."battery.display"`?

Something like the following:
``` nix
{
  programs.starship.settings."battery.display" = [
    {
      threshold = 10;
      style = "bold red";
    }
    {
      threshold = 99;
      style = "bold yellow";
    }
  ];
}
```

I haven't tried the configuration above but it's probably worth a try!

**Comment by Fidgetcetera** [comment]
oh our gosh thank you *so* much, that was almost exactly what we needed. it needs to be `programs.starship.settings.battery."display"` but otherwise? perfect perfect thank you lots!!

**Comment by berbiche** [comment]
> is this workaround/part of nix language

I suppose it is considered a workaround.

I updated my previous comment to use the right solution.

I will close this issue since it was resolved.
