### ISSUE TITLE
Config for the Vim ALE plugin

### ISSUE THREAD

**Issue by witchof0x20** [nix-community/home-manager#2733]
### Description
I find myself often wanting to logically tie my ALE config to a development enviroment, for example a `rust.nix` that installs `rustup` and appends to the vim config: 
```vim
let g:ale_fixers = {"rust":["rustfmt"]}
let g:ale_linters = {"rust":["analyzer"]}
```
but this might look nicer as
```nix
{
  programs.vim.ale = {
    fixers.rust = ["rustfmt"];
    linters.rust = ["analyzer"];
  };
}
```
which also has the benefit that it automatically combines attribute sets. I'm actually not sure how to do this append operation normally, which is part of what spurred this.

I have a small, very hacky prototype I've hacked in to my local config https://gist.github.com/witchof0x20/48cd56f75f6474ef0538ae390b891c88

Would nixifying specific vim plugin config be within scope for the vim module?

**Comment by ModdedGamers** [comment]
I'm not a core dev of home-manager, but I'd say no. Implementing config for every vim plugin(even just the major ones, there are many definitions of major plugins in an ecosystem as wide as vim's) seems way too out of scope for home-manager. 

Home-manager(correct me if I'm wrong) is meant to do the things it does well, and vim configuration seems like something too out-of-scope for home-manager, and something that is prone to screw-ups/misconfiguration(different variable types such as lists vs dictionaries, etc). To add onto that, home-manager is not tied to a specific nixpkgs version, so adding a config for one version of a plugin is liable to break any time the plugin's author updates the config(and that update is pushed to nixpkgs of course), which means that user config is broken until we update or the user updates their config. 

So, while I think that this would be a great idea(I'm all for it), I don't think it's feasible or worth it to implement this. But, as stated at the top, I'm not a home-manager dev, so maybe someone's already working on this.

**Comment by teto** [comment]
Reimplementing every configuration system in nix is madness. I dont think this should go into HM but you can extend the home-manager module in your own config, you dont have to upstream this to be able to use it.

**Comment by witchof0x20** [comment]
I do like this particular instance of madness... But I figured it might be a bit out of scope which is why I posted this to check, Thanks!
