### ISSUE TITLE
bug: EDITOR and VISUAL are hardcoded when using prezto+zsh

### ISSUE THREAD

**Issue by Retrodynen** [nix-community/home-manager#2739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hi,

When using the below:

```nix
programs.zsh.prezto.enable = true;
home.sessionVariables.ALTERNATE_EDITOR = "emacs";
home.sessionVariables.EDITOR = "emacsclient -c";
home.sessionVariables.VISUAL = "emacsclient -c";
programs.zsh.envExtra = ''
export EDITOR='emacsclient -c'
export VISUAL='emacsclient -c'
'';
```

The EDITOR and VISUAL environment variables stay as 'nano' due to https://github.com/sorin-ionescu/prezto/blob/6c5657be8ef5f36054524ba171f254d5d9073e24/runcoms/zprofile#L20-L21

https://github.com/nix-community/home-manager/blob/master/modules/programs/zsh/prezto.nix#L354-L355

If I try envExtra or extraConfig.. the lines to change EDITOR and VISUAL are added to the top of the file which makes them useless as the hardcoded `EDITOR=nano` overrides it anyway :(

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.22, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"home-manager, nixos"`
 - channels(syl): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jian-lin** [comment]
Sorry my #2708 expose this issue
see https://github.com/nix-community/home-manager/issues/2751#issuecomment-1065964222

**Comment by pinpox** [comment]
https://github.com/sorin-ionescu/prezto/pull/1992 has been merged and fixes this problem, just needs an update.

**Comment by pinpox** [comment]
https://github.com/NixOS/nixpkgs/pull/168255 should fix this

**Comment by holymonson** [comment]
Would someone confirm if https://github.com/NixOS/nixpkgs/pull/167843 has fixed this?

**Comment by oati** [comment]
It was fixed for me

**Comment by pinpox** [comment]
Just updated to latest unstable branch, can confirm `EDITOR` and `VISUAL` are now correct.

**Comment by berbiche** [comment]
Thanks for resolving this issue at the source :smiley:

**Comment by Retrodynen** [comment]
Can also confirm, works perfectly for me now :)

----------------------------------------

*From: *Pablo Ovelleiro Corral ***@***.***>
*To: *nix-community/home-manager ***@***.***>
*CC: *Retrodynen ***@***.***>; Author ***@***.***>
*Date: *23 Apr 2022 12:48:17
*Subject: *Re: [nix-community/home-manager] bug: EDITOR and VISUAL are 
hardcoded when using prezto+zsh (Issue #2739)
