### ISSUE TITLE
Module overriding inside `home.nix` (e.g. through `imports` and `disableModules`)

### ISSUE THREAD

**Issue by ShamrockLee** [nix-community/home-manager#2740]
### Description

I haven't found a way to override the Home Manager modules for standalone without dilect patching to the home-manager source tree.

If is a modular way to override the modules, just as what `imports = [ "path/to/foo", ... ];` and `disableModules = [ `bar/baz`, ... ]` do on NixOS, is available in Home Manager, users will be able to get modules from multiple sources, and module testing will be a piece of cake.

Without such mechanism, changse such as #2718 will be untestable without switching the source branch.

**Comment by berbiche** [comment]
Hi,

Home Manager supports the `disabledModules` feature of NixOS.

For instance, to disable the `swayidle` service, you can set `disabledModules = [ "services/swayidle.nix" ]`.

The `modulesPath` functionality that allows using `disabledModules` was added in October and is only available in the "master" branch currently.

See:
- https://github.com/nix-community/home-manager/commit/099cbcf13e8219f07b493980a66fe64df0e32d09
- https://github.com/nix-community/home-manager/commit/fd2f746016e3d99bdc3c86736d30f2ca7594929a

**Comment by ShamrockLee** [comment]
@berbiche I mean supporting `imports`, `disableModules` or similar functionality to override modules **inside the Home Manager Configuratio (`home.nix`)**.

Stand-alone installation cannot make use of the NixOS and nix-darwin feature so far.

**Comment by berbiche** [comment]
Hi again @ShamrockLee,

I've looked at our module code once more and the `disabledModules` feature should work.
The attribute `modulesPath` (used by the modules system to support `disabledModules`) is correctly exported in a standalone Home Manager configuration.

**Comment by ShamrockLee** [comment]
But I get this:

```
error: The option `disableModules' does not exist. Definition values:
       - In `<unknown-file>': [ ]
(use '--show-trace' to show detailed location information)
```

after having

```
{ config, lib, pkgs, ... }:
{
  disableModules = [
  ];

  # Something else ...
}
```

BTW, the Home Manager is set up as a flake (the way I documented it in the manual). Not sure if it causes any difference:
https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone

**Comment by berbiche** [comment]
@ShamrockLee You used `disableModules` instead of `disabledModules`, you are missing a "d".

**Comment by ShamrockLee** [comment]
Oops! Sorry for the typo, and thanks a lot for your patience!

The problem is now solved.
