### ISSUE TITLE
bug: makeWrapper breaks on LUA_PATH/LUA_CPATH affecting neovim package

### ISSUE THREAD

**Issue by ashinkarov** [nix-community/home-manager#2754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have recently updated nixos and home manager, and the propagation of lua paths that was added in #2617 stopped working.

Versions:
```shell
$ nixos-version
22.05pre356180.d5f23787297 (Quokka)
$ home-manager --version
22.05 # I am on commit 0b1745b4ef4c3
```

The essence of the problem boils down to the following.  When I compute lua paths that I need to propagate into neovim's environment, I end up with the following expressions:
```shell
$ nix repl
Welcome to Nix 2.7.0pre20220127_558c4ee. Type :? for help.

nix-repl> a = import <nixpkgs> { }

nix-repl> a.lib.concatMapStringsSep ";" (a.pkgs.lua51Packages.getLuaCPath) [ a.lua51Packages.luautf8 ]
"/nix/store/vd8vp5hrdzqk7wv6r0r05660j87iiigd-lua5.1-luautf8-0.1.3-1/lib/lua/5.1/?.so"

nix-repl> a.lib.concatMapStringsSep ";" (a.pkgs.lua51Packages.getLuaPath) [ a.lua51Packages.luautf8 ]
"/nix/store/vd8vp5hrdzqk7wv6r0r05660j87iiigd-lua5.1-luautf8-0.1.3-1/share/lua/5.1/?.lua;/nix/store/vd8vp5hrdzqk7wv6r0r05660j87iiigd-lua5.1-luautf8-0.1.3-1/share/lua/5.1/?/init.lua"
```
These `?` in LUA_PATH/LUA_CPATH kill the makeWrapper!  When I pass these via `--prefix` command, the script simply does not generate anything.

I figured out a workaround for now (which I'll submit as a PR), but if anyone has an idea on a proper fix, I'd be very interested.  Also, should this be reported to whoever maintains the `make-wrapper.sh` script?  Who would that be?

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.101, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - channels(tema): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
See: https://github.com/NixOS/nixpkgs/pull/159394

**Comment by ashinkarov** [comment]
Thanks, @berbiche.  It is good that the problem is already reported.

**Comment by sumnerevans** [comment]
For tracking progress: https://nixpk.gs/pr-tracker.html?pr=159394

**Comment by berbiche** [comment]
Closing this issue since I believe it has been fixed.

Feel free to reopen if it's not the case.
