### ISSUE TITLE
Is using nixfmt a good idea?

### ISSUE THREAD

**Issue by schuelermine** [nix-community/home-manager#2758]
Nixfmt doesn’t support antiquotations in paths.

**Comment by rycee** [comment]
I'm super happy about nixfmt, it has helped me maintain my sanity when handling PRs. So I would be very reluctant to change it.

About the specific feature you miss, I guess it is corresponding to https://github.com/serokell/nixfmt/issues/84? If so, hopefully @Lucus16 will have a chance to fix it. I might make an attempt myself but I fear it would take me quite a while to find the time.

**Comment by SuperSandro2000** [comment]
and has problems parsing numbers https://github.com/serokell/nixfmt/issues/85 https://github.com/serokell/nixfmt/issues/86 . The development of it is not very active and recent features are not available.

**Comment by yorickvP** [comment]
We are working on the numbers, path quotations and string escapes. I hope nobody uses these numbers in practice. AFAIK, the path quotations aren't yet nixpkgs-approved either, but they probably will be in the future.

**Comment by schuelermine** [comment]
@yorickvP I see, I didn’t know the path quotations weren’t yet used that widely. (nixpkgs-fmt handles them)
I also like nixfmt!

**Comment by yorickvP** [comment]
We've released nixfmt 0.5.0, which supports path quotations :).

**Comment by schuelermine** [comment]
Thank you! I’m gonna close this as I don’t see any other issues.

**Comment by rycee** [comment]
@yorickvP Much appreciated! We can update to 0.5.0 in HM once it hits Nixpkgs unstable.
