### ISSUE TITLE
bug: fontconfig error, no config file

### ISSUE THREAD

**Issue by phdcybersec** [nix-community/home-manager#2771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When installing fonts via Home Manager, and enabling `fonts.fontconfig`, any interaction with fontconfig yields the following error: 
```
Fontconfig error: Cannot load default config file: No such file: (null)
```

I assume it has to do with the fact that `/etc/fonts/` does not exist, and neither `FONTCONFIG_FILE` nor `FONTCONFIG_PATH` is set. 

Here is an excerpt of my `home.nix`:
```nix
  home.packages = with pkgs; [
    # tex
    tectonic
    texlive.combined.scheme-full

    # fonts
    fontconfig
    gyre-fonts
    (nerdfonts.override { fonts = [ "FiraCode" ]; })
  ];  

  fonts.fontconfig = {
    enable = true;
  };

```

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.1`
 - channels(<redacted>): `"home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by phdcybersec** [comment]
While the issue is still present, I have no further information to provide.

Thus, as recommended by the stale-bot, I'll close the issue for now. If someone encounters it in the future, do not hesitate to reopen it, I'll try my best to participate in its resolution.

**Comment by eamreyes** [comment]
I experienced the same issue. After enabling `fontconfig` in `home.nix` I still experienced the issue. I added the the environment variable `FONTCONFIG_PATH` and pointed it at the `fontconfig` file that HM generated under the `~/.config/fontconfig` folder.

**Comment by phdcybersec** [comment]
Thanks, I'll make sure to test that as soon as possible. Should this environment variable be defined in the package's expression?

**Comment by augustebaum** [comment]
Also having this issue.
