### ISSUE TITLE
xdg.desktopEntires.<name> needs a groups section

### ISSUE THREAD

**Issue by Denommus** [nix-community/home-manager#2777]
### Description

When I define an Actions attribute under settings, I need to be able to create a group corresponding to each Action available. For instance, if I want to create a custom steam.desktop, I need
```nix
{
Actions = "Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;";
}
```

But, because of that, now I'd need something like the following in the generated .desktop file
```desktop
[Desktop Action Store]
...

[Desktop Action Community]
...

[Desktop Action Library]
...
```

And etc

Currently, that's no longer possible with xdg.desktopEntries. Before, I could do it with `extraConfig`, but now that has been removed.

**Comment by berbiche** [comment]
Hi,

I opened a PR that resolves your issue, see #2778.
