### ISSUE TITLE
bug: xdg.desktopEntries stopped building

### ISSUE THREAD

**Issue by Grawp** [nix-community/home-manager#2782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm using home-manager from flake.
- home-manager is locked at rev afe96e7433c513bf82375d41473c57d1f66b4e68
- nixpkgs are locked at rev 2ebb6c1e5ae402ba35cca5eec58385e5f1adea04 and nixpkgs used by home-manager are the same

I have
```
    xdg.desktopEntries = {
      fstl = {
        name = "fstl";
        exec = "fstl %f";
        mimeType = [ "model/stl" ];
      };
    };
```

in my configuration and it had been working fine until recently. Now it yields:

```
error: anonymous function at /nix/store/0zkxkjl7jzbkfwdxpw3rilwf831w5qpq-source/pkgs/build-support/make-desktopitem/default.nix:4:1 called with unexpected argument 'extraConfig'

       at /nix/store/k3rwpzlr5d73kfn4vzv9cp77s1j78ffn-source/modules/misc/xdg-desktop-entries.nix:144:5:

          143|   makeFile = name: config:
          144|     pkgs.makeDesktopItem {
             |     ^
          145|       inherit name;
```
Commenting out the whole `xdg.desktopEntries` section above makes it build again.

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.16.11, NixOS, 21.11 (Porcupine)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.4`
- nixpkgs: `/nix/store/p2mbs4mixfskbhp3wf045pi2ssd263ai-source`
```

**Comment by berbiche** [comment]
Hi,

This was fixed in e58a7cb13d5d870550888cdc6fe92154efd9e571.

**Comment by Grawp** [comment]
Hm.. but I'm on a newer revision.

**Comment by Grawp** [comment]
I do apologize. I was using `home-manager/master` with `nixpkgs/nixos-21.11`

**Comment by berbiche** [comment]
Sorry, I replied to quickly. You will have to either revert to a version of Home Manager before this commit or update your Nixpkgs version.
Unfortunately Home Manager often has to be upgraded in lockstep with Nixpkgs.

**Comment by DanielSiepmann** [comment]
Just for proper linking, so others might find related issues more easily: #2767
