### ISSUE TITLE
bug: password-store installed from nixpkgs has no zsh completions

### ISSUE THREAD

**Issue by permezel** [nix-community/home-manager#2802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Running macOS.  The `zsh` I use is the system one: `/bin/zsh`.
Using `password-store` (`pass`) installed from `nixpkgs`.
Command completion does not work. 
```zsh
sloth% nix-env -q | grep pass
password-store-1.7.4
sloth% pass ls Au<TAB>
Completing `file' or `corrections'
```
Prior version of `pass` was from `brew` and this worked.  I no longer use `brew` and just recently removed it all and that is about when the command completion stopped working.

```zsh
sloth% find ~/.nix-profile/. | grep pass
/Users/dap/.nix-profile/./bin/pass
/Users/dap/.nix-profile/./libexec/gpg-preset-passphrase
/Users/dap/.nix-profile/./lib/password-store
/Users/dap/.nix-profile/./share/man/man1/gpg-preset-passphrase.1.gz
/Users/dap/.nix-profile/./share/man/man1/pass.1.gz
/Users/dap/.nix-profile/./share/emacs/site-lisp/password-store.el
/Users/dap/.nix-profile/./share/fish/vendor_completions.d/pass.fish
/Users/dap/.nix-profile/./share/bash-completion/completions/pass
```

### System information

```markdown
sloth% nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - channels(dap): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

sloth%
```

**Comment by permezel** [comment]
Im not sure why I opened this bug here --- google lead me here, but now that I look at the site, I am not sure it was correct.

**Comment by berbiche** [comment]
Hi,

Can you specify how `password-store` is installed on your system (i.e. `nix-env`, Home Manager or nix-darwin)?

If the package is not installed through Home Manager's `home.packages`, then the completion will not be available.
If the package is installed with nix-darwin's `environment.systemPackages`, you also need to set `environment.pathsToLink = [ "/share/zsh" ]`

**Comment by permezel** [comment]
> Hi,
> 
> Can you specify how `password-store` is installed on your system (i.e. `nix-env`, Home Manager or nix-darwin)?
> 
> If the package is not installed through Home Manager's `home.packages`, then the completion will not be available. If the package is installed with nix-darwin's `environment.systemPackages`, you also need to set `environment.pathsToLink = [ "/share/zsh" ]`

**Comment by berbiche** [comment]
The reason completions for package installed with `nix-env` do not work, is because your shell does not know where to load completions for this package from.

In a usual Linux distribution, the completion files would be added to a global path, but with Nix this path is in the nix store.

Home Manager, nix-darwin and NixOS have logic to resolve this issue by making a path that contains all the completion files and exposing this path in the right environment variable for your shell.

I advise against using `nix-env` to install packages because it leads to those kind of problems.
