### ISSUE TITLE
bug: sway systemd integration is imperfect (breaking things at times)

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#2806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I've got some changes staged up for sway and friends but wanted to file an issue for visibility and to make sure I don't forget these fixes on some fork.

Particularly, `systemctl --user import-environment` should be replaced with `dbus-update-activation-environment --systemd`. I've also seen some issues with how the target binding works that causes some services to not be restarted if you restart the sway target, instead requiring that the user restart both the sway and graphical-session targets.

I do have fixes for most of this stuff.

**Particularly** the environment fix will make GCR/pinentry-gnome3 actually reliable. As-is today, if you start sway, then stop sway, and start it again, pinentry will likely not work or will fall back to curses.

Finally, I think we should:
- encapsulate `sway` itself in a systemd --user unit, bound to the graphical session target
- have `sway-start` that invokes `systemctl --user start graphical-session.target`, maybe it warns if it's already running and tries to suggest which tty to switch to
- have `sway-stop` that invokes `systemctl --user stop graphical-session.target`

I want this because:
- I keep catching stale env vars or sockets lying around. systemd is great at handling these things, we should leverage it

I suspect that maybe the dbus environment issue may very likely have to do with why many users have opted to not use it (yet?).

### System information

```markdown
n/a
```

**Comment by berbiche** [comment]
Something relevant to the discussion: https://github.com/alebastr/sway-systemd

**Comment by colemickens** [comment]
Thanks yeah, I actually have looked at that, and this one is more aligned with what I've described https://github.com/xdbob/sway-services
