### ISSUE TITLE
bug: mkOutOfStoreSymlink does not work well when inside function

### ISSUE THREAD

**Issue by marcosrdac** [nix-community/home-manager#2810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I usually automate linking of files in home-manager with:

```nix
xdg.configFile."lf/lfrc".source = config.lib.file.mkOutOfStoreSymlink "${dotConfig}/lf/lfrc";
```

This way my config for `lf` is a link to the store, but such store file is links back to my dotfiles directory. This allows me to edit the config file from `~/.config` instead of having to edit my dotfiles and do a `home-manager switch` everytime I want to modify it.

In order to link several files in a directory I think the following is logical:

```nix
linkChildren = dir: linkdir: builtins.listToAttrs (
  map (filename: {
    name = "${linkdir}/${filename}";
    value = { source = config.lib.file.mkOutOfStoreSymlink "${dir}/${filename}"; };
  }) (builtins.attrNames (builtins.readDir dir)));
```

so that then I could do:

```nix
xdg.configFile = { ... } // (linkChildren ./dotConfig "${config.xdg.configHome}/lf");
```

But for some reason, the children links (i.e., `.config/lf/lfrc`) point to the nix store this way (not to my dotfiles, as expected from the lone example above).

Why is that? Am I missing something here?

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.105, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(marcosrdac): `""`
 - channels(root): `"nixos-21.11.335820.521e4d7d13b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by polykernel** [comment]
IIRC, antiquotation on a path will cause it copied to the Nix store. In your linkChildren function, `dir` is a path so the result of `"${dir}/${filename}"` is a string representing the path to the source `dir` in the Nix store rather than the original path.

**Comment by marcosrdac** [comment]
It makes total sense. Do you know any way to avoid the behaviour and treat dir as a path, if the dir argument is still passed as a string?

**Comment by polykernel** [comment]
Apologies for the late response. I believe `readDir` accept string representation of nix paths so you can pass `dir` as string by wrapping the parameter in `toString` at the call site. Alternatively can replace `${dir}` with `${toString dir}` in the function definition and it should work regardless whether `dir` is a string or a path.

```nix
linkChildren = dir: linkdir: builtins.listToAttrs (
  map (filename: {
    name = "${toString linkdir}/${filename}";
    value = { source = config.lib.file.mkOutOfStoreSymlink "${toString dir}/${filename}"; };
  }) (builtins.attrNames (builtins.readDir dir)));
```

**Comment by marcosrdac** [comment]
@polykernel thank you for your trial. For some reason, now not even my first example (`xdg.configFile."lf/lfrc".source = config.lib.file.mkOutOfStoreSymlink "${dotConfig}/lf/lfrc";`) is creating out of store links anymore. Then every other variation of it is not working, including yours. I am trying to figure out why it happened, and I will come back here when I discover it :S

**Comment by marcosrdac** [comment]
This function was working for me, if anyone is having the same problem I had:

```nix
linkChildren = dir: linkdir: let
  pathInDrv = path: let
      splitPath = pkgs.lib.strings.splitString "/" (builtins.toString path);
    in
      (builtins.concatStringsSep "/" (pkgs.lib.lists.sublist 4 ((builtins.length splitPath) - 4) splitPath));
in builtins.listToAttrs (
  map (filename: {
    name = "${linkdir}/${filename}";
    value = with config.lib.file; {
      source = mkOutOfStoreSymlink "${config.xdg.configHome}/nixpkgs/${pathInDrv dir}/${filename}";
    };
  }) (builtins.attrNames (builtins.readDir dir)));
```

In practice I discovered a better way of managing my scripts with writeScriptBin, so I am not using it anymore.

Thank you all for your assistance!
