### ISSUE TITLE
Fish completions fail for missing attribute 'name'

### ISSUE THREAD

**Issue by stopbystudent** [nix-community/home-manager#2813]
After a recent update of my nixpkgs (unstable channel), home-manager will not rebuild anymore if I enable fish. Error message as follows:

```
error: attribute 'name' missing

       at /nix/store/wfgrdl7b24fxwb2rqw7nz1x8wd5fk3ch-source/modules/programs/fish.nix:308:30:

          307|         generateCompletions = package:
          308|           pkgs.runCommand "${package.name}-fish-completions" {
             |                              ^
          309|             src = package;
```

My suspicion is that the code at

https://github.com/nix-community/home-manager/blob/835797f3a4a59459a316ae8d4ab91fa59faf61a4/modules/programs/fish.nix#L307-L313

relies too much on the `name` attribute which often is replaced by `pname` and `version`, as seems to be the case in [nixpkgs' definition for fish](https://github.com/NixOS/nixpkgs/blob/19d4f7dc485f74109bd66ef74231285ff797a823/pkgs/shells/fish/default.nix#L135-L137). I have seen that the `stdenv` checker does use a `getName` function to retrieve the package name (see [here](https://github.com/NixOS/nixpkgs/blob/19d4f7dc485f74109bd66ef74231285ff797a823/pkgs/stdenv/generic/check-meta.nix#L10)) but that might be overkill since seemingly only the module here is affected.

I'm not entirely sure (and can't test at the moment) but maybe using `pkgs.runCommand "${package.pname}-${package.version}-fish-completions"` instead of the current `package.name` would already be enough?

Edit: Actually, it seems that not all packages have `pname` either, so I just tried running with the following snippet

```nix
        generateCompletions = let
          getName = attrs: attrs.name or ("${attrs.pname or "«name-missing»"}-${attrs.version or "«version-missing»"}");
        in package:
          pkgs.runCommand "${getName package}-fish-completions" {
            src = package;
            nativeBuildInputs = [ pkgs.python2 ];
            buildInputs = [ cfg.package ];
            preferLocalBuild = true;
          } ''
            mkdir -p $out
            if [ -d $src/share/man ]; then
              find $src/share/man -type f \
                | xargs python ${cfg.package}/share/fish/tools/create_manpage_completions.py --directory $out \
                > /dev/null
            fi
          '';
```

and it at least solved my issue. I don't know whether this is a good place to insert such a `getName` function (taken from the source linked above) or whether it should be imported somehow, hence I won't prepare a PR.

**Comment by berbiche** [comment]
Hi,

The assumption in Home Manager's logic is that the `name` attribute is always set on a derivation.

Using the primitive `builtins.derivation { }` gives an error if the `name` attribute is not specified.

I don't think there's anything to fix on our side though I might be wrong. If you think so, a PR is welcome!

**Comment by stopbystudent** [comment]
As I have described in the issue, this assumption does not hold. Sometimes there's only `pname` and `version`, sometimes only `name`. The function from the issue description solved my issue after a home-manager update broke my config. If you don't want to include it, that's fine, I'll keep it in my personal fork.

I would prepare a PR if I knew this affected only the fish completions. But if this is a general assumption that does not hold which spreads throughout the codebase I'm not sure a PR to change it at this place would justify the inconsistencies. So I guess, I'll leave it at this status quo.

**Comment by rycee** [comment]
FWIW there is a function getName in Nixpkgs. See https://github.com/NixOS/nixpkgs/blob/7d6954d8dfd68f47b5c8fe803a47959a3423c4ab/lib/strings.nix#L614-L629

**Comment by Xervon** [comment]
I just noticed the following issue in nixpkgs: https://github.com/NixOS/nixpkgs/issues/103997
It seems like the plan for the future is for packages to have pname+version instead of name so using either getName or at least falling back to pname+version seems reasonable.

**Comment by rycee** [comment]
I think it wouldn't be controversial to create a PR that changes the module to use Nixpkgs' `getName` so you should absolutely feel free to try it out and open a PR if it work well for you.

I'll reopen this issue for now.
