### ISSUE TITLE
bug: man page duplicates option names into beginning of option description text

### ISSUE THREAD

**Issue by dtzWill** [nix-community/home-manager#2820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The man page for `home-manager` against latest Nixpkgs repeats the option names into the text, without even the courtesy of a space :).

Here's what I mean, from manpages built against current unstable with something like:

```console
$ man $(nix-build -A docs.manPages -I nixpkgs=channel:nixos-unstable)/share/man/man5/home-configuration.nix.5
```

looks like: (copied from terminal running above command)
```
       accounts.email.accounts
           accounts.email.accountsList of email accounts.

           Type: attribute set of submodules

           Default: { }
```

Where the correct output can be found from using effectively this command to build against 21.11:
```console
$ man $(nix-build -A docs.manPages -I nixpkgs=channel:nixos-21.11)/share/man/man5/home-configuration.nix.5
```

which produces:

```
       accounts.email.accounts
           List of email accounts.

           Type: attribute set of submodules

           Default: { }
```

---

This is no good, and is surprisingly effective at making the manual hard to read :grin: :cry: .

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.16.15, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - channels(will): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
I can reproduce the bug.

The issue is in the [nmd project](https://gitlab.com/rycee/nmd) that generates the documentation.

**Comment by dtzWill** [comment]
Thanks for checking, and okay that makes sense.  FWIW upstream fixed it by patching the docbook style sheets, see 84d6565d52d1f9f25280f8dc1716b90238fbb738 .

**Comment by thiagokokada** [comment]
Opened a PR in the `nmd` repo: https://gitlab.com/rycee/nmd/-/merge_requests/5

**Comment by thiagokokada** [comment]
BTW, I think we also need to backport a fix to `release-22.05` at least, however this will be slightly more complicated because `release-22.05` doesn't have https://github.com/nix-community/home-manager/pull/2971, so we will need to bump the `nmd` manually here: https://github.com/nix-community/home-manager/blob/release-22.05/docs/default.nix#L8-L14

**Comment by thiagokokada** [comment]
Should be fixed now:
- `master`: https://github.com/nix-community/home-manager/commit/9550595502bf437be7eb32f312a924ec891872d1
- `release-22.05`: https://github.com/nix-community/home-manager/commit/4a3d01fb53f52ac83194081272795aa4612c2381

**Comment by rycee** [comment]
I'll close.
