### ISSUE TITLE
compress man pages

### ISSUE THREAD

**Issue by dtzWill** [nix-community/home-manager#2821]
### Text spliced from other thread/issue, originally a comment there...
(issue description written normally starts below)

As an aside, I just noticed the man pages aren't compressed?

It should be easy to do (if not just a gzip bash loop, there's a setup hook in nixpkgs for it IIRC?).

Not big deal but since it's ~44k lines (and 744K) that might be a nice little improvement :smile:.

Looking at nixpkgs quickly I don't see easy way to rig it in, if it's not already part of the derivation (via `stdenv`?)  Anyway could probably get away with something simple like `find $out/share/man -type f -execdir gzip {} +` in this case :+1: .

### Description

home-manager's man pages are not compressed, as is pretty common I think but is the norm in Nix-land anyway :).

Testing with the `home-configuration.nix.5` I have on hand (`man -w home-configuration.nix.5`, or let's use a fresh one actually),
simple gzip goes from:

```console
$ du -h ./result/share/man/man5/home-configuration.nix.5
744K	./result/share/man/man5/home-configuration.nix.5
$ wc -l ./result/share/man/man5/home-configuration.nix.5
43973 ./result/share/man/man5/home-configuration.nix.5
$ file ./result/share/man/man5/home-configuration.nix.5
./result/share/man/man5/home-configuration.nix.5: troff or preprocessor input, Unicode text, UTF-8 text, with very long lines (314)
```

to

```console
$ gzip -c ./result/share/man/man5/home-configuration.nix.5 > test.gz
$ du -h test.gz
112K	test.gz
```

Which is a verbose way of saying **744K -> 112K**, the latter being **~15%** of the original's size.  Which between CI/cache, folks having multiple generations in profiles, etc., might add up, but good just on principle anyway I think :+1: .

Unfortunately not sure how to best accomplish this, although I offer some suggestions/tips (but whatever sounds good to you :+1:) in the version I initially wrote as a comment first :innocent: .

**Comment by rycee** [comment]
Thanks for the suggestion, it is indeed a good idea to compress the man pages! Turned out to be quite easy to do so it should be fixed in master now.
