### ISSUE TITLE
Generate window manager configuration without setting the command for xsession.

### ISSUE THREAD

**Issue by rizo** [nix-community/home-manager#2825]
### Description

When working with multiple window managers installed by the global configuration, the window manager enable by home-manager will override the session and always run the user-specified configuration.

I would like to use home-manager to generate the configuration for each installed window-manager but without forcing its activation when logging in so that I can use multiple window managers.

I tried explicitly overriding the command, but it didn't work:

```
error: The option `xsession.windowManager.command' has conflicting definition values:
       - In `/nix/var/nix/profiles/per-user/root/channels/home-manager/modules/services/window-managers/i3-sway/i3.nix': "/nix/store/p48qv6srzil8hdqcxm5b8nj41k00vrz3-i3-4.20/bin/i3"
       - In `/home/rizo/Developer/Repository/rizo/nixos-config/nixpkgs/home.nix': ""
(use '--show-trace' to show detailed location information)
```

Any help with this would be appreciated.

**Comment by olmokramer** [comment]
To override the command you could use `lib.mkForce`, i.e.

```nix
{ lib, ... }:
{
  xsession.windowManager.command = lib.mkForce "";
}
```

**Comment by berbiche** [comment]
I think the suggestion by `@olmokramer` is sufficient.
I don't think adding another option is meaningful or relevant.
