### ISSUE TITLE
nushell: module will need upgrade for 0.60.0 package

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#2837]
### Description

see: https://github.com/NixOS/nixpkgs/pull/165473

see: https://www.nushell.sh/blog/2022-03-22-nushell_0_60.html#a-new-config-file

cc: @Philipp-M

**Comment by Philipp-M** [comment]
I'm not sure, if issue links in the commit were enough to trigger a github notification.

I've ported nushell to the new configuration in https://github.com/nix-community/home-manager/pull/2957, so you might want to test and probably review it
