### ISSUE TITLE
bug: `packages` command is broken

### ISSUE THREAD

**Issue by tactlessfish** [nix-community/home-manager#2844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When I run `home-manager packages`, I get the following output:
```
error: unknown flag '--outpath'
Try 'nix-env --help' for more information.
```

This seems to be introduced in https://github.com/nix-community/home-manager/commit/2f58d0a3de97f4c20efcc6ba00878acfd7b5665d, when the `nix-env` call was moved to `setNixProfileCommands`. In the process, `--out-path` was changed to `--outpath`. 

I believe this is a mistake, because according to the [docs](https://nixos.org/manual/nix/stable/command-ref/nix-env.html#operation---query) and the [source code](https://github.com/NixOS/nix/blob/master/src/nix-env/nix-env.cc#L995), the flag remains `--out-path`.

If this is indeed the issue, could I open a PR fixing it?

### System information

- system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(fisher): `"home-manager, nixpkgs-22.05pre363272.4d600814942"`
 - nixpkgs: `/Users/fisher/.nix-defexpr/channels/nixpkgs`

**Additional info**
- `nix-info` reports the system to be x86_64, but it's really M1 running with Rosetta. Probably not relevant, but just in case.
- home-manager version: 22.05

**Comment by tactlessfish** [comment]
Changing `--outpath` to `--out-path` in my local home-manager fixes this issue.
<img width="770" alt="image" src="https://user-images.githubusercontent.com/29507110/160265154-d144e603-2d03-466d-8d3b-fbc5c31422db.png">
@rycee could I open a PR?

**Comment by rycee** [comment]
Thanks for the report. I've changed the option now and hopefully it'll work ok 🙂
