### ISSUE TITLE
neovim packer support

### ISSUE THREAD

**Issue by pca006132** [nix-community/home-manager#2845]
### Description

[packer.nvim](https://github.com/wbthomason/packer.nvim) is a plugin manager that supports lazy-loading plugins (triggered through filetype/commands/events etc.) and other features. It seems widely used now for neovim (at least quite a lot of popular configurations use it?). I wonder if it is possible to support using this as plugin manager.

This plugin manager can use local plugins by specifying the plugin path, so I think this is suitable for home-manager. I've wrote a very simple nix expr to generate the config but I'm not sure how to integrate it into home-manager neovim config.

(the nix script might be too complicated as I am not familiar with nix)
<details>

```nix
{ config, lib, pkgs, ... }:
with lib;
let
  pluginWithConfigType = types.submodule {
    options = {
      plugin = mkOption {
        type = with types; either package str;
        description = "vim plugin";
      };
      filetypes = mkOption {
        type = types.listOf types.str;
        description = "load on filetypes";
        default = [ ];
      };
      cmds = mkOption {
        type = types.listOf types.str;
        description = "load on commands";
        default = [ ];
      };
      config = mkOption {
        type = types.str;
        description = "run code after load";
        default = "";
      };
      run = mkOption {
        type = types.str;
        description = "post-install/update hook";
        default = "";
      };
      opt = mkOption {
        type = types.bool;
        description = "optional";
        default = false;
      };
      requires = mkOption {
        type = with types; listOf (either package pluginWithConfigType);
        description = "requires";
        default = [ ];
      };
    };
  };
in
{
  options = {
    plugins = mkOption {
      type = with types; listOf (oneOf [ str package pluginWithConfigType ]);
      description = "plugins";
      default = [ ];
    };
    output = lib.mkOption {
      type = lib.types.str;
    };
  };
  config =
    let
      pluginsNormalized = map
        (x:
          if (x ? plugin) then
            x
          else {
            plugin = x;
          }
        )
        config.plugins;
      concatStringList = v: ''[${concatMapStringsSep ", " (x: "\"${x}\"") v}]'';
      concatList = concatStringsSep ", ";
      pluginConfig = map
        (x:
          let
            mkPluginOption = attr: name: f:
              if hasAttr attr x then
                let val = getAttr attr x;
                in
                if (isBool val && val)
                  || (isString val && val != "")
                  || (isList val && length (getAttr attr x) > 0)
                then [ "${name} = ${f (getAttr attr x)}" ] else [ ]
              else [ ];
          in
          concatList ([ "\"${x.plugin}\"" ] ++
            (mkPluginOption "filetypes" "ft" concatStringList) ++
            (mkPluginOption "cmds" "cmd" concatStringList) ++
            (mkPluginOption "config" "config" id) ++
            (mkPluginOption "run" "run" id) ++
            (mkPluginOption "opt" "opt" id))
        )
        pluginsNormalized;
    in
    {
      output = concatMapStringsSep "\n" (x: "use { ${x} }") pluginConfig;
    };
}
```

</details>

Example config:
```nix
    plugins = [ {
      plugin = "test";
      filetypes = ["a" "b"];
    } "test2" ];
```

Example output:
```
use { "test", ft = ["a", "b"] }
use { "test2" }
```

**Comment by berbiche** [comment]
Hi,

Support for Packer and other specific vim plugin managers has been requested in other neovim issues and thus far we have not been interested in adding support for them.

Nixpkgs has a lot of vim plugins packaged and automatically updated though it is not a perfect substitute for a plugin manager that can pull any dependencies.

I recommend maintaining an out-of-tree module since we will very likely not merge a pull request introducing this feature.

cc @teto

**Comment by teto** [comment]
in the issue, you dont describe the benefits over the current approach ? 
The support for different package manager in nixpkgs is the source of several issues and for no benefit (IMO). 
Some may argue that lazyloading capabilities etc are interesting but if the plugin is well designed, you may shave a few milliseconds at the expense of great complexity.

My config setups my basic plugins (the ones I always want) via nix and then I have vim-plug (historic) and packer installed plugins that I update declaratively.
You can extend home-manager via your own modules but I advocate against this upstream.

**Comment by DanielSiepmann** [comment]
One addition regarding autoloading of plugins: Neovim allows to postpone loading of plugins via its native plugin system. This is supported by home-manager already (https://github.com/nix-community/home-manager/blob/master/modules/programs/neovim.nix#L47). 

One can then use autocommands to load the plugin on demand.
As already mentioned, that is nearly never necessary as most plugins already make use of the `autoload/` feature and only load some small commands and mappings. The real loading of code is postponed until needed.
