### ISSUE TITLE
bug: wrong home directory is used when activating multiple users

### ISSUE THREAD

**Issue by rtimush** [nix-community/home-manager#2856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

If home-manager is used as a nix-darwin module to configure multiple users, all users are activated in the home directory of the current one. It seems that it happened because of switching to [sudo -s](https://github.com/nix-community/home-manager/pull/807) — it doesn't update the "$HOME" variable, and therefore activation script uses the wrong value. Maybe adding "-H" can help.

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/m2vv0bxfchzrjngx8wi0i7dhzb9q2g50-source`
```

**Comment by berbiche** [comment]
cc @toonn @kalbasit

**Comment by toonn** [comment]
Apologies, hope #2857 fixes this use case again.
