### ISSUE TITLE
error: The option `home-manager.users.teto.services.polybar.script' is used but not defined.

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#2860]
### Description
```
{ config, pkgs, lib,  ... }:
{

  services.polybar = {
	enable = true;
	# script = "polybar bar &";
  };

}
```
wiothout the `script` line I got:
```
error: The option `home-manager.users.teto.services.polybar.script' is used but not defined.
(use '--show-trace' to show detailed location information)
```
One thing I like about nixpkgs is that `enable = true;` is usually enough to get going. Any reason it's not the case here ? can we make the example the default ? Isn't there like a default polybar config ? I dont know the software, just wanted to try it out

**Comment by berbiche** [comment]
Hi,

I have just tried polybar myself recently and a script is necessary because there is no concept of a "default" bar.

Setting `polybar.enable` alone is useless because polybar does not have a default configuration.

Hence a custom script is needed to start polybar.

**Comment by teto** [comment]
I gave up on using polybar (switching status programs is costlier than I though). Thanks for the insight
