### ISSUE TITLE
bug: himalaya `passwordCommand` escaping breaks commands

### ISSUE THREAD

**Issue by huuff** [nix-community/home-manager#2864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Himalaya's module uses `lib.escapeShellArgs` to escape the `passwordCommand`. This causes my command:

```
passwordCommand = "op item get Mail --vault personal --field _pass";
```

To become:

```
imap-passwd-cmd = "'op' 'item' 'get' 'Mail' '--vault' 'personal' '--field' '_pass'"
```

Which will give an `AUTHENTICATION FAILURE`. Note that removing all single quotes fixes the command. Can't we just pass the command unchanged and let the user escape the command (since they know it's a command they're likely to do it if necessary anyway) or am I being naive?

Does anyone have a workaround for this use case?

### Maintainer CC

@ambroisie 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - channels(root): `"nixos-21.11pre297244.d2b489b24ae"`
 - channels(fran): `"home-manager, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ambroisie** [comment]
I haven't tested this (on mobile) but I'm pretty sure your command is wrong, and should instead be a list of strings: `["op" "item" ... ]`

**Comment by huuff** [comment]
Thanks for the quick response! I've tried the following:
```nix
    passwordCommand = [ "op" "item" "get" "Mail" "--vault" "personal" "--field" "_pass"];
```

But the result is the same:
```
imap-passwd-cmd = "'op' 'item' 'get' 'Mail' '--vault' 'personal' '--field' '_pass'"
```

I'm not sure whether not accepting this format is himalaya's fault, since if I run it verbatim from the cli, it works

**Comment by ambroisie** [comment]
It works on my machine, with the following configuration in `$XDG_CONFIG_HOME/himalaya/config.toml`:

```toml
imap-passwd-cmd = "'/nix/store/8z56qdy25mnd7chf1y10kmws3zadmpl5-bw-pass-0.1.0/bin/bw-pass' 'Mail' 'Migadu'"
```

(where `bw-pass` is a wrapper script for Bitwarden to use `keyctl` for caching the password).

**Comment by huuff** [comment]
Putting the full store path works, thanks!

Though I really don't know why... if `himalaya` couldn't access my `$PATH` then why does it work when the command is unquoted?

In any case, I'm closing this issue since it was my mistake and not a bug.
