### ISSUE TITLE
bug: Flameshot does not work

### ISSUE THREAD

**Issue by dschrempf** [nix-community/home-manager#2868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Not sure if this is the right place to report this (might be an upstream issue), but `flameshot` does not work.

I have `services.flameshot.enable = true;` set, and executing `flameshot full -p ~/Pictures/Temp/` leads to a weird popup stating that I "must resolve all errors before continuing". The "details" are:

```
flameshot: error: Unrecognized setting: 'setSaveAsFileExtension'

flameshot: error: Unrecognized setting: 'saveAfterCopyPath'

flameshot: error: Bad value in 'drawThickness'. Expected: number >= 1
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05.20220330.1063244`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - nixpkgs: `/nix/store/040yq8hrrylcby60md5lsipc7mz19bik-source`
```
```

**Comment by berbiche** [comment]
Hi @dschrempf,

I believe this is an issue in your configuration.
The module does not set any default configuration.

You may have an old configuration file in `$XDG_CONFIG_HOME/flameshot/flameshot.ini` with invalid settings.

**Comment by dschrempf** [comment]
Haha, thank you. I never touched this file. I would say this is an upstream bug then, which is not worth reporting. Thanks!
