### ISSUE TITLE
Readme has broken link to Rollback documentation

### ISSUE THREAD

**Issue by boxofrox** [nix-community/home-manager#2872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

In the `README.md`, the following paragraph contains a broken link:

```
See the [rollbacks](https://github.com/nix-community/home-manager#rollbacks) section for instructions on how to manually perform a rollback.
```

This section is missing.  I don't know, yet, whether it was moved or deleted.

### System information

```markdown
N/A
```

**Comment by boxofrox** [comment]
I believe I found the correct link at https://github.com/nix-community/home-manager/blob/master/docs/usage.adoc#rollbacks .

I can submit a PR if this is correct.

**Comment by rycee** [comment]
Indeed, the link was incorrect. It should point to https://nix-community.github.io/home-manager/index.html#sec-usage-rollbacks. I've updated it now, thanks for pointing it out 🙂
