### ISSUE TITLE
Make new release in `NixOS/nixpkgs` (ahead of 22.05 release)

### ISSUE THREAD

**Issue by berbiche** [nix-community/home-manager#2881]
Is there any new release in `NixOS/nixpkgs` planned? That release is really outdated (and without this patch broken now)

_Originally posted by @genofire in https://github.com/nix-community/home-manager/pull/2867#issuecomment-1093337361_

**Comment by rycee** [comment]
I've never really been involved with the package in Nixpkgs. I think it just needs a volunteer to keep it up to date. Alternatively it may be best to remove it altogether since there is no guarantee that it'll actually work with the Nixpkgs commit in which it is defined.
