### ISSUE TITLE
RFC: powershell module

### ISSUE THREAD

**Issue by ShrykeWindgrace** [nix-community/home-manager#2890]
Hi!

I wonder if there is some interest in creating a powershell (`pwsh` to be precise) HM module.

Basic functionality that looks useful:
- aliases for pwsh (it has a somewhat peculiar way to set them)
- installation of common pwsh modules like `posh-git`, `Terminal-Icons`, and `oh-my-posh`. Presumably from PSGallery, since these modules do not exist (yet) in nixpkgs/nur.
- integration for tools like `starship`, `zoxide`, `just`, etc.

I understand that the userbase of pwsh on *nix systems is vanishingly small - if there is no demand for this module, there is no need to invest time into creating that module=) If there are folks who would be interested in this functionality, I'd like to know.

What do you guys think?

**Comment by houstdav000** [comment]
I partially started to make one at one point, given I've done a lot with PowerShell, but I can't imagine it being widely used, given its lack of adoption and general incompatibility with Unix program output conventions.

Some of the most valuable things I've seen done with PowerShell were DSC-related and focused on cross-platform compatibility, and considering Nix's position, I have to wonder whether time would be better spent getting Nix to work on Windows (which in-of-itself is difficult considering a lot of Microsoft's design decisions around NTFS, DLL loading, and environment variables)...

**Comment by ShrykeWindgrace** [comment]
@houstdav000 thanks for the feedback=)

I concur that porting `nix` to windows is a daunting task and is of several order of magnitude more complex that writing a HM module to handle `pwsh`.

Since this idea seems to attract very low attention, I am inclined to drop the subject. Feel free to reopen if necessary =)

**Comment by srid** [comment]
I'd like to see this happen. Can this be reopened?
