### ISSUE TITLE
bug: starship config generated incorrectly

### ISSUE THREAD

**Issue by aranw** [nix-community/home-manager#2896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm getting a warning now from my starship config and I believe the issue is related to the way home manager encodes the config

Below is my config 
```
programs.starship.settings = {
    battery.display.threshold = 25; # display battery information if charge is <= 25%
}
```
and the generated config found in `~/.config/starship.toml` looks like 

```
[battery]
charging_symbol = ""
discharging_symbol = ""
empty_symbol = ""
full_symbol = ""
unknown_symbol = ""

[battery.display]
threshold = 25
```

Notice how the `batter.display` section has only 1 set of `[]` but when you look at https://starship.rs/config/#battery you'll notice it should have look like `[[]]`

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(aranw): `"darwin, home-manager, nixpkgs-22.05pre335126.391f93a83c3"`
 - channels(root): `"nixpkgs-21.11pre330734.5cb226a06c4"`
 - nixpkgs: `/Users/aranw/.config/nixpkgs/nixpkgs.nix`
```

**Comment by berbiche** [comment]
Hi @aranw,

It looks like the `battery.display` option is a list in the configuration.

You have to rewrite your configuration to `battery.display = [{ threshold = 25 }]`.

**Comment by aranw** [comment]
Ah okay interesting. Starship must of changed cause it wasn't giving a warning before

**Comment by aranw** [comment]
> Hi @aranw,
> 
> It looks like the `battery.display` option is a list in the configuration.
> 
> You have to rewrite your configuration to `battery.display = [{ threshold = 25; }]`.

This has resolved the warning. Must have been a change between the versions of Starship and how it parsed the config
