### ISSUE TITLE
bug: Activation script fails after `sudo` attempts to use an invalid shell

### ISSUE THREAD

**Issue by kclejeune** [nix-community/home-manager#2900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After updating my `home-manager` input to the current master branch, my activation script appears to be broken on both an intel and m1 machine:

```
setting up groups...
setting up users...
setting up ~/Applications...
applying patches...
setting up /etc...
system defaults...
setting up launchd services...
configuring networking...
configuring keyboard...
configuring fonts...
Activating home-manager configuration for kclejeune
sudo: /usr/bin/bash: command not found
```

I assume this is due to the change introduced by #807, since the failing line is:

```
sudo -u kclejeune -s --set-home /nix/store/2wb1b2kyzlfb5k6mr66di7qi0aldmq0d-activation-kclejeune
```

I've been using home-manager on both m1 and intel machines prior to this change without any activation script issues (including setup from scratch) so I don't think the issue motivating #807 is universal.

### Maintainer CC

@kalbasit @toonn 

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(kclejeune): `""`
 - channels(root): `"darwin, home-manager, nixpkgs-20.09pre228453.dcb64ea42e6"`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by toonn** [comment]
I wonder how SHELL got set to a shell that doesn't actually exist?

**Comment by kalbasit** [comment]
Does reverting #807 help? What about running the command outside of the activation? Does it work?

**Comment by kclejeune** [comment]
> Does reverting #807 help? What about running the command outside of the activation? Does it work?

Sorry I missed this. I'll try reverting on a fork and see if that resolved it.

**Comment by starcraft66** [comment]
Experiencing this as well on my macbook

**Comment by kclejeune** [comment]
> Does reverting #807 help? What about running the command outside of the activation? Does it work?

@kalbasit I have confirmed that reverting #807 resolves this issue

**Comment by kclejeune** [comment]
> I think the way forward here is figuring out why `/usr/bin/bash` pops up if that's not even available on the system.

I've never been able to reproduce the issue that motivated the original PR in the first place (seems like it definitely wasn't widespread or there would've been more than one issue about it?), so I'm thinking that the logical path forward is to revert.

**Comment by toonn** [comment]
That would be *really* unfortunate. I'd much rather see this actually fixed because getting anyone to pay attention to my issue and attempted fix in the first place was so hard.

IMO, `sudo -i` is not correct, it assumes the user's shell is set up correctly and since that shell can come from an older generation that assumption does not always hold.
My assumption that `SHELL` would be properly set in the activation script's environment apparently also doesn't hold. Maybe we can explicitly set it to a Nix-provided Bash in all activation scripts?

Seeing `sudo: /usr/bin/bash: command not found` on a system that has never had a `/usr/bin/bash` is pretty suspicious to me, if that's a sudo fallback then `SHELL` is probably unset or empty and setting it would probably be entirely harmless.

**Comment by starcraft66** [comment]
@toonn in my case it was looking for `/usr/local/bin/bash` which was probably a bash installed by homebrew (probably around 5) years ago long before I started using Nix. This `bash` obviously hasn't existed in forever but this issue just suddenly started manifesting itself after updating my inputs. I need a working computer so I just resorted to re-installing and re-linking bash via homebrew to get `/usr/local/bin/bash` to exist for the activation script to succeed. Obviously this is not a good solution at all but it should at least provide some insight.

**Comment by starcraft66** [comment]
I'm currently grepping my filesystem to find possible references to `/usr/local/bin/bash`. I have it an an entry in my `/etc/shells`:
```
# List of acceptable shells for chpass(1).# Ftpd will not allow users to connect who are not using# one of these shells./bin/bash
/bin/csh
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/usr/local/bin/bash
/etc/profiles/per-user/tristan/bin/zsh
```
I also see thousands of lines of spam relating to it in some log files:
```
/var/log/weekly.out
9:su: /usr/local/bin/bash: No such file or directory
14:su: /usr/local/bin/bash: No such file or directory
19:su: /usr/local/bin/bash: No such file or directory
24:su: /usr/local/bin/bash: No such file or directory
29:su: /usr/local/bin/bash: No such file or directory
```
It's not present as any user's shell in `/etc/passwd`.

**Comment by starcraft66** [comment]
Okay, wow I found the problem:

I suspected `/etc/passwd` was not to be trusted on macOS because it has its own facilities to manage users. I ran `dscacheutil -q user` which confirmed exactly what I was suspecting:
```
[...]
name: root
password: *
uid: 0
gid: 0
dir: /var/root
shell: /usr/local/bin/bash
gecos: System Administrator
[...]
```
So, I changed the shell back to the default zsh installation from Apple:
```
@NightmareMoon:~/s/iac-k8s (main) ❯ sudo dscl . -change /Users/root UserShell /usr/local/bin/bash /bin/zsh                     
@NightmareMoon:~/s/iac-k8s (main) ❯ dscl . -read /Users/root UserShell                                                         
UserShell: /bin/zsh
```
Unlinked bash:
```
@NightmareMoon:~/s/iac-k8s (main) ❯ brew unlink bash                                                                           
Unlinking /usr/local/Cellar/bash/5.1.16... 48 symlinks removed.                                                                
@NightmareMoon:~/s/iac-k8s (main) took 22s ❯ file /usr/local/bin/bash                                                          
/usr/local/bin/bash: cannot open `/usr/local/bin/bash' (No such file or directory) 
```
Then ran `darwin-rebuild`:
```
@NightmareMoon:~/s/iac-k8s (main) ❯ z os                                                                                       
direnv: loading ~/src/iac-infra/.envrc                                                                                         
direnv: using flake                                                                                                            
direnv: nix-direnv: using cached dev shell
[...]
@NightmareMoon:~/s/os-config (master) [$!?] ❯ darwin-rebuild switch --flake '.#NightmareMoon'
[...]
ctivating home-manager configuration for tristan                                                                              
Starting Home Manager activation                                                                                               
Sanity checking Nix                                                                                                            
Sanity checking oldGenNum and oldGenPath                                                                                       
This is a live run                                                                                                             
Using Nix version: nix-env (Nix) 2.4                                                                                           
Activation variables:
  oldGenNum=21
  oldGenPath=/nix/store/k5hkrqmyyazbhh08m4hrbzkk3j5ycl9p-home-manager-generation
  newGenPath=/nix/store/k5hkrqmyyazbhh08m4hrbzkk3j5ycl9p-home-manager-generation
  newGenNum=22
  newGenGcPath=/nix/var/nix/gcroots/per-user/tristan/current-home
  genProfilePath=/nix/var/nix/profiles/per-user/tristan/home-manager
Activating checkFilesChanged
Activating checkLaunchAgents
Activating checkLinkTargets
Activating writeBoundary
Activating copyFonts
[...]
```
Success!

**Comment by toonn** [comment]
@kclejeune, are you on macOS too? Do you have `/usr/bin/bash` in `/etc/shells`?

**Comment by kclejeune** [comment]
> @kclejeune, are you on macOS too? Do you have `/usr/bin/bash` in `/etc/shells`?

I'm on an m1 mac but don't have /usr/bin/bash or /usr/local/bin/bash in /etc/shells. My system was set up from scratch and all shell config is managed with nix, so there must be something else here?

**Comment by toonn** [comment]
@kclejeune, what is your `UserShell` set to?

```dscl . -read /Users/root UserShell```

**Comment by kclejeune** [comment]
> @kclejeune, what is your `UserShell` set to?
> 
> `dscl . -read /Users/root UserShell`

@toonn here's that command

```
❯ dscl . -read /Users/root UserShell
UserShell: /bin/sh
```

and also my `/etc/shells`

```
❯ cat /etc/shells
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh

# List of shells managed by nix.
/run/current-system/sw/bin/bash
/run/current-system/sw/bin/zsh
/run/current-system/sw/bin/fish
```

**Comment by starcraft66** [comment]
I would auggest grepping `/etc` and `/var` as root for mentions of `/usr/bin/bash` to try and find clues as to what is going on.

**Comment by kclejeune** [comment]
> I would suggest grepping `/etc` and `/var` as root for mentions of `/usr/bin/bash` to try and find clues as to what is going on.

@starcraft66 just checked both of them again to confirm, `/usr/bin/bash` doesn't appear in either one.

**Comment by kclejeune** [comment]
@toonn That shows the default `/bin/zsh` for my user:

```
❯ dscl . -read /Users/kclejeune UserShell
UserShell: /bin/zsh
```

Both `$SHELL` variables show this as well:

```
❯ echo $SHELL
/bin/zsh

❯ sudo su
sh-3.2# echo $SHELL
/bin/sh
```

Based on the man-page description, I'm even less convinced that `-s` is the right value to use here. I don't want nix activation scripts to be influenced by impure factors in my system, and the fact that an apparent difference in `$SHELL` is enough to derail an activation script is precisely the type of behavior that I use nix to avoid. 

Regardless of _why_ `$SHELL` is evaluating this way, this issue is reproducible with clean installation on a machine that has only been managed by nix, home-manager, and nix-darwin, which makes for a terrible UX and feels like a huge show-stopper to me.

@toonn Could you confirm whether your original failure was on a clean installation of macOS?

**Comment by kclejeune** [comment]
@toonn @starcraft66 Interestingly enough, the macOS 12.4 update seems to have resolved this issue. As far as I can tell nothing has changed? 

I still think this case warrants some discussion, especially as it concerns a potential failure when bootstrapping new systems that might not be on 12.4.

**Comment by toonn** [comment]
It wasn't a clean install. I can't go around trying to find macOS ISO's to get a clean install rather than just using Apple's system updates unfortunately.

HM is (or should be?) completely in control of the environment it runs activation scripts in so this seems like it shouldn't be a problem. What HM is *not* in control of is the login shell specified for the user. So I think we're in agreement, we should not let outside factors influence the shell used for sudo invocations. `sudo -i` is not the solution. `sudo -s` is closer but we should figure out why you were getting a non-existent shell.

@kclejeune, current hypothesis, `SHELL` is unset at the time of this call, therefore `sudo -s` falls back to using `/bin/sh`, somehow this is actually a symbolic link to `/usr/bin/bash`?

I'm not sure how to check this though. `/bin/sh` on my system is in fact a Bash but it doesn't look like it's a link. I also don't think the `/bin/sh` Nix provides would be a  symlink to `/usr/bin/bash`, surely it would link to a Bash in the store. So this hypothesis doesn't really explain anything *but* anyone running into this issue could make sure their `/bin/sh` isn't a symlink, I guess.

Looks like further troubleshooting is thwarted by the system update for now though? : s

Either way, I think setting the variable for the sudo invocation should be perfectly fine, `SHELL=${nix_bash} sudo -s ...`? I'll look into whether `SHELL` is set at this point and PR this as a potential fix.

**Comment by kclejeune** [comment]
Yeah, maybe if someone sees this and hasn't done the 12.4 update they can troubleshoot further? Either way, definitely agree that setting $SHELL more explicitly during activation is still a good bet. 

I can close this since my particular issue seems to be resolved, or leave it open for visibility in case someone is able to troubleshoot? I'm good with either.

**Comment by toonn** [comment]
I'm in favor of keeping it open. Closed  issues tend to be neglected. But I'm not a maintainer so I'll defer to their wisdom.

**Comment by kclejeune** [comment]
> I'm in favor of keeping it open. Closed  issues tend to be neglected. But I'm not a maintainer so I'll defer to their wisdom.

Coming back to this quick - I received a new machine at work and ran into this issue again on a clean install of 12.4. The dscl -change fix worked, but I figured it's worth noting here that the default is still /usr/bin/bash for some reason.
