### ISSUE TITLE
Fish should use Python 3

### ISSUE THREAD

**Issue by rycee** [nix-community/home-manager#2910]
Currently the fish module depends on Python 2 but it seems like the [create_manpage_completions.py script](https://github.com/fish-shell/fish-shell/blob/7489ab9d5bcd7b256d53026a5ef0fd78def8278d/share/tools/create_manpage_completions.py#L1) supports Python 3. Perhaps it would be possible to also switch in the HM module?

@hyperfekt could you help see if it's possible to do the switch to Python 3?

**Comment by hyperfekt** [comment]
The nixpkgs version already uses Python 3 so it should be possible with no issue.
