### ISSUE TITLE
bug: `home-manager switch` always fail because of Emacs service

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#2913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have 

```nix
{
  services.emacs = {
    enable = true;
    defaultEditor = true;
    # Start Emacs immediately, don't wait for me to ask for it:
    socketActivation.enable = false;
  };
}
```

Most of the time, when I execute `home-manager switch`, I get a failure:

```
$ home-manager switch
...
Creating home file links in /home/cassou
Activating onFilesChange
Activating reloadSystemd
Starting: emacs.service
^[[BJob for emacs.service failed because the control process exited with error code.
See "systemctl --user status emacs.service" and "journalctl --user -xeu emacs.service" for details.

● emacs.service - Emacs text editor
     Loaded: loaded (/home/cassou/.config/systemd/user/emacs.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2022-04-24 17:07:35 CEST; 5ms ago
       Docs: info:emacs
             man:emacs(1)
             https://gnu.org/software/emacs/
    Process: 159535 ExecStart=/nix/store/bcwyhqvik6jhcklib33v6kykdl4zp9d4-bash-5.1-p8/bin/bash -l -c /nix/store/090ibnyvrlhba668yv4bspf>   Main PID: 159535 (code=exited, status=1/FAILURE)
        CPU: 15.848s

$ echo $?
1
```

This means home-manager won't finish its job and just stop at restarting Emacs.

Because I use Emacs for nearly everything (including as a terminal to execute `home-manager switch`), I don't want home-manager to kill Emacs.

Should I stop using home-manager to define emacs.service?

### Maintainer CC

/cc @tadfisher @schotts-fired @rvl 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.16.20-200.fc35.x86_64, Fedora Linux, 35 (Workstation Edition)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.4`
- channels(root): `""`
- nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`
```

**Comment by rycee** [comment]
After the failed activation, does `systemctl --user status emacs.service` say anything useful? If it fails I hope something shows up in the service log. I use Emacs myself but not the daemon so I haven't encountered this.

**Comment by tadfisher** [comment]
Does the systemd module support `restartIfChanged` like NixOS? That's used to prevent restarting the desktop/display manager service on the NixOS side.

**Comment by rvl** [comment]
There's a special `X-RestartIfChanged` property set on the systemd service which is supposed to prevent emacs from being restarted by the activation script. It seems to work for me, but I use socket activation.

The log excerpt above suggests to me that `emacs.service` is started because it wasn't running at the time of activation.

**Comment by DamienCassou** [comment]
> After the failed activation, does systemctl --user status emacs.service say anything useful?

doesn't seem like it:

```
$ systemctl --user status emacs.service
● emacs.service - Emacs text editor
     Loaded: loaded (/home/cassou/.config/systemd/user/emacs.service; enabled; vendor preset: disabled)
     Active: activating (start) since Wed 2022-04-27 06:26:19 CEST; 15s ago
       Docs: info:emacs
             man:emacs(1)
             https://gnu.org/software/emacs/
   Main PID: 49390 (.emacs-28.1-wra)
      Tasks: 3 (limit: 38047)
     Memory: 112.8M
        CPU: 14.566s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/emacs.service
             ├─49390 /nix/store/kl4cfpy6x57hd2mqh8n3rbn21is5n0y7-emacs-native-comp-28.1/bin/emacs --fg-daemon
             └─49428 /nix/store/aznvi6xpdhqhcsi81iwccjay9047276s-emacs-packages-deps/share/emacs/site-lisp/elpa/emacsql-sqlite-20220218>
```

But it seems that I now have several instances of Emacs running:
```
$ pgrep -a emacs
9470 /nix/store/...-emacs-native-comp-28.1/bin/emacsclient --alternate-editor= --create-frame
9472 /nix/store/...-emacs-native-comp-28.1/bin/emacs --daemon
9488 /nix/store/...-emacs-packages-deps/share/emacs/site-lisp/elpa/emacsql-sqlite-20220218.1543/sqlite/emacsql-sqlite /home/cassou/.emacs.d/var/org/org-roam.db
50147 /nix/store/...-emacs-native-comp-28.1/bin/emacs --fg-daemon
```

Given that the service passes `--fg-daemon` to Emacs, I have no clue why I see a `emacs --daemon` in my processes.

Here is what the service looks like:
```ini
# /home/cassou/.config/systemd/user/emacs.service
[Install]
WantedBy=default.target

[Service]
ExecStart=/nix/store/…-bash-5.1-p8/bin/bash -l -c "/nix/store/…-emacs-native-comp-with-packages-with-packages-28.1/bin/emacs --fg-daemon "
Restart=on-failure
SuccessExitStatus=15
Type=notify

[Unit]
Description=Emacs text editor
Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/
X-RestartIfChanged=false

```

Please note that I am using the *legacy* reload systemd script. I can switch to the new one if you want me to.

I would like to experiment more but I don't know how to reproduce the issue systematically. Is there a way to force home-manager to reload systemd?

**Comment by DamienCassou** [comment]
Here is what I think may happen:

1. I use Emacs for some time
2. I kill Emacs with `M-x kill-emacs`
3. I start Emacs by using the emacsclient.desktop

I think the emacsclient.desktop file starts Emacs with `--daemon` instead of restarting the systemd service. Then, maybe, when I want to `home-manager switch`, systemctl doesn't manage to start the service because Emacs is already running?

> Could it be that you don't have programs.emacs.enable = true

No, I have `programs.emacs.enable = true`

> I don't understand what you mean by the legacy reload systemd script?

I'm talking about `systemd.user.startServices` which is set to `true`. This value is documented as being the same as "legacy".

>  your nixpkgs and home-manager git revisions

- nixpkgs: I'm following the `origin/nixos-21.11` branch for nixpkgs on which I'm adding [a few package updates](https://github.com/DamienCassou/nixpkgs/commits/system).
- home-manager: I'm following the `origin/master` on top of which I'm adding [a few reverts](https://github.com/DamienCassou/home-manager/tree/master) to make the branch compatible with my version of nixpkgs.

This setup is a bit weird but it serves me well:
- I can benefit from a stable system (by following `nixos-21.11`) with recent versions of packages (thanks to adding my own commits on top).
- I can benefit from most of the latest updates in home-manager services.

> and is your EDITOR environment variable set to the editor script provided by services.emacs.defaultEditor?

yes. You will find my configuration in the first message of this thread.

**Comment by rvl** [comment]
Thanks for the info. I was not aware of the `systemd.user.startServices` option.

It does make sense to combine stable nixos-21.11 with the very latest home-manager. Although I imagine the `makeDesktopItem` change in nixos-unstable has caused some pain.

It seems like you need either of these things:
1. Launching emacsclient.desktop when `emacs.service` is stopped causes `emacs.service` to start.
2. Starting `emacs.service` when there is already an emacs server process running should not fail, but should result in the systemd service moving to the active state.
Either is possible, but would require hacks to achieve.

Can I suggest enabling socket activation for emacs? This would make `emacsclient.desktop` work even if emacs isn't running. Even with socket activation, you can make emacs start immediately at login with this:
```nix
systemd.user.services.emacs.Install.WantedBy = [ "default.target" ];
```

I'm still puzzled by where the `emacs --daemon` option was coming from. It might be worth looking at `echo $PATH`, `which emacsclient`, `echo $EDITOR`, `gtk-launch emacsclient`, `grep -HRi 'exec.*emacs' /etc/profiles/per-user/rodney/share/applications /run/current-system/sw/share/applications ~/.local/share/applications ~/.nix-profile/share/applications`, etc, etc.

**Comment by DamienCassou** [comment]
> Can I suggest enabling socket activation for emacs? This would make emacsclient.desktop work even if emacs isn't running. Even with socket activation, you can make emacs start immediately at login with this: ...

I created https://github.com/nix-community/home-manager/pull/2941 to make this easier.

> I'm still puzzled by where the emacs `--daemon` option was coming from.

emacsclient does that automatically when passed `--alternate-editor ""` (which emacsclient.desktop does). Here is the [relevant extract of the manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Invoking-emacsclient.html):

```
‘-a command’
‘--alternate-editor=command’

    Specify a shell command to run if emacsclient fails to contact Emacs. This is useful when running emacsclient in a script. The command may include arguments, which may be quoted "like this". Currently, escaping of quotes is not supported.

    As a special exception, if command is the empty string, then emacsclient starts Emacs in daemon mode (as ‘emacs --daemon’) and then tries connecting again. 
```

**Comment by DamienCassou** [comment]
I'm closing this issue as I think everything is clear now.
