### ISSUE TITLE
backport helix to 21.11

### ISSUE THREAD

**Issue by anthr76** [nix-community/home-manager#2921]
### Description

I'd like to use the helix module on home-manager 21.11. Would it be possible to backport it? If so I'd try to do it myself.

**Comment by Philipp-M** [comment]
Since a new stable release (22.05) is coming out in a few days for NixOS I don't think it's worth the effort?
Btw. I'm using home-manager on master successfully in NixOS 21.11

**Comment by teto** [comment]
22.05 is out. I suppose you upgraded to that
