### ISSUE TITLE
The `$HOME` in the maildirBasePath is not expanded.

### ISSUE THREAD

**Issue by wucke13** [nix-community/home-manager#2946]
https://github.com/nix-community/home-manager/blob/882bd8118bdbff3a6e53e5ced393932b351ce2f6/modules/accounts/email.nix#L388

By putting `maildirBasePath = "$HOME/pim/mail";` in my config, I ended up with the following entry in the `.mbsynrc`:
```
Inbox /home/<my-username>/$HOME/pim/mail/mailbox/Inbox
```

This is definitely not what I expected.

**Comment by berbiche** [comment]
Hi,

The description for the option explicitly says that a relative path is relative to your home folder.

The solution is simply to remove `$HOME/` from your configuration.

**Comment by wucke13** [comment]
Hi, I think here is a misunderstanding. I figured out a workaround myself,
its quite obvious how to avoid the problem, but thank you for pointing it
out explicitly :) .

IMHO the default value given is still a bug; it implies that `$HOME` is
interpolated -- which is __not__ the case. Your comment _would_ make
perfect sense _if_ the given default value was a relative path, but it
isn't.

**Comment by berbiche** [comment]
Indeed, the documentation is incorrect and leads to confusion.
It should be `defaultText = "${config.home.homeDirectory}/Maildir"`
