### ISSUE TITLE
bug: dunst.settings.global.shortcuts should be attrset

### ISSUE THREAD

**Issue by yurrriq** [nix-community/home-manager#2953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

`shortcuts` (an attrSet) was moved under `global`, but home-manager insists it's a string or bool. ref: https://dunst-project.org/changelog/

### Maintainer CC

@sumnerevans @ncfavier @ctem @rycee 

### System information

```markdown
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-41-generic, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"nixpkgs"`
 - channels(ebailey): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
`shortcuts` was moved *and flattened* under `global`, so you set `global.close` etc directly. Nothing to do here.

**Comment by yurrriq** [comment]
Aha, thanks. Personally I moved my key bindings to XMonad, but I'm sure someone will find this thread useful in the future.
