### ISSUE TITLE
sway: support "mouse_warping container"

### ISSUE THREAD

**Issue by PedroHLC** [nix-community/home-manager#2956]
### Description

Right now [`wayland.windowManager.sway.config.focus.mouseWarping`](https://nix-community.github.io/home-manager/options.html#opt-wayland.windowManager.sway.config.focus.mouseWarping) is a boolean and later transcribes to:
```"mouse_warping ${if focus.mouseWarping then "output" else "none"}"```

But we have one more option as shown in `man 5 sway`:
>       mouse_warping output|container|none
>           If _output_ is specified, the mouse will be moved to new outputs as you move focus between
>           them. If _container_ is specified, the mouse will be moved to the middle of the container on
>           switch. Default is _output_.

It was probably made like this to match the i3 option (which is `output|none`)...

Cc maintainers: @alexarice @sumnerevans @sebtm

**Comment by berbiche** [comment]
Still relevant I believe
