### ISSUE TITLE
bug: pass-secret-service unnecessarily depends on password-store

### ISSUE THREAD

**Issue by houstdav000** [nix-community/home-manager#2962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The nix expression requires that `programs.password-store.enable` be `true`, basing the loaded password store directory on the environment variable configured within the `password-store` module. This is unnecessary, as [pass_secret_service uses pypass](https://github.com/mdellweg/pass_secret_service/blob/develop/setup.py), meaning the dependency is unnecessary, as well as potentially problematic if one wishes to use a different compliant pass tool, such as pypass or gopass, or use the service without installing pass itself. This directory should be configurable separately.

It may indeed be best to have it use a default of the environment variable `PASSWORD_STORE_DIR` or the one given in the `password-store` module if enabled, but it should still be configurable.

### Maintainer CC

@cab404

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.17.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos"`
 - channels(david): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by houstdav000** [comment]
I forgot I apparently wrote a patch for this before: <https://github.com/nix-community/home-manager/compare/master...houstdav000:patch/pass-secret-package>

Though note this one does go a bit further in scope, adding a package arg as well, but also doesn't check for the `config.programs.password-store.config.PASSWORD_STORE_DIR` value, leaving that to the user.

It may be a good idea to add a test for this as well, but I can't get it to work with standard nixpkgs anyways without <https://github.com/NixOS/nixpkgs/pull/168879>

**Comment by cab404** [comment]
patch you wrote LGTM!
why won’t you PR it?

**Comment by houstdav000** [comment]
My hesitancy is that I hadn't written tests, and so wasn't sure if it worked. I've now written a few tests and fixed a bug, so now it might be good to PR.
