### ISSUE TITLE
bug: neovim: rebuilding with coc support does not work when nodejs is in PATH

### ISSUE THREAD

**Issue by IvarWithoutBones** [nix-community/home-manager#2966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When attempting to rebuild my neovim configuration I hit the following error:
```
neovim> Generating remote plugin manifest
neovim> Error detected while processing function coc#rpc#start_server[13]..coc#util#get_data_home:
neovim> line   15:
neovim> E117: Unknown function: coc#float#create_notification
neovim> remote/host: generated rplugin manifest: /nix/store/qkdzljsqi4i99hmghnab4nnnd1w16vjy-neovim-0.7.0/rplugin.vim
neovim> Generating rplugin.vim failed!
```
This happens with the following config:
```nix
programs.neovim = {
  enable = true;
  coc.enable = true;
  withNodeJs = true;
};
```
This is problematic because coc needs nodejs to function, when its not in `PATH` coc errors out at runtime. I've confirmed removing nodejs from the environment rebuilds just fine. Supplying the environment with nodejs and without the `withNodeJs` option also didn't seem to fix anything, maybe this is an issue with a coc version bump in nixpkgs?

### Maintainer CC
(Based on the `git blame`)

@sumnerevans @fmoda3 @selene57 @ashinkarov

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.17.7, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220512_d354fc3`
 - channels(root): `"nixos-21.11"`
 - channels(ivv): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sumnerevans** [comment]
I also ran into this. I'm not quite sure what the solution should be. It appears to be some issue with an upstream version bump as it was working fine before.

**Comment by sumnerevans** [comment]
Overriding the package using #2972 with the latest commit from https://github.com/neoclide/coc.nvim/commits/release allows the build to work.

**Comment by sumnerevans** [comment]
I'm going to go ahead and close this issue, as there is now a solution to fix the issue. I guess we will just have to maintain an override for a while until nixpkgs updates the coc-nvim package.
