### ISSUE TITLE
Move mkOutOfStoreSymlink to lib.hm

### ISSUE THREAD

**Issue by suconakh** [nix-community/home-manager#2980]
### Description
When using home-manager as a flake input, it is inconvenient to access `mkOutOfStoreSymlink`. Maybe i am doing something wrong, but at the moment, in order to access this function, i need to do something like this:
```nix
(inputs.home.lib.homeManagerConfiguration {
  configration = {};
  system = "x86_64-linux";
  homeDirectory = "/home/user";
  username = "user";
}).config.lib.file.mkOutOfStoreSymlink
```
When using home-manager in a nixos module, i can access `config` by passing a closure that can take `config` as an argument:
```nix
home-manager = {
  useGlobalPkgs = true;
  users.user = { config, ... }: {
    home.file."file.txt".source = config.lib.file.mkOutOfStoreSymlink ./file.txt;
  };
};
```
Which of course is more convenient but again in my opinion it is not as ideal as simply accessing it with `inputs.home-manager.lib.hm.files.mkOutOfStoreSymlink` for example.
I examined its source code and it seems to me that it is not tied to current home-manager configuration in any way, so it can be used as a library function.

**Comment by rycee** [comment]
Unfortunately, `mkOutOfStoreSymlink` requires the use of `pkgs`, which prevents it from being a plain library function. I think the most idiomatic way to access it is to go through the `config` parameter like in your second example.

**Comment by suconakh** [comment]
Oh, i didn't noticed that. Closing then
