### ISSUE TITLE
bug: programs.vscode.extensions causes "Extensions have been modified on disk" message on startup

### ISSUE THREAD

**Issue by winterqt** [nix-community/home-manager#2981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When starting VS Code v1.67.2, the message "Extensions have been modified on disk. Please reload the window." pops up every time (even after reloading the window and restarting the application), without any changes being made to the extensions configuration since the last occurrence of this message. I suspect this may be due to the symlink to `home-manager-files` in `~/.vscode/extensions` being different, even if the content is unchanged; so this is an upstream issue with their implementation of this feature.

This happens no matter the value of `programs.vscode.mutableExtensionsDir`, and even when the generation has not been switched at all.

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220512_d354fc3`
 - channels(winter): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/d257b5klv0hq73i5f853iv1h8vkjy1f5-source`
```

**Comment by winterqt** [comment]
Fixed upstream, closing.

**Comment by kubukoz** [comment]
Seeing this again :(
