### ISSUE TITLE
bug: fail in fetching nmd from gitlab: error 403 forbidden

### ISSUE THREAD

**Issue by diegofariasm** [nix-community/home-manager#2996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Whenever i run the "nix build"  command for the home-manager configuration, it ends up failing in the build part for nmd. Trying to prefetch the url  with "nix-prefetch-url" gives out the same error; 403 forbidden
![2022-06-04_20-42](https://user-images.githubusercontent.com/102834119/172029123-7d91e22b-4fef-4dd7-a0f4-1af278c697ec.png)
.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.118, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-21.11"`
 - channels(deviant): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by diegofariasm** [comment]
I have just now noticed what i just made an issue of. I guess it doesn't make much sense, lol.

**Comment by geekscrapy** [comment]
I am currently getting this message. What did you do to fix it? I thought it might be a temporary thing but it's been like this for days
