### ISSUE TITLE
bug: services.barrier assumes barrierc disables crypto by default

### ISSUE THREAD

**Issue by Francesco149** [nix-community/home-manager#3001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

the barrier service assumes that barrierc disables crypto by default: https://github.com/nix-community/home-manager/blob/master/modules/services/barrier.nix#L73 however crypto has enabled by default for quite a few versions now. this means it's impossible to declaratively disable crypto.

```
$ /nix/store/908jnji47zm0bxvwlsjckbdb3bh1f13w-barrier-2.4.0/bin/.barrierc-wrapped --help | grep crypto
      --enable-crypto      enable the crypto (ssl) plugin (default, deprecated).
      --disable-crypto     disable the crypto (ssl) plugin.
```

### Maintainer CC

@Kritnich 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.41, NixOS, 22.05 (Quokka), 22.05.20220520.dfd8298`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(loli): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Kritnich** [comment]
Created a fix by simply inverting the logic of the module option. I left the option name as is for backward compatibility.
