### ISSUE TITLE
bug: xdg.userDirs not updating directories

### ISSUE THREAD

**Issue by archer-65** [nix-community/home-manager#3004]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue description

The `xdg-user-dirs` module provides a way to manage user directories, however if I change the dirs' path or add `extraConfig`, it doesn't update anything.
Also, `user-dirs.dirs` is the same everytime.

Here a snippet
```
 xdg.userDirs = {
    enable = true;
    createDirectories = true;
    desktop = "${config.home.homeDirectory}/desktop";
    documents = "${config.home.homeDirectory}/docs";
    download = "${config.home.homeDirectory}/dl";
    music = "${config.home.homeDirectory}/music";
    pictures = "${config.home.homeDirectory}/pics";
    publicShare = "${config.home.homeDirectory}/public";
    templates = "${config.home.homeDirectory}/templates";
    videos = "${config.home.homeDirectory}/videos";

    extraConfig = ''
      {
        XDG_PROJECTS_DIR = "${config.home.homeDirectory}/projects";
        XDG_GAMES_DIR = "${config.home.homeDirectory}/games";
      }
    '';
  };
```

Result:
```
XDG_DESKTOP_DIR="/home/mario/desktop"
XDG_DOCUMENTS_DIR="/home/mario/docs"
XDG_DOWNLOAD_DIR="/home/mario/dl"
XDG_MUSIC_DIR="/home/mario/music"
XDG_PICTURES_DIR="/home/mario/pics"
XDG_PUBLICSHARE_DIR="/home/mario/public"
XDG_TEMPLATES_DIR="/home/mario/templates"
XDG_VIDEOS_DIR="/home/mario/videos"
```

### Maintainer CC

@pacien

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.18.0, NixOS, 22.11 (Raccoon), 22.11.20220603.236cc29`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.8.1`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Instead of

    extraConfig = ''
      {
        XDG_PROJECTS_DIR = "${config.home.homeDirectory}/projects";
        XDG_GAMES_DIR = "${config.home.homeDirectory}/games";
      }
    '';

try

    extraConfig = {
      XDG_PROJECTS_DIR = "${config.home.homeDirectory}/projects";
      XDG_GAMES_DIR = "${config.home.homeDirectory}/games";
    };

**Comment by ncfavier** [comment]
>     XDG_PUBLICSHARE_DIR="/home/mario/public"
>     XDG_TEMPLATES_DIR="/home/mario/templates"

Seems like you did?

**Comment by archer-65** [comment]
> >     XDG_PUBLICSHARE_DIR="/home/mario/public"
> >     XDG_TEMPLATES_DIR="/home/mario/templates"
> 
> Seems like you did?

No, I want to totally unset them

**Comment by ncfavier** [comment]
Ah, then no, you can't, but you can set them to your home directory to effectively disable them. Maybe we could make them nullable.

**Comment by archer-65** [comment]
> Ah, then no, you can't, but you can set them to your home directory to effectively disable them. Maybe we could make them nullable.

Uh, good idea, I think it's reasonable to have these values nullable.
For now, I'll put my home as value. Thank you!
