### ISSUE TITLE
 :bug: nixos hits "raw not defined" error 

### ISSUE THREAD

**Issue by waalge** [nix-community/home-manager#3011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Running
```
 sudo nixos-rebuild switch
```
outputs 
``` 
building Nix...
building the system configuration...
error: undefined variable 'raw'

       at /nix/store/1la8ngm6d41j6a5fn0m602qjqd0n6qpj-source/integration-common.nix:87:33:

           86|     sharedModules = mkOption {
           87|       type = with types; listOf raw;
             |                                 ^
           88|       default = [ ];
(use '--show-trace' to show detailed location information)

```
which looks like its coming from
https://github.com/nix-community/home-manager/blob/70824bb5c790b820b189f62f643f795b1d2ade2e/integration-common.nix#L87

nixos configuration was pointing at master version. Switching the config to use release-22.05 works. 

### Maintainer CC

@ncfavier ? 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.109, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.337011.e7d63bd0d50, nixpkgs-22.05pre363562.30d3d79b7d3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
You're using the master branch of home-manager while on NixOS 21.11. See https://github.com/nix-community/home-manager#releases

**Comment by waalge** [comment]
Gosh, you are fast. 

Thanks
