### ISSUE TITLE
My config broke this morning referencing the following line in a recent contribution

### ISSUE THREAD

**Issue by nikolaishields** [nix-community/home-manager#3015]
First off:
**Big thanks to the home-manager devs and community, this is a great tool!**

A few days ago everything was working great with home-manager, however when I upgraded and pulled in the most recent changes from upstream I traced the resulting error to the following source.
https://github.com/nix-community/home-manager/blob/70824bb5c790b820b189f62f643f795b1d2ade2e/integration-common.nix#L86
```
sudo nixos-rebuild test
building Nix...
building the system configuration...
error: undefined variable 'raw'

       at /nix/store/1la8ngm6d41j6a5fn0m602qjqd0n6qpj-source/integration-common.nix:87:33:

           86|     sharedModules = mkOption {
           87|       type = with types; listOf raw;
             |                                 ^
           88|       default = [ ];
(use '--show-trace' to show detailed location information)
```

It looks like the change was introduced as part of this contribution: https://github.com/nix-community/home-manager/commit/64ab7d6e8d157848ec285cd267db29e2f14c1076

If anyone could help me resolve this issue I would greatly appreciate it.

**Comment by nikolaishields** [comment]
I switched to tracking the `release-22.05` branch and this resolved my issue. Looking forward to the upcoming improvements to flake support.
Thanks.

**Comment by holmesmr** [comment]
Should this issue be closed if the problem still exists?

**Comment by steve-chavez** [comment]
> I switched to tracking the release-22.05 branch and this resolved my issue.

Can confirm as well, I did:

```
nix-channel --remove home-manager
nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz home-manager
nix-channel --update
home-manager switch
```
