### ISSUE TITLE
NIX_PATH: unbound variable on Windows WSL

### ISSUE THREAD

**Issue by 101v** [nix-community/home-manager#3020]
I tried to install home manager on Windows WSL (Ubuntu) using the following command:
`nix-shell '<home-manager>' -A install`

It failed with the following error message:

> Creating initial Home Manager generation...
> 
> /nix/store/inphj230qfkd25zpf995p5kggbbyqk44-home-manager/bin/home-manager: line 90: NIX_PATH: unbound variable
> Uh oh, the installation failed! Please create an issue at
> 
>     https://github.com/nix-community/home-manager/issues
> 
> if the error seems to be the fault of Home Manager.

Addtional info:
Kernel Release: 5.10.16.3-microsoft-standard-WSL2
Kernel Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
Machine: X86_64

**Comment by 101v** [comment]
Apologies found the solution in the documentation - on a Non-NixOS we have to add following:
`export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}`

**Comment by SuperSandro2000** [comment]
Did you source the home-manager file mentioned in the docs?
