### ISSUE TITLE
bug: fontconfig.enable value is a set while a Boolean was expected

### ISSUE THREAD

**Issue by K1aymore** [nix-community/home-manager#3022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When trying to switch to NixOS unstable, and using the master/unstable of Home-Manager as a NixOS module, I get the error
```
error: value is a set while a Boolean was expected

       at /nix/store/6jnjqzbjp65hyrf48wyv7mff57wdl6jv-source/nixos/default.nix:24:37:

           23|           # fontconfig by default.
           24|           fonts.fontconfig.enable = lib.mkDefault cfg.useUserPackages
             |                                     ^
           25|             && config.fonts.fontconfig.enable;
```
Which seems to be from [line 24 of the NixOS module's default.nix](https://github.com/nix-community/home-manager/blob/cd3dd2188c19416bc70d9703f84e07a0646af5bf/nixos/default.nix#L24).

I tried putting `fonts.fontconfig.enable = ` both true and false into my configuration, but it didn't change anything.

### Maintainer CC

@SuperSandro2000
@ncfavier

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon), 22.11pre384739.90cd5459a1f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by K1aymore** [comment]
Ah okay thank you

**Comment by jkarlson** [comment]
Ideally one would not close the issue before the merge request is merged maybe, so people will not file duplicates, because they would not look through closed issues?

**Comment by K1aymore** [comment]
Alright it's been fixed now
