### ISSUE TITLE
bug: hash is not SRI

### ISSUE THREAD

**Issue by newAM** [nix-community/home-manager#3044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When updating home-manager I get this error:

```console
$ nix flake update --show-trace
error: hash '07szg39wmna287hv5w9hl45wvm04zbh0k54br59nv3yzvg9ymlj4' is not SRI

       … while updating the flake input 'home-manager'

       … while updating the lock file of flake 'git+file:///etc/nixos?ref=refs%2fheads%2fmain&rev=241f79f05b3dea6ce2a4d29551b7d83d1216418c'
```

The commit that introduced this is 77f1c7636a92973be913ec21be5203edba017100, another user has also noted the problem with a commit comment.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(alex): `""`
 - channels(root): `"nixos-21.11, nixos-unstable, nixos-unstable-small"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aancw** [comment]
I experienced the same problem

```
❯ nix flake update --show-trace
error: hash '07szg39wmna287hv5w9hl45wvm04zbh0k54br59nv3yzvg9ymlj4' is not SRI

       … while updating the flake input 'home-manager'
```

**Comment by newAM** [comment]
> Is this problem will fixed after updated in repo and run `nix flake update` again?

Yup, after #3045 (or similar) gets merged this will fix itself with a `nix flake update`.
