### ISSUE TITLE
bug: home.stateVersion is used but not defined.

### ISSUE THREAD

**Issue by CardboardTurkey** [nix-community/home-manager#3047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Building against master fails, giving:

```
error: The option `home-manager.users.kiran.home.stateVersion' is used but not defined.
```

I can build fine though with release-22.05.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.11 (Raccoon), 22.11pre386636.0d68d7c857f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(kiran): `"nixos-22.05pre359917.fcd48a5a069"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MaeIsBad** [comment]
See: https://github.com/nix-community/home-manager/blob/master/docs/release-notes/rl-2211.adoc

* The <<opt-home.stateVersion>> option no longer has a default value.
It used to default to ``18.09'', which was the Home Manager version
that introduced the option. If your configuration does not explicitly
set this option then you need to add
+
[source,nix]
home.stateVersion = "18.09";
+
to your configuration.
