### ISSUE TITLE
bug: `coc.nvim` build failure on 22.05

### ISSUE THREAD

**Issue by lourkeur** [nix-community/home-manager#3049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Since https://github.com/nix-community/home-manager/pull/3048, the neovim wrapper has a build error on 22.05. The error message is:

```
Generating remote plugin manifest
Error detected while processing function coc#rpc#start_server[13]..coc#util#get_data_home:
line   15:
E117: Unknown function: coc#float#create_notification
remote/host: generated rplugin manifest: /nix/store/k2cqhzb39dkqy8xsv7qp4ckyb5ad8ilc-neovim-0.7.0/rplugin.vim
Generating rplugin.vim failed!
```

[gist minimal reproducer.](https://gist.github.com/lourkeur/bb447b42fc26c28e316dfb81219df8aa) Does not occur on unstable or before e622bad16372aa5ada79a7fa749ec78715dffc54

### Maintainer CC

@addict3d @sumnerevans

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.05 (Quokka), 22.05.20220622.21321a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/etc/nix/channels/nixos`
```

**Comment by addict3d** [comment]
I wasn't sure how to triage this but was able to work around it temporarily as suggested by @sumnerevans here: https://github.com/nix-community/home-manager/issues/2966

Grabbing the latest release from upstream:

```nix
coc.package = pkgs.vimUtils.buildVimPluginFrom2Nix {
  pname = "coc.nvim";
  version = "2022-06-14";
  src = pkgs.fetchFromGitHub {
    owner = "neoclide";
    repo = "coc.nvim";
    rev = "87e5dd692ec8ed7be25b15449fd0ab15a48bfb30";
    sha256 = "sha256-bsrCvgQqIA4jD62PIcLwYdcBM+YLLKLI/x2H5c/bR50=";
  };
  meta.homepage = "https://github.com/neoclide/coc.nvim/";
};
```

**Comment by lourkeur** [comment]
Thank you, this workaround seems to do it for now. Of course a more permanent solution is still desirable.

**Comment by sumnerevans** [comment]
A more permanent solution would be to update `coc.nvim` in nixpkgs, but the whole auto-generated vim plugin file scares me.

**Comment by teto** [comment]
closing as a non home-manager issue. coc.nvim was already fixed on unstable so a backport of that specific change should be fine.

NB: coc often breaks, I hope some coc user comes up with a test that can be added to nixpkgs
