### ISSUE TITLE
bug: error using home-manager: submoduleWith ... unexpected argument "description"

### ISSUE THREAD

**Issue by hydra989** [nix-community/home-manager#3057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

home-manager has been working fine for me up until tonight, when upon a nixos-rebuild (I use home-manager as a nixos module), I get the following error:

    $ sudo nixos-rebuild switch -I nixos-config=/home/hydra/s/dotfiles/nix/configuration.nix
    [sudo] password for hydra: 
    building Nix...
    building the system configuration...
    error: 'submoduleWith' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:570:7 called with unexpected argument 'description'

       at /nix/store/zq34lc3vh1b56ggbvbch85r06sa61h6l-source/nixos/common.nix:14:14:

           13|
           14|   hmModule = types.submoduleWith {
             |              ^
           15|     description = "Home Manager module";

    (use '--show-trace' to show detailed location information)

thereby preventing me from using home-manager.

Removing the install process from my configuration.nix and trying to install home-manager as a user nets the same result after:

    nix-shell '<home-manager>' -A install

For what it's worth, I've been managing home-manger as detailed [on the wiki](https://nixos.wiki/wiki/Home_Manager#Usage_as_a_NixOS_module) and it's worked fine until just now.

I've tracked down [the commit that seems to be causing it](https://github.com/nix-community/home-manager/commit/0434f8e4cab4f200c9b4d3741a9e5d89705e6754) if that's of any help.

### Maintainer CC

No meta.maintainers list I could find for the module. Last touched in [this commit](https://github.com/nix-community/home-manager/commit/0434f8e4cab4f200c9b4d3741a9e5d89705e6754).

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.17.8-xanmod1, NixOS, 22.05 (Quokka), 22.05.342.a634c8f6c1f`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.10.0pre20220601_1892355`
- channels(hydra): `""`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Should work now. Seems I merged the submoduleWith fix too early. Thanks for reporting!

**Comment by ncfavier** [comment]
Do we want to support tracking home-manager/master while using an older nixpkgs? That seems to be the problem here.

**Comment by rycee** [comment]
@ncfavier Thanks for the ping. I've cherry-picked the commit back into master now.
