### ISSUE TITLE
bug: vscode extensions cause IFD

### ISSUE THREAD

**Issue by pwaller** [nix-community/home-manager#3094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

In my home configuration I have:
```
    programs.vscode = {
      enable = true;
      extensions = with pkgs.vscode-extensions; [
        ...
      ];
    }
```

This line here is causing IFD with vscode: https://github.com/nix-community/home-manager/blob/4c5106ed0f3168ff2df21b646aef67e86cbfc11c/modules/programs/vscode.nix#L194

The unwanted behaviour I see is that `nix build --dry-run` downloads and installs a significant amount of stuff before it can even do a dry run, and I'm bandwidth and disk space sensitive -- I want dry-run to be a dry run.

### Maintainer CC

@ncfavier @berbiche -- not sure who is the maintainer here but I see you folks were involved with #2506, hope you don't mind the ping.

### System information

```markdown
The given command doesn't work for me. Given the nature of the issue I don't believe this is relevant; I'm using 4c5106ed0f3168ff2df21b646aef67e86cbfc11c and the nixos-22.05 release. Happy to provide further information if requested.
```

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/3096

**Comment by pwaller** [comment]
Thanks! :)
