### ISSUE TITLE
bug: gpg-agent issue with custom pinentry

### ISSUE THREAD

**Issue by seqizz** [nix-community/home-manager#3095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hi :wave: 

I have the following setup:

```
    services.gpg-agent = {
      enable = true;
      defaultCacheTtl = 86400;
      maxCacheTtl = 86400;
      pinentryFlavor = null;
      extraConfig = ''
        pinentry-program ${pkgs.pinentry-rofi}/bin/pinentry-rofi
        auto-expand-secmem
      '';
    };
```

Which correctly creates following agent config:
```
default-cache-ttl 86400
max-cache-ttl 86400
pinentry-program /nix/store/scm2rkc84jm2kby3k1hjqclri54kqmvx-pinentry-rofi-2.0.3/bin/pinentry-rofi
auto-expand-secmem
```

But I get the following when I use `pass` to get something:
```
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: ccid open error: skip
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: sending signal 12 to client 82924
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: ccid open error: skip
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: ccid open error: skip
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: added app 'piv' to the card context
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: DBG: asking for PIN '||Please unlock the card%0A%0A\x1eNumber\x1f: 6948704%0AHolder\x1f: '
Jul 15 15:37:12 innodellix gpg-agent[83126]: /bin/sh: line 1: env: command not found
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: PIN callback returned error: IPC call has been cancelled
Jul 15 15:37:12 innodellix gpg-agent[83094]: scdaemon[83094]: app_decipher failed: IPC call has been cancelled
Jul 15 15:37:12 innodellix gpg-agent[82924]: smartcard decryption failed: Operation cancelled
Jul 15 15:37:12 innodellix gpg-agent[82924]: command 'PKDECRYPT' failed: Operation cancelled <Pinentry>
```

I could not determine where is this sh including "env" coming from.

If I use nixos' option gnupg.agent, it works with this config without issues. Sounds like a bug, but feel free to close if I'm missing something obvious 🤔

Thanks!

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.18.10, NixOS, 22.05 (Quokka), 22.05.1703.8fa57a6538d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(gurkan): `"home-manager-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by seqizz** [comment]
Realized this is less relevant with home manager and more with the embedded pinentry guis. Closing, sorry for the noise.

**Comment by gautaz** [comment]
Hello @seqizz, sorry to barge in your already closed issue but I am also trying to get `pinentry-rofi` to work with `home-manager` and I guess I am having the exact same issue (`gpg-agent[28866]: /bin/sh: line 1: env: command not found`).

Could you please tell us how you did resolve the issue or point to a more relevant issue report?

**Comment by seqizz** [comment]
Hi, sadly I just couldn't manage to do it. I still have pinentry-rofi there but it always uses the default one, assuming it can only use the main binary can reach and I didn't patch it up correctly. If you find a hint please share, I'd love to use it :)

**Comment by gautaz** [comment]
Sorry to hear that, thank you for the followup :-).
I'll share any progress on my side if I find anything.

**Comment by berbiche** [comment]
@seqizz @gautaz 
This might be an issue with the PATH being "empty" in systemd services.

If you replace the pinentry program with an strace wrapper, you will probably see the chain of call (`pinentry-program = pkgs.writeShellScript "foo" ''${strace}/bin/strace -v -e execve ${my-pinentry-program}''`).

My guess is that pinentry-rofi is executing rofi with an `env rofi` call to resolve the path of the binary.
(Seems like so:
<https://github.com/plattfot/pinentry-rofi/blob/1ee27486d3ed19a7f8ebc7df035c574861e620ba/pinentry-rofi.scm#L332-L341>)

The solution is to wrap rofi-pinentry with a shell script that sets the $PATH or to run pinentry-rofi through a login bash/$SHELL so it gets a "valid" $PATH.
``` nix
''
  pinentry-program = ${pkgs.bash}/bin/bash -lc ${pkgs.pinentry-rofi}/bin/pinentry-rofi
''
```
(assuming there will never be spaces in nix store paths, otherwise quote as needed)

**Comment by gautaz** [comment]
Thanks @berbiche, perfect analysis of the issue :-).

I had to tweak a bit the fix because the `pinentry-program` option cannot take multiple arguments:

```nix
{pkgs, ...}: let
  pinentryRofi = pkgs.writeShellApplication {
    name= "pinentry-rofi-with-env";
    text = ''
      PATH="$PATH:${pkgs.coreutils}/bin:${pkgs.rofi}/bin"
      "${pkgs.pinentry-rofi}/bin/pinentry-rofi" "$@"
    '';
  };
in {
  services.gpg-agent = {
    enable = true;
    extraConfig = ''
      pinentry-program ${pinentryRofi}/bin/pinentry-rofi-with-env
    '';
    pinentryFlavor = null;
  };
}
```

And now it works!

**Comment by Croissong** [comment]
Does anyone have an idea how this could be properly fixed?

**Comment by gautaz** [comment]
Hello @Croissong,

My understanding is that the current pain point is related to `pinentry-rofy` which retrieves `rofi` by using `env`.
From a `nix` point of view, it would be better if the `pinentry-rofy` executable could be built by specifying which `rofi` executable to use.
As nix is able to install in parallel two versions of `rofi`, currently `pinentry-rofi` will use the `rofi` executable reachable from the user environment, so its the user environment which is in control of which `rofi` is used by `pinentry-rofi`, not the nix derivation of `pinentry-rofi`.
This means that if incompatibilities emerge between versions of `pinentry-rofi` and `rofi` at one time, it will be difficult to guarantee a stable installation.
