### ISSUE TITLE
bug: submoduleWith called with unexpected argument `description`

### ISSUE THREAD

**Issue by bradb423** [nix-community/home-manager#3102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Using `home-manager` as a NixOS module, I have encountered the following issue when using `sudo nix-channel --update` followed by `sudo nixos-rebuild switch`:

```nix
building Nix...
building the system configuration...
error: 'submoduleWith' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/types.nix:570:7 called with unexpected argument 'description'

       at /nix/store/bvs1zll53r9day9zz7m1rw7v2b7bvgmm-source/nixos/common.nix:14:14:

           13|
           14|   hmModule = types.submoduleWith {
             |              ^
           15|     description = "Home Manager module";
(use '--show-trace' to show detailed location information)
```

Previously, this has worked fine, including yesterday while using the same configuration on a VM. However, today I now encounter the above error. I believe it is related to [70d5929](https://github.com/nix-community/home-manager/commit/70d5929885ccec8dde8585894dd3ebe606e75f41), although I am not quite sure.

Perhaps I am wrongly including `home-manager` in my [configuration](https://github.com/bradb423/nixos-hosts/blob/02d1a01f2f084e46e16ae9b7b1c0618f3ff30639/configuration.nix#L4)?

Any  help would be much appreciated, thank you :)

### Maintainer CC

@ncfavier @rycee 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.15.54, NixOS, 22.05 (Quokka), 22.05.1744.07a2e6a4e31`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.8.1`
- channels(root): `"nixos-22.05"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
See https://github.com/nix-community/home-manager/issues/3101

You should track the release-22.05 branch of Home Manager as explained [here](https://github.com/nix-community/home-manager#releases)
