### ISSUE TITLE
bug: home-manager doesn't work with latest nixpkgs-22.05-darwin

### ISSUE THREAD

**Issue by LucianU** [nix-community/home-manager#3104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The [nixos/common.nix](https://github.com/nix-community/home-manager/blob/70d5929885ccec8dde8585894dd3ebe606e75f41/nixos/common.nix#L15) file uses `types.submoduleWith` with an argument that doesn't exist in the [`nixpkgs-22.05-darwin` of the function](https://github.com/NixOS/nixpkgs/blob/2bee7df80612eda72b913cfae602ac3d863134d1/lib/types.nix#L569). The argument is `description`.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.2`
 - channels(lucian): `"darwin, home-manager-22.05.tar.gz"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rycee** [comment]
Please use the release-22.05 branch of Home Manager when you are using Nixpkgs 22.05. See the [installation instructions](https://nix-community.github.io/home-manager/index.html#ch-installation) for more.
