### ISSUE TITLE
bug: "The name ca.desrt.dconf was not provided by any .service files"

### ISSUE THREAD

**Issue by the-argus** [nix-community/home-manager#3113]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When using ``gtk.enable = true`` I now get the following at the end of my home manager activation:
```
Activating dconfSettings
error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

This did not happen in the past, as of a few weeks ago. I believe the point at which it changed was when I installed and uninstalled the gnome desktop environment. I suspect some state remains from that.

You can find my system configuration at [github.com/the-argus/nixsys](https://github.com/the-argus/nixsys)
More specifically in user/argus/gtk.
To see my gnome settings, check modules/desktops/gnome.nix.

This is not related to issue #1444 as I have tried removing ``~/.config/dconf/user`` to no avail.

### Maintainer CC

@rycee (maintainer)
@polykernel (comitter who most recently touched the gtk.nix file in this repo)

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.18.13, NixOS, 22.05 (Quokka), 22.05.20220722.e3583ad`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by the-argus** [comment]
Okay update, I was able to fix the issue by adding ``home.packages = [ pkgs.dconf ]`` when using gtk.enable. That line should be added to the gtk module.

**Comment by polykernel** [comment]
Hello, I believe this should be handled at the NixOS level with the option `programs.dconf.enable`.

See https://nix-community.github.io/home-manager/index.html#_why_do_i_get_an_error_message_about_literal_ca_desrt_dconf_literal_or_literal_dconf_service_literal.

**Comment by the-argus** [comment]
Why not cut the problem at the root, at least in this case, and enable dconf in the HM gtk module?

**Comment by berbiche** [comment]
> Why not cut the problem at the root, at least in this case, and enable dconf in the HM gtk module?

Home Manager modules cannot set NixOS options as they do not have access to the configuration even when Home Manager is used as a NixOS module.

Home Manager also tries to not to set anything at the system-level to retain a separation from NixOS. This makes it possible to use the Home Manager module with nix-darwin and possibly future platforms.

**Comment by Animeshz** [comment]
For non-NixOS, Installing dconf in host fixed this, while adding pkgs.dconf to home.packages didn't.

**Comment by marie-bnl** [comment]
Fixing this issue doesn't require any system-level configuration, as mentioned above, setting `home.packages = [ pkgs.dconf ]` works so I believe this should be added when `gtk.enable` is set to `true`.
