### ISSUE TITLE
bug: New bash completion code breaks builtin

### ISSUE THREAD

**Issue by zdcthomas** [nix-community/home-manager#3133]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The new bash completion setting [here](https://github.com/nix-community/home-manager/pull/3131/files#diff-3a810ca5b6e265fe6df63d439068fef3840c902092218ad480ae4054e592a0fbR221) errors in the macos default /bin/bash 
That bash version sadly can't be upgraded, cause macos.

The bash version:
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

The error:
```
bash: /Users/<my_user_name>/.bashrc: line 21: conditional binary operator expected
bash: /Users/<my_user_name>/.bashrc: line 21: syntax error near `BASH_COMPLETION_VERSINFO'
bash: /Users/<my_user_name>/.bashrc: line 21: `if [[ ! -v BASH_COMPLETION_VERSINFO ]]; then'
```

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(zacharythomas): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
```

**Comment by berbiche** [comment]
Hi,

We've had few reports (for different modules) over time related to the old version of bash used in MacOS and we've always had the same stance: unless the fix is simple, we won't make any effort to support it.

I recommend installing a different bash with nix-darwin or homebrew and making it your default.

**Comment by rycee** [comment]
Yeah, I'm not keen on supporting an ancient version of Bash. @zdcthomas You can add

    programs.bash.enableCompletion = false;

to your configuration and the generated code won't have this `if` statement. I imagine the Nixpkgs bash-completion package won't work with Bash 3 anyway.

That said, I'm not certain what the error actually refers to, Bash 3 doesn't support `-v`?

**Comment by zdcthomas** [comment]
@berbiche yeah for sure, my default shell is zsh installed from nix, but I thought I'd report this anyway, since I noticed it.

@rycee I believe so, I can't find any mention of it bash 3's man page.

**Comment by zdcthomas** [comment]
Either way, I'm totally fine closing this out

**Comment by bohendo** [comment]
I'm hitting this same issue. Agreed, I don't care for ancient bash support but how do I install a different bash with nix-darwin and make it my default? Or maybe that isn't the solution here?

In my configuration.nix I have:
```
  environment.systemPackages = with pkgs; [
    bash
    bash-completion
    ...
```

And in my home.nix I have:

```
    bash = {
      enable = true;
      enableCompletion = false;
      sessionVariables = {
        SHELL = "bash";
      };
     ...
```
Looks like I have a modern bash version:
```
$ bash --version
GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin22.1.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
but this `-v` operator still isn't supported
```
$ if [[ ! -v BASH_COMPLETION_VERSINFO ]]; then echo "yay"; else echo "nay"; fi
-bash: conditional binary operator expected
-bash: syntax error near `BASH_COMPLETION_VERSINFO'
```
setting enableCompletion to false quiets the above error on shell login but I would still like bash-completion to work.

Could the `test` aka `[` command be out of date or otherwise misconfigured?

```
$ coreutils --version
coreutils (GNU coreutils) 9.1
Packaged by https://nixos.org
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(bohendo): `"darwin, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/bohendo/.nix-defexpr/channels/nixpkgs`

**Comment by bohendo** [comment]
Looks like the version of bash installed via homebrew is newer & does support `-v`
```
darwin:etc bohendo$ /opt/homebrew/bin/bash
bash-5.2$ if [[ ! -v BASH_COMPLETION_VERSINFO ]]; then echo "yay"; else echo "nay"; fi
nay

darwin:etc bohendo$ /opt/homebrew/bin/bash --version
GNU bash, version 5.2.2(1)-release (aarch64-apple-darwin21.6.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```
How do I install bash 5.2 via nix instead of 5.1? I'm already using nixpkgs unstable, my current flake.nix:
```
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    darwin.url = "github:lnl7/nix-darwin/master";
    darwin.inputs.nixpkgs.follows = "nixpkgs-unstable";
    home-manager.url = "github:nix-community/home-manager/master";
    home-manager.inputs.nixpkgs.follows = "nixpkgs-unstable";
  };
```

**Comment by bohendo** [comment]
Weird thing is, bash 5.1 supports the `-v` operator on linux, so something's off with bash built for `aarch64-apple-darwin22.1.0`
```
[bohendo@linux:~/code]$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[bohendo@linux:~/code]$ if [[ ! -v BASH_COMPLETION_VERSINFO ]]; then echo "yay"; else echo "nay"; fi
nay
```

**Comment by bohendo** [comment]
Ok, found a workaround that is mostly adequate:
```nix
    bash = {
      enable = true;
      enableCompletion = false; # turn off the automated completion injection
      bashrcExtra = ''
        if [[ -z BASH_COMPLETION_VERSINFO ]]; then
          . "${pkgs.bash-completion}/etc/profile.d/bash_completion.sh"
        fi
      ''; # manually import completions using `-z` to check if it's been loaded instead of `-v`
```
I think some other completions (git? docker?) might be lost by doing ^ this but it's working well enough for now & I can add more to it if/when needed.

I'd still like to be able to install an up-to-date bash on macos tho so any guidance towards that end would be appreciated

**Comment by garryshield** [comment]
`cat /etc/shells`
```
...
/Users/XXX/.nix-profile/bin/zsh
/Users/XXX/.nix-profile/bin/bash
```

then 
`chsh -s /Users/XXX/.nix-profile/bin/bash`
works for me
