### ISSUE TITLE
pass a runtime attrset along with vim plugins

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#3135]
I've got a pretty fluid neovim setup, e.g, I often add/remove/disable neovim plugins. I sometimes achieve this imperatively via vim-plug/packer and sometimes via nix. One advantage of nix is that disabling removes the cruft. 

Right now we can install plugins with an associated config, e.g.:
```
    programs.neovim.plugins = {
      plugin = gitsigns-nvim;
      config = ''" hello world'';
   }
```

Having everything written to a single init.vim prevents from using vim mechanisms that can make the config clearer (subjectively), for instance I prefer to add files in the "after" folder rather than using autocommands

```
    programs.neovim.plugins = {
      plugin = gitsigns-nvim;
      config = ''" hello world'';
      runtime = {
           # implemented with a linFarm 
           "after/git/signs.vim".text =  ''ventrecloque'';
   }
```

**Comment by lxsymington** [comment]
It looks as if this feature has been merged, would it be worth extending this to allow for general runtime config? Seems there's a few things in [here](https://neovim.io/doc/user/options.html#'runtimepath') that could be useful for configuration outside of plugins?

**Comment by teto** [comment]
I am not sure I understand what you mean, feel free to open a new ticket. Indeed I can close this.
