### ISSUE TITLE
kanshi: Support adaptive_sync option

### ISSUE THREAD

**Issue by houstdav000** [nix-community/home-manager#3136]
### Description

The kanshi module as-written does not support the `adaptive_sync` sway output option, but also does not support arbitrary string additions to profiles -- only additions to the top-level config.

As such, I'd have to create an entire profile manually with `extraConfig` just to have `adaptive_sync on` for an output.

**Comment by wchresta** [comment]
Hi @houstdav000, I looked shortly in to this and all I could find is the following bug for kanshi which seems to indicate that adaptive_sync is currently not supported in kanshi:
https://todo.sr.ht/~emersion/kanshi/64

A quick test with kanshi also seems to indicate the same:
```
$ mkdir .config/kanshi
$ cat > .config/kanshi/config
profile test {
  output "DP-1" enable adaptive_sync on
}
$ kanshi
unknown directive 'adaptive_sync' in profile output 'DP-1'
failed to parse config file: error on line 2, column 37
```

Can you confirm this finding or were you able to get kanshi to adopt `adaptive_sync` by providing a custom config?

**Comment by houstdav000** [comment]
Sorry, haven't had a chance to test until now. I do indeed get the same, so I suppose this is a moot point.
