### ISSUE TITLE
bug: i3status-rust: Nix can't convert Unicode points properly and generate TOML file

### ISSUE THREAD

**Issue by Alejandro-Villa** [nix-community/home-manager#3138]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

First of all, sorry if this is a nix-related issue, I have been looking at the [module](https://github.com/nix-community/home-manager/blob/master/modules/programs/i3status-rust.nix) and I don't totally understand the workings behind translating nix attribute sets to toml.

I have configured my i3status-rust and it is working properly with the FontAwesome 5 icons. But I want to override a certain icon. According to the [docs for i3status-rs](https://github.com/greshake/i3status-rust/blob/v0.22.0/doc/themes.md#overriding-themes-and-icon-sets). I should be able to do the following in my `/etc/nixos/configuration.nix` (I'm using home-manager as a module):

```nix
programs.i3status-rust = {
  enable = true;
  bars = {
    mybar = {
      settings = {
        icons = {
          name = "awesome5";
          overrides = {
            disk_drive = "\uXXXX";
          };
        };
      };
    };
  };
};
```

However, when I regenerate my configuration file, this is what I see:

```toml
[icons]
name = "awesome5"

[icons.overrides]
disk_drive = "uf0a0"
```

So, the bug seems to be with Nix's string treatment. As I said, if this can't be fixed in here, please tell me and I will take the issue and ask upstream. Thanks!

### Maintainer CC

@ncfavier @sephii @rycee @happysalada @workflow @ivan

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"                
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.56, NixOS, 22.05 (Quokka), 22.05.2019.d9536b9b1e3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(alejandro): `""`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
`"\u"` doesn't have any special meaning to Nix to it just interprets it as `"u"`. Can you insert the character you want directly in the string? e.g. `"😀"`

**Comment by Alejandro-Villa** [comment]
Yes that works! Thank you, I didn't consider directly copy-pasting the glyph.
