### ISSUE TITLE
Expose Neovim's `finalPackage`

### ISSUE THREAD

**Issue by samhh** [nix-community/home-manager#3157]
After updating my system inputs I've started having problems with Neovim when opened indirectly (e.g. via `$MANPAGER`, which references plain `pkgs.neovim[-unwrapped]`), which I've been debugging here: https://github.com/samhh/dotfiles/issues/346

`config.programs.neovim.finalPackage` would I think solve my problem, however it's hidden. Among other packages it's sometimes hidden and sometimes not, for example it is for Emacs but isn't for Rofi.

Is there a better solution? If not, can we expose Neovim's `finalPackage`?

**Comment by berbiche** [comment]
Hi,

The `internal` and `hidden` attribute are only used for documentation purposes.
Both attributes will hide the option/setting from the documentation.

You can still access `config.programs.neovim.finalPackage` even if it's hidden.
