### ISSUE TITLE
bug: sway not longer working because of upstream changes

### ISSUE THREAD

**Issue by djacu** [nix-community/home-manager#3160]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

[This nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/186028) deactivates polkit by default which is required to run sway. This can be fixed with `security.polkit.enable = true;` but it is enabled by default in the [nixpkgs implementation of sway](https://github.com/NixOS/nixpkgs/blob/600b02324c37abd1280051f872c914113f1f37bf/nixos/modules/programs/sway.nix#L137).

### Maintainer CC

@alexarice @sumnerevans @SebTM @oxalica 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.18.16, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos-21.11"`
 - channels(bakerdn): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by oxalica** [comment]
Not sure what we could do in h-m. `polkit` is a system service and cannot be enabled via h-m.

**Comment by berbiche** [comment]
Hi,

As @oxalica said, there is nothing HM can do to resolve this issue.

The only thing we could do is documenting this issue in the documentation.
