### ISSUE TITLE
bug: waybar does not reload on configuration change when `programs.waybar.systemd.enable = true`

### ISSUE THREAD

**Issue by oati** [nix-community/home-manager#3186]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Modifying waybar's configs (or manually running the `OnChange` command) does not restart the waybar service, nor does it reload waybar's configuration.

### Maintainer CC

@berbich

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.18.19, NixOS, 22.11 (Raccoon), 22.11.20220826.38e16b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/sjmq1gphj1arbzf4aqqnygd9pf4hkfkf-source`
```

**Comment by thiagokokada** [comment]
Still an issue.

**Comment by teto** [comment]
I think I witness the same which is weird because there are some `xdg.configFile."waybar/style.css".onChange` hooks that are supposed to trigger a reload.

An alternative could be to use sthg like:
```
# Make sure the service is restarted if the settings change.
systemd.user.services.waybar.Unit.X-Restart-Triggers = [ (builtins.hashString "md5" (builtins.toJSON cfg.settings)) ];
```

**Comment by pluiedev** [comment]
Been experimenting with this lately — I think the `|| true` part is causing the issue here, as it was clearly supposed to ignore errors from pkill, and obfuscating what's actually happening.

**Comment by pluiedev** [comment]
I ended up going with `(ps aux | grep waybar | grep -v grep) && (${lib.getExe' pkgs.procps "pkill"} -u $USER waybar) && (${lib.getExe pkgs.waybar})` as my `onChange` command. Using the built-in refresh mechanism by sending a `SIGUSR2` often doesn't work as it complains with:
```console
[2023-11-06 11:49:58.790] [error] Cannot merge config, conflicting or invalid JSON types
```
Killing and restarting entirely seems to work much better.
