### ISSUE TITLE
Suggest adding local file to git on `nix build {home manager activation}` 

### ISSUE THREAD

**Issue by vlashada** [nix-community/home-manager#3221]
### Description
If you try to use a local file as a module when building home manager in flake with `nix build`, but while having forgotten to add the file to git, you will get an error that is quite hard to understand while a beginner (`error: getting status of '/nix/store/.../you-folder/your-file.nix' : No such file or directory`). If you have this file and folder in the local file, just have forgotten to add it to git: Should you maybe get feedback asking if you might have forgotten to add the local file to git?

**Comment by x10an14** [comment]
This is issue belongs in https://github.com/NixOS/nix I believe - Home Manager is not what gives you that error message.
(HM does however rely on this behavior).

**Comment by berbiche** [comment]
Hi,

As pointed out by @x10an14, this is not something Home Manager wants to tackle.

Home Manager's `home-manager` script is a wrapper around nix commands and as such some of the UX issues stem from nix commands themselves.
