### ISSUE TITLE
Capitalize "music" folder name

### ISSUE THREAD

**Issue by AdsonCicilioti** [nix-community/home-manager#3225]
https://github.com/nix-community/home-manager/blob/5408e27961599b1350b651f88715daf6e67244a7/modules/services/mpd.nix#L56

This cause incorrect path because the default name of userDirs on English is capitalized.

**Comment by rycee** [comment]
Probably best to simply remove the default and let the user sort it out. I think I chose that default at some point since it matches the directory I use 🙂

**Comment by rycee** [comment]
Well, I guess if `xdg.userDirs.enable == true` then we should default to `xdg.userDirs.music`…
