### ISSUE TITLE
mbsync: extraConfig enum missing variant

### ISSUE THREAD

**Issue by dbaynard** [nix-community/home-manager#3228]
As described in [mbsync](https://isync.sourceforge.io/mbsync.html), the following account configuration line is valid (and probably desirable).

```
SSLVersions TLSv1.3 TLSv1.2
```

However, this cannot be represented using the `extraConfigType`.

https://github.com/nix-community/home-manager/blob/5408e27961599b1350b651f88715daf6e67244a7/modules/programs/mbsync-accounts.nix#L7

I _think_ this should allow for `attrsOf (listOf (separatedString " "))`, meaning I can supply the following value.

```nix
SSLVersions = [ "TLSv1.3" "TLSv1.2" ];
```

If I just use a string, then the output (below) results in an error (edit: `Unrecognized SSL version`).

```
SSLVersions "TLSv1.3 TLSv1.2"
```

I'd be happy to make the change, if it's ok.

**Comment by rycee** [comment]
Seems to make sense to allow lists of strings. Would `SSLVersions "TLSv1.3" "TLSv1.2"` be a valid value or does it have to be without `"` characters?

**Comment by dbaynard** [comment]
I think that will work — I'll be able to check, tomorrow.

**Comment by dbaynard** [comment]
The example, `SSLVersions "TLSv1.3" "TLSv1.2"`, works, and adding `listOf str` does the right thing (I'll make a PR).

I've looked at git history and the `extraConfigType` definition (home-manager@151f29a17a6027cd2bdbd8276ef79631a1a950f6) pre-dates the introduction of `lib.types.oneOf`, in nixpkgs@9a44f44d4c0d33775b63ad9dd387fd77f810074e. Given home-manager claims to support only 22.05 onwards, I suspect that would be better than replacing the `bool` with another `either bool`, etc.

I think it's worth making this change, as there are multiple options that will benefit. I could, though, add `SSLVersions` as an explicit option, though, if desired? I'm minded not to, as it adds additional complexity for relatively little gain.
