### ISSUE TITLE
bug: emacs does not get the GTK theme of the system

### ISSUE THREAD

**Issue by tobiasBora** [nix-community/home-manager#3239]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

If I open emacs installed from home manager or from the system I get different themes (basically the system theme seems to be forgotten by home manager):

![image](https://user-images.githubusercontent.com/2164118/191092455-ec78770e-8802-4c9c-966f-380d4d878f91.png)

Any idea how to ask to emacs to follow the system's gtk theme?

### Maintainer CC

@tadfisher

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220411_f7276bc`
 - channels(leo): `"home-manager, local-nixos-unstable, local-nixpkgs-unstable, nixgl, nixos-20-03-20.03, nixos-unstable, test"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tobiasBora** [comment]
After exploring a bit more it seems that the system binaries is wrapped twice while home manager wraps the program only once. The first (common) wrapper configure the emacs load path while the second wrapper defines `GIO_EXTRA_MODULES`, `GDK_PIXBUF_MODULE_FILE`,`XDG_DATA_DIRS`… However even if I bypass these wrappers and directly execute the binary file I can see that the style is different.

```
# Provides the good gtk style (installed from the system):
$ /nix/store/887536bk4zhcirg95ynhqr9klkfnm0z8-emacs-28.1/bin/.emacs-28.1-wrapped
# Provides no gtk style (installed from home manager)
$ /nix/store/lnzzlb1b0i0q03hkxacgpivib05rv3vm-emacs-28.2/bin/emacs
```

Hovewer I am not sure to understand what's different… I'm using
```
  programs.emacs = {
    enable = true;
    package = pkgs.emacs;
    # …
  }
```
in home manager and
```
  environment.systemPackages = with pkgs; [
    ((emacsPackagesFor emacs).emacsWithPackages (epkgs: [
      epkgs.vterm
    ]))
    libvterm
    shellcheck # Check if this is needed by doom or not.
  ];
```
They should use the same kind of binary no? (the hash may not correspond 100% as the system used a slightly older pin of nixpkgs)

**Comment by terlar** [comment]
This is not because of Home-Manager, see this for details:
https://github.com/NixOS/nixpkgs/pull/189543

**Comment by tobiasBora** [comment]
Ho thanks a lot for pointing that! To get gtk back there is `emacs-gtk`.
