### ISSUE TITLE
bug: Config file Generated by Home-Manager is in the way.

### ISSUE THREAD

**Issue by DrRuhe** [nix-community/home-manager#3245]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Home manager repeatedly complains about `.config/fontconfig/conf.d/10-hm-fonts.conf` being in the way. 
Home manager created the file and deleting it (or the folders `.config/fontconfig` or `.config/fontconfig/conf.d`) does not permanently resolve it.

The part of config responsible for this behavior is this (from my [nixos-config](https://gitlab.com/DrRuhe/nixos-config/-/blob/main/config/user/programs/shell/fonts.nix)):
```
{ pkgs, ... }:{
  home.packages = with pkgs; [
      (nerdfonts.override { fonts = [ "ShareTechMono" ]; })
      twitter-color-emoji
      fira-code
  ];
  fonts.fontconfig.enable = true;
}
```
The files differ in this way (which to me looks like they only change in the nix-store paths, which is expected since I am switching to a config with a different hash):
```
$ diff /home/caspar/.config/fontconfig/conf.d/10-hm-fonts.conf /nix/store/cxl5dciv3caajydah981w5wmrvi0cw49-home-manager-files/.config/fontconfig/conf.d/10-hm-fonts.conf
2c2
< <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
---
> 
3a4,5
> 
> <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
5,12c7,15
<  <include ignore_missing="yes">/nix/store/qay1f1iblg89cmpl2macxi2n2dwia5ny-home-manager-path/etc/fonts/conf.d</include>
<  <include ignore_missing="yes">/nix/store/qay1f1iblg89cmpl2macxi2n2dwia5ny-home-manager-path/etc/fonts/fonts.conf</include>
<  <dir>/nix/store/qay1f1iblg89cmpl2macxi2n2dwia5ny-home-manager-path/lib/X11/fonts</dir>
<  <dir>/nix/store/qay1f1iblg89cmpl2macxi2n2dwia5ny-home-manager-path/share/fonts</dir>
<  <dir>/etc/profiles/per-user/caspar/lib/X11/fonts</dir>
<  <dir>/etc/profiles/per-user/caspar/share/fonts</dir>
<  <cachedir>/nix/store/qay1f1iblg89cmpl2macxi2n2dwia5ny-home-manager-path/lib/fontconfig/cache</cachedir>
<  <dir>~/.local/share/fonts</dir>
---
>   <include ignore_missing="yes">/nix/store/ssjcsgjk0p12zw0bvqqz2mrwm9cn1byg-home-manager-path/etc/fonts/conf.d</include>
>   <include ignore_missing="yes">/nix/store/ssjcsgjk0p12zw0bvqqz2mrwm9cn1byg-home-manager-path/etc/fonts/fonts.conf</include>
> 
>   <dir>/nix/store/ssjcsgjk0p12zw0bvqqz2mrwm9cn1byg-home-manager-path/lib/X11/fonts</dir>
>   <dir>/nix/store/ssjcsgjk0p12zw0bvqqz2mrwm9cn1byg-home-manager-path/share/fonts</dir>
>   <dir>/etc/profiles/per-user/caspar/lib/X11/fonts</dir>
>   <dir>/etc/profiles/per-user/caspar/share/fonts</dir>
> 
>   <cachedir>/nix/store/ssjcsgjk0p12zw0bvqqz2mrwm9cn1byg-home-manager-path/lib/fontconfig/cache</cachedir>
```

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.11 (Raccoon), 22.11.20220912.5f326e2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05"`
 - channels(jakob): `"home-manager-22.05.tar.gz, nixos"`
 - channels(caspar): `"home-manager-22.05.tar.gz, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
```

**Comment by phpcitizen** [comment]
Having the same issue here.

**Comment by DrRuhe** [comment]
Since this has not happened to me anymore, I am closing this.

**Comment by PgBiel** [comment]
Just had the exact same issue (with the same filenames and all), so it might not be solved yet (using 23.05 branch though, commit 07c347bb50994691d7b0095f45ebd8838cf6bc38 - so not master). I wonder if some package - such as nerdfont - could be creating that file as some sort of residual artifact (or perhaps trying to read it, seeing it's a link and replacing with its actual contents due to some bug)? Could also be a bug somewhere in home-manager though (I personally find that harder to be the case, however).

**Comment by makoConstruct** [comment]
This is happening to me without any reference to fonts in my hm config :(

**Comment by makoConstruct** [comment]
Relevant code: https://github.com/nix-community/home-manager/blob/2aff324cf65f5f98f89d878c056b779466b17db8/modules/misc/fontconfig.nix#L75

@rycee any ideas as to why might be happening or how I could troubleshoot?

The only relevant detail about my setup that I can think of, that might have anything to do with this is that I have a ~/fonts/ directory (where I collect my fav fonts), but I didn't think anything would use that, and removing it doesn't prevent the issue.

Using KDE.

Tried disabling fontconfig but this seemed to cause all sorts of issues. It's enabled by default.
