### ISSUE TITLE
Using https://github.com/shlevy/nix-plugins with HM

### ISSUE THREAD

**Issue by x10an14** [nix-community/home-manager#3246]
### Description

Can I (in HM config), configure my `nix` instance (like with `config.nix.settings.experimental-features = ["(...)"];`), and have HM use _this_ `nix` to built all the rest of it?

I'm asking due to wanting to make use of [`nix-plugins`](https://github.com/shlevy/nix-plugins) on a non-nixos machine.

#2324 Seems relevant, but I don't know for sure.

**Comment by berbiche** [comment]
Hi,

This is technically not possible due to how Home Manager uses the Nix module system.

We don't have any plans to support setting system-wide settings from Home Manager outside of what is absolutely required by the "system" (nixos/nix-darwin) modules themselves.

**Comment by x10an14** [comment]
>@berbiche: This is technically not possible due to how Home Manager uses the Nix module system.

Could you supply me with a reference I could read up on, to understand why this is so?

>@berbiche: We don't have any plans to support setting system-wide settings from Home Manager outside of what is absolutely required by the "system" (nixos/nix-darwin) modules themselves.

Hmm, that makes perfect sense to me except in one regard - why does this require setting "system-wide" settings, like the ones found in nixos/nix-darwin?
The plugins I refer to only require re-compilation of the `nix` binary - something done all the time in the nix eco-system.

At least, that's according to my (very possibly faulty/lacking) understanding.
