### ISSUE TITLE
bug: bash's historyIgnore breaks when using spaces

### ISSUE THREAD

**Issue by kip93** [nix-community/home-manager#3249]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Bash's `HISTIGNORE` variable supports spaces, as described in [the docs](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html), but when configuring it via home-manager, the value is not properly quoted to avoid issues with spaces. Here's a minimal example of the problem:
```nix
{ ... }:
{
  home-manager.users.username.programs.bash = {
    enable = true;
    historyIgnore = [
      "cd .."
    ];
  };
}
```
Now, this can easily be workaround by using `historyIgnore = [ "'cd ..'" ]` or `historyIgnore = [ "'" "cd .." "'" ]` (the latter being more useful if there's many commands that need to be wrapped); but I expected this to be handled automatically by home manager. Based on the [source code](https://github.com/nix-community/home-manager/blob/f5e9879/modules/programs/bash.nix#L204-L206) this seems like it would not be that hard to change:
```diff
           // optionalAttrs (cfg.historyIgnore != []) {
-            HISTIGNORE = concatStringsSep ":" cfg.historyIgnore;
+            HISTIGNORE = "'${concatStringsSep ":" cfg.historyIgnore}'";
           }
```
though this would be a breaking change, since it would have some unintended side effects on existing configurations. Alternatively, the docs could be updated to at least notify that this is the expected behaviour and you are supposed to handle spaces on your own, and not end up like me spending an hour trying to figure out the error message that get spit out (since it outputs `HISTIGNORE=cd ..` and cries `bash: ..: command not found`, because it is trying the `..` command with the env variable `HISTIGNORE=cd`; and even if you alias `..` to `cd ..`, aliases only get applied later on).

### Maintainer CC

@rycee

### System information

```markdown
 - system: `"aarch64-linux"`
 - host os: `Linux 4.9.140-tegra, NixOS, 22.11 (Raccoon), 22.11.20220718.2e3f6ef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Thanks for the report, should be fixed now 🙂
