### ISSUE TITLE
Allow home files symlinked to global location

### ISSUE THREAD

**Issue by shlevy** [nix-community/home-manager#3257]
Currently I'm doing this:

```nix
{ pkgs, ... }: let
  creds = pkgs.runCommand "creds" {} ''
    ln -sv /home/shlevy/creds $out
  '';
in {
  home-manager.users.shlevy.home.file ={
    ".aws" = {
      source = "${creds}/aws";
    };
    ".ssh" = {
      source = "${creds}/ssh";
    };
    ".netrc" = {
      source = "${creds}/netrc";
    };
  };
}
```

It would be nice if I didn't need to add the extra indirection and could instead have `source` be treated simply as a symlink target when some appropriate flag is set.

**Comment by rycee** [comment]
Maybe `mkOutOfStoreSymlink` does what you want. See https://github.com/nix-community/home-manager/blob/de3758e31a3a1bc79d569f5deb5dac39791bf9b6/tests/modules/files/out-of-store-symlink.nix#L11

**Comment by shlevy** [comment]
Ah that's basically shorthand for what I'm doing here, I guess that works for now.
