### ISSUE TITLE
bug: gmailieer -> lieer

### ISSUE THREAD

**Issue by t184256** [nix-community/home-manager#3261]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

nixpkgs 79d3ca0 errors out with the following:

```
error: 'gmailieer' has been renamed to/replaced by 'lieer'
```

### Maintainer CC

@tadfisher

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.68, NixOS, 22.11 (Raccoon), 22.11.20220925.79d3ca0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tadfisher** [comment]
As a workaround, you can enable [allowAliases](https://nixos.org/manual/nixpkgs/stable/#opt-allowAliases) in your nixpkgs config until home-manager picks up the change.

**Comment by t184256** [comment]
Or, more narrowly, `programs.lieer.package = pkgs.lieer;`.
