### ISSUE TITLE
bug: kdeconnect has been renamed to plasma5Packages.kdeconnect-kde

### ISSUE THREAD

**Issue by samsky72** [nix-community/home-manager#3274]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The kdeconnect has been renamed to plasma5Packages.kdeconnect-kde at 24.09.2022. So kdeconnect.nix module need to be updated.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.19.10-zen1, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Dietr1ch** [comment]
The service should point to the new package

https://github.com/nix-community/home-manager/blob/master/modules/services/kdeconnect.nix#L8
