### ISSUE TITLE
Unpublish https://rycee.gitlab.io/home-manager/

### ISSUE THREAD

**Issue by mightyiam** [nix-community/home-manager#3279]
Redirect it to the canonical manual.

It's confusing to have two. It ranks higher in Google.

**Comment by mightyiam** [comment]
No no no no. Bad bot. Who has the power to give me the power to do this myself?

**Comment by rycee** [comment]
The gitlab version of the documentation is kept up to date and I don't want to break links there. I've added a rycee.gitlab.io/robots.txt now, though, that discourages indexing.
