### ISSUE TITLE
autotag PRs via the "labeler" github bot

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#3288]
I quite like the autolabeling done in nixpkgs via the file https://github.com/NixOS/nixpkgs/blob/master/.github/labeler.yml (I would like to autotag neovim PRs when a neovim file is touched for instance).

Do you think we could enable this on the repo please ? @rycee

**Comment by rycee** [comment]
Seems fine to me. Can you create such a file? Anything needed to be done with the repo, like adding a github app or something?

**Comment by teto** [comment]
I think you need to enable this action https://github.com/marketplace/actions/auto-labeler I can push a small file as well

**Comment by rycee** [comment]
Had a look and it seem this is not needing any particular enabling? Perhaps it is sufficient to create a workflow like in https://github.com/jimschubert/labeler-action#create-a-workflow

**Comment by teto** [comment]
I've created https://github.com/nix-community/home-manager/pull/3294, feel free to push to it
