### ISSUE TITLE
vscode-extensions.sheaf.groovylambda

### ISSUE THREAD

**Issue by TheOddler** [nix-community/home-manager#3305]
### Description

For Haskell development I'm currently using the extension [Groovy Lambda](https://marketplace.visualstudio.com/items?itemName=sheaf.groovylambda) for more colour scopes support. However, it does not seem to exist when trying to manage vscode through home-manager.

It would be swell if I can manage this one through home-manager too. Or if anybody knows an alternative.

**Comment by loicreynier** [comment]
This is not related to Home Manager but to the [Nix package collection](https://github.com/NixOS/nixpkgs). You can have a look at the VSCode extensions [Nix packages source code](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/applications/editors/vscode/extensions/default.nix) to see how you could build your own package for the extension and add it to Home Manager's `program.vscode.extensions`.

**Comment by TheOddler** [comment]
I see, I'll look into that! Thank you :D
