### ISSUE TITLE
bug: `wayland.windowManager.sway.config.output` does not work correctly when setting multiple options

### ISSUE THREAD

**Issue by mdarocha** [nix-community/home-manager#3312]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When using [`wayland.windowManager.sway.config.output`](https://rycee.gitlab.io/home-manager/options.html#opt-wayland.windowManager.sway.config.output) to configure multiple values on an output, like this:

```nix
"Acer Technologies SA220Q 0x0000F37B" = {
 mode = "1920x1080@60Hz";
 subpixel = "rbg";
};
```

the resulting config is incorrectly generated, which casues sway to display errors and ignore any setting other than the first:

```
output "Acer Technologies SA220Q 0x0000F37B" {
mode 1920x1080@60Hz
subpixel rbg
}
```

According to the [docs](https://github.com/swaywm/sway/wiki#display-configuration), it should be:
```
output "Acer Technologies SA220Q 0x0000F37B" mode 1920x1080@60Hz subpixel rbg
```

### Maintainer CC

@alexarice 
@sumnerevans 
@SebTM 
@oxalica 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.68, NixOS, 22.11 (Raccoon), 22.11.20221006.598f83e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/if56vv9237zafkzgzcdkqxf2lmp86myq-source`
```

**Comment by SebTM** [comment]
Disclaimer I'm not a sway user. From man-page which sounds :

```
       Commands can also be given as a block in the form command { <subcommands...> }.
       Anything before the opening { will be prepended to the lines inside the block.
       For example:

           output eDP-1 {
                background ~/wallpaper.png fill
                resolution 1920x1080
           }

       is identical to

           output eDP-1 background ~/wallpaper.png fill
           output eDP-1 resolution 1920x1080
```

To your problem, can't find something about an option `subpixel`?

**Comment by rcerc** [comment]
`rbg` is not one of the values the `subpixel` command accepts according to the manual page. Does using one of the listed values (`rgb`, `bgr`, `vrgb`, `vbgr` or `none`) still cause an error?

**Comment by mdarocha** [comment]
> `rbg` is not one of the values the `subpixel` command accepts according to the manual page. Does using one of the listed values (`rgb`, `bgr`, `vrgb`, `vbgr` or `none`) still cause an error?

Yeah, that was it, stupid mistake :)
