### ISSUE TITLE
bug: Himalaya broken config

### ISSUE THREAD

**Issue by toastal** [nix-community/home-manager#3330]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The 0.6.0 Himalaya release has changed some of the syntax for for the config which on unstable is now causing failures for me. https://github.com/soywod/himalaya/wiki/Configuration:config-file

### Maintainer CC

@ambroisie 

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.14, NixOS, 22.11 (Raccoon), 22.11.20221014.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(toastal): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ambroisie** [comment]
I have actually stopped using this module, @toastal if you want to become the maintainer you can add yourself.

**Comment by toastal** [comment]
Looking into this (though I'd prefer not to maintain things on GitHub)

**Comment by NomisIV** [comment]
I'm also looking into this. I will probably have something working either today or tomorrow in this PR: https://github.com/nix-community/home-manager/pull/3354

**Comment by NomisIV** [comment]
I was made aware of this PR: https://github.com/nix-community/home-manager/pull/3332
