### ISSUE TITLE
bug: `attribute 'numbers' missing` in picom module

### ISSUE THREAD

**Issue by samuela** [nix-community/home-manager#3340]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After running `nix-channel --update`, I'm now seeing an error when attempting `home-manager switch`:
```
❯ home-manager switch
error: attribute 'numbers' missing

       at /Users/sam.ainsworth/.nix-defexpr/channels/home-manager/modules/services/picom.nix:144:14:

          143|     activeOpacity = mkOption {
          144|       type = types.numbers.between 0 1;
             |              ^
          145|       default = 1.0;
(use '--show-trace' to show detailed location information)
```
It appears to be caused by https://github.com/nix-community/home-manager/commit/28334988dbd613012b1b085c37d144889f8e2abc.

Full log available here: https://gist.github.com/samuela/1803f504d57b74b57d01aa86f8d8102c

### Maintainer CC

@thiagokokada @ncfavier 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(sam.ainsworth): `"home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by samuela** [comment]
FWIW `services.picom.enable = lib.mkForce false;` does not help

**Comment by samuela** [comment]
can confirm that https://github.com/nix-community/home-manager/commit/28334988dbd613012b1b085c37d144889f8e2abc is the breaking commit, its parent https://github.com/nix-community/home-manager/commit/6dc8a43f397c92afbc3f771385ac803d96d5eeb5 works

**Comment by ncfavier** [comment]
> My Nixpkgs and Home Manager versions are in sync

Are you sure? Try updating your nixpkgs channel. The commit has [been](https://nixpk.gs/pr-tracker.html?pr=181834) in channels for a while.

**Comment by samuela** [comment]
Ah indeed, you're right. For some reason my nixpkgs channel was owned by root so I had to run `sudo nix-channel --update` to get it working. Thanks @ncfavier!

Side note: it's quite annoying that `nix-channel --update` doesn't provide more user-friendly output, esp. show what channels it tried to update and what commits they were on before/after the update... perhaps i should create an issue for that one of these days

**Comment by pepijno** [comment]
The issue is still present when using a flake with the altest 22.05 channel.

**Comment by ncfavier** [comment]
You should use the [corresponding](https://github.com/nix-community/home-manager#releases) branch of home-manager: `release-22.05`.
