### ISSUE TITLE
bug: borgmatic service error, no `sleep` found

### ISSUE THREAD

**Issue by mentalblock** [nix-community/home-manager#3348]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The borgmatic service which creates a systemd service and associated timer to run periodic backups seems to have an unqualified `sleep` invocation. The specific configuration in question I believe is: https://github.com/nix-community/home-manager/blob/69d19b9839638fc487b370e0600a03577a559081/modules/services/borgmatic.nix#L61

I do not have any experience creating modules, but I would think that the sleep referenced should reference the `coreutils` package and the `bin/sleep` underneath it to ensure that the invocation works.

Here is the error:
```
borgmatic.service: Failed at step EXEC spawning sleep: No such file or directory
```

Here is the fully rendered systemd service in my user configuration:
```
[Service]
CPUSchedulingPolicy=batch
ExecStart=/nix/store/fcb987c6axvjmn2scd2pr9b2hxf4iang-systemd-251.4/bin/systemd-inhibit \
  --who="borgmatic" \
  --why="Prevent interrupting scheduled backup" \
  /nix/store/891y17vxv0sg7jkjdh7dagq4y89ip3wg-borgmatic-1.7.2/bin/borgmatic \
    --stats \
    --verbosity -1 \
    --list \
    --syslog-verbosity 1

ExecStartPre=sleep 3m
IOSchedulingClass=best-effort
IOSchedulingPriority=7
IOWeight=100
LogRateLimitIntervalSec=0
Nice=19
Restart=no
Type=oneshot

[Unit]
ConditionACPower=true
Description=borgmatic backup
```

Here is the relevant output of `systemctl show ...` for the issue:
```
ExecStartPre={ path=sleep ; argv[]=sleep 3m ; ignore_errors=no ; start_time=[Sun 2022-10-23 15:11:45 EDT] ; stop_time=[Sun 2022-10-23 15:11:45 EDT] ; pid=242507 ; code=exited ; status=203 }
```

### Maintainer CC

@DamienCassou

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11pre419369.301aada7a64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(user): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by DamienCassou** [comment]
Thank you very much for the detailed issue. I believe PR #3349 will fix the problem.

**Comment by mentalblock** [comment]
Is the `sleep` invocation necessary given the timer delay at https://github.com/nix-community/home-manager/blob/69d19b9839638fc487b370e0600a03577a559081/modules/services/borgmatic.nix#L81 ?

**Comment by mentalblock** [comment]
Thanks for the quick followup. This simplified my backup configuration tremendously.

**Comment by DamienCassou** [comment]
> Is the sleep invocation necessary given the timer delay at `RandomizedDelaySec = "10m";`

Excellent question. I took this from https://projects.torsion.org/borgmatic-collective/borgmatic/src/branch/master/sample/systemd.

As I understand it, the `RandomizedDelaySec` prevents several computers using the same systemd unit from starting at the same time to avoid sending too many requests to the same server in parallel. The `sleep` call prevents while the computer is starting. Having both is important because `RandomizedDelaySec` provides a random delay which might be 0 from time to time. When it is, you still don't want the backup to start immediately when the computer boots.

**Comment by mentalblock** [comment]
This makes a lot of sense. Thanks for the explanation.
