### ISSUE TITLE
bug: search.json.mozlz4 is not being copied/symlinked into firefox profile 

### ISSUE THREAD

**Issue by pshirshov** [nix-community/home-manager#3350]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

@kira-bruneau I've switched to `master` from your fork and now the build passes but for some reason the `search.json.mozlz4` is not being copied into my firefox profile.

I'm not sure what's the problem it worked perfectly before the switch.

The file is definitely in the nix store:

```
❯ find /nix/store -name "*search.json.mozlz4*" -print
/nix/store/5m8svcwjzhw1gsfy4z7vdxq1g6qjnw76-search.json.mozlz4.drv
/nix/store/18v232fya27q4cfgprk9gasrqjrq6q73-search.json.mozlz4
/nix/store/xvigdy7p49bxq36d1vspazky3bjdw478-home-manager-files/.mozilla/firefox/main/search.json.mozlz4
```

The content of that file is correct and there is just one copy in the store.

### System information

```markdown
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/j5bmvfdggihnlq2bkpxp69w6l3amfknp-nix-info
copying path '/nix/store/j5bmvfdggihnlq2bkpxp69w6l3amfknp-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.16, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-21.11pre333218.263ef4cc414, home-manager"`
 - channels(pavel): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pshirshov** [comment]
Hmm. Works on macOS.

**Comment by kira-bruneau** [comment]
Hmm that's strange, not much has changed from my branch, I'll try out master to see if I can reproduce it.

**Comment by kira-bruneau** [comment]
Hmm, it seems ok to me, what happens when you run:

```
sudo systemctl restart home-manager-kira.service
```

It's possible that it's failing for some reason, which would prevent the file from being linked in.

**Comment by pshirshov** [comment]
I guess the problem is that there may be a situation where nothing has changed in the nix formula so the generated derivation remains the same, but the outer world (firefox profile) changes (firefox loves to overwrite this damn file). But the home-manager service is not being restarted because it restarts only after changes in the nix formulas themselves.
