### ISSUE TITLE
bug: hm-setup-env: Exec format error

### ISSUE THREAD

**Issue by gilice** [nix-community/home-manager#3355]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I don't know when the issue started appearing, but I can't do `nixos-rebuild switch` with the latest home-manager and nixpkgs stable anymore. The command fails with `home-manager-user.service: Failed to execute /nix/store/5azdr7593lbbgf2l654d7qsr0acnmzzj-hm-setup-env: Exec format error`. After a reboot, I can no longer log in with the new nixos generation.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11pre420742.f994293d1eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Hi @gilice. I haven't seen that error before. Could you paste the output of

    systemctl cat home-manager-user.service

and

    cat /nix/store/5azdr7593lbbgf2l654d7qsr0acnmzzj-hm-setup-env

?

**Comment by gilice** [comment]
Hey @rycee and sorry for the delay!
I am getting another error now; at build time, not even from systemd:
`/nix/store/sgc72309zc4cwdsxij5j30sa7b1da418-get-hm-version: line 4: cd: /nix/store/3lmaisjxm89kiphsiivmad987rxnq03r-home-manager: No such file or directory`. I guess it has something to do with 32fe7d2ebb7e338ad95a3ea9393fc6ad681368ce?

**Comment by gilice** [comment]
I can still boot up into the old generation tho, so here is the stuff you asked:
https://gist.github.com/gilice/5f6a23a08212d99dbd73dfea5d9efff8

**Comment by malSet** [comment]
> Hey @rycee and sorry for the delay! I am getting another error now; at build time, not even from systemd: `/nix/store/sgc72309zc4cwdsxij5j30sa7b1da418-get-hm-version: line 4: cd: /nix/store/3lmaisjxm89kiphsiivmad987rxnq03r-home-manager: No such file or directory`. I guess it has something to do with [32fe7d2](https://github.com/nix-community/home-manager/commit/32fe7d2ebb7e338ad95a3ea9393fc6ad681368ce)?

I'm getting the same error as well, on my main system as well as a completely fresh install (with default home.nix) on a separate system, both non-NixOS.

**Comment by ShinobiX9X** [comment]
Hello, I got the exact same error:
`building Nix...
building the system configuration...
these 5 derivations will be built:
  /nix/store/471amc6qhg3rcsnr8frzvyn1419wnav8-home-manager-generation.drv
  /nix/store/3fvvm0b3zy24w5rg3hmnrzyywsj3w5ap-unit-home-manager-dimic.service.drv
  /nix/store/qln29ghs3aqh6r95q0x5n9n6qh215mkb-system-units.drv
  /nix/store/y4q5zx6lvw8kkw1l529d52ga3h7na282-etc.drv
  /nix/store/kh4c3shg9njw61zlbmasglis6kljh288-nixos-system-nixos-22.11pre420742.f994293d1eb.drv
building '/nix/store/471amc6qhg3rcsnr8frzvyn1419wnav8-home-manager-generation.drv'...
/nix/store/sgc72309zc4cwdsxij5j30sa7b1da418-get-hm-version: line 4: cd: /nix/store/3lmaisjxm89kiphsiivmad987rxnq03r-home-manager: No such file or directory
error: builder for '/nix/store/471amc6qhg3rcsnr8frzvyn1419wnav8-home-manager-generation.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/3fvvm0b3zy24w5rg3hmnrzyywsj3w5ap-unit-home-manager-dimic.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qln29ghs3aqh6r95q0x5n9n6qh215mkb-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y4q5zx6lvw8kkw1l529d52ga3h7na282-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kh4c3shg9njw61zlbmasglis6kljh288-nixos-system-nixos-22.11pre420742.f994293d1eb.drv' failed to build`

Info:

- OS: NixOS 22.11pre421109.5bdb380ee7f (Raccoon) x86_64
- Kernel: 6.0.3

**Comment by rycee** [comment]
I added f67649307d4f81d8fbac68c19d1d1c564ab26dca yesterday. Does the issue still occur after that?

**Comment by ShinobiX9X** [comment]
I have a fresh install of Nixos, and only added the home-manager channel (master.tar.gz) today.

**Comment by gilice** [comment]
@rycee The build phase seems to work, but I still get the original (exec format) error

**Comment by rycee** [comment]
Have a look at  #3359 for a new attempt at generating hm-version.

@gilice About the actual bug report. The empty `/nix/store/5azdr7593lbbgf2l654d7qsr0acnmzzj-hm-setup-env` file is quite odd. That file is generated by `pkgs.writeScript`. I haven't seen that function failing to produce output before, does it always produce an empty file? Is your overall Nix installation working OK? See https://github.com/nix-community/home-manager/blob/213a06295dff96668a1d673b9fd1c03ce1de6745/nixos/default.nix#L66-L79

**Comment by ShinobiX9X** [comment]
Hello, this is what I did and it did work for me now.
(maybe not al the steps are needed, I am just beginning with nixos and home-manager, didn´t touch flakes yet)
`
sudo nix-channel --remove home-manager
sudo nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
sudo nix-channel --update
sudo nixos-rebuild switch`

Thank you :)

**Comment by rycee** [comment]
I'm glad you got it to work! I imagine something very odd had happened to your install to cause something as basic as `writeScript` to fail.
