### ISSUE TITLE
bug: string values in `.gitconfig` have undesired quotes

### ISSUE THREAD

**Issue by leungbk** [nix-community/home-manager#3358]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Most fields in `.gitconfig` have string values with surrounding double quotes:

```
[user]
	email = "alice@bob.spam"
	name = "First Last"
	signingKey = "123ABC"
```

This appears to lead to cases where, in `git` logs, the name and email non-deterministically are (or, are not) surrounded by double quotes; to see this, go into the Nixpkgs repo and compare the output of

```
❯ git log --author="my_github_handle@posteo.net"
```

and 

```
❯ git log --author="\"my_github_handle@posteo.net\""
```

The fact that some commits aren't attributed to the right name can be annoying when you wish to see all commits by some user.

I think most, if not all, of the fields should be stripped of double quotes.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.3, NixOS, 22.11 (Raccoon), 22.11.20221025.03a00f6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pleshevskiy** [comment]
We can use quotes for string type in the `ini` file. I have the same configs and your problem doesn't affect me 🤔

**Comment by rycee** [comment]
I haven't encountered this either and searched various git commits for my email with quotes, without finding any.

Also, the quotes and escaping is important in the git module, see https://github.com/nix-community/home-manager/pull/1209 so we cannot avoid having those.

@leungbk do you know which revision of Home Manager and/or configuration you used when the quotes appeared?

**Comment by leungbk** [comment]
Hmm, looking through the nixpkgs repo, the last time I got a commit outputting my info in quotes was eight months ago. I am not sure what rev of Home Manager I was using back then, so I shall close for now. Sorry for the noise.
