### ISSUE TITLE
bug: cant open gparted with app icon if installed thru home-manager 

### ISSUE THREAD

**Issue by m911t** [nix-community/home-manager#3404]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I installed gparted through home-manager, but can't open it using the app icon, does open using sudo gparted though. Installing gparted thru the configuration.nix file does work correctly. Also, when installed thru configuration.nix, the screen that asks for the password displays the correct message "authentication is required to open the Gnome Partition Editor as root".

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.7-zen1, NixOS, 22.11 (Raccoon), 22.11pre424584.667e5581d16`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(m911t): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hacker1024** [comment]
This can occur due to issues with Wayland compatibility. It may be worked around by using a desktop environment permission elevator such as `kdesu` on KDE.

**Comment by ncfavier** [comment]
In order to get an authentication request via polkit when you run gparted as non-root, you need the `${gparted}/share/polkit-1/actions/org.gnome.gparted.policy` file to be installed system-wide under `/run/current-system/sw`, because that's where polkit looks for policies. This is not something Home Manager can fix.

**Comment by m911t** [comment]
Should I then report this to nixpkgs?

**Comment by ncfavier** [comment]
No, I'm saying this is the way it should work. System utilities should be installed system-wide.

**Comment by m911t** [comment]
gotcha, thanks

**Comment by necauqua** [comment]
Hi, I was living with this issue forever (and opening gparted with `sudo gparted` in terminal) until I finally learned about how it works.

My suggestion is to make an assertion (of some sort) to prevent gparted from being installable with home manager, or at least a warning - would have saved me a few hours :sweat_smile:
