### ISSUE TITLE
bug: aerc display error message instead of message

### ISSUE THREAD

**Issue by a12l** [nix-community/home-manager#3420]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When opening a message  in `aerc` I only see this message, I've tried several different messages from different senders (both automatic and manual).

![Screenshot from 2022-11-16 12-59-16](https://user-images.githubusercontent.com/38804798/202175338-0da291e1-e999-4809-ab7d-1dead9171242.png)

### Maintainer CC

@lukasngl 

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.77, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lukasngl** [comment]
> When opening a message  in `aerc` I only see this message, I've tried several different messages from different senders (both automatic and manual).

Hi, this is not an issue with the module but with the package:
https://github.com/NixOS/nixpkgs/pull/197736

Workaround: You could comment out/adapt the default filters in `~/.config/aerc/aerc.conf`.

**Comment by emmanuelrosa** [comment]
This was fixed by https://github.com/NixOS/nixpkgs/pull/204322
