### ISSUE TITLE
bug: fetchTree 

### ISSUE THREAD

**Issue by niksingh710** [nix-community/home-manager#3427]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

```
building the system configuration...
error: in pure evaluation mode, 'fetchTree' requires a locked input, at /nix/store/0vgw175vzq10avgcfpav1nig2mc6c283-source/modules/go/go.nix:7:29
(use '--show-trace' to show detailed location information)
```

I am trying to add `go.packages` using home-manager and getting this error.

```
{ config, pkgs, lib, ... }:
{
  programs.go = {
    enable = true;
    packages = {
#      "simplehttp" = builtins.fetchGit "https://github.com/niksingh710/simplehttp";
      "golang.org/x/text" = builtins.fetchGit "https://go.googlesource.com/text";
    };
  };
}
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.9, NixOS, 22.11 (Raccoon), 22.11.20221120.690ffff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.05"`
 - channels(niksingh710): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
If you are using Nix Flakes then I assume the plain `fetchGit` is disallowed. Try running with `--impure`. The option example/description should probably be improved to highlight this.

@rvolosatovs Anything you know about?

**Comment by niksingh710** [comment]
`--impure` did work
Didn't gave the result as i was expecting m trying to declare some packages from node and from go packages to be installed automatically while building but unable to figure out any way to do so.

as `--impure` flag is working m closing the issue.

**Comment by terlar** [comment]
You misses specifying what command you were running. But judging from the error message it seems you are using nix flakes, which requires pure evaluation. It is just as the error message says, when you are using `builtins.fetchTree` you also need to specify the hash. Alternatively use `pkgs.fetchgit`.

`builtins.fetchGit` is using `builtins.fetchTree` under the hood. But seems the fetchGit does not expose the ability to set the hash. So you would have to use `builtins.fetchTree` or as suggested `pkgs.fetchGit`.

**Comment by niksingh710** [comment]
> You misses specifying what command you were running. But judging from the error message it seems you are using nix flakes, which requires pure evaluation. It is just as the error message says, when you are using `builtins.fetchTree` you also need to specify the hash. Alternatively use `pkgs.fetchgit`.
> 
> `builtins.fetchGit` is using `builtins.fetchTree` under the hood. But seems the fetchGit does not expose the ability to set the hash. So you would have to use `builtins.fetchTree` directly or as suggested `pkgs.fetchgit`.
> 
> PS: I wrote this earlier, but forgot to post
> 

Thanks for clearing mate.
Yep I am using flakes.
