### ISSUE TITLE
bug: `programs.just.enable` causes zsh to error on start

### ISSUE THREAD

**Issue by NobbZ** [nix-community/home-manager#3449]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When one uses `programs.just.enable` it creates an entry in the `.zshrc` that causes `zsh` to print an error message on start.

The error is similar to the one below:

```text
_arguments:comparguments:327: can only be called from completion function
```

This has been reported by another user without a GH account in the inofficial nix discord, and I am posting it here on their behalf.

We were able to identify the following snippet:

https://github.com/nix-community/home-manager/blob/master/modules/programs/just.nix#L43-L45

Perhaps using `programs.zsh.plugins` would be a better option? Or any other way to extend the `FPATH` appropriately?

### Maintainer CC

For `just`:

* @maximsmol

For zsh (no maintainers in module, therefore pinging random commiters from first page of history)

* @rycee 
* @zimbatm 
* @oxalica 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.2, NixOS, 23.05 (Stoat), 23.05.20221125.5dc7114`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0pre20221126_534332c`
 - channels(nmelzer): `""`
 - channels(root): `"nixos-21.05"`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`

(ran this on my machine, though the issue is obvious and not related to my setup)
```

**Comment by maximsmol** [comment]
I'm able to reproduce but I don't use zsh so would prefer someone else give their opinion on the `FPATH` and `plugins` thing

For the record [`just` docs say to use
`fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)`
and make sure that something runs `compinit`](https://github.com/casey/just#shell-completion-scripts)

---

I'll look around some more for what other home-manager apps are doing, but ideally someone familiar with zsh should comment

---

I'll also try the fish integration and see if it's obviously broken, just in case

**Comment by maximsmol** [comment]
So actually my understanding is that we should delete the completion flags entirely due to [the nixpkgs for `just` installing the completions itself](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/just/default.nix#L56) and [the patch that makes home-manager use bash completions from the appropriate directories](https://github.com/nix-community/home-manager/pull/3131)

I confirmed that `bash`, `zsh`, and `fish` all have completions even when there is nothing explicit in their corresponding `rc` files

**Comment by maximsmol** [comment]
The module sans completion is also just an alias for `home.packages = [ nixpkgs.just ];` so it seems like we can just deprecate it entirely?

The only thing to save it would be to add support for https://github.com/casey/just#user-justfiles but it seems kind of ad hoc (alias for each shell?) and I don't use it

---

So here is what I propose:
- Turn the completion flags into no-ops to unbreak people who are already using them
- Add a deprecation message to the entire module
