### ISSUE TITLE
neovim: allow lua to be passed like vimscript in extraConfig

### ISSUE THREAD

**Issue by kjeremy** [nix-community/home-manager#3457]
### Description

Many tutorials (see: https://rsdlt.github.io/posts/rust-nvim-ide-guide-walkthrough-development-debug/) specify their configuration in lua. This works great for plugins where we can do things like:

```nix
{
  plugin = rust-tools-nvim;
  type = "lua";
  config = ''
    local rt = require("rust-tools")
    -- The rest of this is lua too...
  '';
}
```

but when it comes to writing more general non-plugin related lua there is no option. `programs.neovim.extraConfig` allows us to add vimscript to the configuration and we can then source a lua file but it would be great if there was an `extraConfigLua` or something that allowed us to write it inline,

**Comment by Ashe** [comment]
Would love this. My neovim configs are very ugly as I essentially inline lua ([example](https://github.com/Ashe/dotfiles/blob/9c61f00af82861650d1c26d77fc0f4e909562c24/home/modules/neovim/plugins/nvim-surround/default.nix)). While you can make a `.vim` file that then inline lua for the entirety of it it would be a lot nicer to just be able to take lua strings or files.

**Comment by teto** [comment]
@Ashe look at the first message, you can do
```
{ pkgs, ... }:

{
  # Configure neovim
  programs.neovim = {

    # Install nvim-surround
    plugins = with pkgs.vimPlugins; [{
      plugin = nvim-surround;
      type = "lua";
      config = ''
        -- nvim-surround  
        require('nvim-surround').setup({
          -- Configuration here, or leave empty to use defaults
        })
      '';
    }];
  };
}
```

HM master generates an init.lua by default now. 

@kjeremy a workaround is to dump your luacode along with a plugin.

**Comment by GuillaumeDesforges** [comment]
Had the same issues, I want to add some general lua config that is not specific to any plugin, so I went ahead and opened https://github.com/nix-community/home-manager/pull/3639.

**Comment by GuillaumeDesforges** [comment]
There should be a `extraLuaConfig` option now.
