### ISSUE TITLE
git: command not found for git-receive-pack and git-upload-pack

### ISSUE THREAD

**Issue by worldofpeace** [nix-community/home-manager#347]
I notice this when interacting with repositories in my LAN, I'll get errors like
```
command not found: git-receive-pack
fatal: Could not read from remote repository.
```
and similar for `git-upload-pack`.

So I have to set the path to it like `git push remote --upload-pack /home/worldofpeace/.nix-profile/bin/git-upload-pack`

I'm using the home-manager nixos module with:
```nix
programs.git = {
  enable = true;
  ...
};
```

**Comment by worldofpeace** [comment]
I noticed this is a problem with git in `environment.systemPackages` also. Not sure if this is normal but it's in the path so it should be able to find it.

**Comment by worldofpeace** [comment]
I just realized that I'm using home-manager for zsh and not using `programs.zsh.enable` and `users.users.<name?>.shell = "pkgs.zsh"` which set env vars so things like this in git work.

Is there something we can add to the git module in home-manager if someone is using any of the shells from home-manager?

**Comment by rycee** [comment]
If you don't want to use `programs.zsh.enable` then you need to manually make sure that

    ~/.nix-profile/etc/profile.d/hm-session-vars.sh

is sourced. For example by placing

```sh
. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
```

in your `.zshrc` file. I think you also have to add `programs.zsh.enable = true;` in your system `configuration.nix` file to make sure the system zsh configuration is generated.

**Comment by rycee** [comment]
@Infinisil, @uvNikita Am I right above in that `programs.zsh.enable = true` needs to be in the system configuration?
