### ISSUE TITLE
Reloading emacs packages without restarting emacs

### ISSUE THREAD

**Issue by aheaume** [nix-community/home-manager#3480]
### Description

Hi! 👋

I was looking for a way to reload emacs packages after `home-manager switch` but I couldn't find any, did I miss something? Anyway, I made my own:

```emacs-lisp
  (defun my-home-manager-reload ()
    (interactive)
    (let* ((which-emacs (shell-command-to-string "cat $(which emacs)"))
           (pattern (rx "newLoadPath+=(/nix/store/"
                        (group (* any))
                        "-emacs-packages-deps/share/emacs/site-lisp)"))
           (current-deps (when (string-match pattern which-emacs)
                           (match-string 1 which-emacs)))
           (subdirs (concat "/nix/store/" current-deps "-emacs-packages-deps/share/emacs/site-lisp/subdirs.el"))
           (native (concat "/nix/store/" current-deps "-emacs-packages-deps/share/emacs/native-lisp/")))
      (load-file subdirs)
      (when (boundp 'native-comp-eln-load-path)
        (add-to-list 'native-comp-eln-load-path native))))
```

It works like this

- I get the new path to load from `which emacs` and regexp my way to the new store path
- I call `load-file` on the `subdirs.el` file found in the store, the new packages will shadow the old ones
- I add the `native-lisp` directory to `native-comp-eln-load-path`

This much works for me. However, running `cat $(which emacs)` seems very brittle, is there another way to figure out the store path? Anybody wants to try it before I put it on melpa? Would it be useful to include it as an option in the emacs module directly instead?

Have a nice day 😄

**Comment by ParetoOptimalDev** [comment]
> This much works for me. However, running cat $(which emacs) seems very brittle, is there another way to figure out the store path? Anybody wants to try it before I put it on melpa? Would it be useful to include it as an option in the emacs module directly instead?

Now I remember what I was trying to say on mastodon..

Ideally the `exec /nix/store/yy2b2fxrslxz2pvlvlk62d2cv0w0nzcg-emacs-git-20221205.0/bin/emacs "$@"` line or similar would happen in another file and these:

```
export EMACSLOADPATH="${newLoadPath[*]}"
export emacsWithPackages_siteLisp=/nix/store/0hv8ndqcm7hbcrz3prg3np1pndpvjffi-emacs-packages-deps/share/emacs/site-lisp

export EMACSNATIVELOADPATH="${newNativeLoadPath[*]}"
export emacsWithPackages_siteLispNative=/nix/store/0hv8ndqcm7hbcrz3prg3np1pndpvjffi-emacs-packages-deps/share/emacs/native-lisp:
```

would be returned by bash functions.

Then you could execute just that script to get a list of the correct paths.

That would require changing the emacs derivation a bit upstream though.

**Comment by psionic-k** [comment]
Honestly just use Elpaca or straight.  No matter how you do reloading, you will have a slow workflow when you want to make changes to elisp in an immutable store.

**Comment by ParetoOptimalDev** [comment]
> Honestly just use Elpaca or straight. 

I tried straight for a long time, but I got weird issues too often that required using plumbing commands.

Using nix I've had 0 issues for many years.

It is a huge downside things aren't instant, but this would be a first step in improving that.
