### ISSUE TITLE
bug: borgmatic can't encode all configuration options

### ISSUE THREAD

**Issue by tehmatt** [nix-community/home-manager#3489]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Various useful options can't be configured via `extraConfigOption`, since it requires the options to be of type `str | bool | path | in`.  This makes it impossible to configure options like `exclude_patterns` (https://torsion.org/borgmatic/docs/reference/configuration/) which take a list of strings.

### Maintainer CC

@DamienCassou 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.5-1-default, openSUSE Tumbleweed, noversion, nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(user): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs```
```

**Comment by DamienCassou** [comment]
Are you willing to submit a PR to fix that?

**Comment by tehmatt** [comment]
Willing, but we'll see if I'm able to 😄
