### ISSUE TITLE
Feh module - Create a program.package option

### ISSUE THREAD

**Issue by Wisehh** [nix-community/home-manager#3495]
### Description

Because feh can extend their capabilities by adding a full imlib2 library (i.e. support for .heic, .svg, etc), I had to disable the module to install a overrided feh package with the changes. So I want to ask if makes sense to add an `program.feh.package` option to the feh module for this?

I remain attentive to what you think, and thanks in advance.

**Comment by rycee** [comment]
If you make a PR that adds such an option then I'm pretty certain it would be accepted. See, e.g.,  #3456.

**Comment by Wisehh** [comment]
Hello again.

I am trying to test that the option (added in home-manager/modules/programs/feh.nix) works correctly, however when I try to test it I get the following error.

```
error: The option `programs.feh.package' does not exist. Definition values:
       - In `/nix/store/6l7czsqbmabj43msi8ic2ydd9566vqng-source/home-manager/home.nix': <derivation feh-3.9>
(use '--show-trace' to show detailed location information)
```

To run my local copy of home-manager I have tried the two options mentioned in the [contribution guide](https://nix-community.github.io/home-manager/index.html#sec-contrib-getting-started). However neither works. To be exact I am running 

```
home-manager -I home-manager=/home/user/dev/home-manager switch --flake <path_to_my_flake>
```

I suspect that the flake inputs are overwriting the flag used in the command, but I'm not sure and if so I don't know how to correct it. Could you direct me how I can fix the error please?

**Comment by ncfavier** [comment]
With `--flake`, you probably want to use something like `home-manager --override-input home-manager /home/user/dev/home-manager`. Can you confirm that this works?

This should probably be added to the documentation.

**Comment by ncfavier** [comment]
Closed by https://github.com/nix-community/home-manager/pull/3552

**Comment by Wisehh** [comment]
> With --flake, you probably want to use something like home-manager --override-input home-manager /home/user/dev/home-manager. Can you confirm that this works?

Yes sir, I just did it and it works perfectly. The complete command to execute is then:

`home-manager --override-input home-manager <path_to_local_home-manager> switch --flake <path_to_flake>.`

> This should probably be added to the documentation.

It would be nice. I just thought of changing the url in the flake input directly and this solution is much simpler.

Thanks for your help.

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/3556
