### ISSUE TITLE
Update installation instructions in manual to use flakes

### ISSUE THREAD

**Issue by psionic-k** [nix-community/home-manager#3497]
`nix shell home-manager#home-manager` gets a shell with home manager available, using default registry for nixOS.
`nix flake new ~/.config/nixpkgs -t home-manager#` will copy the flake template.
From here, bootstrap remaining setup with no changes.

Faster, easier, and more modern than the older channels based workflow.

Also noticed I got a weird bug when I followed the advice to set `stateVersion` to 18.05:
```
error: cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)

       at /nix/store/xg2ijnl5x1g64dv2hn23g39k6r5fn3sx-source/modules/modules.nix:324:11:

          323|         else
          324|           <nixpkgs>);
             |           ^
          325|       _module.args.pkgs = lib.mkDefault pkgs;
(use '--show-trace' to show detailed location information)
```
I set stateVersion to 22.11 and everything proceeded normally.

**Comment by ncfavier** [comment]
We already have [an entire chapter](https://nix-community.github.io/home-manager/index.html#ch-nix-flakes) on flakes, is anything missing there?

> the advice to set `stateVersion` to 18.05

What advice are you referring to?
