### ISSUE TITLE
bug: gitui moves theme file

### ISSUE THREAD

**Issue by aidalgol** [nix-community/home-manager#3506]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

As of a recent update, `gitui` updates the theme file when run, without any further action from the user.  The effect of this when using `gitui` via the home-manager module (`programs.gitui.enable = true;`) is that the `~/.config/gitui/theme.ron` symlink to `/nix/store/aaaa...-home-manager-files/.config/gitui/theme.ron` is renamed to `~/.config/gitui/theme.ron.old` and a new regular file `~/.config/gitui/theme.ron` is created.

### Maintainer CC

@Mifom

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.12, NixOS, 22.11 (Raccoon), 22.11.20221210.9c5e57f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by rycee** [comment]
Spontaneously this seems like an issue for gitui, it shouldn't attempt to modify a read-only configuration file.

Maintainer CC: @Mifom

**Comment by aidalgol** [comment]
Looks like the reason gitui is doing this is because the theme file generated by the hm module is invalid:
```console
Theme loading error: 19:1: Unexpected missing field `selection_fg` in `Theme`
 Old file was renamed to "/home/aidan/.config/gitui/theme.ron.old".
 Defaults loaded and saved as "/home/aidan/.config/gitui/theme.ron"
```

**Comment by rycee** [comment]
Ah, perhaps it would work with this patch applied?

```patch
diff --git a/modules/programs/gitui.nix b/modules/programs/gitui.nix
index ee6572bc..710e3fd9 100644
--- a/modules/programs/gitui.nix
+++ b/modules/programs/gitui.nix
@@ -41,6 +41,8 @@ in {
           selected_tab: Reset,
           command_fg: White,
           selection_bg: Blue,
+          selection_fg: White,
+          cmdbar_bg: Blue,
           cmdbar_extra_lines_bg: Blue,
           disabled_fg: DarkGray,
           diff_line_add: Green,
@@ -55,6 +57,8 @@ in {
           danger_fg: Red,
           push_gauge_bg: Blue,
           push_gauge_fg: Reset,
+          tag_fg: LightMagenta,
+          branch_fg: LightYellow,
         )
       '';
       description = ''
```

**Comment by rycee** [comment]
@aidalgol If you try the latest HM master then the above patch is included. Hopefully it will resolve the issue, otherwise please comment and we'll reopen.
