### ISSUE TITLE
bug: nixos, nix completions not working with zsh when no desktop environment is active

### ISSUE THREAD

**Issue by GeFrIt42** [nix-community/home-manager#3521]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

hello community,

I have one computer used as remote server that i access via ssh, so no Desktop environment is necessary.
I have noticed that **completion of ZSH of the nix commands** stop to work if i disable the desktop environment ( in my case plasma5 ).

It stop to work only for **nix** commands 

when the lines shown in the pics are uncommitted it works, when it is commented out it stop to work:
![image](https://user-images.githubusercontent.com/9764492/209430243-89850191-241b-4bbf-a991-05e610238da8.png)

how to reproduce:
disable desktop environment
nix -- <tab><tab> 

can be possible that some dependency is missing? 
how can i debug this at the best?

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 22.11 (Raccoon), 22.11.20221220.cbe419e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by GeFrIt42** [comment]
It seems that somehow it does not load the completion for nix in /nix/store/gzd5wpvq9b5q5l3hvwpihgrhcrrllgi0-nix-2.11.1/share/zsh/site-functions

with kde /run/current-system/sw/share/zsh/site-functions is generated:
![image](https://user-images.githubusercontent.com/9764492/209466281-d6f57aff-c2e7-4f47-8a3a-79796dc73507.png)

![image](https://user-images.githubusercontent.com/9764492/209466262-1af01655-74e1-4526-b353-51f5c758da59.png)

without kde  /run/current-system/sw/share/zsh/is not generated :
![image](https://user-images.githubusercontent.com/9764492/209466336-58d0b310-92a4-48e9-b57f-d694abda8910.png)

I at this point this is not a bug of home-manager or completion.
Is this the correct place to address this?

**Comment by rycee** [comment]
Do you have `programs.zsh.enable = true` in your system configuration? It may be that you are lacking

    environment.pathsToLink = "/share/zsh";

This should be set automatically if the NixOS configuration contains `programs.zsh.enable = true`.

**Comment by GeFrIt42** [comment]
Hi Rycee,

I have done as advised ad it worked, thanks!

Now i am a little confused, why i need to have the same line **programs.zsh.enable = true** once in the system configuration and once more in the home manager, isn't this redundant?

**Comment by rycee** [comment]
@GeFrIt42 Yeah, may not be necessary to do `programs.zsh.enable = true` but you need at least `environment.pathsToLink = [ "/share/zsh" ]` to have access to completion of packages installed on the system level. See [`programs.zsh.enableCompletion`](https://nix-community.github.io/home-manager/options.html#opt-programs.zsh.enableCompletion).

**Comment by GeFrIt42** [comment]
Hi rycee,

Ok got it, thank you very much!
