### ISSUE TITLE
services.copyq.enable and possibly services.copyq.XWayland

### ISSUE THREAD

**Issue by AlistairKeiller** [nix-community/home-manager#3530]
Add a service for copyq, similar to services.flameshot.enable. In the future, it would also be nice to add services.copyq.XWayland, which would set QT_QPA_PLATFORM=xcb ( https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland ) so that pasting from copyq in Wayland works.

**Comment by rycee** [comment]
Resolved in #3713. I'm not sure about the `QT_QPA_PLATFORM` workaround since it may conflict with other usage? Might be easiest to just add through `home.sessionVariables.QT_QPA_PLATFORM = "xcb"` in your configuration.

**Comment by rycee** [comment]
@DamienCassou Do you think it would be possible to add

    Service.Environment.QT_QPA_PLATFORM = "xcb"

to the copyq systemd service? I guess it should be safe for X11 use and would seemingly make XWayland work.

**Comment by DamienCassou** [comment]
I don't understand how all of that is working but I opened a PR anyway. Feel free to merge if it helps.
