### ISSUE TITLE
bug: nvim-treesitter permission denied parsers 

### ISSUE THREAD

**Issue by ruanyouxing** [nix-community/home-manager#3548]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

This is my home-manager config:
```nix
 programs.neovim = {
       enable = true;
       viAlias = true;
       withPython3 = true;
       plugins = with pkgs.vimPlugins; [
         nvim-treesitter.withAllGrammars
       ];
  };
```
when I open up, it triggers this:
``` 
Could not create parser dir ' /nix/store/fw09jik29pb3jhfmmdk9g3rndwik7dlv-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser ':  Vim:E739: Cannot create directory /nix/store/fw09jik29pb3jhfmmdk9g3rndwik7dlv-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser: permission denied 
```
I searched many solutions for nvim-treesitter on home-manager but couldn't found anything related to this, even  `sudo chown -R 777` or something like that

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.1-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - channels(hungz): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by szaffarano** [comment]
Are you using a custom neovim configuration? 
It can be caused if have [ensure_installed](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/doc/nvim-treesitter.txt#L49) declared in your neovim config.  Since you install treesitter parsers through home-manager, you don't have to do it twice.

**Comment by giovanni-nappi** [comment]
> It can be caused if you have [ensure_installed](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/doc/nvim-treesitter.txt#L49) declared in your neovim config.

For me it was exactly the cause. Thank you for pointing it out

**Comment by hakkm** [comment]
The issue is now resolved. But I could not figure out why it works.
