### ISSUE TITLE
bug: error: The option `home.sessionVariables.XCURSOR_PATH' has conflicting definition values:

### ISSUE THREAD

**Issue by DanielSiepmann** [nix-community/home-manager#3551]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I've run `nix-channel --update` after the holidays followed by `home-manager switch`. This ends in the following output:

```
~ > home-manager switch
error: The option `home.sessionVariables.XCURSOR_PATH' has conflicting definition values:
       - In `/home/daniels/.nix-defexpr/channels/home-manager/modules/targets/generic-linux.nix': "$XCURSOR_PATH\${XCURSOR_PATH:+:}/home/daniels/.nix-profile/share/icons:/usr/share/icons:/usr/share/pixmaps"
       - In `/home/daniels/.nix-defexpr/channels/home-manager/modules/config/home-cursor.nix': "$XCURSOR_PATH\${XCURSOR_PATH:+:}/home/daniels/.nix-profile/share/icons"
(use '--show-trace' to show detailed location information)
```

### Maintainer CC

@polykernel, @league

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-135-generic, Ubuntu, 20.04.5 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(daniels): `"home-manager, nixpkgs, phps"`
 - nixpkgs: `/home/daniels/.nix-defexpr/channels/nixpkgs`
```

**Comment by polykernel** [comment]
My apologies, this is caused by https://github.com/nix-community/home-manager/pull/2902 where I forgot to set `home.sessionVariables` with a higher priority.

**Comment by DanielSiepmann** [comment]
Thanks @polykernel, I'm still new to nix and the ecosystem. Don't know why this appears now as those changes are already old.
Thanks for fast response and providing a fix.

**Comment by teto** [comment]
the merging strategy for sessionVariables has recently been changed to detect this kind of conflict.
