### ISSUE TITLE
bug: segmentation fault nix build

### ISSUE THREAD

**Issue by cchalc** [nix-community/home-manager#3554]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am getting a segmentation fault when trying to run a nix build with flakes. 
`[1]    88003 segmentation fault  nix build .#C02CT8TEMD6M`

It worked three weeks ago during my last [change](https://github.com/cchalc/nix-config/commit/c2cf3271e2829adf028a9470632b19098881fef4). I started tinkering around on another branch [add_lvim](https://github.com/cchalc/nix-config/commit/d064bab62fb461bf03088044b1175ead5ef32fe8) which ended up giving me the segmentation fault. I tried switching back to `main` but I am still getting the same thing and I don't know how to debug it. 

I have tried with `GC_DONT_GC` as indicated by @jonringer in this [comment](https://github.com/NixOS/nix/issues/4246#issuecomment-738888246) in Issue: [Segmentation fault when building ISO image with nixFlakes #4246](https://github.com/NixOS/nix/issues/4246) but that did not work. 

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(christopher.chalcraft): `"darwin, home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
If nix segfaults, that's an issue with nix, not home-manager. You should report the issue at nix, including a stack trace and/or a minimal reproducer.
