### ISSUE TITLE
bug: defining firefox search engines breaks configuration

### ISSUE THREAD

**Issue by gaelreyrol** [nix-community/home-manager#3569]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

If I define search engines without modifying the default one, the salt throws an error because profile.search.default is null.
Here is my configuration:   
```nix
{
  programs.firefox = {
    profiles.default = {
      search.engines = {
        "Nix Packages" = {
          urls = [{
            template = "https://search.nixos.org/packages";
            params = [
              { name = "type"; value = "packages"; }
              { name = "query"; value = "{searchTerms}"; }
            ];
          }];
          definedAliases = [ "@np" ];
        };
      };
    };
  };
}
```
Here is the error output:
```
error: cannot coerce null to a string

       at /nix/store/bajwvbdgy4ldwa4rdvfrn9iklpsglfb3-source/modules/programs/firefox.nix:631:37:

          630|
          631|               salt = profile.path + profile.search.default
             |                                     ^
          632|                 + disclaimer "Firefox";
(use '--show-trace' to show detailed location information)
```
The documentation does not specify that it is required to defined the default one to be able to add custom search engines.

### Maintainer CC

@rycee @kira-bruneau 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.15.85, NixOS, 23.05 (Stoat), 23.05.20221228.e182da8`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.12.0`
- channels(gael): `"nixos-unstable"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kira-bruneau** [comment]
Thanks for reporting this! We definitely should allow this without a default. The main issue is that the default engine might not always be Google. The hash is only for the default engine configuration, so I think if we just leave it off, Firefox will automatically choose the default.

I'll submit a PR once I'm off work!
