### ISSUE TITLE
bug: error: Unicode escape sequence is not a Unicode scalar value

### ISSUE THREAD

**Issue by etu** [nix-community/home-manager#3573]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The commit 709a87fe3300fc791734956125c4666a4fd42c69 that updated something that seems to be fairly innocent seems to have introduced something that doesn't eval on nix 2.3. It seems to work on newer versions of nix though.

Regardless it's a regression since it worked before that commit :wink: 

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.15, NixOS, 23.05 (Stoat), 23.05.git.677ed08a509`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/etc/nixos/nix/nixos-unstable`
```

**Comment by tazjin** [comment]
Fwiw, this error seems to come from inside a TOML parsing step in C++ Nix.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nix/pull/3305

Consider updating to a more recent version of Nix.

**Comment by ncfavier** [comment]
I've submitted a fix anyway: https://gitlab.com/rycee/nmd/-/merge_requests/8

**Comment by rycee** [comment]
Merged @ncfavier's nice fix and bumped the nmd dependency. Hopefully it works now.

**Comment by etu** [comment]
Seems to be working now, thanks! 🙂
