### ISSUE TITLE
bug: fish completions put in wrong directories when xdg.dataHome is set

### ISSUE THREAD

**Issue by bsvh** [nix-community/home-manager#3575]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I setup a custom location for `$XDG_DATA_HOME` using the following in my home-manager configuration

```
xdg.dataHome = /persist/user/data;
```

This correctly sets `$XDG_DATA_HOME`, but whenever I use `home-manager switch` a `persist` directory is setup in my home directory with fish completions.

```
$ ls /home/bsvh/persist/user/data/fish
home-manager_generated_completions@
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05.20221214.62433a4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/store/n93mjr66d66rlly1n3csnd3s5vz10y84-source`
```

**Comment by rycee** [comment]
Home Manager never puts anything outside your home directory. I've started working on supporting any path but there is little time left over for such larger developments so I haven't finished it. You will for the foreseeable future have to find some solution that puts the data directory somewhere under you home path.
