### ISSUE TITLE
Impossible to configurate pkgFilter for texlive

### ISSUE THREAD

**Issue by antonmosich** [nix-community/home-manager#3581]
### Description

The texlive.combine function allows for an Argument `pkgFilter` which further allows one to also install documentation for the installed Packages.
It would be nice to allow setting the `pkgFilter` in home-manager.

See https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive/combine.nix#L4

I am rather new to the nix world, so it might be a misunderstanding on my side, please make me aware of it should that be the case.

**Comment by ncfavier** [comment]
You can do

```nix
extraPackages = tpkgs: {
  inherit (tpkgs) scheme-medium ...;
  pkgFilter = pkgs: ...;
};
```

**Comment by antonmosich** [comment]
Oh my that's even easier than I feared haha.
Thank you very much, sorry for the unnecessary issue.
