### ISSUE TITLE
bug: Can't install packages using programs.*.enable

### ISSUE THREAD

**Issue by ERAGON007** [nix-community/home-manager#3587]
### Are you following the right branch?

- [x] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

This is the content of my home config file:
```nix
{ pkgs, ...}:

{
  home.packages = with pkgs; [

  ];
  home.stateVersion = "22.11";
  home.homeDirectory = "/home/eragon";

  programs.git = {
    enable = true;

    userName = "ERAGON007";
    userEmail = "turk6486@gmail.com";
  };

  programs.alacritty = {
    enable = true;
  };

  programs.rustc = {
    enable = true;
  };
}
```
When i try to build it using `sudo nixos-rebuild switch --flake .#eragon` (I'm using home manager with flakes)

I get the following error:
```log
└─(16:39:06 on main ✹ ✚)──> sudo nixos-rebuild switch --flake .#eragon
[sudo] password for eragon: 
warning: Git tree '/home/eragon/flake' is dirty
building the system configuration...
warning: Git tree '/home/eragon/flake' is dirty
error: The option `home-manager.users.eragon.programs.rustc' does not exist. Definition values:
       - In `/nix/store/9yaq152139igbs6rlma7mnl4hly1l07y-source/flake.nix':
           {
             enable = true;
           }
(use '--show-trace' to show detailed location information)
```

### System information

```markdown
┌─(~/flake)────────────────────────────────────────(eragon@EragonNixOS:pts/0)─┐
└─(16:45:46 on main ✹ ✚)──> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 23.05 (Stoat), 23.05.20230109.aa1d747`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(eragon): `"nixos"`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
We don't have a `rustc` module. If you want to install `pkgs.rustc`, you can just add it to `home.packages`.

**Comment by ERAGON007** [comment]
Hmm, sorry about noob questions.

but does that mean i can only use packages included in https://github.com/nix-community/home-manager/tree/master/modules/programs ?

**Comment by ncfavier** [comment]
No, you can use any package you want. `pkgs` contains the entire nixpkgs package collection, but you can even use packages from elsewhere. The modules defined in home-manager are only conveniences that let you install a package and manage its configuration declaratively. If you open e.g. the [abook](https://github.com/nix-community/home-manager/blob/master/modules/programs/abook.nix#L33) module you'll see that it boils down to `home.packages = [ pkgs.abook ];`.

**Comment by ERAGON007** [comment]
Thanks for the time you spent. closing issue
