### ISSUE TITLE
Support qt6 themes configurations

### ISSUE THREAD

**Issue by Tungsten842** [nix-community/home-manager#3590]
### Description
Since https://github.com/NixOS/nixpkgs/pull/182580 adwaita-qt6 is now available. Home manager should support configuring qt6 themes.

**Comment by 9ary** [comment]
Just chiming in with some info: it seems that unlike for qt5 for which adding the theme to home.packages is sufficient, qt6 requires QT_PLUGIN_PATH to point at the theme in order to find it.
I haven't yet checked whether this is necessary when the theme is in the system package set.

**Comment by Aleksanaa** [comment]
> qt6 requires QT_PLUGIN_PATH to point at the theme in order to find it.

I may accidentally add support to this in https://github.com/nix-community/home-manager/pull/4306

**Comment by 9ary** [comment]
As far as I know, yes. We now set QT_PLUGIN_PATH, and the module already included package mappings for some qt6 themes.
