### ISSUE TITLE
bug: swayidle unit not restarting on error

### ISSUE THREAD

**Issue by jboynyc** [nix-community/home-manager#3596]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Following a `nixos-rebuild switch`, this happens:
```
$ systemctl --user status swayidle.service
● swayidle.service - Idle manager for Wayland
     Loaded: loaded (/home/jboy/.config/systemd/user/swayidle.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-01-11 08:34:37 CET; 4 days ago
       Docs: man:swayidle(1)
   Main PID: 204251 (swayidle)
      Tasks: 1 (limit: 18457)
     Memory: 500.0K
        CPU: 17ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/swayidle.service
             └─204251 /nix/store/zvl70s8x0bygdmm79r5f64jviqlwxxm2-swayidle-1.7.1/bin/swayidle -w timeout 3600 "swaylock -e"

Jan 11 08:34:37 alterra systemd[1589]: Started Idle manager for Wayland.
Jan 12 18:47:26 alterra swayidle[395016]: /nix/store/wim4mqpn8lxhhr10p2kd070hyj152lil-bash-5.1-p16/bin/bash: line 1: swaylock: command not found
Jan 14 21:18:10 alterra swayidle[585892]: /nix/store/wim4mqpn8lxhhr10p2kd070hyj152lil-bash-5.1-p16/bin/bash: line 1: swaylock: command not found
```

Rather than entering a failed state and restarting, the unit remains active (running). This means that a computer that is supposed to be locked after an idle period remains unlocked.

### Maintainer CC

@c0deaddict 

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 22.11 (Raccoon), 22.11.1574.6a3f9996408`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(jboy): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sumnerevans** [comment]
This is probably intentional from swaylock: even if a single scheduled command fails, you want the subsequent ones to run.

**Comment by jboynyc** [comment]
> This is probably intentional from swaylock

I guess you mean `swayidle`? In fact, the swayidle maintainers say that running it as a systemd service is "[not supported][]", so I think we're beyond what is or isn't intended by swayidle here.

[not supported]: https://github.com/swaywm/swayidle/issues/74

**Comment by jboynyc** [comment]
My solution for now is to just periodically (manually) restart systemd user services.
