### ISSUE TITLE
bug: "replaceChars is a deprecated" warning in services.gnome-keyring

### ISSUE THREAD

**Issue by Aleksanaa** [nix-community/home-manager#3598]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

`nixos-rebuild switch ` shows `trace: warning: replaceChars is a deprecated alias of replaceStrings, replace usages of it with replaceStrings.` when setting `services.gnome-keyring.enable = true` in home manager

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.3-zen1, NixOS, 23.05 (Stoat), 23.05.20230111.6c8644f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/store/izkfanzxhdp831q9a1lbbj1qrv70543z-source`
```

**Comment by ncfavier** [comment]
Can't reproduce that on master and can't find any instance of `replaceChars` in home-manager. Could you try to come up with a minimal reproducing example?
