### ISSUE TITLE
Change location of lazygit's config on Darwin

### ISSUE THREAD

**Issue by saccarosium** [nix-community/home-manager#3634]
## The issue

Hi,
Lazygit in the in the [configuration docs][1] says that, by default on Darwin, it will look for a configuration file under `~/Library/Application Support/lazygit`. The problem is that, at least on MacOS Ventura (Darwin 22.3), it looks instead under `~/.config/lazygit`.

The way to check this is by running lazygit with the flag `cd`. Which prints the default config directory.
```bash
$ uname -rom
22.3.0 x86_64 Darwin

$ lazygit -cd
/Users/sacca/.config/lazygit
```

## Possible Solutions

_Referring to_ `modules/programs/lazygit.nix`

1. Removing check in `!Darwin`
2. Removing the hole `home.file` expression

[1]: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

**Comment by ncfavier** [comment]
From a quick look at the source, lazygit uses https://github.com/OpenPeeDeeP/xdg to locate its config file, and that should default to `~/Library/Application Support` on darwin. Do you maybe have `XDG_CONFIG_HOME` set explicitly? If so, what sets it?

**Comment by saccarosium** [comment]
> Do you maybe have XDG_CONFIG_HOME set explicitly? If so, what sets it?

Yes, I have it in my bashrc; but is not something I can get rid of since, a lot of apps, don't even look at the variable and they use `~/.config`. And since I want all in one location I would prefer using `~/.config`.

Maybe we could add a check if the variable is set:
```nix
home.file."Library/Application Support/lazygit/config.yml" =
      mkIf (cfg.settings != { } && isDarwin && !xdgVar) {
        source = yamlFormat.generate "lazygit-config" cfg.settings;
      };
```

**Comment by ncfavier** [comment]
It does seem to me that if the xdg module is enabled at all, then we should use `xdg.configFile` even on darwin.

I'll defer to @rycee since I'm not sure how XDG and darwin should interact.
