### ISSUE TITLE
bug: Inconsistent cursor size in Telegram Desktop due to XCURSOR_SIZE not set

### ISSUE THREAD

**Issue by raphielscape** [nix-community/home-manager#3645]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After I configured my cursor settings, I noticed that Telegram Desktop in Wayland has varying sizes, when diagnosing this, I noticed that the `XCURSOR_SIZE` variable is not being set and `xsetroot` is ignored in Wayland, running Telegram Desktop with `XCURSOR_SIZE` set to the same value as `home.pointerCursor.size` made the cursor size consistent again in Telegram Desktop, adding it on the environment fixed this issue

### Maintainer CC

@polykernel 

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.91, NixOS, 22.11 (Raccoon), 22.11.2301.cff83d5032a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by polykernel** [comment]
Thanks for the report. I wasn't sure when I made the PR whether the `XCURSOR_*` environment variables are a standard way to configure cursor settings on wayland but it seems to be widely used or at least as a fallback for many applications/libraries. I think it warrants being set by default when `home.pointerCursor` is enabled. If needed, the section can always be moved into the x11 specific backend.
