### ISSUE TITLE
request: dircolors terminal specific sections support

### ISSUE THREAD

**Issue by bsd-department** [nix-community/home-manager#3658]
### Description

Currently, the `dircolors` module can't specify terminal specific sections. This makes it impossible to fully replicate the default configuration of dircolors with home-manager. In the default `.dir_colors` generated with `dircolors -p`, the `LS_COLORS` environment variable is set only when using these terminals:
```
TERM Eterm
TERM ansi
TERM *color*
TERM con[0-9]*x[0-9]*
TERM cons25
TERM console
TERM cygwin
TERM dtterm
TERM gnome
TERM hurd
TERM jfbterm
TERM konsole
TERM kterm
TERM linux
TERM linux-c
TERM mlterm
TERM putty
TERM rxvt*
TERM screen*
TERM st
TERM terminator
TERM tmux*
TERM vt100
TERM xterm*
```
However, in home-manager generated `.dir_colors` this list is omitted, and `LS_COLORS` is set regardless of the `TERM` environment variable. Please provide a way to replicate the default behavior of dircolors.

**Comment by ncfavier** [comment]
Is `programs.dircolors.extraConfig` not enough? If not, feel free to open a PR.
