### ISSUE TITLE
Add programs.ssh.package option

### ISSUE THREAD

**Issue by gmacon** [nix-community/home-manager#3667]
### Description

I'm interested in adding the option `program.ssh.package` so that I can more easily adjust what ssh client I'm using (`pkgs.openssh` most of the time, but `pkgs.openssh_gssapi` in a few places). I think the right thing to do is to make the default value `pkgs.openssh`, but I think that would be a backwards-breaking change, so I wanted to see what folks thought about this before I work on it.

**Comment by sumnerevans** [comment]
It looks like the module doesn't even add the `ssh` package. I think it would be fine to add it and default to `pkgs.openssh`.

**Comment by gmacon** [comment]
There's an open PR, #3668 that fixes this issue.
