### ISSUE TITLE
bug: `programs.helix.languages` format not up-to-date

### ISSUE THREAD

**Issue by augustebaum** [nix-community/home-manager#3687]
It seems the `helix.languages` option don't follow the current format for the `languages.toml` file: the option takes a list of TOML values which I guess would then appear as `[[language]]` sections in the generated `languages.toml`, but the [`helix` documentation](https://docs.helix-editor.com/languages.html) states there can also be `[[grammar]]` keys as well as a top-level `use-grammars` key.

Ideally `languages` would just take a TOML value which could be obtained by parsing a TOML file, e.g.
```nix
helix.languages = (builtins.fromTOML (builtins.readFile ./config/helix/languages.toml));
```
However, as this is a breaking change, a quick-fix solution would be an option linking to a TOML file directly, which is the easiest way to port a non-Nix config to home-manager. Something like:
```nix
helix.languagesSource = builtins.readFile ./config/helix/languages.toml;
```

Source:
https://github.com/nix-community/home-manager/blob/5ffb0f1f818ff0d435b16a4934a24c6277d3fde7/modules/programs/helix.nix#L45

**Comment by ncfavier** [comment]
Is this a duplicate of https://github.com/nix-community/home-manager/issues/2871 ?

**Comment by ncfavier** [comment]
I think adding a `grammars` option would be welcome, or even more generally a `languageSettings` option with a full TOML value type, so that `languageSettings.language` can then be set from `languages`.

**Comment by augustebaum** [comment]
> Is this a duplicate of #2871 ?

Yes, thanks for bringing this to my attention. Closing as duplicate of #2871.
