### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by MangoIV** [nix-community/home-manager#3689]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

for some reason the default setting for `direnv.enableNushellIntegration` is `true` *and* readonly. 

### Maintainer CC

@autophagy 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.10-zen2, NixOS, 22.11 (Raccoon), 22.11.20230217.de5448d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.14.0pre20230128_792d83f`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
The option should no longer be read only now. Please update and try again.
