### ISSUE TITLE
qt style assertion for gnome platform doesnt detail that both name and package are necessary

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [nix-community/home-manager#3691]
https://github.com/nix-community/home-manager/blob/ebb21e1bf6b921a60ee314c4246785b61f5ecbf2/modules/misc/qt.nix#L90-L94

the error only talks about the name

but the code wants both

as name and package seem to match i wonder if it would make sense to imply the name from the package if given

**Comment by ncfavier** [comment]
Probably the opposite, since packages can have multiple styles.

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/3692

**Comment by RonnyPfannschmidt** [comment]
@ncfavier thanks, awesome :)
