### ISSUE TITLE
bug: keychain generates xsession code for bash regardless of the shell executing .xsession

### ISSUE THREAD

**Issue by siflfran** [nix-community/home-manager#3693]
How to reproduce:
- configure fish as your login shell
- in home-manager set xsession.enable = true;
- set programs.keychain.enable = true; set programs.keychain.enableXsessionIntegration = true;

Near the end of keychain.nix xsession.initExtra is set to eval "$(${shellCommand})". This will generate working code only for bash and compatible shells.

One possible solution would be to force the shell in .xsession to bash by prepending #!/usr/bin/env bash. This may break client code, though.

Alternatively, keychain.nix (and other places generating code for .xsession) could be made aware of the user's shell. That would generate code that depends on the environment, which would be bad for reproducibility.

**Comment by rycee** [comment]
Odd, the [code running the xsession script](https://github.com/NixOS/nixpkgs/blob/8ed9778a85f9220ffd343df13dea0dd987dbc93f/nixos/modules/services/x11/display-managers/default.nix#L33) is quite explicit about running under Bash. Do you know how the script ends up running under fish? I don't see any obvious way it could happen, perhaps you have some custom X initialization code somewhere?

**Comment by siflfran** [comment]
I still don't know what's really happening here. I'm running home-manager on an Ubuntu system. Within the .xsession script the $SHELL variable is set to /usr/bin/fish. I don't think that necessarily means that we are running in a fish shell, just that at the time when the script was started the $SHELL variable was already set and bash did not set it. What's happening might be that keychain checks what $SHELL is set to, sees that it's set to fish and then generates output for the fish shell.

The error message I was getting was something along the lines of 'set does not support -U'. Fish supports that flag, bash does not. So maybe what needs to be done here (since the assumption already is that we are running in bash) is to set the $SHELL variable to bash for the keychain invocation. So that would be the same code that's generated for bash integration further up in keychain.nix.

**Comment by siflfran** [comment]
I've been using this for several days now and it works for me.
