### ISSUE TITLE
Alacritty moving towards configuration with TOML format

### ISSUE THREAD

**Issue by oceanlewis** [nix-community/home-manager#3696]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

This isn't a "bug" exactly, but it looks like the Alacritty project is looking at migrating away from using YAML as their configuration language to TOML, which will break `programs.alacritty.settings`.

I don't think `nixpkgs` has a `builtin.toTOML`, but it's easy enough for me to get around this by using `nushell`'s `from yaml | to toml` functionality. Probably there are better ways to fix this though.

See https://github.com/alacritty/alacritty/pull/6673 for where this work is happening.

### Maintainer CC

@timhae @rycee @berbiche @ncfavier

### System information

```markdown
N/A
```

**Comment by ncfavier** [comment]
Thanks for the heads-up. It looks like upstream will continue supporting YAML for some time so we can have a graceful transition.

Should be as simple as changing `pkgs.formats.yaml` to `pkgs.formats.toml`, and maybe that will be a good time to revisit [this TODO](https://github.com/nix-community/home-manager/blob/4295fdfa6b0005c32f2e1f0b732faf5810c1bc7f/modules/programs/alacritty.nix#L53-L54).

**Comment by jperras** [comment]
Tangentially related: Alacritty has already introduced a non-standard YAML `import` directive, which allows a YAML file to import another YAML file. One of the drivers of this was for colorscheme themes: https://github.com/alacritty/alacritty-theme#imports

**Comment by kchibisov** [comment]
>Tangentially related: Alacritty has already introduced a non-standard YAML import directive, which allows a YAML file to import another YAML file. One of the drivers of this was for colorscheme themes: https://github.com/alacritty/alacritty-theme#imports

It's a simple array of strings which is called `import`, it could be called whatever and is a plain yaml array with strings. Those strings we use as a source of other configurations which we manually merge.

```yml
foo:
  - "./foo1.yml"
  - "./foo2.yml"
```

**Comment by tobiasbaehr** [comment]
btw. when you enable alacritty via home manager, then it generates json for alacritty.yml.

 I do not believe this is valid. ;-)

**Comment by rycee** [comment]
@tobiasbaehr YAML is a superset of JSON so any valid JSON is also valid YAML so we have historically used Nix's builtin toJSON function also for YAML output.

**Comment by ncfavier** [comment]
I think the easiest would be something like

```nix
pkgs.runCommand "alacritty-unescaped.toml" {} ''
  sed -E 's/\\(\\[uU])/\1/g' ${toml.generate "alacritty.toml" settings} > "$out"
''
```

Though maybe alacritty could take care of interpreting backslash sequences itself in the relevant options? (Does it ever make sense to have a literal backslash in keybindings?)

**Comment by kchibisov** [comment]
It's not about just keybindings, you can define arbitrary regexes to search, so user can type whatever they want, it's just an issue that you can't generate toml with `\u` no matter how you try with nix.

**Comment by kchibisov** [comment]
Besides, you'd need a
```sh
sed -E 's/\\\\/\\/g'
```

Otherwise other `\` commands won't translate from the way it was with `yml` (at least my config required that to translate).

**Comment by ncfavier** [comment]
The TOML change has not been released yet. If you're using alacritty master, feel free to open a PR and use it and we'll merge it when the release hits nixpkgs.

**Comment by oxalica** [comment]
> I don't think `nixpkgs` has a `builtin.toTOML`

That can be implemented in Nix. I created a PR in nixpkgs: https://github.com/NixOS/nixpkgs/pull/243390

**Comment by Airradda** [comment]
As of [Alacritty Version 0.13.0](https://github.com/alacritty/alacritty/releases/tag/v0.13.0), the configuration file format is now TOML.
> Configuration file now uses TOML instead of YAML
> Run `alacritty migrate` to automatically convert all configuration files

**Comment by flaturtha** [comment]
I upgraded this morning and when I tried to run `alacritty migrate`, I got the following error: "Configuration file migration failed:
    "/home/h/.config/alacritty/alacritty.yml": parsing error: Yaml conversion error: unsupported unit type"
    
I'm not an expert but am trying to learn. Therefore, I'm obviously missing something but am unsure how to proceed. Googling hasn't help. Nor did ChatGPT! :-)

**Comment by kchibisov** [comment]
it means that the old config was not valid in the first place, as in wrong section alignments, etc.

**Comment by flaturtha** [comment]
Yeah, I figured something like that but I don't believe I ever changed it. Is there a standard file I can use?

**Comment by kchibisov** [comment]
`man 5 alacritty` or alacritty.org.

**Comment by flaturtha** [comment]
gee, thanks for helping a noob

**Comment by n8henrie** [comment]
@rycee @ncfavier -- could this be considered for backporting to 23.11? As it has the [version check built-in](https://github.com/r-vdp/home-manager/blob/ba6b75011b44e85b1b755b6c423f85d0817645f7/modules/programs/alacritty.nix#L7) I think it should be compatible.

I'm happy to test, though I'm not entirely sure how -- actually it looks like I should be able to [use `disabledModules`](https://github.com/nix-community/home-manager/issues/602) for this. Should be able to try tomorrow and report back.

(I am pinned to release-23.11 for my system as a whole but use a handful of unstable packages for development, including alacritty.)

**Comment by n8henrie** [comment]
I can confirm that the updated `programs.alacritty` works on 23.11 with alacritty <0.13 (generates yml) as well as alacritty >= 13 (generates toml) and avoid the warning message in both cases.

Can a backport be considered?

For other readers, this I have a `home-manager-unstable` flake input in my otherwise 23.11-pinned configuration, and I pass that input via `specialArgs`
```
{
  pkgs,
  lib,
  config,
  ...
} @ args: {
imports = [
    "${args.inputs.home-manager-unstable}/modules/programs/alacritty.nix"
];
disabledModules = ["programs/alacritty.nix"];
}
```
