### ISSUE TITLE
bug: Specialization does not work with nixos modules

### ISSUE THREAD

**Issue by zoriya** [nix-community/home-manager#3716]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hello, I am trying to set up specializations for light/dark theme switching, but creating a specialization result in a build error.
```
error: The option `home-manager.users.zoriya.specialization.test.configuration._module.args.name' is defined multiple times while it's expected to be unique.

       Definition values:
       - In `/nix/store/3jhxmigz3b15xdcdhj0pryq2bg6qyhcv-source/modules/misc/specialization.nix': "zoriya"
       - In `<unknown-file>': "configuration"
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
(use '--show-trace' to show detailed location information)`
```

The snippets that make my build crash is the specialization test"
```nix
nixpkgs.lib.nixosSystem {
  inherit system;
  specialArgs = inputs;
  modules = [
	{
	  home-manager = {
	    useGlobalPkgs = true;
	    useUserPackages = true;
	    extraSpecialArgs = inputs;
	    users.${user} = {
		    specialization.test.configuration = {
		      home.file.testfile.text = "very special";
		    };
		    home.stateVersion = "22.11";
	    };
	  };
	}
  ];
}
```

Link to the [full config](https://github.com/zoriya/flake/blob/059ff0118d539e5602f1319101234c0f221c2219/modules/home/colors/default.nix#L29)

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 23.05 (Stoat), 23.05.20230222.988cc95`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
That's a fun one! cc @roberth @infinisil

Minimal reproducer:

```nix
with import <nixpkgs/lib>;
let eval = evalModules {
  modules = [ {
    options.hm = mkOption {
      type = types.submoduleWith {
        modules = [ ({ moduleType, ... }: {
          options.foo = mkOption {
            type = types.str;
          };
          options.special = mkOption {
            type = moduleType;
          };
        }) ];
      };
    };

    config.hm = { name, ... }: {
      foo = name;
      special = {};
    };
  } ];
};
in eval.config.hm.special.foo
```

```
error: The option `hm.special._module.args.name' is defined multiple times while it's expected to be unique.

       Definition values:
       - In `<unknown-file>': "hm"
       - In `<unknown-file>': "special"
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

`_module.args.name` is defined [here](https://github.com/NixOS/nixpkgs/blob/68196a61c26748d3e53a6803de3d2f8c69f27831/lib/types.nix#L744), and this ends up being evaluated twice with different values for `loc` (`hm`, then `hm.special`).

A way to solve this would be to add a `nameArgument` argument to `submoduleWith` and define `_module.args.${nameArgument}` instead. The HM NixOS module could set that to `userName`, and this wouldn't interfere with specialisations because [`moduleType`](https://github.com/NixOS/nixpkgs/blob/83a88dea9ebefbc26594d7e39e26e739260ae336/lib/modules.nix#L340-L342) does not inherit this argument:

```nix
…
    config.hm = { userName, name, ... }: {
      foo = "${userName} / ${name}";
      special = {};
    };
  } ];
};
in eval.config.hm.special.foo
```

```
"hm / special"
```

**Comment by roberth** [comment]
hm. I've been at this problem a couple of times now. I'd say `name` is rather unprincipled in how it's implemented.
I [reinvented](https://nix-dev.science.uu.narkive.com/R8B5uN2W/fixing-module-arguments-proposal-may-break-existing-nixos-configs-please-read) `dependentAttrsOf` [the other day](https://github.com/NixOS/nixpkgs/issues/218006#issuecomment-1443725476)

I've also gone through some iterations of this in the NixOS vm test test matrix PR
 - https://github.com/NixOS/nixpkgs/pull/176557

Eventually I settled on a solution that didn't need `name`, avoiding `submodule` directly inside `attrsOf`.

**Comment by roberth** [comment]
> Eventually I settled on a solution that didn't need `name`, avoiding `submodule` directly inside `attrsOf`.

Home-manager could structure its specialisations module in the same way NixOS does, which happens to satisfy the same criteria.

The non-`moduleType` submodule inside `attrsOf` can forward the username to the `moduleType` submodule as usual.

**Comment by roberth** [comment]
The breaking change does solve the lack of extensibility in the `specialisations` attribute. There's currently no way to add a per-specialisation option that isn't inside the home-manager config. NixOS has used such an option to specify whether to inherit the regular config, and other options may come up in the future.

**Comment by ncfavier** [comment]
> The non-`moduleType` submodule inside `attrsOf` can forward the username to the `moduleType` submodule as usual.

How? I don't see where the NixOS specialisation module does this.

**Comment by ncfavier** [comment]
> The breaking change does solve the lack of extensibility in the `specialisations` attribute. There's currently no way to add a per-specialisation option that isn't inside the home-manager config.

Not sure what you mean here, we could already add options besides `configuration` [here](https://github.com/nix-community/home-manager/blob/master/modules/misc/specialization.nix#L8).

**Comment by roberth** [comment]
> How? I don't see where the NixOS specialisation module does this.

Right, it doesn't, which could be a good thing. I assumed from the example that the `name` had to be used for some reason. The goal, for this solution, is to not evaluate the invalid `name` at all.

**Comment by roberth** [comment]
> Not sure what you mean here, we could already add options besides `configuration` [here](https://github.com/nix-community/home-manager/blob/master/modules/misc/specialization.nix#L8).

I must have inferred too much / incorrectly from the example. The trace would be helpful. I wish people just posted traces, but I guess they consider them too verbose...

**Comment by ncfavier** [comment]
Right, I simplified the failing example down to the bare minimum, so I removed the intermediate layer of submodule.

> The goal, for this solution, is to not evaluate the invalid `name` at all.

Aha, the following seems to work:
```patch
diff --git a/modules/misc/specialization.nix b/modules/misc/specialization.nix
index 67e593e2..1f93ef00 100644
--- a/modules/misc/specialization.nix
+++ b/modules/misc/specialization.nix
@@ -1,4 +1,4 @@
-{ config, extendModules, lib, ... }:
+{ config, extendModules, name, lib, ... }:
 
 with lib;
 
@@ -8,7 +8,7 @@ with lib;
       options = {
         configuration = mkOption {
           type = let
-            stopRecursion = { specialization = mkOverride 0 { }; };
+            stopRecursion = { _module.args.name = mkForce name; specialization = mkOverride 0 { }; };
             extended = extendModules { modules = [ stopRecursion ]; };
           in extended.type;
           default = { };
```

**Comment by ncfavier** [comment]
And if `name` isn't passed, that means we're not in a NixOS module, so `name` isn't evaluated either, so the problem fixes itself by laziness.

**Comment by zoriya** [comment]
Wow, that was fast. Thanks a lot!
