### ISSUE TITLE
bug: home-manager fails to install with a basic flake

### ISSUE THREAD

**Issue by fislysandi** [nix-community/home-manager#3736]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

so im having this issue.
im trying to make a flake that will install home manager by just running nix run .#homeConfigurations.<user>.activationPackage 
and i get this : 
![vmware_O3wLkydSIl](https://user-images.githubusercontent.com/45166203/222795714-42493105-a290-4493-8dc3-84c0aa542a2d.png)

steps to reproduce :

1. spin up a quickemu debian  instance
2. clone the repo and make sure you have nix installed
3. go to the repo folder symlink nix and nixpkgs to ~/.config/ and run "nix run .#homeConfigurations.myuser.activationPackage"
4. wait for a little. then get the error i specified

### System information

```markdown
"x86_64-linux"
- system:
'Linux 6.1.0-5-amd64, Debian GNU/Linux,
- host os:
yes'
- multi-user? :
yes'
- sandbox:
nix-env (Nix) 2.13.2'
- version:
"nixpkgs"'
- channels( root):
novers ion ,
nobuild'
"home-manager-22.11. tar. gz"
- channels(fislysandi):
- nixpkgs:
/nix/var/nix/profiles/per-user/root/channels/nixpkgs
```

**Comment by ncfavier** [comment]
Can't reproduce, I get a different error.
```
~ $ nix run github:fislysandi/home-manager-for-3dartists?dir=nixpkgs#homeConfigurations.fislysandi.activationPackage
error: attribute 'buildHomeConfig' missing
```

(I assume that's the repository you're talking about...)

**Comment by fislysandi** [comment]
i will create a second vm to test it.

**Comment by fislysandi** [comment]
hey @ncfavier  i solved the error you talked about try again. i removed symlinking for now and i get the error im talking about. all you need to do is nix run github:fislysandi/home-manager-for-3dartists?dir=nixpkgs#= (you dont need to add  #homeConfigurations.fislysandi.activationPackage its executeable with nix run .#)

just do what you did before.

**Comment by fislysandi** [comment]
and if you will be able to reproduce it, the issue will be addressed right?

**Comment by ncfavier** [comment]
> dont pass homeConfigurations.fislysandi.activationPackage, its not needed

What makes you think it's not needed? How should Nix guess which attribute you want to run if you don't tell it?

Still getting the same error as last time with the same command. `buildHomeConfig` is not a thing.

**Comment by fislysandi** [comment]
@ncfavier 

i tried this command:
`nix run github:fislysandi/home-manager-for-3dartists?dir=nixpkgs#`
![vmware_LqHqZskZW3](https://user-images.githubusercontent.com/45166203/223648157-3948c265-8a8c-4c0f-a397-9b7fdfa04ce2.png)

i tried it on a brand new arch vm, and i get the issue i talked about.

maybe its because of your host username you get this error or i just dont get it?

**Comment by ncfavier** [comment]
> **What makes you think it's not needed? How should Nix guess which attribute you want to run if you don't tell it?**

**Comment by fislysandi** [comment]
😞ok then. do you have the most boilerplate flake that just pulls the home manager and installs it?

**Comment by ncfavier** [comment]
https://nix-community.github.io/home-manager/index.html#ch-nix-flakes

**Comment by fislysandi** [comment]
maybe ill try to move my symlinked folders to their respective folders? lets try that.
