### ISSUE TITLE
Borgmatic Hooks?

### ISSUE THREAD

**Issue by mentalblock** [nix-community/home-manager#3760]
cc: @DamienCassou 

It seems like the [current nix abstraction of borgmatic](https://github.com/nix-community/home-manager/blob/e412025fffdcd6219ddd21c65d9a1b90005ce508/modules/programs/borgmatic.nix) does not allow specifying hooks as outlined in the [official borgmatic configuration](https://torsion.org/borgmatic/docs/reference/configuration/). Can someone verify this is the case? I am questioning whether I understand the current home-manager options correctly.

I do not believe I have the skillset to add the appropriate options to the current module, but I will give it a shot if someone can confirm that the current state of the module does not support hooks.

I look forward to hearing from other users regarding this use case. Thanks in advance.

**Comment by ncfavier** [comment]
That is correct. We should add a YAML `freeformType` to the `configModule` so that any options can be configured before the module knows about them, following [RFC 42](https://github.com/Infinisil/rfcs/blob/config-option/rfcs/0042-config-option.md).

**Comment by mentalblock** [comment]
It looks like we can basically use [the NixOS module](https://github.com/NixOS/nixpkgs/blob/919f2b2b6292436570613e7f7166eb992b12255f/nixos/modules/services/backup/borgmatic.nix) as a guideline as it is more flexible and uses the pattern you describe.

As a general question, what is the proper direction when a NixOS module and a home-manager module mostly overlap? Is the home-manager module still maintained for those who run home-manager but not NixOS?

**Comment by DamienCassou** [comment]
I think https://github.com/nix-community/home-manager/pull/3793 will fix this issue.

**Comment by DamienCassou** [comment]
I implemented a different fix for this issue in https://github.com/nix-community/home-manager/pull/4108.

**Comment by mentalblock** [comment]
Thank you so much @DamienCassou , works perfectly.
