### ISSUE TITLE
bug: `home-manager` does not configure `helix` properly when using `space.<key>` syntax

### ISSUE THREAD

**Issue by alxpettit** [nix-community/home-manager#3766]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Attempting to configure Helix with the following config:

```nix
programs.helix = {
    keys.normal = {
        space.w = ":w";
    };
};
```

Expected config:

```toml
[keys.insert]
space.c = ":toggle_comments"
```
Got:

```toml
[keys.insert.c]
c = ":toggle_comments"
```

This is not interpreted by Helix the same way, and results in a runtime error.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.97, NixOS, 22.11 (Raccoon), 22.11.20230312.970402e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
```

**Comment by ncfavier** [comment]
Can't reproduce. With

```nix
programs.helix = {
  enable = true;
  settings = {
    keys.normal = {
      space.w = ":w";
    };
  };
};
```

I get

```
[keys.normal.space]
w = ":w"
```

and helix behaves accordingly when pressing `<space>w`.

**Comment by alxpettit** [comment]
Ah, looks like there was another error that happened to correspond exactly with when I was testing `space.w` last night. Sorry about that!
