### ISSUE TITLE
bug: Packages and programs configured with home-manager are not in PATH

### ISSUE THREAD

**Issue by grimerssy** [nix-community/home-manager#3781]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hi. I am new to nix and I'm trying to move my system config to nix-darwin and home-manager. Everything seems to work fine, but for some reason home-manager does not link /nix/store paths with specified packages to my nix profile. I am using nix-flakes and I did not actually install nix-darwin and home-manager with nix-channels. Instead, I am building my flake and using `./result/sw/bin/darwin-rebuild switch --flake .`
Here is my flake.nix:
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-22.11-darwin";
    home-manager = {
      url = "github:nix-community/home-manager/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = { self, nixpkgs, darwin, home-manager }:
  let
    user = "grimerssy";
    host = "myhost";
    system = "aarch64-darwin";
  in rec {
    packages.${system}.default = darwinConfigurations.${host}.system;
    darwinConfigurations.${host} = darwin.lib.darwinSystem {
      inherit system;
      pkgs = nixpkgs.legacyPackages.${system};
      modules = [
        ./darwin
        home-manager.darwinModules.home-manager {
          home-manager = {
            useGlobalPkgs = true;
            useUserPackages = true;
            users.${user} = import ./home;
          };
        }
      ];
    };
  };
}
```
and ./home.default.nix:
```nix
{ config, lib, pkgs, ... }:
{
  home.stateVersion = "22.11";
  programs.home-manager.enable = true;
  home.packages = [
    pkgs.hello
  ];
  programs.exa.enable = true;
  home.sessionVariables = {
    PAGER = "less";
    CLICLOLOR = 1;
    EDITOR = "nvim";
  };
  home.file."test".text = "it works\n";
}
```
home.file."test" actually works and that confirms that home-manager can write in my home directory and it applies my config. But for some reason hello and exa are not available (even if I source my .zshrc or start a new shell). I am not sure if this is a bug or I am doing something wrong. I tried to follow both home-manager and nix-darwin manuals and don't know what the issue might be.

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(grimerssy): `"nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/grimerssy/.nix-defexpr/channels/nixpkgs`
```

**Comment by rycee** [comment]
Did you source `hm-session-vars.sh` in your shell configuration? If not, then something like

    . /etc/profiles/per-user/grimerssy/etc/profile.d/hm-session-vars.sh

in `.zshenv` might work.

**Comment by grimerssy** [comment]
Yes, I have done that. Unfortunately, it doesn't help

**Comment by grimerssy** [comment]
Oh, I think it's important to mention that if I add homeConfigurations and run `nix run '.#homeConfigurations.grimerssy.activationPackage'` everything works just fine.
```nix
homeConfigurations.${user} = home-manager.lib.homeManagerConfiguration {
  inherit pkgs;
  modules = [
    ({ ... }: {
      home.username = user;
      home.homeDirectory = "/Users/" + user;
    })
    ./home
  ];
};
```
Although it works, I still don't understand why home-manager does not include packages and programs if it's in the nix-darwin module

**Comment by ncfavier** [comment]
Does it work if you disable `useUserPackages`?

**Comment by grimerssy** [comment]
No, it throws an error:
```
error: attribute 'grimerssy' missing

       at /nix/store/byf0h1z1ngiimv4k21fakyv6qzily29y-source/nixos/common.nix:33:27:

           32|
           33|           home.username = config.users.users.${name}.name;
             |                           ^
           34|           home.homeDirectory = config.users.users.${name}.home;
(use '--show-trace' to show detailed location information)
```

**Comment by ncfavier** [comment]
Sounds like you need to declare your user in your nix-darwin configuration, as hinted at [here](https://nix-community.github.io/home-manager/index.html#sec-install-nix-darwin-module).

**Comment by grimerssy** [comment]
I added that and removed useUserPackages, it finally works. Thank you :)
