### ISSUE TITLE
Exclude specific systemd template services from being restarted/killed by home-manager switch

### ISSUE THREAD

**Issue by avh4** [nix-community/home-manager#3782]
I tried to see if there's currently a way to do this, but I didn't find one.

### Description

I have a few systemd template services that I use to keep certain things organized into cgroups and have logs in journalctl.  For example, `systemctl --user start "terminal@$(date -Is)"` starts an instance of the following service:

```nix
{
  systemd.user.services."terminal@" = {
    Unit = {
      Description = "terminal session (%i)";
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      ExecStart = "${pkgs.alacritty}/bin/alacritty";
    };
  };
}
``` 

When I `home-manager switch`, I want most of my systemd user services to be restarted if changed, or stopped if removed, but for these specific template services, I want a way to exclude them from being restarted/killed.  With the above example, if I update nixpkgs (and say there's a new version of alacritty) and then home-manager switch, I want the old terminal sessions to stay alive and not be killed.

I guess I'd proposed maybe an additional option `systemd.user.startServices.exclude` which could be a list of service names to exclude from automatically restarting or killing.  The option would need to accept `servicename@` as meaning to exclude all instances of the given template unit.  It would probably be useful to have any running excluded services be printed so the user can choose to kill or restart them if desired, though that is not necessary for me personally.

**Comment by ambroisie** [comment]
It might make more sense to do the same as NixOS's systemd module and have the equivalent of `systemd.user.services.<name>.restartIfChanged` to control such behaviour.

**Comment by rycee** [comment]
If you use `systemd.user.startServices = "sd-switch"` then doing

``` nix
{
  systemd.user.services."terminal@" = {
    Unit = {
      X-SwitchMethod = "keep-old";
      …
```

should prevent the restart.

**Comment by avh4** [comment]
Thanks!  That seems to work.

I've tried a few times and haven't been able to find this documented for sd-switch.  So maybe noting this in the description or example for either https://nix-community.github.io/home-manager/options.html#opt-systemd.user.services or https://nix-community.github.io/home-manager/options.html#opt-systemd.user.startServices would be helpful.
