### ISSUE TITLE
bug: XCURSOR_SIZE exported as an int breaks `concatStringsSep`

### ISSUE THREAD

**Issue by NotAShelf** [nix-community/home-manager#3784]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Not exactly a bug, but an unforeseen consequence of a change.

I have a script that allows me to run commands as systemd services. It makes use of `lib.concatStringSep` to apply envvars to the process:

```nix
{
  pkgs,
  config,
  lib,
  ...
}: let
  apply-hm-env = pkgs.writeShellScript "apply-hm-env" ''
    ${lib.optionalString (config.home.sessionPath != []) ''
      export PATH=${builtins.concatStringsSep ":" config.home.sessionPath}:$PATH
    ''}
    ${builtins.concatStringsSep "\n" (lib.mapAttrsToList (k: v: ''
        export ${k}=${v}
      '')
      config.home.sessionVariables)}
    ${config.home.sessionVariablesExtra}
    exec "$@"
  '';

  # runs processes as systemd transient services
  run-as-service = pkgs.writeShellScriptBin "run-as-service" ''
    exec ${pkgs.systemd}/bin/systemd-run \
      --slice=app-manual.slice \
      --property=ExitType=cgroup \
      --user \
      --wait \
      bash -lc "exec ${apply-hm-env} $@"
  '';
in {
  home = {
    packages = [run-as-service];
    sessionVariables = {
      STARSHIP_CACHE = "${config.xdg.cacheHome}/starship";
    };
  };
}
```

In [this commit](https://github.com/nix-community/home-manager/commit/5e94669f8ea8d697b1a00b916b2a86909f8c4ff5) home-manager started exporting XCURSOR_SIZE variable as an int, which cannot be coerced into a string.

The simple, I believe unbreaking, solution is to export this value as a string and not a string. Should be as simple as switching `XCURSOR_SIZE = mkDefault cfg.size;` to `XCURSOR_SIZE = mkDefault "${cfg.size}";`

I've tested that XCURSOR_SIZE takes values as strings instead of int.

### Maintainer CC

 @polykernel 

### System information

```markdown
$ ~ nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.6, NixOS, 23.05 (Stoat), 23.05.20230314.7067edc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/store/rmw0kq593g38kj9dwpg5ka81bbskh9dm-source`
```

**Comment by ncfavier** [comment]
`home.sessionVariables` is an attribute set of `string or path or signed integer or floating point number`, so your code should treat it as such. Conveniently, `toString` can convert all of those into interpolatable strings:

```bash
export ${k}="${toString v}"
```

In fact you could simply reuse home-manager's [library](https://github.com/nix-community/home-manager/blob/master/modules/lib/shell.nix) for this:

```nix
''
  ${config.lib.shell.exportAll config.home.sessionVariables}
''
```

Or even go a step further and directly source `${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh` instead of reinventing the wheel:

```bash
bash -lc '. ${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh; exec "$@"'
```

**Comment by NotAShelf** [comment]
The wheel has already been re-invented. I see little to no point in uninventing it at this point.

However you are right, I should've been converting the value to a string manually, accounting the possibility that it may be an int.
