### ISSUE TITLE
Sway: Ignores home.keyboard

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#3795]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The sway module doesn't configure the keyboard the way it is set in `home.keyboard`.

Home Manager allows for a high-level keyboard configuration, e.g.,

```nix
{
  home.keyboard = {
    layout = "us";
    variant = "colemak";
    options = ["ctrl:nocaps"];
  };
}
```

Such a configuration has no impact on Sway. I would expect setting `home.keyboard` would make Sway configured with this keyboard.

Workaround: Sway's handling of keyboard can be configured with something like:

```nix
{
  input = {
    "*" = {
      xkb_layout = "us";
      xkb_variant = "colemak";
      xkb_options = "ctrl:nocaps";
    };
  };
}
```

Would it make sense to generate the above Sway configuration from `home.keyboard`?

### Maintainer CC

@alexarice @sumnerevans @SebTM @oxalica

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.18-200.fc37.x86_64, Fedora Linux, 37 (Workstation Edition), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - channels(temp): `"home-manager, nixpxkgs"`
 - channels(cassou): `"home-manager-22.11.tar.gz, nixpkgs"`
 - nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`
```

**Comment by DamienCassou** [comment]
This is still a problem but if maintainers are not willing to give feedback I'm fine closing the issue.

**Comment by sumnerevans** [comment]
If there is a clear translation, then sure, we can generate that from `home.keyboard`. I do worry about the options part as it seems like it's a string in the sway config. How do you translate the list to that?

Also, instead of `*` it should be `type:keyboard` so that things such as YubiKeys don't get caught in whatever layout you are using.

**Comment by SebTM** [comment]
> How do you translate the list to that?

It seems like you can just comma separate it // https://unix.stackexchange.com/questions/571885/how-to-toggle-keyboard-layout-in-sway-from-the-shell

**Comment by ambroisie** [comment]
Not stale.

**Comment by sliedes** [comment]
Still relevant.

**Comment by DamienCassou** [comment]
Closing the issue as I'm not interested in its resolution anymore.
