### ISSUE TITLE
bug: programs.fish.plugins installing the wrong plugin

### ISSUE THREAD

**Issue by caarlos0** [nix-community/home-manager#3810]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have a config like so:

```nix
{ pkgs, ... }:
{
  # ...
  programs.fish = {
    enable = true;
    plugins = [
      {
        name = "nix-env";
        src = pkgs.fetchFromGitHub {
          owner = "lilyball";
          repo = "nix-env.fish";
          rev = "main";
          sha256 = "qt3t1iKRRNuiLWiVoiAYOu+9E7jsyECyIqZJ/oRIT1A=";
        };
      }
      {
        name = "fzf";
        src = pkgs.fetchFromGitHub {
          owner = "jethrokuan";
          repo = "fzf";
          rev = "main";
          sha256 = "28QW/WTLckR4lEfHv6dSotwkAKpNJFCShxmKFGQQ1Ew=";
        };
      }
      {
        name = "autopair";
        src = pkgs.fetchFromGitHub {
          owner = "jorgebucaran";
          repo = "autopair.fish";
          rev = "main";
          sha256 = "qt3t1iKRRNuiLWiVoiAYOu+9E7jsyECyIqZJ/oRIT1A=";
        };
      }
  ];
  # ...
}
```

But its evaluated incorrectly, see:

```
Developer/caarlos0/dotfiles.nix on  main ⇡?!
❯ rg store ~/.config/fish/conf.d/*
/Users/carlos/.config/fish/conf.d/plugin-nix-env.fish
2:set -l plugin_dir /nix/store/g1l0fqxhf982lc2pqw6613bqwm6bw382-source

/Users/carlos/.config/fish/conf.d/plugin-fzf.fish
2:set -l plugin_dir /nix/store/72ir6g2b07ad0ydx6zg5gg6zxil6zysr-source

/Users/carlos/.config/fish/conf.d/plugin-autopair.fish
2:set -l plugin_dir /nix/store/g1l0fqxhf982lc2pqw6613bqwm6bw382-source
```

autopair and nix-env are using the same nix-store folder, hence, the same plugin is being loaded twice.

I tried adding more plugin, shuffling, etc, it always happens...

### Maintainer CC

cc @ryanorendorff 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(carlos): `"home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rycee** [comment]
You are using the same sha256 hash for those plugins. Nix will therefore consider them the same.

Try using

    sha256 = "0000000000000000000000000000000000000000000000000000000000000000";

instead.

**Comment by caarlos0** [comment]
Oh! I thought i could put any hash and it would error with the right one, so my mental model was wrong🤔

Thanks so much for explaining, I'm new to nix and your reply definitely saved me hours of debugging in the future 🙏

**Comment by rycee** [comment]
No problem. Glad it worked.

The behavior is relatively intuitive since to double check the hash Nix would have to re-download the source each time you build, which would be very inefficient.
