### ISSUE TITLE
Attribute 'packpathDirs' missing

### ISSUE THREAD

**Issue by giang-nghg** [nix-community/home-manager#3815]
Looks like a default value is needed for changes from this PR https://github.com/nix-community/home-manager/pull/3717

```
sudo nixos-rebuild switch
building Nix...
building the system configuration...
error: attribute 'packpathDirs' missing

       at /nix/store/85dawr294cn3mc2g7pxcjcprkxbn66kc-source/modules/programs/neovim.nix:403:8:

          402|       };
          403|     }) neovimConfig.packpathDirs);
             |        ^
          404|
```

**Comment by afh** [comment]
I'm also running into this issue.

@ncfavier can you advise on to update the nixpkgs?
I have run `nix-channel --update` with the following channels configured:

```
% nix-channel --list
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-22.11-darwin
% nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
"22.11pre432003.1e87cf2595f"
```

but the issue remains for me.

Do I just need to wait until [NixOS/nixpkgs#218786](https://github.com/NixOS/nixpkgs/pull/218786) is available on the `nixpkgs-22.11-darwin` channel (how long could roughly that take?) or switch to the `unstable` channel (which I'd like to avoid if possible)?

**Comment by ncfavier** [comment]
If you're on nixpkgs stable, you should follow home-manager's `release-22.11` branch, not master.

**Comment by afh** [comment]
That makes a lot of sense, @ncfavier! Thanks for the quick response and helping improve my setup; very much appreciated 🙏
