### ISSUE TITLE
xdg.desktopEntries requires 'exec' attribute be set

### ISSUE THREAD

**Issue by simplejack-src** [nix-community/home-manager#3825]
I don't have the home-manager repo checked out (to submit a PR), but noticed that `xdg.desktopEntries.<name>.exec` doesn't have a default value of `null`, making this attribute required to be set.

**Comment by ncfavier** [comment]
Is there any point in having a desktop entry with no `Exec` field?

**Comment by simplejack-src** [comment]
For one its not required by the specification, as another there are plenty of desktop entries that exist without an `Exec` key (ones where `Hidden`/`NoDisplay`/`DbusActivatable`/etc. alone may be set for instance).

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/3827

**Comment by ncfavier** [comment]
Looks like the desktop-file-utils tool used to validate desktop entries does not accept *actions* without an Exec key, although the spec allows it. Omitting the entry's Exec is fine, though.
