### ISSUE TITLE
bug: Why does `programs.man.enable` create a `.manpath` file in $HOME?

### ISSUE THREAD

**Issue by SuperSamus** [nix-community/home-manager#3836]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Ideally, files should not be created in the `$HOME`'s root, but they should be placed according [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

With home-manager, if the option `programs.man.enable` is set to `true` (which it is by default), then a file named `.manpath` will be placed in the `$HOME`'s root.
Other than the fact that it should not be placed here... what does this file do?

~I can't find any documentation online of a file named `.manpath` that does something.~ EDIT: Google is bad for searching documentation.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.2.7-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230331.3364b5b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
That's where [man(1)](https://man7.org/linux/man-pages/man1/man.1.html) looks for its configuration file by default. It seems like the only way to override it is to pass a flag to `man`.

**Comment by rycee** [comment]
Yeah, it's like @ncfavier says. Btw, the file should not be generated if you have just `programs.man.enable = true`, you also need to enable [`programs.man.generateCaches`](https://nix-community.github.io/home-manager/options.html#opt-programs.man.generateCaches).

In any case, we can't do much about this until the man tool itself is XDG directory aware so I'll close the issue. Feel free to create a new issue if the man package is updated to support the XDG directories.
