### ISSUE TITLE
bug: mcfly options not working

### ISSUE THREAD

**Issue by shauryagoel** [nix-community/home-manager#3844]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I was trying mcfly and its various options from home-manager docs. I was able to successfully enable mcfly, but options such as fuzzySearchFactor and keyScheme are not working. I have the following configuration- 
```
programs.mcfly = {
    enable = true;
    keyScheme = "vim";
    fuzzySearchFactor = 5;
  };
```

Besides mcfly enabling with Ctrl-R, the other options are not working.

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.2.8-arch1-1, Arch, noversion, rolling`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.13.3`
- channels(root): `"nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
It looks like those options set environment variables, so you might need to log out and back in for them to take effect.

**Comment by rycee** [comment]
@shauryagoel No, unfortunately that is folklore. At some point, I would like to simply have the activation script notify the user when any session variable has changed and ask them to relog if they want to apply the changes.
