### ISSUE TITLE
Specifying reload/restart triggers of systemd services

### ISSUE THREAD

**Issue by akirak** [nix-community/home-manager#3865]
It would be nice if home-manager allowed the user to configure restart conditions of user systemd services more flexibly. At present, systemd units are activated [here](https://github.com/nix-community/home-manager/blob/master/modules/systemd-activate.sh), and restarts are determined by making diffs of service files. On the other hand, NixOS supports [systemd.user.services.\<name\>.restartTriggers](https://search.nixos.org/options?channel=unstable&show=systemd.user.services.%3Cname%3E.restartTriggers&from=0&size=50&sort=relevance&type=packages&query=systemd+triggers), which are potentially useful in home-manager as well.

**Comment by rycee** [comment]
If you have `systemd.user.startServices=sd-switch` in your configuration then the `[Unit]` section can contain

    X-SwitchMethod=(reload|restart|stop-start|keep-old)

Where

- `reload` – reload the new unit
- `restart` – restart the new unit
- `stop-start` – stop the old unit and start the new unit
- `keep-old` – leave the old unit running

**Comment by akirak** [comment]
This is helpful! Actually, I don't require the functionality any more, because I have implemented an alternative solution to my problem, but `X-SwitchMethod` will be generally useful. 

I'll close this issue, as `sd-switch` seems to support the exact feature I requested here.
