### ISSUE TITLE
bug: The name org.freedesktop.Notifications was not found

### ISSUE THREAD

**Issue by gebeer** [nix-community/home-manager#3878]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

On a fairly blank arch install I got this error:
`GDBus.Error: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not found`

This happened towards the end of installation when the installer script tries to send a notification.

After installing libnotify and notification-daemon and configuring the daemon via dbus service the error went away.
You might want to catch that case in the installer script. Not everyone who installs home-manager will have a nitifcation system already setup.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.2.7-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rycee** [comment]
Pushed a fix to master. Please give it a try.
