### ISSUE TITLE
bug: `autorandr` fails to connect

### ISSUE THREAD

**Issue by kylechui** [nix-community/home-manager#3883]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm using both `programs.autorandr.enable` and `programs.xrandr.enable`. When I plug in my monitor, nothing happens. I did a bit of investigating by checking the output of `autorandr docked`, and got:
```sh
Failed to apply profile 'docked' (line 1018; /nix/store/p7lrm3nwbwjax7ivaww3nqjk4p59yssk-autorandr-1.13.3/bin/.autorandr-wrapped):
  Command failed: /nix/store/8bpn74k49bp2jslpnisxg1xc7c4j95ap-xrandr-1.5.1/bin/xrandr --fb 2560x1440 --output DP-1 --gamma 1.0:1.0:1.0 --mode 2560x1440 --primary --rate 71.97 --reflect normal --rotate normal (line 1018; /nix/store/p7lrm3nwbwjax7ivaww3nqjk4p59yssk-autorandr-1.13.3/bin/.autorandr-wrapped)
```
Retrying the command yields the same result, and it seems that I have to "refresh" something by running `xrandr --auto` before I am able to use `autorandr --change`. I imagine that if the error didn't happen, then I wouldn't even need to run `autorandr` commands manually and that things would "just work". Additionally, the same error occurs if I unplug my monitor:
- My monitor turns off due to lack of display signal
- My laptop screen does *not* turn on
- Running `autorandr mobile` yields a similar error

Please let me know if I'm missing any details!

### Maintainer CC

@GaetanLepage @uvNikita 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.23, NixOS, 23.05 (Stoat), 23.05.20230411.3fb8eed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kylechui** [comment]
Sorry for the typo, I meant I have both `services.autorandr.enable = true` and `programs.autorandr.enable = true`. I also have `xrandr` on my PATH. Running the command `autorandr mobile` *without unplugging my monitor* works just fine, and then if I do *autorandr docked* right after that switches it back to my monitor. The issue is that when I unplug my monitor from my laptop (FWIW I am using a USB-C hub for this), the profile does change to `mobile`, but the display for my laptop stays off. I then have to do something like `autorandr --change` to force it to "update" and match the profile. Hopefully I am making things more clear, sorry for the confusion.

**Comment by GaetanLepage** [comment]
Well, setting `services.autorandr.enable = true`  will automate the launch of `autorandr` only when you log in to your session.
The HM module is not setting other automation that run `autorandr` automatically when you plug/unplug a monitor.
It is then normal to have to run `autorandr --change` explicitly when you need to.

Now, if `autorandr --change` fails, that is another story.
Then, you have to check if the equivalent `xrandr` command fails as well.
Sorry if I don't understand your question ^^
