### ISSUE TITLE
`polybar` service can't use `pulseaudio` module

### ISSUE THREAD

**Issue by kylechui** [nix-community/home-manager#3884]
### Description

As it stands, I don't think there exists a way to get a `pulseaudio` module working for `polybar`. There already exists `i3Support`, `alsaSupport`, etc.; I would like to see something like `pulseaudioSupport` for the `polybar` service.

Here's the current output when polybar is installed via `services.polybar.enable = true;`
```
$ polybar -v
polybar 3.6.3

Features: +alsa -curl -i3 -mpd +network(libnl) -pulseaudio +xkeyboard
```

**Comment by ncfavier** [comment]
This has nothing to do with home-manager, you're looking for the nixpkgs [polybar package](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/polybar/default.nix), which seems to have a `pulseSupport` option.
