### ISSUE TITLE
Request: add Mako systemd user service option

### ISSUE THREAD

**Issue by stelcodes** [nix-community/home-manager#3893]
### Description
Currently there is no systemd user service defined in `modules/services/mako.nix`. This is strange because service modules for long running processes usually include a systemd service option (see waybar, swayidle, wlsunset, etc) but the only thing in the Mako module currently that starts Mako is the `xdg.configFile."mako/config".onChange` trigger  via `${cfg.package}/bin/makoctl reload || true`.

This config file trigger is not a good solution because it is in no way bound to a Wayland session and users may want to change their Mako config without starting Mako (i.e. while inside an Xorg session). The omission of a systemd service option has already confused some users (#2028).

A systemd user service option should be added, just like wlsunset for example.

**Comment by ncfavier** [comment]
Is this actually needed? See https://github.com/emersion/mako#running

**Comment by stelcodes** [comment]
@ncfavier Oh I did not know that. How does that work? Could another installed Wayland notification daemon replace Mako as the "default" dbus-triggered Wayland notification program?

**Comment by ncfavier** [comment]
I don't know, I don't use wayland.

**Comment by stelcodes** [comment]
This is from the `services.fnott` Wayland notification daemon module:
```
  config = mkIf cfg.enable {
    assertions =
      [ (hm.assertions.assertPlatform "services.fnott" pkgs platforms.linux) ];

    home.packages = [ cfg.package ];

    systemd.user.services.fnott = {
      Unit = {
        Description = "Fnott notification daemon";
        Documentation = "man:fnott(1)";
        After = [ "graphical-session-pre.target" ];
        PartOf = [ "graphical-session.target" ];
      };

      Service = {
        Type = "dbus";
        BusName = "org.freedesktop.Notifications";
        ExecStart = concatStringsSep' " " [
          "${cfg.package}/bin/fnott"
          "-c ${escapeShellArg cfg.configFile}"
          (escapeShellArgs cfg.extraFlags)
        ];
      };
    };

    xdg.configFile."fnott/fnott.ini".source =
      iniFormat.generate "fnott.ini" cfg.settings;
  };
}
```
Seems like a more appropriate service definition.

**Comment by stelcodes** [comment]
Closing this issue because Mako does work without a systemd service, and I personally don't have any issue.

**Comment by v4rakh** [comment]
I think this really makes sense because of actions and the required sh on PATH. See my comment here: https://github.com/nix-community/home-manager/pull/3266#issuecomment-1950236875

**Comment by stelcodes** [comment]
@v4rakh I do not use any actions, that's correct. You should probably just define your own systemd user service in the meantime but I think this does provide enough justification to add a `services.mako` option in home-manager.

**Comment by v4rakh** [comment]
Asking out of curiosity here, where's the silver line when to add such a feature and when to not add it? IMO, when the default (how it is currently) is not covering the feature set the underlying application supports, that would be an indicator for me to add such a service, but I haven't had much contact with the Nix community as of now. :-)

Actually I did go the easy path of starting it within the sway module which works fine an `PATH` is correct there.

**Comment by stelcodes** [comment]
@v4rakh I agree with you, I think home-manager should try to fix this issue. But actually now that I think about it, the best way to fix this would be to create a wrapper derivation around mako that adds `sh` to the `PATH` as part of the `programs.mako` option.

**Comment by stelcodes** [comment]
@v4rakh @sumnerevans Just want to let y'all know that I fixed the core issue in [this PR](https://github.com/NixOS/nixpkgs/pull/290387) that was just merged into nixpkgs unstable. With that change, `sh` is always in `mako`'s `PATH` and `exec` will work with the normal D-Bus activation, no systemd service required. But you may have to restart D-Bus (by rebooting) in order to see the change take effect.
