### ISSUE TITLE
bug: (undocumented) gnome-terminal profile <name> must be UUID

### ISSUE THREAD

**Issue by MichaelMMacLeod** [nix-community/home-manager#3923]
### Are you following the right branch?

- [x] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Configuring gnome-terminal requires that `<name>` in `profile.<name>.<option>` be a UUID (any UUID works), but this is not documented. If it is anything other than a UUID then the profile will not be shown in the options or activated (even if it is marked as default).

For example, the following configuration correctly creates a profile whose visible name is "profile1":
```nix
programs.gnome-terminal = {
  enable = true;
  profile."060efe23-3ab4-4c71-8a38-dd13f89b400d" = {
    visibleName = "profile1";
    audibleBell = false;
    customCommand = "zsh";
    default = true;
  };
  themeVariant = "dark";
  showMenubar = false;
};
```
I discovered this by running `dconf watch /org/gnome/terminal/legacy/profiles:/` and then manually creating a new profile named "MyProfile". I got the following output:
```
/org/gnome/terminal/legacy/profiles:/:04aa0881-b94f-47a3-8f83-83bda85750aa/visible-name
  'MyProfile'
```
If, in the configuration, I replace `profile."060efe23-3ab4-4c71-8a38-dd13f89b400d"` with `profile.profile1`, I get the following output from dconf:
```
/org/gnome/terminal/legacy/profiles:/:profile1/visible-name
  'profile1'
```
The profile only seems to be created when the `<name>` in `/org/gnome/terminal/legacy/profiles:/:<name>/visible-name` is a UUID.

A fix for this could be to document that `<name>` must be a UUID. 

Alternatively, given that `<name>` in `profile.<name>.<option>` doesn't have any good use other than to be a UUID, the following could be done:
1. the `profile.<name>.visibleName` option is removed; 
2. `<name>` in `profile.<name>.<option>` is used to set `/org/gnome/terminal/legacy/profiles:/:<UUID>/visible-name`; 
3.  `<name>` in `profile.<name>.<option>` is passed to something akin to `uuidgen --sha1 --namespace '@oid' --name profile.<name>` to deterministically generate the UUID in  `/org/gnome/terminal/legacy/profiles:/:<UUID>/` for the profile.

### Maintainer CC

@kamadorueda @rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.25, NixOS, 23.05 (Stoat), 23.05.20230423.8f33856`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
I think this got resolved in f58889c07efa8e1328fdf93dc1796ec2a5c47f38. Basically, the `programs.gnome-terminal.profile` option description now state that the name has to be an UUID. And there is an assertion verifying that they are UUIDs.

I'll close the issue, if you feel this is incorrect then feel free to comment and we'll reopen.
