### ISSUE TITLE
bug: Upgrade throws error in stdlib-extended

### ISSUE THREAD

**Issue by farnoy** [nix-community/home-manager#3928]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm using NixOS stable 22.11 and HM installed as a NixOS module in a single flake. After upgrading both nixpkgs and HM, I started seeing an error in stdlib-extended.nix from HM.

```
• Updated input 'home-manager':
    'github:nix-community/home-manager/bf5712c5865e543fb3f4796511d4cf51efd841b1' (2023-03-11)
  → 'github:nix-community/home-manager/43ba4489bd3f9f69519f5f7ebdb76d0455eccbbe' (2023-04-28)
• Removed input 'home-manager/utils'
• Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/5eb98948b66de29f899c7fe27ae112a47964baf8' (2023-03-11)
  → 'github:NixOS/nixpkgs/15b75800dce80225b44f067c9012b09de37dfad2' (2023-04-26)
```

Started throwing this error:

```
error: attribute 'extend' missing

       at /nix/store/bmxyjabn7zj054239gyx3kga44wi8v91-source/modules/lib/stdlib-extended.nix:7:4:

            6| let mkHmLib = import ./.;
            7| in nixpkgsLib.extend (self: super: {
             |    ^
            8|   hm = mkHmLib { lib = self; };
       Did you mean extends?
```

Seems to make sense, as nixpkgs has had `extends` [for a long time](https://github.com/NixOS/nixpkgs/blame/nixos-22.11/lib/default.nix#L76) and at least in the nixos-22.11 branch, those exports for `nixpkgs.lib` haven't changed in the past 3 months.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.16, NixOS, 22.11 (Raccoon), 22.11.20230311.5eb9894`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager, nixos"`
 - channels(kuba): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/kuba/.nix-defexpr/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
You should use the branch of home-manager corresponding to your branch of nixpkgs, in this case `release-21.11`. See https://github.com/nix-community/home-manager#releases
