### ISSUE TITLE
Add Firefox bookmark tags

### ISSUE THREAD

**Issue by cvoges12** [nix-community/home-manager#3941]
### Description

Firefox has a feature to [tag your bookmarks](https://support.mozilla.org/en-US/kb/categorizing-bookmarks-make-them-easy-to-find?redirectslug=Bookmark+Tags&redirectlocale=en-US) instead of just organizing them by directory tree.

It would be nice if bookmarks could be tagged in [home-manager's bookmark option](https://github.com/nix-community/home-manager/blob/master/modules/programs/firefox.nix#L62).

This feature lacking prevents the tags from being used because rebuilding the bookmarks option overwrites any existing bookmarks. It practically makes tags unusable without adding it to home-manager because of this effect.

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/3942
