### ISSUE TITLE
bug: Cannot uninstall in a flake-only install

### ISSUE THREAD

**Issue by JulienMalka** [nix-community/home-manager#3948]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hello, I'm using a flake-only (no channels) system.
I have installed home-manager like so: 
```
nix run home-manager -- init --switch
```
Home-manager works fine, but when trying to uninstall I get:
```
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
```

### System information

```markdown
- system: `"x86_64-linux"` 
- host os: `Linux 5.19.0-41-generic, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild` 
- multi-user?: `yes` 
- sandbox: `yes` - version: `nix-env (Nix) 2.13.3` 
- nixpkgs: `/nix/store/ngskiw91l3fbqnkmzd45s22mfqb7a42v-source`
```

**Comment by nakoo** [comment]
I had the same issue with this. Is there a workaround before getting it merged?

**Comment by rycee** [comment]
If you update to latest master then this should, hopefully, be fixed now.

**Comment by JulienMalka** [comment]
Does work for me
