### ISSUE TITLE
bug: wrong path for hm-session-vars.sh

### ISSUE THREAD

**Issue by tbenst** [nix-community/home-manager#3952]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

On a new standalone Flakes install of home-manager on Ubuntu 22.04, I get an error like: `/home/tyler/.zshenv:.:2: no such file or directory: /home/tyler/.nix-profile/etc/profile.d/hm-session-vars.sh`.

I have the following symlink: `~/.nix-profile -> /nix/var/nix/profiles/per-user/tyler/home-manager`. By using `fd hm-session-vars.sh`, I see the following path:
`/nix/var/nix/profiles/per-user/tyler/home-manager/home-path/etc/profile.d/hm-session-vars.sh`

Therefore, while `/home/tyler/.nix-profile/etc/profile.d/hm-session-vars.sh` does not exist, `/home/tyler/.nix-profile/home-path/etc/profile.d/hm-session-vars.sh` does exist.

I think this is created by https://github.com/nix-community/home-manager/blob/38271ead8e7b291beb9d3b8312e66c3268796c0a/modules/home-environment.nix#L727.

However, it appears that home-manager uses the wrong link, https://github.com/nix-community/home-manager/blob/38271ead8e7b291beb9d3b8312e66c3268796c0a/modules/programs/zsh.nix#L474

This happens several places in the code base, for example here as well https://github.com/nix-community/home-manager/blob/38271ead8e7b291beb9d3b8312e66c3268796c0a/modules/targets/generic-linux.nix#L70 

Note that `home-path` is not part of `profileDirectory`: https://github.com/nix-community/home-manager/blob/38271ead8e7b291beb9d3b8312e66c3268796c0a/modules/home-environment.nix#L507-L511

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
error:
       … <borked>

         at «none»:0: (source not available)

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
```

**Comment by rycee** [comment]
Yeah, the Home Manager generation is definitely not intended to be used directly as a Nix profile. You'll want to link `~/.nix-profile` to `/nix/var/nix/profiles/per-user/$USER/profile` instead.

**Comment by tbenst** [comment]
Amazing thanks! That resolves the issue.

**Comment by Ay4namiR3i** [comment]
What can i do if i dont even have my user in /nix/var/nix/profiles/per-user/
