### ISSUE TITLE
bug: 38271ea breaks paths

### ISSUE THREAD

**Issue by GenericNerdyUsername** [nix-community/home-manager#3960]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

after 38271ea, putting nix store paths in your xfconf config fails with the error `access to canonical path '[path]' is forbidden in restricted mode`

example:
`xfce4-desktop.backdrop.screen0.monitoreDP-1.workspace0.last-image = pkgs.nixos-artwork.wallpapers.nineish-dark-gray.gnomeFilePath`

### Maintainer CC

@gou4shi1 @chuangzhu 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.3.1, NixOS, 23.05 (Stoat), 23.05.20230504.2395e4f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/3961

**Comment by ncfavier** [comment]
Thanks, should be fixed now.

**Comment by GenericNerdyUsername** [comment]
Everything is working as expected now. Thanks!

**Comment by gou4shi1** [comment]
Thanks for your fix, I was not aware of this :cry:
