### ISSUE TITLE
bug: borgmatic conflicting values

### ISSUE THREAD

**Issue by cyntheticfox** [nix-community/home-manager#3971]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

On master, the `borgmatic-program-exclude-hm-symlinks` test fails with:

```txt
error: The option `programs.borgmatic.backups.main.location.extraConfig.exclude_from' has conflicting definition values:
       - In `/home/cynthia/repos/home-manager/tests/modules/programs/borgmatic/exclude-hm-symlinks.nix':
           [
             "/nix/store/pmq27zqfly93wvjgy6y5n67f457c0gb3-excludeFile.txt"
           ]
       - In `/home/cynthia/repos/home-manager/modules/programs/borgmatic.nix':
           [
             "/nix/store/va42wvgk47rf1bac3p7gly00pybv0jy8-hm-symlinks.txt"
           ]
(use '--show-trace' to show detailed location information)
```

Run via `nix-shell --pure tests -A run.borgmatic-program-exclude-hm-symlinks`

### Maintainer CC

@DamienCassou

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.2.13, NixOS, 22.11 (Raccoon), 22.11.20230504.cc45a3f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cyntheticfox** [comment]
it's this exact error from <https://github.com/nix-community/home-manager/pull/3787#discussion_r1142665947>, but surely the `home-manager` test system doesn't use your own system packages, right?

**Comment by ncfavier** [comment]
The `nix-shell` interface just imports `<nixpkgs>`, so you can set that with `-I nixpkgs=` or use `nix develop .#all`.
