### ISSUE TITLE
bug: not a valid garbage collector root

### ISSUE THREAD

**Issue by Kineolyan** [nix-community/home-manager#3980]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After a recent upgrade of home-manager and nix channels _unstable_ and _22.11_, every call to `home-manager switch` ends in failure with the following message:

```console 
/nix/store/hn4f8bwynwb2nvb9cnsgs9ni2nsygv2v-home-manager-generation
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating linkGeneration
Cleaning up orphan links from /home/oliv
Creating profile generation 280
error: path '/home/oliv/.local/state/home-manager/gcroots/current-home' is not a valid garbage collector root; it's not in the directory '/nix/var/nix/gcroots'
```

Grabbing the nix store entry, I can activate it manually. However, when running `home-manager generations`, none of the generations are marked as current.

The directory _.local/state/home-manager/gcroots_ in my user home does not exist, nor the file _current-home_ in it. Manually creating the directory does not solve the issue.
I do see a gcroot that seems to be matching _/nix/var/nix/gcroots/per-user/oliv/current-home_, pointing to my oldest generation. But I don't know what to do of it :shrug: 

Please, help :smiley: 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.19.0-41-generic, Ubuntu, 22.10 (Kinetic Kudu), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(oliv): `"edgepkgs-23.05pre483213.635a306fc8e, home-manager, nixpkgs-22.11.4091.a08e061a4ee"`
 - nixpkgs: `/home/oliv/.nix-defexpr/channels/nixpkgs`
```

**Comment by Kineolyan** [comment]
I did some investigation, trying to understand the problem.

The build of the home-manager generation works perfectly. I can inspect the generation, activate it manually. It contains the stuff I configured. Great :tada: 

The issue occurs when activating the generation and trying to migrate the profile.
https://github.com/nix-community/home-manager/blob/70c8bd08e6c186e5c628a4e5af6f7ad67cd344b8/modules/lib-bash/activation-init.sh#L4-L10
I believe that on my side, the NIX_STATE_DIR is not set, causing it to default to _/nix/var/nix_.
And when the activation tries to add the new root, `nix-store` complains about the new root not being under _/nix/var/nix/gcroots_.
Looking at the related now-closed PR, it seems that this change is recent and there is maybe something off in my setup.

@rycee seeing that you commented on the PR, you may have more informed guesses regarding what could be wrong.

**Comment by Kineolyan** [comment]
Some additional information:
I do see the home-manager generations under _/nix/var/nix/profiles/per-user/myname_. And _/nix/var/nix/per-user/myname_ contains only _current-home_, as mentionned before.

**Comment by rycee** [comment]
I think you may want to update your Nix installation. Version 2.3.10 is quite old.

Also, if you want to use Nixpkgs 22.11 then you should use the release-22.11 branch of Home Manager. That branch does not contain the code that migrates profiles and gcroot to `~/.local/state`.

**Comment by Kineolyan** [comment]
Thanks @rycee . I am quite ashamed as I thought about updating home-manager and my channels but forgot about `nix` (though being a newb to nix stuff, I did not know a command `nix upgrade-nix` existed).

Now that `nix` is at version 2.13.3, everything works fine. I will close this issue.

**Comment by Kineolyan** [comment]
> Also, if you want to use Nixpkgs 22.11 then you should use the release-22.11 branch of Home Manager.

I don't understand that comment. I specially switch to nixpkgs 22.11 to be sync with the value of `home.stateVersion = "22.11"`. Having re-read the installation guide and manual, I don't understand how to "use the release-22.11 branch of Home Manager".
Can you shed some light on your comment?

Still, many thanks again for your answers and sorry for my silly mistake.

**Comment by ncfavier** [comment]
You should not try to stay in sync with `stateVersion`. That value is meant to stay constant as you upgrade your installation, so that things keep working in the current state of your machine.

The manual explains how to use a release branch of home-manager:

> and if you follow a Nixpkgs version 22.11 channel you can run
>  ```
>  nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz home-manager
>
>  nix-channel --update
>  ```

**Comment by Kineolyan** [comment]
:disappointed: Yes, it is plainly written...
Thanks @ncfavier

**Comment by Kineolyan** [comment]
Final comment here, for the sake of transparency:
I tried to install the 22.11 release, as suggested by your comments and the manual. However, with `nix` 2.13.3, it failed because `NIX_PATH` is not set.
Looking at this, it seems absent from non-nixOS system https://github.com/NixOS/nixpkgs/issues/149791, though channels are correctly found.

So, for now, as everything is working, I will live dangerously :smile: In the end, if I understand it correctly, the issue will be that programs and services as configured in home-manager master _could_ fail when applied on 22.11 pkgs. If so, I think that I will just replace the package by its nixpkgs-unstable version, waiting for the release of 23.05

Cheers to all :wave:
