### ISSUE TITLE
Change deploy path for each individual file

### ISSUE THREAD

**Issue by JakeDevs** [nix-community/home-manager#3985]
It would be convenient to be able to change deploy path for each individual file. For example :

home.file {
     ".bashrc".source = ~/.dotfiles/.bashrc;

     ".bashrc".deploy = ~/Downloads;

};

**Comment by JakeDevs** [comment]
not sure why the text was crossed out

**Comment by ncfavier** [comment]
I don't understand, what do you mean by "deploy path"? If you want the file to be in `~/Downloads` you can do

```nix
home.file."Downloads/.bashrc".source = ...;
```

P.S. you can use backticks to insert code, cf. https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by JakeDevs** [comment]
my mistake.
