### ISSUE TITLE
bug: could not set programs.kitty.theme

### ISSUE THREAD

**Issue by pirey** [nix-community/home-manager#3988]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

i use the following value for the option
```
programs.kitty.theme = "Tokyo Night Moon";
```

and i got the following error

```
error: list index 0 is out of bounds

       at /nix/store/4v8mj95srhrsjv85bkx9kyq8kc5plnmk-source/modules/programs/kitty.nix:138:14:

          137|           include ${pkgs.kitty-themes}/${
          138|             (head (filter (x: x.name == cfg.theme) (builtins.fromJSON
             |              ^
          139|               (builtins.readFile "${pkgs.kitty-themes}/themes.json")))).file
(use '--show-trace' to show detailed location information)
```

my configuration https://github.com/pirey/dotfiles/blob/master/home-manager/home.nix

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.94, NixOS, 22.11 (Raccoon), 22.11.20230219.0cf4274`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
So your `kitty-themes` package doesn't have that theme. It was added [recently](https://github.com/kovidgoyal/kitty-themes/commit/edb3944565c280578c7e6a1a56a49d46759f375c), try updating or using an unstable branch.

The error message could be clearer though.

**Comment by pirey** [comment]
I tried to check the available themes using `kitty +kitten themes` command and turns out the theme is available.
![image](https://github.com/nix-community/home-manager/assets/10344542/6675c8df-d25b-42f8-971b-4873fa73bf2f)

I also tried your suggestion and added unstable nixpkgs overlay and install kitty-themes from there, but the issue still persists.
https://github.com/pirey/dotfiles/blob/master/home-manager/home.nix#L64

I'm still new to nix, so I'm not sure what I'm missing or which part did I do wrong here.

**Comment by ncfavier** [comment]
Ah, I just noticed https://github.com/nix-community/home-manager/pull/3764.

The root of the issue is that you're following `nixos-22.11`, but home-manager `master`.

Did you read the issue template?

> You should follow the branch of Home Manager that corresponds to your
version of Nixpkgs; see [the README](https://github.com/nix-community/home-manager#releases) for details.

**Comment by pirey** [comment]
I tried to configure the home manager using release 22.11 and then configure kitty from unstable. 
https://github.com/pirey/dotfiles/commit/bc22025cc7c878bf81d96da7fbd5a8414db6ad21
But I still got the same error.
I would appreciate it if you give me more clues on how to solve this.

**Comment by ncfavier** [comment]
The theme you want is only in a version of kitty-themes with the new path, so you have two options:
- use unstable versions of home-manager and nixos
- use an overlay to move the files back to the old (pre- https://github.com/NixOS/nixpkgs/pull/220872) path

**Comment by eureka-cpu** [comment]
Honestly, this issue has been plaguing me for a while now. It doesn't seem to matter if I use the same version of home-manager and nixpkgs releases. I can see that the theme I want is available with `kitten themes`, but home-manager insists that it doesn't exist. I've tried 25.05 and 25.11, and no dice, it can't seem to find the theme file even though it does exist. Would be nice if there was a way to just provide the package for the themes to the kitty module.
