### ISSUE TITLE
Merge .Xresources

### ISSUE THREAD

**Issue by lukasstevens** [nix-community/home-manager#400]
When changing `windowManager.i3.extraConfig` and performing `home-manager switch` the i3 window manager is automatically reloaded; however, this is not true when `xresources.extraConfig` is changed. I would expect that at least the command `xrdb -merge .Xresources` is suggested. Unfortunately I am not really familiar with nix and don't know how to change that. Maybe somebody can help me?

**Comment by lukasstevens** [comment]
Thanks for the quick fix and for this amazing project in general.

**Comment by rycee** [comment]
No worries and glad you like it! Report more issues if you find them, but don't count on the fix always being this fast 😉
