### ISSUE TITLE
bug: `xdg.configFile.<name>.source` and `xdg.configFile.<name>.text` Manual Text Incorrect

### ISSUE THREAD

**Issue by ArchieAtkinson** [nix-community/home-manager#4005]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The documentation in the manual for [xdg.configFile.<name>.source](https://nix-community.github.io/home-manager/options.html#opt-xdg.configFile._name_.source) and [xdg.configFile.<name>.text](https://nix-community.github.io/home-manager/options.html#opt-xdg.configFile._name_.text) both reference their home.file.<name> equivalents. I assume this is an error.

### Maintainer CC

N/A

### System information

```markdown
N/A
```

**Comment by ncfavier** [comment]
Thanks! Opened https://github.com/nix-community/home-manager/pull/4007
