### ISSUE TITLE
Create a release-23.05 branch

### ISSUE THREAD

**Issue by ajs124** [nix-community/home-manager#4013]
Same procedure as every NixOS branch-off

**Comment by rycee** [comment]
Created a branch earlier today 🙂 It'll just be a mirror of master for a while.

**Comment by Nairou** [comment]
I assume this will lead to a version bump for master? I currently get a version mismatch between Home Manager and nixpkgs-unstable.

```
warning: You are using

  Home Manager version 23.05 and
  Nixpkgs version 23.11.```
