### ISSUE TITLE
bug: error: A definition for option `home-manager.users.[me].programs.foot.enable' is not of type `boolean'.

### ISSUE THREAD

**Issue by featherfurl** [nix-community/home-manager#4020]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When adding `programs.foot.enable = "true";` to my home-manager configuration I get the following error:

```
error: A definition for option `home-manager.users.featherfurl.programs.foot.enable' is not of type `boolean'. Definition values:
       - In `/etc/nixos/configuration.nix': "true"
```

According to the documentation, programs.foot.enable expects `Type: Boolean`
Using the same syntax, `programs.foot.server.enable = "true";` works fine, so I'm guessing there's an error in the option definition somewhere.

### Maintainer CC

@plabadens

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.05 (Stoat), 23.05pre484309.0470f36b02e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
`"true"` is a string. `true` is a boolean.

**Comment by ncfavier** [comment]
> Using the same syntax, `programs.foot.server.enable = "true";` works fine

More likely that's not getting evaluated because you didn't enable foot, so the error is not triggered.

**Comment by featherfurl** [comment]
Wow I'm blind. Not sure how I triple checked this without seeing that it was different from every single other boolean definition in my config.
