### ISSUE TITLE
bug: Most recent commit "ssh: don't install a client by default (#4016) "  appears to give me "called with unexpected argument 'nullable'" when I rebuild.

### ISSUE THREAD

**Issue by featherfurl** [nix-community/home-manager#4030]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

As of a couple days ago, running `sudo nixos-rebuild test` fails, giving me the following error:

```
error: 'mkPackageOption' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/options.nix:157:7 called with unexpected argument 'nullable'

       at /nix/store/pwgz2jsy0iymnqjcs2rj8hshmxqa8qcp-source/modules/programs/ssh.nix:364:15:

          363|
          364|     package = mkPackageOption pkgs "openssh" {
             |               ^
          365|       nullable = true;
```
This appears to relate directly to the most recent commit in both timing and substance. Is there anything I can do on my end to fix this or is it just a bug that needs addressing?

### Maintainer CC

@nc

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.05 (Stoat), 23.05pre484309.0470f36b02e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(featherfurl): `"nixos-23.05-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
Update your nixpkgs, the relevant change is in all unstable channels.

**Comment by featherfurl** [comment]
Yeah the problem was that I was foolishly running "nix-channel --update" instead of "sudo nix-channel --update" and it was succeeding so I assumed it was updating correctly.
