### ISSUE TITLE
support attrSets inside `programs.aerc.stylesets.<styleset-name>`

### ISSUE THREAD

**Issue by onemoresuza** [nix-community/home-manager#4037]
### Description

As of [aerc 0.15][aerc-0.15], stylesets are now able to modify the coloring of the `colorize` filter by having a `[viewer]` section like so:

```ini
[viewer]
url=1
header=2
# etc
```

However, it is not possible to define it through `home-manager` since the `stylesets` attrSet of `programs.aerc` throws the following error when given an attrSet:

> error: A definition for option \`programs.aerc.stylesets.\<styleset-name\>.viewer' is not of type 
> \`values (null, bool, int, string of float) or a list of values, that will be joined with a 
> comma'. Definition values:
>       - In `/nix/store/\<path-to-derivation\>':
>          {
>            url = 1;
>            header = 2;
>          }

[aerc-0.15]: <https://git.sr.ht/~rjarry/aerc/refs/0.15.0> "Aerc's 0.15 Release"

**Comment by Ma27** [comment]
Why was this closed as "completed"? This seems to still be an issue.

**Comment by karlprieb** [comment]
Can we reopen this issue? I can reproduce the same problem @Ma27 was having.

**Comment by echozio** [comment]
Fixed in master now

**Comment by jghauser** [comment]
I'm not sure this is fixed. While we can now have a `[viewer]` section, allowing us to adjust the `colorizer` filter, it seems no longer possible to define the rest of the styleset. Setting it under the `[ui]` section as suggested by home-manager seems to be ignored by aerc. It looks like aerc expects ui styleset settings at the top level, and viewer and user settings under the `[viewer]` and `[user]` sections, respectively.

**Comment by echozio** [comment]
> I'm not sure this is fixed. While we can now have a `[viewer]` section, allowing us to adjust the `colorizer` filter, it seems no longer possible to define the rest of the styleset. Setting it under the `[ui]` section as suggested by home-manager seems to be ignored by aerc. It looks like aerc expects ui styleset settings at the top level, and viewer and user settings under the `[viewer]` and `[user]` sections, respectively.

Anything you set under `global` will end up at the top-level, before sections.

**Comment by jghauser** [comment]
oh, thanks a lot! i should have looked at the source code. i got confused as i couldn't find any reference to a `[ui]` section anywhere in the aerc manual or the default stylesets.
