### ISSUE TITLE
bug: bat.nix extraPackages option not available

### ISSUE THREAD

**Issue by godsmith99x** [nix-community/home-manager#4043]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hi, I'm trying to configure the bat command line utility and hitting an error

Here is my config:
```
{
  programs.bat = {
    enable = true;
    config = {
        theme = "Dracula";
    };
    extraPackages = with pkgs.bat-extras; [
      batdiff # git diff
      batgrep # grep replacement
      batman # manual highlighter
    ];
  };
}
```

And here is the error:
```
error: The option `home-manager.users.godsmith.programs.bat.extraPackages' does not exist. Definition values:
       - In `/etc/nixos/apps/bat/bat.nix':
           [
             <derivation /nix/store/hq54yvvm4d3sfgyfmzbj9vf5v2pff5cd-bat-extras-batdiff-2021.04.06.drv>
             <derivation /nix/store/4q7rpxz3i96nrwawzxrbdbjgdc9n1slg-bat-extras-batgrep-2021.04.06.drv>
             <derivation /nix/store/l6j6ndny9kf13ydcw4s7psiq00fhb5si-bat-extras-batman-2021.04.06.drv>
           ]
```

When I look at the home-configuration.nix man page, I DO NOT see the extraPackages option for bat. However, when I look the bat.nix program module, it IS there (https://github.com/nix-community/home-manager/blob/master/modules/programs/bat.nix#blob-path).

Can you please help me determine what I'm doing wrong?

### Maintainer CC

 @sielicki @ryc

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.15.112, NixOS, 22.11 (Raccoon), 22.11.4433.9af373a6164`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.11.1`
- channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
You're looking at the master branch while using 22.11. That option was added somewhere in between.

**Comment by godsmith99x** [comment]
You're so right. Thank you.

> You're looking at the master branch while using 22.11. That option was added somewhere in between.
