### ISSUE TITLE
bug: `programs.wezterm` does not install the `terminfo` file

### ISSUE THREAD

**Issue by mrjones2014** [nix-community/home-manager#4047]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

`programs.wezterm.enable = true` should install the terminfo for Wezterm. I've done this in my own `home-manager` config like so, but I think it should be installed by default:

```nix
home.activation.installWeztermTerminfo = ''
  ${pkgs.ncurses}/bin/tic -x -o $HOME/.terminfo ${
    pkgs.fetchurl {
      url =
        "https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo";
      sha256 = "P+mUyBjCvblCtqOmNZlc2bqUU32tMNWpYO9g25KAgNs=";
    }
  }
'';
```

### Maintainer CC

@blmhemu 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
So wezterm has a `wezterm.terminfo` attribute that you can just add to `home.packages`. I agree that this should happen automatically, but I'm not sure what the best way to do that is. Maybe we could add that output to wezterm's `propagated-user-env-packages`, as is [done](https://github.com/NixOS/nixpkgs/blob/5e871d8aa6f57cc8e0dc087d1c5013f6e212b4ce/pkgs/applications/terminal-emulators/alacritty/default.nix#L124) for alacritty?

@SuperSandro2000 any thoughts?

**Comment by mrjones2014** [comment]
>wezterm has a wezterm.terminfo attribute that you can just add to home.packages

cool, thanks for that info, in the meantime I'll switch to this approach until its done automatically.

**Comment by SuperSandro2000** [comment]
You don't need the to change your TERM variable to be able to use wezterm and just installing the terminfo is also not enough, you also need to change the config setting to use it. See https://wezfurlong.org/wezterm/config/lua/config/term.html

So just propagating the extra output is not enough and I don't think we need to do it by default or should change the term by default since it breaks the ability to ssh into machines that do not know about the term and then your term gets downgraded to one that supports almost nothing.

**Comment by mrjones2014** [comment]
> it breaks the ability to ssh into machines that do not know about the term and then your term gets downgraded to one that supports almost nothing.

Good point, fair enough.
