### ISSUE TITLE
Add declarative config options for Syncthing

### ISSUE THREAD

**Issue by Anomalocaridid** [nix-community/home-manager#4049]
### Description
The syncthing service can be declaratively configured at the OS level using the various nixpkgs options under `services.syncthing`. However, Home Manager lacks equivalents for all except for the bare minimum, which makes declaratively configuring syncthing from userspace significantly more difficult.

**Comment by charlot-shaw** [comment]
I also would appreciate better configuration for syncthing via home-manager.

**Comment by Thymelizabeth** [comment]
Syncthing has just changed to using $XDG_STATE_DIR by default, which could change things.

**Comment by MattSturgeon** [comment]
Looks like NixOS does this fairly _imperatively_;

At build time it [generates](https://github.com/NixOS/nixpkgs/blob/3cb4ae6689d2aa3f363516234572613b31212b78/nixos/modules/services/networking/syncthing.nix#L48-L144) an `updateConfig` shell script, which does most of its work by calling Syncthing's REST API (at `localhost:8384`) using `curl`.

This shell script then gets [run by](https://github.com/NixOS/nixpkgs/blob/3cb4ae6689d2aa3f363516234572613b31212b78/nixos/modules/services/networking/syncthing.nix#L713) one of the systemd services.

I don't see any reason why the NixOS solution couldn't be ported to home-manager more-or-less as-is?

**Comment by TheHans255** [comment]
+1 for this. In particular, I can't set up Syncthing as a system level service because I need to have two separate instances of Syncthing running on the same computer for different users.

**Comment by HPRIOR** [comment]
> Just as a heads up for those of you (like @HPRIOR) that use synching also on Darwin: PR #6104 expands the linux solution for a declarative config from the recently merged PR #5616 to Darwin. I've been using it for the past two months in an environment with Linux and Darwin systems without problems. I'd be happy over any reviews on the PR or general feedback if you run into problems.

Great thanks. I'll check it out when I get a chance
