### ISSUE TITLE
bug: espanso >=2 (now in nixpkgs) requires config update

### ISSUE THREAD

**Issue by n8henrie** [nix-community/home-manager#4052]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Looks like an update for espanso snuck in just in time for 23.05: https://github.com/NixOS/nixpkgs/pull/231062/commits/5762a20a253e88a8dd9b2e49a6719fda00cb54ca

Espanso >= 2 requires a config format update, format is at https://espanso.org/docs/configuration/basics/

The link for documentation is also out of date, should probably be updated to the above.

I'm happy to help work on PR but will not likely have time for 6 weeks or so.

### Maintainer CC

@lucasew

### System information

```markdown
Not machine specific
```

**Comment by ncfavier** [comment]
> Will the fix get back ported to 23.05?

Done.

**Comment by Nebucatnetzer** [comment]
Thank you very much💪
