### ISSUE TITLE
bug: "org/gnome/desktop/peripherals/mouse" is not of type `GVariant value'.

### ISSUE THREAD

**Issue by DEEENGAN** [nix-community/home-manager#4057]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I was wanting to declare my mouse settings via home-manager, but this error cropped up:

`"org/gnome/desktop/peripherals/mouse" is not of type `GVariant value'.`

Am unsure if this is meant to be, or if it has just not been included yet as part of settings?

Thanks so much in advance! Really appreciate it.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.20230531.3a70dd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
Please give the full error and the configuration you tried to use.

**Comment by ncfavier** [comment]
> A definition for option `home-manager.users.user.dconf.settings."org/gnome/shell"."org/gnome/desktop/peripherals/mouse"'

You forgot a closing `}`.
