### ISSUE TITLE
bug: workspaceOutputAssign doesn't quote the output name

### ISSUE THREAD

**Issue by lukaswrz** [nix-community/home-manager#4058]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Sway supports specifying outputs by make, model and serial, e.g.: `LG Electronics LG HDR 4K 0x00008FEE`.

The problem arises when using `workspaceOutputAssign`, which doesn't quote the output name:

```nix
workspaceOutputAssign = [
  {
    output = "LG Electronics LG HDR 4K 0x00008FEE";
    workspace = "1";
  }
];
```

```
workspace "1" output LG Electronics LG HDR 4K 0x00008FEE
```

The above will just be ignored by Sway. It would work if the output name was quoted, e.g.:

```
workspace "1" output "LG Electronics LG HDR 4K 0x00008FEE"
```

In contrast, using `output` works perfectly, i.e., it quotes the output name correctly:

```nix
output."LG Electronics LG HDR 4K 0x00008FEE" = {
  mode = "3840x2160@144.004Hz";
};
```

```
output "LG Electronics LG HDR 4K 0x00008FEE" {
mode 3840x2160@59.997Hz
}
```

### Maintainer CC

@sebtm

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.11 (Tapir), 23.11.20230603.dd49825`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/my1b33f1dm7srg8ngcmk769ahkslgkaz-source`
```

**Comment by ncfavier** [comment]
Could you test https://github.com/nix-community/home-manager/pull/4059 please?

**Comment by lukaswrz** [comment]
Yes, that works. Thanks!
