### ISSUE TITLE
bug: fcitx-engines is deprecated, please use fcitx5 instead.

### ISSUE THREAD

**Issue by alethenorio** [nix-community/home-manager#4072]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have upgrade my NixOS to 23.05 followed by home-manager to 23.05 but whenever I run `home-manager switch` I run into the error

```
error: fcitx-engines is deprecated, please use fcitx5 instead.
(use '--show-trace' to show detailed location information)
```

Using the `--show-trace` does not show anything that seem more useful.

The upgrade was done the following way

1. `sudo nix-channel --add https://channels.nixos.org/nixos-23.05 nixos`
2. `sudo nixos-rebuild boot --upgrade`
3. Reboot machine and log back into my user
4. `sudo nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz home-manager`
5. `nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz home-manager`
6. `home-manager switch`

This is what the system looks like at the moment

```bash
$ sudo nix-channel --list
home-manager https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz
nixos https://channels.nixos.org/nixos-23.05
nixos-unstable https://nixos.org/channels/nixos-unstable
unstable https://nixos.org/channels/nixpkgs-unstable

$ nix-channel --list
home-manager https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz
home-manager-unstable https://github.com/nix-community/home-manager/archive/master.tar.gz
```

I am a little uncertain what issue is because after a lot of googling and trying a few things out, I am uncertain what package is using the `fcitx-engines` package. Is there a way to trace back which package is using that?

I have found a similar issue discussed at https://discourse.nixos.org/t/error-when-upgrading-nixos-related-to-fcitx-engines/26940 however there seems to be no real solution there except bypassing the issue by moving home-manager to master. From that discussion I can confirm that the following overlay bypasses the issue and allows me to run `home-manager switch` however it is a workaround which is why I decided to post this issue

```nix
(self: super: {
      fcitx-engines = pkgs.fcitx5;
})
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.05 (Stoat), 23.05.589.a558f7ac29f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixos-unstable, unstable"`
 - channels(alethenorio): `"home-manager-22.11.tar.gz, home-manager-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
> ```
>  - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixos-unstable, unstable"`
>  - channels(alethenorio): `"home-manager-22.11.tar.gz, home-manager-unstable"`
> ```

Looks like there's some confusion with the channels there. This error indicates that you're still using Home Manager 22.11.

**Comment by alethenorio** [comment]
@ncfavier I am uncertain why this is but I am guessing it has to do with this config option in my home-manager configuration

```nix
  # This value determines the Home Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Home Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  home.stateVersion = "22.11";
```

As the comment say, I did not update that value however as I wrote in the ticket, the channel `home-manager` is definitely set to `https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz`

**Comment by ncfavier** [comment]
No, `stateVersion` has nothing to do with it.

`nix-info` thinks your `home-manager` channel is 22.11.

Did you forget to run `nix-channel --update`?

**Comment by alethenorio** [comment]
Oh. I could have sworn I did however it looks I did not. It seems to work now.

Thank you for taking the time to reply to the ticket and I think I have learned better how to debug such issues in the future :blush: 

I'm closing the ticket for now
