### ISSUE TITLE
specializations: option name consistency with NixOS

### ISSUE THREAD

**Issue by montchr** [nix-community/home-manager#4074]
### Description

- home-manager's specialisation option is `specialization` (`z`)
- NixOS's specialization option is `specialisation` (`s`)

Personally, I don't care about `ise`/`ize` in itself, but perhaps since home-manager specializations are experimental it may be worth changing the option name to match that of NixOS. This would provide a more seamless experience for users (one less tiny discrepancy to remember).

**Comment by rycee** [comment]
Fair point, didn't even notice and used the US spelling as that's what I am accustomed to. Should be fixed now.
