### ISSUE TITLE
bug: Unable to switch configurations due to attribute  'qt6Packages qt6ct'

### ISSUE THREAD

**Issue by tiredofit** [nix-community/home-manager#4097]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Since today I am unable to perform home-manager switch as I am presented with the error of:

`error: Invalid package attribute path 'qt6Packages qt6ct'`

### Setup
nixpkgs = 23.05

home-manager = 23.05

mode = standalone (flake) on nixOS

### Steps tried

- Setting up home-manager from new with the following:

```
# ~/.config/home-manager/flake.nix

{
  description = "Tired of I.T! Home Manager configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-23.05";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, home-manager, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      homeConfigurations.dave = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;

        modules = [
          ./home.nix
        ];
      };
    };
}
```

```
# ~/.config/home-manager/home.nix

{ config, pkgs, ... }:

{
  imports = [
  ];


  home = {
    username = "dave";
    homeDirectory = "/home/dave";
    stateVersion = "23.05";
  };

  programs = {
    home-manager.enable = true;
  };
}
```

Similar to #664 

````
sh-5.2$ nix flake update ~/.config/home-manager --extra-experimental-features "nix-command flakes"
warning: Git tree '/home/dave/.config/home-manager' is dirty
sh-5.2$ home-manager switch --flake ~/.config/home-manager/#${USER} -v --extra-experimental-features "nix-command flakes"
warning: Git tree '/home/dave/.config/home-manager' is dirty
error: Invalid package attribute path 'qt6Packages qt6ct'
(use '--show-trace' to show detailed location information)
````

### Maintainer CC

@thiagokokada - I see you have done some with with qt6 in the past 12 hours d214b93ee3c82b2746b85e8cb96bc150c6a74e50

### System information

```markdown
`
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.7, NixOS, 23.05 (Stoat), 23.05.20230614.ddf4688`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(dave): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
````
```

**Comment by ncfavier** [comment]
Read the issue template please.

> You should follow the branch of Home Manager that corresponds to your
version of Nixpkgs; see [the README](https://github.com/nix-community/home-manager#releases) for details.

**Comment by tiredofit** [comment]
Oh gosh. I see where I went wrong. I will go hang my head in shame - apologies.

**Comment by borgmanJeremy** [comment]
@tiredofit  Could you elaborate? I am sure the fix was obvious but I seem to have made the same mistake :)

**Comment by tiredofit** [comment]
I had incorrectly assumed that since I have nixpkgs set to `23.05` that my home manager without the explicit declaration of the `release-23.05` would follow `nixpkgs`.

Here's how it looks now:

```
    nixpkgs.url = "github:nixos/nixpkgs/nixos-23.05";

    home-manager = {
      url = "github:nix-community/home-manager/release-23.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

Smooth sailing since then.

**Comment by borgmanJeremy** [comment]
Thank you :) I had made the same assumption. All building here as well now.

**Comment by andrewcrook** [comment]
Thanks @tiredofit  saved me some time
