### ISSUE TITLE
programs.firefox.package should accept a null package

### ISSUE THREAD

**Issue by rafaelsgirao** [nix-community/home-manager#4112]
HM's sway's `wayland.windowManager.sway.package` option states:
> Sway package to use. (...) Set to null to not add any Sway package to your path. This should be done if you want to use the NixOS Sway module to install Sway.

I think the `programs.firefox.package` should follow the same behaviour of allowing a null package. This would allow using HM options such as setting search engines declaratively (which isn't an option in nixpkgs and wouldn't make sense to be), while still allowing firefox package to come from NixOS options, which allows e.g setting Firefox Policies.

**Comment by 1sixth** [comment]
You can set Firefox Policies with override:

```nix
{ pkgs, ... }:

{
  programs.firefox = {
    enable = true;
    package = pkgs.firefox-esr.override {
      extraPolicies = {
        # https://mozilla.github.io/policy-templates/
        SearchEngines = {
          Add = [{
            Name = "GitHub";
            URLTemplate = "https://github.com/search?q={searchTerms}&type=repositories";
          }];
        };
      };
    };
  };
}

```
