### ISSUE TITLE
bug: error: function 'anonymous lambda' called with unexpected argument 'withManOptDedupPatch'

### ISSUE THREAD

**Issue by happysalada** [nix-community/home-manager#4120]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

on latest nixpkgs master, the withManOptDedupPatch has been removed (ref PR https://github.com/NixOS/nixpkgs/pull/237557)
one of home-manager's dependency (nmd) still has this option
https://git.sr.ht/~rycee/nmd/tree/master/item/lib/manual-docbook.nix#L37
https://github.com/nix-community/home-manager/blob/6bdd72b914fc3472be807bc9b427650b49808a94/docs/default.nix#L10

when you have a moment, the option should be removed.

(should the nmd dependency be inside the flake ? Not my place to say so, just thought I would suggest it).

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.11 (Tapir), 23.11.20230617.204cadf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by happysalada** [comment]
the change was in the end reverted in nixpkgs to enable home-manager to make the switch https://github.com/NixOS/nixpkgs/pull/238629
Happy to close this issue if you would prefer.

**Comment by ncfavier** [comment]
> (should the nmd dependency be inside the flake ? Not my place to say so, just thought I would suggest it).

This is discussed at https://github.com/nix-community/home-manager/pull/3056

I think we can close this now; the real issue is still that documentation generation for the NixOS module system should be distributed with the NixOS module system and not be reimplemented in nmd.

**Comment by rycee** [comment]
Since https://github.com/nix-community/home-manager/commit/172d46d4b2677b32277d903bdf4cff77c2cc6477, the documentation should no longer depend on this patch 🙂
