### ISSUE TITLE
See list of new packages

### ISSUE THREAD

**Issue by archaeron** [nix-community/home-manager#4121]
I couldn't find how to do this. Sorry if it's already possible but I didn't see how.

### Description

Would it be possible to see the packages that were changed and to what version they were updated while using `home-manager switch/build`?

**Comment by teto** [comment]
I had this for a while which is fun 
```
  # system.activationScripts.report-nixos-changes = ''
  #   PATH=$PATH:${lib.makeBinPath [ pkgs.nvd pkgs.nix ]}
  #   nvd diff $(ls -dv /nix/var/nix/profiles/system-*-link | tail -2)
  # '';

#   system.activationScripts.report-home-manager-changes = ''
#     PATH=$PATH:${lib.makeBinPath [ pkgs.nvd pkgs.nix ]}
#     nvd diff $(ls -dv /nix/var/nix/profiles/per-user/teto/home-manager-*-link | tail -2)
#   '';
```

**Comment by diego898** [comment]
Im using nix on ubuntu. The best I came up with after installing `nvd` is:

`home-manager generations | head -2 | awk '{print $NF}' | tac | xargs -n 2 nvd diff` 

But I have to do this manually after the switch

**Comment by archaeron** [comment]
this is awesome, thank you!!

**Comment by ilyagr** [comment]
I think it should be doable to diff the output of `home-manager packages` before and after automatically. It's certainly doable manually (though not necessarily fun), especially after #4789. This shows less information than `nvd`, though.
