### ISSUE TITLE
Skip default values when generating configuration for `programs.ssh`

### ISSUE THREAD

**Issue by x80486** [nix-community/home-manager#4132]
## Description

I started using `NixOS` recently. While (still) configuring `Home Manager` I've noticed that sometimes some programs generate configuration with default values and some others not.

This issue is to considering to _tone down_ the generated configuration values for `programs.ssh`. The relevant configuration (`/home/x80486/.config/home-manager/home.nix`) is:

```haskell
{ config, pkgs, ... }:

{
  ...
  programs.ssh = {
    compression = true;
    enable = true;
    matchBlocks = {
      "gitlab.com" = {
        hostname = "gitlab.com";
        identityFile = "~/.ssh/gitlab-personal";
      };
      "github.com" = {
        hostname = "github.com";
        identityFile = "~/.ssh/github-personal";
      };
    };
  };
  ...
}
```

There is nothing wrong with this. It correctly generates the `/home/x80486/.ssh/config` file:

```ssh
Host github.com
  HostName github.com
  IdentityFile ~/.ssh/github-personal
Host gitlab.com
  HostName gitlab.com
  IdentityFile ~/.ssh/gitlab-personal

Host *
  ForwardAgent no
  Compression yes
  ServerAliveInterval 0
  ServerAliveCountMax 3
  HashKnownHosts no
  UserKnownHostsFile ~/.ssh/known_hosts
  ControlMaster no
  ControlPath ~/.ssh/master-%r@%n:%p
  ControlPersist no
```

But I was expecting only `Compression yes` for `Host *` and not any other of the default values — because they are set like that regardless.

The main reasoning for this is (1) because these values might change between versions, (2) there are some other missing default values, and (3) some other programs/tools do not really specify them because they can be extensive.

Thank you for maintaining `Home Manager` — it's really great! :wave:

**Comment by ncfavier** [comment]
That would be much appreciated, going in the direction of https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md#part-2-1.

See also https://github.com/nix-community/home-manager/pull/3935#issuecomment-1530128671
