### ISSUE TITLE
Add Cleaner option to LF configuration

### ISSUE THREAD

**Issue by colin-heffernan** [nix-community/home-manager#4139]
### Description

LF has an optional script called `cleaner` that exists as a compliment to the previewer for images. Could there be an option such as `programs.lf.cleaner.source` to configure it?

**Comment by colin-heffernan** [comment]
I plan on switching to XPLR, so I am closing this. It was never implemented.

**Comment by colin-heffernan** [comment]
Since it never happened, changing to closed unplanned.

**Comment by ismay-tue** [comment]
Would be nice to have though. Bit inconsistent that the previewer is implemented, but the cleaner isn't. Can't really have one without the other.
