### ISSUE TITLE
Generate `.gitconfig` file

### ISSUE THREAD

**Issue by x80486** [nix-community/home-manager#4145]
### Description

I'm using `programs.git` to generate the `Git` configuration. Problem is that the generated `${HOME}/.config/git/config` is a link to the `Nix` store, and while that works for the most part, `Flatpak` applications are unable to access those files.

So I wonder if there is a way to generate a `.gitconfig` in the home directory as well, or something around those lines?

**Comment by rycee** [comment]
Unfortunately no, there is no way to make it a real file. You will have to create it manually. Something like

```
home.activation.createGitignore = lib.hm.dag.entryAfter ["writeBoundary"] ''
  cp -f ${./path//to/gitignore} $HOME/.config/git/ignore
'';
```

perhaps.
