### ISSUE TITLE
bug: wezterm is being compiled from source and the build fails

### ISSUE THREAD

**Issue by augustebaum** [nix-community/home-manager#4150]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Disclaimer: Noob here, I don't know if my nixpkgs and HM versions are the same, and the README doesn't seem to clearly explain how to figure that out. Please do let me know how to do that!

---

Hi all,

I've set up home-manager through nix-darwin on my MacOS machine and everything has been working fine. However, I recently restarted my machine and since then, `switch`ing fails because Wezterm is being built from source, and the build fails. This was not an issue until now and I'm at a loss. Has this happened to anyone before? Would appreciate any help in understanding what is going on.

My stripped-down `home.nix` (let me know if you think including other sections might be relevant):

```nix
{ config, pkgs, lib, ... }:

{
  home.stateVersion = "23.05";
  
  # ...

  programs = {
    home-manager = { enable = true; };
    wezterm = {
      enable = false;
      package = pkgs.wezterm;
      extraConfig = builtins.readFile ./config/wezterm/wezterm.lua;
    };
  };
  # ...
}
```

I also have the nix logs recorded when running `darwin-rebuild switch`, let me know if you think they'd be useful.

Thanks in advance for your help!

### System information

```markdown
- system: `"x86_64-darwin"`
- host os: `Darwin 21.6.0, macOS 10.16`
- multi-user?: `yes`
- sandbox: `no`
- version: `nix-env (Nix) 2.13.3`
- channels(auguste): `"darwin, home-manager"`
- nixpkgs: `/nix/store/q336zlh9g3f5k0vabn6xzwhxasnhk7hv-source`
```

**Comment by ncfavier** [comment]
This is almost definitely a nixpkgs issue since we don't modify the wezterm package. The build logs would definitely be helpful.

> Disclaimer: Noob here, I don't know if my nixpkgs and HM versions are the same, and the README doesn't seem to clearly explain how to figure that out. Please do let me know how to do that!

As explained [here](https://github.com/nix-community/home-manager#releases), the branches need to match up (either both the same release or both unstable). So, for example, if you're following `nixos-unstable`, you need home-manager `master`. But this shouldn't be a synchronisation problem anyway.

**Comment by ncfavier** [comment]
Well, it looks like wezterm has been failing to build on x86_64-darwin on Hydra for 5 days: https://hydra.nixos.org/job/nixpkgs/trunk/wezterm.x86_64-darwin/all

You should open an issue at nixpkgs with that URL and ping the maintainers.

**Comment by augustebaum** [comment]
Thanks for the quick response! Will open an issue as advised.

> if you're following `nixos-unstable`, you need home-manager `master`

I don't seem to have specified anywhere in my config to use `unstable` or `master` anything of that sort. How would I go about figuring out what I'm using?

Leaving the logs [here](https://github.com/nix-community/home-manager/files/11849363/bug-log.txt) just in case.

**Comment by ncfavier** [comment]
If you use flakes, that's in your `flake.nix`. If you use channels, you must have specified what version of the channel to use in the URL.

**Comment by augustebaum** [comment]
Got it, thanks! For future reference, I used `nix-channel --list` and got:
```md
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
```
