### ISSUE TITLE
bug: antidote does not load plugins automatically

### ISSUE THREAD

**Issue by seh** [nix-community/home-manager#4164]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

In my _home-manager_ configuration, with the _zsh_ plugin manager [_antidote_ enabled](https://nix-community.github.io/home-manager/options.html#opt-programs.zsh.antidote.enable), I use [the `programs.zsh.antidote.plugins` option](https://nix-community.github.io/home-manager/options.html#opt-programs.zsh.antidote.plugins) to have _antidote_ load a few plugins from my _~/.zshrc_ file.

This produces the following fragment in my _~/.zshrc_ file:
```shell
## home-manager/antidote begin :
source /nix/store/mp4vd43zggyh20i7ykhsw3hywlckk178-antidote-1.8.8/share/antidote/antidote.zsh
zstyle ':antidote:bundle' use-friendly-names 'yes'
bundlefile=.zsh_plugins.txt
zstyle ':antidote:bundle' file $bundlefile
staticfile=.zsh_plugins.zsh
zstyle ':antidote:static' file $staticfile
antidote load $bundlefile $staticfile
## home-manager/antidote end
```
Note that the extant #4151 changes this output slightly.

Per [my recent comment](https://github.com/nix-community/home-manager/pull/4027/files#r1241260461) in #4027, the so-called "staticfile" does not exist yet.

The call to _antidote load_ seems to have no effect. _zsh_ starts without complaint, but _antidote_ doesn't seem to have loaded the plugins.

If I then source the referenced _antidote.zsh_ file manually, and then invoke _antidote load .zsh_plugins.txt_, it _does_ load the plugins and do things like change my prompt.

I thought that the call to _antidote load_ might be failing because the second referenced file—_.zsh_plugins.zsh_—does not exist yet, but I tried that interactively, and _antidote load_ still worked as intended even if I supplied it with a second argument nominating a nonexistent file.

Perhaps better fit for a second issue here, we should [create a _~/.zsh_plugins.zsh_ file automatically](https://github.com/mattmc3/antidote#performance) to reduce the time it takes to start new shell sessions.

### Maintainer CC

@hitsmaxft

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 22.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/qb3dg4cx5jzk3pa8szzi0ziwnqy33p50-source`
```

**Comment by hitsmaxft** [comment]
there is a bug in the master  
```
bundlefile=.zsh_plugins.txt
```
should be 
```
bundlefile=$HOME/.zsh_plugins.txt
```

  i've summited bugfix in PR ,   @rycnee 
https://github.com/nix-community/home-manager/pull/4151

**Comment by seh** [comment]
Yes, and I had mentioned that pending fix, but how is it relevant here? _antidote_ is already operating in the proper directory. Are you expecting that the _.zsh_plugins.zsh_ file will be created automatically as a result of your patch?

**Comment by hitsmaxft** [comment]
> Yes, and I had mentioned that pending fix, but how is it relevant here? _antidote_ is already operating in the proper directory. Are you expecting that the _.zsh_plugins.zsh_ file will be created automatically as a result of your patch?

`antidote load $bundlefile [$staticfile]`  will auto update `$staticfile` if bundlefile is newer than static (mod_time)
but since nix store file never update mod_time , so this will never happend, will leads to `.zsh` never update

my patch is use stat check symbolic link and update static file , every update home-manager switch may trigger update

**Comment by seh** [comment]
Oh, I didn’t know that _antidote_ would do that! Is that a new feature? When I wrote my configuration, the documentation advised to handle those updates manually.

**Comment by hitsmaxft** [comment]
> Oh, I didn’t know that _antidote_ would do that! Is that a new feature? When I wrote my configuration, the documentation advised to handle those updates manually.

 just look  functions/antidote-load in source code . 

i wonder that may  antidote don't need hm-module to  generate zsh_plugin.txt  ,    just doing this   fun.

**Comment by seh** [comment]
With #4172 merged, this problem no longer occurs for me.
