### ISSUE TITLE
Setting within `Home Manager` to install "unfree" packages?

### ISSUE THREAD

**Issue by x80486** [nix-community/home-manager#4166]
## Description

I'm fairly new to `Home Manager`. I usually end up using [MyNixOS](https://mynixos.com/home-manager/options) and `GitHub` to figure it out what options are available for a given key or set of keys.

Problem I'm facing is that I'm trying to install a non-free package ([`smartgithg`](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/version-management/smartgithg/default.nix)) and I'm getting the usual: `error: Package ‘smartgithg-22.1.5’ in /nix/store/j7zkyiddrzr0452bpbshwc1vfyszpr4h-nixos-23.05/nixos/pkgs/applications/version-management/smartgithg/default.nix:88 has an unfree license (‘unfree’), refusing to evaluate.`

I do have `nixpkgs.config.allowUnfree = true;` in `/etc/nixos/configuration.nix`, so I thought that would take precedence system-wide, but looks like `Home Manager` is not honoring (or it's not aware of) the setting.

Applying any of the suggested methods seems not to be the solution (but a setting within `Home Manager`, or for `Home Manager` to recognize the global setting in `/etc/nixos/configuration.nix`):

```shell
[x80486@uplink:~]$ home-manager switch 
error: Package ‘smartgithg-22.1.5’ in /nix/store/j7zkyiddrzr0452bpbshwc1vfyszpr4h-nixos-23.05/nixos/pkgs/applications/version-management/smartgithg/default.nix:88 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "smartgithg"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

What's the resolution path in this case?

**Comment by ncfavier** [comment]
If you're using Home Manager in a standalone way, you can set `nixpkgs.config.allowUnfree` in your Home Manager configuration.

**Comment by x80486** [comment]
Would it be possible to use, if present, the `nixpkgs.config.allowUnfree` value from `/etc/nixos/configuration.nix`?

I meant in general terms, if it's something that should be implemented — I'm not sure if it's possible nowadays.

**Comment by ncfavier** [comment]
Yes, you can use HM as a NixOS module and turn on `home-manager.useGlobalPkgs` as explained [here](https://nix-community.github.io/home-manager/index.html#sec-install-nixos-module).

**Comment by x80486** [comment]
Thanks for the pointer, @ncfavier.

I guess I was more on the side that, if `nixpkgs.config.allowUnfree` is already set within `/etc/nixos/configuration.nix`, wouldn't it be possible for Home Manager to recognize that this is already set globally and behave accordingly?

Of course, that puts Home Manager into an "interesting" state because if the setting is removed from `/etc/nixos/configuration.nix` later, some packages were already installed, and probably Home Manager wouldn't be able to update them :grimacing:

**Comment by ncfavier** [comment]
Perhaps you're looking for `~/.config/nixpkgs/config.nix`.
