### ISSUE TITLE
`programs.librewolf`: allow installing extensions like `programs.firefox`

### ISSUE THREAD

**Issue by mrjones2014** [nix-community/home-manager#4179]
### Description

Feel free to close if you feel this is a duplicate of #2803, but I think it's slightly different as far as I understand?

Firefox has `programs.firefox.profiles.myprofile.extensions = [ foo bar ];`.

I'd like to be able to do the same for Librewolf like: `programs.librewolf.profiles.myprofile.extensions = [ foo bar ];`

**Comment by mrjones2014** [comment]
tagging module maintainer @onny

**Comment by KamWithK** [comment]
Is there currently any way to do this? Nix doesn't throw an error the extensions just don't show up when added into profiles.default.extensions (default as an example profile)

**Comment by steveej** [comment]
https://github.com/nix-community/home-manager/pull/3339 had some activity last month. maybe enough to mark this as not stale.

**Comment by steveej** [comment]
> #3339 had some activity last month. maybe enough to mark this as not stale.

same with activity as recent as yesterday.

**Comment by danielpza** [comment]
It seems this got closed by mistake when #5128 was merged, but the actual settings to the librewolf module will be added in https://github.com/nix-community/home-manager/pull/5684.

**Comment by brckd** [comment]
Sorry, my bad. That happened when i changed the objective of the prior PR.
