### ISSUE TITLE
bug: using programs.topgrade.settings makes topgrade crash

### ISSUE THREAD

**Issue by keenanweaver** [nix-community/home-manager#4182]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

With the latest version of topgrade, the `programs.topgrade.settings` option no longer works. Here's the release: https://github.com/topgrade-rs/topgrade/releases/tag/v12.0.0

The error received is:

```
The application panicked (crashed).
Message:  Tried to auto-migrate the config file, unable to write to config file.
Please add "[misc]" section manually to the first line of the file.
Error: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
Location: src/config.rs:710

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### Maintainer CC

@msfjarvis

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.4.0, NixOS, 23.11 (Tapir), 23.11.20230628.60a783e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by msfjarvis** [comment]
Yeah I haven't bothered with the forked topgrade yet and still use the archived version, I'll try to find time this weekend to update the module for `topgrade-rs/topgrade`.

**Comment by msfjarvis** [comment]
So I looked into this and it seems like the `topgrade` folks just decided to fuck up their config format for no apparent reason?

They demand everything be wrapped in a `misc` header, so it can be fixed either by consumers of the topgrade module moving all values in `programs.topgrade.settings` to `programs.topgrade.settings.misc` like [this](https://github.com/msfjarvis/dotfiles/commit/282199eeb77c0e8a007a45c13ebbfc52f5189f21), or the home-manager module can do it automatically like [this](https://github.com/msfjarvis/home-manager/commit/ae8078b78f64ce1b326874169ba13d09ccd14491). I don't know which one makes the most sense, but they're both options.

**Comment by msfjarvis** [comment]
Did some more research, the home-manager change is not gonna work since there are still [settings keys outside the `misc` heading](https://github.com/topgrade-rs/topgrade/blob/b974938a33ea9c214d06bfb4941c1daa79f9f3dc/config.example.toml).

The config adjustment will have to be done by the users of this module on their own end, it is not a home-manager bug.

**Comment by keenanweaver** [comment]
> The config adjustment will have to be done by the users of this module on their own end, it is not a home-manager bug.

Sure enough, this resolved it. Thanks for looking into it!! As an example for anyone else who's looking for a fix, you basically need to populate a key in the misc section.

``` nix
    topgrade = {
      enable = true;
      settings = {
        misc = {
          "display_time" = true;
        };
        distrobox = {
          containers = [ "archlinux-latest" ];
        };
      };
    };
```
