### ISSUE TITLE
bug: flameshot doesn't work on sway

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#4187]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

flameshot service starts but clicking "take screenshot" does nothin.

I realized I was missing out some variables here:
https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

and also I added grim to flameshot service:
```
diff --git a/modules/services/flameshot.nix b/modules/services/flameshot.nix
index 2de0d547..67d39d67 100644
--- a/modules/services/flameshot.nix
+++ b/modules/services/flameshot.nix
@@ -64,7 +64,7 @@ in {
       Install = { WantedBy = [ "graphical-session.target" ]; };
 
       Service = {
-        Environment = "PATH=${config.home.profileDirectory}/bin";
+        Environment = "PATH=${config.home.profileDirectory}/bin:${pkgs.grim}/bin";
         ExecStart = "${cfg.package}/bin/flameshot";
         Restart = "on-abort";
```

I am not sure if the variables are really needed but everything combined that fixed flameshot on sway for me. The flameshot service should detect when we are using wayland and adapt itself when that's the case.

### Maintainer CC

@hamhut1066 

### System information

```markdown
everything unstable
```

**Comment by teto** [comment]
after a reboot, I can confirm that I needed the kde portal on top it. I had to comment out the gnome portals which were breaking ` systemctl --user status xdg-desktop-portal`
```
  xdg.portal = {
    wlr.enable = true;
    lxqt.enable = true;
    # xdg-desktop-portal-gnome
    extraPortals = [
        # pkgs.xdg-desktop-portal-gnome # necessary for flameshot
        pkgs.xdg-desktop-portal-kde
        # (pkgs.xdg-desktop-portal-gtk.override {
        #   # Do not build portals that we already have.
        #   buildPortalsInGnome = false;
        # })
      ];
  };
```

**Comment by KFearsoff** [comment]
It seems like Flameshot now provides a `grim` backend to screenshotting, which seems to work a lot better on wlroots-based compositors than the KDE way that the OP described. I don't think there's anything on the Home Manager side that can be improved, besides adding `grim` to `home.packages` for better experience. Tracking issue on the Nixpkgs side: https://github.com/NixOS/nixpkgs/issues/292700
