### ISSUE TITLE
bug: nixos won't gc the home-manager generations

### ISSUE THREAD

**Issue by tywtyw2002** [nix-community/home-manager#4204]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The home-manager in my environment the generation won't expire and keep the same time as the nixos-rebuild time.

I use the flake to manager the system, and the home-manager as a module of nixosConfigurations. Only use the `nixos-rebuild switch --flake .#XXXXXXX` to switch the both system and home-manager.

Use command `home-manager remove-generations X` to remove the each old generations, the nix gc works.

When I query the home-manager generations the results is here.
```
$  home-manager generations
2023-07-05 17:06 : id 5 -> /nix/store/gjki8g7skhnswqry98igbq753djdydl5-home-manager-generation
2023-07-05 17:06 : id 4 -> /nix/store/c0s5fk38fbdk45k656xi5nscr0dyy38p-home-manager-generation
2023-07-05 17:06 : id 3 -> /nix/store/5kiybxs6x569vzcng1mxqhcf15fjs0x5-home-manager-generation
```

```
$ home-manager --version 
23.05-pre
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.11 (Tapir), 23.11.20230704.78419ed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/2p1jsxsxv0d0gkybanb5acbpi7sr6rjw-source`
```

**Comment by ivankovnatsky** [comment]
I think that's a duplicate of https://github.com/nix-community/home-manager/issues/3450.
