### ISSUE TITLE
bug: xsession.windowManager.i3.config.floating.modifier overly restrictive

### ISSUE THREAD

**Issue by VincentVanlaer** [nix-community/home-manager#4216]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

`xsession.windowManager.i3.config.floating.modifier` is limited to single modifier keys. However, i3 allows combinations of modifier keys. For example `Mod1+Control'. 

### Maintainer CC

@sumnerevans @sebtm

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.20230601.f0ba823`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - channels(vincenttc): `""`
 - nixpkgs: `/nix/store/ipbqg8zvymxjlw96pl2mvgpigzc3wm7p-source`
```

**Comment by ncfavier** [comment]
https://github.com/nix-community/home-manager/pull/4229
