### ISSUE TITLE
Zellij doesn't depend on "wl-clipboard", so copy/paste doesn't work on Konsole Wayland

### ISSUE THREAD

**Issue by CarlMitchellKT** [nix-community/home-manager#4218]
### Description

Zellij's default clipboard behavior does not function on Konsole under Wayland. It can be made to function by setting the option `programs.zellij.settings.copy_command = "wl-copy";`, but that depends on having `wl-clipboard` installed. It'd be more pure if there were an actual module option for this which would include the dependency and select the config.

**Comment by Rosuavio** [comment]
I have no option on changing the home-manager module for zellij, but you should be able to do
`programs.zellij.settings.copy_command = "${pkgs.wl-clipboard}/bin/wl_copy"` in your own config. Would that not achieve the purity you are looking for?

**Comment by CarlMitchellKT** [comment]
Yes, that'd work.
