### ISSUE TITLE
bug: imapnotify service fails

### ISSUE THREAD

**Issue by minikN** [nix-community/home-manager#4222]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hello,

I'm currently having trouble getting the imapnotify service to work with home-manager. The relevant configuration can be found [here](https://github.com/minikN/nix/blob/0e30719924b04cdd9444adb7ef693412c0912401/modules/mail/mailbox.nix#L83-L92) and [here](https://github.com/minikN/nix/blob/0e30719924b04cdd9444adb7ef693412c0912401/modules/mail/default.nix#L38-L47).

```
db > cat ~/.config/systemd/user/imapnotify-primary.service
[Install]
WantedBy=default.target

[Service]
Environment=NOTMUCH_CONFIG=/home/db/.config/notmuch/default/config
ExecStart=/nix/store/d40h2bvn1310s1hjwzsnzkiwxivg89pk-goimapnotify-2.3.7/bin/goimapnotify -conf /nix/store/r0aqq5k69bxrch32dqhrfskf7n1frkyl-imapnotify-primary-config.json
Restart=always
RestartSec=30
Type=simple

[Unit]
Description=imapnotify for primary
```

```
db > cat /nix/store/r0aqq5k69bxrch32dqhrfskf7n1frkyl-imapnotify-primary-config.json
{"boxes":["Inbox"],"host":"imap.mailbox.org","onNewMail":"/nix/store/76z76nads9sl506bq7bdw173m1j2r7f2-libnotify-0.8.2/bin/notify-send -t 5000 \"New mail\" \"You received new private mail.\"","passwordCmd":"'/nix/store/l3rzmr79vdhbyx28pnxzqsppbks4hq21-getPassword'","port":993,"tls":true,"username":"db@minikn.xyz","wait":1}%                                                                                                                                               
```

Now when I start up my laptop, shortly after logging in, pinentry-qt pops up, so retrieving the password seems to work fine, but I never get a notification when I receive a mail.

systemd reports:
```
db > systemctl --user status imapnotify-primary.service                                                                                                  
● imapnotify-primary.service - imapnotify for primary
     Loaded: loaded (/home/db/.config/systemd/user/imapnotify-primary.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2023-07-11 08:52:13 CEST; 29s ago
    Process: 7458 ExecStart=/nix/store/d40h2bvn1310s1hjwzsnzkiwxivg89pk-goimapnotify-2.3.7/bin/goimapnotify -conf /nix/store/r0aqq5k69bxrch32dqhrfskf7n1frkyl->
   Main PID: 7458 (code=exited, status=1/FAILURE)
        CPU: 14ms
```

```
db > journalctl -u imapnotify-primary.service                                                                                                            [130]
-- No entries --
```

What I don't understand is this, if I run the `ExecStart` command manually in the console, everything seems to work fine:

![image](https://github.com/nix-community/home-manager/assets/1888338/03c0cce6-7016-4966-bb9a-9d3163dcb5d8)

I'm new to nixos so maybe I'm doing something wrong, I'd appreciate any help. Thanks in advance!

### Maintainer CC

@NickHu 

### System information

```markdown
db > nix-shell -p nix-info --run "nix-info -m"                                                                                                           [130]
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/k57fgpvjv1z5lk7w5p5lhp9ikvj04i0i-nix-info
copying path '/nix/store/k57fgpvjv1z5lk7w5p5lhp9ikvj04i0i-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.9, NixOS, 23.11 (Tapir), 23.11.20230625.1c9db97`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `""`
 - channels(db): `"nixos"`
 - nixpkgs: `/home/db/.nix-defexpr/channels/nixpkgs`
```
```

**Comment by ncfavier** [comment]
@dbaynard this is likely related to your recent changes

**Comment by ncfavier** [comment]
@minikN just to check, does the issue persist if you use `github:nix-community/home-manager/b23c7501f7e0a001486c9a5555a6c53ac7b08e85` in your `flake.nix`?

**Comment by minikN** [comment]
> @minikN just to check, does the issue persist if you use `github:nix-community/home-manager/b23c7501f7e0a001486c9a5555a6c53ac7b08e85` in your `flake.nix`?

Hey @ncfavier 
No, with this commit checked out the behaviour doesn't change. Also the output from the commands I posted above doesn't change.

**Comment by dbaynard** [comment]
Did you have a working system until you upgraded, or is this not working since you upgraded?

I looked through the changes and for the only thing that jumped out (changing how the executable is identified), you've already shown that isn't the problem. I also checked and the nixpkgs version of goimapnotify hasn't changed recently.

> shortly after logging in, pinentry-qt pops up, so retrieving the password seems to work fine, but I never get a notification when I receive a mail.

If you disable the service and don't unlock the password, does everything work when you _manually_ run the `ExecStart`?

Finally, I have noticed some goimapnotify flakiness on macos but not on Linux. I found it hard to pin down, though it appears to have stopped occurring. I wonder whether it is a race condition involving the password — one of my systems has a pin-entry like password input and showed flakiness when goimapnotify was requesting a keychain unlock, and I think the flakiness has gone because it's now isync doing it. (This is a happy accident — I haven't confirmed this is what is happening.) This has annoyed me for months, and it's only thanks to your issue that I've considered this possibility.

I don't know how `pass` compares with `security` on macos, but I wonder whether the following leads to a working configuration.

1.  Disable the service
2.  Restart (or logout, etc)
3.  Unlock pass manually, or by manually calling mbsync
4.  Re-enable the service.

I don't see why this would be different to just running `ExecStart`, though.

**Comment by minikN** [comment]
@dbaynard I'm not sure what you mean by _enabling/disabling_ the service, if you mean running `systemctl --user enable/disable imapnotify-primary.service` then this doesn't work:

```
db > systemctl --user disable imapnotify-primary.service                                                                                                  
Removed "/home/db/.config/systemd/user/default.target.wants/imapnotify-primary.service".
Removed "/home/db/.config/systemd/user/imapnotify-primary.service".
db > systemctl --user enable imapnotify-primary.service
Failed to enable unit: Unit file imapnotify-primary.service does not exist.
```

What I tried instead is, disabling the service through the nix config by changing `enable` to `false` here:
```
        imapnotify = {
          enable = true;
          boxes = [ "Inbox" ];
          #onNotify = "${pkgs.isync}/bin/mbsync primary";
          onNotify = "${pkgs.libnotify}/bin/notify-send -t 5000 'You received new private mail.'";
        };
```

Rebooted. Than ran `mbsync -a`, pinentry pops up, typed in password.
The changed the nix config again to enable the service and ran `sudo nixos-rebuild switch --flake .#`, then ran 

```
db > systemctl --user status imapnotify-primary.service
○ imapnotify-primary.service - imapnotify for primary
     Loaded: loaded (/home/db/.config/systemd/user/imapnotify-primary.service; enabled; preset: enabled)
     Active: inactive (dead)
```

Tried running `systemctl --user enable imapnotify-primary.service` manually but that didn't change the service status.

**Comment by minikN** [comment]
I also tried this: After re-enabling the service through the config, I rebooted and logged in. I than quickly stopped the service before I saw a pinentry prompt:
```
db > systemctl --user stop imapnotify-primary.service
db > systemctl --user status imapnotify-primary.service
○ imapnotify-primary.service - imapnotify for primary
     Loaded: loaded (/home/db/.config/systemd/user/imapnotify-primary.service; enabled; preset: enabled)
     Active: inactive (dead) (Result: exit-code) since Sat 2023-07-15 11:17:20 CEST; 13s ago
   Duration: 656ms
    Process: 1593 ExecStart=/nix/store/d40h2bvn1310s1hjwzsnzkiwxivg89pk-goimapnotify-2.3.7/bin/goimapnotify -conf /nix/store/kr9knprwi6lvsjxwdz8qf33m8mbymxqd->
   Main PID: 1593 (code=exited, status=1/FAILURE)
        CPU: 15ms

Jul 15 11:17:20 slimboy systemd[1586]: Stopped imapnotify for primary.
```
Then I ran `mbsync -a` manually again and restarted the service:
```
db > systemctl --user start imapnotify-primary.service
db > systemctl --user status imapnotify-primary.service
● imapnotify-primary.service - imapnotify for primary
     Loaded: loaded (/home/db/.config/systemd/user/imapnotify-primary.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2023-07-15 11:17:55 CEST; 3s ago
    Process: 1998 ExecStart=/nix/store/d40h2bvn1310s1hjwzsnzkiwxivg89pk-goimapnotify-2.3.7/bin/goimapnotify -conf /nix/store/kr9knprwi6lvsjxwdz8qf33m8mbymxqd->
   Main PID: 1998 (code=exited, status=1/FAILURE)
        CPU: 15ms
lines 1-6/6 (END)
```

**Comment by minikN** [comment]
Is there any way to actually see what the FAILURE is systemd reports? I'm not too familiar with it but journald has no entries:

```
db > journalctl -u imapnotify-primary.service                                                                                                            
-- No entries --
```

**Comment by ncfavier** [comment]
That should mean that goimapnotify exited with status 1 without writing anything. Maybe try `-debug`?

**Comment by minikN** [comment]
> That should mean that goimapnotify exited with status 1 without writing anything. Maybe try `-debug`?

Okay. But how am I supposed to try it with the debug flag? Looking through the [https://gitlab.com/shackra/goimapnotify](docs) of imapnotify, there doesn't seem to be a way to enable it via the config. Looking through the HM [options](https://mipmip.github.io/home-manager-option-search/?query=imapnotify) there doesn't seem to be a way to enable it either.

Running imapnotify manually works every time so I'm not sure how to enable the debug flag through nix / systemd. Can I overwrite the command written to the service by nix?

**Comment by ncfavier** [comment]
It's not very ergonomic, but

```nix
systemd.user.services.imap-primary.Services.ExecStart = lib.mkForce "${getExe config.services.imapnotify.package} -debug -conf '${config.xdg.configHome}/imapnotify/imapnotify-primary-config.json'";
```

**Comment by minikN** [comment]
> It's not very ergonomic, but
> 
> ```nix
> systemd.user.services.imap-primary.Services.ExecStart =
>   lib.mkForce "${getExe config.services.imapnotify.package} -debug -conf '${config.xdg.configHome}/imapnotify/imapnotify-primary-config.json'";
> ```

Thank you. Unfortunately I cannot seem to get it to work. I'm not quite sure where to add it since `systemd.user.services` exist for both system and HM.

I tried adding it to the system level:

```
config = {
systemd.user.services.imap-primary.Services.ExecStart =
        lib.mkForce "${lib.getExe config.home-manager.users.${config.user}.services.imapnotify.package} -debug -conf '${config.home-manager.users.${config.user}.xdg.configHome}/imapnotify/imapnotify-primary-config.json'";
}
```
But it'd error out saying:
> The option `systemd.user.services.imap-primary.Services' does not exist.

I looked throught the [available](https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=systemd.user.services.%3Cname%3E) options and tried `script` instead of `Services.ExecStart`. This would build fine, but the systemd service didn't change at all.

Then I tried adding it to the HM config:
```
  config = {
    home-manager.users.${config.user} = {
        systemd.user.services.imap-primary.Services.ExecStart =
        lib.mkForce "${lib.getExe config.home-manager.users.${config.user}.services.imapnotify.package} -debug -conf '${config.home-manager.users.${config.user}.xdg.configHome}/imapnotify/imapnotify-primary-config.json'";
  };
};
```

This would also build fine, but once again the systemd service doesn't change at all. Sorry, I'm new to Nix and not quite sure if I did it correclty.

**Comment by ncfavier** [comment]
That was meant as home-manager configuration. Your imap-primary service should definitely change after switching

**Comment by minikN** [comment]
> That was meant as home-manager configuration. Your imap-primary service should definitely change after switching

Added it [here](https://github.com/minikN/nix/blob/master/modules/mail/default.nix#L38-L39). Ran
```
sudo nixos-rebuild switch --flake .# 
```

Ran fine. Rebooted.

```
db > systemctl --user status imapnotify-primary.service
● imapnotify-primary.service - imapnotify for primary
     Loaded: loaded (/home/db/.config/systemd/user/imapnotify-primary.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2023-07-15 12:58:08 CEST; 11s ago
    Process: 1413 ExecStart=/nix/store/d40h2bvn1310s1hjwzsnzkiwxivg89pk-goimapnotify-2.3.7/bin/goimapnotify -conf /nix/store/kr9knprwi6lvsjxwdz8qf33m8mbymxqd->
   Main PID: 1413 (code=exited, status=1/FAILURE)
        CPU: 15ms
```

`ExecStart` didn't change.

**Comment by ncfavier** [comment]
Typo, should be `Service` not `Services`

**Comment by minikN** [comment]
> Typo, should be `Service` not `Services`

No worries. But unfortunately even after fixing the typo and rebuilding/switching the service didn't change.

**Comment by ncfavier** [comment]
aaand `imapnotify-primary` not `imap-primary`.

**Comment by minikN** [comment]
Okay I could have spotted that myself. Thanks, the service changed now. It still reports
```
db > systemctl --user status imapnotify-primary.service
● imapnotify-primary.service - imapnotify for primary
     Loaded: loaded (/home/db/.config/systemd/user/imapnotify-primary.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2023-07-15 13:26:52 CEST; 7s ago
    Process: 3823 ExecStart=/nix/store/d40h2bvn1310s1hjwzsnzkiwxivg89pk-goimapnotify-2.3.7/bin/goimapnotify -debug -conf /home/db/.config/imapnotify/imapnotif>
   Main PID: 3823 (code=exited, status=1/FAILURE)
        CPU: 15ms
```

However something changed I think.

```
db > systemctl --user | grep imap                                                                                                                          
  imapnotify-primary.service                                                                                      loaded activating auto-restart imapnotify for primary
```

I could have sworn that earlier on it also listed `imapnotify-primary.timer`, which is gone now. But maybe I'm hallucinating. In any case, the service output doesn't help much. In addition to that, I also don't see pinentry popping up now (after reboot). Again if I manually run the `ExecStart` command it works:

```
db > /nix/store/d40h2bvn1310s1hjwzsnzkiwxivg89pk-goimapnotify-2.3.7/bin/goimapnotify -debug -conf '/home/db/.config/imapnotify/imapnotify-primary-config.json'
INFO[0000] Command: /nix/store/mh1c3p23xby3chc3q0c0g78fa1nn65yw-bash-5.2-p15/bin/bash -c '/nix/store/l3rzmr79vdhbyx28pnxzqsppbks4hq21-getPassword'
a8WXvw LOGIN db@minikn.xyz REDACTED
a8WXvw OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE SEARCH=X-MIMEPART XDOVECOT ACL UIDPLUS LITERAL+ NOTIFY SPECIAL-USE FILTER=SIEVE COMPRESS=DEFLATE XAPPLEPUSHSERVICE QUOTA ACL RIGHTS=texk] Logged in
mQmqmA EXAMINE Inbox
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft $purchases $social $Forwarded)
* OK [PERMANENTFLAGS ()] Read-only mailbox.
* 13 EXISTS
* 0 RECENT
* OK [UNSEEN 1] First unseen.
* OK [UIDVALIDITY 1606209038] UIDs valid
* OK [UIDNEXT 4623] Predicted next UID
* OK [HIGHESTMODSEQ 13155] Highest
mQmqmA OK [READ-ONLY] Examine completed (0.001 + 0.000 secs).
INFO[0004] Watching mailbox Inbox
ot_O5g IDLE
+ idling
```

**Comment by dbaynard** [comment]
I've been able to upgrade, now, and I can't reproduce this… but I'm not relying on pinsentry. Thanks for your patience.

My impnotify config is much like yours, except I don't use the `extraConfig` and I call `mbsync` in `onNotify` and `notmuch` in `onNotifyPost`.

**Comment by minikN** [comment]
For anyone interested, I finally fixed this problem (yeah, I can't believe it either).

The problem was the script responsible for retrieving the password from `pass`. Two things are important:
- Script needs to know the value of `GNUPGHOME` and `PASSWORD_STORE_DIR`
- Any binary used in the script has to have an absolute nix path

In the end, I ended up with this:
```nix
accounts.email.accounts.work.passwordCommand = toString (pkgs.writeShellScript "get-work-password" ''
## ~!shell!~
export GNUPGHOME=${config.home-manager.users.${config.user}.programs.gpg.homedir}
export PASSWORD_STORE_DIR=${config.const.passDir}
${pkgs.pass}/bin/pass show Mail/apprologic.de/demis.balbach@apprologic.de | ${pkgs.coreutils}/bin/head -n 1
'');
```

previously I had just `head`, which is why it didn't work. I found this out by trial and error.
