### ISSUE TITLE
browserpass: Add `programs.browserpass.browsers = [  "librewolf" ]` 

### ISSUE THREAD

**Issue by BenediktBroich** [nix-community/home-manager#4227]
### Description

The [firefox/native-messaging-host](https://github.com/nix-community/home-manager/blob/master/modules/programs/browserpass.nix#L65) for [browserpass](https://github.com/nix-community/home-manager/blob/master/modules/programs/browserpass.nix) does not work with [librewolfl](https://github.com/nix-community/home-manager/blob/master/modules/programs/browserpass.nix), but there is a [librewolf/native-messaging-host](https://github.com/browserpass/browserpass-native/blob/master/Makefile#L477).

Error: `Error: Error: No such native application com.github.browserpass.native`

### Current configuration example
```
{
  services.pass-secret-service.enable = true;
  programs = {
    librewolf = {
      enable = true;
    };
    password-store = {
      enable = true;
    };
    browserpass = {
      enable = true;
      browsers = [ "firefox" ];
    };
  };
}
```

### Expected configuration example
```
{
  services.pass-secret-service.enable = true;
  programs = {
    librewolf = {
      enable = true;
    };
    password-store = {
      enable = true;
    };
    browserpass = {
      enable = true;
      browsers = [ "librewolf" ];
    };
  };
}
```

**Comment by RobinBoers** [comment]
+1 on this
