### ISSUE TITLE
Allow specifying presets for Starship

### ISSUE THREAD

**Issue by pluiedev** [nix-community/home-manager#4231]
### Description
Starship has a bunch of handy [presets](https://starship.rs/presets/). With the simple command `starship preset <name>`, one can generate a template of the `starship.toml` and modify it further. Now, since `starship.toml` is managed by HM, I think it's reasonable to add a preset option that does this step automatically to save the user from typing... this, but in Nix.

![image](https://github.com/nix-community/home-manager/assets/22406910/449361de-f470-44bf-92e6-c9f212343045)

**Comment by loicreynier** [comment]
There is no particular challenge to implement this in HM, but IMO customisation presets do not behold here.

**Comment by jacekszymanski** [comment]
You can output the preset TOML to file and use it like this:

```
program.starship.settings = (with builtins; fromTOML (readFile ./starship.toml)) // {
  # overrides here, may be empty
};
```

This way you can also override the preset in Nix and possibly update the preset when it changes upstream without losing your overrrides. For more advanced overrides you can use ```recursiveUpdate```.

**Comment by pluiedev** [comment]
> You can output the preset TOML to file and use it like this:
> 
> ```
> program.starship.settings = (with builtins; fromTOML (readFile ./starship.toml)) // {
>   # overrides here, may be empty
> };
> ```
> 
> This way you can also override the preset in Nix and possibly update the preset when it changes upstream without losing your overrrides. For more advanced overrides you can use `recursiveUpdate`.

That's a valid point - I'll do that then :+1:

**Comment by axelsimon** [comment]
> You can output the preset TOML to file and use it like this:
> 
> ```
> program.starship.settings = (with builtins; fromTOML (readFile ./starship.toml)) // {
>   # overrides here, may be empty
> };
> ```
> 
> This way you can also override the preset in Nix and possibly update the preset when it changes upstream without losing your overrrides. For more advanced overrides you can use `recursiveUpdate`.

This looks neat @jcszymansk. Sadly, my knowledge and understanding of Nix is pretty limited, so sorry if this seems obvious to you, but i've tried the following to load a preset in starship, and it fails:
```nix
settings = (with builtins; fromTOML (readFile "${pkgs.starship}/share/starship/presets/gruvbox-rainbow.toml")) {
     time = {
       disabled = false;
       format = "[$time]($style) ";
     };
    // more settings
};
```

```nix
error: attempt to call something which is not a function but a set: { "$schema" = "https://starship.rs/config-schema.json"; …
````

What am i misunderstanding?

@pluiedev did you get it working in the end?

**Comment by jcszymansk** [comment]
@axelsimon You need `//` in the first line before the `{`:

```nix
settings = (with builtins; fromTOML (readFile "${pkgs.starship}/share/starship/presets/gruvbox-rainbow.toml")) // {
     time = {
       disabled = false;
       format = "[$time]($style) ";
     };
    // more settings
};
```

**Comment by jblsp** [comment]
Here is a simple example using recursiveUpdate:
```nix
{lib, ...}: {
  programs.starship = let
    getPreset = name: (with builtins; removeAttrs (fromTOML (readFile "${pkgs.starship}/share/starship/presets/${name}.toml")) ["\"$schema\""]);
  in {
    enable = true;
    settings =
      lib.recursiveUpdate
      (lib.mergeAttrsList [
        (getPreset "nerd-font-symbols")
        (getPreset "gruvbox-rainbow")
      ]) {
        username = {
          # Your settings here
          show_always = true;
        };
      };
  };
}
```

**Comment by jblsp** [comment]
Here is a simple example using recursiveUpdate. This should also fix @axelsimon's problem.
```nix
{lib, ...}: {
  programs.starship = let
    getPreset = name: (with builtins; removeAttrs (fromTOML (readFile "${pkgs.starship}/share/starship/presets/${name}.toml")) ["\"$schema\""]);
  in {
    enable = true;
    settings =
      lib.recursiveUpdate
      (lib.mergeAttrsList [
        (getPreset "nerd-font-symbols")
        (getPreset "gruvbox-rainbow")
      ]) {
        username = {
          # Your settings here
          show_always = true;
        };
      };
  };
}
```
