### ISSUE TITLE
Make UID and GID of current user available.

### ISSUE THREAD

**Issue by Mikilio** [nix-community/home-manager#4242]
### Description

It would be nice to have UIDs and GIDs of the user available in the home-manager config. Since I like to decouple my home-manager configs from host I am on, I never use the nixosModule which means that I don't have the IDs in scope. As a workaround I have to do hacky things with `_module.args`. It would be nice if I could just declaratively choose the IDs or have a nix function that evaluates to them. I don't know what is the best way to do this, but I'd love to see it happen.

**Comment by Mikilio** [comment]
I would like to use it as a value in a nix expression. For my particular use-case I need it in a Path.

**Comment by ncfavier** [comment]
(Well, `UID` is usually not an environment variable, but you do have `XDG_RUNTIME_DIR` if that helps)

**Comment by Mikilio** [comment]
I was happy for a few seconds but then I realized I need the path for a program written in go that doesn't care about environment variables. So I need a way to evaluate to a real path as a nix expression.

**Comment by Mikilio** [comment]
So in this particular case I solved it with:
```
"/run/user/${builtins.readFile /proc/self/loginuid}/foo"
```

**Comment by ncfavier** [comment]
That's a bit hacky and would fail in pure evaluation mode.

How are you passing the path to the program? Could you make a wrapper script maybe?

**Comment by Mikilio** [comment]
The program is packaged as a systemd service that runs a script starting the go executable and passing it a attribute set as a JSON file.

**Comment by Mikilio** [comment]
> That's a bit hacky and would fail in pure evaluation mode.
> 
> How are you passing the path to the program? Could you make a wrapper script maybe?

You are right about that I will stick to _module.args with flake_parts

**Comment by ncfavier** [comment]
It would help if you said what the actual program/service is. https://xyproblem.info/

**Comment by Mikilio** [comment]
Since it was a feature request I wanted to keep it general.

However, what I want to use is the home-manager module of sops-nix.
And I am having this [issue](https://github.com/Mic92/sops-nix/issues/284).

**Comment by rycee** [comment]
I haven't thought about this a lot but I'm almost certain that we cannot do anything sensible here. The only occasion where Home Manager would know the user's uid or gid at evaluation time, without you putting them explicitly in your HM configuration, would be if you use Home Manager as a NixOS (or possibly nix-darwin) module and put the explicit uid and gid in there.

I think this use-case is sufficiently rare that we probably won't do anything here, if you need it then I think `_module.args`, as you do now, or `config.lib` is probably good places to put them yourself (or just make your own option for it).

**Comment by Mikilio** [comment]
I thought a bit about it and I think I agree. If i have user specific configs depending on system information, it's better to factor out that information and just declare it in the config as global variables. Since I don't even allow mutableUsers I think this approach is most coherent with nix's philosophy. I will close, this issue as I also found a workaround.
