### ISSUE TITLE
Allow `$HOME/.config/home-manager` to be symlinked

### ISSUE THREAD

**Issue by martin-braun** [nix-community/home-manager#4245]
Setting up the stand-alone home-manager for NixOS from a different machine via network drive is not possible when `$HOME/.config/home-manager` is symlinked to the directory on the network drive.

```
$ nix run home-manager/release-23.05 -- init --switch
The file /home/mbx/.config/home-manager/home.nix already exists, leaving it unchanged...
The file /home/mbx/.config/home-manager/flake.nix already exists, leaving it unchanged...

Creating initial Home Manager generation...

error: path '/home/mbx/.config/home-manager' is not a flake (because it's not a directory)
error: path '/home/mbx/.config/home-manager' is not a flake (because it's not a directory)
error: path '/home/mbx/.config/home-manager' is not a flake (because it's not a directory)
```

In contrast, NixOS Flakes work fine, even when `/etc/nixos` is symlinked to a network directory. I would expect `home-manager` to allow the same.

My current dirty work-around is:

```sh
rm -rf $HOME/.config/home-manager
cp -r /media/psf/flake-mbx $HOME/.config/
mv $HOME/.config/flake-mbx $HOME/.config/home-manager
home-manager switch
```

Dirty ..

**Comment by dongcarl** [comment]
See: https://github.com/nix-community/home-manager/issues/4198#issuecomment-1638500038

**Comment by Jayojay12** [comment]
Hey

**Comment by jonahbron** [comment]
This appears to be obsolete, I have `~/.config/home-manager` symlinked and it has no trouble.
