### ISSUE TITLE
bug: Kime configuration outdated

### ISSUE THREAD

**Issue by FurstPlattner** [nix-community/home-manager#4261]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The Kime IME has recently changed its configuration file format to use YAML tags. In response, the NixOS config has changed from a YAML `config` attribute [to a freeform `extraConfig` one.](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/i18n/input-method/kime.nix). It would be nice to have this in the home manager module as well.

### Maintainer CC

@Kranzes

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.05 (Stoat), 23.05.20230719.b8f0f72`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
It's a bit of a shame to move away from structured settings but it looks like we have no choice: https://github.com/NixOS/nixpkgs/pull/211937#issuecomment-1399556736
