### ISSUE TITLE
bug: tmate: config file gets created even if there are no config options

### ISSUE THREAD

**Issue by cloudlena** [nix-community/home-manager#4270]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

If I don't set any config options for `programs.tmate`, an empty config file gets created, which pollutes a user's home directory. This file should only be created if any config options are set. E.g.,

```nix
programs.tmate.enable = true;
```
Should not create a config file.

```nix
programs.tmate = {
  enable = true;
  host = "tmate.io";
};
```

Should create a config file.

### Maintainer CC

@jlesquembre 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.1.39, NixOS, 23.11 (Tapir), 23.11.20230722.12303c6`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.15.1`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
```

**Comment by ncfavier** [comment]
Could you test https://github.com/nix-community/home-manager/pull/4271 please?
