### ISSUE TITLE
bug: Getting 'optionsDocBook is deprecated since 23.11 and will be removed in 24.05' on most runs

### ISSUE THREAD

**Issue by yoav-lavi** [nix-community/home-manager#4273]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

**Home Manager installation type**: Standalone + Flake (also happens without the flake)

I seem to get

```
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
```

On almost every run, the error seems to originate from https://sourcegraph.com/github.com/NixOS/nixpkgs/-/blob/nixos/lib/make-options-doc/default.nix?L160

This doesn't seem to have any effect at the moment, but thought I'd post an issue

### System information

```markdown
- system: `"aarch64-darwin"`
- host os: `Darwin 22.6.0, macOS 13.5`
- multi-user?: `yes`
- sandbox: `no`
- version: `nix-env (Nix) 2.16.1`
- channels(root): `"nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by emilazy** [comment]
Yeah, this is an unfortunate consequence of the manual build pipeline still being DocBook-based. I am too busy for the next while to tackle this but intend to make the necessary changes to the upstream Nixpkgs documentation generator and migrate the manual generation to it starting in probably a month or so.

**Comment by bjornfor** [comment]
@emilazy: Are you working on it? If this is painful to fix in home-manager for NixOS 23.11, maybe we can buy some time by un-deprecating optionsDocBook in nixpkgs for one more release?

**Comment by considerate** [comment]
I have a WIP PR for this at #4673. Hopefully I'll be able to finish this before the NixOS 23.11 release.

**Comment by bjornfor** [comment]
> I have a WIP PR for this at https://github.com/nix-community/home-manager/pull/4673. Hopefully I'll be able to finish this before the NixOS 23.11 release.

That's awesome, thanks!

In case we need more time to finalize that, I made a nixpkgs PR to postpone the deprecation one release cycle: https://github.com/NixOS/nixpkgs/pull/270093.

**Comment by considerate** [comment]
@bjornfor I hope that we can merge (and backport) the changes needed in the next couple of days so hopefully postponing the depreciation shouldn't be necessary.
