### ISSUE TITLE
How to circumvent broken package to still manage config with HM?

### ISSUE THREAD

**Issue by augustebaum** [nix-community/home-manager#4278]
Hi,

I'm trying to install qutebrowser and manage my configuration for it using HM. It works on my nixos install, but on MacOS I get the error:
```
error: Package ‘qtwebengine-5.15.12’ [...] is marked as broken, refusing to evaluate.
```

Can anyone recommend a way to pin a qutebrowser version to avoid this? Or otherwise make it so I can manage my config with HM even if I'm installing the app from another source (like homebrew)?

System info:
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(auguste): `"darwin, home-manager, nixpkgs"`
 - nixpkgs: `/Users/auguste/.nix-defexpr/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs

You should be able to set `package = pkgs.emptyDirectory;` to disable installing a package.

**Comment by teto** [comment]
or you can install a version of qutebrowser that works from a different commit of nixpkgs as [nixos.wiki/wiki/FAQ/Pinning_Nixpkgs](https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs) mentions:
```
let
  pinnedPkgs = hostPkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    # nixos-unstable as of 2017-11-13T08:53:10-00:00 CHANGE IT
    rev = "ac355040656de04f59406ba2380a96f4124ebdad";
    sha256 = "0frhc7mnx88sird6ipp6578k5badibsl0jfa22ab9w6qrb88j825";
  };
in 
  programs.qutebrowser.package = pinnedPkgs.qutebrowser
```
