### ISSUE TITLE
bug: khal locale options do not get applied

### ISSUE THREAD

**Issue by antonmosich** [nix-community/home-manager#4283]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The documentation for khal currently supplies several options to modify the way khal will look like, like dateformat etc. Those options do not get applied at any point, though the code for including the options is there, it's just commented out.
https://github.com/nix-community/home-manager/blob/f58889c07efa8e1328fdf93dc1796ec2a5c47f38/modules/programs/khal.nix#L164
I do not know why it is commented out, maybe it breaks something. I tried it on my machine and it worked.

### Maintainer CC

@teto

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.4.6-1-MANJARO, Manjaro Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - channels(anton): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by teto** [comment]
I had commented it out because it triggered errors because of missing defaults or sthg. It's possible I fixed it then commented it. PR welcome I can test it

**Comment by teto** [comment]
seems like it's fine if `locale` has a default value (currently missing).
