### ISSUE TITLE
Make dotDir variable export ZDOTDIR instead of just setting the variable locally

### ISSUE THREAD

**Issue by NovaViper** [nix-community/home-manager#4286]
### Description
In certain cases, having `ZDOTDIR` can cause issues where applications cannot see the variable and thus result in conflicts where the program ends up thinking all of the zsh configurations are located on the home folder instead of the specified folder in the `dotDir` variable. Specifically, I'm encountering [this very issue with topgrade](https://github.com/topgrade-rs/topgrade/issues/514) and having the variable be exported instead of set locally would fix the issue entirely. So instead of a `~/.config/zsh/zshenv` like this
```
# Environment variables
. "/home/novaviper/.nix-profile/etc/profile.d/hm-session-vars.sh"

# Only source this once
if [[ -z "$__HM_ZSH_SESS_VARS_SOURCED" ]]; then
  export __HM_ZSH_SESS_VARS_SOURCED=1
  
fi

ZDOTDIR=$HOME/.config/zsh
```

it should look like this
```
# Environment variables
. "/home/novaviper/.nix-profile/etc/profile.d/hm-session-vars.sh"

# Only source this once
if [[ -z "$__HM_ZSH_SESS_VARS_SOURCED" ]]; then
  export __HM_ZSH_SESS_VARS_SOURCED=1
  
fi

export ZDOTDIR=$HOME/.config/zsh
```

With the offending lines being [these](https://github.com/nix-community/home-manager/blob/master/modules/programs/zsh.nix#L481-L493).

### Metadata
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.11 (Tapir), 23.11.20230729.e6ab469`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/9xpvg56sk83p217x1ws6a42ga07mip2d-source`
```
HomeManager: 23.11-pre

**Comment by teto** [comment]
Looks sensible, patch welcome
