### ISSUE TITLE
bug: direnv nushell integration needs to be updated for nushell 0.83

### ISSUE THREAD

**Issue by lilyball** [nix-community/home-manager#4291]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

`nushell` version 0.83 deprecated the `let-env` command in favor of just assigning to `$env.NAME` directly. This syntax was supported in at least version 0.82 as well (I haven't tried older versions). Unfortunately, the `direnv` module is still using `let-env` in its nushell integration.

https://github.com/nix-community/home-manager/blob/4fd794d3df88735dcf9662155d77b08a2e2dde29/modules/programs/direnv.nix#L127-L142

As nixpkgs now has nushell 0.83, this needs to be updated to assign to `$env.config` directly.

While you're at it, you can also simplify the code, it doesn't need to create each key separately, it can look something like

```nu
$env.config.hooks.pre_prompt = ($env.config?.hooks?.pre_prompt? | default [] | append {
    code: "…"
})
```

### Maintainer CC

@rycee

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(lily): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by ncfavier** [comment]
Is this fixed by https://github.com/nix-community/home-manager/pull/4292 ?

**Comment by lilyball** [comment]
Yes, thanks.
