### ISSUE TITLE
bug: qutebrowser - system wide installed version is replaced by hm

### ISSUE THREAD

**Issue by VuiMuich** [nix-community/home-manager#4321]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have `qutebrowser-qt6` installed through my `nixos/configuration.nix`.
When I use `programs.qutebrowser.enable` home-manager installs the qt5 version.

This may well be intended behaviour and just feel like a bug. And it might be well solvable with an overlay and I am still to noob to nix expressions.

A nice solution IMO would be to add an option `programs.qutebrowser.qt6.enable = true`, but if someone could give pointers how to write an overlay as a workaround that would be much appreciated.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.05 (Stoat), 23.05.20230610.d3bb401`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - channels(vuimuich): `""`
 - nixpkgs: `/nix/store/0yzh1r9mhsr4vp5w96y3i0jgz3m2qzv6-source`
```

**Comment by ncfavier** [comment]
`programs.qutebrowser.package = pkgs.qutebrowser-qt6;` or `programs.qutebrowser.package = pkgs.emptyDirectory;`

**Comment by VuiMuich** [comment]
Oh, well that was easy.. actually almost too obvious :joy: 
Thanks.

**Comment by VuiMuich** [comment]
Just one more question: with `programs.qutebrowser.package = pkgs.qutebrowser-qt6;` home-manager would at first install its own instance of `qutebrowser-qt6` and garbage collection would later hard link to the system one?

**Comment by ncfavier** [comment]
No, garbage collection has nothing to do with this. You would get one package under `/run/current-system/sw/bin` and one under wherever your user profile is, so your shell would pick whichever comes first in `PATH` (which is usually the user one).

**Comment by VuiMuich** [comment]
Ah, so with `pkgs.emptyDirectory` I would suppress home-manager installing the user profile on, right?
