### ISSUE TITLE
bug: installation is extremely britle, no ability to repair "broken" installations.

### ISSUE THREAD

**Issue by YellowOnion** [nix-community/home-manager#4335]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I tried downgrading to nixpkgs 23.05, and it's been a complete disaster.

I get this warning:

```
trace: warning: You are using

  Home Manager version 23.11 and
  Nixpkgs version 23.05.
  ```

The installation process, via `nix-shell -p nix-shell '<home-manager>' -A install`:

 *does not support* flakes, it will create a new `home.nix` instead.

*doesn't install the correct version*,  after running installation with the correct home-manager repo, and then attempting to build my flake version, it still complains about 23.11 being used.

To fix this you have to explicitly call:  `nix-env --uninstall home-manager-path` and then run installation.

And then it gives me errors about docbook:

```
error: builder for '/nix/store/3ynsb3fhvxxphhq5psnpjhfn74h7sksp-options-docbook.xml.drv' failed with exit code 6;
       last 10 log lines:
       > options.xml:169: parser error : Opening and ending tag mismatch: varlistentry line 104 and variablelist
       > </variablelist>
       >                ^
       > options.xml:170: parser error : Opening and ending tag mismatch: variablelist line 5 and appendix
       > </appendix>
       >            ^
       > options.xml:170: parser error : Premature end of data in tag appendix line 2
       > </appendix>
       >            ^
       > unable to parse options.xml
       For full logs, run 'nix log /nix/store/3ynsb3fhvxxphhq5psnpjhfn74h7sksp-options-docbook.xml.drv'.
error: 1 dependencies of derivation '/nix/store/03wxkyy23ywcdmpyc17z3pkb5vicbw3y-hm-module-docs-for-nmd.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xfp62y8bw5g9klgnfd72vc1n85zzs7mm-nmd-documents.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4arpkjpcar3xcgb2slf49czfnbbk740p-manual-combined.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vfzfl39a7bp271hap9mys7plb21fhyph-man-pages.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nyf5i64xl6qbwm7vbsnri42qi3kj0plj-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f9v9sfs87h7pm18zh2q535x21wv2xzz3-home-manager-generation.drv' failed to build
```

The option `manual.manpages.enable = false;` seems to be missing from the documentation too, I was only lucky enough to find it in an old bug report.

not to mention that the home-manager version in nixpkgs 23.05 (the one my NixOS config), also seems to be for 23.11, and also complains about version missmatch.

Is the expectation to always run `nixpkgs-unstable`, and only select specific applications from stable when they're buggy?

Sway/XWayland on unstable seems to constantly crash for me, so I can't use it, which is what motivated me to move my entire system to 23.05.

### Maintainer CC

@rycee

### System information

```markdown
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.0-bcachefs-master-640a004, NixOS, 23.05 (Stoat), 23.05.2573.61676e4dcfee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(daniel): `""`
 - channels(root): `"nixos-23.05, nixos-unstable, nixpkgs-master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
```

**Comment by rycee** [comment]
Indeed, I would also think this is a case of using the master branch of HM with Nixpkgs 23.05. @YellowOnion Could you check the output of `nix-channel --list` and check the URL of the home-manager entry? It should end with `release-23.05`, not `master`.

The `nix-shell -p nix-shell '<home-manager>' -A install` installation method is specifically for non-flake installs. If you want to use a flake setup then follow the steps in the [flake standalone](https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone) install instructions. Basically `nix run home-manager/release-23.05 -- init --switch` for Nixpkgs 23.05.

**Comment by YellowOnion** [comment]
Okay I'll admit I somehow missed the flake warning in the documentation, I originally did a non flake install and transitioned to flakes later, I think the other day I was quickly skim reading (perhaps even clicked the first subheading toc link) and missed it, a compounding of situations.

I explicitly downgraded the branch in nix-channel and made sure to call --update, after I saw the warning again I double checked the channel and called --update again, this is when I started to investigate it further and how I found that I had to remove home-path from my env to get the version warning to go away, this is also where I found that the home-manager version from stable nixpkgs (it's in my NixOS configuration, `which` showed it being in current-system/sw/bin) also showed the version warning.

I then hit that error about docs after making sure the warning was gone.

I'm not at my computer right now, but if you want maybe I can make video proof of it not working.

Now that I think about it, 
Perhaps this is just a stupid issue with path priorities and an impure nix-shell calling out to the home manager in the environment.

**Comment by YellowOnion** [comment]
@rycee Ok I think what I actually need to do is change home-manager in the flake so it points to the correct branch:

```nix
home-manager = {
      url = "github:nix-community/home-manager/release-23.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

home-manager wasn't installing itself correctly.
