### ISSUE TITLE
Bat builds cache without xdg dirs being set

### ISSUE THREAD

**Issue by KaitlynEthylia** [nix-community/home-manager#4345]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When rebuilding with the `bat` package enabled, it automatically runs `bat cache --rebuild` however at the time of running this, XDG dirs don't seem to be set, as it places the cache in .cache rather than where it should go (.local/cache in my case). Bat itself does follow xdg dirs as it places the files in the correct location when I run the command myself

### Maintainer CC

None given but @lovesegfault commited the addition of rebuilding the cache

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.11 (Tapir), 23.11.20230801.9e1960b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Please give the proposed fix in #4350 a try.
