### ISSUE TITLE
bug: cannot configure gdm anymore

### ISSUE THREAD

**Issue by Luflosi** [nix-community/home-manager#4352]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I would like to enable tap-to-click in GDM. After reading https://discourse.nixos.org/t/need-help-for-nixos-gnome-scaling-settings/24590/5, I tried something very similar to what was suggested:
```nix
home-manager.users.gdm = { ... }: {
  home.stateVersion = "23.05";

  dconf.settings = {
    "org/gnome/desktop/peripherals/touchpad" = {
      tap-to-click = true;
    };
  };
};
```
However, this no longer works properly.
This is because user profiles are now (since Nix 2.14) stored in the user's home directory, which is stored on a RAM disk for the gdm user. This directory will obviously be empty after a reboot. This causes the home-manager activation script to fail because it can't find the profile directory in `/run/gdm/.local/state/nix/profiles`.

Is there any good way still left to declaratively configure settings in GDM on NixOS?

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.37, NixOS, 23.11 (Tapir), 23.11pre502009.3c7487575d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos"`
 - channels(u): `"nixpkgs"`
 - nixpkgs: `/home/u/.nix-defexpr/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
[`services.xserver.displayManager.gdm.settings`](https://nixos.org/manual/nixos/unstable/options#opt-services.xserver.displayManager.gdm.settings)?

**Comment by Luflosi** [comment]
I'm quite sure that these are different settings that cannot be used to configure things like `tap-to-click`.

**Comment by BehradJi** [comment]
I have made the same configuration for changing gdm settings with home-manager, but the error I get is different, first I get systemd error for `home-manager-gdm.service`:
```
systemd[1]: home-manager-gdm.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: home-manager-gdm.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Home Manager environment for gdm.
```
And when I look at systemd service status, apparently the error is because home-manager couldn't `mkdir` the `.cache` directory in `/run/gdm` because of permission error.
```
Nov 18 12:24:29 Legion hm-activate-gdm[1284]: dbus-daemon[1284]: [session uid=132 pid=1284] Successfully activated service 'ca.desrt.dconf'
Nov 18 12:24:29 Legion hm-activate-gdm[804]: Activating linkGeneration
Nov 18 12:24:29 Legion hm-activate-gdm[804]: Cleaning up orphan links from /run/gdm
Nov 18 12:24:29 Legion hm-activate-gdm[804]: No change so reusing latest profile generation 11
Nov 18 12:24:29 Legion hm-activate-gdm[804]: Creating home file links in /run/gdm
Nov 18 12:24:29 Legion hm-activate-gdm[1391]: mkdir: cannot create directory ‘/run/gdm/.cache’: Permission denied
Nov 18 12:24:29 Legion hm-activate-gdm[1393]: ln: failed to create symbolic link '/run/gdm/.cache/.keep': No such file or directory
Nov 18 12:24:29 Legion systemd[1]: home-manager-gdm.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 12:24:29 Legion systemd[1]: home-manager-gdm.service: Failed with result 'exit-code'.
Nov 18 12:24:29 Legion systemd[1]: Failed to start Home Manager environment for gdm.
```
<details>
<summary>home-manager gdm settings:</summary>
  home-manager.users = {

    gdm= { lib, ... }: {

      home = {
        stateVersion = "23.05";
        file.".config/monitors.xml".source = ./monitors.xml;
      };
      dconf.settings = {

        "org/gnome/mutter" = {
          experimental-features = ["scale-monitor-framebuffer"];
        };

        "org/gnome/shell" = {
          disable-user-extensions = false;
        };

        "org/gnome/desktop/peripherals/keyboard" = {
          repeat-interval = lib.hm.gvariant.mkUint32 15;
          delay = lib.hm.gvariant.mkUint32 200;
          numlock-state = true;
          # remember-numlock-state = false;
        };

        "org/gnome/settings-daemon/plugins/color" = {
          night-light-enabled = true;
          night-light-temperature = lib.hm.gvariant.mkUint32 3800;
        };

        "org/gnome/desktop/peripherals/touchpad" = {
          speed = 0.50;
          tap-to-click = true;
          two-finger-scrolling-enabled = true;
          disable-while-typing = true;
        };

        "org/gnome/desktop/interface" = { 
          gtk-theme = "adw-gtk3-dark";
          font-name = "Cantarell 12";
          document-font-name = "Cantarell 12";
          titlebar-font = "Cantarell 12";
          monospace-font-name = "Source Code Pro 11";
        };
      };
    };
};
</details>

## System Information
```
- system: "x86_64-linux"
 - host os: Linux 6.5.11, NixOS 23.05 (Stoat), 23.05.20231114.d4b5a67
 - multi-user?: yes
 - sandbox: not sure
 - version: nix (Nix) 2.13.6
 - using flakes: yes
 - nixpkgs: github:NixOS/nixpkgs/nixos-23.05
```

**Comment by Luflosi** [comment]
This is now possible with NixOS since https://github.com/NixOS/nixpkgs/pull/234615 was merged 🎉:
```nix
programs.dconf.profiles.gdm.databases = [{
  settings."org/gnome/desktop/peripherals/touchpad" = {
    tap-to-click = true;
  };
}];
```

**Comment by jul1u5** [comment]
Is there a way to configure cursor and icon theme on GDM?

**Comment by Luflosi** [comment]
I would think so.
The way I figured out which setting to change was by executing `dconf watch /`, then changing some setting in the GNOME settings and then translating the output of that command to the corresponding Nix setting.

**Comment by jul1u5** [comment]
I got the cursor and font configuration working. But for some reason, my icon theme doesn't apply :thinking: 

```nix
programs.dconf.profiles.gdm.databases = [
  {
    settings = {
      "org/gnome/desktop/peripherals/touchpad" = {
        tap-to-click = true;
      };
      "org/gnome/desktop/interface" = {
        cursor-theme = "Bibata-Modern-Classic";
        icon-theme = "Papirus";
        font-name = "Overpass Regular 11";
        show-battery-percentage = true;
      };
    };
  }
];

users.users.gdm.packages = with pkgs; [
  bibata-cursors
  papirus-icon-theme
  overpass
];
```
