### ISSUE TITLE
Can't enable syntax highlighter in zsh

### ISSUE THREAD

**Issue by gepbird** [nix-community/home-manager#4353]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I want to enable brackets syntax highlighting in zsh, but I don't know how to do that with `programs.zsh.syntaxHighlighting`, since it doesn't have an example. The only options (other than `enable` and `package`) is `styles` that edits the `ZSH_HIGHLIGHT_STYLES` variable.

According to the [documentation](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md) in order to enable a syntax highlighter, we need to change the `ZSH_HIGHLIGHT_HIGHLIGHTERS` variable.
I think the solution is to add a new string option `syntaxHighlighting.highlighters` that adds this line to the .zshrc: `ZSH_HIGHLIGHT_HIGHLIGHTERS+=('${cfg.syntaxHighlighting.highlighters}')`

### Maintainer CC

@ThinkChaos introduced this feature in https://github.com/nix-community/home-manager/commit/f5f64ac022ed379442286a4e81a2a7cdc552cb28

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.11 (Tapir), 23.11pre514857.caac0eb6bdca`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos, stable-23.05"`
 - channels(gep): `"nixpkgs"`
 - nixpkgs: `/home/gep/.nix-defexpr/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
From a quick look at the [docs](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/brackets.md) I think you would have to do `styles.bracket-level-1 = "fg=blue,bold";` etc. An example would indeed be welcome.

**Comment by gepbird** [comment]
@ncfavier That generates this line in my .zshrc: `ZSH_HIGHLIGHT_STYLES+=('bracket-level-1' 'fg=blue,bold')` which unfortunately doesn't enable brackets highlighting.

**Comment by gepbird** [comment]
I edited the issue title and description after realizing there are 2 seperate zsh variables: `ZSH_HIGHLIGHT_HIGHLIGHTERS` for enabling and `ZSH_HIGHLIGHT_STYLES` for customizing a highlighter.
