### ISSUE TITLE
programs.git: use `lib.generators.toGitINI` instead of `gitToIni`

### ISSUE THREAD

**Issue by VwCSXg** [nix-community/home-manager#4354]
Is there any good reason that `git.nix` defines an own function [`gitToIni`](https://github.com/nix-community/home-manager/blob/2471d965a3522025157a790fc49c3567fd56e26e/modules/programs/git.nix#L49)  instead of using [`lib.generators.toGitINI`](https://github.com/NixOS/nixpkgs/blob/cde2941c60c5bd68e99682af12745978ca4cd0d3/lib/generators.nix#L197C2-L197C2)?

If not, I'd like to normalize it by using the generator function.

**Comment by rycee** [comment]
Yeah, shouldn't be a problem to use the Nixpkgs version. Feel free to open a PR 🙂
