### ISSUE TITLE
Ability to pass user-specific arguments to HM module users

### ISSUE THREAD

**Issue by iivvaannxx** [nix-community/home-manager#4392]
First of all, I apologize if this was asked before or it's an idea that has been already discussed and discarded for some reason, but no matter how I search it, I can't find anything related.

### Description
The concept is simple, when using Home Manager as a module, extra arguments can be passed through the `extraSpecialArgs`. However these arguments are passed to each and every one of the users defined in the `home-manager.users` option of the module.

Wouldn't be helpful (to avoid boilerplate code) to be able to pass down specific arguments to each user? Or is it simply non-sense and I am not seeing the picture as I should?

The most basic example and use case for this let's say it's the `username` (but can be expanded to quite a few other parameters.) Of course if I want to avoid repeating code I could use `let ... in` on the user configuration file, but those "variables" don't get passed down on the `imports` array, and if I want to use any piece of data of that kind I need to define it again and again on each module. 

Suppose I have a Git preset/module that looks like this: 

```
{ home, lib, pkgs, upkgs, ... } @ args: let

  inherit (lib) mkDefault;

in {

  # See: https://github.com/nix-community/home-manager/blob/master/modules/programs/git.nix
  programs.git = {

    enable = true;
    package = mkDefault pkgs.gitFull;

    userName = mkDefault "anyname";
    userEmail = mkDefault "anyemail";

    extraConfig = {

      init.defaultBranch = mkDefault "main";
    };
  };
}
```

This is imported through the `imports` array. Let's say that my `userName` is the same as my system account name, instead of defining it twice, I could have data like that all centralized in a file like for example `profile.nix` which contains a set of "constants" for a user. Then pass the contents of that file to its corresponding user and use it in a module like the above.

That would also allow me for example to, if I have two Git accounts (which I don't, but it's an example) to reuse the same 'preset' as I would have the different options parameterized.  

I tried to do it myself, with `_module.args`, `specialArgs` or any similar "typical way" to modify/extend the arguments of a module, but everything I tried resulted in invalid code. I came up with a solution, but it's really really ugly, and it doesn't work as expected; the home configuration file receives a custom argument, but any file under the `imports` array doesn't accept it's usage (which is curious, because it appears in the argument array (`{ ... } @ args`) after a `builtins.trace`, but when you try to use it, it fails saying that the parameter doesn't exist).

The solution is this:

```
users.example = { 

    imports = [ 
      
      # This is a little hacky, but needed to pass user-specific arguments to home-manager.
      # Somehow 'home' argument doesn't get passed unless it's explicitly specified.
      ({ home, ... } @ args: (import userConfig ({ inherit home customArgHere; } // args) ))
    ]; 
};
```

I also tried to look into the code of the HM module, but couldn't find any way to actually inject an argument to a user configuration. 

Is this a valid concern? Or I am fundamentally wrong because there's something of NixOS/Home Manager I still don't understand? (I am a bit of a newbie still).

Anyway, any clarification around this mater would be greatly appreciated.

**Comment by iivvaannxx** [comment]
Okay nevermind, I feel so dumb, I used `_module.args` and somehow I received an error (I did in the wrong place for sure) and never tried it again. Now I figured out how to do it, I apologize for creating an issue for such a trivial matter.

**Comment by musjj** [comment]
Can you post how you did it? I tried:

```nix
home-manager.users.foobar = {
  imports = [ .... ];
  _module.args.inputs = inputs;
  _module.args.outputs = outputs;
};
```

But got an infinite recursion.

**Comment by iivvaannxx** [comment]
I did it exactly like you show, using `_module.args`. I have a function that I use to create Home Manager users like this:

```nix
# Generates entries for each home manager user.
mkHomeUsers = homeUsers: (listToAttrs (map (userPath: let 

  # The profile of the current user.
  profile = getProfile userPath;

in {

  name = profile.username;
  value = { 
    
    _module.args.profile = profile;
    imports = [ userPath ];
  };

}) homeUsers));
```

And it works great, I receive the correct `profile` under each user configuration. If this doesn't work for you, I think it could be because you're trying to pass `outputs` to module.args. I am not sure of how your config looks and by any means I am an expert on NixOS because I am quite noob, but if the `outputs` represent your Flake configuration `outputs` it would make sense that you receive an infinite recursion. When the outputs are evaluated the home-manager module does too, if you pass outputs as a module when home-manager or a user (I don't have a clue how it works) configuration is evaluated it probaby finds `outputs` and tries to evaluate it, leading to an infinite recursion.

Now, take what I'm saying with a grain of salt because I am not an expert on this and I could be wrong. Try to remove the `outputs` and add something else like `_module.args.dummy = "hello";` and see if you can evaluate the value of `dummy` in a `repl` or somewhere. If it works then I'm afraid you can't pass `outputs` as an extra argument.
