### ISSUE TITLE
bug: xdg-open of URLs with Firefox installed by home-manager always tries to start a new instance

### ISSUE THREAD

**Issue by hcsch** [nix-community/home-manager#4402]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

With Firefox installed for my user with the home-manager module for NixOS, when I click on a link or use `xdg-open <http(s)-url>` firefox attempts to start a new instance, usually failing to do so, since one will already be running. This results in links just not working for me (other than from inside firefox).
The same also happens when manually executing `firefox --name firefox <url>` or `firefox <url>` from the command line.

### Maintainer CC

@rycee @kira-bruneau 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11.20230819.d680ded`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kira-bruneau** [comment]
This isn't specifically an issue with home-manager, but more just an upstream issue in Firefox. 

I'm using a custom desktop entry to workaround this: https://gitlab.com/kira-bruneau/home-config/-/blob/main/package/firefox/default.nix#L282-312

**Comment by kira-bruneau** [comment]
I wonder if it would be useful to include this by default in home-manager?

Ideally though, this should be fixed upstream.

**Comment by hcsch** [comment]
Ah ok, first of all thanks for the info. I think it might be nice to include this by default in home-manager, until it is indeed fixed upstream. That way things Just Work™ when you add firefox to your user packages.
Is there a tracking issue on Bugzilla for this? If I recall correctly, Arch Linux uses similar `Exec` lines in their desktop file (minus the `--name firefox`) for firefox and that worked for me.

**Comment by hcsch** [comment]
This doesn't seem to be an issue anymore for me (using GNOME 45 with nixos-unstable) with xdg-open using the xdg-desktop-portal `org.freedesktop.portal.OpenURI.OpenURI` method.
