### ISSUE TITLE
bug: standalone flake installation fails on new nix installations

### ISSUE THREAD

**Issue by e-nikolov** [nix-community/home-manager#4403]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm not sure if this should be addressed in home-manager or somewhere else, but with a brand new multi-user nix installation, running this home-manager installation command:

```sh
nix run --extra-experimental-features "flakes nix-command" home-manager/master -- init --switch ~/nix-config
```

Results in this error:

```
Could not find suitable profile directory, tried /home/test/.local/state/home-manager/profiles and /nix/var/nix/profiles/per-user/test
```

It looks like `.nix-profile` does not yet exist in brand new nix installations, but is created the first time `nix profile list` or `nix profile install` is executed. I tried both the default nix-installer and https://github.com/DeterminateSystems/nix-installer:

- `sh <(curl -L https://nixos.org/nix/install) --daemon`
- `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install`

### Maintainer CC

@rycee

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.15.90.1-microsoft-standard-WSL2, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.17.0`
- channels(root): `"nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by tomasmota** [comment]
Just ran into the same issue

**Comment by bb2020** [comment]
This issue should be pinned.

**Comment by bb2020** [comment]
Installing a package into user environment also creates the profile.
`nix-env -iA nixos.hello && nix-env -e hello`

**Comment by Hoverbear** [comment]
In... I believe Nix 2.15? (I don't see it in the changelog, but we've seen some similar issues to this) ... The default profile location was changed.

You can see the documentation here: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile#profiles. Similar documentation from an old version in Ubuntu shows this to be a different location back then: https://manpages.ubuntu.com/manpages/jammy/man1/nix3-profile.1.html

So, `/nix/var/nix/profiles/per-user/$USER` is not where a profile goes anymore.

`$NIX_STATE_DIR/profiles/per-user/root` is now only used for `root`, otherwise the profile directory is under `$XDG_STATE_HOME/nix/profiles`.

**Comment by e-nikolov** [comment]
@Hoverbear I think home-manager already handles the new profile location, but the issue is that the profiles don't exist at that location until the first execution of a nix command that queries or installs packages to the profile, e.g. `nix-env -q`,  `nix profile list` or `nix profile install`

**Comment by e-nikolov** [comment]
Upon further investigation, it appears that before the nix profile location change, the commands `nix shell` and `nix run` used to create the profile at /nix/var/nix/profiles/per-user/ if it was missing. But with nix v2.17.0 they don't create the profile at the new location ~/.local/state/nix/profiles/profile if it is missing.

Looks like installing home-manager via `nix run ...` used to work with the older versions of nix because it created the profile before home-manager checked it, but it doesn't work anymore because nix run does not create it anymore. 

This behaviour of nix 2.17.0 can probably be considered a bug, but until that is fixed, the quickest way to resolve this for home-manager might be to either 
- add the extra required step of running `nix-env -q` to the manual
- execute it automatically in home-manager's init script

Summary of how I tested the behaviour of nix run:

```bash
## create a new ubuntu VM in WSL with systemd enabled via 
wsl --install ubuntu
## install nix 2.13.3 via an older DeterminateSystems/nix-installer:
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.8.0 | sh -s -- install
. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

## check the global profiles directory
ls /nix/var/nix/profiles/per-user/ ## shows only root

## run nix run
nix run nixpkgs#hello ## the command does not need to run to completion for the profile to be created

## check the global profiles directory
ls /nix/var/nix/profiles/per-user/ ## shows root and the current user
```

I repeated the test with nix 2.17.0 via the latest nix-installer and checked ~/.local/state/nix/profiles/profile. The directory didn't exist after nix run, but it did after nix profile list.
