### ISSUE TITLE
bug: `home.homeDirectory' is not of type `path' using builtins.getEnv "HOME"

### ISSUE THREAD

**Issue by mfouesneau** [nix-community/home-manager#4407]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am trying to make my configuration a bit more flexible, but I have issues with setting the home directory automatically.

I tried the following
```
home.homeDirectory = (builtins.getEnv "HOME");
error: A definition for option `home.homeDirectory' is not of type `path'. Definition values:
       - In `/nix/store/m1620asilvapn32h0x3firzpzwack5gq-source/home.nix': ""
```
And I do not understand the error. If I put a fixed string, it works. 

Is there a particular type I should force?

### System information

```markdown
- system: `"x86_64-darwin"`
- host os: `Darwin 22.6.0, macOS 10.16`
- multi-user?: `yes`
- sandbox: `no`
- version: `nix-env (Nix) 2.17.0`
- channels(root): `"nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by testplayername** [comment]
Try converting to a `path` type with this [weird](https://nixos.org/manual/nix/stable/language/builtins.html#builtins-toPath) syntax:

```
home.homeDirectory = /. + builtins.getEnv("HOME");
```

**Comment by trueNAHO** [comment]
Flakes consider environment variables as impure: https://github.com/tweag/rfcs/blob/ca2845b81814c345945de4be0b36cd5fb4eb080b/rfcs/0049-flakes.md?plain=1#L25-L30

**Comment by rycee** [comment]
The code

    home.homeDirectory = builtins.getEnv "HOME";

should work, provided you are running in an impure setting. Getting the home directory this way used to be the default (and still is if you are using state version older than 20.09).

I would recommend against doing this, though. In any case, there is not much we can do about the behavior of `builtins.getEnv` in Home Manager since it is a Nix language issue.
