### ISSUE TITLE
Not an issue, please remove

### ISSUE THREAD

**Issue by JustWhateverIOnlyWantBetterCodeView** [nix-community/home-manager#4409]
I've encountered this issue and debugged it.

As it was mentioned `unsetopt CASE_GLOB` causes huge performance git.
The reason is that with `CASE_GLOB` enabled any glob like `/nix/store/sn59qaijwgpf8n41khl60mfnfbxyb16x-zsh-5.9/*` would be optimized as opening directory `/nix/store/sn59qaijwgpf8n41khl60mfnfbxyb16x-zsh-5.9/` and then `readdir` on this directory.
But what happens if `CASE_GLOB` is not set and globs are case-insensitive? Then zsh can no longer to this optimization, it must open `/nix/store` dir and search all of it because, there could exist a path like `/nix/store/SN59qaijwgpf8n41khl60mfnfbxyb16x-zsh-5.9/` or `/nix/store/sn59qaijWGPF8n41khl60mfnfbxyb16x-zsh-5.9/` (i.e., only case of letters changed).
In summary `unsetopt CASE_GLOB` disables pure paths optimization in globbing and forces zsh to list and go though entire `/nix/store`.

The only reliable workaround is to set `programs.zsh.prezto.caseSensitive = true`. Settings it to false (the default) causes not only prezto, but literally any unrelated zsh script that globs anything inside `/nix/store` to be very slow (e.g. direnv).

If you really want to keep `caseSensitive = false`, then you could try adding it to the very end of `pmodules` list so no other pmodules are affected (greatly improves zsh startup time). But it be honest this option is broken and potentially harmful.

_Originally posted by @JustWhateverIOnlyWantBetterCodeView in https://github.com/nix-community/home-manager/issues/2255#issuecomment-1706717448_

**Comment by JustWhateverIOnlyWantBetterCodeView** [comment]
Ups, I had not idea what "reference in another issue" button does, sorry.

**Comment by JustWhateverIOnlyWantBetterCodeView** [comment]
close

**Comment by JustWhateverIOnlyWantBetterCodeView** [comment]
close

**Comment by trueNAHO** [comment]
As the title suggests, you may want to close this issue.

**Comment by JustWhateverIOnlyWantBetterCodeView** [comment]
Hmm, I've tried closing it previously and it didn't work.
