### ISSUE TITLE
alacritty: upstream is migrating from yaml to toml

### ISSUE THREAD

**Issue by colemickens** [nix-community/home-manager#4415]
I've started building tip of alacritty, due to wayland incompatibility issues on newer sway.

It seems that the next release will move from YAML to TOML.

This is just a heads-up. I'll probably hack my HM fork to render TOML, but it might be best for HM to choose yaml/toml based on version.

**Comment by ncfavier** [comment]
Duplicate of https://github.com/nix-community/home-manager/issues/3696
