### ISSUE TITLE
wezterm: remove `wezterm.add_to_config_reload_watch_list` function call

### ISSUE THREAD

**Issue by trueNAHO** [nix-community/home-manager#4426]
# Description

The `wezterm.add_to_config_reload_watch_list` function was introduced in [20210814-124438-54e29167](https://wezfurlong.org/wezterm/changelog.html?h=add_to_config_reload_watch_list#20210814-124438-54e29167), but is no longer required since [20220807-113146-c2fee766](https://wezfurlong.org/wezterm/changelog.html?h=add_to_config_reload_watch_list#20220807-113146-c2fee766):

> Config will now automatically reload for changes made to required lua files. Previously, only the main config file and any files that you explicitly passed to `add_to_config_reload_watch_list` would trigger a reload.
>
> (Source: https://wezfurlong.org/wezterm/changelog.html?h=add_to_config_reload_watch_list#fixed_8)

For backwards compatibility, `wezterm.add_to_config_reload_watch_list` should only be inserted for versions between [20210814-124438-54e29167](https://wezfurlong.org/wezterm/changelog.html?h=add_to_config_reload_watch_list#20210814-124438-54e29167) and [20220807-113146-c2fee766](https://wezfurlong.org/wezterm/changelog.html?h=add_to_config_reload_watch_list#20220807-113146-c2fee766).

The concerned lines are:

https://github.com/nix-community/home-manager/blob/9f9e277b60a6e6915ad3a129e06861044b50fdf2/modules/programs/wezterm.nix#L103

https://github.com/nix-community/home-manager/blob/9f9e277b60a6e6915ad3a129e06861044b50fdf2/modules/programs/wezterm.nix#L105

# Module Maintainer

@blmhemu is the module maintainer:

https://github.com/nix-community/home-manager/blob/9f9e277b60a6e6915ad3a129e06861044b50fdf2/modules/programs/wezterm.nix#L15

**Comment by rycee** [comment]
Generally speaking we only support the version of a package that is in the targeted Nixpkgs channel. So if the version in Nixpkgs unstable does not require `add_to_config_reload_watch_list`, then we should simply remove it.

@blmhemu Could you have a look at this?
