### ISSUE TITLE
bug: fnott uses incorrect generator

### ISSUE THREAD

**Issue by eclairevoyant** [nix-community/home-manager#4444]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

As mentioned in the manpages for fnott, the app-wide settings need to be in an unnamed (global section). Using INI here is therefore incorrect, it should use `toINIWithGlobalSection`.

My current workaround:

```nix
{config, lib, pkgs, ...}:
let
  cfg = config.services.fnott;
in
{
  xdg.configFile."fnott/fnott.ini".source = lib.mkForce (pkgs.writeText "fnott.ini" (lib.generators.toINIWithGlobalSection {} cfg.settings));
}
```

Effectively, this change (without the priority change, of course) should be applied to the module itself.
Also, the config example for `services.fnott.settings` needs to be corrected.

### Maintainer CC

@polykernel

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.5.2-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(limao7): `"home-manager, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/limao7/.nix-defexpr/channels/nixpkgs`
```

**Comment by eclairevoyant** [comment]
Didn't see it documented anywhere, but if upstream supports it then this can be closed out. Thanks.

**Comment by MartinLoeper** [comment]
I stumbled across this as I only read the home manager option docs which unfortunately did not mention it. Would be great to add it there, too. ;D
