### ISSUE TITLE
bug: Prezto option 'prezto.pmoduleDirs' gives error [ definition 1-entry 1 ] is not of type `path'

### ISSUE THREAD

**Issue by im-notpua** [nix-community/home-manager#4452]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am using the `programs.zsh.prezto` as shown below:

```nix
 prezto = {
     enable = true;
     autosuggestions.color = "fg=#666666,bg=#ffffff";
     ...
     pmoduleDirs = [ "$HOME/.config/custom" ];
};
```
The `pmoduleDirs` option complains about wrong format.

detailed code files can be found in my [dotfiles](https://gitlab.com/imnotpua/nixos/-/blob/main/home-manager/zsh.nix?ref_type=heads).

But it gives the error 
```
$ home-manager switch
error: A definition for option `programs.zsh.prezto.pmoduleDirs."[definition 1-entry 1]"' is not of type `path'. Definition values:
       - In `/home/notpua/storage/nixos/home-manager/zsh.nix': "$HOME/.config/custom"
(use '--show-trace' to show detailed location information)
```

The full --show-trace output is [here](https://pastebin.com/mTQubVFd)

Note: I followed the documentation example from the [whole list](https://rycee.gitlab.io/home-manager/options.html#opt-programs.zsh.prezto.pmoduleDirs) of home-manager configuration options. 
Either the example given there is the wrong implementation of the `path` format or is there a problem in my end.

I have tried using absolute paths and using `~` in the above option.

### Maintainer CC

@emilazy @NickHu 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.05 (Stoat), 23.05.3356.73e1976309fc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(notpua): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - channels(root): `"home-manager, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
It seems either the type is incorrect or the example is incorrect. The `path` type requires an absolute path. I.e., a fully defined path without any shell variables or anything. Maybe @NickHu has any idea which way it is supposed to be?

In any case, the user's config home directory is quite easy to access, though. Perhaps

```
pmoduleDirs = [ "${config.xdg.configHome}/custom" ];
```

works better?

**Comment by im-notpua** [comment]
Yeah `${config.xdg.configHome}/custom`, worked. 

Ok, now the [options.html](https://rycee.gitlab.io/home-manager/options.html#opt-programs.zsh.prezto.pmoduleDirs) page needs to be updated.
