### ISSUE TITLE
ssh-agent seemingly not working?

### ISSUE THREAD

**Issue by TsujimotoYukasuke** [nix-community/home-manager#4462]
Please be patient with me, I'm new and kinda dived headfirst into flakes and home manager.

Trying to enable the ssh-agent, here's the code:

##### flake.nix
```nix
{
  description = "My Flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager/release-23.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { nixpkgs, home-manager, ... }@inputs: {
    nixosConfigurations = {
      aicornix = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          # Irrelevant code omitted
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.tsuji = import ./home;
          }
        ];
      };
    };
  };
}
```

##### home/default.nix
```nix
{ config, pkgs, ... }:

{
  # Irrelevant code omitted
  services.ssh-agent.enable = true;
}
```

I get the following error message: `error: The option 'home-manager.users.tsuji.services.ssh-agent' does not exist.`

Is home manager's option search lying to me, or am I doing this wrong?

**Comment by bnjmnt4n** [comment]
I think this is likely because you're using `release-23.05`, when this feature was only merged in recently and won't be backported to the old release. Setting `home-manager.url = "github:nix-community/home-manager";` should fix this.

**Comment by sumnerevans** [comment]
@bnjmnt4n is correct. The `services.ssh-agent` module is not in `release-23.05`. We should probably make it easier to get to the documentation for previous releases at some point, but I think a lot of people just track unstable (`master` branch) anyway.
