### ISSUE TITLE
bug: after is incorrectly defined for waybar

### ISSUE THREAD

**Issue by pshirshov** [nix-community/home-manager#4469]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

See: https://github.com/nix-community/home-manager/blob/d9b88b43524db1591fb3d9410a21428198d75d49/modules/programs/waybar.nix#L312

It must be

```
After = [ "graphical-session-pre.target" ];
```

instead of 

```
After = [ "graphical-session.target" ];
```

Current definition creates a circular dependency on itself.

### System information

```markdown
N/A
```

**Comment by rycee** [comment]
Should be fixed now, thanks for the report.
