### ISSUE TITLE
Add Nushell integration into Yazi ``programs.yazi.enableNushellIntegration``

### ISSUE THREAD

**Issue by Nyabinary** [nix-community/home-manager#4480]
### Description

Add Nushell Integration into Yazi (there is already bash & zsh integration)

**Comment by Nyabinary** [comment]
cc @XYenon

**Comment by XYenon** [comment]
I've never used Nushell. Can bash scripts be run directly on it?

**Comment by Nyabinary** [comment]
@XYenon Nope, but there is a useful guide showing what is different between bash and nushell: 
https://www.nushell.sh/book/coming_from_bash.html

**Comment by Nyabinary** [comment]
Merged
