### ISSUE TITLE
bug: hyprland startup command does not handle abruptly terminated sessions and cannot be altered

### ISSUE THREAD

**Issue by pshirshov** [nix-community/home-manager#4484]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Currently the startup command is hardcoded [here](https://github.com/nix-community/home-manager/blob/0ed5f9786bba801c59fb53eef497438040acd471/modules/services/window-managers/hyprland.nix#L199) and cannot be altered.

When hyprland crashes (or killed with SIGKILL), `hyprland-session.target` will remain in "active" state and other autorun units (e.g. waybar and everything what is autostarted and depends on waybar or `tray.target` if it's present) won't be restarted.

There are several ways to alleviate that. The generic solution would be to set the startup command to 

```
${pkgs.dbus}/bin/dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP  &&  systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
```

(please note, just `restart` is NOT enough)\\

Although, for some reason uknown to me, while such approach fixes the problem, it introduces a long delay before the autorun services are restarted (about 30 seconds). Seemingly, something might be wrong with `xdg-desktop-portal` and everything is being delayed until some timeout related to it.

In my case I found that 

```
${pkgs.dbus}/bin/dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP  &&  systemctl --user stop waybar.service && systemctl --user start hyprland-session.target
```

completely fixes the issue. Though there might be users who don't use `waybar` at all.

I think that the best idea would be to introduce a new option allowing startup command customization.

### Maintainer CC

@fufexan @ncfavier 

### System information

```markdown
N/A
```

**Comment by pshirshov** [comment]
The order matters. It can't be started in parallel.

**Comment by fufexan** [comment]
I mean started after the target, like this `&& systemctl --user start xdg-desktop-portal.service`.

**Comment by fufexan** [comment]
In my case, doing a `loginctl terminate-session self` fixes the issues you describe. Though that does not take into account crashes, so it needs to be executed after a crash as well, in order to fix the issue.

I've thought about having a script that continuously checks `pgrep Hyprland`, and when it returns `$? != 0` it should automatically terminate the session.

**Comment by pshirshov** [comment]
> I mean started after the target, like this `&& systemctl --user start xdg-desktop-portal.service`.

Nope, that doesn't help.

**Comment by pshirshov** [comment]
> In my case, doing a `loginctl terminate-session self` fixes the issues you describe. Though that does not take into account crashes, so it needs to be executed after a crash as well, in order to fix the issue.
> 
> I've thought about having a script that continuously checks `pgrep Hyprland`, and when it returns `$? != 0` it should automatically terminate the session.

The script would be killed together with all other processes in case of greetd.

The most flexible option would be to allow startup command customization.

**Comment by fufexan** [comment]
@pshirshov I've opened a PR that addresses this issue. Mind taking a look at it?

**Comment by pshirshov** [comment]
```
exec-once = /nix/store/00000000000000000000000000000000-dbus/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user stop hyprland-session.target
exec-once = systemctl --user start hyprland-session.target
```

unfortunately, this won't work because these command will be run in parallel. We have to stick with && crap. Or, maybe, generate an autostart script.

**Comment by fufexan** [comment]
That sounds good. I'm on it.

**Comment by Misterio77** [comment]
For me, `systemctl --user stop graphical-session.target` (which stuff such as waybar is bound to) and `systemctl --user start hyprland-session.target` does the trick. Perhaps this should be the default?
