### ISSUE TITLE
bug: The default tray_output for sway makes no sense

### ISSUE THREAD

**Issue by c-x-berger** [nix-community/home-manager#4488]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The default config for sway generates a `bar` block with `tray_output primary`. But [wayland (or sway, take your pick?) has no concept of a primary display](https://github.com/swaywm/sway/issues/242) so this just results in no tray anywhere.

A better default might be `*` which puts the tray on every monitor, since sway can apparently do so without issue.

(Also, is there some snippet I can put in my `home.nix` to set `config.bars` to "the default but make `trayOutput = "*"` on all of them"? I kept running into infinite recursion trying to do it naively.)

### Maintainer CC

@Scrumplex, @alexarice, @sumnerevans, @sebtm, and @oxalica

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.05 (Stoat), 23.05.20230917.5d017a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Scrumplex** [comment]
`sway-bar(5)` mentions that if the option is omitted, it will default to displaying on all outputs. So `*` would be the right default.
