### ISSUE TITLE
Force recreation of existing files

### ISSUE THREAD

**Issue by Kipari** [nix-community/home-manager#451]
I am having trouble with managing configuration files for a program (Syncthing) that forcefully deletes and recreates configuration files instead of updating them in-place, thus breaking the symbolic link to the nix store. When regenerating the environment, home-manager (rightfully) complains about conflicting files.

Is there a way of forcefully recreating these files? I know that this is sub-optimal, and I am open to alternative solutions.

**Comment by rycee** [comment]
I would in such a case make an custom activation block to force copy or link the files into place. I.e., adding something like
```nix
home.activation.copyMyFiles = config.lib.dag.entryAfter ["writeBoundary"] ''
  install -D ${./path/to/my/file} $HOME/where/i/want/it
'';
```
to your configuration.

**Comment by rycee** [comment]
@Kipari Did this fix your issue?

**Comment by Kipari** [comment]
What you posted solves my problem, but I'd prefer to have something to add to the Synthing-derivation itself; I'm trying to extend it to generate config files, which it currently does not. Is there anything like this, that can be added to the derivation itself, or should the derivation just generate the config file to some auxillary path, from which users can use `install` to copy the file? (That seems a bit sub-optimal)

(Sorry for not responding earlier!)
