### ISSUE TITLE
bug: `expire-generations`: "HM_DATA_HOME: readonly variable"

### ISSUE THREAD

**Issue by mhutter** [nix-community/home-manager#4519]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Steps to reproduce:

```sh
$ home-manager expire-generations "-30 days"
/home/XXX/.nix-profile/bin/home-manager: line 165: declare: HM_DATA_HOME: readonly variable

$ nix run home-manager/master -- expire-generations "-30 days"
/nix/store/7grhn06bkmxm6qpkfy1ar7ag9iw1f8zd-home-manager/bin/home-manager: line 165: declare: HM_DATA_HOME: readonly variable
```

This started recently (last good run was `Sat Sep 30 12:58:18 2023 +0200`).

### Maintainer CC

Probably broken in ae896c810f501bf0c3a2fd7fc2de094dd0addf01 @e-nikolov 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.5.5-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(mh): `"home-manager"`
 - channels(root): `""`
 - nixpkgs: `/nix/store/7nkxz4y8vxz5p73s6rj0j2q606a01aji-source`
```

**Comment by e-nikolov** [comment]
Probably happens because `setHomeManagerPathVariables()` is called multiple times while `HM_DATA_HOME` is readonly and can only be set once.

- `doExpireGenerations()` -> `setHomeManagerPathVariables()`
- `doExpireGenerations()` -> `doRmGenerations()` -> `setHomeManagerPathVariables()`

**Comment by rycee** [comment]
Thanks for the report, I think it should be resolved now 🙂

**Comment by mhutter** [comment]
Thanks for fixing!
