### ISSUE TITLE
bug: xplr: `cfg.plugins` does not work for more than one plugin

### ISSUE THREAD

**Issue by ChanceHarrison** [nix-community/home-manager#4520]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The implementation of `programs.xplr.plugins` does not correctly set the `package.path` in the Lua configuration file that gets written out.

The result is that users cannot enable/load any additional plugins after the first.

---
For the full context, please reference [this discussion](https://github.com/sayanarijit/xplr/discussions/668) on the upstream repository.

### Maintainer CC

@NotAShelf

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.49, NixOS, 23.11 (Tapir), 23.11.20230830.a63a64b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/flsqq53kqi52lz73n543wmxz0mbhpb52-source`
```

**Comment by NotAShelf** [comment]
not stale, PR stil needs merging
