### ISSUE TITLE
bug: `fcitx5` is not working with `qutebrowser`

### ISSUE THREAD

**Issue by toyboot4e** [nix-community/home-manager#4536]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

`fcitx5` and `fcitx5-mozc` (the IME) used to work with qutebrowser below 3.0.0, but today it doesn't show. It still works with other applications such as Firefox, Chromium and Kitty, so the switch to Qt6 on qutebrowser 3.0.0 would be relevant.

`fcitx5` installed with `configuration.nix` still works with the latest `qutebrowser`.

### What I tried

I compared the two `fcitx5.nix` files between `nixpkgs` and `home-manager` and [tried exporting `QT_PLUGIN_PATH`](https://github.com/toyboot4e/home-manager/commits/fcitx5-export-QT_PLUGIN_PATH), but it didn't solve the issue.

Edit: @Kranzes . Sorry I forgot pinging here.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11pre531102.fdd898f8f79e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager, nixos, stable-22.11, unstable"`
 - channels(tbm): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nyarla** [comment]
hi, @toyboot4e

I think, it need to install recompiled `libForQt5.fcitx5-qt` with Qt6?

In my environment (however, it in ***configuration.nix*** ), fctix5 works with this configuration, but without not:

```nix
  # this is a part of my configuration.nix

  i18n.inputMethod = {
    enabled = "fcitx5";
    fcitx5.addons = with pkgs; [
      fcitx5-gtk
      fcitx5-skk
      libsForQt5.fcitx5-qt
      # I said about this ↓
      ((libsForQt5.fcitx5-qt.override { inherit (qt6) qtbase; }).overrideAttrs
        (old: rec { cmakeFlags = old.cmakeFlags ++ [ "-DENABLE_QT6=1" ]; }))
    ];
  };
```

**Comment by nyarla** [comment]
It sorry again, I found solution about this issue.

This problem happened by qutebrowser could not find fcitx5 Qt6 plugin.
I confirm that reproduce by launch `QT_PLUGIN_PATH= qutebrowser`.

So if we could set QT_PLUGIN_PATH to valid path, this issue resolved.
For example, we could use to this method in home-manager:

```nix
{ config, pkgs, ... }: {
  home.sessionVariables.QT_PLUGIN_PATH
    = "${config.home.profileDirectory}/${pkgs.qt6.qtbase.qtPluginPrefix}";
}
```

However, persistent this method inside home-manager, it broke another Qt5 applications.

I think, if we would to resolve this issue on home-manager,
we could write to launch script or create desktop file by home-manager, per applications.

BTW: I feed that is packaging issue by upstream. anyone could report to nixpkgs?

**Comment by toyboot4e** [comment]
@nyarla Sorry for my late, reply I appreciate your help! I know you're an NixOS hacker :)

I'm not actually sure about the packaging problem. Maybe #4579 is relevant?

To my specific problem, #4468 was exactly the fix you suggested (though it had some kind of typo). I'm feeling sorry, but I would wait until it's fully resolve by them. Thank you.

**Comment by toyboot4e** [comment]
Closing as my original problem was resolved. Maybe another issue can be opened for the packaging problem.
