### ISSUE TITLE
bug: gromit-mpx module is borken due to ini file replacement by gromit-mpx

### ISSUE THREAD

**Issue by MathiasSven** [nix-community/home-manager#4537]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Currently, Gromit-MPX will replace the file `~/.config/gromit-mpx.ini` file instead of trying to write to it, thus deleting the symlink. Aside from not being able to manage the config via home-manager, this also results in having `home-manager swtich` always complaining about it, needing to delete the file manually. I have submitted a [bug report](https://github.com/bk138/gromit-mpx/issues/182) to Gromit-MPX, the author is open to a PR but I am not familiar with C, the issue seems to be the use of [`g_key_file_save_to_file`](https://github.com/bk138/gromit-mpx/blob/806baf6aa5d33ea1bbfbcda5d0ffa05acab5b669/src/config.c#L652C10-L652C33) which replaces the file instead of truncate & write.

As is, home-manager should not try to manage the config file.

### Maintainer CC

@pjones 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.5.2, NixOS, 23.11 (Tapir), 23.11pre525972.ace5093e36ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - channels(mathiassven): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pjones** [comment]
I'm not sure that I understand your use case.  If I don't answer your question sufficiently I'm happy to try again.

If you want to manage the `gromit-mpx.ini` file via Home Manager then you should *not* change settings inside the Gromit UI.  If however, you want to use the Gromit UI to change settings, you should *not* use Home Manager to set Gromit settings.  These are common use cases when configuring applications via Home Manager that also let you change settings in their UI.

In order to prevent Home Manager from managing the `gromit-mpx.ini` file, don't enable the Gromit module.  Instead, put the Gromit package in your `home.packages` list.

**Comment by MathiasSven** [comment]
I have not tried to change any settings inside Gromit-MPX, right now when I close the program, even as soon as it starts, it replaces the symlink at `~/.config/gromit-mpx.ini`. On my machine, the steps to reproduce are:
```nix
gromit-mpx = {
  enable = true;
};
```
```bash
> home-manager switch
# ...
> ls .config/gromit-mpx.ini # File is a symlink
lrwxrwxrwx 63 mathiassven users  5 Oct 15:19  .config/gromit-mpx.ini -> /nix/store/7iiyqq37s0xd22rcbqb6zvwc95gl95vp-home-manager-files/.config/gromit-mpx.ini

> gromit-mpx
# ...
^C
> ls .config/gromit-mpx.ini # File is still a symlink
lrwxrwxrwx 63 mathiassven users  5 Oct 15:19  .config/gromit-mpx.ini -> /nix/store/7iiyqq37s0xd22rcbqb6zvwc95gl95vp-home-manager-files/.config/gromit-mpx.ini
> gromit-mpx
# ...
# ALT-F9 or Quit the program via the sys trey icon
> ls .config/gromit-mpx.ini # File is replaced and no longer a symlink
.rw-r--r-- 59 mathiassven users  5 Oct 15:22  .config/gromit-mpx.ini
```

**Comment by pjones** [comment]
Ah, I see.  I was able to reproduce this by quitting Gromit and noticing that it replaced the symlink with a new file.  I have never seen it do this before, but I also never explicitly quit Gromit.

I don't think we can avoid this bug in Home Manager.  According to my notes in the Home Manager module, Gromit didn't previously write to this file if it was a symlink.  Maybe something changed upstream?

I don't really have time to submit a patch upstream to fix this.  If that changes I'll update this issue.

**Comment by MathiasSven** [comment]
Upstream has introduced a patch to accommodate for Home-Manager's use case, this should be fixed on the next release of Gromit-MPX.
