### ISSUE TITLE
bug: file.old would be clobbered by backing up file

### ISSUE THREAD

**Issue by viperML** [nix-community/home-manager#4566]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The automatic backup setting doesn't handle having a backup already in place.

Steps to reproduce:

1. Have some `file` be backed up by HM into `file.old`
2. Replace `file` again with something else.
3. HM won't be able to backup `file` into `file.old`.

This behaviour is located here: https://github.com/nix-community/home-manager/blob/d4a5076ea8c2c063c45e0165f9f75f69ef583e20/modules/files.nix#L116-L119

My suggestion: add a new option, that will force the backup, removing the old backup.

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.20231006.87828a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/g68f5abh3xhcz8xsdlfw7wkgkkcx3nwy-source`
```
```

**Comment by viperML** [comment]
CC the git blame: @nyarly

**Comment by nyarly** [comment]
The backup flag takes an option for what to backup to. I generally just change it to e.g. `old2`

**Comment by viperML** [comment]
I am using it through the NixOS module and the `backupFileExtension` option. So changing it every now and then is not an option.

**Comment by viperML** [comment]
Still an issue, everytime I boot NixOS the HM systemd service fails with this.

**Comment by snoopdouglas** [comment]
Shame this issue is stale, I've just been tripped up by it:

```
warning: the following units failed: home-manager-doug.service
× home-manager-doug.service - Home Manager environment for doug
     Loaded: loaded (/etc/systemd/system/home-manager-doug.service; enabled; preset: ignored)
     Active: failed (Result: exit-code) since Fri 2025-08-15 18:50:02 BST; 261ms ago
 Invocation: cfe19ca418c54d91b96095ad655f314d
    Process: 35292 ExecStart=/nix/store/xrz52c09p9ba8hdlcbrl9fnfg87f0w6z-hm-setup-env /nix/store/x2g3nagidbc9kbmv3yfby4yg56zdwvjd-home-manager-generation (code=exited, status=1/FAILURE)
   Main PID: 35292 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
         IO: 0B read, 0B written
   Mem peak: 5.6M
        CPU: 148ms

Aug 15 18:50:02 dusty-hugo hm-activate-doug[35394]: Please do one of the following:
Aug 15 18:50:02 dusty-hugo hm-activate-doug[35394]: - Move or remove the above files and try again.
Aug 15 18:50:02 dusty-hugo hm-activate-doug[35394]: - In standalone mode, use 'home-manager switch -b backup' to back up
Aug 15 18:50:02 dusty-hugo hm-activate-doug[35394]:   files automatically.
Aug 15 18:50:02 dusty-hugo hm-activate-doug[35394]: - When used as a NixOS or nix-darwin module, set
Aug 15 18:50:02 dusty-hugo hm-activate-doug[35394]:     'home-manager.backupFileExtension'
Aug 15 18:50:02 dusty-hugo hm-activate-doug[35394]:   to, for example, 'backup' and rebuild.
Aug 15 18:50:02 dusty-hugo systemd[1]: home-manager-doug.service: Main process exited, code=exited, status=1/FAILURE
```

Note that it isn't at all obvious here that the problem is that some backup is being clobbered, because:

- The files aren't shown, presumably because they're too far up the journal.
- I'm told to set `backupFileExtension` even though I have this set.
