### ISSUE TITLE
bug: incorrect option in manual

### ISSUE THREAD

**Issue by kacperwyczawski** [nix-community/home-manager#4589]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

> [!NOTE]
> I'm new to nixos/nix so I'm not sure if I do everything correctly.

I was following [the manual](https://nix-community.github.io/home-manager/index.html#sec-install-nixos-module) while installing home manager as NixOS module and got an error about line with [`system.stateVersion`](https://github.com/nix-community/home-manager/blob/c5c1ea85181d2bb44e46e8a944a8a3f56ad88f19/docs/installation.adoc?plain=1#L161). I replaced it with `home.stateVersion` which I found [here](https://mipmip.github.io/home-manager-option-search/?query=stateVersion) and it worked. I think that this is an error in manual, but I'm not sure.

I can open a PR if it's an error, let me know.

### Maintainer CC

Based on `git blame`:

@Artturin, @rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.56, NixOS, 23.05 (Stoat), 23.05.4407.80c1aab72515`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - channels(kacper): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Thanks for the report, it is indeed a mistake! Should be resolved now.
