### ISSUE TITLE
bug: SSH_AUTH_SOCK not set in nushell

### ISSUE THREAD

**Issue by TornaxO7** [nix-community/home-manager#4637]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have the following options saved in my hm-config:
```nix
   programs = {
       ssh.enable = true;
       nushell.enable = true;
   };

  services.ssh-agent.enable = true;
```
but I'm getting the following error message if I'm trying to ssh, for example, to push to my repository on github:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Also entering `$env.SSH_AUTH_SOCK` gives me:
```nushell
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #13:1:1]
 1 │ $env.SSH_AUTH_SOCK
   · ──┬─ ──────┬──────
   ·   │        ╰── cannot find column 'SSH_AUTH_SOCK'
   ·   ╰── value originates here
   ╰────
```

# Possible issue
The code in for the `ssh-agent` service [doesn't look like valid nushell code](https://github.com/nix-community/home-manager/blob/master/modules/services/ssh-agent.nix#L22-L26). In `nushell` you'd normally, if I'm correct (I'm still a newbie), set the value through `$env.<variable-name>`.

### Maintainer CC

@lheckemann 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231102.fa804ed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by TornaxO7** [comment]
Ok, after trying stuff out, I can't get the ssh-agent working on `zsh` as well if `gpg-agent.enableSshSupport = enable;` and the gpg-agent is enabled as well.

However, the [ssh-support-string in the gpg-agent module](https://github.com/nix-community/home-manager/blob/master/modules/services/gpg-agent.nix#L13) doesn't look like valid nushell-code as well.

**Comment by lheckemann** [comment]
I suppose it would make sense to use `home.sessionVariables` here, but I'm not sure if XDG_RUNTIME_DIR will always be set at the time of evaluation. If you want to add nushell init code to the module, I'm happy to review it :)

**Comment by TornaxO7** [comment]
hm... I can try to do that but I'm still unfamiliar with the nixos-ecosytem (I'm using NixOS for about 5 months now).

**Comment by TornaxO7** [comment]
> I suppose it would make sense to use `home.sessionVariables` here, but I'm not sure if XDG_RUNTIME_DIR will always be set at the time of evaluation. If you want to add nushell init code to the module, I'm happy to review it :)

may I ask if you know what happens with the values in `home.sessionVariables`?

**Comment by TornaxO7** [comment]
Because with my `zsh` settings I can't find the entry from `home.sessionVariables` in my `~/.zshrc`.

**Comment by gabevenberg** [comment]
#4700 only fixed this with gpg-agent, not ssh agent...

**Comment by TornaxO7** [comment]
I'm sadly not using `nushell` anymore (switched to fish) but I think this should be doable with a PR.
