### ISSUE TITLE
bug: cursor icons are placed in the wrong XDG Data subdirectory

### ISSUE THREAD

**Issue by PoQuatre** [nix-community/home-manager#4638]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The cursor icons that should be placed inside `~/.local/share/icons` are instead placed in `~/.local/share/.icons`.

From what I understand this issue probably stems from these lines :
https://github.com/nix-community/home-manager/blob/c067d57fc4552835987fd7611c3a6741ee32ebd5/modules/config/home-cursor.nix#L159-L162

### Maintainer CC

@polykernel
@league 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231102.fa804ed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by polykernel** [comment]
Thanks for catching this typo, I should have more been thorough with testing.
