### ISSUE TITLE
Support flags without associated values for `bat` config.

### ISSUE THREAD

**Issue by Anomalocaridid** [nix-community/home-manager#4657]
### Description
Currently, `programs.bat.config` assumes that flags to go in the config file all take a value. However, some flags, like `--show-all` and `--lessopen` (if the `lessopen` feature is enabled) do not take a value.

I would be up for doing a PR for this myself, but I'm not sure if the best way to implement this is to somehow adapt `programs.bat.config`, to just add another option like `programs.bat.extraConfig`, or something else entirely.

**Comment by pluiedev** [comment]
I think you can make the flag take a boolean instead, so if it's set to `true` then it will be added to the params

**Comment by pluiedev** [comment]
I actually went ahead and did this myself — was feeling like doing some OSS work today — see #4660
