### ISSUE TITLE
starship: add extraConfig

### ISSUE THREAD

**Issue by Guanran928** [nix-community/home-manager#4658]
https://github.com/nix-community/home-manager/issues/2519 (bug) might be related
### Description
Add `programs.starship.extraConfig`.
In my use case, I wanted to use a fetcher to fetch a Starship [preset](https://starship.rs/presets/toml/nerd-font-symbols.toml) from [starship.rs](https://starship.rs/presets/nerd-font.html)

Something like this:
(i have no idea what am i writing)
```nix
programs.starship.extraConfig = ''
  ${builtins.readFile (pkgs.fetchurl {
    url = "https://starship.rs/presets/toml/nerd-font-symbols.toml";
    hash = "sha256-fPmZrfhwM9NakdlJ7Y4rZ5n6JjsqXNEQ9XuFa8en9n0=";
  })}
'';
```

**Comment by pluiedev** [comment]
You can just do this via `programs.starship.settings`, no?

**Comment by Guanran928** [comment]
> You can just do this via [`programs.starship.settings`](https://nix-community.github.io/home-manager/options.html#opt-programs.starship.settings), no?

I believe you cannot use fetchers with this setting? or is there other ways to do it?

**Comment by pluiedev** [comment]
> > You can just do this via [`programs.starship.settings`](https://nix-community.github.io/home-manager/options.html#opt-programs.starship.settings), no?
> 
> I believe you cannot use fetchers with this setting? or is there other ways to do it?

You *can* use fetchers with it if you do an [import-from-derivation (IFD)](https://nixos.org/manual/nix/unstable/language/import-from-derivation), like that `readFile` + `fetchurl` combination you showed, but at that point it doesn't really matter if it's `extraConfig` or `settings` — the only difference is that with `settings` you need to also parse the config string via `fromTOML`.

IFD has quite a few drawbacks though so I wouldn't really make it my first choice. Just copy the Nerd Font preset locally — you're leaving yourself room for further customization that way anyway

**Comment by Guanran928** [comment]
Ah, `fromTOML` works, I didn't know it existed before :P
Thanks!

**Comment by Guanran928** [comment]
Update: I found `${pkgs.starship}/share/starship/presets/nerd-font-symbols.toml` :facepalm:

**Comment by pluiedev** [comment]
> Update: I found `${pkgs.starship}/share/starship/presets/nerd-font-symbols.toml` 🤦

TIL that that exists. :rofl: :+1:

**Comment by marvin-tr-81** [comment]
Very sorry to bother you but how exactly do you add this into the settings. I would appreciate an example if possible. I am still quiet new to nix. Thanks a lot.

**Comment by Guanran928** [comment]
> Very sorry to bother you but how exactly do you add this into the settings. I would appreciate an example if possible. I am still quiet new to nix. Thanks a lot.

Sure! Here's my config:
https://git.ny4.dev/nyancat/flake/src/commit/448f375e8deb25fc9413ee5f71eb5de034de2e3a/home/applications/starship/default.nix

**Comment by marvin-tr-81** [comment]
> > Very sorry to bother you but how exactly do you add this into the settings. I would appreciate an example if possible. I am still quiet new to nix. Thanks a lot.
> 
> Sure! Here's my config: https://git.ny4.dev/nyancat/flake/src/commit/448f375e8deb25fc9413ee5f71eb5de034de2e3a/home/applications/starship/default.nix

you are so kind, thanks.

**Comment by marvin-tr-81** [comment]
A quick update:

When `//` is used to merge the configs, the first one is overwritten.

Instead I use `lib.mkMerge' so that my custom config can coexist with the preset toml config.

So my final config looks like:

```
settings = lib.mkMerge [
  (builtins.fromTOML
    (builtins.readFile "${pkgs.starship}/share/starship/presets/nerd-font-symbols.toml"
  ))
  {
    # here goes my custom configurations
  }
];
```

This approach allowed me to set for example `os.disabled = false` and still retain os icons from the toml file.
