### ISSUE TITLE
bug: On fresh nix install during installation with flake: "Could not find suitable profile directory"

### ISSUE THREAD

**Issue by breezeight** [nix-community/home-manager#4674]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Step to reproduce, start a new vm on Ubuntu and do:

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
nix run home-manager/release-23.05 -- init --switch
```

And I get this error
```
Could not find suitable profile directory, tried /home/nicolabrisotto/.local/state/home-manager/profiles and /nix/var/nix/profiles/per-user/nicolabrisotto
```

Proposed solution: I think this commit on master solves the problem:
https://github.com/nix-community/home-manager/commit/ae896c810f501bf0c3a2fd7fc2de094dd0addf01

May be you could backport it on the 23.05 branch?

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-10-generic, Ubuntu, 23.10 (Mantic Minotaur), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/bxygxxbgcc7s82wn8a8wdp4gd34hiw4w-source`
```

**Comment by rycee** [comment]
Thanks for the nice report. I've created a PR for the backport.

**Comment by rycee** [comment]
@breezeight would have to confirm that it worked but for now I closed it.
