### ISSUE TITLE
bug: programs.khal fails to build because of null value

### ISSUE THREAD

**Issue by gvolpe** [nix-community/home-manager#4675]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The simplest configuration enabling `khal` results in the following build failure:

```console
       … while calling 'genCalendarStr'

         at /nix/store/6zmjz22khxi92dh43w1dp2mjadysjjy8-source/modules/programs/khal.nix:27:26:

           26|
           27|   genCalendarStr = name: value:
             |                          ^
           28|     concatStringsSep "\n" ([

       error: value is null while a set was expected
```

Here's a minimal config that builds to fail with the latest Home Manager and nixpkgs from nixos-unstable:

```nix
{ ... }:

{
  accounts.calendar.accounts.gvolpe = {
    primary = true;
    khal = {
      enable = true;
      color = "light green";
      glob = "*";
      priority = 10;
      readOnly = false;
      type = "discover";
    };
  };

  programs.khal = {
    enable = true;
    locale = { }; 
  };
}
```

Here's also a PR I made to my personal config, resulting in the same build failure on CI: https://github.com/gvolpe/nix-config/pull/246

Not sure if I'm missing something, but I feel we could do better than failing on a `null` value (e.g. using assertions).

### Maintainer CC

@Janik-Haag @DanielSiepmann @antonmosich @teto @arjan-s 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.11 (Tapir)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.05pre343321.78cd22c1b86"`
 - channels(gvolpe): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Janik-Haag** [comment]
I can try to debug this some time next week. Just looking over the code there seems to be some filter issue with an attribute that has empty values: https://github.com/nix-community/home-manager/blob/master/modules/programs/khal.nix#L185

**Comment by gvolpe** [comment]
Thansk @Janik-Haag ! Yes, and that seems to resolve to the following values, which are set in my config (the calendar bit):

```nix
  khalCalendarAccounts =
    filterAttrs (_: a: a.khal.enable) config.accounts.calendar.accounts;

  khalContactAccounts = mapAttrs (_: v: v // { type = "birthdays"; })
    (filterAttrs (_: a: a.khal.enable) config.accounts.contact.accounts);

  khalAccounts = khalCalendarAccounts // khalContactAccounts;
```

**Comment by Janik-Haag** [comment]
Sorry I didn't find time and then kinda forgot about this one :see_no_evil: 
but I updated some time ago and didn't get this error so it's probably something wrong with your config and the error message could be improved.

**Comment by 7FM** [comment]
@gvolpe, @pierrot-lc
The problem appears to be that `accounts.calendar.accounts.<name>.local` is set to null by default and khal tries to use `local.path` here: https://github.com/nix-community/home-manager/blob/1d085ea4444d26aa52297758b333b449b2aa6fca/modules/programs/khal.nix#L31
A simple fix would probably be to default initialize `accounts.calendar.accounts.<name>.local` with an empty set, not sure though if other programs might be affected by this change.
Otherwise, manually adding `local = {};` to each account in your config has the same effect.

Similarly, I am getting an `error: The option `accounts.calendar.accounts.<name>.primaryCollection' is used but not defined.`.
While the module for khal seems to consider a null value for this: https://github.com/nix-community/home-manager/blob/1d085ea4444d26aa52297758b333b449b2aa6fca/modules/programs/khal.nix#L191
The type definition of this option does not allow a null assignment.

Setting both `local = {};` and `primaryCollection = <name>;` (only for the account with `primary = true;`) manually, I no longer get a build failure.

**Comment by gvolpe** [comment]
@7FM thanks for sharing! Do you have a configuration I can look at? I was also getting this error:

```console
error: The option `accounts.calendar.basePath' is used but not defined.
```

Which is referenced here:
https://github.com/nix-community/home-manager/blob/1d085ea4444d26aa52297758b333b449b2aa6fca/modules/accounts/calendar.nix#L130

I updated [my PR](https://github.com/gvolpe/nix-config/pull/246) and it's now building. However, I can't figure out how to configure `khal` properly; it fails at runtime with the following error:

```console
$ khal calendar
critical: in section [default] gvolpe is not valid for 'default_calendar', must be one of []
If your configuration file used to work, please have a look at the Changelog to see what changed.
```

<details>
<summary>Click to expand the khal configuration that HM generates</summary>

```ini
[calendars]
[[gvolpe]]
path = /home/gvolpe/kalendar/gvolpe/*
color=light green
priority=10
type=discover

[default]
default_calendar=gvolpe
highlight_event_days=true
timedelta=5d

[locale]
dateformat=%x
datetimeformat=%c
firstweekday=0
longdateformat=%x
longdatetimeformat=%c
timeformat=%X
unicode_symbols=true
weeknumbers=off

[view]
agenda_event_format={calendar-color}{cancelled}{start-end-time-style} {title}{repeat-symbol}{reset}
```

</details>

**Comment by 7FM** [comment]
> @7FM thanks for sharing! Do you have a configuration I can look at? I was also getting this error:
> 
> ```
> error: The option `accounts.calendar.basePath' is used but not defined.
> ```

Yes I had this one as well and set `basePath = "${config.xdg.dataHome}/cal";`.

If you are going to enable `vdirsyncer` for CalDav based calendars then you will also need to add the following entries to every account:
```
          local.type = "filesystem";
          local.fileExt = ".ics";
```

> 
> Which is referenced here:
> 
> https://github.com/nix-community/home-manager/blob/1d085ea4444d26aa52297758b333b449b2aa6fca/modules/accounts/calendar.nix#L130
> 
> I updated [my PR](https://github.com/gvolpe/nix-config/pull/246) and it's now building. However, I can't figure out how to configure `khal` properly; it fails at runtime with the following error:
> 
> ```
> $ khal calendar
> critical: in section [default] gvolpe is not valid for 'default_calendar', must be one of []
> If your configuration file used to work, please have a look at the Changelog to see what changed.
> ```

I did'nt had that one though. Your config looks fine to me with a short skim.

> Do you have a configuration I can look at?

Unfortunately not yet.
I am still configuring my setup and did not push anything yet to my [config](https://github.com/7FM/nixos-dotfiles).
It should hopefully be up by the end of the week.

**Comment by Janik-Haag** [comment]
@7FM can you send a pr with your fix?

**Comment by 7FM** [comment]
> @7FM can you send a pr with your fix?

Sure thing, hopefully also by the end of this week

**Comment by teto** [comment]
can we close ?

**Comment by gvolpe** [comment]
@7FM thanks for the quick fix! 🙏🏽
