### ISSUE TITLE
bug: Unable to rebuild my system anymore if H-M enabled

### ISSUE THREAD

**Issue by SrEstegosaurio** [nix-community/home-manager#4684]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am no longer able to do a successful system rebuild and after some testing _(mainly disabling stuff and trying to rebuild again)_ I've found out that disabling `home-manager` lets me rebuild just fine. I've also tried to disable every single one of my home-manager related config files and then try to incrementally enable them but it just fails without any of them enabled.

I've tried asking several times but nobody was able to provide me with any help.

Here is the lengthy log: https://bpa.st/3SNQ

I would be sorry if this happened to be a simple user error. I've tried things but nothings seams to work.

### System information

```markdown
Cannot run this at the moment.
```

**Comment by Sntx626** [comment]
I have the same bug.
Here's my log: https://bpa.st/4LSQ

**Comment by sezryo** [comment]
I have the same bug as well.

My log: https://bpa.st/XY5Q

**Comment by Sntx626** [comment]
Looking at the logs, I think an unset (possibly new, withoug default?) option for either xdg or systemd forces the fail.

**Comment by SrEstegosaurio** [comment]
Both your logs @sezryo @Sntx626 end suspiciously with the same error message as this one https://github.com/nix-community/home-manager/pull/4579#issuecomment-1817831173. Maybe take a look there?

**Comment by SrEstegosaurio** [comment]
> Looking at the logs, I think an unset (possibly new, withoug default?) option for either xdg or systemd forces the fail.

That would mostly make sense? I can remember seeing a lot of systemd, tmpfiles et all stuff in my trace at least.

**Comment by SrEstegosaurio** [comment]
I've picked a commit from a few days ago and now everything works again.

**Comment by rycee** [comment]
@SrEstegosaurio Could you try 7af969886b0792be6d1d2c13404052e6393a8eb3 to see if it works? If it it does then I imagine it is one of the commits in https://github.com/nix-community/home-manager/pull/4579 that causes the problem. If you have the opportunity, then please do a bisect to see which specific commit introduces the issue.

**Comment by tejing1** [comment]
Just ran into someone on discord with the same issue. I believe the problem is this line:
https://github.com/nix-community/home-manager/blob/master/modules/misc/qt.nix#L163

When `qt.platformTheme` is null, this will generate an error, which the `or` will *not* catch, since the error isn't a missing attribute, but the failure to calculate an attribute.

This also evals even when the qt module is disabled, due to how `mkIf` works.

**Comment by SrEstegosaurio** [comment]
@rycee I can confirm that everything works fine with https://github.com/nix-community/home-manager/commit/7af969886b0792be6d1d2c13404052e6393a8eb3.  I'll be trying out setting `qt.platformTheme` to some value as @tejing1 suggests latter if I have the time.

Thanks for the quick responses everyone. :)

**Comment by sezryo** [comment]
@tejing1 I do have been setting ``qt.platformTheme`` (and in the counterpart in H-M as well) as ``"qt5ct"`` as always, but seems like the problem generates without difference.

**Comment by rycee** [comment]
@SrEstegosaurio Ok,thanks for the confirmation. Could you try latest master now? To see if #4677 fixed the issue…

**Comment by SrEstegosaurio** [comment]
@rycee It works just fine with latest master _(that being 1aabb0a31b25ad83cfaa37c3fe29053417cd9a0f)_. Thanks for your help and everyone involved. :)

**Comment by rycee** [comment]
Cool, so I think this can be closed? Feel free to re-open if needed.
