### ISSUE TITLE
bug: complained about "mismatched versions" on latest nixos-unstable with h-m master

### ISSUE THREAD

**Issue by oxalica** [nix-community/home-manager#4691]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After an update of both nixpkgs and home-manager, I got:
```
trace: warning: oxa profile: You are using

  Home Manager version 23.11 and
  Nixpkgs version 24.05.

Using mismatched versions is likely to cause errors and unexpected
behavior. It is therefore highly recommended to use a release of Home
Manager that corresponds with your chosen release of Nixpkgs.

If you insist then you can disable this warning by adding

  home.enableNixpkgsReleaseCheck = false;

to your configuration.
```

The version check seems to be messed up by the recent nixpkgs release branch off? Probably similar to #3033.

Says in README,
> Home Manager is developed against nixpkgs-unstable branch, which often causes it to contain tweaks for changes/packages not yet released in stable [NixOS](https://nixos.org/).

I'd consider home-manager master branch is supposed to work well with nixpkgs-unsatble and nixos-unstable branch, thus there's no actual mismatch.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05.20231122.da41de7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/khp8n05s60lckxb5fdfal09b8k31209f-source`
```

**Comment by rycee** [comment]
Should be fixed now 🙂
