### ISSUE TITLE
Yazi "extraConfig" Attribute

### ISSUE THREAD

**Issue by W-Y-R** [nix-community/home-manager#4706]
### Description
Using the “settings” attribute to configure the yazi home manager module is not optimal, as it is based on nix and has compatibility issues. A better alternative would be to implement the “extraConfig” attribute, which would allow for more adaptable and effective configuration possibilities.

### Maintainers
@XYenon 

Note: Thank you for your previous assistance with yazi. I really appreciate it.

**Comment by XYenon** [comment]
As [manual](https://nix-community.github.io/home-manager/index.html#sec-guidelines-valuable-options) say

> If the software uses a structured configuration format like a JSON, YAML, INI, TOML, or even a plain list of key/value pairs then consider using a settings option as described in [Nix RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md).

Could you give some examples of compatibility issue?

**Comment by W-Y-R** [comment]
```nix
 programs.yazi = {
        enable = true;
        enableNushellIntegration = true;
        settings = {
            manager = {
            layout         = "[ 1, 4, 3 ]";
            sort_by        = "alphabetical";
            sort_sensitive = true;
            sort_reverse   = true;
            sort_dir_first = true;
            linemode       = "size";
            show_hidden    = true;
            show_symlink   = true;
            };

            preview = {
            tab_size        = 2;
            max_width       = 600;
            max_height      = 900;
            cache_dir       = "";
            ueberzug_scale  = 1;
            ueberzug_offset = "[ 0, 0, 0, 0 ]";
            };

            tasks = {
            micro_workers = 5;
            macro_workers = 10;
            bizarre_retry = 5;
            };

            plugins = {
            preload = [];
            };

            log = {This is the code snippet that causes me trouble. Every time I try to open yazi, I get this error from nushell:
            enabled = false;
            };
        };
    };
```
    
This one above is the code snippet that causes me trouble. Every time I try to open yazi, I get this error from nushell:
```nushell
Aborted: oops, process 'yazi' core dumped
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ yazi
   · ──┬─
   ·   ╰── core dumped
   ╰────
  help: Aborted: child process 'yazi' core dumped
```
Yazi works fine if I delete the “settings” part.

**Comment by W-Y-R** [comment]
There are also a few more lines in the yazi conf file which I would love to use, but cannot as the syntax is quite hard to convert to nix, like this one:
```
[opener]
edit = [
	{ exec = '$EDITOR "$@"', block = true,  for = "unix" },
	{ exec = 'code "%*"',    orphan = true, for = "windows" },
]
open = [
	{ exec = 'xdg-open "$@"',             desc = "Open", for = "linux" },
	{ exec = 'open "$@"',                 desc = "Open", for = "macos" },
	{ exec = 'start "%1"', orphan = true, desc = "Open", for = "windows" }
]
```
I'm not sure what the advantages of the nix oriented "settings" attribute are, but, in comparison, the “extraConfig” attribute seems more convenient to use.

**Comment by Misterio77** [comment]
This should do the trick:

```
opener = {
    edit = [
                { exec = '$EDITOR "$@"'; block = true;  for = "unix"; }
                { exec = 'code "%*"';    orphan = true; for = "windows"; }
           ];
};
```

Just as a refresher:
```nix
[ 1 2 3 4 ]
```
```nix
[
  { foo = "bar"; }
  { bar = "foo"; }
]
```
JSON equivalent:
```json
[ 1, 2, 3, 4 ]
```
```json
[
  { "foo": "bar" },
  { "bar": "foo" },
]
```

The main differences are:
- Lists on nix are space-separated (as opposed to JSON commas)
- Attribute sets (equivalent to JSON objects) always have semicolons, even if they're the last element in the set (as opposed to JSON having commans, except on the last pair)

**Comment by Misterio77** [comment]
And keep in mind you can easily write TOML (or any text file, really) either inside a nix string, or including a TOML file:
```nix
{
  xdg.configFile."yazi/theme.toml".text = ''
    [foo]
    bar=true
  '';
}
```
```nix
{
  xdg.configFile."yazi/theme.toml".source = ./file-on-the-same-dir.toml;
}
```

**Comment by W-Y-R** [comment]
Hey, @Misterio77! Sorry for the notification, but I can't seem to make this work. Perhaps you might know why.
``` 
keymap = {
    manager.keymap = [
        { exec = "'shell 'dragon -x -i -T \"$1\"' --confirm'"; on = [ "<C-n>" ]; }
    ];
};
```
I've tried ```exec = "\"shell \"dragon -x -i -T \"$1\"\" --confirm\"";``` too, but that does not seem to do the trick either. Nixos rebuild works, but yazi won't accept any input for some reason. Thank you in advance!

**Comment by Misterio77** [comment]
No prob!

Maybe you have extra single quotes? As a rule of thumb, nix handles extra escaping for you, just write it as you would TOML.
If you want the TOML to look like:

```toml
exec = "shell 'dragon -x -i -T \"$1\"' --confirm"
```

This should do the trick:
```nix
exec = "shell 'dragon -x -i -T \"$1\"' --confirm"
```

Otherwise, see if you can manually make a TOML that works, and I can show you the equivalent nix :)

**Comment by W-Y-R** [comment]
This is the TOML, taken directly from Yazi Wiki:

```
{ on = [ "<C-n>" ], exec = '''
    shell 'dragon -x -i -T "$1"' --confirm
''' }
```
**References that I used:**
[Yazi Wiki](https://yazi-rs.github.io/docs/tips/)
[MyNixOS](https://mynixos.com/home-manager/option/programs.yazi.keymap)

**Comment by Misterio77** [comment]
Yeah the example I provided should work, then. If you specifically want to use multiline string like the toml example does, this is the nix equivalent:

```nix
exec = ''
  shell 'dragon -x -i -T "$1"' --confirm
'';
```

**Comment by W-Y-R** [comment]
That worked, thank you!

I realized a bit later that by setting the nixos declarative keymap option, it overwrote the nondeclarative one, so I had to convert the TOML file into nix language. 

For anyone who might find this issue in the future, you can check it below: 
[Keymap Gist](https://gist.github.com/W-Y-R/540572eef630a99684ddc51dcc0f7025)

**Comment by dmyTRUEk** [comment]
> Could you give some examples of compatibility issue?

Yazi supports lua scripting (mentioned in [yazi's tips](https://yazi-rs.github.io/docs/tips/#no-status-bar), [plugins](https://yazi-rs.github.io/docs/plugins/overview), and for example [here](https://github.com/sxyazi/yazi/discussions/532#discussioncomment-8203748)), so it would be pretty good to have option to set it from home manager.

Sure, `extraConfig` probably isn't the right name, maybe something like `extraLuaInit` would do, but probably even better solution would be to add support for arbitrary extra config files like this: `extraConfigFiles."init.lua"` (inspired by [anyrun's extraConfigFiles option](https://github.com/anyrun-org/anyrun/blob/be6728884d543665e7bd137bbef62dc1d04a210b/nix/hm-module.nix#L156), here's [how i use it](https://github.com/dmyTRUEk/nixos-config/blob/a9ccbb52477e9960c836c0ed437bbf2bfcfffd63/home-manager/programs/anyrun.nix#L34-L49)). I imagine it would work like this:
```nix
extraConfigFiles."init.lua".text = ''
    -- lua things go here
'';
```
