### ISSUE TITLE
bug: Hyprland plugin throws an error on system rebuild

### ISSUE THREAD

**Issue by LennyLizowzskiy** [nix-community/home-manager#4716]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Tried to move my plain-text setup of Hyprland to Nix via home-manager. Got an error when rebuilding my system.

Logs: https://pastebin.com/scnAja9F
Config: https://pastebin.com/GLzvYrrM

### Maintainer CC

@fufexan @andresilva 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05.20231122.19cbff5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by LennyLizowzskiy** [comment]
> There's a `plugins` option in the module itself, you don't need to use `extraConfig` for that.

![Screenshot_20231130-080341.png](https://github.com/nix-community/home-manager/assets/46971551/d31f3806-d0db-4c37-a473-e35f2f3a981e)

I just followed the readme of the module.

**Comment by LennyLizowzskiy** [comment]
@fufexan I changed `extraConfig` to `...hyprland.plugins = [ "${pkgs.hy3}/lib/libhy3.so" ];` but I get the same error

**Comment by andresilva** [comment]
You're using the home-manager module from hyprland repo (https://github.com/hyprwm/Hyprland/blob/main/nix/hm-module.nix) and not the module from home-manager. Remove `hyprland.homeManagerModules.default` from your config. If you want to use the more recent hyprland package from the hyprland repo (instead of the one from nixpkgs) you can add the hyprland overlay to your config (`nixpkgs.overlays = [ hyprland.overlays.default ]`).

**Comment by LennyLizowzskiy** [comment]
3rd party nixos modules in my config:
![image](https://github.com/nix-community/home-manager/assets/46971551/10bd04c0-04cf-4019-8d77-cb235d402fae)

3rd party home-manager modules in my config:
![image](https://github.com/nix-community/home-manager/assets/46971551/919f6057-1dba-4765-831f-dc224cafc29d)

**Comment by andresilva** [comment]
Can you comment stuff out from your config until you figure out what causes the error? Is it the plugin line? The log complains about coercing an integer to string, but looking at the config I don't see anything wrong.

**Comment by LennyLizowzskiy** [comment]
@andresilva oh, I should've done that from the start. 

`exec-once` was causing the error. Once I commented it out module worked
