### ISSUE TITLE
bug: alacritty no longer working on non-NixOS system

### ISSUE THREAD

**Issue by n8henrie** [nix-community/home-manager#4720]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Just updated to release-23.11 on an Arch Linux machine that has been running hm-installed alacritty with no issues.

Trying to run alacritty now shows:

```console
$ alacritty
Error: failed to find suitable GL configuration.
Error: "Event loop terminated with code: 1"
```

Likely related:

- https://github.com/nix-community/home-manager/issues/2251
- https://github.com/NixOS/nixpkgs/issues/9415
- https://github.com/NixOS/nixpkgs/issues/80936
- https://github.com/NixOS/nixpkgs/issues/230660
- 
### Maintainer CC

based on blame: @elkowar @ncfavier @hyperfekt 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.64-1-lts, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.1`
 - channels(root): `""`
 - channels(n8henrie): `"nixpkgs-22.11"`
 - nixpkgs: `/home/n8henrie/.nix-defexpr/channels/nixpkgs`
```

**Comment by n8henrie** [comment]
Looking into it further (in particular https://github.com/NixOS/nixpkgs/issues/230660) it looks like this is a complicated longstanding issue. Perhaps it was just by luck that it was previously working before the update?

**Comment by n8henrie** [comment]
No luck following instructions from https://nixos.org/manual/nixpkgs/unstable/#nix-on-gnulinux#4673 

```console
$ nix shell nixpkgs#alacritty nixpkgs#libglvnd nixpkgs#mesa.drivers
$ LD_LIBRARY_PATH=$(nix eval --raw nixpkgs#libglvnd)/lib:$(nix eval --raw nixpkgs#mesa.drivers)/lib alacritty
Error: failed to find suitable GL configuration.
Error: "Event loop terminated with code: 1"
```

Running with nixGL works:

```console
$ NIXPKGS_ALLOW_UNFREE=1
    nix run \
        --override-input nixpkgs nixpkgs/nixos-23.11 \
        --impure github:guibou/nixGL -- \
        nix run nixpkgs#alacritty
```

Closing as this isn't really an HM issue.

**Comment by mikefaille** [comment]
I have the same problem with kitty !

**Comment by cognivore** [comment]
Same

**Comment by DawnMagnet** [comment]
same

**Comment by 0xTheFr34k** [comment]
> No luck following instructions from https://nixos.org/manual/nixpkgs/unstable/#nix-on-gnulinux#4673
> 
> $ nix shell nixpkgs#alacritty nixpkgs#libglvnd nixpkgs#mesa.drivers
> $ LD_LIBRARY_PATH=$(nix eval --raw nixpkgs#libglvnd)/lib:$(nix eval --raw nixpkgs#mesa.drivers)/lib alacritty
> Error: failed to find suitable GL configuration.
> Error: "Event loop terminated with code: 1"
> Running with nixGL works:
> 
> $ NIXPKGS_ALLOW_UNFREE=1
>     nix run \
>         --override-input nixpkgs nixpkgs/nixos-23.11 \
>         --impure github:guibou/nixGL -- \
>         nix run nixpkgs#alacritty
> Closing as this isn't really an HM issue.

Thanks to this man for the idea what i did is just create a wrapper :
```nix
# filepath =  alacritty/default.nix
{ pkgs }:

pkgs.stdenv.mkDerivation {
  name = "alacritty-wrapped";
  dontUnpack = true;

  buildInputs = with pkgs; [ alacritty libglvnd mesa.drivers ];

  installPhase = ''
    mkdir -p $out/bin
    makeWrapper ${pkgs.alacritty}/bin/alacritty $out/bin/alacritty \
      --set LD_LIBRARY_PATH "${pkgs.libglvnd}/lib:${pkgs.mesa.drivers}/lib"
  '';

  nativeBuildInputs = [ pkgs.makeWrapper ];
}
``` 

and add this to home.nix

```nix
  home.packages = with pkgs; [
    tmux
    btop
    fzf
    lunarvim
    moreutils
    pwndbg
    git
    lazygit
    nerd-fonts.jetbrains-mono
    xsel
    cargo
    (pkgs.callPackage ./alacritty { })
  ];
```

**Comment by helios175** [comment]
@0xTheFr34k that worked for me as well. Thank you very much!
There might be a typo: the reference to alacrity.nix in home.nix should include the extension.

**Comment by helios175** [comment]
I realized that wrapping the original alacritty looses the gnome shortcut and the man configuration (I think).
So I'm trying now this approach: https://discourse.nixos.org/t/setting-an-environment-variable-for-a-single-package/15075/6 to have a "patched alacritty". I won't use overlays, just declare a package that is the same with an extended postInstall...
