### ISSUE TITLE
Users upgrading `gh` to v2.40.0 may see failures to write the config file

### ISSUE THREAD

**Issue by williammartin** [nix-community/home-manager#4744]
## Description

In `gh` v2.40.0, we are going to be releasing initial support for [multiple accounts](https://github.com/cli/cli/issues/326) on a single host. As part of this process there is a migration of on-disk data and we will be adding a `version` field with value `1` to the `config.yml` file.

I'm not too familiar with `nix` or how people use it, so I'm not sure if the following is even an expected workflow. If it is expected that you can update the version of `gh` in place without regenerating the `config.yml` file from `home-manager` scripts it is likely that users will run into an error when `gh` tries to write the `config.yml` file.

Although it's our position that `gh` manages its own configuration file, we also try not to break users that choose to configure their systems this way. Unfortunately, in this case we value the future maintainability of having this `version` to support future migrations should we need them.

As such, this is just an informative issue for people to find that this new field will be required to perform any operations with v2.40.0. Since I'm not totally sure on the workflows used in this project, here are some possible workarounds:
 1. Temporarily allow writing to `config.yml` one time so that this `version` can be written
 1. After seeing a failure, install updated `home-manager` scripts with `version: 1` declared in the config
 1. Update the `home-manager` scripts with `version: 1` declared in the config and then blow everything away and start with v2.40.0 from scratch

To me it feels like option `3` is the most sensible, since home manager enforces config to be declaratively defined up front, the only consequence will be requiring `gh auth login` to be run for any accounts that were removed when blowing it all away. However, I will again point to my ignorance in this space 😅 

We apologise for the inconvenience.

**Comment by msfjarvis** [comment]
Hm yeah that's definitely a problem. I'll give this some more thought and see if a better solution reveals itself to me.

**Comment by msfjarvis** [comment]
> Is there any way for `home-manager` to do side effects? The [migration](https://github.com/cli/cli/blob/54d56cab3a0882b43ac794df59924dc3f93bb75c/internal/config/migration/multi_account.go#L31-L69) of data is really very simple. Perhaps it could be mimic-ed here?
> 
> There's some bad yaml formatting occurring in there by `gofmt` but the gist should be clear.

There's [`onChange`](https://nix-community.github.io/home-manager/options.html#opt-home.file._name_.onChange) but it runs _after_ the config file is generated :(

**Comment by msfjarvis** [comment]
> Is that a problem? The `hosts.yml` file is unmanaged by `home-manager` (as far as I can tell) so once `config.yml` gets generated, could we use `onChange` to migrate `hosts.yml`. Instead of leaning on the `version` existing in `config.yml`, this mimiced migration could lean on whether there is a `users` key in the `hosts.yml` or something?

Hm yeah that's true, I'll give it a shot.

> 
> It might be pretty hard to write the migration though without extra tooling that can work with yaml.

Nixpkgs has the ability to at least generate YAML, I'll have to check if we can also parse it.

**Comment by Tenzer** [comment]
For people that are coming here because they encounter an error such as:
> failed to migrate configuration: failed to write config after migration: open /Users/<user>/.config/gh/config.yml: permission denied

then a workaround I've found is that I could configure `gh` like this, as a workaround for now:
```nix
programs.gh = {
  enable = true;

  settings = {
    # Workaround for https://github.com/nix-community/home-manager/issues/4744
    version = 1;

    ...
  };
};
```

The migration of `hosts.yml` has already happened at this point so there's no more manual work to be done.

**Comment by williammartin** [comment]
@Tenzer thank you for chiming in. That will indeed work and I don't think it will give you any more issues moving forwards.

@msfjarvis I thought a bit more about writing a migration and I think maybe it's not the best idea because we might end up diverged at some point. It just seems better to hash out a solution that works generally going forward. I'll speak with the team about it today as well.

**Comment by msfjarvis** [comment]
> @msfjarvis I thought a bit more about writing a migration and I think maybe it's not the best idea because we might end up diverged at some point. It just seems better to hash out a solution that works generally going forward. I'll speak with the team about it today as well.

I agree. I'm currently out on vacation so it's been harder to find time to iterate on this, but a potential solution I thought of is to introduce a `beforeChange` file hook to home-manager and run something like `gh auth status` there to force the migration and only alter the `config.yml` after. With stdout and stderr silenced it'd be transparent to users. Unfortunately I can only work on an implementation of that around Friday of this week when I get back home.

**Comment by Janik-Haag** [comment]
Hi, thanks for the heads up, I looked into it and don't really see too many options.
The least bad solution on our end would probably running the gh migration in the home-manager activation script, this would require the gh migration to be callable in a shell script, be idempotent and take less than a few seconds because it would be run every time home-manager is activated. 

Then we can add the correct version string based on `cfg.package.version` and the `config.stateVersion` in the home-manger gh module. If anyone want's to implement that, take a look at: [lib.versions.](https://noogle.dev/?term=%22lib.versions%22) and this ["example"](https://github.com/nix-community/home-manager/blob/master/modules/services/window-managers/i3-sway/lib/options.nix#L85). As you can see when running `nix eval nixpkgs#legacyPackages.x86_64-linux.gh.version` it will return the version string: `"2.40.0"`

**Comment by rycee** [comment]
In this case the ideal would be to make the module keep using the old version of gh for `stateVersion ≤ 23.11` and the newer version for later state versions. This is the exact use-case for state versions. If the user would like to upgrade, then they have to do some manual actions to migrate to the newer gh and then switch their state version.

That said, it seems like the old version of gh does not exist in Nixpkgs so I guess it needs some alternative solution.

To this end. Is it possible to detect whether the migration has happened using grep, [yq](https://github.com/mikefarah/yq), or similar? If so, then you could add a check step in the activation script. Something like:

``` nix
home.activation.checkGhV1Migration = hm.dag.entryBefore ["writeBoundary"] ''
  if grep -q "magic stuff" "$HOME/whatever"; then
    _iError $'The existing gh state files are not compatible with gh version 2.40.0.
To migrate the state please run the command suitable for your installation method:

  Channel: nix-shell <nixpkgs> -p …
  Flake:   nix run …'
    exit 1
  fi
'';
```

It is a bit drastic, perhaps, but at least it'll be clear for the user what is going on.

**Comment by varun-sal** [comment]
Is the `version` key the only thing that matters? Even if the migration is done manually by specifying the key in the config, I think there are still problems with the multiple accounts feature itself. I tried switching accounts and this failed due to a read-only file system when `config.yml` was not writable due to being managed by HM, which doesn't make sense to me because it looks like `gh` doesn't modify the `config.yml` file when switching anyway.

```
open /home/<username>/.config/gh/config.yml: read-only file system
```

**Comment by water-sucks** [comment]
Is the `version` key the only thing that matters? Even if the migration is done manually by specifying the key in the config, I think there are still problems with the multiple accounts feature itself. I tried switching accounts and this failed due to a read-only file system when `config.yml` was not writable due to being managed by HM, which doesn't make sense to me because it looks like `gh` doesn't modify the `config.yml` file when switching anyway.

```
open /home/<username>/.config/gh/config.yml: read-only file system
```

**Comment by williammartin** [comment]
> To this end. Is it possible to detect whether the migration has happened using grep, [yq](https://github.com/mikefarah/yq), or similar

Yes, in that writing the `version` key is the last thing that happens.

>  but the account itself is switched after the operation. I still think it's a weird problem that this error shows up in the first place when the operation completes successfully though.

Switching account should not result in writing the `config.yml` and I would consider this to be a bug in `gh`. That would not be acceptable behaviour in my mind for the level of support we want to provide to this community. I can't quite put the mental model together for why this would be happening but I will investigate after the holidays. Please consider creating an issue over on https://github.com/cli/cli so we can help in a structured manner.

---

All this said, I have to be honest that I did not expect this to be so problematic for the `home-manager` community and that feels bad. I have been mulling over another option here which would remove the need to write the `config.yml` file, that we could ship in January and then skip this version altogether. I won't commit to it now because we're in the holidays and I want to speak to the team, but I did want to write something here to be transparent in case people want to delay work to see how that develops.

I've also mentioned over on the [`gh` issue for this](https://github.com/cli/cli/issues/8462) that there's nothing specific about these kind of immutable configurations that we don't want to support, however, I don't want `gh` to go about it _unintentionally_ and be restricted in our ability to deliver valuable experiences (and, as you can tell from my naivety in this thread already, I don't feel equipped yet to support it intentionally). What do you think the best way to engage with this community is, to understand the goals, the size of the user base, what people here are using `gh` for, tools in the same space that might be supported in the same way, etc?

**Comment by rycee** [comment]
Looking through the comments again it seems like it wouldn't be too tricky to do the migration as part of the activation script (as suggested by @Janik-Haag. Something like

``` nix
home.activation.migrateGhAccounts =
  hm.dag.entryBetween [ "linkGeneration" ] [ "writeBoundary" ] ''
    # Check if migrated and, if not, run some command that does the migration.
  '';
```

That should make the migration run after the activation script is allowed to mutate the user environment but before the updated settings (which would include `version: 1`) are linked into place. If somebody could come up with some shell code to replace the comment, then please give it a try and, if it seems to work OK, open a PR. I promise to have a look and merge ASAP.

Since Nixpkgs unstable only has 2.40.0+ available I think we can do this migration unconditionally and not worry about looking at the package `.version` field, but if you feel like doing it I don't mind.

**Comment by williammartin** [comment]
>  If somebody could come up with some shell code to replace the comment, then please give it a try and, if it seems to work OK, open a PR. I promise to have a look and merge ASAP.

Any command will attempt to run the migration, so `gh help` is probably the simplest thing that could be done. 

I would expect something like this to work, assuming that `grep` is available and it is POSIX compliant:

```
grep --quiet 'version: "1"' <CONFIG_FILE_LOCATION> || gh help
```

This will search for the string `version: "1"` in the config file, but silencing the output. If found, then the left side evaluates to true so the right side won't be run, and if not found, then the right side would be run ensuring the migration occurs.

I'm not sure all the environments in which `home-manager` might be used but I think the above is pretty well standardised?

**Comment by rycee** [comment]
Ok, cool. I've updated the #4749 PR to include this activation script thingy. It will run `gh help` if there already exists a gh configuration file. Untested, though. It would be great if somebody could try it out and see if it works OK!

**Comment by water-sucks** [comment]
> Switching account should not result in writing the config.yml and I would consider this to be a bug in gh. That would not be acceptable behaviour in my mind for the level of support we want to provide to this community. I can't quite put the mental model together for why this would be happening but I will investigate after the holidays. Please consider creating an issue over on https://github.com/cli/cli so we can help in a structured manner.

I've created [an issue](https://github.com/cli/cli/issues/8496) there. Thanks!

**Comment by williammartin** [comment]
Amazing, thank you @msfjarvis and @rycee for the fix and everyone else for their involvement in this issue.
