### ISSUE TITLE
Option to enable program configiration without installing package

### ISSUE THREAD

**Issue by deej-io** [nix-community/home-manager#4763]
### Description

I am currently in the process of moving the configuration for a lot of programs to home-manager on Arch Linux but I'd like to continue to use the packages from the Arch repositories.

Currently, we have to `enable` the program to ensure it writes the configuration files, however this also automatically adds the package to the package list.

I was wondering if there would be any interest in a way of decoupling the configuration and installation through a top-level flag, e.g. `options.programs.installPackages`, that is defaults to `true` for backwards compatibility.

This can be used as a default value for e.g. `config.programs.git.installPackage`, which can then be used to conditionally add the package to the packages list like so:

```
config = mkIf cfg.enable (mkMerge [
  {
    mkIf cfg.installPackage {
      home.packages = [ cfg.package ];
    }
   ...
```

This gives the flexibility of a top-level default but also able to opt in/out for individual programs.

I'm happy to have a go at implementing this if there is interest.

**Comment by rycee** [comment]
No installing the package together with the configuration is generally speaking not supported or recommended since it breaks reproducibility. The typical escape hatch if you really really want, is to override the package using `pkgs.emptyDirectory`. For example,

    programs.git.package = pkgs.emptyDirectory;

**Comment by deej-io** [comment]
Thank you for the responses. That `emptyDirectory` approach seems simple enough and my desired behavior can be  trivially implemented with a helper function to conditionally set that option.

Closing this issue, but will update with the helper function code once I've gotten around to it.

Thanks again.

**Comment by mainrs** [comment]
Sorry to necro this, but this resulted from trying the same thing as OP!

I wanted to configure `fish` using home-manager without installing the binary. However, it seems that the config generation for autocompletions relies on the fact that the package is actually _not_ empty:

https://github.com/nix-community/home-manager/blob/e83414058edd339148dc142a8437edb9450574c8/modules/programs/fish.nix#L424-L446

There is no way to make this work right now, am I right? `fish` cannot be used with the above-mentioned trick of using `pkgs.emptyDirectory`.

**Comment by Lindenk** [comment]
This really should never have been closed. This behaviour is still a serious issue on any non-nixos distro (actually it's a pretty big issue on nixos as well if a system wide graphical program like hyprland is overridden by a different, incorrect version with home-manager). The `emptyDirectory` trick is a workaround that doesn't always work, such as with modules that expect the original package to exist or when dependencies and stuffed into the user's path (like python).
