### ISSUE TITLE
docs: release notes

### ISSUE THREAD

**Issue by langfingaz** [nix-community/home-manager#4778]
### Issue description

The configuration example for home-manager has this comment above `home.stateVersion`:

> You can update Home Manager without changing this value. See the Home Manager release notes for a list of state version changes in each release.

However, I could not find the release notes for e.g. home-manager 23.11. My search engine returned this link to a file which does no longer exist: https://nix-community.github.io/home-manager/release-notes.html

Where can I find the release notes? On the "Home Manager Manual" they seem to be missing. https://nix-community.github.io/home-manager/

**Comment by rycee** [comment]
@langfingaz Sorry about that, you can have a look at the unofficial location https://home-manager.dev/manual/23.11/release-notes.html#sec-release-23.11 until this is fixed.

@considerate Would you mind having a look at this? Seems we missed including the release notes after all 🙂

**Comment by considerate** [comment]
@rycee I'll have a look!

**Comment by langfingaz** [comment]
Many thanks!
