### ISSUE TITLE
bug: `programs.starship.settings` raises error for 'list of lists' setting type

### ISSUE THREAD

**Issue by dkimbel** [nix-community/home-manager#4786]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

As of last year, when [Starship added a C module](https://github.com/starship/starship/commit/0863146f072ae8382be63db26dcf9ddeff967aea), Starship has had a single instance of a 'list of lists' configuration option: the C module's `commands` setting (documented [here](https://starship.rs/config/#c)).

This seems to violate Home Manager's expectations for `programs.starship.settings`, resulting in an error. For instance, this configuration:
```
        starship = {
          enable = true;
          settings = {
            c = {
              commands = [[ "clang" "--version" ] [ "gcc" "--version" ] [ "cc" "--version" ]];
            };
          };
        };
```
Will lead to this error:
```
       error: A definition for option `home-manager.users.dk.programs.starship.settings.c.commands."[definition 1-entry 1]"' is not of type `boolean or signed integer or string or attribute set of (boolean or signed integer or string)'. Definition values:
       - In `/nix/store/a8gjlzrlss739zskkfrfbv807p9d5661-source/darwin/home-manager.nix':
           [
             "clang"
             "--version"
           ]
```

The same problem comes up when using TOML directly. For instance, you'll get the same error by setting `starship.settings = pkgs.lib.importTOML ../starship.toml;` when these are the contents of `starship.toml`:
```
[c]
commands = [ [ 'clang', '--version' ], [ 'gcc', '--version' ], [ 'cc', '--version' ] ]
```

On a more meta note: thank you for maintaining home-manager! It's been a joy to use. Sorry if this is the wrong place or format for this issue report.

Also -- my 'system information' has a rather alarming claim of 'nixpkgs: `not found`' (related to my using a flake? or nix-darwin?), but generally my setup is working.

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - nixpkgs: `not found`
```

**Comment by rennsax** [comment]
Same issues. No workaround now?
