### ISSUE TITLE
Sort the output of `home-manager packages`

### ISSUE THREAD

**Issue by ilyagr** [nix-community/home-manager#4788]
This is minor, but it is a bit annoying to have to always remember to do `home-manager packages |sort`. I can't see any reason not to do this, but let me know if there is one.

**Comment by rycee** [comment]
Don't think there was any reason for leaving it unsorted, just hasn't been brought up before. Fixed now, at least 🙂

**Comment by ilyagr** [comment]
Great, thank you very much! 😸
