### ISSUE TITLE
bug: gh breaks home-manager-$user.service

### ISSUE THREAD

**Issue by nim65s** [nix-community/home-manager#4812]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hi,

Recently (I guess since #4749), home-manager-$user.service is not starting properly with `cp: cannot stat '/home/nim/.config/gh/hosts.yml': No such file or directory`:

```
activating the configuration...
setting up /etc...
reloading user units for nim...
setting up tmpfiles
warning: the following units failed: home-manager-nim.service

× home-manager-nim.service - Home Manager environment for nim
     Loaded: loaded (/etc/systemd/system/home-manager-nim.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-12-27 09:54:19 CET; 106ms ago
   Duration: 12min 56.396s
    Process: 71038 ExecStart=/nix/store/l310dsarqxy96zpcd5j3blv2s2b5jc3g-hm-setup-env /nix/store/s14c18m0lp3ziw83bb3zczz5j58lhhsd-home-manager-generation (code=exited, status=1/FAILURE)
   Main PID: 71038 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 406ms

déc. 27 09:54:18 hattorixos systemd[1]: Starting Home Manager environment for nim...
déc. 27 09:54:18 hattorixos hm-activate-nim[71038]: Démarrage de l'activation de Home Manager
déc. 27 09:54:18 hattorixos hm-activate-nim[71038]: Activation de checkFilesChanged
déc. 27 09:54:18 hattorixos hm-activate-nim[71038]: Activation de checkLinkTargets
déc. 27 09:54:19 hattorixos hm-activate-nim[71038]: Activation de writeBoundary
déc. 27 09:54:19 hattorixos hm-activate-nim[71038]: Activation de migrateGhAccounts
déc. 27 09:54:19 hattorixos hm-activate-nim[71237]: cp: cannot stat '/home/nim/.config/gh/hosts.yml': No such file or directory
déc. 27 09:54:19 hattorixos systemd[1]: home-manager-nim.service: Main process exited, code=exited, status=1/FAILURE
déc. 27 09:54:19 hattorixos systemd[1]: home-manager-nim.service: Failed with result 'exit-code'.
déc. 27 09:54:19 hattorixos systemd[1]: Failed to start Home Manager environment for nim.
```

### Maintainer CC

@Gerschtli @berbiche @msfjarvis @rycee 

### System information

```markdown
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05pre562833.5f64a12a7289`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos, nixpkgs"`
 - channels(nim): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by msfjarvis** [comment]
Sorry about that, the file existence check [here](https://github.com/nix-community/home-manager/blob/d1d950841d230490f308f5fcf8c0d4f2bd3f24a7/modules/programs/gh.nix#L139) should've entirely prevented it. I'm investigating.

**Comment by panchoh** [comment]
> Sorry about that, the file existence check [here](https://github.com/nix-community/home-manager/blob/d1d950841d230490f308f5fcf8c0d4f2bd3f24a7/modules/programs/gh.nix#L139) should've entirely prevented it. I'm investigating.

The test is for one file `config.yml`, which I have, but the `cp` that fails is for another `hosts.yml`, which I don't.
(I just updated and it happened to me as well).
To be fair, I have `gh` configured, but haven't got around to actually use it, not even once. If using it causes the creation of the missing file, that would be why you have it and me and the OP don't :-?

At any rate, thanks for caring <3

**Comment by msfjarvis** [comment]
Ah of course, that checks out. Here's the fix https://github.com/nix-community/home-manager/pull/4813
