### ISSUE TITLE
bug:  yazi nushell integration is broken (arg passing: "Cannot convert nothing to string")

### ISSUE THREAD

**Issue by tukanoidd** [nix-community/home-manager#4822]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When running 'ya', I get this error:

```
❯ ya
Error: nu::shell::external_command

  × External command failed
     ╭─[/home/<user>/.config/nushell/config.nu:659:1]
 659 │   let tmp = $"($env.TEMP)(char path_sep)yazi-cwd." + (random chars -l 5)
 660 │   yazi $args --cwd-file $tmp
     ·        ──┬──
     ·          ╰── Cannot convert nothing to a string
 661 │   let cwd = (open $tmp)
     ╰────
  help: All arguments to an external command need to be string-compatible
```

### Maintainer CC

@XYenon 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.6.7-zen1, NixOS, 24.05 (Uakari), 24.05.20231224.5f64a12`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- channels(root): `"nixos"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tukanoidd** [comment]
Sorry, for some reason github was very buggy when putting maintainers name, i thought it was fine, but just realized it cut off part of it when posting

**Comment by tukanoidd** [comment]
I temporarily decided to fix this locally with a simple if-else statement:
```
def --env ya [args?] {
      	let tmp = $"($env.TEMP)(char path_sep)yazi-cwd." + (random chars -l 5)

        if ($args == null) {
          yazi --cwd-file $tmp
        } else {
          yazi $args --cwd-file $tmp
        }

      	let cwd = (open $tmp)
      	if $cwd != "" and $cwd != $env.PWD {
      		cd $cwd
      	}
      	rm -f $tmp
      }
```
Should I make a PR myself or let @XYenon do it? Sorry, I'm not sure what the rules here are if there is a module maintainer already. 

Also, dk if it's just my setup being borked, but I had to also manually do 
```nix
   nushell.extraEnv = ''
      $env.TEMP = /tmp
    '';
```

to ensure the env var was there, idk why, but at some point it just disappeared from the table, although all i did was do a regular `nix flake update` and `sudo nixos-rebuild ...`

**Comment by XYenon** [comment]
I think we can use `mktemp` just like other shells. The avoidance of using `mktemp` in yazi's documentation should be for the sake of compatibility with Windows.

**Comment by tukanoidd** [comment]
> I think we can use `mktemp` just like other shells. The avoidance of using `mktemp` in yazi's documentation should be for the sake of compatibility with Windows.

Been using windows for years and didn't know mktemp was a thing😅 I'll try to see what I can do when I have time, or will you do it, so we can push this change quicker, since you're the maintainer and all that? Makes no difference to me, just wanna make this work as soon as possible so anyone with this setup can benefit :)

**Comment by XYenon** [comment]
> Been using Linux for years and didn't know mktemp was a thing😅 I'll try to see what I can do when I have time, or will you do it, so we can push this change quicker, since you're the maintainer and all that? Makes no difference to me, just wanna make this work as soon as possible so anyone with this setup can benefit :)

Ok, I will make a pr soon. But I also need to wait for merge too, although I am the maintainer.

**Comment by tukanoidd** [comment]
> Ok, I will make a pr soon. But I also need to wait for merge too, although I am the maintainer.

Nice! And ye, no worries, I get the merge wait :)
