### ISSUE TITLE
bug: `programs.bat` causes activation to fail

### ISSUE THREAD

**Issue by mcwitt** [nix-community/home-manager#4826]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

With `programs.bat.enable = true`, `nixos-rebuild switch --flake .` fails during activation with the following error:

```
Dec 29 16:43:20 xxxx hm-activate-matt[587149]: Activating batCache
Dec 29 16:43:20 xxxx hm-activate-matt[587870]: error: unexpected argument '--build' found
Dec 29 16:43:20 xxxx hm-activate-matt[587870]:   tip: to pass '--build' as a value, use '-- --build'
Dec 29 16:43:20 xxxx hm-activate-matt[587870]: Usage: bat <FILE>...
Dec 29 16:43:20 xxxx hm-activate-matt[587870]: For more information, try '--help'.
```

### Maintainer CC

@lovesegfault 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05.20231224.5f64a12`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- channels(root): `"nixos"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by zoriya** [comment]
Can confirm this issue. But running bat cache --build on the cli does work, so I don't understand why it fails.

**Comment by lovesegfault** [comment]
I can't reproduce

**Comment by zoriya** [comment]
This happens on latest unstable. Did you try with unstable too?

**Comment by mcwitt** [comment]
@Diti 

> out of curiosity would you happen to also have this `nixpkgs.config.cudaSupport` option set to `true`?

hmm, I do not have `nixpkgs.config.cudaSupport` set to true in my system configuration. I do routinely use flakes which set this option to true when import nixpkgs, but that's probably not related?

**Comment by philipwilk** [comment]
This has just started occuring for me as well even though I've been using unstable for months.
![image](https://github.com/nix-community/home-manager/assets/50517631/080283a0-6969-4738-aeff-1d8adcba9381)

**Comment by aidalgol** [comment]
I've just started getting this with standalone home-manager, also tracking unstable.

**Comment by rycee** [comment]
Could somebody who has this issue check their activation script. It should have a line
```
run /nix/store/…/bin/bat cache --build
```

Could you check the version of bat, it should be included in the path or run the command with `--version`.

Also please run `/nix/store/…/bin/bat cache --help`. Hopefully some of the above will show what is going on.

**Comment by mcwitt** [comment]
I think I've figured out what's going on in my case: I have a directory `~/cache` (which in my case was created by Steam).

When `~/cache` exists, I can reproduce the failure of the command in the activation script:

```
$ mkdir ~/cache
$ /nix/store/wc8yb1n2wbkflv66nqmx536xla2bq5gf-bat-0.24.0/bin/bat cache --build
error: unexpected argument '--build' found
```

After removing `~/cache`, that command and the hm activation script finish successfully. It seems like the root of the issue is that the meaning of `bat cache` is different depending on whether the path `cache` exists in the cwd.

**Comment by rycee** [comment]
Wow, that's pretty wild. Thanks for figuring it out @mcwitt 🙂
