### ISSUE TITLE
bug: home.keyboard.options does nothing

### ISSUE THREAD

**Issue by AshleyYakeley** [nix-community/home-manager#4841]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have this in my Home Manager config, to disable the caps lock key:

    home.keyboard.options = ["caps:none"];

However, it doesn't work. [Apparently](/nix-community/home-manager/blob/master/modules/xsession.nix#L109) HM is supposed to create a oneshot user-level systemd unit called `setxkbmap` to make the call, but I'm not seeing that in `systemctl --user list-units` or in `systemctl --user list-unit-files`.

If I call `setxkbmap -option caps:none` directly it correctly disables the caps lock key, but I want Home Manager to do it.

Related: #3795, however, I am using MATE/Marco rather than Sway.

### System information

```markdown
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20231225.d02d818`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(ashley): `""`
 - nixpkgs: `not found`
```

**Comment by AshleyYakeley** [comment]
Looks like @rycee last touched this part of the code.

**Comment by stuart-warren** [comment]
I can see a user service
```
cat .config/systemd/user/setxkbmap.service 
[Install]
WantedBy=graphical-session.target

[Service]
ExecStart=/nix/store/hy9plgqdghxbx6wsn1wa2ivk17qkxkim-setxkbmap-1.3.4/bin/setxkbmap -layout 'us' -variant 'dvorak' -option '' -option 'ctrl:nocaps'
RemainAfterExit=true
Type=oneshot

[Unit]
After=graphical-session-pre.target
Description=Set up keyboard in X
PartOf=graphical-session.target
```
I can manually enable it
```
sudo systemctl enable ~/.config/systemd/user/setxkbmap.service
```
but it fails to run
```
sudo journalctl -u setxkbmap   
Jan 06 21:06:18 stuartwarren-MacBookPro systemd[1]: Starting Set up keyboard in X...
Jan 06 21:06:18 stuartwarren-MacBookPro setxkbmap[34826]: Cannot open display "default display"
Jan 06 21:06:18 stuartwarren-MacBookPro systemd[1]: setxkbmap.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 21:06:18 stuartwarren-MacBookPro systemd[1]: setxkbmap.service: Failed with result 'exit-code'.
Jan 06 21:06:18 stuartwarren-MacBookPro systemd[1]: Failed to start Set up keyboard in X.
```

**Comment by AshleyYakeley** [comment]
Interesting. I can't even see a user service.
```
$ cat .config/systemd/user/setxkbmap.service
cat: .config/systemd/user/setxkbmap.service: No such file or directory
```

**Comment by stuart-warren** [comment]
think you might need:
```
xsession = {
  enable = true;
};
```
and then somehow load the `~/.xsession` to make it work, though I configure i3 using home-manager https://nix-community.github.io/home-manager/options.xhtml#opt-xsession.windowManager.i3.enable and had to create a `/usr/share/xsession/xsession.desktop` file
```
[Desktop Entry]
Name=XSession
Comment=This session uses the custom xsession file
Exec=/etc/X11/Xsession
Type=Application
```
So it does kind of work if you do all that and manually enable the user systemd units

**Comment by AshleyYakeley** [comment]
OK, `xsession.enable = true` fixed it for me.
