### ISSUE TITLE
bug: k9s 0.29 & 0.30 breaking changes

### ISSUE THREAD

**Issue by LucasWagler** [nix-community/home-manager#4855]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

k9s [v0.29](https://github.com/derailed/k9s/releases/tag/v0.29.0) & [v0.30](https://github.com/derailed/k9s/releases/tag/v0.30.0) introduced some breaking changes.

Of note for home-manager:
- 0.29: Skin file organization changes. (A rework of the current skin option to allow definition of multiple named skins may be appropriate.)
- 0.30: Config file extensions changed from `.yml` to `.yaml`.

### Maintainer CC

@katexochen @liyangau 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.15.133.1-microsoft-standard-WSL2, NixOS, 24.05 (Uakari), 24.05.20231230.b0d36bd`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- channels(nixos): `""`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by LucasWagler** [comment]
If I find time to work on this, I'll link a draft PR here 👍

**Comment by katexochen** [comment]
Thanks @LucasWagler, I'm aware of the breaking changes but didn't had the time to work on the config yet.
