### ISSUE TITLE
bug: services.swayosd does not use the correct executable for newer swayosd versions

### ISSUE THREAD

**Issue by hweissi** [nix-community/home-manager#4857]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

SwayOSD was split up into `swayosd-client` and `swayosd-server` in [this commit](https://github.com/ErikReider/SwayOSD/commit/064ebf4bba4f6b453d5934ecfed0960d27f4a7b8).
`nixos-unstable` as well as `nixpkgs-unstable` follow a [newer commit](https://github.com/ErikReider/SwayOSD/commit/1c7d2f5b3ee262f25bdd3c899eadf17efb656d26).

The home-manager module still tries to use the old `swayosd` as executable for the service ([link](https://github.com/nix-community/home-manager/blob/26b8adb300e50efceb51fff6859a1a6ba1ade4f7/modules/services/swayosd.nix#L48)), so the service does not start (Failed to locate executable).

### Maintainer CC

@pltanton 

### System information

```markdown
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240102.bd645e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/m707dys0ykz12vnyfljx62dc6lv0hmx7-source`
```

**Comment by pltanton** [comment]
https://github.com/nix-community/home-manager/pull/4881 PR with updated binary

**Comment by ethangillengg** [comment]
Did this fix the issue? When I enable `swayosd` in home-manager like so:
```nix
services.swayosd = {
  enable = true;
};
```
I get the following output when using the CLI:
```
$ swayosd-client
Could not connect to SwayOSD Server with error: org.freedesktop.DBus.Error.ServiceUnknown: The name org.erikreider.swayosd-server was not provided by any .service files

$ swayosd-server
SwayOSD LibInput Backend isn't available, waiting...

$ sudo systemctl enable --now swayosd-libinput-backend.service
Failed to enable unit: Unit file swayosd-libinput-backend.service does not exist.
```

I think we need to wrap the `swayosd-libinput-backend.service`. Anyone else having this issue?

**Comment by ethangillengg** [comment]
> I think we need to wrap the `swayosd-libinput-backend.service`. Anyone else having this issue?

Fixed this now! For anyone else experiencing this issue, you can just ignore the error message, see [this discussion post](https://github.com/NixOS/nixpkgs/issues/280041#issuecomment-1887514586).
