### ISSUE TITLE
bug: Yazi doesn't read config

### ISSUE THREAD

**Issue by imadnyc** [nix-community/home-manager#4868]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

 Running Yazi works fine, but none of the options are being read. I checked that my config file is being evaluated - it is, especially since it is writing a symlink to `~/.config/yazi`.
 
 ```
{
programs.yazi = {
	enable = true;
	enableZshIntegration = true;
	settings = {
		manager = {
		sort_by = "alphabetical";
		show_symlink = true;
		};
	};
};
}
```

The file in `.config`

```
[manager]
show_symlink = true
sort_by = "alphabetical"
```

This may be a yazi issue, but I'm unsure because while yazi might not be reading the config, I have `enableZshIntegration = true`, and it's not working. Using `ya` does nothing, and quitting when using `yazi` just quits without bringing me to that directory. 

My nix channels in the system information below are outdated since I moved my config to flakes. My inputs are on 23.11. 

### Maintainer CC

@XYenon 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20240105.c1be43e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/store/lgwgz45xgp04xspicd2xkkhb0krq5j2a-source`
```

**Comment by XYenon** [comment]
Could you provide the output of `yazi --version`, `nix path-info "$(which yazi)"`, and the content of `~/.zshrc`?

**Comment by imadnyc** [comment]
`yazi --version` :

`yazi 0.1.5`


`nix path-info "$(which yazi)"`:

`/nix/store/mfb6k97sg729319f38id8mcgfi61gfpc-yazi-0.1.5`


`.zshrc` is empty. I manage mine using home-manager, here's the config:

```
{inputs, outputs, pkgs, config, ...}: {
  programs.zsh = {
    enable = true;
    ohMyZsh ={
      enable = true;
      theme = "robbyrussell";
    };
    promptInit = ''
      any-nix-shell zsh --info-right | source /dev/stdin
    '';
    shellAliases = {
      rebuild = "sudo nixos-rebuild switch --flake .#$DEVICENAME";
      update = "cdconfig; rebuild;";
      fullupdate = "cdconfig; sudo nix flake update; update";
      rollback = "sudo nixos-rebuild switch --rollback --flake .#$DEVICENAME";
      develop = "nix develop -c zsh";
      cdconfig = "cd ~/Documents/nix-config";
      build = "nix build";
      run = "nix run";
      check = "nix flake check";
      garbage = "sudo nix-collect-garbage -d";
      hx = "~/Documents/nix-config/scripts/helix-dark-mode.sh"; # Fix to be not impure
      search = "grep -Rnw '.' -e";
      searchip = "nmap -sP 192.168.1.0/24";
    };

  };
    #FIXME: update DEVICENAME
    environment.variables = {
    #   DEVICENAME = "nix-one";
      EDITOR = "~/Documents/nix-config/scripts/helix-dark-mode.sh";
    };
}
```

**Comment by XYenon** [comment]
> .zshrc is empty.

home-manager should create a link on `~/.zshrc`, empty is not expected.

**Comment by imadnyc** [comment]
I see, I mistakenly said that my zsh was handled by home-manager. I only configured it through nixos options - adding `programs.zsh.enable` to my home config allowed .zshrc to be written. This lets the cwd hook work, but it's still not reading the config for yazi, despite it being symlinked. 

Is there a way to write a zsh/bash function without having it explicitly being managed by home-manager? I'm not familiar enough with nix to be sure. Or, c:qan the module throw an error if it's not managed by hm?

**Comment by XYenon** [comment]
> This lets the cwd hook work, but it's still not reading the config for yazi, despite it being symlinked.

Is there any output from `echo "$XDG_CONFIG_HOME"`?

> Is there a way to write a zsh/bash function without having it explicitly being managed by home-manager?

You can add [the function](https://yazi-rs.github.io/docs/quick-start#changing-working-directory-when-exiting-yazi) to your zshrc manually.

**Comment by imadnyc** [comment]
No, I don't have any output.

**Comment by XYenon** [comment]
> I meant for the module, so that this doesn't happen for someone in the future.

I think home-manager can't automatically do this, maybe you can write some scripts to achieve.

cc @sxyazi Do you have any idea about why the config doesn't take effect?

**Comment by sxyazi** [comment]
Please do a `ls -al ~/.config/yazi` and `ls -ald ~/.config/yazi` then paste the output here.

**Comment by imadnyc** [comment]
`ls -al ~/.config/yazi`

```
total 12                                                                                                                                                                                                                                        
drwxr-xr-x   2 dre users 4096 Jan 11 23:18 .                                                                                                                                                                                                    
drwx------ 119 dre users 4096 Jan 11 17:56 ..                                                                                                                                                                                                   
lrwxrwxrwx   1 dre users   85 Jan 11 23:18 yazi.toml -> /nix/store/nrak0mwky6q128vmz62j1754l4zqi593-home-manager-files/.config/yazi/yazi.toml   
```

`ls -ald ~/.config/yazi`
```
drwxr-xr-x 2 dre users 4096 Jan 11 23:18 /home/dre/.config/yazi    
```

**Comment by sxyazi** [comment]
Then do a `cat /nix/store/nrak0mwky6q128vmz62j1754l4zqi593-home-manager-files/.config/yazi/yazi.toml` and `ls -al /nix/store/nrak0mwky6q128vmz62j1754l4zqi593-home-manager-files/.config/yazi/yazi.toml`

**Comment by imadnyc** [comment]
`cat /nix/store/nrak0mwky6q128vmz62j1754l4zqi593-home-manager-files/.config/yazi/yazi.toml`

```
[manager]                                                                                                                                                                                                                                       
show_symlink = true                                                                                                                                                                                                                             
sort_by = "alphabetical"     
```

`ls -al /nix/store/nrak0mwky6q128vmz62j1754l4zqi593-home-manager-files/.config/yazi/yazi.toml`

```
lrwxrwxrwx 3 root root 57 Dec 31  1969 /nix/store/nrak0mwky6q128vmz62j1754l4zqi593-home-manager-files/.config/yazi/yazi.toml -> /nix/store/jznm1r5jg5rgl4303fq53kbxza40yhja-yazi-settings   
```

**Comment by sxyazi** [comment]
Try changing `show_symlink` to `"wrong value"` and see if Yazi reports an error during startup, to check if the configuration file is taking effect:

```bash
[manager]
show_symlink = "wrong value"
```

**Comment by imadnyc** [comment]
Hmm, it semems like I was mistaken. Is this a yazi issue?

```
thread 'main' panicked at config/src/manager/manager.rs:31:61:                                                                                                                                                                                  
called `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "invalid sort_by value: wrong value", original: Some("[manager]\nshow_symlink = true\nsort_by = \"wrong value\"\nlayout = [1, 4, 3]\nsort_sensit
ive = true\nsort_reverse = true\nsort_dir_first = true\nlinemode = \"none\"\nshow_hidden = false\n\n[preview]\ntab_size = 2\nmax_width = 600\nmax_height = 900\ncache_dir = \"\"\n\n[[opener.edit]]\nexec = \"$EDITOR \\\"$@\\\"\"\nblock = true
\nfor = \"unix\"\n\n[[opener.edit]]\nexec = \"code \\\"%*\\\"\"\norphan = true\nfor = \"windows\"\n\n[[opener.open]]\nexec = \"xdg-open \\\"$@\\\"\"\ndesc = \"Open\"\nfor = \"linux\"\n\n[[opener.open]]\nexec = \"open \\\"$@\\\"\"\ndesc = \"
Open\"\nfor = \"macos\"\n\n[[opener.open]]\nexec = \"start \\\"%1\\\"\"\norphan = true\ndesc = \"Open\"\nfor = \"windows\"\n\n[[opener.reveal]]\nexec = \"open -R \\\"$1\\\"\"\ndesc = \"Reveal\"\nfor = \"macos\"\n\n[[opener.reveal]]\nexec = 
\"explorer /select,%1\"\norphan = true\ndesc = \"Reveal\"\nfor = \"windows\"\n\n[[opener.reveal]]\nexec = \"exiftool \\\"$1\\\"; echo \\\"Press enter to exit\\\"; read\"\nblock = true\ndesc = \"Show EXIF\"\nfor = \"unix\"\n\n[[opener.extrac
t]]\nexec = \"unar \\\"$1\\\"\"\ndesc = \"Extract here\"\nfor = \"unix\"\n\n[[opener.extract]]\nexec = \"unar \\\"%1\\\"\"\ndesc = \"Extract here\"\nfor = \"windows\"\n\n[[opener.play]]\nexec = \"mpv \\\"$@\\\"\"\norphan = true\nfor = \"uni
x\"\n\n[[opener.play]]\nexec = \"mpv \\\"%1\\\"\"\norphan = true\nfor = \"windows\"\n\n[[opener.play]]\nexec = \"mediainfo \\\"$1\\\"; echo \\\"Press enter to exit\\\"; read\"\nblock = true\ndesc = \"Show media info\"\nfor = \"unix\"\n\n[[o
pen.rules]]\nname = \"*/\"\nuse = [\"edit\", \"open\", \"reveal\"]\n\n[[open.rules]]\nmime = \"text/*\"\nuse = [\"edit\", \"reveal\"]\n\n[[open.rules]]\nmime = \"image/*\"\nuse = [\"open\", \"reveal\"]\n\n[[open.rules]]\nmime = \"video/*\"\
nuse = [\"play\", \"reveal\"]\n\n[[open.rules]]\nmime = \"audio/*\"\nuse = [\"play\", \"reveal\"]\n\n[[open.rules]]\nmime = \"inode/x-empty\"\nuse = [\"edit\", \"reveal\"]\n\n[[open.rules]]\nmime = \"application/json\"\nuse = [\"edit\", \"r
eveal\"]\n\n[[open.rules]]\nmime = \"*/javascript\"\nuse = [\"edit\", \"reveal\"]\n\n[[open.rules]]\nmime = \"application/zip\"\nuse = [\"extract\", \"reveal\"]\n\n[[open.rules]]\nmime = \"application/gzip\"\nuse = [\"extract\", \"reveal\"]
\n\n[[open.rules]]\nmime = \"application/x-tar\"\nuse = [\"extract\", \"reveal\"]\n\n[[open.rules]]\nmime = \"application/x-bzip\"\nuse = [\"extract\", \"reveal\"]\n\n[[open.rules]]\nmime = \"application/x-bzip2\"\nuse = [\"extract\", \"rev
eal\"]\n\n[[open.rules]]\nmime = \"application/x-7z-compressed\"\nuse = [\"extract\", \"reveal\"]\n\n[[open.rules]]\nmime = \"application/x-rar\"\nuse = [\"extract\", \"reveal\"]\n\n[[open.rules]]\nmime = \"*\"\nuse = [\"open\", \"reveal\"]
\n\n[tasks]\nmicro_workers = 5\nmacro_workers = 10\nbizarre_retry = 5\n\n[plugins]\npreload = []\n\n[log]\nenabled = false\n"), keys: ["manager", "sort_by"], span: Some(40..53) } } }                                                          
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace    
```

I honestly can't believe that I didn't think to do this before, LMAO.

**Comment by sxyazi** [comment]
Hmm I don't think this is an issue with Yazi itself, as it does read your configuration file and takes effect - you can try changing the value of `sort_by` to see if the order of the file list changes.

I believe your issue is with shell integration rather than a configuration problem. Please do a `which ya` to see what happens.

**Comment by imadnyc** [comment]
`which ya`

```
ya () {                                                                                                                                                                                                                                         
        tmp="$(mktemp -t "yazi-cwd.XXXXX")"                                                                                                                                                                                                     
        yazi --cwd-file="$tmp"                                                                                                                                                                                                                  
        if cwd="$(cat -- "$tmp")"  && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]                                                                                                                                                                     
        then                                                                                                                                                                                                                                    
                cd -- "$cwd"                                                                                                                                                                                                                    
        fi                                                                                                                                                                                                                                      
        rm -f -- "$tmp"                                                                                                                                                                                                                         
}                         
```

Ok, I'm thoroughly confused. I tried different sorting methods before opening this PR, and it was consistent with none of the sortings working. 

Here is my Downloads folder in nautilus, sorting by last modified.

![image](https://github.com/nix-community/home-manager/assets/113966166/c059e14a-1551-4f1b-a474-1d2f415dfa3f)

And here it is in yazi when the config is set to modified, no issues here. Of course, folders are at top, but otherwise it's sorted correctly.

![image](https://github.com/nix-community/home-manager/assets/113966166/5768d179-3c43-4594-96d4-625f41683454)


Here is my nautilus sorting by alphabetical.
![image](https://github.com/nix-community/home-manager/assets/113966166/635f1721-24ba-4ee2-84d1-a2f6b85f271c)

Here is yazi when the config is alphabetical.
![image](https://github.com/nix-community/home-manager/assets/113966166/2f4e5656-f404-4173-9c9f-e682b1cda471)

And it's... kinda alphabetical? It's reversed, first of all, and from the bottom, just looking at the files, it's alphabetical till the Win11 iso, then it wraps back around and starts a new alphabetical list? But when I do `, A` (also reverse, just to be consistent)

![image](https://github.com/nix-community/home-manager/assets/113966166/fca7fe5b-0622-4165-a73a-1d58432b5d04)

I'm unsure what's happening or what I did wrong. 

This behavior is also when the config is set to natural. Sorting when I open ya

![image](https://github.com/nix-community/home-manager/assets/113966166/ca6c2420-01fd-4a74-b439-6572360f4836)

Sorting when I do `, N`
![image](https://github.com/nix-community/home-manager/assets/113966166/d6f3b00f-9023-462c-a7de-ff5a63da707d)

**Comment by imadnyc** [comment]
Sorry, I just realized, when it's set in config, it sorts capitals first, then it does lowercase, but when I do it manually, it does it correctly. I think this may be a yazi issue, do I make an issue there?

**Comment by sxyazi** [comment]
https://github.com/sxyazi/yazi/blob/a735b3234f2da36ef9c85581b94414a5acdbd16f/yazi-config/preset/yazi.toml#L3-L6, this is Yazi's default sorting configuration.

```bash
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
```

You may need to modify some of them to meet your needs, not just `sort_by`, and the docs here, https://yazi-rs.github.io/docs/configuration/yazi#manager

> And it's... kinda alphabetical? It's reversed, first of all, and from the bottom, just looking at the files, it's alphabetical till the Win11 iso, then it wraps back around and starts a new alphabetical list? But when I do , A (also reverse, just to be consistent)

Yazi defaults to sorting in descending order by modification time. You may need to set `sort_reverse=false` in your `yazi.toml`.

**Comment by imadnyc** [comment]
Oh my god, I'm such an idiot. Thanks for being so patient! 
I assume that just making it alphabetical would be identical to the behavior found in the program. Thanks so much !
