### ISSUE TITLE
maildir-rank-addr module

### ISSUE THREAD

**Issue by RyanGibb** [nix-community/home-manager#4883]
It would be very useful to have a module for https://github.com/ferdinandyb/maildir-rank-addr to act as an address book for email clients like aerc. I can have a go at writing one if there's appetite for upstreaming it.

**Comment by teto** [comment]
you can add a HM module in your config without upstreaming it. If you are happy with it, let's upstream

**Comment by RyanGibb** [comment]
I've actually ended up doing something a bit custom with maildir-rank-addr as well as an ldap query, but something like:
```
  compose.address-book-cmd = "${pkgs.ugrep}/bin/ugrep -jPh -m 100 --color=never "$1" {config.accounts.email.maildirBasePath}/addressbook;
```

Would make sense to upstream for aerc-accounts.

**Comment by RyanGibb** [comment]
I think this is blocked on https://github.com/NixOS/nixpkgs/pull/280334 though
