### ISSUE TITLE
bug: Installation fails during active SourceHut outage

### ISSUE THREAD

**Issue by cjlarose** [nix-community/home-manager#4892]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Installation of home-manager `release-23.11` via the git repository (such as via Nix flakes) attempts to download a resource from ﻿https://git.sr.ht/~rycee/nmd, but this is unavailable due to an ongoing [SourceHut outage](https://sourcehut.org/).

The outage may continue for a while longer, so it might be nice to provide an alternative way to download these resources.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.11 (Tapir), 23.11.20231208.a47395a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rycee** [comment]
Should be resolved now. The package is taken from the binary cache instead.
