### ISSUE TITLE
bug: Standalone fails to run

### ISSUE THREAD

**Issue by PAI5REECHO** [nix-community/home-manager#4903]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

```
$ nix run github:nix-community/home-manager/846200eb574faa2af808ed02e653c2b8ed51fd71 --option eval-cache false -- init --switch
error:
       … in the right operand of the update (//) operator

         at /nix/store/db7dfj545xf35q6ia29gky48vk487s8q-source/flake.nix:128:11:

          127|           docs-manpages = docs.manPages;
          128|         } // testPackages);
             |           ^
          129|

       … while calling the 'listToAttrs' builtin

         at /nix/store/lrmxkfadhlcrakza60w0mc8sc327a5qg-source/lib/attrsets.nix:633:5:

          632|     set:
          633|     listToAttrs (map (attr: f attr set.${attr}) (attrNames set));
             |     ^
          634|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'nix-lib-nmt' missing

       at /nix/store/db7dfj545xf35q6ia29gky48vk487s8q-source/tests/default.nix:36:11:

           35|
           36| in import pkgs.nix-lib-nmt {
             |           ^
           37|   inherit lib pkgs modules;
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20231224.5f64a12`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - nixpkgs: `/nix/store/5acdh8xyry0kdvp6xla2hw7wf3zkphkl-source`
```

**Comment by rycee** [comment]
Try updating Nixpkgs.

**Comment by sreehax** [comment]
Yeah I can confirm the error still comes up when I update nixpkgs

**Comment by e-nikolov** [comment]
It's breaking my nix bootstrap CI as well - https://github.com/e-nikolov/nix-config/actions/runs/7522272306/job/20474075488

**Comment by ljuzig** [comment]
I'm on **NixOS 23.11** and I do have this issue as well.
My Home-Manager is in a separated home.nix file:
 ```
 [...]
  home-manager = builtins.fetchTarball "https://github.com/nix-community/home-manager/archive/release-23.11.tar.gz";
in
{
  imports = [
    (import "${home-manager}/nixos")
  ];
  
  [...]
```
imported in my _configuration.nix_.
Temporarily commenting the import of _home.nix_ fixes my rebuild switch.

**Comment by e-nikolov** [comment]
I think the issue is that home-manager's [flake.lock](https://github.com/nix-community/home-manager/blob/master/flake.lock#L9C17-L9C57) points to commit hash 317484b1ead87b9c1b8ac5261a8d2dd748a0492d of nixpkgs, which does not contain the nix-lib-nmd package.

So the first time someone runs home-manager via nix shell or nix run, it fails.

As a workaround until the flake.lock is updated, it should be possible to override the flake input via --override-input, e.g.

nix shell --override-input nixpkgs github:NixOS/nixpkgs/nixos-unstable home-manager/master 

or via a .follows directive in your flake.nix

```nix
inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
home-manager = {
      url = "github:nix-community/home-manager/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

outputs = {...}:{}
```

**Comment by rohanssrao** [comment]
Thank you, that worked!
I ran `nix run --override-input nixpkgs github:NixOS/nixpkgs/nixos-unstable home-manager/master -- init --switch` to successfully install Home Manager.

**Comment by supercoolspy** [comment]
Is there a way to do this with nixos-rebuild switch?
