### ISSUE TITLE
bug: rtx has been renamed to mise

### ISSUE THREAD

**Issue by AntonFriberg** [nix-community/home-manager#4909]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

rtx has been renamed to mise to avoid confusion with Nvidia's brand of graphics cards. See https://mise.jdx.dev/rtx.html for more info. Further, https://github.com/jdx/rtx now points to https://github.com/jdx/mise

nixpkgs have merged a fix https://github.com/NixOS/nixpkgs/pull/279158

Not sure how to handle a breaking change like this but programs.rtx needs some changes due to this 
https://github.com/nix-community/home-manager/blob/37d6eeceee464adc03585404eebd68765b3c8615/modules/programs/rtx.nix 

I think simply changing the links and configuration file paths should be enough but the question is how to notify users of the breaking change so that they change their project specific config files. Probably enough to reference rtx official documentation.

### Maintainer CC

@pedorich-n 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-27-amd64, Debian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - channels(afriberg): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by pedorich-n** [comment]
Thanks for the issue!
I saw the program being renamed but missed a moment when the change got merged into `nixpkgs`.
I searched for similar cases in `home-manager`, but the only PR I found is this: https://github.com/nix-community/home-manager/pull/3265. They just moved `programs` to `services`.

So, I think I can just rename the program. I will add a news entry about breaking change as well.
