### ISSUE TITLE
bug: fish functions needs to be called twice to work

### ISSUE THREAD

**Issue by leana8959** [nix-community/home-manager#4932]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I noticed that ever since my fish functions are managed with the `programs.fish.functions` options, I need to call the function twice for it to work.

Here's an example:
```sh
~
$ functions timestamp
# Defined in /home/leana/.config/fish/functions/timestamp.fish @ line 1
function timestamp
    function timestamp
        date +%s
    end
end

~
$ timestamp

~
$ timestamp
1705703205
```

Note that the function is loaded before the first time, where it does nothing. This behaviour is true for all my fish functions.

Here's my nix file for fish configuration:
https://github.com/leana8959/.files/blob/7446e49c6f46f906a8a3fd7f61d057aebca52af5/nix/home/common/fish/default.nix#L24-L53

I also have tried to write the `makeFishFunctions` function different as such (without the `body` and nested attrSet as I don't need the `event` attribute):
```nix
        makeFishFunctions = ns:
          listToAttrs
          (
            concatMap
            (n: [
              {
                name = n;
                value = readFile ./functions/${n}.fish;
              }
            ])
            ns
          );
```

I'm not sure if this is an upstream problem, though I can confirm that it was not present before nixifying my fish config.

Thank you for your time !

### Maintainer CC

@rycee @stel

### System information

```markdown
~
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 23.11 (Tapir), 23.11.20231220.d65bcea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by leana8959** [comment]
I just noticed that the way I do it creates nested functions, that explains it. Sorry for the ping and the overlook!

**Comment by rycee** [comment]
Glad you found the cause so quickly 😀
