### ISSUE TITLE
bug: services.fusuma.settings writes config w/ wrong filename

### ISSUE THREAD

**Issue by pluiedev** [nix-community/home-manager#4945]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Fusuma looks for configuration files at `~/.config/fusuma/config.yml`, not `config.yaml`. While the module currently works, it sidesteps this issue by manually specifying the path to the config, which is certainly not ideal for people like me trying to debug issues with fusuma by launching it directly.

### Maintainer CC

@iosmanthus 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.74, NixOS, 24.05 (Uakari), 24.05.20240121.612f972`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/rqdf3gfjq8zh488msnv62h03kkzr308q-source`
```

**Comment by teto** [comment]
agreed we should stick to defaults (I didn't with the notmuch module and regretted it)
