### ISSUE TITLE
bug: error on Darwin where /bin/sh can't understand exported run() bash function

### ISSUE THREAD

**Issue by purcell** [nix-community/home-manager#4950]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

As of 425672900691a16a897fc47b4d5c3013d2a822a0 by @rycee, I see many instances of the following error messages during the activation phase on Darwin:

```
/bin/sh: run: line 4: conditional binary operator expected
/bin/sh: run: line 4: syntax error near `DRY_RUN'
/bin/sh: run: line 4: ` if [[ -v DRY_RUN ]]; then'
/bin/sh: error importing function definition for `run'
```

This error message is consistent with `/bin/sh` trying to evaluate the exported `run` function from `homemanager.sh`: the conditional expression isn't recognised by the old `/bin/sh`. Illustrating that separately:

```
❯ /bin/sh
sh-3.2$ if [[ -v DRY_RUN ]]; then echo yay; fi
sh: conditional binary operator expected
sh: syntax error near `DRY_RUN'
```

I'm on the latest macOS, and the `/bin/sh` here is:
```
❯ /bin/sh --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1.2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/sl31dgnpwinzvzhh7ak2rx3h6w7kbb30-source`
```

**Comment by rycee** [comment]
Hmm, that is quite odd. I believe there should be no place where a shell script is allowed to run with a non-Nixpkgs Bash. Does it happen in a specific activation block (the X in the "Activating X" message)?

**Comment by rycee** [comment]
I wonder if the `export -f run` in https://github.com/nix-community/home-manager/blob/6359d40f6ec0b72a38e02b333f343c3d4929ec10/lib/bash/home-manager.sh#L121 could be the cause? I don't think that line is actually needed so, if you are able, could you try removing it and see if that helps?

**Comment by purcell** [comment]
I think it's in (or around) activation blocks relating to https://github.com/hraban/mac-app-util but it's hard to tell, and the code in that repo doesn't obviously run any shell scripts. (cc @hraban)

I'll see if I can test changing the `export -f run` line tomorrow.

**Comment by purcell** [comment]
Hi @hraban, I tried that fix and it does work nicely for me, thanks. It would indeed be hard to stop references to `/bin/sh` from creeping in, but I suppose prohibiting them would be an option.

**Comment by rycee** [comment]
Thanks for looking into this! I would prefer not to have to adapt to the old version of Bash. I think the best solution is simply to not expose the `run` function so that it gets called unintentionally from other scripts.

Did any of you have a chance to try it without the `export -f run` line?

**Comment by hraban** [comment]
> Did any of you have a chance to try it without the `export -f run` line?

That works fine for me, if that's a sacrifice you're willing to make I have no problem with it.
