### ISSUE TITLE
Allow enabling config for programs without adding to environment

### ISSUE THREAD

**Issue by cprussin** [nix-community/home-manager#496]
There are cases sometimes where I want to have home-manager write out a configuration file for a program, without actually adding that program to my environment.  Generally this is the case for programs I use from nix-shells for my development environments (and thus I use different versions depending on what I'm working on, and no one belongs in my nix profile), or for dependencies of things I do have in my environment.  I'd like to propose adding a boolean option to most home-manager modules that will control whether or not the package is added to the environment.  For instance:

```nix
let
    cfg = config.programs.myProgram;
in

{
    options.programs.myProgram = {
        enable = mkEnableOption "myProgram";
        addPackage = mkOption {
            type = types.boolean;
            default = true;
            description = "Add myProgram to the nix profile.";
        };
    };
    config = mkIf cfg.enable (mkMerge [
        {
            home.file.".myprogramrc" = ''
                someConfig = here
            '';
        }
        (mkIf cfg.addPackage {
            home.packages = [ packages.myProgram ];
        })
    ]);
}
```

I'm happy to put in a PR to make this change, but wanted to get feedback before I did so.  Thoughts?

**Comment by sboosali** [comment]
maybe `enableProgram` to read similarly to `enable`?

**Comment by cprussin** [comment]
Yeah, I think there's a better name here.  I don't like `enableProgram` though, because if I didn't understand this mechanism, I would guess it's just a synonym for `program.myProgram.enable`.

**Comment by rycee** [comment]
But if you're in a Nix shell that provides the package then it should appear before your user profile in the PATH. So I assume the one installed in the user profile shouldn't matter in this case.

If you absolutely don't want the package in your user profile then you could replace the package in an overlay to be an empty package. Something like
```
myProgram = super.runCommand "empty" { preferLocalBuild = true; allowSubstitutes = false; } "mkdir $out";
```
or, if the module provides a `package` option, then you could set this to the empty package.

If the module doesn't provide a `package` option then you could add one in a PR.

Alternatively use
```
home.packages = mkForce [];
```
to prevent Home Manager from installing any package and you are then free to manage the installs (if any) yourself.

**Comment by cprussin** [comment]
Yep, that works!

Fwiw the major use case here is that it just makes it slightly easier to not forget to add deps to `shell.nix` if those deps aren't unnecessarily in the env. Obviously it's better to use `--pure`, but why not both eh?

**Comment by cprussin** [comment]
@rycee so experimenting around a bit, I found the problem with the `mkForce` approach, which is that there are some things that home-manager does under the hood using `home.packages` that break when you exclude them, for instance, [session variables](https://github.com/rycee/home-manager/blob/ea7482017692d92e123b191abad2ff103280527a/modules/home-environment.nix#L289).

I'd still love to be able to use home-manager like this, so I'd be happy to put in contributions if you could provide any guidance on how you think this should be solved.

**Comment by cprussin** [comment]
Closing as this is no longer something I really care too much about.
