### ISSUE TITLE
way to remove source hut dependency

### ISSUE THREAD

**Issue by benaryorg** [nix-community/home-manager#4966]
### Related

- #4884
- #4892
- #4879
- #4024 
- #2074

### Description

I have not found a feature for this in the documentation or elsewhere.
The [problematic lines in the source code](https://github.com/nix-community/home-manager/blob/4d54c29bce71f8c261513e0662cc573d30f3e33e/docs/default.nix#L10-L13) are hard-coding source hut and since they're in a lot statement and they're not using the flake ways (either indirect or via an explicit input) I cannot override this any way.

The issue has surfaced multiple times and at least [in some instances people have asked for a way to be able to self-host/mirror this](https://github.com/nix-community/home-manager/issues/4879#issuecomment-1887123678).

I am currently unable to use home-manager even in a flake setting *at all* because source hut does not support IPv6 and the majority of my infrastructure is IPv6 only (no IPv4, not even with NAT, it's just not worth it). The way that home-manager handles this makes it *impossible* to use home-manager because it directly depends on the tarball from that specific source with no way to override.

All preceding issues, plenty at that, have been closed as the temporary failures have been dealt with, however the underlying problem persists.

At least in the flake version it should be possible to override this as a flake can declare [inputs which can easily be redirected by the user](https://git.shell.bsocat.net/infra/tree/flake.nix?id=2db98fde444e38c6d718f5be5022993239c3f7c7#n2).

**Comment by benaryorg** [comment]
A workaround for the import is to disable the entire documentation build, something along the lines of https://github.com/benaryorg/infra/commit/e0eb9365f2278a8da86198c584f7d76969a72c45:

https://github.com/benaryorg/infra/blob/e0eb9365f2278a8da86198c584f7d76969a72c45/spec/home-manager.nix#L71-L75

However that's not much of a *solution* considering it removes the entire documentation build.

**Comment by rycee** [comment]
Thanks for the report! This should be resolved with the merge of #4986. It moves the necessary files from nmd into the HM repo. So there should be no download necessary (beyond downloading HM itself). I'll close this issue, if you think there still some problem remaining then let me know and we can reopen.
