### ISSUE TITLE
bug: firefox creates a new `containers.json` on quite that is not overwritten

### ISSUE THREAD

**Issue by slotThe** [nix-community/home-manager#4989]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When configuring firefox to use container tabs, e.g.,

``` nix
programs.firfeox = {
  …
  profiles.persistent = {
    name = "persistent";
    id = 1;
    containers = {
      "foo" = {
        id    = 1;
        color = "purple";
        icon  = "chill";
      };
      …
    };
  };
}
```

Firefox does respect the containers, but it upon exit it *sometimes* seems to create the default `containers.json` file in its place.

``` console
$ cat /home/slot/.mozilla/firefox/persistent/containers.json
{"version":5,"lastUserContextId":5,"identities":[{"icon":"fingerprint","color":"blue","l10nId":"user-context-personal","public":true,"userContextId":1},{"icon":"briefcase","color":"orange","l10nId":"user-context-work","public":true,"userContextId":2},{"icon":"dollar","color":"green","l10nId":"user-context-banking","public":true,"userContextId":3},{"icon":"cart","color":"pink","l10nId":"user-context-shopping","public":true,"userContextId":4},{"public":false,"icon":"","color":"","name":"userContextIdInternal.thumbnail","accessKey":"","userContextId":5},{"userContextId":4294967295,"public":false,"icon":"","color":"","name":"userContextIdInternal.webextStorageLocal","accessKey":""}]}
```

Then on switching to a new profile I'm greeted with things like

    Existing file '/home/slot/.mozilla/firefox/persistent/containers.json' is in the way of '/nix/store/pzk1y5rz7l7r8qwzkvdwswlffsnsclp0-home-manager-files/.mozilla/firefox/persistent/containers.json'

I will try to bisect this on the weekend, as this was working until very recently

### Maintainer CC

@rycee @kira-bruneau 

### System information

```markdown
console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 24.05 (Uakari), 24.05.20240130.222c194`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/v9ndcychjpdnnxqdhkwj60brx6d0xaz9-source`
```
```

**Comment by codingCoffee** [comment]
Facing the same issue! @slotThe did you find any workaround for the same?

**Comment by slotThe** [comment]
@codingCoffee I opened https://github.com/nix-community/home-manager/pull/5057, which fixes this for me.
