### ISSUE TITLE
bug: Broken links to options manual page

### ISSUE THREAD

**Issue by jtojnar** [nix-community/home-manager#5002]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

https://nix-community.github.io/home-manager/options.html#opt-dconf.settings no longer works.

### Maintainer CC

@rycee 

### System information

```markdown
n/a
```

**Comment by rycee** [comment]
Unfortunately the pages now use a `.xhtml` suffix. See https://github.com/nix-community/home-manager/pull/4673#discussion_r1409875976 for the associated discussion. So we have had quite a few broken links. Where did you see this link?

**Comment by jtojnar** [comment]
The option links are used all over the place (e.g. on wiki, Discourse).

Would be nice to at least add a redirect.
