### ISSUE TITLE
bug: man binary from nix store used instead of /usr/bin/man on Debian

### ISSUE THREAD

**Issue by trya2l** [nix-community/home-manager#5032]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hi, 

I have recently installed nix on my debian machine with home-manager (Apparently, it is a good choice when using nix on other distros).

However, I have a (small) problem using man pages.

By default, the man binary from the nix store overtook the one in `/usr/bin`.

A quick workaround was to create an alias to `/usr/bin/man` but I was wondering if this behavior was intended ?

Thanks

### System information

```markdown
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/g09jbj92l7j0wsvnch87z93mz9s8pz4i-nix-info
copying path '/nix/store/g09jbj92l7j0wsvnch87z93mz9s8pz4i-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-18-amd64, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.1`
 - nixpkgs: `/home/allan/.nix-defexpr/channels/nixpkgs`
```

**Comment by rycee** [comment]
The [programs.man.enable](https://nix-community.github.io/home-manager/options.xhtml#opt-programs.man.enable) option is an exception in that it is enabled by default. This does cause it to install the Nixpkgs man package.

I think there are two alternatives. Add either

    programs.man.enable = false;

or

    programs.man.package = pkgs.emptyDirectory;

to your configuration. The former will entirely disable the man page functionality, including omitting the `man` outputs for those packages that have an explicit `man` output. The latter will keep the module enabled but will not actually install the `man` package.

**Comment by trya2l** [comment]
Nice, thanks 🙂
