### ISSUE TITLE
bug: error when updating flake: syntax error in `~/.local/share/home-manager/news-read-ids` when `HOME` has a trailing slash

### ISSUE THREAD

**Issue by Ruin0x11** [nix-community/home-manager#5033]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When I attempt to update my `home-manager` config I'm presented with this cryptic error:

```
$  home-manager switch --flake /etc/nixos/#nori
<...>
error: syntax error, unexpected PATH_END, expecting DOLLAR_CURLY

       at «string»:1:1:

            1| /home/nori//.local/share/home-manager/news-read-ids
             | ^
```

I think it may have to do with #4631 which has a suspiciously similar error message, but I'm not sure. Also the same issue was reported at the NixOS Discourse with the full config available: https://discourse.nixos.org/t/cryptic-error-message-after-upgrading-to-23-11/39609

My environment shows the `HOME` variable as `/home/nori/` with a trailing slash, but I wasn't sure where that was being set.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 24.05 (Uakari), 24.05.20240217.6c2492f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(nori): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ruin0x11** [comment]
I did `export HOME=/home/nori` then ran `home-manager switch --flake <...>` and the problem went away. It wasn't quite obvious to me that the `HOME` variable should not have a trailing slash. Is this user error or something that can be fixed/documented?

**Comment by ErikMcClure** [comment]
I also ran into this. Programs should not care about whether or not a path has a trailing slash, and for that matter, nothing else in nix does, nor does any other part of home-manager. This should be fixed so that it can concatenate paths properly even in the presence of a trailing slash.

**Comment by BlueDrink9** [comment]
Just ran into a similar issue with `$TMPDIR=/tmp/`. Using `TMPDIR=/tmp nix-channel --update` worked.
