### ISSUE TITLE
nix.gc.frequency - reimplement to match upstream nixos nix.gc.dates

### ISSUE THREAD

**Issue by sedlund** [nix-community/home-manager#5058]
@shivaraj-bh 

these 'special expressions' as mentioned in the systemd-time manaul are already implemented in systemd, so this is redundant, also daily is missing, and also limits the user from choosing their own setting.

https://github.com/nix-community/home-manager/blob/4ee704cb13a5a7645436f400b9acc89a67b9c08a/modules/services/nix-gc.nix#L8-L43

For consistency please just rename `frequency` to `dates` to match upstream:

https://github.com/NixOS/nixpkgs/blob/5bf1cadb72ab4e77cb0b700dab76bcdaf88f706b/nixos/modules/services/misc/nix-gc.nix#L23-L34

**Comment by sedlund** [comment]
sorry just noticed that its trying to work with darwin.  maybe istdenv.isDarwin then you pass the output of your function, if not just pass whatever the user wants?

**Comment by shivaraj-bh** [comment]
That’s right,[ I wasn’t super happy with this](https://github.com/nix-community/home-manager/pull/4973#discussion_r1477427419) either but because we had to be compatible with Darwin, [it was decided to keep it as it is](https://github.com/nix-community/home-manager/pull/4973#discussion_r1477465966) and address it in the future.

**Comment by shivaraj-bh** [comment]
We can add another option `dates` that will override frequency in linux, i.e if `dates` is not null.

**Comment by sedlund** [comment]
@shivaraj-bh what do you think of #5061

**Comment by shivaraj-bh** [comment]
Looks good!

**Comment by sedlund** [comment]
resubmitted PR for letting systemd users have full configurability as #5151 .

will close this after the the above lands in favor of #5106 for tracking the naming of the option

**Comment by sedlund** [comment]
#5151 merged
