### ISSUE TITLE
feature request: programs.firejail

### ISSUE THREAD

**Issue by bbigras** [nix-community/home-manager#506]
I guess we can't use wrappedBinaries with apps installed using home-manager.

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/firejail.nix

```
programs.firejail = {
    enable = true;
    wrappedBinaries = {
      dropbox = "${pkgs.dropbox}/bin/dropbox";
    };
  };
```

**Comment by bbigras** [comment]
I wonder if we should give up this.

I'm not 100% sure but I think I heard that firejail wasn't that good. Anyone can confirm this?

**Comment by Baitinq** [comment]
I think it'd be really cool if we could manage firejail through home-manager

**Comment by tobiasBora** [comment]
Any news on this? It may be of help to solve this issue https://discourse.nixos.org/t/automatic-firejail-of-home-managers-librewolf-does-not-work/22291 Could someone reopen the ticket?

**Comment by KaiserCalm** [comment]
Why is this a closed issue? This was never resolved. Stalebots are so horrible: https://nostalebots.xyz/
