### ISSUE TITLE
ssh: add options for IdentityAgent and IdentityFile

### ISSUE THREAD

**Issue by Mikilio** [nix-community/home-manager#5066]
### Description

Some programs use this to specify the identity of the agent. This however isn't done by `ssh-add` which causes **_the need to be set manually_** on some systems.

I'm not an expert at this, but it seems like this could even be achieved automatically because in my system that would basically be:
```
  IdentityAgent /run/user/1000/gnupg/d.31ec**************u/S.gpg-agent.ssh
  IdentityFile none
```
This is because I use ssh via gpg-agent with a YubiKey. This automatization option should probably exist under the gpg module.

I'm rather busy the next few months, so I can't dedicate my time to this otherwise I would have written a PR.

Here are some resources:

- an [example](https://developer.1password.com/docs/ssh/agent/advanced/) for an app that uses it
- [ssh_config doc](https://man.openbsd.org/ssh_config)
- [github instructions](https://docs.github.com/en/enterprise-cloud@latest/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=mac) for mac require those
- and finally [wezterm](https://wezfurlong.org/wezterm/ssh.html) can't do without them

**Comment by Mikilio** [comment]
not stale

**Comment by Mikilio** [comment]
bump it

**Comment by dudeofawesome** [comment]
I think this is a dupe of https://github.com/nix-community/home-manager/issues/4134?

**Comment by Mikilio** [comment]
In that case, I'll close it
