### ISSUE TITLE
astroid: folders for drafts and sent are set as relative paths, but astroid expects full paths

### ISSUE THREAD

**Issue by wirew0rm** [nix-community/home-manager#507]
In the astroid module, the value for save_sent_to is simply taken from accounts.email.accounts."name".folders.sent

https://github.com/rycee/home-manager/blob/e68d6e7924925b28ddd46bd7748be7aa3e5c57bd/modules/programs/astroid.nix#L17-L27

According to astroid's [configuration documentation](https://github.com/astroidmail/astroid/wiki/Configuration-Reference#accountsaccountnamesave_sent_to) an absolute Path is required (and also sync behaviour can be controlled by putting mail into different mailbox subfolders?):

> # accounts.[accountname].save_sent_to
> Type    : directory-path
> Default : /home/root/Mail/sent/cur/

But in `email.nix`, the folders.* options are supposed to be relative paths inside the mailbox:

https://github.com/rycee/home-manager/blob/e68d6e7924925b28ddd46bd7748be7aa3e5c57bd/modules/accounts/email.nix#L255-L261

The accounts.[accountname].save_drafts_to setting has the same problems.

I'm just switching to these kinds of mail setups, so I might just be missing something obvious.

Thank you,

Alex

**Comment by teto** [comment]
thanks for the detailed report. 
Either we convert these to "path" and let the burden of specifying the full path to the user or we can generate the fullpath ourselves.
The hybrid way is to detect if it's a fullpath (do nothing) or relative (complete the value ourselves). What do you think @rycee ?

`sync behaviour can be controlled by putting mail into different mailbox subfolders?` 
what do you mean ?

**Comment by wirew0rm** [comment]
> Either we convert these to "path" and let the burden of specifying the full path to the user or we can generate the fullpath ourselves.

I would prefer to specify the relative path, as other MUAs might have different options to specify folders and splitting the path later sounds like a potential error source.

> The hybrid way is to detect if it's a fullpath (do nothing) or relative (complete the value ourselves). What do you think @rycee ?

> `sync behaviour can be controlled by putting mail into different mailbox subfolders?`
> what do you mean ?

From [astroid documentation](https://github.com/astroidmail/astroid/wiki/Configuration-Reference#accountsaccountnamesave_drafts_to):
> Note that the end of the directory ends here in /cur/ which is a Maildir specific thing.

and

> Note that here the end does not contain /cur/ which in many cases has the effect that programs like mbsync will not sync your draft messages back to an IMAP server for example.

So if we implement relative Paths, we would either take this decision from the user or would have to add another option, whether "cur/" should be appended to the folder to sync it back to the server...
I only read this in astroid documentation and didn't look up any Mailbox or mbsync documentation, so no idea if "controls sync" is the best description of what is happening here. (I'm also not sure why one would not want to sync drafts to the server to complete on another device)

**Comment by teto** [comment]
sthg like that ?
```
diff --git a/modules/programs/astroid.nix b/modules/programs/astroid.nix
index 0463cd1..c74b605 100644
--- a/modules/programs/astroid.nix
+++ b/modules/programs/astroid.nix
@@ -14,15 +14,21 @@ let
 
   boolOpt = b: if b then "true" else "false";
 
-  accountAttr = account: with account; {
+
+  accountAttr = account:
+    let 
+      absPath = relPath: config.accounts.email.maildirBasePath + "/" + account.name + "/" + relPath;
+    in 
+    with account; {
     email = address;
     name = realName;
     sendmail = astroid.sendMailCommand;
     additional_sent_tags = "";
     default = boolOpt primary;
-    save_drafts_to = folders.drafts;
+    # no /cur => mbsync might not sync it ?
+    save_drafts_to = absPath folders.drafts;
     save_sent = "true";
-    save_sent_to = folders.sent;
+    save_sent_to = absPath folders.sent;
     select_query = "";
   }
   // optionalAttrs (signature.showSignature != "none") {

```

**Comment by rycee** [comment]
Sorry for the delay! Perhaps it would suffice to have
```patch
diff --git a/modules/programs/astroid.nix b/modules/programs/astroid.nix
index 0463cd1..4fa2db0 100644
--- a/modules/programs/astroid.nix
+++ b/modules/programs/astroid.nix
@@ -20,9 +20,9 @@ let
     sendmail = astroid.sendMailCommand;
     additional_sent_tags = "";
     default = boolOpt primary;
-    save_drafts_to = folders.drafts;
+    save_drafts_to = "${maildir.absPath}/${folders.drafts}";
     save_sent = "true";
-    save_sent_to = folders.sent;
+    save_sent_to = "${maildir.absPath}/${folders.sent}";
     select_query = "";
   }
   // optionalAttrs (signature.showSignature != "none") {
```
?

**Comment by jorsn** [comment]
> Perhaps it would suffice to have
> 
> ```diff
> [...]
> +    save_drafts_to = "${maildir.absPath}/${folders.drafts}";
> [...]
> +    save_sent_to = "${maildir.absPath}/${folders.sent}";
> [...]
> ```
> 
> ?

No, it won't, if you want to use the maildir correctly: You have to place the files in <folder>/new.
So the folders become:

```nix
{
save_drafts_to = "${maildir.absPath}/${folders.drafts}/new";
save_sent_to = "${maildir.absPath}/${folders.sent}/new";
}
```
. See also [save_sent_to](/astroidmail/astroid/wiki/Configuration-Reference#accountsaccountnamesave_sent_to) and [save_drafts_to](/astroidmail/astroid/wiki/Configuration-Reference#accountsaccountnamesave_drafts_to) in the the astroid config reference.
To my understanding, these mails are really newly injected into the Maildir, hence must go to the 'new' subfolder.

**Comment by teto** [comment]
I was trying to fix this but am currently blocked by https://github.com/rycee/home-manager/issues/747

**Comment by jorsn** [comment]
Where's the connection?

Do I understand correctly, that you see it in multiple mbsync channels per account for renaming sent/draft folders? But if rycee's and my solution are sufficient, which I assume, this issue requires merely a change local to the astroid config. So mbsync mechanics for folders needn't be touched in any way, if the options `maildir.absPath` and `folders.(drafts|sent)` stay there and don't change meaning.

Or maybe you see an entanglement with mbsync in the `/cur/`-question (see above)? If I understand the hint

> Note that here the end does not contain /cur/ which in many cases has the effect that programs like mbsync will not sync your draft messages back to an IMAP server for example.
-- @wirew0rm in [previous comment](#issuecomment-451977628)

correctly, then this is a totally reasonable behavior: Inside a Maildir, messages reside in `/cur/`, `new` or `tmp`. Files somewhere else are noise with unspecified behaviour. It's only consequent to not sync theese, but only regular Maildir messages. So it is no problem at all. The only issue I have with `/cur/` is what I posted above: It should be `/new/`. And mbsync syncs this.
