### ISSUE TITLE
bug: Hyprland per-device settings have unintended behaviour due to alphabetical sorting of options 

### ISSUE THREAD

**Issue by xopclabs** [nix-community/home-manager#5081]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Per-device settings in home-manager module no longer work when `name` is not the first option in alphabetical order. 
For example, this
```nix
device = {
    name = "kensington-expert-mouse";
    sensitivity = -0.2;
};
```
will result in this hyprland.conf:
```
device {
  name=kensington-expert-mouse
  sensitivity=-0.200000
}
```
and will work. But adding `accel_profile` option, for example, will make it on top and result in error message `special category's first value must be the key. Key for <device> is <name>`.
So, this nix configuration
```nix
device = {
    name = "kensington-expert-mouse";
    sensitivity = -0.2;
    accel_profile = "flat";
};
```
will alphabetically sort parametsrs and result in this hyprland.conf:
```
device {
  accel_profile=flat
  name=kensington-expert-mouse
  sensitivity=-0.200000
}
```

### Maintainer CC

@fufexan 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.7.7, NixOS, 24.05 (Uakari), 24.05.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/fpr5fsl88azrdsbzjpfq2hk307bbr7cm-source`
```

**Comment by xopclabs** [comment]
Sorry for the wrong ping there. While it's being fixed (or not), can you recommend a work-around? I've been thinking of adding a `hyprctl keyword` call in exec-once to set `accel_profile` for my trackball but haven't managed to make per-device settings to work with `hyprctl`. Of course I can just link correct .conf file config dir with home-manager but I kinda don't want to...

**Comment by fufexan** [comment]
There's a PR that should fix this https://github.com/nix-community/home-manager/pull/5038. Until it's merged you can use `extraConfig` like this:
```nix
  wayland.windowManager.hyprland.extraConfig = ''
    device {
      name=elan2841:00-04f3:31eb-touchpad
      accel_profile=custom 0.21 0.000 0.040 0.080 0.140 0.200 0.261 0.326 0.418 0.509 0.601 0.692 0.784 0.875 0.966 1.058 1.149 1.241 1.332 1.424 1.613
      natural_scroll=true
      scroll_points=0.21 0.000 0.040 0.080 0.140 0.200 0.261 0.326 0.418 0.509 0.601 0.692 0.784 0.875 0.966 1.058 1.149 1.241 1.332 1.424 1.613
    }
  '';
```

**Comment by xopclabs** [comment]
Oh, sorry, haven't checked PR's before posting. Thanks! I guess we can close it now?

**Comment by fufexan** [comment]
Let's close it when the PR gets merged, in case other people stumble upon the same issue.

**Comment by fufexan** [comment]
I think this can be closed.
