### ISSUE TITLE
Handling TERM=dumb in zsh

### ISSUE THREAD

**Issue by wedens** [nix-community/home-manager#511]
For `TERM=dumb` shell should be as simple as possible (no line-editing, no fancy prompts, no completion).

In my non-home-manager zsh config I have this code (taken from https://www.emacswiki.org/emacs/TrampMode#toc9) at the top of `.zshrc`:
```sh
if [[ "$TERM" == "dumb" ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  if whence -w precmd >/dev/null; then
      unfunction precmd
  fi
  if whence -w preexec >/dev/null; then
      unfunction preexec
  fi
  PS1='$ '
  return
fi
```
I'm not sure how to incorporate it in zsh configured by home-manager. 

I can make a PR with this code behind a configuration option (off by default) if it seems like a reasonable thing to add.

**Comment by kalbasit** [comment]
You should use [`programs.zsh.initExtra`](https://github.com/rycee/home-manager/blob/40b3443c8f2e94ae5b8f6e1cf1e973f3b5ee8e2a/modules/programs/zsh.nix#L196-L200) for that.

```nix
programs.zsh.initExtra = ''
	if [[ "$TERM" == "dumb" ]]
	then
		unsetopt zle
		unsetopt prompt_cr
		unsetopt prompt_subst
		if whence -w precmd >/dev/null; then
				unfunction precmd
		fi
		if whence -w preexec >/dev/null; then
				unfunction preexec
		fi
		PS1='$ '
		return
	fi
'';
```

**Comment by uvNikita** [comment]
If this is something standard and will not break anything, it might make sense to add this lines unconditionally to zsh module. Alternatively, it seems like it might be just easier to use bash (or even `/bin/sh`) for this, from the wiki you linked:

> None of the above worked for me so I decided to just change the SHELL environment variable. There is no added benefit from running zsh inside tramp anyway.
> 
>   (eval-after-load 'tramp '(setenv "SHELL" "/bin/bash"))
> 
> --EzeBirman

**Comment by wedens** [comment]
> Alternatively, it seems like it might be just easier to use bash (or even /bin/sh) for this, from the wiki you linked

It'll set local SHELL variable. No idea what the author meant.

> If this is something standard and will not break anything,

I think it's pretty safe to have those lines by default.

**Comment by CarlOlson** [comment]
I also have something like this:
```
[ $TERM = "dumb" ] && unsetopt zle && PS1='$ '
```

Looks like I probably copied from the TRAMP wiki, but others programs seem to use it:
https://stackoverflow.com/questions/39001517/features-obligatory-for-term-dumb-terminal

Does it make sense to revert variables or just call `exec sh`? Either way, maybe controlled via a configuration variable? `programs.zsh.execShWhenDumb = true;`, `programs.zsh.skipConfigWhenDumb = true;`, or `dumbShell = "sh";`?

**Comment by wedens** [comment]
Seems like currently "dumbifying" code with early exit can be added to `initExtraBeforeCompInit`.
