### ISSUE TITLE
FR: Mosh module

### ISSUE THREAD

**Issue by AkechiShiro** [nix-community/home-manager#5111]
### Description

Hi, I would like to be able to enable [Mosh](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/programs/mosh.nix) in home-manager.

A module is already written upstream, but I prefer to use Home Manager for Non-NixOS systems.

**Comment by ambroisie** [comment]
Other than installing the package, I don't see what home-manager can do (firewall and setuid binaries are system-level concepts).

Because of that, I don't see the point of a module.

**Comment by AkechiShiro** [comment]
I believe you are correct I'm closing this request @ambroisie
