### ISSUE TITLE
bug: online accounts config doesn't play well with gnome apps

### ISSUE THREAD

**Issue by balintbarna** [nix-community/home-manager#5113]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Maybe this is halfway between a bug and a feature request, but I would treat it as a bug because the expected behavior based on the configuration options is different than the current behavior.

I use the modern Gnome suit for mail, calendar and contacts, that is Geary, Gnome Calendar and Gnome Contacts.
Geary has it's own UI to configure a mail account and it also works with the "Online accounts" part of the OS settings, both for special providers like google and for custom imap/smtp accounts. The calendar and contacts apps don't seem to have a UI for connecting to a cal/carddav account, but they work with the special accounts like google from the online accounts settings.

Since I use a custom provider for multiple accounts which work with imap/smtp, caldav and carddav, I'm currently using the online accounts settings for the email setup and Evolution to configure calendar and contacts. Evolution can set up a "collection account" which includes both calendar and contacts for one account.

This is a quite annoying and manual configuration process that doesn't work too well. When I saw the accounts options in home manager, it seemed obvious to me that it is there to provide a solution for these scenarios, but it seems that after adding my configuration, although I haven't set the password command up yet, my configuration builds but my accounts don't show up anywhere, not in settings, geary, calendar, contacts, or evolution.

I'm not sure if these options were meant to do what I describe here, but I think it would make a lot of sense.

### Maintainer CC

@7FM  @felipeqq2  @bclement-ocp 

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/10i1kjjq5szjn1gp6418x8bc1hswqc90-stdenv-linux
copying path '/nix/store/10i1kjjq5szjn1gp6418x8bc1hswqc90-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.13, NixOS, 23.11 (Tapir), 23.11.20240308.2be119a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by felipeqq2** [comment]
Currently, the `accounts` options don't have support for GNOME calendar/contacts. The only apps with support for calendar accounts are khal, qcal and vdirsyncer, AFAIK.

It _may_ be possible to declaratively configure gnome accounts via [dconf](https://help.gnome.org/admin/system-admin-guide/stable/dconf.html.en). Home-manager does have support for it (see [manual](https://nix-community.github.io/home-manager/options.xhtml#opt-dconf.settings)).

**Comment by balintbarna** [comment]
Closing as not really a bug and there is no clear solution in sight.

**Comment by valyntyler** [comment]
I'd also love for `accounts.calendar.accounts` to be more integrated with gnome online accounts and the `gnome-calendar` app
