### ISSUE TITLE
Add module for hypridle

### ISSUE THREAD

**Issue by cloudlena** [nix-community/home-manager#5126]
https://github.com/hyprwm/hypridle

It would be awesome to have this available as `services.hypridle` and be able to configure it via home manager.

**Comment by LilleAila** [comment]
If you use flakes, it's already possible to do this using the [flake from the repo](https://github.com/hyprwm/hypridle). The module is defined [here](https://github.com/hyprwm/hypridle/blob/main/nix/hm-module.nix). You can add `hyprlock.url = "github:hyprwm/hyprlock"` to the inputs, and do something like [this](https://github.com/LilleAila/dotfiles/blob/f958b0243327a7c8ee660f74e4ad8e900029d477/home/programs/wm/wayland/hypridle.nix) or [this](https://github.com/fufexan/dotfiles/blob/main/home/services/wayland/hypridle.nix) to configure it.

**Comment by cloudlena** [comment]
Fixed by https://github.com/nix-community/home-manager/commit/fdaaf543bad047639ef0b356ea2e6caec2f1215c
