### ISSUE TITLE
bug: pinentry-related modules broken

### ISSUE THREAD

**Issue by musjj** [nix-community/home-manager#5135]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

```bash
error: A definition for option `home-manager.users.$USER.services.gpg-agent.pinentryFlavor' is not of type `null or one of "curses", "gtk2", "gnome2", "qt", "emacs"'. Definition values:
- In `/nix/store/c7a7yvmwnv9p9basdl89vxbnbaa8ppyj-source/gpg.nix': "gnome3"
```

It looks like they did a refactor of `pinentry` upstream, but I'm not sure how it works. It seems that the `pinentry` package doesn't exist anymore and it's replaced by `pinentry-{gnome3,qt,...}`. But then why does this definition not error out?:

```nix
type = types.nullOr (types.enum pkgs.pinentry.flavors);
```

### Maintainer CC

@rycee
@ambroisie

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.19, NixOS, 24.05 (Uakari), 24.05.20240306.9df3e30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/gig8j85kj7ybjy3ksn6k3aich8j2k59y-source`
```

**Comment by musjj** [comment]
Ah, this has been fixed upstream: https://github.com/NixOS/nixpkgs/pull/294937
Just need to wait for it to reach `nixos-unstable`: https://nixpk.gs/pr-tracker.html?pr=294937

**Comment by ambroisie** [comment]
@rycee yes I think so.

**Comment by SebTM** [comment]
#5139 fixes a follow up problem then it can be closed from my POV

**Comment by yshui** [comment]
#4895 causes this error:

```
    error: undefined variable 'pinentryPackage'
       at /nix/store/kww2vp5mhnvb0mczv2xll0m5qsrjrw9q-source/modules/services/gpg-agent.nix:251:42:
          250|           ++ optional (cfg.pinentryPackage != null)
          251|           "pinentry-program ${lib.getExe pinentryPackage}"
             |                                          ^
          252|           ++ [ cfg.extraConfig ]);
```

**Comment by SebTM** [comment]
Resolved and merged
