### ISSUE TITLE
bug: espanso not able to execute command

### ISSUE THREAD

**Issue by pbek** [nix-community/home-manager#5145]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm using and loving home-manager also for configuring [espanso](https://github.com/nix-community/home-manager/blob/master/modules/services/espanso.nix), which works great.

When using a global var, like:

```nix
          global_vars = [
            {
              name = "quote";
              type = "shell";
              params = {
                cmd = "nix-shell -p neo-cowsay --run \"curl -s 'https://zenquotes.io/api/random' | jq -r '.[0].q' | cowthink\"";
              };
            }
          ];
```

(see https://github.com/pbek/nixcfg/blob/8cee700aa66a1cd01365f7a91752b1a28d39e60d/modules/mixins/espanso.nix#L40-L49)

I get an error: `[Espanso]: An error occurred during rendering, please examine the logs for more information.` instead on the text replacement.

The espanso log says:

```
14:32:22 [worker(4943)] [WARN] extension 'shell' on var: 'quote' reported an error: could not execute command: '`nix-shell -p neo-cowsay --run "curl -s 'https://zenquotes.io/api/random' | jq -r '.[0].q' | cowthink"`', error: '`No such file or directory (os error 2)`'
14:32:22 [worker(4943)] [ERROR] error during rendering: rendering error

Caused by:
    could not execute command: '`nix-shell -p neo-cowsay --run "curl -s 'https://zenquotes.io/api/random' | jq -r '.[0].q' | cowthink"`', error: '`No such file or directory (os error 2)`'
```

I also get the same error when I just try to execute a shell script instead.

The "`" is puzzling me, are there some extra quotes added by home-manager, that espanso doesn't understand?

### Maintainer CC

@bobvanderlinden
@lucasew
@liyangau

### System information

```markdown
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240312.0ad13a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/run/current-system/nixpkgs`
```

**Comment by pbek** [comment]
I tried with the latest espanso 2.2.1, as well as with 2.1.8 from https://github.com/NixOS/nixpkgs/blob/nixos-unstable/.

**Comment by bobvanderlinden** [comment]
I presume the yaml looks alright.

Im a bit skeptic about the use of nix-shell here. It should be needed and jq and curl are not part of the packages included (which could explain no such file errors).

```
cmd = "${pkgs.curl}/bin/curl -s https://zenquotes.io/api/random | ${pkgs.jq}/bin/jq -r '.[0].q' | ${pkgs.neo-cowsay}/bin/cowthink";
```

If this doesn't work I'd take a look at the yaml configuration files and check whether that is valid config for espanso.

**Comment by lucasew** [comment]
> I presume the yaml looks alright.
> 
> Im a bit skeptic about the use of nix-shell here. It should be needed and jq and curl are not part of the packages included (which could explain no such file errors).
> 
> ```
> cmd = "${pkgs.curl}/bin/curl -s https://zenquotes.io/api/random | ${pkgs.jq}/bin/jq -r '.[0].q' | ${pkgs.neo-cowsay}/bin/cowthink";
> ```
> 
> If this doesn't work I'd take a look at the yaml configuration files and check whether that is valid config for espanso.

Or maybe

```
cmd = "${lib.getExe pkgs.curl} -s https://zenquotes.io/api/random | ${lib.getExe pkgs.jq} -r '.[0].q' | ${lib.getExe pkgs.neo-cowsay}";
```

**Comment by pbek** [comment]
nix-shell isn't the issue here for me (I thought about that too first), I even tested running a script with an absolute path and got the same error...

And now I ran espanso manually with `espanso start --unmanaged` and my current global var works, also with nix-shell. 🙈

**Comment by pbek** [comment]
I'll try after a reboot when the service is running again. Thank you so far for the tipps, @bobvanderlinden and @lucasew.

**Comment by pbek** [comment]
Hm, after several tries with reboots to make sure espanso runs a service on its own I can't even reproduce the error. 😬 Maybe it's X11 / Wayland thing. Need to do more tests.

**Comment by pbek** [comment]
Ok, I get the error with X11 (still with plasma6):

```
09:52:19 [worker(4631)] [ERROR] Unable to show notification: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
09:52:57 [worker(4631)] [WARN] extension 'shell' on var: 'quote' reported an error: could not execute command: '`/nix/store/dzs2chgxcwzpwplcw6wvv8nzkn01yr7y-curl-8.6.0-bin/bin/curl -s https://zenquotes.io/api/random | /nix/store/wm8dxrnlp32hrls06cq5abgq4b0fvmwd-jq-1.7.1-bin/bin/jq -r '.[0].q' | /nix/store/jb7avidryhv4y3m6kdp4n1pqp3za4r93-neo-cowsay-2.0.4/bin/cowthink`', error: '`No such file or directory (os error 2)`'
09:52:57 [worker(4631)] [ERROR] error during rendering: rendering error

Caused by:
    could not execute command: '`/nix/store/dzs2chgxcwzpwplcw6wvv8nzkn01yr7y-curl-8.6.0-bin/bin/curl -s https://zenquotes.io/api/random | /nix/store/wm8dxrnlp32hrls06cq5abgq4b0fvmwd-jq-1.7.1-bin/bin/jq -r '.[0].q' | /nix/store/jb7avidryhv4y3m6kdp4n1pqp3za4r93-neo-cowsay-2.0.4/bin/cowthink`', error: '`No such file or directory (os error 2)`'
```

It's using `cmd = "${lib.getExe pkgs.curl} -s https://zenquotes.io/api/random | ${lib.getExe pkgs.jq} -r '.[0].q' | ${pkgs.neo-cowsay}/bin/cowthink";`:

https://github.com/pbek/nixcfg/blob/5fb1e863cf7f852e132b26a5975070605d07dc5d/modules/mixins/espanso.nix#L47

**Comment by pbek** [comment]
Can't reproduce this any more, thank you for the help!
