### ISSUE TITLE
services.cliphist should add wl-clipboard as a dependency

### ISSUE THREAD

**Issue by 44100hertz** [nix-community/home-manager#5165]
### Description
In [the source for cliphist.service](https://github.com/nix-community/home-manager/blob/master/modules/services/cliphist.nix), the systemd target for cliphist runs a wl-paste command that will fail if wl-clipboard is not added as a package. I believe that wl-clipboard should be added to the system if services.cliphist is enabled.

**Comment by rycee** [comment]
Seems to me that the unit refers to wl-paste by its full path so I don't understand why it wouldn't work.

@44100hertz Perhaps you could elaborate a little on what the problem is, "it doesn't work" is very unhelpful.

Maintainer CC: @Janik-Haag

**Comment by Janik-Haag** [comment]
+1 on rycee's comment. I don't see a problem with the current implementation and know multiple people who run it like this (including myself).

**Comment by 44100hertz** [comment]
Ahh I know the problem now. I didn't run the systemd unit after installing, which is my fault. IDK if it's possible to write a hint after switching to use this package.

**Comment by rycee** [comment]
@44100hertz You can try adding `systemd.user.startServices = "sd-switch"` to your configuration. Then it should automatically start systemd services. I'm hoping to make this the default in the future.
