### ISSUE TITLE
bug: error: store path 'blahblahash-.gitconfig' starts with illegal character '.'

### ISSUE THREAD

**Issue by PlumpMath** [nix-community/home-manager#5166]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

nix-collect-garbage -d  ;
nix-store --gc --print-dead ; 
nix-store --optimise

bug: error: store path 'blahblahash-.gitconfig' starts with illegal character '.'

### System information

```markdown
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/bv68i4l7g6s5sixxm0c9lcjdxhlkg0n5-source`
```

**Comment by sumnerevans** [comment]
This is a Nix bug, not a Home Manager bug: https://github.com/NixOS/nix/issues/5176.

I ran into this a while ago as well, and at that point, I had to stop using `.`s in my filenames, and also use an older version of nix to GC, but I think they've patched it in https://github.com/NixOS/nix/pull/5203 so you should be able to roll forward your Nix version and it should work.
