### ISSUE TITLE
bug: downgraded to nix v2.7

### ISSUE THREAD

**Issue by gilescope** [nix-community/home-manager#5167]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm going spare! With home manager my nix is always 2.7:

```sh
nix --version
nix (Nix) 2.7.0
```
I try setting it to other later versions:
nixVersions.nix_2_13
but to no avail.

I have to do this `nix-shell -p nixVersions.nix_2_18` every time I start a new terminal.
Any hints on how to get to the latest nix would be absolutely amazing (`sudo nix --version` is fine) 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 23.11 (Tapir), 23.11.5441.614b4613980a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-unstable, rust-overlay"`
 - channels(gilescope): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Sgiath** [comment]
I have this in my system config and it works fine:
```nix
{ pkgs, ...}: {
  nix = {
    settings.experimental-features = [ "nix-command" "flakes" ];
    package = pkgs.nixStable;
  };
}

**Comment by gilescope** [comment]
Have that and system nix version is behaving correctly, but not in user mode. Seems even if I uninstall home manager I still get nix 2.7 so must be something wrong at the system level somehow rather than at the home manager level...

**Comment by gilescope** [comment]
Finally figured it out. `nix-env` keeps a list of manually installed programs about for a lot longer than I expected and seems to take preference over home-manager installed ones. Might be nice if home manager warned that a program it was managing was being overridden potentially?
