### ISSUE TITLE
bug: Error 504 preventing downloads from git.sr.ht

### ISSUE THREAD

**Issue by heiytor** [nix-community/home-manager#5180]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Upon adding the following configuration:

```nix
home-manager = {
  url = "github:nix-community/home-manager/release-23.11";
  inputs.nixpkgs.follows = "nixpkgs";
};
```

An error is encountered when executing `sudo nixos-rebuild switch`, as shown below:

```
• Added input 'home-manager':
    'github:nix-community/home-manager/f33900124c23c4eca5831b9b5eb32ea5894375ce' (2024-03-19)
• Added input 'home-manager/nixpkgs':
    follows 'nixpkgs'
building the system configuration...
warning: error: unable to download 'https://git.sr.ht/~rycee/nmd/archive/v0.5.0.tar.gz': HTTP error 504

       response body:

       <html>
       <head><title>504 Gateway Time-out</title></head>
       <body>
       <center><h1>504 Gateway Time-out</h1></center>
       <hr><center>nginx</center>
       </body>
       </html>; retrying in 346 ms
```

The same issue arises when attempting to access https://git.sr.ht/ via a web browser.

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.20240322.56528ee`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
```

**Comment by heiytor** [comment]
By the way, as mentioned in https://github.com/nix-community/home-manager/issues/4024#issuecomment-1565234363, adding `manual.manpages.enable = false;` bypass this issue.

**Comment by rycee** [comment]
Seems to work for me. But I notice that there is an [email about this](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3CD02L7G5CC998.3G3PLT5CDH376@kararou.space%3E) on the sr.ht discussion list.

Hopefully it can be fully resolved quite soon.

**Comment by heiytor** [comment]
I just tried it again, and it's working now.

**Comment by teto** [comment]
Looks like a transient error, closing
