### ISSUE TITLE
bug: ZSH .zshenv doesn't support ($XDG_STATE_HOME) XDG Base Directory Specification

### ISSUE THREAD

**Issue by mboyea** [nix-community/home-manager#5187]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue description

Hello! Thank you for your time investigating this issue.

When the location of .nix-profile is changed to conform to the XDG Base Directory Specification, ZSH does not support the new location.

Specifically, when `$XDG_DATA_HOME` is defined, the generated .zshenv does not support that `./etc/profile.d/hm-session-vars.sh` is located in `~/.local/share/nix/profile` instead of `~/.nix-profile`

### Steps to Reproduce
On NixOS, include the following in `/etc/nixos/configuration.nix`:
```nix
  nix.settings.use-xdg-base-directories = true;
  environment.variables = {
    XDG_CONFIG_HOME = "$HOME/.config";
    XDG_DATA_HOME = "$HOME/.local/share";
    XDG_STATE_HOME = "$HOME/.local/state";
  };
  # the following may be optional to reproduce, I'm not sure
  programs.zsh = {
    enable = true;
    shellInit = ''export ZDOTDIR="$HOME/.zsh"'';
    histFile = "$ZDOTDIR/.zsh_history";
  };
```
Run `sudo nixos-rebuild boot && reboot` to ensure system changes are set.

Install `home-manager` as a user, and include the following in `~/.config/home-manager/home.nix`:
```nix
programs.zsh = {
  enable = true;
  dotDir = ".zsh";
  history.path = "$ZDOTDIR/.zsh_history";
  oh-my-zsh
};
```
Run `home-manager switch` to generate configs.

Launch `zsh` from a shell. Observe the error message:
```nix
/home/<user>/.zsh/.zshenv::.:2: no such file or directory: /home/<user>/.nix-profile/etc/profile.d/hm-session-vars.sh
```
Run `echo $XDG_STATE_HOME` from the shell to ensure it is set correctly.

Run `ls $XDG_STATE_HOME/nix/profile/etc/profile.d` from the shell to ensure `hm-session-vars.sh` is in the correct location.

Run `$EDITOR ~/.zsh/.zshenv` to observe that there is no check for `$XDG_STATE_HOME`.

### Screenshot of Issue
![image](https://github.com/nix-community/home-manager/assets/68197922/a27827aa-5023-4919-9224-ee1bb44df693)

### Proposed Fix
To fix should be an easy one-line change to the shell script generated for `.zshenv`.

Home Manager's generation of .zshenv should include a check for whether `$XDG_STATE_HOME` is set, and use `$XDG_STATE_HOME/nix/profile` as the base directory of `/etc/profile.d/hm-session-vars.sh`, or otherwise use the current (`.nix-profile`).

### Maintainer CC

@berbiche @rycee @sumnerevans @jian-lin 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.20240320.f091af0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jian-lin** [comment]
The cause is that [`profileDirectory`][1] [hardcodes][2] its value without taking xdg config into consideration.  If this behavior is changed (I am not sure if the change is desired though) and your xdg config is set using the xdg module of home-manager, it should work.


[1]: https://github.com/nix-community/home-manager/blob/1c2c5e4cabba4c43504ef0f8cc3f3dfa284e2dbb/modules/programs/zsh.nix#L553
[2]: https://github.com/nix-community/home-manager/blob/1c2c5e4cabba4c43504ef0f8cc3f3dfa284e2dbb/modules/home-environment.nix#L206-L212

**Comment by jian-lin** [comment]
(updated my above comment)

**Comment by mboyea** [comment]
> Setting `nix.settings.use-xdg-base-directories` at the NixOS level and not using home-manager as a module [make it hard](https://github.com/nix-community/home-manager/blob/1c2c5e4cabba4c43504ef0f8cc3f3dfa284e2dbb/modules/home-environment.nix#L522-L528) for home-manager to set the right value for [`profileDirectory`](https://github.com/nix-community/home-manager/blob/1c2c5e4cabba4c43504ef0f8cc3f3dfa284e2dbb/modules/programs/zsh.nix#L553).

Why could we not just detect if `$XDG_STATE_HOME` is defined, and use `$XDG_STATE_HOME/nix/profile` if so, but default to `.nix-profile` otherwise?

**Comment by jian-lin** [comment]
> Why could we not just detect if $XDG_STATE_HOME is defined, and use $XDG_STATE_HOME/nix/profile if so

For this to work, do not forget to also detect the nix config of `use-xdg-base-directories`.

However, one major point of nix is reproducibility, so I am not sure if this behavior is desired (even for the standalone home-manager usage).

**Comment by mboyea** [comment]
> For this to work, do not forget to also detect the nix config of `use-xdg-base-directories`.
> 
> However, one major point of nix is reproducibility, so I am not sure if this behavior is desired (even for the standalone home-manager usage).

You bring up good points about reproducibility and options checking for user choice.

Whether the Operating System conforms to the XDG Base Directory Specification is not relevant to whether home-manager conforms to the spec. Home manager should not base its behavior on the operating system's behavior (in this case NixOS `nix.settings.use-xdg-base-directories`).

Instead, home-manager has the option [`programs.xdg.enable`](https://github.com/nix-community/home-manager/blob/master/modules/misc/xdg.nix#L25) which should determine whether the spec is used.

Therefore the best solution seems to be (in pseudo code):
```py
if (home.programs.xdg.enable)
  # inline support for the XDG Base Directory Specification
```

The specification is here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

**Comment by mboyea** [comment]
After some further investigation, I found that `${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh` seems to be the regular way of checking for the session vars. This means that the if/else in my last comment isn't even necessary.

**Comment by mboyea** [comment]
I looked into how .zshenv is generated, and I have found that `config.home.profileDirectory` is sourced correctly: https://github.com/nix-community/home-manager/blob/b787726a8413e11b074cde42704b4af32d95545c/modules/programs/zsh.nix#L553

It looks like this must be my fault, and the solution is to properly declare values to make `config.home.profileDirectory` resolve correctly..

**Comment by mboyea** [comment]
> See how `config.home.profileDirectory` is defined here:
> 
> https://github.com/nix-community/home-manager/blob/b787726a8413e11b074cde42704b4af32d95545c/modules/home-environment.nix#L528

By reading this source code, I found that the nix config setting `nix.settings.use-xdg-base-directories = true` is required to conform to the XDG Base Directory Spec.

My first thought was, "Oh no! it's impossible to do this unless you call Home Manager as a nix module!"

However, I found that nix configuration options can actually be set inside Home Manager explicitly, even when run as a User.

Adding the following to `home.nix` causes Home Manager to conform to the specification:
```
  nix = {
    package = pkgs.nix;
    settings.use-xdg-base-directories = true;
  };
```

**Comment by mboyea** [comment]
With the above addition to `home.nix` the issue is resolved.
![image](https://github.com/nix-community/home-manager/assets/68197922/9d3ec8c1-8f55-49ea-a5c0-d1eacd0ccb19)

Given that everything here appears to be working correctly, I'll close the issue with this comment.
Thank you @jian-lin for the help.
