### ISSUE TITLE
Customizable gtkrc-2.0 file location

### ISSUE THREAD

**Issue by wedens** [nix-community/home-manager#519]
`.gtkrc-2.0` file location can be changed using `GTK2_RC_FILES` env variable. e.g.:
`export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc`

It'd be very useful for people like me who annoyed by `$HOME` pollution.

**Comment by bqv** [comment]
@rycee interested?

**Comment by bqv** [comment]
Would be nice.

**Comment by sumnerevans** [comment]
@bqv or @wedens can you test the PR that I just created?
