### ISSUE TITLE
Declaratively manage mapping of website to container firefox

### ISSUE THREAD

**Issue by codingCoffee** [nix-community/home-manager#5202]
### Description

Firefox has an extension called [Multi Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/). And one can configure it to force open certain websites in certain containers. Creating containers is already managed by home-manager using `programs.firefox.profiles.<profile_name>.containers`. Can a feature be added to manage mapping of websites to containers as well?

**Comment by jeslinmx** [comment]
It might not be plausible to support more granular config of the Containers extension; whereas setup of containers is achieved through containers.json, the settings for automatically opening particular websites in containers is an extension setting, which in general is not easily made declarative (see https://github.com/nix-community/home-manager/issues/4618#issuecomment-1987186943)
