### ISSUE TITLE
programs.mpv.bindings: Multiple items with the same key

### ISSUE THREAD

**Issue by arvigeus** [nix-community/home-manager#5212]
Not sure if this should be classified as a feature request, documentation request, or simply brain dump for the future intrepid explorers stumbling through the same problem.

Use case: uosc allows defining [custom menus](https://github.com/tomasklaen/uosc?tab=readme-ov-file#adding-items-to-menu), for example:

```
#    #! ---
#    #! Section > ---
```

The problem is that nix cannot have a dictionary with the same value. I figured I could just go funky and define it like this:

```nix
"#    #! ---" = "";
"#    #! Section > ---" = "";
```

It appears to work, but it's undocumented. I think this either should be added as an example [here](https://mynixos.com/home-manager/option/programs.mpv.bindings), or binding values should be allowed to be an array:

```nix
"#": [
  "#! ---"
  "#! Section > ---"
]
```

Another option is to address the source directly and add the ability to define the menu in `programs.mpv.scriptOpts.uosc`.

If no solution is feasible, I hope my workaround would help someone in the future.

**Comment by Lichthagel** [comment]
I suggest adding a `extraBindings` or  `extraInput` option for text that is appended to `input.conf`.

Could do a PR on that.

**Comment by rycee** [comment]
Yeah, an `extraInput` would probably be useful for this.
