### ISSUE TITLE
helix: consider running `hx --grammar fetch && hx --grammar build` on activation

### ISSUE THREAD

**Issue by britter** [nix-community/home-manager#5218]
### Description

When configuring custom grammars using the `languages` option, one needs to remember to run `hx --grammar fetch` and `hx --grammar build`. Otherwise the newly configured grammar does not work. This could be added as an activation step, much like the [one for bat](https://github.com/nix-community/home-manager/blob/80546b220e95a575c66c213af1b09fe255299438/modules/programs/bat.nix#L165-L172).

**Comment by britter** [comment]
Pinging maintainer @Philipp-M. WDYT?

**Comment by teto** [comment]
usuallly you would install those grammars via, wouldn't you ? not using hx but that's how nix+neovim does it

**Comment by Philipp-M** [comment]
I'm not sure whether that should be in a default activation hook, it takes some time, and I doubt that custom grammars are used by a lot of people. But I think this could be done though, when `programs.helix.languages.grammar` is set. I'm happy to review a PR doing that.

> usuallly you would install those grammars via, wouldn't you ? not using hx but that's how nix+neovim does it

(I'm guessing you meant "Nix") Unfortunately not that easy yet in helix, see the discussion in https://github.com/nix-community/home-manager/issues/2871#issuecomment-1264459501. At some point, I think that feature could be added upstream, as I think installing via nix is certainly cleaner.

**Comment by SrEstegosaurio** [comment]
Dosn't grammars need to be managed via nix?

I do use the upstream flake to provide the package and that one builds all and every grammar supported by helix. Those do indeed take some time to build and I need to override them since I use like 3 of them.

**Comment by britter** [comment]
@Philipp-M I can give it a shot. Not sure when I will get to it though. Maybe we can call `fetch` and `build` only for the grammars that are explicitly defined in `languages`. I don't recall whether the commands take a grammar name as an argument. Will check.

**Comment by SrEstegosaurio** [comment]
I think it only builds things defined in `languages.toml` as per the help message:
`-g, --grammar {fetch|build}    Fetches or builds tree-sitter grammars listed in languages.toml`

**Comment by britter** [comment]
@SrEstegosaurio as far as I can tell on my system it builds both, the built in grammars defined in the languages.toml that it ships with as well as the user supplies grammars from the user space language.toml.

**Comment by SrEstegosaurio** [comment]
I might mention that I'm using the h-m module in conjunction with the upstreram latest nix pacakge.

**Comment by britter** [comment]
No, I load it into `nix shell` when I need to rebuild grammars. That works well enough for me.
