### ISSUE TITLE
bug: multiple errors setting up joplin

### ISSUE THREAD

**Issue by eblechschmidt** [nix-community/home-manager#5222]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

1. Joplin derivation is not building due to this error `error: value is null while a string was expected` when I don't set the options  `sync.target` and `sync.interval`. If i set those I get error number two.
2. `touch: cannot touch '/home/xxxx/.config/joplin-desktop/settings.json': No such file or directory`. As I'm doing a fresh install the folder does not yet exist so it needs to be created before this line https://github.com/nix-community/home-manager/blob/80546b220e95a575c66c213af1b09fe255299438/modules/programs/joplin-desktop.nix#L116

### Maintainer CC

@zorrobert

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7ay2dd0w41iqvrnkx19v4vf4f5kkxvc2-source`
```

**Comment by zorrobert** [comment]
Thanks, I fixed it in #5226
