### ISSUE TITLE
bug: Nushell fails to load config file since version 0.92.0 on darwin

### ISSUE THREAD

**Issue by jaudiger** [nix-community/home-manager#5248]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Since the version 0.92.0 of nushell and the full support of XDG_CONFIG_HOME, it seems on startup it fails to load its configuration file set from home-manager:

```
    programs.nushell = {
      enable = true;

      configFile = {
        text = ''
          $env.config = {
            show_banner: false

            ls: {
                use_ls_colors: true
                clickable_links: true
            }

            rm: {
                always_trash: true
            }
          }
        '';
      };
    };
```

I always got the following warnings:

```
No environment config file found at /Users/jaudiger/.config/nushell/env.nu
Would you like to create one with defaults (Y/n):
n
Continuing without config file
No config file found at /Users/jaudiger/.config/nushell/config.nu
Would you like to create one with defaults (Y/n):
n
Continuing without config file
```

I think the problem comes from these lines in home-manager: https://github.com/nix-community/home-manager/blob/40a99619da804a78a0b166e5c6911108c059c3a8/modules/programs/nushell.nix#L9-L12

### Maintainer CC

@Philipp-M 
@oceanlewis 

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Philipp-M** [comment]
@jaudiger can you test #5250, whether this fixes your issue?

**Comment by jaudiger** [comment]
Just test it, and it works like a charm. You were right, I forgot to mention that I had set `home-manager.xdg.enable` in my config.
