### ISSUE TITLE
bug: Zsh setting the wrong autosuggest color variable

### ISSUE THREAD

**Issue by jrunestone** [nix-community/home-manager#5290]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Seems to me the `programs.zsh.autosuggestion.highlight` option is setting the wrong variable: [`AUTOSUGGESTION_HIGHLIGHT_COLOR`](https://github.com/nix-community/home-manager/blob/master/modules/programs/zsh.nix#L615) when it should be [`ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE`](https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/config.zsh#L10).

Or am I the only one trying to style the autosuggest color? :D

### Maintainer CC

@teto

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.27, NixOS, 24.05 (Uakari), 24.05.20240416.5672bc9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source`
```

**Comment by teto** [comment]
hum I dont remember where I took [AUTOSUGGESTION_HIGHLIGHT_COLOR](https://github.com/nix-community/home-manager/blob/master/modules/programs/zsh.nix?rgh-link-date=2024-04-17T22%3A04%3A20Z#L615) from but following the doc you seem to be right :s I dont have time to investigate though so PR welcome.
