### ISSUE TITLE
bug: `programs.bash.enable` does not add bash to `home.packages`

### ISSUE THREAD

**Issue by Samasaur1** [nix-community/home-manager#5295]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Enabling bash with `programs.bash.enable` does not add bash to `home.packages`, and thus not to my configuration.

All other shells in home-manager do this:
- https://github.com/nix-community/home-manager/blob/ff1c3646541316258b1ca64e9b25d4c9cca8e587/modules/programs/zsh.nix#L564
- https://github.com/nix-community/home-manager/blob/ff1c3646541316258b1ca64e9b25d4c9cca8e587/modules/programs/fish.nix#L384
- https://github.com/nix-community/home-manager/blob/ff1c3646541316258b1ca64e9b25d4c9cca8e587/modules/programs/nushell.nix#L158

but not bash. I'm not sure if this was an oversight, or if there was a deliberate reason, but I think if it is deliberate that there should be a note somewhere

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.20.5`
 - nixpkgs: `/nix/store/3vysbx7v008h7473gwfmv6lzqfzsn3q7-source`
```

**Comment by rycee** [comment]
The historic reason for this is that the bash shell always is available through NixOS anyway. But I agree, the module should probably install it as well.

**Comment by rycee** [comment]
Please give it a try now.

**Comment by Samasaur1** [comment]
That did it, thanks!
