### ISSUE TITLE
bug: footclient has wrong path.

### ISSUE THREAD

**Issue by lgehr** [nix-community/home-manager#5302]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hello,

when using `foot.service.enable`. All `footclient` have the wrong PATH. Especially they do not have `/run/current-system/bin` etc. 
(Which makes it impossible for me to find out, what the path actually is, since not even `echo` is working correctly)

Since `foot` and `footclient` are the only(?) command working I think the culprit is #5254  
However I was not able to check this. 

### Maintainer CC

@brynedwards @plabadens 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.27, NixOS, 24.05 (Uakari), 24.05.20240416.66adc1e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/6bf943g0mlhymyffs9dflzgc78r93s60-source`
```
```

**Comment by michaelBelsanti** [comment]
The path is being set to just the foot derivation: `/nix/store/zzd71mj06mpslmpik51cdc4x51p5z1qn-foot-1.17.1/bin`, so it does seem to be caused by that change.

**Comment by michaelBelsanti** [comment]
This issue exists on GNOME, but not Hyprland

**Comment by brynedwards** [comment]
Sorry about that, I'm using Sway and it fixed my issue but I didn't realise this would break other desktop environments. I don't know enough yet to provide a cross-environment solution, until there is one I agree that it should be reverted.

**Comment by michaelBelsanti** [comment]
All good, I'm honestly not even sure why it's causing this issue, especially why it's only happening in some environments.
