### ISSUE TITLE
Upgrade `programs.taskwarrior` to use `taskwarrior3`

### ISSUE THREAD

**Issue by cloudlena** [nix-community/home-manager#5310]
Currently, `programs.taskwarrior.package` defaults to `pkgs.taskwarrior`. A new version of Taskwarrior was released, so we should update the default to `pkgs.taskwarrior3`.

**Comment by aktaboot** [comment]
since the `taskwarrior` package is still in nixpkgs and people might not have migrated yet, I think we should still keep it to `pkgs.taskwarrior`. It can easily be set manually to taskwarrior3.

I don't think a breaking change should be imposed on users without notice

**Comment by cloudlena** [comment]
Thanks, @aktaboot. I see your point.

I'm not sure how this is handled usually. Would you just wait for some time and then change it later, or how would you proceed?

**Comment by aktaboot** [comment]
Yes, eventually it will roll out, but really unsure when.

**Comment by mdietrich16** [comment]
What about `services.taskwarrior-sync`? AFAIK (still a newbie to Nix) there is no option to explicitly set the used taskwarrior pkg to `taskwarrior3` instead of `taskwarrior`.

**Comment by aktaboot** [comment]
@mdietrich16  for taskwarrior3, you can just set `programs.taskwarrior.package = pkgs.taskwarrior3;`
for the sync server module, I have a thing that I should upstream soon
