### ISSUE TITLE
bug: even using NixOS module HM suggests using HM flag `-b backup`

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nix-community/home-manager#5350]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

i use HM as a [NixOS module](https://nix-community.github.io/home-manager/index.xhtml#sec-install-nixos-module).
if i then use `nixos-rebuild switch` while a link target is blocked, HM offers an interesting line of feedback:

> Activating checkLinkTargets
> Existing file '/home/kiara/.zsh_history' is in the way of '/nix/store/k8paywiwg3h9glws1a1kz7wxjwv4jlwh-home-manager-files/.zsh_history'
> Please move the above files and try again or use 'home-manager switch -b backup' to back up existing files automatically.

given i am not using the HM cli, it would be nice if the error feedback would cover the use-case of using the NixOS module - i would gladly pass an additional option to tweak its behavior (over the flag) if i know how.

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 24.05 (Uakari), 24.05.20240425.ebee8d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/run/current-system/nixpkgs`
```
```

**Comment by rycee** [comment]
Good point about the misleading error message. I'll see if it can be improved to point to the proper configuration option.

Btw, the configuration option you want is [`home-manager.backupFileExtension`](https://nix-community.github.io/home-manager/nixos-options.xhtml#nixos-opt-home-manager.backupFileExtension).
