### ISSUE TITLE
bug: zoxide enableFishIntegration doesn't seem to work

### ISSUE THREAD

**Issue by pbek** [nix-community/home-manager#5364]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Thank you for the zoxide integration!

I enabled zoxide and enabled also `enableFishIntegration` (see [config](https://github.com/pbek/nixcfg/blob/debbca911c2537daae09efd41ddd3b3b2ea91358/modules/mixins/common.nix#L158-L164)), but that only seem to do a `${cfg.package}/bin/zoxide init fish ${cfgOptions} | source` (see [config](https://github.com/nix-community/home-manager/blob/6d3b6dc9222c12b951169becdf4b0592ee9576ef/modules/programs/zoxide.nix#L79-L81)) and is not writing it to somewhere where every fish instance is supposed to pick up (like `~/.config/fish/conf.d`), like e.g. the starship module is doing...

I'm I doing something wrong here? 🤷🏻

### Maintainer CC

maybe @r-vdp, @marsam, @rycee, @adamcstephens

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/run/current-system/nixpkgs`
```

**Comment by pbek** [comment]
@adamcstephens, @rycee, is piping to source enough to store it permanently? 

https://github.com/nix-community/home-manager/blob/6d3b6dc9222c12b951169becdf4b0592ee9576ef/modules/programs/zoxide.nix#L80

**Comment by r-vdp** [comment]
> @adamcstephens, @rycee, is piping to source enough to store it permanently?
> 
> https://github.com/nix-community/home-manager/blob/6d3b6dc9222c12b951169becdf4b0592ee9576ef/modules/programs/zoxide.nix#L80

This line is put into the `programs.fish.interactiveShellInit` option, which will include it in `~/.config/fish/config.fish`, which should always be picked up by fish.

Are you actually experiencing that something is not working well? I use zoxide on fish and haven't noticed any issues myself.

**Comment by pbek** [comment]
Strange. The `z` alias doesn't work for me, even when I use `"--cmd z"`. Using `"--cmd cd"` also didn't help. Tried on several boxes. Also tried to reboot. When I do a `zoxide init fish | source` or `zoxide init fish --cmd cd | source` the assigned alias works for the shell I ran the command. 🤔

What's your config you are using?
It's not https://github.com/r-vdp/nixos-config/blob/048496c9d71e6d7e818706830c9b4e40fc786ded/home-modules/shell-config.nix#L67, isn't it?

**Comment by pbek** [comment]
My `~/.config/fish/config.fish` don't look like they were generated by nix, it's an actual file and the content is different on every box.

For example:

```fish
if status is-interactive
    # Commands to run in interactive sessions can go here
end
```

**Comment by pbek** [comment]
Oh, I just saw I added the starship config myself too with:

```nix
    # enable starship prompt in fish shell, enableFishIntegration in the starship config did not work
    home.file.".config/fish/conf.d/starship.fish".text = ''
      starship init fish | source
    '';
```

https://github.com/pbek/nixcfg/blob/4ad1582e66609e87d931a27644d2cf6c00d491f7/modules/mixins/starship.nix#L5-L8

Looks like no `enableFishIntegration` is working for me. 🙈
Is there something that needs to be done, so those integrations work in general with home-manager?

**Comment by r-vdp** [comment]
Okay, so it seems that you didn't actually enable fish, you should set `programs.fish.enable = true;`.

Then, home-manager will complain that config.fish already exists, so you should migrate whatever is in there now into your nix config, and then remove that file and let home-manager put the nix-managed file in place.

You probably want to put most things in `programs.fish.interactiveShellInit`.

**Comment by pbek** [comment]
Seems like I only enabled fish for nixos, but not in home-manager! 🤦🏻

https://github.com/pbek/nixcfg/blob/debbca911c2537daae09efd41ddd3b3b2ea91358/modules/mixins/common.nix#L8-L9

**Comment by pbek** [comment]
It now works on its own. So I learned something new today! 😁 
Sorry for my misunderstanding, and thanks a lot for helping me, @r-vdp!
