### ISSUE TITLE
bug: kitty and wezterm have trouble processing ime input (because they are spammed by fcitx5-daemon ?)

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#5369]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Kitty had trouble processing my input:
- no repeat on keypress
- sometimes it would ignore keypress
- can't copy/paste freeze

I tried to switch to wezterm. At first it all seemed fine but then I experienced the same and wezterm had the tendency to lockup (the wayland backend is being rewritten, that might be why).  Then I found https://github.com/kovidgoyal/kitty/issues/2191#issuecomment-565353150 and as I explained later on in the thread, kitty was receiving lots of IME-related events even without me using the keyboard.   ` systemctl stop --user fcitx5-daemon` fixed the issue. I have yet to investigate the situation. Looks like there is an `execve` failure in my fcitx5 journal. 

Putting it out there since fix was not obvious.

### System information

```markdown
nixos-unstable
```

**Comment by teto** [comment]
just found out by looking at https://github.com/NixOS/nixpkgs/pull/316403 that it's a known bug https://groups.google.com/g/fcitx/c/8V0OVxkUkFA?pli=1 https://github.com/swaywm/sway/issues/8143

**Comment by nevivurn** [comment]
Can confirm that fcitx5 5.1.10 (tested by locally backporting NixOS/nixpkgs#316403) fixes the issue for me. This is an fcitx5 / nixpkgs issue, not h-m.

**Comment by teto** [comment]
> This is an fcitx5 / nixpkgs issue, not h-m.

Indeed.
