### ISSUE TITLE
bug: kanshi profile order is not respected

### ISSUE THREAD

**Issue by benjamb** [nix-community/home-manager#5374]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The order in which profiles are defined within kanshi's configuration file matters, however since `kanshi.nix` implements `profiles` as an attribute set that is converted to a list via `mapAttrsToList`, profiles within the resulting config file are ordered alphabetically according to their name.

It would likely make sense to convert the `profiles` option to a list, moving the profile name to an attribute within `profileModule`, but this would be a breaking change and I'm not familiar with home-manager's policy on this.

### Maintainer CC

@nurelin 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.88, NixOS, 23.11 (Tapir), 23.11.20240429.576ecd4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/xpzmrd7qla29lv913dgg0rma1g335zam-source`
```

**Comment by nurelin** [comment]
Looking at how kanshi [defines profiles](https://git.sr.ht/~emersion/kanshi/tree/master/item/doc/kanshi.5.scd) and that profile names are optional. I think it makes sense to use a list as suggested.
On the other hand, I do not know how configuration changes like this shall be handled.
Shall we put both `profiles` and `profilesList` with an assertion that both shall not be used at once and a deprecation message on `profiles`?

**Comment by benjamb** [comment]
That sounds like a reasonable approach.
