### ISSUE TITLE
bug: kanshi breaks nixos-rebuild

### ISSUE THREAD

**Issue by jkaye2012** [nix-community/home-manager#5391]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I think a recent commit might have inadvertently broken NixOS builds (or I'm doing something incorrect):

```bash
error:
       … while calling the 'head' builtin

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:967:11:

          966|         || pred here (elemAt values 1) (head values) then
          967|           head values
             |           ^
          968|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'attrTag' missing

       at /nix/store/gd2i9ncq2rswcwwai1f5wh0jbz4nl9iz-source/modules/services/kanshi.nix:9:19:

            8|
            9|   directivesTag = types.attrTag {
             |                   ^
           10|     profile = mkOption {

```

Builds on this machine were functional last night. A build this morning with identical configuration (save for the home-manager version upgrade) fails with the message above. I believe that [this change](https://github.com/nix-community/home-manager/commit/4855bfb6ce20225a1b0e2aae2379da909ab38350) might be the cause.

### System information

```markdown
[jkaye@jkaye-nixos:~/git/curated]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05pre598982.b06025f1533a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jkaye2012** [comment]
Thanks - I didn't realize that channels had to be manually updated! Still learning over here. Appreciate the help

**Comment by blmarket** [comment]
Hi, still failing even if I try to update nixpkgs-unstable channel. What command to run in order to update the nixpkgs?

**Comment by jkaye2012** [comment]
I ran `sudo nix-channel --update` and my previously failing build started
working.

**Comment by blmarket** [comment]
With that command, I had to add `--upgrade` to `nixos-rebuild switch` to made it work.

```
sudo nixos-rebuild switch -I {blahblah} -j 4 --upgrade
```
