### ISSUE TITLE
bug: modules/programs/helix.nix - Config Options in Nix Lists auto-duplicate in Toml Lists

### ISSUE THREAD

**Issue by cabbott008** [nix-community/home-manager#5398]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

![Toml-Trouble-2024-05-12_17-21](https://github.com/nix-community/home-manager/assets/77243923/198a027a-be77-44c8-a92e-16bffe42401c)

![Double-TOML-Trouble-2024-05-12_17-37](https://github.com/nix-community/home-manager/assets/77243923/14158f43-7d10-40f0-ae2e-5969ac244a88)

In my Home-Manager config, all option entries that are specifically in Lists on the Nix Config side are duplicated in the Helix Toml config via the Home-Manager module.

I hope to get to the stage where I can know exactly what is causing it, but I'm not there yet.

Thank you so much for your work on this!!!

### Maintainer CC

@Philipp-M

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05.20240509.f1010e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/asymc3nsl739p1wwr0w6xbjnqs3qb94p-source`
```

**Comment by Philipp-M** [comment]
Just a wild guess, you may be importing that config twice, I think this is the merge behavior of lists in nix.

Try removing that line:

https://github.com/cabbott008/.nixos/blob/40a4a053b083da74713b15ba49a62b7234d70dc2/flake.nix#L39

**Comment by cabbott008** [comment]
That makes so much better sense that me being the first person to report the issue. LOL. Newbie error.

Yes, you are entirely correct. I was double-importing home.nix as you suspected. Thank you so much!
