### ISSUE TITLE
bug: kanshi breaks home-manager siwtch

### ISSUE THREAD

**Issue by RikudouSage** [nix-community/home-manager#5399]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Pretty much the same thing as in #5391, but I use standalone Home Manager on a non-NixOS system. This happened after I ran `nix-channel --update`, afterwards when running `home-manager switch`, I get the error mentioned in that issue.

This is my `nix-channel --list`:

```
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
```

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.7-201.fsync.fc39.x86_64, Nobara Linux, 39 (KDE Plasma), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by nurelin** [comment]
What does `sudo nix-channel --list` outputs ?
If there is a `nixpkgs` entry, you might need to update it.

**Comment by RikudouSage** [comment]
Good old `sudo: nix-channel: command not found`.

**Comment by nurelin** [comment]
Weird. Given your bug report's System Information, it seems that you are using the nixpkgs of the root user.
Which should be the one used by home-manager if no other is found.

**Comment by nurelin** [comment]
Maybe try running [sudo as a login shell](https://old.reddit.com/r/NixOS/comments/1292abq/how_do_i_update_packages_when_using_homemanager/jsuwtxr/) to force the various `*rc` files to be sourced. `sudo - i nix-channel --list`

**Comment by RikudouSage** [comment]
Running `sudo -i nix-channel --update` fixed it!
