### ISSUE TITLE
bug: `services.kdeconnect.enable` doesn't open port

### ISSUE THREAD

**Issue by lebensterben** [nix-community/home-manager#5403]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

With home-manager's `services.kdeconnect.enable` set to `true`, it doesn't seem to open UDP/TCP port 1714-1764. I need to manually open them to have kdeconnect working correctly.

In the meantime, nixpkgs's `programs.kdeconnect.enable` will open those ports automatically. See https://github.com/NixOS/nixpkgs/blob/44072e24566c5bcc0b7aa9178a0104f4cfffab19/nixos/modules/programs/kdeconnect.nix#L30-L33

### Maintainer CC

@adisbladis 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240512.2057814`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/vsbi6gfwf2bdamw0d0d9xndb1rrxfnbk-source`
```

**Comment by Zocker1999NET** [comment]
I think this cannot be fixed properly as home-manager can only apply configurations with user permissions, while on most systems the firewall configuration can only be modified with root or similar permissions. Also, on NixOS, even with root permissions, home-manager could not really modify the firewall rules defined by your configuration.nix / flake.nix.

(Please correct me if I’m incorrect about this.)

I ran into a similar problem where I wanted my home-manager config to set parts of my NixOS config. I accepted it as impossible. So I would say you just need to set `programs.kdeconnect.enable = true;` in your NixOS config.

*If* you still want your NixOS & HM configs to interact & check each other, you can do the following:
- use Home-Manager as a NixOS module [as explained in the manual](https://nix-community.github.io/home-manager/index.xhtml#sec-install-nixos-module)
- pass your NixOS config to the HM module system [like this in line 76](https://git.banananet.work/banananetwork/server/src/commit/933dd845032963c8a26234235f02e21f9f22aecc/nix/nixos-modules/frontend/default.nix#L70-L80)
- Now you can access your NixOS config ("read-only") from your Home-Manager module. I use that to assert that gpg-agent & scdaemon are enabled by Home-Manager *if and only if* `hardware.gpgSmartcards` udev rules are enabled by NixOS. [See my code here](https://git.banananet.work/banananetwork/server/src/commit/933dd845032963c8a26234235f02e21f9f22aecc/nix/nixos-modules/frontend/home.nix#L22-L36)

**Comment by rycee** [comment]
Indeed, as @Zocker1999NET states, Home Manager as a user space tool cannot have any effect on the system firewall. The best that could be done is to improve the module documentation to state that the user must open these ports for it to work.
