### ISSUE TITLE
bug: hypridle service skipped because of an unmet condition

### ISSUE THREAD

**Issue by Anomalocaridid** [nix-community/home-manager#5407]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I recently updated my NixOS setup and switched from the `hypridle` flake module to the one in Home Manager. I noticed that hypridle does not do anything when I try to lock my session with `loginctl lock-session`. I checked the status of the systemd service with `systemctl --user status hypridle.service` and got the following output:

```
○ hypridle.service - hypridle
     Loaded: loaded (/home/anomalocaris/.config/systemd/user/hypridle.service; enabled; preset: enabled)
     Active: inactive (dead)
  Condition: start condition unmet at Tue 2024-05-14 23:10:00 EDT; 5min ago
             └─ ConditionEnvironment=WAYLAND_DISPLAY was not met

May 14 23:10:00 home-pc systemd[3088]: hypridle was skipped because of an unmet condition check (ConditionEnvironment=WAYLAND_DISPLAY).
```

I am using Hyprland on NixOS unstable. When I manually run `systemctl --user start hypridle.service`, `hypridle` works as expected.

### Maintainer CC

@khaneliman
@fufexan

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.9-xanmod1, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - nixpkgs: `/nix/store/vsbi6gfwf2bdamw0d0d9xndb1rrxfnbk-source`
```

**Comment by khaneliman** [comment]
WAYLAND_DISPLAY should be set by Hyprland in a graphical session.

**Comment by Anomalocaridid** [comment]
I am using the hyprland home-manager module. However I realized that this is probably not a bug with home-manager. Rather I think it's probably this PR I am using: https://github.com/NixOS/nixpkgs/pull/297434. It apparently causes issues with services that rely on `graphical-session.target`.

Sorry for missing that.
