### ISSUE TITLE
bug: kanshi: new profiles structure is counter-intuitive/non-nix-standard and/or erroneously documented

### ISSUE THREAD

**Issue by ppenguin** [nix-community/home-manager#5443]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The example in https://github.com/nix-community/home-manager/blob/850cb322046ef1a268449cf1ceda5fd24d930b05/modules/services/kanshi.nix#L249C1-L272C10 is erroneous, since

```
{ 
   profile.name = "undocked";
   profile .outputs = [...];
}
{ 
   profile.name = "docked";
   profile .outputs = [...];
}
```
would/should reduce to

```
profile = {
   name = "undocked";
   ...
   name = "docked";
   ...
}
```
which is illegal (duplcate keys).
Hence it is not clear what is the correct way to re-define profiles, some (idiomatic) attempts to modify the config lead to ` error: A definition for option 'services.kanshi.settings' is not of type 'list of attribute-tagged union'.`

### Maintainer CC

@nurelin 

### System information

```markdown
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 24.05 (Uakari), 24.05.20240519.6c0b7a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.1`
 - nixpkgs: `/nix/store/aprm7cdlp21bq5ykfkqcyh7a08d3saqa-r8nhgnkxacbnf4kv8kdi8b6ks3k9b16i-source`
```

**Comment by nurelin** [comment]
Oups, I forgot the list in the example, it should read:

```nix
[
  { 
     profile.name = "undocked";
     profile .outputs = [...];
  }
  { 
     profile.name = "docked";
     profile .outputs = [...];
  }
]
```

**Comment by nurelin** [comment]
Concerning the counter-intuitive/non-nix-standard part, the changes was made to be closer to kanshi configuration's file structure in which profiles order is significant. See https://github.com/nix-community/home-manager/issues/5374.

**Comment by ppenguin** [comment]
Ah, ok that makes sense, though it makes `profile` redundant, i.e.

```
[
  { 
     profile.name = "undocked"
     ...
  }
]

==

[
  { 
     profile = { 
        name = "undocked";
        ...
     }
  }
]
```

if the list is in fact called `profiles`, it is doubly redundant, so better would then be:

```
profiles = [
   {
       name = "undocked";
       ....
   }
];
```

No?
I *think* this would also satisfy the requirements set forth in #5374, since it's basicaly your proposed solution but without the redundant `profile.` in front of the actual single profile attributes?

**Comment by nurelin** [comment]
The problem is that kanshi's configuration is essentially a list which can contains profiles, includes and outputs and that the order matter. For example, [output can give default values to profiles](https://git.sr.ht/~emersion/kanshi/tree/master/item/doc/kanshi.5.scd#L43). So I needed a mean to differentiate between them while keeping the list ordered and having a reasonable documentation generated.
