### ISSUE TITLE
Automatically append `.yazi` to Yazi plugin names

### ISSUE THREAD

**Issue by poperigby** [nix-community/home-manager#5478]
Yazi plugins need to have the following structure: `$XDG_CONFIG_DIR/yazi/plugins/<plugin-name>.yazi/init.lua`.

It would be helpful if home-manager would automatically append the `.yazi` part to the plugin directory, so you can do this...

```nix
programs.yazi.plugins = {
    smart-enter = ./plugins/smart-enter;
};
```

...instead of this:

```nix
programs.yazi.plugins = {
    "smart-enter.yazi" = ./plugins/smart-enter;
};
```

Another thing that would nice to have is an assertion that the path given is a directory, and not a Lua file. The directory structure won't be correct unless it's the former. The documentation should reflect this as well.

**Comment by rycee** [comment]
Maintainer CC: @XYenon

**Comment by XYenon** [comment]
Great idea, I'll try to implement it.
