### ISSUE TITLE
no manpage for dunst

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#553]
I have dunst installed through HM and documentation.enable yet `man dunst` gives nothing. dunst has a man output. I remember some problems with nix-env and man outputs. Seems like home-manager doesn't add it to systemPackages.

**Comment by rycee** [comment]
To also install the "doc" outputs you need to add it to the `home.extraOutputsToInstall` option. That is, have
```
home.extraOutputsToInstall = [ "doc" ];
```
in your configuration.

**Comment by teto** [comment]
I have added dunst to the packages list, added "man" to home.extraOutputsToInstall  and even did `programs.man.enable = true;` (equivalent I believe) and still no manpage for dunst. 
Also I wonder if extraOutputsToInstall shouldn't default to nixos `documentation` configuration.
