### ISSUE TITLE
bug: home-manager Failed to build switch plan after recent update 

### ISSUE THREAD

**Issue by sakshatshinde** [nix-community/home-manager#5552]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

home-manager switch worked fine until my last switch. I referred the nix-starter config. Don’t believe I have changed any paths.

`home-manager switch --flake .` stopped working giving the following error

```sh
[sakshat@nixos:~/nix-config]$ home-manager switch --flake .
warning: Git tree '/home/sakshat/nix-config' is dirty
warning: Git tree '/home/sakshat/nix-config' is dirty
warning: Git tree '/home/sakshat/nix-config' is dirty
warning: Git tree '/home/sakshat/nix-config' is dirty
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating linkGeneration
Cleaning up orphan links from /home/sakshat
No change so reusing latest profile generation 6
Creating home file links in /home/sakshat
Activating onFilesChange
Activating reloadSystemd
Error: Error switching

Caused by:
    0: Failed to build switch plan
    1: No such file or directory (os error 2)```

### Maintainer CC

_No response_

### System information

```markdown
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.11 (Vicuna), 24.11.20240616.b60ebf5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/5w7nhyvrgsa81h0kyifmbl6j97hvlzh5-source`
```

**Comment by radek-stasta** [comment]
Also here: https://discourse.nixos.org/t/home-manager-failing-after-recent-update/47211

**Comment by yswtrue** [comment]
same here

**Comment by radek-stasta** [comment]
Can we get any info about this or if there is something we can do to fix it please? Thanks a lot

**Comment by sakshatshinde** [comment]
> Can we get any info about this or if there is something we can do to fix it please? Thanks a lot

Following commits seem to work.

Home-manager: `a7117efb3725e6197dd95424136f79147aa35e5b`
Nixpkgs: `e8057b67ebf307f01bdcc8fba94d94f75039d1f6`

```nix
# flake.nix
{
    description = "Sakshat's NixOS config";

    inputs = {
      # nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
      nixpkgs.url = "github:nixos/nixpkgs/e8057b67ebf307f01bdcc8fba94d94f75039d1f6";
  
      # home-manager.url = "github:nix-community/home-manager";
      home-manager.url = "github:nix-community/home-manager/a7117efb3725e6197dd95424136f79147aa35e5b";
      home-manager.inputs.nixpkgs.follows = "nixpkgs";
    };

)

**Comment by clhodapp** [comment]
Someone knowledgeable needs to spend time to find the root cause. It's all open source so that could be you, @radek-stasta!

This one is pretty annoying so if no one else steps up, I'll eventually find time to do it...

**Comment by radek-stasta** [comment]
Yes, I can look at it as well, but don't know if I don't do accidentally more damage than it already have :)

**Comment by kkoniuszy** [comment]
`strace` pointed to [a bunch of `ENOENT`s](https://gist.github.com/kkoniuszy/68d917a9617e5009e56b6dd5085ccb72) in `sd-switch`.  
This looks a bit scary, but when comparing straces from the successful and error cases only this one stands out:
`[pid 322531<sd-switch>] openat(AT_FDCWD, "/nix/store/80zcay9zjqrc1fpjv5dnsmxkxs6wxcri-home-manager-generation/home-files/.config/systemd/user", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)`. 

This appears to be related to the update from sd-switch 0.4.0 to 0.5.0 in https://github.com/NixOS/nixpkgs/commit/ddb515d3fd18a464bf0d860b866468d2d8b2f9f1. Downgrading it via an overlay makes `home-manager switch` work properly again and strace output doesn't show any error opening `home-files/.config/systemd/user` anymore.

As a workaround, you can use this overlay (add it to `nixpkgs.overlays` in your home-manager config):
```nix
final: prev: {
  sd-switch = final.callPackage (
    {
      lib,
      fetchFromSourcehut,
      rustPlatform,
      nix-update-script,
    }: let
      version = "0.4.0";
    in
      rustPlatform.buildRustPackage {
        pname = "sd-switch";
        inherit version;

        src = fetchFromSourcehut {
          owner = "~rycee";
          repo = "sd-switch";
          rev = version;
          hash = "sha256-PPFYH34HAD/vC+9jpA1iPQRVNR6MX8ncSPC+7bl2oHY=";
        };

        cargoHash = "sha256-zUoa7nPNFvnYekbEZwtnJKZ6qd47Sb4LZGEkaKVQ9ZQ=";
      }
  ) {};
}
```

**Comment by clhodapp** [comment]
Thanks so much for drilling down to find the cause, @kkoniuszy!

It seems like @rycee should be informed, since `sd-switch` seems to exist primarily to support `home-manager`, so breaking `home-manager` seems like a pretty critical regression.

**Comment by kkoniuszy** [comment]
This is the backtrace from sd-switch:

```
Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/redacted/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/error.rs:565:25
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /build/rustc-1.77.2-src/library/core/src/result.rs:1959:27
   2: sd_switch::find_wanted_units
             at ./src/lib.rs:222:18
   3: sd_switch::build_switch_plan
             at ./src/lib.rs:172:24
```

The relevant line is:
```rust
// src/lib.rs:222:18
    for entry in std::fs::read_dir(new_dir)? {
```

Looks like this fails for home-manager configurations that do not have any systemd user units, as in this case there's no dir with stuff to switch to. Therefore, you can work around this bug without downgrading sd-switch – just add some dummy oneshot service such as this one:

```nix
  # Workaround for sd-switch 0.5.0 bug
  systemd.user.services.sd-switch-0_5_0-bug-workaround = {
    Unit = {
      Description = "Dummy service - workaround for sd-switch 0.5.0 failing when home-manager did not create any user units.";
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.hello}/bin/hello";
      RemainAfterExit = true;
    };
    Install = {
      WantedBy = ["default.target"];
    };
  };
```

It doesn't really seem to be a sd-switch bug though. It is overall a regression, but you can't expect anything to behave right when you give it a nonexistent directory. Home-manager should probably be modified to always create the user units dir even when there won't be anything in it.
