### ISSUE TITLE
Way to prevent systemd service defined using `systemd.user.services.*` from being enabled by default.

### ISSUE THREAD

**Issue by sebastianrasor** [nix-community/home-manager#5580]
### Description

I have a systemd oneshot service that I'd like to only be started using a timer, which I have configured using `systemd.user.timers.*`. The issue is that whenever I run home-manager switch, the oneshot service I configured is enabled which leads to unpredictable start times and interferes with my work. I've confirmed this by manually disabling the service, running `systemctl --user is-enabled myservice.service`, running `home-manager switch --flake .`, and then running `systemctl --user is-enabled myservice.service` again. If there could be some kind of option like `systemd.user.timers.*.enable` which defaults to true, but which I can set to false, that would be great.

**Comment by dawidd6** [comment]
How are you defining your service?

**Comment by sebastianrasor** [comment]
> How are you defining your service?

```
{ ... }: {

...

  systemd.user.services."my-service" = {
    Unit = {
      Description = "My service";
    };

    Service = {
      Type = "oneshot";
      ExecStart = [
        "-/path/to/script"
        "-/path/to/other/script"
      ];
    };
  };

  systemd.user.timers."my-timer" = {
    Unit = {
      Description = "My timer";
      Requires = "my-service.service";
    };

    Timer = {
      OnCalendar = "Wed..Sat 06:45";
      Persist = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };
}
```

**Comment by rycee** [comment]
Does your service file have an `Install.WantedBy` set to some active target? If so it will be started. If you want it to only be started by the timer then don't include the `WantedBy` and instead make sure to have your timer unit contain `Install.WantedBy = [ "timers.target" ];`

**Comment by sebastianrasor** [comment]
> Does your service file have an `Install.WantedBy` set to some active target? If so it will be started. If you want it to only be started by the timer then don't include the `WantedBy` and instead make sure to have your timer unit contain `Install.WantedBy = [ "timers.target" ];`

The service only contains the configurations I posted in my example, the only things I have changed are the names and paths.

**Comment by sebastianrasor** [comment]
```
$ systemctl --user is-enabled my-service.service
not-found
$ home-manager switch --flake .
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating linkGeneration
Cleaning up orphan links from /path/to/my/home
No change so reusing latest profile generation 6
Creating home file links in /path/to/my/home
Activating onFilesChange
Activating reloadSystemd

There are 161 unread and relevant news items.
Read them by running the command "home-manager news".

$ systemctl --user is-enabled my-service.service
linked
```

**Comment by rycee** [comment]
@sebastianrasor Try removing the `Requires = "my-service.service";` line from the timer unit.

**Comment by sebastianrasor** [comment]
> @sebastianrasor Try removing the `Requires = "my-service.service";` line from the timer unit.

Without that requires, nothing will happen. The requires needs to be there to run the scripts that I'd like to run on a schedule. Are you just wanting to see if removing the requires will change the behavior of the `is-enabled` stuff?

**Comment by sebastianrasor** [comment]
I just tried, and removing the `Requires` from the timer unit does not prevent the oneshot service unit from being enabled by Home Manager when running `home-manager switch`

**Comment by rycee** [comment]
Maybe it is just me that is confused but isn't "linked" the expected value for the service file and "enabled" the expected value for the timer file? It should then only be activated by the timer file.

That the units end up in the linked and enabled statuses are, as far as I understand, simply a side-effect of reloading the systemd daemon which may happen at unexpected times anyway.

**Comment by sebastianrasor** [comment]
> Maybe it is just me that is confused but isn't "linked" the expected value for the service file and "enabled" the expected value for the timer file? It should then only be activated by the timer file.
> 
> That the units end up in the linked and enabled statuses are, as far as I understand, simply a side-effect of reloading the systemd daemon which may happen at unexpected times anyway.

Oh you know what, you're right. I had assumed "linked" was a synonym for enabled because I figured that it "links" into the default.target.wants directory. I guess it's time to go down the rabbit hole of figuring out why this service is getting started much more often than I'd like it to.

**Comment by rycee** [comment]
Great! The reason it was started unexpectedly may be the `Requires` line in the timer unit. Presumably that would cause the service unit to be started when the timer is started.

**Comment by sebastianrasor** [comment]
Yeah it looks like `Requires` is not the preferred way to indicate that a timer unit should start a service unit.

The `[Timer]` section should contain an option called `Unit=` which is:
The unit to activate when this timer elapses. The argument is a unit name, whose suffix is not ".timer". If not specified, this value defaults to a service that has the same name as the timer unit, except for the suffix. (See above.) It is recommended that the unit name that is activated and the unit name of the timer unit are named identically, except for the suffix.
