### ISSUE TITLE
bug: Pull request checks fail after removal of jonringer as a nixpkgs maintainer

### ISSUE THREAD

**Issue by LilleAila** [nix-community/home-manager#5588]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After submitting a pull request (#5587), the `Test / tests (ubuntu-latest) (pull_request) ` and `Test / tests (macos-latest) (pull_request)` checks failed. Looking at the output from the checks, this is the error:
```
error: attribute 'jonringer' missing
       at /home/runner/work/home-manager/home-manager/modules/services/pulseeffects.nix:12:24:
           11| in {
           12|   meta.maintainers = [ maintainers.jonringer ];
```
I think this happened following NixOS/nixpkgs#322386

### Maintainer CC

@jonringer 

### System information

```markdown
The issue happened in the pr check action.
```

**Comment by rycee** [comment]
Thanks for the heads up! Hopefully it's resolved now.
