### ISSUE TITLE
Is it possible to use home-manager for configuration-only?

### ISSUE THREAD

**Issue by mainrs** [nix-community/home-manager#5629]
### Description

I am running a Linux distribution with specialized packages that have certain optimizations enabled. However, I find it easier to manage my dotfiles using nix. 

Is there a way to tell home-manager to write and link configuration files of packages but to not install the package itself? The package would be provided through the system I use.

**Comment by Lichthagel** [comment]
You can use `home.packages = lib.mkForce [];`

See https://github.com/nix-community/home-manager/wiki#how-to-use-home-manager-as-pure-configuration-manager-

**Comment by mainrs** [comment]
> You can use `home.packages = lib.mkForce [];`
> 
> See [nix-community/home-manager/wiki#how-to-use-home-manager-as-pure-configuration-manager-](https://github.com/nix-community/home-manager/wiki#how-to-use-home-manager-as-pure-configuration-manager-)

I missed that one! Thank you!
