### ISSUE TITLE
bug: hyprpaper doesn't start when `graphical-session.target` is activated

### ISSUE THREAD

**Issue by wuyoli** [nix-community/home-manager#5634]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

hyprpaper doesn't start when `graphical-session.target` is activated. output of `systemctl status`:
```
$ systemctl status --user hyprpaper
○ hyprpaper.service - hyprpaper
     Loaded: loaded (/home/wuyoli/.config/systemd/user/hyprpaper.service; enabled; preset: enabled)
     Active: inactive (dead)
  Condition: start condition unmet at Thu 2024-07-11 19:48:27 CEST; 10min ago
             └─ ConditionEnvironment=WAYLAND_DISPLAY was not met
```
This started happening when I switched from sddm to lightdm by setting `services.displayManager.enable = true;`  instead of `services.displayManager.sddm.enable = true;`.

### Maintainer CC

@khaneliman 
@fufexan 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```

**Comment by fufexan** [comment]
Right, because lightdm runs on X, not Wayland. Many people have had issues with lightdm, so it's recommended to use either sddm, gdm or greetd.
