### ISSUE TITLE
zoxide, shell integration option

### ISSUE THREAD

**Issue by sjLambda** [nix-community/home-manager#5638]
### Description

I searched for zoxide and bash integration. Did not find this feature request. Although it could've been also filed as a bug with a different name. Anway, under 

`"enableBashIntegration = true;"`

we need another suboption that inserts "--cmd cd" between init and bash. The full completed command would look like this:

`eval $(zoxide init --cmd cd bash)`

but right now, all it does is this:

`eval $(zoxide init bash)`

Would this be considered a feature request? Or, is it doable in another way that the documentaiton does not show?  Thanks much for any help.

**Comment by BackHDLP** [comment]
```nix
programs.zoxide.options = [ "--cmd" "cd" ];
```

**Comment by sjLambda** [comment]
That programs.zoxide.options results in option for zoxide:

`eval $(zoxide init bash --cmd cd)`

when the corrct option is for the init subcommand of zoxide:

`eval $(zoxide init --cmd cd bash)`

**Comment by BackHDLP** [comment]
they do the exact same thing

**Comment by sjLambda** [comment]
Yes indeed, your syntax works. You put each option in separate quotes whereas I put both in one. I don't know why, but good to know not to combine options. Thanks.

**Comment by sjLambda** [comment]
closed
