### ISSUE TITLE
Adding extensions to thunderbird

### ISSUE THREAD

**Issue by Mikilio** [nix-community/home-manager#5654]
### Description

Thunderbirds extension mechanism is the same as Firefox, since Mozilla is working on it again (or since forever I don't really know) allowing to add extensions via nix would be nice.

To add this feature, It would be nice to add thunderbird extensions to @rycee 's NUR, because it already includes all the tools to add these easily by name if they are in the Mozilla's index.

A difference would be that thunderbird doesn't have a sync functionality (at least not [yet](https://blog.thunderbird.net/2023/07/an-update-on-thunderbird-sync/)). In Firefox, I did not care much about configuring extensions because I could store the settings in my Mozilla account, but that's not the case here. It's definitely not urgent, but maybe something to think about.

**Comment by alois31** [comment]
The functionality as implemented in the Firefox module is quite problematic (https://github.com/nix-community/home-manager/issues/5652), and the issue is even worse for Thunderbird since the permissions required for certain actions seem to be less static there (in fact this is exactly how the issue was first noticed to begin with). If you are fine with the same extensions applying to all profiles and a semi-declarative approach, you can use policies to install extensions like this:
```
programs.thunderbird.package = pkgs.thunderbird.override {
  extraPolicies.ExtensionSettings = {
    "[id of the extension here]" = {
      installation_mode = "normal_installed";
      install_url = "[URL to the XPI file here]";
    };
  };
};
```

**Comment by Mikilio** [comment]
Thank you for the Tipp. Do you think there should be an issue to track declarative Mozilla stuff in general?

**Comment by booxter** [comment]
I think this feature is still needed, for the following reasons:

1. There's no darwin derivation at the moment in nixpkgs. Darwin users are using external thunderbird setup (e.g. from homebrew) and cannot wrap the nix derivation around with custom policies for extensions.

2. Even when darwin derivation for base thunderbird-unwrapped is implemented, the wrapper work for the platform is not obvious. It's generally possible to use thunderbird-unwrapped as-is, and that's what I have in my `programs.thunderbird.package`.

It seems to me that having the declarative way to configure these extensions per user is desirable; maybe it should be reopened?

**Comment by Mikilio** [comment]
I do have a similar setup to what you're doing in your PR. But as mentioned by @alois31 there is a valid discussion about how reproducible the current approach is.

**Comment by Mikilio** [comment]
I recommend reading the config by running 
```
cat `which thunderbird | xargs realpath | xargs dirname`/../lib/thunderbird/distribution/policies.json
```
To figure out what your configuration is actually writing. If you discover any issue with that, you can open another issue.
In the more likely case that everything is written as expected, you need to examine the Thunderbird documentation as for why this setting is not working.

I have never actually used this mode of configuration, and it is also not the way encouraged by home-manager since the PR #6033 got merged.
