### ISSUE TITLE
bug: Conflicting `policies.json` files in Firefox

### ISSUE THREAD

**Issue by slotThe** [nix-community/home-manager#5675]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When building the newest commit ([bc2b96ac](https://github.com/nix-community/home-manager/commit/bc2b96acda50229bc99925dde5c8e561e90b0b00), but see below) I run into the following Firefox build failure:

```
home-manager-path> error: collision between `/nix/store/25qa9p51z47ddgkqbilpdpmiyjjdywfw-firefox-128.0.3/lib/firefox/distribution/policies.json' and `/nix/store/rrlgprlzrvycdcywv9l51j9kmhkprfsb-firefox-128.0.3/lib/firefox/distribution/policies.json'
```

I'm not doing any manipulation/creation of policies myself (at least, not consciously or explicitly), so I would assume other users will also run into this. The issue seems to have started showing up with (and I currently fixed it by reverting) https://github.com/nix-community/home-manager/pull/5195. I suppose that the `policies.json` created by that PR doesn't play nice with the one that's [already created by nixpkgs itself](https://github.com/NixOS/nixpkgs/blob/78a13d54da050b1a781af934ddcc1cf5517cde75/pkgs/applications/networking/browsers/firefox/wrapper.nix#L132).

### Maintainer CC

firefox: @ryane @kira-bruneau 
#5195: @nawordar @alois31 

### System information

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11.20240727.48bacf5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/riw3791p6yffw8y5d0p60cmvq1fi04hz-source`
```

**Comment by alois31** [comment]
Do you attempt to install another copy of firefox, for example by putting `firefox` in your `home.packages`? If yes, try removing that.

**Comment by slotThe** [comment]
Hah, indeed that was it! I feel a bit embarrassed, but also intrigued that I should only notice this now. Thanks :)
