### ISSUE TITLE
home-manager: switch to inetutils/hostname

### ISSUE THREAD

**Issue by gauravjuvekar** [nix-community/home-manager#5692]
Seems like the inetutils / GNU version is more robust against failures. This should allow us to remove some of the verification added in #5683.

              Ah we are already using a bunch of GNU tools, then indeed we might as well switch to `inetutils` from GNU. One thing I was worrying about is the availability across platforms, but it should be fine according to the hydra build log:
- [x] https://hydra.nixos.org/job/nixpkgs/trunk/inetutils.aarch64-linux
- [x] https://hydra.nixos.org/job/nixpkgs/trunk/inetutils.aarch64-darwin
- [x] https://hydra.nixos.org/job/nixpkgs/trunk/inetutils.x86_64-darwin
- [x] https://hydra.nixos.org/job/nixpkgs/trunk/inetutils.x86_64-linux

The closure size difference should be insignificant since dependencies can be shared between GNU utilities.

_Originally posted by @bryango in https://github.com/nix-community/home-manager/issues/5683#issuecomment-2259593323_

**Comment by bryango** [comment]
Fixed by #5738.
