### ISSUE TITLE
Allow symlinks for yazi flavor path

### ISSUE THREAD

**Issue by diegodorado** [nix-community/home-manager#5700]
I am very new at nix, so maybe this is not the way I should do this, but i cannot find a good way to reference a yazi flavor because the assertion here looks for a directory:

https://github.com/nix-community/home-manager/blob/6e090576c4824b16e8759ebca3958c5b09659ee8/modules/programs/yazi.nix#L248

I am trying this:

```nix
{ config, pkgs, lib, ... }:

let
  catppuccinTheme = pkgs.runCommand "catppuccin-mocha-yazi"
    {
      src = pkgs.fetchgit {
        url = "https://github.com/yazi-rs/flavors.git";
        rev = "main";
        sparseCheckout = [ "catppuccin-mocha.yazi" ];
        hash = "sha256-9hw6+yDI1KMl0e33ZMnFlitS9eE/dG5qW8b+E7k5Oks=";
      };
    } ''
    ln -s $src/catppuccin-mocha.yazi $out
  '';
in
{
  programs.yazi = {
    enable = true;
    enableZshIntegration = true;
    flavors = {
      "catppuccin-mocha.yazi" = catppuccinTheme;
    };
    theme = {
      flavor = {
        use = "catppuccin-mocha";
      };
    };
  };


}

```

Tried to make a copy instead of symlinking too... but the assertion will fail in evaluation time

**Comment by rycee** [comment]
I don't know yazi but I recall seeing a recent change that makes the `.yazi` suffix in flavors unnecessary. Perhaps

``` nix
flavors = {
  catppuccin-mocha = catppuccinTheme;
}
```

would work?

**Comment by diegodorado** [comment]
Thanks @rycee , but no, it doesn't. I get the same error about a failed assertion

```
error:
       Failed assertions:
       - Value at `programs.yazi.flavors.catppuccin-mocha` is not a valid yazi flavor.
       The path or package should be a directory, not a single file.
       The flavor is missing these files: flavor.toml tmtheme.xml README.md preview.png LICENSE LICENSE-tmtheme
       Evaluated value: `/nix/store/35bwp6fw11s02xbpa929ijv8yq7z6cl1-catppuccin-mocha-yazi`
```

But `/nix/store/35bwp6fw11s02xbpa929ijv8yq7z6cl1-catppuccin-mocha-yazi` exists, only it is a symlink and not a directory so it doesn't satisfies the assertion

**Comment by diegodorado** [comment]
THis is what I ended up doing


```nix
{ pkgs, ... }:

let
  flavors = pkgs.fetchFromGitHub {
    owner = "yazi-rs";
    repo = "flavors";
    rev = "main";
    sha256 = "sha256-/EUaaL08K3F0J0Rn9+XgfKm+W8tekdiWsGxkd892BO8=";
  };

in
{

  config = {

    programs.yazi = {
      enable = true;
      enableZshIntegration = true;
      theme = {
        flavor = {
          use = "catppuccin-mocha";
        };
      };
    };

    xdg.configFile = {
      # flavors
      "yazi/flavors/catppuccin-mocha.yazi".source = "${flavors}/catppuccin-mocha.yazi";
    };

  };

}
```

Although it works fine for me, it is a shame that while the module has a `flavors` attr, I cannot use it.

Maybe it has to do with the fact that I am using flakes and that needs to be pure?

**Comment by diegodorado** [comment]
@texhnolyze , didn't worked for me... i believe it is because i use flakes

**Comment by texhnolyze** [comment]
I'm also using flakes with `home-manager` though, otherwise I wouldn't have suggested my solution:
![image](https://github.com/user-attachments/assets/1d7f3166-ab4c-4853-b69d-da78f2eb6571)
Though, I'm running on stable (`2.18.5`) and `home-manager/master`, maybe that's a difference.

**Comment by diegodorado** [comment]
Oh, thanks for pointing that out @texhnolyze .

I am also new nix user, and it turned out I was running an old `nix` version (2.13) that failed to use the package inside a string with:

```
error: the string 'catppuccin-mocha.yazi' is not allowed to refer to a store path (such as '!out!/nix/store/...-source.drv')
```

I realized then that i had to update `nix` itself along with the rest of packages through home manager, and after that, yes, I was able to run it as you said, thanks.
