### ISSUE TITLE
Support for crontabs

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/home-manager#571]
Something similar to the `systemCronJobs` option (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/scheduling/cron.nix#L52) would be useful.

**Comment by rycee** [comment]
Should be possible to create such a module, I won't have time to do it but would be happy to review a PR.

Otherwise I would say that the recommended way to run commands periodically is to use a systemd timer.

**Comment by murdos** [comment]
I would be interested too by this feature!
