### ISSUE TITLE
bug: `home-manager switch --flake .` on non-NixOS simply returns exit code 1 without any output

### ISSUE THREAD

**Issue by kenranunderscore** [nix-community/home-manager#5711]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

(The outcome of this issue looks similar to #5688, but where I don't get an error, the other issue does get one).

After 89670e27e101b9b30f5900fc1eb6530258d316b1 (introduced by #5683) my command `home-manager switch --flake ~/dotfiles --impure --debug --show-trace` simply returns exit code 1 without any message. The parent commit 792757f643cedc13f02098d8ed506d82e19ec1da still works for me. (I manually bisected this by trying a couple of commits, as I had updated only a week before, but I'm pretty sure that's the relevant commits).

Let me know if I can support in testing/debugging this.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.3_2, Void, noversion, nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.3`
 - nixpkgs: `/home/void/.nix-defexpr/channels/nixpkgs`
```

**Comment by mainrs** [comment]
Maybe I get an error message because I am using [lix](https://lix.systems) instead of nix. I did also pass the `--show-trace` flag.

**Comment by mhersson** [comment]
I have the same problem - adding `127.0.1.1 <myhostname>` to `/etc/hosts`  seems to remedy the problem.

**Comment by tom-kuca** [comment]
I have the same problem too.

@gauravjuvekar I believe it was introduced in https://github.com/nix-community/home-manager/pull/5683. I added `set -x` and run `home-manager --flake . switch`, here are the last lines of the output:

```
...
+ local generation
+ generation=/tmp/home-manager-build.TmnayQAUjH/generation
+ setFlakeAttribute
+ [[ -z . ]]
+ [[ -n . ]]
+ local flake=.
+ case $FLAKE_ARG in
+ local name=tomas
+ hostnameArray=()
+ local hostnameArray
+ local fqdn
+ echo 'BEFORE FQDN '
BEFORE FQDN 
++ hostname -f
hostname: Unknown host
+ fqdn=
+ rm -r /tmp/home-manager-build.TmnayQAUjH
```

After the change, `set -e`¹ stops the execution if `hostname -f` fails.

¹ https://github.com/gauravjuvekar/home-manager/blob/89670e27e101b9b30f5900fc1eb6530258d316b1/home-manager/home-manager#L6

**Comment by gauravjuvekar** [comment]
Ah, I completely missed that we have a file-wide `set -e` here https://github.com/nix-community/home-manager/blob/89670e27e101b9b30f5900fc1eb6530258d316b1/home-manager/home-manager#L6

**Comment by gauravjuvekar** [comment]
@tom-kuca Can you test with https://github.com/gauravjuvekar/home-manager/commit/3b13d96016e7e4f2b5a7f51f7ddc6fcaebfbb4c7

**Comment by bryango** [comment]
This is partially my fault for not testing #5683 thoroughly... Cooked up an emergency PR in #5738.

**Comment by tom-kuca** [comment]
> @tom-kuca Can you test with [gauravjuvekar@3b13d96](https://github.com/gauravjuvekar/home-manager/commit/3b13d96016e7e4f2b5a7f51f7ddc6fcaebfbb4c7)

The patch fixes  the issue for me. Both bryango's solutions works too.
