### ISSUE TITLE
bug: safeeyes shows an error message instead of a tray icon

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#5728]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Starting SafeEyes shows an error message

> The required plugin 'Tray Icon' is missing dependencies!

followed by a link [Click here for more information](https://github.com/slgobinath/SafeEyes/wiki/How-to-install-backend-for-Safe-Eyes-tray-icon).

![image](https://github.com/user-attachments/assets/645bdbfa-0133-4c47-8ec2-915a190d59f6)

The documentation says we should start [snixembed](https://git.sr.ht/~steef/snixembed#building-and-installing).

How to reproduce:

```nix
{
  services.safeeyes.enable = true;
}
```

or just install safeeyes and execute it.

### Maintainer CC

@Rosuavio

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.3-200.fc40.x86_64, Fedora Linux, 40 (Workstation Edition), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs"`
 - channels(temp): `"home-manager, nixpxkgs"`
 - channels(cassou): `"home-manager-22.11.tar.gz, nixpkgs"`
 - nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`
```

**Comment by archisman-panigrahi** [comment]
Which desktop environment are you using?

**Comment by DamienCassou** [comment]
I'm on Fedora Linux with i3wm.

**Comment by archisman-panigrahi** [comment]
Can you try the snixembed solution described in the wiki? Also, can you try the native package using pip? People have reported that it works in i3 https://github.com/slgobinath/SafeEyes/issues/617#issuecomment-2270670446

**Comment by DamienCassou** [comment]
sorry for the delay @archisman-panigrahi

> Can you try the snixembed solution described in the wiki?

starting snixembed before SafeEyes make SafeEyes appear correctly. I thought this was the only solution so I opened this issue in home-manager rather than in SafeEyes. Do you agree?

> can you try the native package using pip?

I have tried but installing with pip complains while compiling cairo. I could investigate further but I don't much of the python ecosystem.

**Comment by archisman-panigrahi** [comment]
> starting snixembed before SafeEyes make SafeEyes appear correctly. I thought this was the only solution so I opened this issue in home-manager rather than in SafeEyes. Do you agree?

This is normal and expected behavior in the latest version of safeeyes. i3 does not have the necessary backend for the trayicon technology we are using. Snixembed acts like a bridge in this case. 

Full fledged DEs like KDE or XFCE don't need snixembed.

**Comment by archisman-panigrahi** [comment]
I think there is no bug here

**Comment by DamienCassou** [comment]
@archisman-panigrahi: that was my impression as well, thank you for confirming!

@rycee: we probably need a service for snixembed. The question I have is what kind of API we want given that:

1. not everyone will need snixembed
2. the others will want it to be started before SafeEyes

Should there be an option in SafeEyes module or are the two modules completely separate?

**Comment by archisman-panigrahi** [comment]
In my opinion, it should be left to the user to install snixembed if they want (safeeyes presents them a link which has detailed instruction of how to install). snixembed is really not a dependency of safeeyes. It is rather required because i3/lxde/mate(without Ubuntu's customizations) etc. do not have out-of-the-box support for kstatusnotifier.
