### ISSUE TITLE
bug: borgmatic service borked permissions

### ISSUE THREAD

**Issue by sdaqo** [nix-community/home-manager#5749]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The borgmatic service is failing since 2024-08-11 with this error:
```
× borgmatic.service - borgmatic backup
     Loaded: loaded (/home/paul/.config/systemd/user/borgmatic.service; linked; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-08-17 16:07:06 CEST; 18min ago
TriggeredBy: ● borgmatic.timer
    Process: 698364 ExecStartPre=/nix/store/xfm4mg874w5n39zbqx24yiw7hmka94n7-coreutils-9.5/bin/sleep 3m (code=exited, status=214/SETSCHEDULER)
        CPU: 329us

Aug 17 16:07:06 nixos-desktop systemd[3651]: Starting borgmatic backup...
Aug 17 16:07:06 nixos-desktop (sleep)[698364]: borgmatic.service: Failed to set up CPU scheduling: Operation not permitted
Aug 17 16:07:06 nixos-desktop systemd[3651]: borgmatic.service: Control process exited, code=exited, status=214/SETSCHEDULER
Aug 17 16:07:06 nixos-desktop systemd[3651]: borgmatic.service: Failed with result 'exit-code'.
Aug 17 16:07:06 nixos-desktop systemd[3651]: Failed to start borgmatic backup.
```

### Maintainer CC

@DamienCassou 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.05 (Uakari), 24.05.20240810.a781ff3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/61502m9h1jl40j7sxbcyjdm6qi1k7x97-source`
```

**Comment by DamienCassou** [comment]
I'm unfortunately suffering from the same problem and haven't found a solution yet.

**Comment by sdaqo** [comment]
I think one of these is triggering the perm errors, but who knows why it happened so suddenly.
https://github.com/nix-community/home-manager/blob/086f619dd991a4d355c07837448244029fc2d9ab/modules/services/borgmatic.nix#L48C1-L53C1

**Comment by sdaqo** [comment]
I saw this: https://github.com/Nefelim4ag/systemd-swap/issues/160

**Comment by AmeerTaweel** [comment]
I'm facing the same issue. I would love to help but I have no idea how. I would appreciate it if you give me some pointers.

**Comment by sdaqo** [comment]
You could try commenting out the lines I marked in the link, tho this is probably not the root cause, but beyond that I am none the wiser. I would try but do not have access to any computer rn.

**Comment by DamienCassou** [comment]
Another thing that is worth trying: go back in the past and tell me which commit of nixpkgs or home-manager started the problem.

@sdaqo @AmeerTaweel are you on NixOS or another distribution (and which one)?

**Comment by AmeerTaweel** [comment]
Yes, I'm using NixOS 24.11. I will try finding the commit using `git bisect` tonite or tomorrow.

**Comment by AmeerTaweel** [comment]
I did some bisecting and figured out that `nixpkgs` commit `b9fb14ccf62a39df41a2a92e2bad2777c62ab914` is good. Now `git bisect` wants me to test `4c086d8ee04004eceadc2e9f3bc2e08163cdd677` but building the derivation is taking forever. I guess some core package was modified or something.

**Comment by sdaqo** [comment]
Awesome, maybe just git bisect skip on the one that doesn't build. Sorry that I can't help out but I think we are getting somewhere!

**Comment by AmeerTaweel** [comment]
Thanks @sdaqo, I didn't know about `git bisect skip`. I used it to skip two commits that were taking long to build. I finished the process and I found that `4ca52fdf5f0da995fc26e7d07c6c30a710ed4f8a` is the first bad commit.

I'm attaching the configuration I used for testing:
[test.zip](https://github.com/user-attachments/files/16741262/test.zip)

I hope this helps @DamienCassou

**Comment by JuanGarcia345** [comment]
> I think one of these is triggering the perm errors, but who knows why it happened so suddenly. https://github.com/nix-community/home-manager/blob/086f619dd991a4d355c07837448244029fc2d9ab/modules/services/borgmatic.nix#L48C1-L53C1

According to the table 9 in [systemd.exec manpage](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html), the service error status (`status=214/SETSCHEDULER`) is  directly linked to the parameter `CPUSchedulingPolicy`. I wouldn't be able to say how or why the systemd or kernel settings have changed to lead to this behavior (on NixOS 24.05) but [sched_setscheduler(2)](https://man7.org/linux/man-pages/man2/sched_setscheduler.2.html) does not specify what are the required privileges to change the CPU scheduling.

I'd say that the `Nice` parameter would be enough to set the execution priority for this service (19 gives a very low priority), that is `CPUSchedulingPolicy` can be safely removed (I've tested by duplicating the SystemD units and verifying the priority of the spawned processes).

**Comment by mputz86** [comment]
Maybe it helps some one; this creates an override for the default service definition and unsets the problematic part. Does work on my side :thinking: 

```nix
  home.file."${config.xdg.configHome}/systemd/user/borgmatic.service.d/override.conf".text
  = ''
    [Service]
    CPUSchedulingPolicy=
  '';
```

**Comment by AmeerTaweel** [comment]
Thanks for the workaround. It works for me. I will keep using it until we have a fix.

**Comment by DamienCassou** [comment]
Thank you for your investigation @AmeerTaweel. Unfortunately, I have no clue why this commit would cause any issue: https://github.com/NixOS/nixpkgs/commit/4ca52fdf5f0da995fc26e7d07c6c30a710ed4f8a.

I confirm the workaround. Any of you wants to submit a PR removing this line?

**Comment by ZlobnuDima** [comment]
I'm sorry but English isn't my native language and I can misunderstood something.
Are you sure that this bug is fixed in your repo or I have to use the workaround described above?
I get the same issue right now.

**Comment by sdaqo** [comment]
@ZlobnuDima Do you use the master or the 24.05 release branch? If you are on the 24.05 branch the pr might not have been merged in yet or you may have to update your inputs if using flakes.

**Comment by ZlobnuDima** [comment]
@sdaqo , I use flakes and, I suppose I understood you right, I use this inputs in my _flake.nix_:
```
 inputs = {   
         nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";   
         home-manager = {   
         url = "github:nix-community/home-manager/release-24.05";   
         inputs.nixpkgs.follows = "nixpkgs";   
    };
}; 
```

So, I need to wait?

**Comment by sdaqo** [comment]
Yeah just use the fix @mputz86 mentioned in the meantime.

**Comment by ZlobnuDima** [comment]
> Yeah just use the fix @mputz86 mentioned in the meantime.
> 
> Edit: You can also run `nix flake update` (and rebuild the system) from time to time to keep your inputs up to date, this will pull the fix if it gets merged into 24.05.

Thanks. It's done and it works.

**Comment by rycee** [comment]
Please clarify, does the https://github.com/nix-community/home-manager/pull/5837 change need to be cherry-picked for the 24.05 branch?

**Comment by sdaqo** [comment]
@rycee That would be nice as the  borgmatic service is completely broken without it.

**Comment by rycee** [comment]
@sdaqo Ok, cherry-picked now.
