### ISSUE TITLE
PRs against stable Nixpkgs?

### ISSUE THREAD

**Issue by nyarly** [nix-community/home-manager#577]
I began the process of a PR against home-manager and was quickly stymied. CONTRIBUTING.md makes it clear that you want PRs against master, but I can't get either of (home-manager:master, nixos-18.09) or (home-manager:master, nixos-unstable) to build with my configuration. I know that 19.03 is due to be released relatively soon, but is there a process to issue PRs against the 18.09 tag of home-manager?

**Comment by rycee** [comment]
If the change is specific for 18.09 then absolutely make a PR against the release-18.09 branch. I'll clarify the docs on this.

On February 11, 2019 2:23:08 AM GMT+01:00, Judson Lester <notifications@github.com> wrote:
>I began the process of a PR against home-manager and was quickly
>stymied. CONTRIBUTING.md makes it clear that you want PRs against
>master, but I can't get either of (home-manager:master, nixos-18.09) or
>(home-manager:master, nixos-unstable) to build with my configuration. I
>know that 19.03 is due to be released relatively soon, but is there a
>process to issue PRs against the 18.09 tag of home-manager?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rycee/home-manager/issues/577

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
