### ISSUE TITLE
add module: neovide

### ISSUE THREAD

**Issue by TanvirOnGH** [nix-community/home-manager#5791]
Neovide is a simple, no-nonsense, cross-platform graphical user interface for Neovim with tons of features and animations.

Homepage: [neovide.dev](https://neovide.dev)
Repository: https://github.com/neovide/neovide

**Comment by TanvirOnGH** [comment]
There has been an attempt: https://github.com/nix-community/home-manager/pull/5774

**Comment by NitroSniper** [comment]
I'll reintroduced my PR tomorrow morning up to date, I closed it due to me accidentally messing up with the branch name

**Comment by NitroSniper** [comment]
This issue can be closed now @TanvirOnGH

**Comment by TanvirOnGH** [comment]
You're awesome
