### ISSUE TITLE
Atuin daemon option

### ISSUE THREAD

**Issue by SolidRhino** [nix-community/home-manager#5797]
### Description

Add an option to manage the Atuin daemon with a user service.

[daemon](https://docs.atuin.sh/reference/daemon/#atuin-daemon)

**Comment by opeik** [comment]
Here's the nix-darwin config I used to start the daemon:
```nix
launchd.user.agents.atuin = {
  command = "${pkgs.atuin}/bin/atuin daemon";
  serviceConfig = {
    RunAtLoad = true;
    StandardOutPath = "/tmp/atuin.log";
  };
};
  ````

**Comment by dbaynard** [comment]
The following (via atuinsh/atuin#2039) uses the daemon feature. This ought to be supported in the linux version.

https://github.com/Nemo157/dotfiles/blob/a470d7f442b2ba584d5462f6d5581264ccbaec49/home/cli/atuin.nix#L51-L83

> ```nix
>   systemd.user.services.atuin-daemon = {
>     Unit = {
>       Description = "atuin shell history daemon";
>       Requires = [ "atuin-daemon.socket" ];
>     };
>     Service = {
>       ExecStart = "${lib.getExe pkgs.atuin} daemon";
>       Environment = [ "ATUIN_LOG=info" ];
>       Restart = "on-failure";
>       RestartSteps = 5;
>       RestartMaxDelaySec = 10;
>     };
>     Install = {
>       Also = [ "atuin-daemon.socket" ];
>       WantedBy = [ "default.target" ];
>     };
>   };
>
>
>   systemd.user.sockets.atuin-daemon = {
>     Unit = {
>       Description = "Unix socket activation for atuin shell history daemon";
>     };
>
>
>     Socket = {
>       ListenStream = "%t/atuin.socket";
>       SocketMode = "0600";
>       RemoveOnStop = true;
>     };
>
>
>     Install = {
>       WantedBy = [ "sockets.target" ];
>     };
>   };
> ```

I'm about to test: if it's fine, I can contribute.

**Comment by water-sucks** [comment]
Oh man I didn't see this, I just made a PR! #5946, it's pretty similar to your implementation though @dbaynard.

**Comment by dbaynard** [comment]
Ah, not my implementation but I figured I'd make the link. Glad it's similar! 

I haven't tested a launchd variant, yet.
