### ISSUE TITLE
bug: Firefox container lastUserContextId is incorrect

### ISSUE THREAD

**Issue by Faeranne** [nix-community/home-manager#5810]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When manually setting up containers, the `lastUserContextId` field is set to the context id of the last container reported from `mapAttrsToList`.  Since `mapAttrsToList` uses the key as part of its sort order, this results in the last alphabetical entry being used, rather than the entry with the largest context id.  Since context id defines the order containers show up in the new container list, this forces all user containers to be in alphabetical order, which is not always desirable.  Some container management tools will add new containers during usage (such as Temporary Containers), which are intended to be deleted after.  This results in those temporary containers using the `lastUserContextId` (which is correct) and over-riding existing containers.

Suggest finding the largest context id using fold instead.  It's a bit more work, but would prevent this error from happening.

Example of broken results: (pulled directly from my own nix config https://git.faeranne.com/faeranne/nix-config/src/branch/rebuild2/users/nina/desktop.nix)
```nix
{...}:{
  programs = {
    firefox = {
      profiles.default = {
        containers = {
          personal = {
            color = "orange";
            icon = "fingerprint";
            id = 0;
            name = "Personal";
          };
          google = {
            color = "red";
            icon = "circle";
            id = 1;
            name = "Youtube";
          };
          finance = {
            color = "green";
            icon = "dollar";
            id = 2;
            name = "Finance";
          };
          homelab = {
            color = "red";
            icon = "fingerprint";
            id = 3;
            name = "Homelab";
          };
        };
        containersForce = true;
      };
    };
  };
}
```

This results in `"lastUserContextId":2` which means temporary containers first take over the homelab container.

### Maintainer CC

@brckd

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.46, NixOS, 24.05 (Uakari), 24.05.20240822.797f7dc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/5z81la6av4j0ckp0w1949lxiwjyyykks-source`
```
EDIT: I copied the lastUserContextId example from my old terminal history after testing the below edit.  Fixed to the correct result from the above code

**Comment by Faeranne** [comment]
https://github.com/nix-community/home-manager/blob/aaebdea769a5c10f1c6e50ebdf5924c1a13f0cda/modules/programs/firefox/mkFirefoxModule.nix#L105
Replacing this line with `foldlAttrs (acc: _: value: if value.id > acc then value.id else acc) 0 containers;` seems to fix the issue cleanly.

**Comment by brckd** [comment]
Well noted! Can you file a PR with your suggested fix?

**Comment by Faeranne** [comment]
I can certainly try.  Let me look through the requirements real quick so I know what I'm getting into.  I mostly wanna make sure it gets backported to 24.05 soonish so I can go back to the official fork, so I wanna make sure everything is right to make that work.

**Comment by Faeranne** [comment]
PR opened.  Hopefully I got everything right.

**Comment by Faeranne** [comment]
I guess the close comment on the pr doesn't close this.  I'm gonna close this now, but I do want to ask if anything needs to be done for 24.05 backporting?  Not sure if that will just get picked up at some point, or if I should take additional action for that?

**Comment by rycee** [comment]
@Faeranne Sorry I missed the fact that this should be backported to the 24.05 branch. Done now, please give it a try.
