### ISSUE TITLE
mbsync: update module for v1.5.0

### ISSUE THREAD

**Issue by antonmosich** [nix-community/home-manager#5884]
`isync` had a new release v1.5.0 in August, and the update has been merged into nixpkgs master a few days ago (see https://github.com/NixOS/nixpkgs/pull/331813). The update introduces several breaking changes, the details of which can be seen on https://sourceforge.net/projects/isync/files/isync/1.5.0/. See #3317 as well for an issue specific to one of those changes.

Maintainer ping: @KarlJoad

**Comment by KarlJoad** [comment]
Looking at isync's change notes, this is what I see needs to be done on home-manager's end:

- [ ] Default to XDG `$HOME/.config/isync/mbsyncrc` (https://github.com/nix-community/home-manager/blob/04213d1ce4221f5d9b40bcee30706ce9a91d148d/modules/programs/mbsync.nix#L270)
- [ ] Rename `SSLVersions` to `TLSVersions` (https://github.com/nix-community/home-manager/blob/04213d1ce4221f5d9b40bcee30706ce9a91d148d/modules/programs/mbsync.nix#L33)

Is there anything I missed @antonmosich?

**Comment by antonmosich** [comment]
Thank you for the quick response. Those are the changes I noticed as well. I have some other errors appear when testing, but I think those are due to configuration errors on my side.
I just didn't want to open a potentially incomplete PR, because I don't understand mbsync thoroughly enough.

**Comment by KarlJoad** [comment]
Feel free to drop the other errors you are getting here. I have moved off of NixOS and home-manager, so I cannot as easily test as I could in the past. I would like to get as much as I can fixed at once rather than have many issues opened one at a time.

**Comment by antonmosich** [comment]
I've looked into it and been able to fix it (although I think it could've been done better). The "Maildir Path cannot be nested into Inbox anymore" is the change that caused the errors. Now for _my_ configuration it only shows the deprecation notice for SSLVersions.

**Comment by peterhoeg** [comment]
`SSLType` has also changed to `TLSType`

**Comment by KarlJoad** [comment]
From my searching, the `SSLVersions` option is not an explicit option that can be used (You cannot say `sslVersions = [ "TLSv1.2" ... ];` somewhere. Please correct me if I am wrong, and point me in the right direction. home-manager has changed significantly since I last looked at it.

From what I see, you must set `TLSVersion` in an `extraConfig.account` attrset, which means you must rename your option. I can always add a check to alert the user, but that's the most I can do.
