### ISSUE TITLE
bug: firefox: the option `programs.firefox.languagePacks' does not exist

### ISSUE THREAD

**Issue by artur-sannikov** [nix-community/home-manager#5917]
### Are you following the right branch?

- [x] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

This feature was [merged](https://github.com/nix-community/home-manager/pull/5195) but it does not exist.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.11-200.fc40.x86_64, Fedora Linux, 40.20240927.0 (Kinoite), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.2`
 - nixpkgs: `/nix/store/l0l5kmr4iwbngj0df58g61nv2im0y2i3-source`
```

**Comment by brckd** [comment]
What happens when you try to set it regardless?

**Comment by brckd** [comment]
That shouldn't be possible, I even tested that option in #5840. Are you sure you aren't accidentally using the NixOS Firefox module? If possible please link your configuration.
Are there errors if you don't set `firefox.languagePacks`? If not, does setting `firefox.preferences` to `{}` produce an error?

**Comment by artur-sannikov** [comment]
As far as I know, I don't use the NixOS Firefox module. I need to test this config on my other machine with NixOS, though.

Here is my config: https://codeberg.org/arsann/nixos/src/branch/devel

No errors, if I don't set `languagePacks`. `firefox.preferences` results in the same error.

**Comment by brckd** [comment]
Wouldn't have noticed it myself! 😆
