### ISSUE TITLE
[Ques]: Any service is not starting by self. 

### ISSUE THREAD

**Issue by niksingh710** [nix-community/home-manager#5921]
I have recently setted up impermanence could be because of that.

but any service like `hypridle.service, kdeconnect-indicator.service` is not starting by default when the build is done.

even if i do `systemctl --user enable --now hypridle.service` the services goes to dead state after reboot.

if it is because of impermanence can anyone tell me what file to preserve? and if not then is it a hm issue?

**Comment by rycee** [comment]
You'll need `systemd.user.startServices = true` in your configuration. With a bit of luck that won't be necessary much longer as I intend to make that the default.

**Comment by niksingh710** [comment]
> You'll need `systemd.user.startServices = true` in your configuration. With a bit of luck that won't be necessary much longer as I intend to make that the default.

I have just added this and in repl the reported value `sd-switch`.

still after rebooting or rebuilding the services are in dead state.

**Comment by niksingh710** [comment]
nvm i needed `--all` in dbus-activation-systemd
