### ISSUE TITLE
bug: Nushell environment variables are broken

### ISSUE THREAD

**Issue by tukanoidd** [nix-community/home-manager#5984]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Nushell sessionVariables integration code gets this kind of output in env.nu:
```nu
load-env {
    "CLUTTER_BACKEND": "\"wayland\""
    "EDITOR": "\"hx\""
    "GDK_BACKEND": "\"wayland,x11\""
    "GNUPGHOME": "\"/home/{user}/.local/share/gnupg\""
    "GTK2_RC_FILES": "\"/home/{user}/.gtkrc-2.0\""
    "LOCALE_ARCHIVE_2_27": "\"/nix/store/6n9i2bqz9s76ylvc2l8r9ld72vcr2v0a-glibc-locales-2.40-36/lib/locale/locale-archive\""
    "PASSWORD_STORE_DIR": "\"/home/{user}/.local/share/password-store\""
    "QT_AUTO_SCREEN_SCALE_FACTOR": "\"1\""
    "QT_QPA_PLATFORM": "\"wayland;xcb\""
    "QT_QPA_PLATFORMTHEME": "\"adwaita\""
    "QT_STYLE_OVERRIDE": "\"adwaita-dark\""
    "QT_WAYLAND_DISABLE_WINDOWDECORATION": "\"1\""
    "SDL_VIDEODRIVER": "\"wayland\""
    "XDG_CACHE_HOME": "\"/home/{user}/.local/cache\""
    "XDG_CONFIG_HOME": "\"/home/{user}/.config\""
    "XDG_DATA_HOME": "\"/home/{user}/.local/share\""
    "XDG_STATE_HOME": "\"/home/{user}/.local/state\""
}
```

The problem is that the variables get double-quoted for some reason, creating issues with all the applications that use any of these env vars, creating new files in wrong paths (that start with '"' due to how nushell interprets these). This issue did not exist before with the previous '$env.{var} = "..."' approach, as it produced correct strings:
```nu
$env.CLUTTER_BACKEND = "wayland"
$env.EDITOR = "hx"
$env.GDK_BACKEND = "wayland,x11"
$env.GNUPGHOME = "/home/{user}/.local/share/gnupg"
$env.GTK2_RC_FILES = "/home/{user}/.gtkrc-2.0"
$env.LOCALE_ARCHIVE_2_27 = "/nix/store/49pqyidvmqb8gi9gf6bimyj2mba936y8-glibc-locales-2.39-52/lib/locale/locale-archive"
$env.PASSWORD_STORE_DIR = "/home/{user}/.local/share/password-store"
$env.QT_AUTO_SCREEN_SCALE_FACTOR = "1"
$env.QT_QPA_PLATFORM = "wayland;xcb"
$env.QT_QPA_PLATFORMTHEME = "adwaita"
$env.QT_STYLE_OVERRIDE = "adwaita-dark"
$env.QT_WAYLAND_DISABLE_WINDOWDECORATION = "1"
$env.SDL_VIDEODRIVER = "wayland"
$env.XDG_CACHE_HOME = "/home/{user}/.local/cache"
$env.XDG_CONFIG_HOME = "/home/{user}/.config"
$env.XDG_DATA_HOME = "/home/{user}/.local/share"
$env.XDG_STATE_HOME = "/home/{user}/.local/state"
```

An example of what im talking about (screenshot of filetree of a project i work on in tandem with direnv)
![image](https://github.com/user-attachments/assets/258ae72e-5537-4c9e-b5ad-c3c130c8ebad)

This issue appeared last week when I tried upgrading and hoped this would be found and fixed by now, but I was wrong to make that assumption clearly. (And yes, this is still happenning with the latest commit of hm, tried flake updat'ing couple hours ago)

### Maintainer CC

@Philipp-M @JoaquinTrinanes 

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.11-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241008.f6f24b0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/ycfb5fhsyk1h1pr5ql2lhdsnydl4l627-source`
```

(I already rolled back to last working config, as it's impossible for me to use the system if i update the flake)

**Comment by JoaquinTrinanes** [comment]
How are you defining those variables in your config? They work fine on my end.

We added support for nushell basic types in #5905, partly to fix existing configs breaking because values now require to be quoted. So if you escaped them yourself that's not necessary anymore ✨ 

If you want, you can now use `lib.hm.nushell.mkNushellInline "{|| 'raw nushell code'}"` to embed nushell code in your config.

**Comment by tukanoidd** [comment]
Here's my definitions (left - hm, right - nixos module level)
![image](https://github.com/user-attachments/assets/895bff4b-1479-4c55-b1a0-78fcc12d99f8)

Pretty sure i don't double quote anything?

**Comment by JoaquinTrinanes** [comment]
You don't show how  `programs.nushell.environmentVariables` is set in the screenshots. That config won't affect the resulting `env.nu` on its own

**Comment by tukanoidd** [comment]
I'm an idiot, I completely forgot i did this a while ago
```nix
programs.nushell.environmentVariables = builtins.mapAttrs (name: value: "\"${builtins.toString value}\"") config.home.sessionVariables;
```
:sweat_smile: my bad, thanks for pointing it out! I'll check now

**Comment by tukanoidd** [comment]
Taking a while to rebuild, imma go home now and try then, dont wanna stay overtime at the office :smile:
