### ISSUE TITLE
bug: error: 'utillinux' has been renamed to/replaced by 'util-linux'

### ISSUE THREAD

**Issue by elmarsto** [nix-community/home-manager#5991]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

flake-based config ran fine until build today. Last build was a week ago, maybe two. Did `nix flake update` (this is flake-based build) and then `home-manager switch --flake`. Got:

![image](https://github.com/user-attachments/assets/8e13bec4-a1a5-4430-9382-ceb26be0ae2f)

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.6.53, NixOS, 24.11 (Vicuna), 24.11.20241020.1997e4a`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.24.9`
- channels(lattice): `""`
- channels(root): `"nixos-23.11"`
- nixpkgs: `/etc/nix/path/nixpkgs`
```
```

**Comment by elmarsto** [comment]
@robhanlon22  my nixpkgs _is_ nixpkgs-unstable:

![image](https://github.com/user-attachments/assets/6015b105-3bcb-43b8-a9fd-1c5298499678)

**Comment by elmarsto** [comment]
I guess I'll wait for the upstream fix and see what shakes in a day or two.

**Comment by kyp0717** [comment]
@robhanlon22 Thank you!  That was it!  Make sure you are referencing `nixpkgs-unstable`  NOT `nixos-unstable`.

**Comment by nakoo** [comment]
Could you pin this issue or related PR?

**Comment by pinpox** [comment]
Note that running from nixpkgs-unstable is quite adventurous and not something I would recommend long-term.

**Comment by M4RC3L05** [comment]
Hey, I am facing the same error but I am not using flakes I did the standalone install, what should I do in my case?

**Comment by pinpox** [comment]
You can create an overlay with an alias to the old package name until the fix has reached your nixpkgs branch. Something long these lines should work:

```nix
    nixpkgs.overlays = [ (self: super: { utillinux = super.util-linux; })];
```

**Comment by M4RC3L05** [comment]
Thx will try

**Comment by Yohh** [comment]
> Hey, it not did it for me
> 
> ```nix
> {
>   config,
>   pkgs,
>   lib,
>   ...
> }:
> let
>   nixgl = import <nixgl> { };
>   nixpkgsUnstable = import <nixpkgs-unstable> { };
> in
> {
>   nixpkgs.overlays = [
>     (self: super: {
>       utillinux = super.util-linux;
>     })
>   ];
>   ...
> }
> ```
> 
> But doing `home-manager switch` still get the error `error: 'utillinux' has been renamed to/replaced by 'util-linux'`.
> 
> Tried to use `nixpkgsUnstable.util-linux` instead of `super.util-linux`, but it did not work either.
> 
> Still a bit noob with the hole nix and home-manager stuff, so please bear with me.

worked for me by adding it in `configuration.nix`

**Comment by M4RC3L05** [comment]
I am on arch linux and i only have a home.nix files with the contents i posted above. Do i need to do something extra since i am not using nixos?

**Comment by Yohh** [comment]
not sure, but you should have at least a configuration module called by your flake (same as your home-manager), that's the way I installed it on a macbook, it seems this is where you should add it

**Comment by M4RC3L05** [comment]
I do not use flakes, i did the standalone installation, after installing nix using the single-user installation.

**Comment by M4RC3L05** [comment]
nope, no file there

**Comment by JonnieCache** [comment]
I managed to fix this using the overlay given here by following this material:

https://nixos-and-flakes.thiscute.world/nixpkgs/overlays

**Comment by hubert3158** [comment]
> @elmarsto you’re on nixos-unstable, which lags behind nixpkgs-unstable.

Thanks a lot bro. been struggling for a couple days

**Comment by rycee** [comment]
Home Manager itself has no reference to utillinux, so I think this can be closed. Any problem you encounter w.r.t utillinux will be due to something external to HM.
