### ISSUE TITLE
bug: config.lib.nixGL.wrap overrides programs.chromium.commandLineArgs

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#6016]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

In #5355, @Smona, @vigress8, @rycee, @exzombie and a few others collaborated to add the nixGL modules. This is great as it simplifies my configuration. Thank you very much.

Nevertheless, the support for Chromium seems problematic.

Here is an example configuration:

```nix
{
  programs.chromium = {
    enable = true;
    package = config.lib.nixGL.wrap pkgs.ungoogled-chromium;
    commandLineArgs = [
      "--extension-mime-request-handling=always-prompt-for-install"
      "--enable-features=ClearDataOnExit"
      "--no-default-browser-check"
      "--incognito"
    ];
  };
}
```

This generates a `chromium` executable script which doesn't contain my `commandLineArgs` anymore.

Workaround: remove `config.lib.nixGL.wrap` from `programs.chromium.package` to get the command line arguments back.

### Maintainer CC

@Smona 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.11.4-201.fc40.x86_64, Fedora Linux, 40 (Workstation Edition), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - channels(temp): `"home-manager, nixpxkgs"`
 - channels(cassou): `"home-manager-22.11.tar.gz, nixpkgs"`
 - nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`
```

**Comment by Smona** [comment]
I wonder if we could override `override` on the wrapper derivation returned by `nixGL.wrap`, so that it basically maps `(nixGL.wrap pkg).override { args }` to `(nixGL.wrap (pkg.override { args }))`.

**Comment by DamienCassou** [comment]
Thank you very much @Smona and @rycee.
