### ISSUE TITLE
bug: unable to open kitty program

### ISSUE THREAD

**Issue by kwigley** [nix-community/home-manager#6025]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

After upgrading MacOS to 15.1, I'm unable to open kitty program.

```bash
❯ open '/nix/store/wiindrplkcj1mn22x6nbl8clpnz7adpm-kitty-0.36.4/Applications/kitty.app/'                                                                                                                                              
_LSOpenURLsWithCompletionHandler() failed with error -54.
```

I apologize if this is in the wrong place, thanks for any help.

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
```

**Comment by kwigley** [comment]
https://github.com/NixOS/nixpkgs/pull/352795

**Comment by viniciuspalma** [comment]
"the application dock does not have permission to open (null)" trying to open the kitty from dock or from launchpad gives me this error message.

An
