### ISSUE TITLE
QSyncthingTray fails to start due missing tray on i3 startup

### ISSUE THREAD

**Issue by Moredread** [nix-community/home-manager#603]
When starting i3 with `services.syncthing.tray = true;`  a window with "I couldn't detect any system tray on this system" is shown, and QSyncthingTray fails to start.

![2019-03-04-225643_312x84_scrot](https://user-images.githubusercontent.com/100848/53766229-97106880-3ed2-11e9-9998-20de4fc62864.png)

i3 is managed by home-manager as well.

It worked a few months ago, but I changed to the unstable version of QSyncthingTray a while ago and thought that had caused the issue. Now it happens even with the version in nixos-19.03.

I manually added qsyncthingtray to the i3 startup option, with a 5 second delay before running, but that is a crude fix.

Any idea how we can delay the start until a tray is available? Other services that depend on a tray seem to handle a missing tray by themselves.

**Comment by uvNikita** [comment]
Yes, I started to get this message from time to time as well. Not sure what is so special about qsyncthingtray though and haven't found a good fix for this issue for now.

Will appreciate any help on this one :)

**Comment by Moredread** [comment]
@uvNikita I guess other software is waiting for a tray or oppurtinistically adding a tray icon when it becomes available.

@coldfix How does udiskie handle installing the tray icon when no tray is available? I think I didn't see it fail on i3 startup in the time I used it.

**Comment by coldfix** [comment]
udiskie currently uses gtk, so I think it's pretty different. Apart from that I don't take special care, which may be why users can't use systemd units to start udiskie.

**Comment by rycee** [comment]
The tray applications typically have an `After` section in their service description, QSyncthingTray included
https://github.com/rycee/home-manager/blob/52692e299d72b5b42cf0451f9769d6f82229d692/modules/services/syncthing.nix#L49-L52
but I guess you are using a tray different from the ones listed?

That said, I'm thinking systemd will consider an After-relation fulfilled once the application is exec'd. Which may not mean that the application is ready to accept requests… So even if your tray is among the ones listed you can end up with this problem 🙁

**Comment by Moredread** [comment]
I'm using i3bar and it is started by i3 and doesn't have a service file afaik. :/

**Comment by Dietr1ch** [comment]
I have a similar issue with KDE. `qsyncthingtray.service` tries to start too early and fails, but a simple `restart` will make it work.


Currently it waits for `graphical-session-pre.target` and it's part of `graphical-session.target`.
Maybe it could just wait for `graphical-session.target` instead?

**Comment by league** [comment]
I've encountered this with KDE/Plasma too. I'm not sure how to get the `After` right so I thought of just introducing a delay. I had some hopes for adding something like `ExecStartPre=sleep 10` but that ended up just delaying the error by ten seconds (and holding up the entire login).

So here's a hack I came up with that _seems_ to work, although I guess I'd like to see it work consecutively a few more times before being certain…

```nix
{
    services.syncthing = {
      enable = true;
      tray = true;
    };
    systemd.user.services.qsyncthingtray.Service.ExecStart = lib.mkForce
      "${pkgs.stdenv.shell} -c '(${pkgs.coreutils}/bin/sleep 10; ${pkgs.qsyncthingtray}/bin/QSyncthingTray)&'";
}
```

The `mkForce` is to force it to override the `ExecStart` provided in `modules/services/syncthing.nix`, so I could do this in my configuration instead of branching and editing.

HTH.

**Comment by LunNova** [comment]
This should be reopened as it still occurs.

I couldn't get --wait working, so my current workaround is:

```
  systemd.user.services.${config.services.syncthing.tray.package.pname} = {
    Install.WantedBy = lib.mkForce [ ];
  };
  systemd.user.timers.${config.services.syncthing.tray.package.pname} = {
    Timer = {
      OnActiveSec = "10s";
      AccuracySec = "1s";
    };
    Install = { WantedBy = [ "graphical-session.target" ]; };
  };
```
