### ISSUE TITLE
bug: arRPC service takes a minute to stop

### ISSUE THREAD

**Issue by mbekkomo** [nix-community/home-manager#6075]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When stopping `arRPC.service`, it takes a minute or so to kill the process.

### Maintainer CC

@NotAShelf 

### System information

```markdown
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.24.10, nixpkgs: /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source
```

**Comment by mbekkomo** [comment]
I have a workaround to fix this by running the project with `bun`.

**Comment by NotAShelf** [comment]
I believe this is a mod caused by arRPC itself, and not home-manager.

What is the version of your kernel?

**Comment by mbekkomo** [comment]
6.6.59

**Comment by NotAShelf** [comment]
Related: https://github.com/OpenAsar/arrpc/issues/120

**Comment by mbekkomo** [comment]
I guess it's NodeJS problem, since running it with Bun doesn't reproduce the same issue.

**Comment by mbekkomo** [comment]
Closing this as NixOS/nixpkgs#355567 is much superior.
