### ISSUE TITLE
Expand fish support to functions and packages?

### ISSUE THREAD

**Issue by sondr3** [nix-community/home-manager#609]
I'm currently in the process of trying to convert my dotfiles and assorted stuff to using `home-manager` and currently I use a few custom functions and a few packages installed through `fisher`, I was curious if you'd be willing to accept PRs towards automatically installing this for `fish`? And if you have any pointers or code that can point me in the right direction if this is the case.

Thanks for `home-manager` :)

**Comment by rycee** [comment]
Glad you like Home Manager 🙂

I don't know much about the fish and nothing about fisher, so I think I can't help you very much. Perhaps @vdemeester, @gnidorah, @hyperfekt, or @Jomik have any idea whether this makes sense for the module?

**Comment by Jomik** [comment]
This here is my personal setup. I can open a PR with it, if wanted. 

https://github.com/Jomik/dotfiles/tree/master/.config/nixpkgs/modules/programs/fish
https://github.com/Jomik/dotfiles/blob/master/.config/nixpkgs/configurations/fish.nix

**Comment by sondr3** [comment]
That looks really sweet, I'd love to see it in `home-manager`.

**Comment by vdemeester** [comment]
@sondr3 @Jomik Nice setup ! Mine is a bit weirder, less polished… I do agree this would be a really cool addition to `home-manager`.

**Comment by loewenheim** [comment]
I also think that it would be great to have this.

**Comment by Jomik** [comment]
@vdemeester Do you mind sharing yours? It may have some nice ideas that we could incorporate.
@rycee I'll look at opening a PR for this then, probably this weekend.

**Comment by vdemeester** [comment]
> @vdemeester Do you mind sharing yours? It may have some nice ideas that we could incorporate.

ahah I can share but it won't have any nice ideas :sweat: (the nice ideas are still somewhere in an `org` file :joy:) — https://github.com/vdemeester/home/blob/master/modules/profiles/fish.nix :sweat_smile:
