### ISSUE TITLE
bug: Shouldn't programs.swaylock.package allow null?

### ISSUE THREAD

**Issue by s0racat** [nix-community/home-manager#6090]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue description

swaylock requires additional configuration for non NixOS and non-sway environments. 
Shouldn't such things be left to NixOS and the system?

### Maintainer CC

@rcerc

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11.20241113.24f0d4a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/c05d1sqfhkl93p3j5ykic68mgg1gsrvb-source`
```

**Comment by rcerc** [comment]
Thanks for reporting! I have filed #6095 to change this. In the meantime, you could set
```nix
package = pkgs.runCommandLocal "dummy" { } "mkdir $out";
```

**Comment by s0racat** [comment]
Thank you!

**Comment by rycee** [comment]
Instead of the `pkgs.runCommandLocal …` alternative above you can simply use `pkgs.emptyDirectory`. I think this is preferred in general over using a null.

**Comment by rcerc** [comment]
@rycee, I did not know about that! #6095 should be closed then?

**Comment by s0racat** [comment]
I understood. I will close this issue.
