### ISSUE TITLE
Request: Backport librewolf: use mkFirefoxModule to release 24.11

### ISSUE THREAD

**Issue by TilCreator** [nix-community/home-manager#6125]
### Description

I'm currently successfully using NixOS release-24.11 and home-manager master. I really like the mkFirefoxModule librewolf config and would really like to use it in the release-24.11 branch of home-manager.

**Comment by rycee** [comment]
Fair enough, I've cherry-picked that change now. Please give it a try.

**Comment by TilCreator** [comment]
Works great, thx!
