### ISSUE TITLE
Add rustup support

### ISSUE THREAD

**Issue by loewenheim** [nix-community/home-manager#618]
I only recently encountered home-manager, so forgive me if this is out of scope. I’m thinking it would be nice to let home-manager take care of rust toolchains, i.e., something like this:
```nix
programs.rustup = {
    enable = true;
    toolchains = {
        stable = {
            components = [ "clippy"];
        };
    };
    defaultToolchain = "stable";
};
```
I’m not so sure about overrides. There is also the question of how home-manager generations would interact with toolchain updates.

**Comment by dali99** [comment]
I use a nix-shell with direnv to do this
```
let
  moz_overlay = import (builtins.fetchTarball https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz);
  nixpkgs = import <nixpkgs> { overlays = [ moz_overlay ]; };
  rustNightlyChannel = (nixpkgs.rustChannelOf { date = "2019-01-26"; channel = "nightly"; }).rust;
        rustStableChannel = nixpkgs.latest.rustChannels.stable.rust.override {
                extensions = [
                        "rust-src"
                        "rls-preview"
                        "clippy-preview"
                        "rustfmt-preview"
                ];
  };
in
with nixpkgs;
  stdenv.mkDerivation {
    name = "moz_overlay_shell";
    buildInputs = [
      rustNightlyChannel
    ];
  }
```

**Comment by rycee** [comment]
I'm not familiar with rustup but if this module would configure rustup in some way then it seems to me a good fit 🙂

**Comment by LinArcX** [comment]
@dali99 Hi and thank you. Can you provide your solution as a PR?

**Comment by dali99** [comment]
@LinArcX The solution isnt a special thing for home-manager. it's a basic nix shell. That can be loaded via direnv, by including it in the folder of your project.

**Comment by rycee** [comment]
So should this issue be closed with the motivation that nix-shell is the better choice?

**Comment by loewenheim** [comment]
Probably, yes.

**Comment by oxalica** [comment]
What about using https://github.com/mozilla/nixpkgs-mozilla ?
