### ISSUE TITLE
bug: HM always writes settings.json for zed

### ISSUE THREAD

**Issue by DaRacci** [nix-community/home-manager#6193]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When using zed-editor, I've configured no settings or extensions but there is still a settings.json file generated.

I've figured out the issue comes from this https://github.com/nix-community/home-manager/blob/c7ffc9727d115e433fd884a62dc164b587ff651d/modules/programs/zed-editor.nix#L10-L11

Later on when the config is checked for being empty it will never be empty because auto_install_extensions will always be in mergedSettings even if there were none defined.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.11.11-xanmod1, NixOS, 25.05 (Warbler), 25.05.20241209.a73246e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-dev-pre20241210-8ddcdfb
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/racci/.config/nix/nix.conf:/nix/store/dfn5fg6l506vm7n8cchfys27x4wj27iy-stylix-kde-config/nix/store/dfn5fg6l506vm7n8cchfys27x4wj27iy-stylix-kde-config/etc/xdg/nix/nix.conf:/home/racci/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/racci/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/racci/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/wpr7kirrxzz1l8kb17vwnqggl8dbcly4-lix-2.92.0-dev-pre20241210-8ddcdfb/share`
 - nixpkgs: `/nix/store/yw6kg4rb9v8s3ypjbpspig5r81m4lr5s-source`
```

**Comment by teto** [comment]
classic problem. PR welcome

**Comment by DaRacci** [comment]
Fixed in https://github.com/nix-community/home-manager/commit/66c5d8b62818ec4c1edb3e941f55ef78df8141a8
