### ISSUE TITLE
bug: services.wob suggest wrong systemctl command

### ISSUE THREAD

**Issue by d3spairx** [nix-community/home-manager#6214]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

According to wob [documentation](https://github.com/francma/wob/blob/master/contrib/README.md#systemd-integration) you need to execute `systemctl enable --now --user wob.socket` for systemd integration to work.
But auto-generated command shown after `home-manager switch` outputs wrong command:

```Activating dconfSettings
Activating onFilesChange
Activating reloadSystemd
Suggested commands:
systemctl --user start wob.service
```

### Maintainer CC

@Scrumplex 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.66, NixOS, 24.11 (Vicuna), 24.11.711349.394571358ce8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager-24.11.tar.gz, nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Scrumplex** [comment]
That message is printed by the module that handles `systemd.user.startServices = "suggest";` When configuring wob through HM, it is already enabled. The command that is shown there will just start the (currently) stopped service.
