### ISSUE TITLE
bug: home-manager switch with @ in directory name fails

### ISSUE THREAD

**Issue by to-bak** [nix-community/home-manager#6217]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Running `home-manager switch` when home directory contains a `@` symbol, results in following error:
```
error: syntax error, unexpected '@', expecting end of file
```
The function to build news are luckily ran after home-manager switches; implying home-manager is still useable.

### Maintainer CC

@LunNova @rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-49-generic, Ubuntu, 22.04.5 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rycee** [comment]
I think this may be fixed now. Please update to latest master and try again.
