### ISSUE TITLE
bug: podman not installed on 24.11

### ISSUE THREAD

**Issue by undefined-landmark** [nix-community/home-manager#6252]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I recently switched from the unstable branch to 24.11. It seems that podman is no longer installed with just this line in my config: `services.podman.enable = true;`. On the unstable branch it was. 

For reference, this the relevant inputs portion of my flake on the 24.11 branch, which I'm using at the moment:
```
 inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.11";

    home-manager = {
      url = "github:nix-community/home-manager/release-24.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };
 };
```
With these inputs podman is not installed.

When I switch the inputs to unstable podman is installed:
```
 inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
 };
```

Comparing the release-24.11 and master branch I don't see any changes in the podman files. So maybe the issue lies in one of the modules it depends on?

If any further info or tests are needed I'm of course willing to help with that. Thanks for all the great work!

### Maintainer CC

@bamhm182 
@n-hass 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.67, NixOS, 24.11 (Vicuna), 24.11.20241227.d49da4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/salp9r9j3pj9cwqf06wchs16hy8g882k-source`
```

**Comment by bamhm182** [comment]
[This] (https://github.com/nix-community/home-manager/blob/master/modules/services/podman-linux/default.nix#L78) is the line in `master` that added podman to the user's path.

It is part of [this] (https://github.com/nix-community/home-manager/pull/6039) PR, which wasn't backported to 24.11.

**Comment by undefined-landmark** [comment]
Thanks for the quick response and explanation. Since the cause is known by you it's fine for me to close this issue. 

Just out of curiosity, would this be something that's worth backporting?

**Comment by bamhm182** [comment]
I'm not really sure what the criteria is for backporting, tbh, but it doesn't really feel like it considering you could add it to either the NixOS environment.systemPackages list or in your home manager packages as was done on that line.

**Comment by undefined-landmark** [comment]
Okay, agreed. Closing this issue. Wishing you a happy new year!
