### ISSUE TITLE
Add support for XDG user directories

### ISSUE THREAD

**Issue by lovesegfault** [nix-community/home-manager#628]
[XDG user directories](https://wiki.archlinux.org/index.php/XDG_user_directories) are widely used in the Linux ecosystem by Desktop applications.

It'd be nice to be able to correctly set them in home-manager.

**Comment by teto** [comment]
duplicate of https://github.com/rycee/home-manager/issues/95 ?

**Comment by Shimuuar** [comment]
@teto no it's not. XDG user dirs are for directories like desktop, default location for downnoads, music, etc. 

I wrote module for myself but it's not PR ready. No documentation mostly. I'm too lazy and/or busy to finish it myself but if someone is willing to take over I can share code

**Comment by teto** [comment]
oh I think I hadn't clicked the link, didn't know about these. I can imagine some interesting usecases. Share the code wouldn't hurt. 
Any example of you take advantage of xdg user directories ? 

> XDG user directories are widely used in the Linux ecosystem by Desktop applications.

I wonder about that, do you have some examples ? like gnome ? firefox ?

**Comment by Shimuuar** [comment]
Mostly to keep them out of the way. If some application wants to download some file and place it somewhere I'd prefer it to be somewhere inside waste dump which is `~/Desktop`. `$HOME` is full of various directories anyway. Also I'd like them consistently named using latin alphabet. Switching layouts to type `Загрузки` is seriously inconveninent

Firefox and telegram download files by default into `$XDG_DOWNLOADS_DIR`. Telegram doesn't even ask

Code available at https://github.com/Shimuuar/home-manager/ branch `xdg-user-dirs`
