### ISSUE TITLE
Feature Request: .xinitrc support

### ISSUE THREAD

**Issue by LinArcX** [nix-community/home-manager#650]
Sometime some users like me prefer to use [startx](https://github.com/NixOS/nixpkgs/blob/af6e2464bba2d178b278c66d822f8c95378e6f58/nixos/modules/services/x11/display-managers/startx.nix) instead of other display managers.
But after set it up, you have manually create __.xinitrc__ in your home directory.
I've created this file something like:
https://wiki.archlinux.org/index.php/Xinit#Switching_between_desktop_environments/window_managers
It will be nice to have the option to create this file declaratively via home-manager.

**Comment by teto** [comment]
you can do `home.file.".xinitrc".source = ./xinitrc;` or `home.file.".xinitrc".text = "toto";` Feel free to add a module that generates the .xinitrc from the configured window manager.
