### ISSUE TITLE
GnuPG with SSH support takes over forwarded agent through SSH

### ISSUE THREAD

**Issue by kalbasit** [nix-community/home-manager#667]
https://github.com/rycee/home-manager/blob/a6f0fa90f73eab34744bd1dadbc73490e86be057/modules/services/gpg-agent.nix#L151-L154

I'm trying to SSH from one laptop to another, and I've turned SSH agent forwarding on. However, the session variables are overriding the SSH_AUTH_SOCK and I'm unable to use the ssh-agent that was forwarded.

```console
$ ssh -A hades "env | grep SSH_AUTH_SOCK"
SSH_AUTH_SOCK=/tmp/ssh-osqjfnrSwe/agent.25019
$ ssh -A hades
(hades) $ echo $SSH_AUTH_SOCK
/run/user/2000/gnupg/S.gpg-agent.ssh
```

I think we should not export `SSH_AUTH_SOCK` if (a) it's already present in the environment and (b) `SSH_CONNECTION` is set and not empty. This won't work with the current implementation. Can this be moved to `programs.zsh.initExtra` and `programs.bash.initExtra`?

**Comment by teto** [comment]
so home-manager is installed on the remote laptop ? and when you connect, it overrides the current value of SSH_AUTH_SOCK ?
Seems like conditional export adds some impurity, which may end up making debug harder. maybe we should introduce sessionOverridablesVariables that get dispatched to initExtras to isolate these variables. Anyhow feel free to submit a PR.

**Comment by kalbasit** [comment]
Yes l, that's correct. 

Normally, I would jump head first when it comes to fixing OSS bugs, but I'm swamped this weekend all the way through next week. I'm hoping someone else would pick this up. If not, I'll submit one in a couple of weeks.

**Comment by rycee** [comment]
@kalbasit I _think_ this may be unnecessary if you use the gpg-agent extra socket. See, for example, https://superuser.com/a/884602 and https://mlohr.com/gpg-agent-forwarding/.

I've never used it but my understanding is that this will "take over" the SSH_AUTH_SOCK socket and instead forward it to the gpg-agent extra socket on your local machine. The extra socket is handled with more restrictions to avoid some security issues. From gpg-agent(1):
```
--extra-socket name
       The  extra socket is created by default, you may use this option
       to change the name of the socket.  To disable  the  creation  of
       the socket use ``none'' or ``/dev/null'' for name.

       Also listen on native gpg-agent connections on the given socket.
       The intended use for this extra socket is to setup a Unix domain
       socket  forwarding  from  a remote machine to this socket on the
       local machine.  A gpg running on the  remote  machine  may  then
       connect  to  the local gpg-agent and use its private keys.  This
       enables decrypting or signing data on a remote  machine  without
       exposing the private keys to the remote machine.
```

**Comment by kalbasit** [comment]
@rycee oh interesting. I hope this works in my situation: I use the same Yubikey on the local laptop and the remote laptop (whichever I'm actually using), and I want to be able to SSH from one laptop to another while sending my SSH agent with me. I'm assuming that the **local laptop** will rely on SSH_AUTH_SOCK being set to `"%t/gnupg/S.gpg-agent.ssh"` and the **remote laptop** would be using `"%t/gnupg/S.gpg-agent.extra"`.

**Comment by rycee** [comment]
@kalbasit Hmm, my understanding is that it actually is the opposite. You enable the extra socket locally and forward `%t/gnupg/S.gpg-agent.ssh` on the remote host to `%t/gnupg/S.gpg-agent.extra` locally.

If it is possible then the extra socket solution is probably best but otherwise I think you can accomplish what you initially asked for by putting
```
home.sessionVariables.SSH_AUTH_SOCK = mkForce "${SSH_AUTH_SOCK:-$(${pkgs.gnupg}/bin/gpgconf --list-dirs agent-ssh-socket)}"; 
```
in your configuration. I don't know whether it is a good idea or not to have this be the default in the ssh module.

**Comment by kalbasit** [comment]
I spent some time trying to make this work, but I hit a wall. This won't work if there's a GnuPG agent running on the host machine, and that's the situation I'm trying to solve. I could end up writing a script that runs on login for SSH sessions.

I ended up [learning how to forward my GnuPG agent to other hosts](https://github.com/kalbasit/shabka/pull/210), so it was a productive evening :smile: .

**Comment by rprije** [comment]
I also got bitten by this and came up with @rycee 's `"${SSH_AUTH_SOCK:-$(${pkgs.gnupg}/[...]` idea which worked out for me.

Finding this thread, I instead tried out `services.gpg-agent.enableExtraSocket = true` but it didn't help; SSH_AUTH_SOCK still gets bound to the ordinary local gnupg ssh socket which doesn't seem to be aware of any keys on my local host.

**Comment by Vonfry** [comment]
The `sessionVariables` is defined as `types.attrs`, so its attrs cannot work with `mkOverride`. We have to use `mkOrder`  to let the merge function override the original value.

**Comment by abbec** [comment]
I seem to be completely unable to override as suggested by @rycee (and @Vonfry). I just get the original value, regardless of `mkOverride`, `mkOrder` and `mkForce`.

**Comment by berbiche** [comment]
`sessionVariables` is no longer of type `types.attrs` so definition merging and conditional configuration is now possible.

**Comment by Ericson2314** [comment]
> I don't know whether it is a good idea or not to have this be the default in the ssh module.

Per https://github.com/NixOS/nixpkgs/blob/439b1605227b8adb1357b55ce8529d541abbe9eb/nixos/modules/programs/ssh.nix#L295-L297 that is how NixOS does ssh-agent, so I think the answer is yes.

**Comment by Ericson2314** [comment]
@berbiche I am not seeing what you are referring to?

**Comment by mhuesch** [comment]
seems like there's work underway to resolve this more tidily? :pray: 

in the meantime, as hopefully-useful context for others, I was unable to use:

```
home.sessionVariables.SSH_AUTH_SOCK = mkForce "${SSH_AUTH_SOCK:-$(${pkgs.gnupg}/bin/gpgconf --list-dirs agent-ssh-socket)}"; 
```

due to a syntax error, but succeeded with https://github.com/fricklerhandwerk/.config/commit/180e58745e401fb53273af8e2f3d8dbd96c4a9c9:

```
home.sessionVariables = {
  SSH_AUTH_SOCK = "\${SSH_AUTH_SOCK:-$XDG_RUNTIME_DIR/ssh-agent.socket}";
};
```
