### ISSUE TITLE
Creating symbolic links instead of putting files in /nix/store

### ISSUE THREAD

**Issue by sondr3** [nix-community/home-manager#676]
This is more of a question rather than a issue I have, there are some configuration files that I want to be able to change at a moments notice without having to build a new `home-manager` generation, I've looked around on GitHub and tried googling but couldn't find a function that does exactly what I want.

@adisbladis has something that is extremely similar to what I want in his [dotfiles](https://github.com/adisbladis/nixconfig/blob/53457d0f20/home-adisbladis-nixpkgs/home.nix#L5), however they are still linked from `/nix/store` and not my `~/.dotfiles` folder. Any ideas on how you'd do this?

**Comment by zeonin** [comment]
Looks like you're looking for something like [this](https://github.com/rycee/home-manager/issues/589#issuecomment-466594137).

**Comment by IgorGee** [comment]
`mkOutOfStoreSymlink` will create a cascade of symlinks back to your source file.

e.g.
`home.file.".foo".source = config.lib.file.mkOutOfStoreSymlink ./some-source-file;`

**Comment by TornaxO7** [comment]
> `mkOutOfStoreSymlink` will create a cascade of symlinks back to your source file.
> 
> e.g. `home.file.".foo".source = config.lib.file.mkOutOfStoreSymlink ./some-source-file;`

I have the following in my home-manager config:
```nix
xdg.configFile.neovim = {
      enable = true;
      recursive = true;
      source = config.lib.file.mkOutOfStoreSymlink ../config/nvim;
      target = "nvim";
};
```
Now if I add a line in `../config/nvim/init.vim`, the file in `~/.config/nvim/init.vim` doesn't get updated.
Did I understand something wrong?

**Comment by ncfavier** [comment]
I don't know how `mkOutOfStoreSymlink` interacts with `recursive`. Try without.

**Comment by TornaxO7** [comment]
my config now:
```nix
  xdg.configFile.neovim = {
      enable = true;
      #recursive = true;
      source = config.lib.file.mkOutOfStoreSymlink ../config/nvim;
      target = "nvim";
    };
```
but my `~/.config/nvim/init.vim` is still only readable and this is the output of `stat ~/.config/nvim/init.vim`:
```
  File: /home/tornax/.config/nvim/init.vim
  Size: 258       	Blocks: 8          IO Block: 4096   regular file
Device: 254,5	Inode: 1333037     Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-06-17 18:01:16.000000000 +0200
Modify: 1970-01-01 01:00:01.000000000 +0100
Change: 2023-06-17 18:01:16.427030191 +0200
 Birth: 2023-06-17 18:01:16.421029950 +0200
```
but `stat ~/.config/nvim` indeed showed, that `~/.config/nvim` is now a symbolic link:
```
  File: /home/tornax/.config/nvim -> /nix/store/my5wbg28hgl9hf8rdl6y9x9fy09ix6hs-home-manager-files/.config/nvim
  Size: 75        	Blocks: 8          IO Block: 4096   symbolic link
Device: 254,5	Inode: 4520803     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/  tornax)   Gid: (  100/   users)
Access: 2023-06-17 18:02:29.477017023 +0200
Modify: 2023-06-17 18:02:26.741904409 +0200
Change: 2023-06-17 18:02:26.741904409 +0200
 Birth: 2023-06-17 18:02:26.741904409 +0200
```

**Comment by ncfavier** [comment]
Oh. Right. You're using flakes. `../config/nvim` points to the Nix store.

If you want an actual symlink to your config directory, you'll have to pass the path to that to `mkOutOfStoreSymlink`. I have a helper function for that in my config, feel free to steal: https://github.com/ncfavier/config/blob/954cbf4f569abe13eab456301a00560d82bd0165/modules/nix.nix#L12-L14

**Comment by TornaxO7** [comment]
> If you want an actual symlink to your config directory, you'll have to pass the path to that to mkOutOfStoreSymlink

wait, so you mean that `mkOutOfStoreSymlink` needs to get the absolute path of the directory/file, right?

**Comment by ncfavier** [comment]
Yes, the absolute path to the source file on your filesystem, rather than the path in the tree that was copied to the Nix store.

**Comment by TornaxO7** [comment]
@ncfavier may I ask where you defined [`removePrefix`](https://github.com/ncfavier/config/blob/954cbf4f569abe13eab456301a00560d82bd0165/modules/nix.nix#LL14C46-L14C46)?

**Comment by ncfavier** [comment]
That's part of the nixpkgs library https://nixos.org/manual/nixpkgs/unstable/#function-library-lib.strings.removePrefix

**Comment by TornaxO7** [comment]
@ncfavier damn... I can't get your part of the code to work... do you have a link to a blog or somewhere which explains that quickly?  Otherwise I'd need to go through your whole dotfiles.

**Comment by ncfavier** [comment]
It's rather self-contained... `inputs` should point to your flake inputs, but you can also use a relative path like `./.` (or wherever the root of your flake is relative to the current file) instead of `inputs.self`.

The function takes an absolute store path like `/nix/store/<hash>-source/modules/foo.nix`, strips the absolute root prefix to get `/modules/foo.nix`, and then appends that to the actual path to your repo (in my case `/home/n/git/config`).

**Comment by TornaxO7** [comment]
Aye! But I'm struggling setting up this function!

At the moment, I have
```nix
  config.lib.meta = {
    configPath = "/home/tornax/dotfiles/config";
    mkMutableSymlink = path: config.lib.file.mkOutOfStoreSymlink
      (config.lib.meta.configPath + lib.string.removePrefix (toString inputs.self) (toString path));
  };
```
in a file, which gets loaded as a module in `nixpkgs.lib.nixosSystem.modules` and then I should be able to use `config.lib.meta.mkMutableSymlink` but I'm getting the following error message if I'm trying to rebuild my system with `sudo nixos-rebuild switch --flake .#pc`:
```
 error: Module `/nix/store/rz1swbv8cwbbq19mcbwf8wkxdrfcvc10-source/nixos-configurations/shared/default.nix' has an unsupported attribute `console'. This is caused by introducing a top-level `config' or `options' attribute. Add configuration attributes immediately on the top level instead, or move all of them (namely: console environment fonts i18n nix nixpkgs programs security services system users) into the explicit `config' attribute.
```

I can quickly show you, how I've set it up so you can get a better understanding of my dotfiles (*only* if you *have* time and if it's ok for you):

## Quick overview
So, I've setup the function `config.lib.meta.mkMutableSystem` in [`nixos-configurations/shared/default.nix`] which gets loaded as a module for all my systems as you can see in [flake.nix]. Now as for my `pc` system, it [loads](https://github.com/TornaxO7/dotfiles/blob/fixing_neovim/nixos-configurations/pc/default.nix#L15) my [shared home manager config](https://github.com/TornaxO7/dotfiles/blob/fixing_neovim/shared_home/default.nix) which will [set the xdg](https://github.com/TornaxO7/dotfiles/blob/fixing_neovim/shared_home/default.nix#L19) attribute of `home-manager` in [this file](https://github.com/TornaxO7/dotfiles/blob/fixing_neovim/shared_home/xdg.nix) where you can see, that [I'm calling the function](https://github.com/TornaxO7/dotfiles/blob/fixing_neovim/shared_home/xdg.nix#L6) which I defined in [`nixos-configurations/shared/default.nix`] before. I hope that helps!

[`nixos-configurations/shared/default.nix`]: https://github.com/TornaxO7/dotfiles/blob/fixing_neovim/nixos-configurations/shared/default.nix#L61-L65
[flake.nix]: https://github.com/TornaxO7/dotfiles/blob/fixing_neovim/flake.nix#L20

**Comment by ncfavier** [comment]
The error tells you what's wrong. Lose the `config`.

**Comment by TornaxO7** [comment]
Ok, I couldn't get this working... I'll just apply an absolute path for the time being. Thanks!

**Comment by martin-braun** [comment]
> home.file.".foo".source = config.lib.file.mkOutOfStoreSymlink ./some-source-file;

@IgorGee This seems to make a symbolic link into the store. This is a one way street. I'd love to have a two way street, meaning, the files should not be protected, so programs can write to it, and in conclusion, my home configuration repo should get dirty as I use programs.

I.e. symlinking `.config/weechat`, but allowing me to edit weechat settings within its `/fset`, and just reviewing and pushing those changes back into my home configuration.

Maybe this is against the concept of purity? But it would certainly benefit practicality.

@TornaxO7 It seems we both want to have the same. `mkOutOfStoreSymlink` doesn't really do what it advertises to do, because it still links into the store, making files locked on their generation until you switch again. 

Have you made any progress on this, or do you still use absolute paths to circumvent this limitation?

**Comment by ncfavier** [comment]
See https://github.com/nix-community/home-manager/issues/676#issuecomment-1595795685
