### ISSUE TITLE
{gcroots,profiles}/per-user/<username> should belong to 1000 error even though it does.

### ISSUE THREAD

**Issue by gwimm** [nix-community/home-manager#683]
As the title says i'm getting `stat`'s usage and then an error:
```
WARNING: the per-user profile dir /nix/var/nix/profiles/per-user/sai should belong to user id 1000
```
everything works, just annoying when everything is temporarily shot up
120 lines. thanks for an answer in advance.

**Comment by kalbasit** [comment]
Are you using nix-darwin?

**Comment by gwimm** [comment]
oh no, i'm using `home-manager` through nixos
