### ISSUE TITLE
imapnotify module: handle quoting and multiline strings

### ISSUE THREAD

**Issue by leotaku** [nix-community/home-manager#693]
Nix and home-manager generally handle multiline strings and quoting very well. The recently merged #657 imapnotify module is an exception to this.

Because the module directly generates javascript from the supplied nix expressions, quoting majorly messes things up.
This is especially frustrating because it might break currently working configurations that want to use the imapnotify module. 

@NickHu maybe you would be interested in fixing this?

**Comment by rycee** [comment]
Thanks for the report! As somebody not using imapnotify it would help if you could provide an excerpt of a HM configuration and the resulting imapnotify configuration.

**Comment by leotaku** [comment]
This is the configuration I am currently using. It works because I use single quotes inside the `passwordCommand` string.

```nix
{ config, pkgs, lib, ... }:
{
    # ...
    # read password from postfix-style sasl password map
    passwordCommand = ''${pkgs.gnugrep}/bin/grep '${address}' ${pass_map_file} | ${pkgs.gnugrep}/bin/grep -o '[^:]*$' '';

    # misc settings for home-manager email modules
    
    imapnotify = {
      enable = true;
      boxes = syncBoxes;
      onNotify = "${pkgs.isync}/bin/mbsync ${dir}";
      onNotifyPost = {
        mail = ''${pkgs.notmuch}/bin/notmuch --config=${config.xdg.configHome}/notmuch/notmuchrc new && ${pkgs.libnotify}/bin/notify-send "You got mail!" "${userName}"'';
      };
    };
  # ...
}
```

This is the generated imapnotify config.js:
The quotes in `onNotifyPost` get handled correctly, as would newlines (although not used in this config).

```js
var child_process = require('child_process');

function getStdout(cmd) {
    var stdout = child_process.execSync(cmd);
    return stdout.toString().trim();
}

exports.host = "outlook.office365.com"
exports.port = 993;
exports.tls = true;
exports.username = "leo.gaskin@brg-feldkirchen.at";
exports.password = getStdout("/nix/store/fwjg5nq86pa0vf2pkmqfsiwvp6x9wcn2-gnugrep-3.3/bin/grep 'leo.gaskin@brg-feldkirchen.at' /etc/nixos/nixos-config/private/postfix/sasl_password_maps | /nix/store/fwjg5nq86pa0vf2pkmqfsiwvp6x9wcn2-gnugrep-3.3/bin/grep -o '[^:]*$' ");
exports.onNotify = "/nix/store/bda14wxf7cbdxpxz0lykk14p8zj5xf6w-isync-1.3.0/bin/mbsync outlook";
exports.onNotifyPost = {"mail":"/nix/store/47xnv58z5pi230ah91dk8k080vq1b4qq-notmuch-0.28.3/bin/notmuch --config=/home/leo/.config/notmuch/notmuchrc new && /nix/store/kvsq6sfh9sciwys3zavhda0nvcs626rw-libnotify-0.7.7/bin/notify-send \"You got mail!\" \"leo.gaskin@brg-feldkirchen.at\""};
exports.boxes = ["Inbox"];
```

However this does not seem to work for the `passwordCmd` string, it breaks when double quotes are used.

This is the relevant part of the output with the `passwordCmd` string containing double quotes:

```js
exports.password = getStdout("/nix/store/mzvffy1yvzq8mhygga1r7q0npc7qcdnb-gnugrep-3.3/bin/grep "leo.gaskin@brg-feldkirchen.at" /etc/nixos/nixos-config/private/postfix/sasl_password_maps | /nix/store/mzvffy1yvzq8mhygga1r7q0npc7qcdnb-gnugrep-3.3/bin/grep -o '[^:]*$' ");
```

Maybe changing `toString` to `toJSON` [here](https://github.com/rycee/home-manager/blob/2f819d1647d4c73aad6ca8fec8348beaae4bb870/modules/services/imapnotify.nix#L58) would suffice. Idk

**Comment by rycee** [comment]
@Lyndeno Which version of HM are you using? As far as I can tell, this should have been solved since release 21.05 since the configuration there is generated by `toJSON`.

**Comment by Lyndeno** [comment]
I thought I was encountering this issue, but it seemed to have been a configuration error on my part as I was able to correct it.
I believe I tried using `onNotifyPost` and the application did not like that.
Using just `onNotify` made my config work properly.

**Comment by rycee** [comment]
Thanks for checking. I'll close this issue for now, please comment if there is anything else here.
