### ISSUE TITLE
nextcloud-client: start upon switch

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#697]
so I just added   `services.nextcloud-client.enable = true;` to my config. Was expecting to see nextcloud-client popup into my tray but it didn't (using i3). What's the systemd parameter I should change to make it working ? I can submit a PR.

**Comment by rycee** [comment]
Hmm, I don't see anything obviously wrong with the current definition of the systemd unit. What does `systemctl --user status nextcloud-client` say? And perhaps `journalctl --user -u nextcloud-client.service`.

**Comment by teto** [comment]
hum also noticed it doesn't work with the system proxy. The process doesn't have http_proxy in its environment even though I set it via the nixos networking.proxy option. 
I might have a look when I get more time next week.

NB: I checked if upstream provided a service but not yet. For future reference:
https://github.com/nextcloud/desktop/issues/728

**Comment by teto** [comment]
@rycee any reason we should not inherit nixos sessionVariables in systemd's user services ? or I should just add nixos.config.networking.proxy.envVars to the sessionVariables when nixos is detected ?

**Comment by benneti** [comment]
I think I might have a solution for one of your problems, namely adding the following (in home-manager.users.your-user):
``` nix
    systemd.user.services.nextcloud-client = {
      Service.ExecStartPre = lib.mkForce "${pkgs.coreutils}/bin/sleep 15";
      Unit = {
        After = lib.mkForce [ "graphical-session.target" ];
        PartOf = lib.mkForce [  ];
      };
    };
```
In detail, for me (using gnome) was that apparently nextcloud started to early such that libindicator was not setup and running already. 
To make sure it is running I needed to add the sleep and for the sleep to actually do something usefull and not only create a black screen it was necessary to remove the service from the `graphical-session.target` and for it to be clean I actually want to start it after the graphical-session not `graphical-session-pre.target` .

**Comment by augustebaum** [comment]
https://nostalebots.xyz/
