### ISSUE TITLE
KDE / Plasma configuration

### ISSUE THREAD

**Issue by tobiasBora** [nix-community/home-manager#731]
Hello,

First, thanks a lot for this great project. I'd like to use it to configure my KDE/plasma, for example to keep track of the theme, but I was not able to find in the manual any reference to it. Is it because KDE is not configurable by this project, or is it because I missed something?
Thanks!

**Comment by uvNikita** [comment]
Hi!

You can see the supported options in this online manual: https://rycee.gitlab.io/home-manager/options.html. As far as I know, KDE configuration is not supported at the moment and, unfortunately, I'm not sure how much work it would take to implement it.

That said, if KDE configuration is stored as text files, it should be relatively simple. You can check other [modules](https://github.com/rycee/home-manager/tree/master/modules) to get an idea of how to implement it.

**Comment by mestaritonttu** [comment]
See also #607

**Comment by AleXoundOS** [comment]
The principle point here I think is coexistence of KDE "System Settings" application with declarative home-manager configuration. So the workflow is not clear. KDE settings application may replace symbolic links with new files or refuse to do it confusing the settings application. Both situations may produce unexpected results for the end user.
_But overall, I think making KDE settings configurable declaratively would be a huge breakthrough for both KDE and home-manager._

**Comment by tobiasBora** [comment]
True. But we can imagine something in between : KDE seems to ask to users to use a command line utility to modify the settings instead of modifying some files : maybe we could create "declaratively" a script that runs the appropriate commands, and let the users run this script when they want to change KDE's configuration via home manager and/or periodically. It's not truly declarative (except maybe if we cover all configurations and if we put in read-only mode all files, which may not be desirable) but that way a user could both configure KDE declaratively and via the graphical tools.

**Comment by AleXoundOS** [comment]
> KDE seems to ask to users to use a command line utility to modify the settings instead of modifying some files

It seems [kwriteconfig](https://manned.org/kwriteconfig/d47c2de0) is this command line utility.
_Though, nix won't know if a user has changed settings via "System Settings", so changes won't be permanent. But it's another story._

**Comment by tobiasBora** [comment]
Yes exactly thanks. Well changes via "System Settings" will be permanent if they are not overwritten by nixos' script I guess.

**Comment by AleXoundOS** [comment]
Nice hypothesis.

**Comment by kennyballou** [comment]
There seems to be clear overlap between this issue and #607.  Can we close this in favor of #607 since most of the context and items discussed here are already covered?
