### ISSUE TITLE
xmonad can not find xmonad-contrib modules

### ISSUE THREAD

**Issue by lem0n4de** [nix-community/home-manager#732]
Importing a module from xmonad-contrib library throws error when restarting xmonad with `xmonad --recompile && xmonad --restart`.

```
xmonad.hs:3:1: error:
    Could not find module ‘XMonad.Util.SpawnOnce’
    Use -v to see a list of the files searched for.
  |
3 | import XMonad.Util.SpawnOnce(spawnOnce)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Please check the file for errors.

```

I have `enableContribAndExtras = true;`. Also added xmonad-contrib and xmonad-extras libraries to `home.packages` but it does not solve the problem either.

**Comment by rycee** [comment]
Are you certain you use the xmonad generated by Home Manager? You need that specific one for it to succeed in finding the modules. Try
```console
$ home-manager build && ./result/home-path/bin/xmonad --recompile && ./result/home-path/bin/xmonad --restart
```

**Comment by lem0n4de** [comment]
I don't think I am using the one that is in the home manager. Home manager is configured in configuration.nix file. I can successfully change something in xmonad config and rebuild the system.  But the problem is I can not reload it with a key that is bound to `spawn "xmonad --recompile && xmonad --restart"`, a restart is needed. Is there a way to get the resulting xmonad in there?

**Comment by rycee** [comment]
Sorry for the delay. I think the easiest way to access xmonad from within the `xmonad.hs` file would be to use
```haskell
spawn "$HOME/.nix-profile/bin/xmonad --recompile && $HOME/.nix-profile/bin/xmonad --restart"
```

**Comment by alexameen** [comment]
It is worthwhile to create a script `~/.xmonad/build` which calls `$HOME/.nix-profile/bin/xmonad --recompile` to get things to behave (more or less) normally.

**Comment by bsima** [comment]
Alex Ameen <notifications@github.com> writes:

> It is worthwhile to create a script `~/.xmonad/build` which calls
> `$HOME/.nix-profile/bin/xmonad --recompile` to get things to behave
> (more or less) normally.

sure, i don't think home-manager will remove it on `home-manager switch`

**Comment by zimbatm** [comment]
One workaround could be to call `xmonad --recompile` in the activation script.
