### ISSUE TITLE
Feature Request: JetBrains Module

### ISSUE THREAD

**Issue by evanjs** [nix-community/home-manager#734]
In my NixOS configuration, I have an [expression](https://github.com/evanjs/nixos_cfg/blob/master/modules/jetbrains.nix) that ensures all JetBrains 
packages are as up-to-date as possible.

One of the problems with updating JetBrains programs so often, is that I will often have to reconfigure various settings, such as installed plugins, plugin settings, JetBrains credentials (or equivalent license verification options for any "professional" programs)

This is something I've been wanting to automate before, but I'm not sure if it would have been feasible before I started using Nix.

Furthermore, while it seems (at least to me) like an ambitious undertaking, I think it might be well suited to the home manager project.

In terms of core features, I would imagine a set of "universal" options that would apply to most, if not all JetBrains applications.
e.g. JetBrains account email

and perhaps options that are specific to various applications
e.g. gdb Debugger path (CLion)

Again, while this seems like it would be a huge project (at least in my mind), I would be very excited to see this functionality available in home-manager.

Happy to investigate or contribute as well, just not sure where I would even start with this.

**Comment by isitreallyalive** [comment]
If there is interest in this I would be more than happy to work on it! I'm not sure how popular JetBrains is within the Nix community though.
