### ISSUE TITLE
Skip dyre

### ISSUE THREAD

**Issue by Ericson2314** [nix-community/home-manager#742]
Xmonad, taffybar, and other such things use dyre. Dyre's an interesting idea, but if I am using home manager I rather just rebuild those tools with Nix. It would be nice if we worked with upstream to make dyre optional in these cases.

**Comment by rycee** [comment]
Yes, that seems like a nice idea! Right now the compilation of these applications is a bit ad-hoc and fragile. If it were possible to directly create a Nix package with the right configuration baked in it would be much more robust.

I think such a thing would be best placed in Nixpkgs, though. Then everybody could take advantage of this, not just HM users.
