### ISSUE TITLE
dunst cannot find icons in the icon-path

### ISSUE THREAD

**Issue by a-schaefers** [nix-community/home-manager#744]
Hi, I'm not actually trying to get icons working per se. I'm only trying to make dunst stop logging messages to journalctl for every notification it displays.

I get this message in **journalctl** every time I run a notify-send command
`Jul 03 00:57:41 latitude org.freedesktop.Notifications[674]: WARNING: No icon found in path: 'dialog-information'
`
And via nm-applet
`Jul 03 00:57:24 latitude org.freedesktop.Notifications[674]: WARNING: No icon found in path: 'nm-signal-75'
`
And via diskie
`Jul 03 00:57:02 latitude org.freedesktop.Notifications[10665]: WARNING: No icon found in path: 'drive-removable-media'
`

Here's the relevant home.nix file
https://github.com/a-schaefers/nix-config/blob/master/modules/desktop/home.nix

I do see it is creating ~/.config/dunst/dunstrc and populating it with icon-path as follows:
`icon_path="/run/current-system/sw/share/icons/hicolor/32x32/actions:/run/current-system/sw/share/icons/hicolor/32x32/animations:/run/current-system/sw/share/icons/hicolor/32x32/apps:/run/current-system/sw/share/icons/hicolor/32x32/categories:/run/current-system/sw/share/icons/hicolor/32x32/devices:/run/current-system/sw/share/icons/hicolor/32x32/emblems:/run/current-system/sw/share/icons/hicolor/32x32/emotes:/run/current-system/sw/share/icons/hicolor/32x32/filesystem:/run/current-system/sw/share/icons/hicolor/32x32/intl:/run/current-system/sw/share/icons/hicolor/32x32/mimetypes:/run/current-system/sw/share/icons/hicolor/32x32/places:/run/current-system/sw/share/icons/hicolor/32x32/status:/run/current-system/sw/share/icons/hicolor/32x32/stock:/home/adam/.nix-profile/share/icons/hicolor/32x32/actions:/home/adam/.nix-profile/share/icons/hicolor/32x32/animations:/home/adam/.nix-profile/share/icons/hicolor/32x32/apps:/home/adam/.nix-profile/share/icons/hicolor/32x32/categories:/home/adam/.nix-profile/share/icons/hicolor/32x32/devices:/home/adam/.nix-profile/share/icons/hicolor/32x32/emblems:/home/adam/.nix-profile/share/icons/hicolor/32x32/emotes:/home/adam/.nix-profile/share/icons/hicolor/32x32/filesystem:/home/adam/.nix-profile/share/icons/hicolor/32x32/intl:/home/adam/.nix-profile/share/icons/hicolor/32x32/mimetypes:/home/adam/.nix-profile/share/icons/hicolor/32x32/places:/home/adam/.nix-profile/share/icons/hicolor/32x32/status:/home/adam/.nix-profile/share/icons/hicolor/32x32/stock:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/actions:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/animations:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/apps:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/categories:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/devices:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/emblems:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/emotes:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/filesystem:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/intl:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/mimetypes:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/places:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/status:/nix/store/6chj1gmlrz720xi1dcxiy2q6w4hbzp2y-hicolor-icon-theme-0.17/share/icons/hicolor/32x32/stock"`

So I'm not sure what the problem is.

**Comment by rycee** [comment]
It seems you only have the "hicolor" theme enabled, this is a very sparse theme that will be missing most named icons. To be able to show proper icons it's best to set the `iconTheme` option, for example, I have
```
dunst = {
    iconTheme = {
      package = pkgs.gnome3.adwaita-icon-theme;
      name = "Adwaita";
    };
    # …
};
```
in my configuration. To disable icons all together I think you can add
```
dunst = {
  settings = {
    icon_position = off
    # …
  };
  # …
};
```
although I notice that `icon_position = off` is supposed to be the default value. Perhaps dunst is trying to load icons even when they won't be used?

**Comment by a-schaefers** [comment]
Hi, I've now tried 
package = pkgs.gnome3.adwaita-icon-theme; name = "Adwaita"; 
as you suggested, but the errors in journalctl still persist. 

It's a slight annoyance because I use a script that puts all of my dmesg and journalctl messages into notify-send, thereby creating an infinite stream of missing icon messages. (lol) For now, I've modified the script to ignore these errors.

**Comment by clkamp** [comment]
The problem seems to be that at least 'dialog-information' is one of the legacy icons and that category is not included in https://github.com/nix-community/home-manager/blob/66a68b4a58f7c554bd7746acd51ff7cc02840b0a/modules/services/dunst.nix#L111
I will try to prepare a patch for that

**Comment by SpiderUnderUrBed** [comment]
Is there any fix to this? I still get the issue.

**Comment by SpiderUnderUrBed** [comment]
My configuration:
```
    dunst = {
        enable = true;
        iconTheme = {
          name = "Adwaita";
          package = pkgs.gnome.adwaita-icon-theme;
        };
        settings = {
         global = {
          width = 300;
          height = 300;
          offset = "30x50";
          origin = "top-right";
          transparency = 10;
          frame_color = "#eceff1";
          font = "Droid Sans 9";
         };

         urgency_normal = {
           background = "#37474f";
           foreground = "#eceff1";
           timeout = 10;
         };
        };
```

**Comment by SpiderUnderUrBed** [comment]
Note, I fixed the issue, just remove the old dunstrc file and rebuild.

**Comment by ulinja** [comment]
There is definitely still something broken here, the `icon_path` string in the generated `dunstrc` does not contain the correct entries needed to resolve icons correctly. The replies above help to get rid of the `journalctl` messages, but don't help those who actually want icons in their notifications.

I've had to do the following to get Adwaita icons to work:
```nix
{
  services = {
    dunst = {
      enable = true;
      iconTheme = {
        name = "Adwaita";
        package = pkgs.adwaita-icon-theme;
      };
      settings = {
        global = {
          icon_theme = "gnome";
          icon_path = "/run/current-system/sw/share/icons/gnome";
          enable_recursive_icon_lookup = true;
        };
      };
    };
  };
}
```
`pkgs.adwaita-icon-theme` creates a directory called `gnome` in `/run/current-system/sw/share/icons`, and here I am telling dunst to look recursively in that directory.

To get other icon packs working, the process is similar, but you need to set the fallbacks correctly. Obsidian-Mint inherits from Obsidian for example:
```nix
{
  services = {
    dunst = {
      enable = true;
      iconTheme = {
        name = "Obsidian";
        package = pkgs.iconpack-obsidian;
      };
      settings = {
        global = {
          icon_theme = "Obsidian-Mint,Obsidian";
          icon_path = "/run/current-system/sw/share/icons/Obsidian:/run/current-system/sw/share/icons/Obsidian-Mint";
          enable_recursive_icon_lookup = true;
        };
      };
    };
  };
}
```
