### ISSUE TITLE
`home.files.onChange` and `--dry-run`

### ISSUE THREAD

**Issue by znewman01** [nix-community/home-manager#751]
If I have:

```
home.file."text.txt" = {
  text = "";
  onChange = "echo TEST";
};
```

and run `home-manager switch --dry-run` I see:

```
...
TEST
...
```

This isn't a huge problem in my use case, but I can imagine a destructive `onChange` command and that'd be a little surprising.

Now I could add `$DRY_RUN_CMD` to my `onChange` entry (it works), but it seems like that perhaps shouldn't be the job of every `onChange` writer.

Instead, I'd prefer we either:
        
- Just add `$DRY_RUN_CMD` [here](https://github.com/rycee/home-manager/blob/f82246171b253801021c6f98cc50fa461cd972e5/modules/files.nix#L222). This has the upside of being simple, but the downside of potentially complicating things if there's a complicated shell expression.
- Do something slightly cleverer to shell-escape the `onChange` value.

**Comment by znewman01** [comment]
I see that [xresources.nix](https://github.com/rycee/home-manager/blob/695791165769f8ba5c5097af9acd62c2ddeceff7/modules/xresources.nix#L80) sticks `$DRY_RUN_CMD` *in* `onChange`. If that's intended, maybe a note in the documentation for `onChange`?

**Comment by znewman01** [comment]
I am still quite interested and would be happy to write a PR. I'll start by making a docs change while we decide what to do long-term.

**Comment by sumnerevans** [comment]
I don't think it makes sense to automatically add `$DRY_RUN_CMD` because that won't work if the `onChange` is more complicated than a single command. I agree that we should definitely make a documentation change, though.

**Comment by ncfavier** [comment]
I agree with the initial concern that it's not the job of every `onChange` hook to add `$DRY_RUN_CMD` before each of its (possibly many) commands.

As an alternative, consider something like this:

```nix
home.activation.onFilesChange = hm.dag.entryAfter ["linkGeneration"] (
  concatMapStrings (v: ''
    if (( ''${changedFiles[${escapeShellArg v.target}]} == 1 )); then
      if [[ -v DRY_RUN || -v VERBOSE ]]; then
        echo "Running onChange hook for" ${escapeShellArg v.target}
      else
        ${v.onChange}
      fi
    fi
  '') (filter (v: v.onChange != "") (attrValues cfg))
);
```

**Comment by rycee** [comment]
@ncfavier Seems like an nice solution, could you create a PR?

**Comment by ncfavier** [comment]
Opened https://github.com/nix-community/home-manager/pull/2239
