### ISSUE TITLE
Wrong store path set when bootstrapping

### ISSUE THREAD

**Issue by fricklerhandwerk** [nix-community/home-manager#753]
As many here, I am reaching for the Holy Grail of managing my machines and user configs fully declaratively.

The extra twist in [my approach](https://github.com/fricklerhandwerk/.config) is that user configs should be able to evolve independently of the system hosting them. To this end I have a module called [`home-config`](https://github.com/fricklerhandwerk/.config/blob/master/modules/home-config.nix), which allows system users to fetch a repository with `home-manager` configuration after each rebuild - given such a configuration does not exist yet - and to instantiate it automatically before login. As a result, everything is immediately available after bootstrapping the system.

For users to update their configuration, they get a convenience wrapper to `home-manager`:

```nix
{ config, lib, pkgs, utils,  ... }:
with lib; with pkgs;
let
  users = config.home-config.users;
  home-manager-src = builtins.fetchGit {
    name = "home-manager-${config.system.stateVersion}";
    url = https://github.com/rycee/home-manager;
    ref = "release-${config.system.stateVersion}";
  };
  home-manager-overlay = self: super: {
    home-manager = (callPackage home-manager-src {}).home-manager;
  };
  home-manager-for-user = cfg: (symlinkJoin {
    name = "home-manager";
    paths = [
      (writeShellScriptBin "home-manager" ''
        exec ${home-manager}/bin/home-manager -f $HOME/${cfg.path}/${cfg.file} $@
       '')
      home-manager
    ];
  });
in
{
  # ...
  # use `home-manager` with correct path per user
  users.users = mkIf (users != {}) (mapAttrs' (user: cfg:
  nameValuePair user {
    packages = [ (home-manager-for-user cfg) ];
  }) users);
}
```

Now an issue arises when bootstrapping the system:

```
home-manager = (callPackage home-manager-src {}).home-manager;
```

calls [the `home-manager` module](https://github.com/rycee/home-manager/blob/c3520bfa52b30f984e73e9616abe4d11ab56de36/default.nix#L4-L6) and hardcodes the store path of `src` into [`@HOME_MANAGER_PATH@`](https://github.com/rycee/home-manager/blob/c3520bfa52b30f984e73e9616abe4d11ab56de36/home-manager/home-manager#L67). At bootstrap time, that store path is `/mnt/nix/store/.../home-manager` instead of `/nix/store/.../home-manager`, such that the respective files cannot be found later.

The more or less obvious workaround is to define the wrapper as

```shell
exec env NIX_PATH="home-manager=${home-manager-src}" \
${home-manager}/bin/home-manager -f $HOME/${cfg.path}/${cfg.file} $@
```

although I do not really understand why that even works.

1. Why does `${home-manager-src}` evaluate to `/nix/store/...`, but `./.` evaluates to `/mnt/nix/store/...` in that situation? Is this a bug/inconsistency in `nix`?
2. Why does the build process hard-code a search path?
3. Why does the build even use a search path?

I see how this is an optimization to save another round of copying, but why leave the option to source `home-manager` files from somewhere other than the repository it came from initially? Using a search path in the first place seems to me like a doorway for non-determinism, as it was in my case. And while there is a workaround, it is a clumsy hack to overcome this underlying weirdness.

I'd be glad to set up a PR to improve this, following the discussion.

**Comment by rycee** [comment]
I'm not certain how to best solve it, perhaps the path will be evaluated to the expected value if you replace
```
  home-manager-overlay = self: super: {
    home-manager = (callPackage home-manager-src {}).home-manager;
  };
```
by
```
  home-manager-overlay = self: super: {
    home-manager = callPackage "${home-manager-src}/home-manager" {
      path = "${home-manager-src}";
    };
  };
```

**Comment by fricklerhandwerk** [comment]
This works indeed. Does that hint at an upstream bug-feature then? In any case that leaves the workaround only slightly less hacky.

In my project I now decoupled user configuration even more, such that the system's `home-manager` is no longer required for bootstrapping and the problem is avoided. I'd still like to understand what is going on, though... ;)
