### ISSUE TITLE
Feature Request - keep custom files with program configuration

### ISSUE THREAD

**Issue by peterhoeg** [nix-community/home-manager#809]
Some software config is spread over multiple files where HM doesn't support all of the knobs, so we end up with configuration spread over ```programs.xxx```, ```home.file.xxx``` and ```xdg.configFile.xxx```.

An example is gnupg, where the settings for ```gpg.conf``` goes into ```programs.gnupg``` but the other bits of configuration are spread out over other parts of the config.

It would be neat if every program also exposed a ```files``` attrset, which would be combined with ```home.file``` and ```xdg```.

**Comment by rycee** [comment]
This seems like it could get quite confusing. I would suggest simply keeping the gnupg configuration in a `gnupg.nix` file and importing it into your main configuration.
