### ISSUE TITLE
Include Oh-My-Fish to home manager

### ISSUE THREAD

**Issue by mudrii** [nix-community/home-manager#844]
I am new to NixOS and home-manager and my shell is Fish and would be really great is maintainers help to integrate oh-my-fish with the home-manager.

Oh My Fish provides core infrastructure to allow to install packages which extend or modify the look of fish shell. It's fast, extensible and easy to use.
Very similar to Oh-my-zsh that is already in NixOs package repo
source URL: https://github.com/oh-my-fish/oh-my-fish

**Comment by ryanorendorff** [comment]
Does #635 address your issue sufficiently? You can import oh-my-fish plugins/themes in your home-manager configuration through the changes mentioned there.

**Comment by mudrii** [comment]
I will try it Thx
