### ISSUE TITLE
JAVA_HOME is not set

### ISSUE THREAD

**Issue by denisgarci** [nix-community/home-manager#845]
Thanks for this great project!
After installing the `jdk` package the `JAVA_HOME` environment variable is not set. Could this be set just by using:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/java.nix
?

**Comment by Gerschtli** [comment]
You can either use this NixOS module, source the setup-hook similar to the NixOS module manually in your home-manager config (`home.nix`) or my preferred method, create a java module in home-manager similar to the NixOS module as this module make definitly more sense on a per user base :)

**Comment by spinus** [comment]
why not just adding JAVA_HOME variable?

**Comment by ShamrockLee** [comment]
I'm a newcomer here.
What should I use to replace the `environment.shellInit` in [`Java.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/java.nix) module of NixOS?
It would be great if it can be replaced the way `environment.systemPackages` is by `home.packages`.
The original code is as follows:
```Nix
environment.shellInit = ''
      test -e ${cfg.package}/nix-support/setup-hook && source ${cfg.package}/nix-support/setup-hook
    '';
```
BTW, should I add any copyright notice of something similar when making a pull request with the modified version? The code in the [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs) repo is distributed under the MIT license.
