### ISSUE TITLE
Agda stdlib

### ISSUE THREAD

**Issue by turion** [nix-community/home-manager#854]
Setting up Agda with its standard library is a bit cumbersome because one needs to fiddle with `.agda-lib` files which seem to be stored in home. I managed to set it up following blog.ielliott.io/agda-nixos/ and I wondered if it's a good idea to include that in home manager. I could try and make a PR if you want.

**Comment by alexarice** [comment]
To be honest I think agda is in need of a `withPackages` construct but there are a couple of dead PRs on nixpkgs

**Comment by turion** [comment]
The agda story in `nixpkgs` is in much better shape now. I think this isn't needed much currently.
