### ISSUE TITLE
Setting environment for (some) user systemd services

### ISSUE THREAD

**Issue by PierreR** [nix-community/home-manager#855]
I am having trouble setting the environment for user services such as [albert](https://github.com/albertlauncher/albert) or [lorri](https://github.com/target/lorri/) in home-manager.

For both of them my first try has been to set the environment using the usual way. Here is an example with lorri: https://github.com/Gerschtli/nur-packages/blob/master/hm-modules/services/lorri.nix#L54.

For `albert` or `lorri` the equivalent service defined in /etc/nixos/configuration.nix will work. Here is an example of such definition for lorri: https://github.com/CIRB/devbox/blob/master/system/lorri.nix#L31

Anyhow at the end what works for me is to add this configuration in home.nix : 
```
session.initExtra = ''
      systemctl --user import-environment
'';
```
I then omit any environment setting in the definition of the service. 

Would it make sense to have an option that would just do that in the xsession setting ? Or would it be better  to come up with a huge list of imported variables in  `xsession.importedVariables` ?

What makes it work in `/etc/nixos/configuration.nix` (all the required environments variables for user systemd service seems to come up auto-magically) ?

**Comment by leotaku** [comment]
I think it would be great if home-manager user services would have access to the environment set by `home.sessionVariables` by default. 

@rycee Was it a deliberate choice to not have the services have access to the user-environment, or did it just happen?

**Comment by vxid** [comment]
+1. This causes the mbsync service to fail if using password-store in a non-standard dir to unlock email passwords.

**Comment by chrispickard** [comment]
I'm having issues with lorri as a systemd service (`services.lorri.enable`), but not if I just run `lorri daemon` directly in my shell. I see lots of ssl cert errors. I believe this is the same issue

**Comment by jonas-schievink** [comment]
Still relevant.

**Comment by jonas-schievink** [comment]
.

**Comment by xhalo32** [comment]
This is what I used to set the PATH in a user service managed by home-manager:

```nix
Service.Environment =
  let
    path = with pkgs; [
      // ...
    ];
  in
  [ "PATH=${lib.makeBinPath path}:${lib.makeSearchPathOutput "bin" "sbin" path}" ];
```

Copied it directly from the [nixos systemd module](https://github.com/NixOS/nixpkgs/blob/dd89086e67137847d9755781f19f7269681746b1/nixos/lib/systemd-lib.nix#L473)
