### ISSUE TITLE
Document how to install unfree packages

### ISSUE THREAD

**Issue by turion** [nix-community/home-manager#856]
There is some discussion of this in https://github.com/rycee/home-manager/issues/463, but it's a bit confusing (at least to me) and it would be nice to have this in one central place, possibly even as a `home-manager` setting.

**Comment by teto** [comment]
feel free to edit the github wiki, there is not much at the moment so thre is room to improve it :)

**Comment by codygman** [comment]
Maybe my failure to make it work for my config can enhance this wiki entry.

I get this error:

From this config:

```nix
{ config, pkgs, home, ... }:
with import <nixpkgs> {};
with lib;
let
  myEnv = builtins.getEnv "MYENV";
in
{
  imports = [ ./work.nix ];
  nixpkgs.config.allowUnfree = true;
  programs = {
    home-manager.enable = true;
    emacs.enable = true;
    git = {
      enable = true;
      userName = "Cody Goodman";
    };
  };

  home = {
    packages = with pkgs; [
      ripgrep
      source-code-pro
    ];
  };

  services = {
    redshift = {
      enable = true;
      provider = "geoclue2";
    };
  };
}

```

work.nix
```nix
{ config, pkgs, home, ... }:
with import <nixpkgs> {};
with lib;
{
  programs =
    {
      git = {
        userEmail = "cody@workEmail.com";
      };
    };
  home = {
    packages = [ teams ];
  };
  services = {
  };
}
```

**Comment by teto** [comment]
when you do `with import <nixpkgs> {};`  it calls the default.nix at the root of nixpkgs, which calls next https://github.com/NixOS/nixpkgs/blob/bfbccde17065cdc9bc7e3844935545a997045314/pkgs/top-level/impure.nix#L15 . You can change the default parameters by doing
```
with import <nixpkgs> {           config = { allowUnfree = true; }; };
```

**Comment by turion** [comment]
@codygman Why do you do `with import <nixpkgs> {};` instead of `with pkgs;`, using the pkgs argument that home manager gives you? I believe if you would do that, then this setting has an effect:

```
nixpkgs.config.allowUnfree = true;
```
