### ISSUE TITLE
Incompatible with CentOS

### ISSUE THREAD

**Issue by tbenst** [nix-community/home-manager#879]
Let me preface by saying that I understand home-manager targets NixOS only, so not a bug per se, but given that it works great on Ubuntu, I'd love to get working on CentOS too!

**Describe the bug**
On a fresh install of CentOS 8, I installed nixpkgs. After reboot, I installed home-manager. The install succeeded but took many minutes and brought computer to a halt; `top` showed very little, but `iotop` showed a ton of io related to manpages (several GBs read).

After reboot, the GUI freezes on login attempt. If I only source the nixpkgs shell per default install in .bash_profile, I can login but cannot open basic programs like firefox, and even opening bash requires a ctrl-c, which prints `bash: __vte_prompt_command: command not found` and subsequently gives me a prompt. The `home-manager` command hangs and gives no output, even `home-manager --help`.

Commenting out `if [ -e /home/tyler/.nix-profile/etc/profile.d/nix.sh ]; then . /home/tyler/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer` in `.bash_profile`, and the home-manager sourcing, followed by logout/login resolves all issues.

**To Reproduce**
1. Download CentOS iso
2. Install workstation environment
3. Install nix: `curl https://nixos.org/nix/install | sh`
4. Install home-manager per README
5. reboot
6. try to login

**Comment by freuk** [comment]
Hello @tbenst, the following works out of the box on a fresh CentOS7 installation for me. 

```
#nix installation
curl -L https://nixos.org/nix/install | sh

#making everything 20.03
nix-channel --remove nixpkgs
nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
nix-channel --add https://github.com/rycee/home-manager/archive/release-20.03.tar.gz home-manager
nix-channel --update

#home-manager installation
nix-shell '<home-manager>' -A install
```
