### ISSUE TITLE
Should neovim expose an extraPackages?

### ISSUE THREAD

**Issue by lovesegfault** [nix-community/home-manager#894]
Currently `programs.neovim` exposes `extraPythonPackages` and the Python 3 analogue. There are, however, non-python packages that it would be interesting to make available/visible from Neovim, such as Yarn and Node for coc-vim, or any number of formatters for vim-ale.

Should we expose this next to current Python options?

**Comment by rycee** [comment]
Seems the neovim wrapper only offers `extraPythonPackages` and `extraPython3Packages`:
https://github.com/NixOS/nixpkgs/blob/d3248c915ed04b78734ff1bfc11f0644c4531941/pkgs/applications/editors/neovim/wrapper.nix#L14-L23
I'm afraid that if HM is to support additional options along these lines support for them would first have to be added to the wrapper.

**Comment by jorsn** [comment]
The neovim wrapper also offers `extraMakeWrapperArgs`. I'm using them like this in my overlay

```.nix
{
  wrapNeovim = nvim: args: super.wrapNeovim nvim (
    if args ? "extraPackages"
    then super.lib.filterAttrs (n: v: n != "extraPackages") args // {
      extraMakeWrapperArgs = (args.extraMakeWrapperArgs or "")
        + " --prefix PATH : '${super.lib.makeBinPath args.extraPackages}'";
    }
    else args
  );
}
```
and adding args to `makeWrapper` is the way this would be implemented in nixpkgs.

Maybe it would be more pleasant to add this to the wrapper in nixpkgs, but until then, in home-manager one could add

```.nix
extraMakeWrapperArgs = "--prefix PATH : '${super.lib.makeBinPath cfg.extraPackages}'";
```

to the call of wrapNeovim.

**Comment by biosan** [comment]
Thank you very much @jorsn for the quick (and very complete) response, I learned a lot and I'm very sorry for the late reply.
But it's still unclear to me how to set the extra packages in my `home.nix` file.
I'm missing something very simple, as a said before I'm very new to Nix and home-manager.

**Comment by jorsn** [comment]
No problem @biosan!
Did you try copying my above snippet (without the `…`)? Did you get errors?

Could you give an example (with code) of what you are trying to do? E.g. the relevant parts of your `home.nix` (or the complete file)? If we talk about your specific problem (and not about home-manager itself), maybe you open a thread on <https://discourse.nixos.org> and we discuss it there? If this results in something relevant to the development of home-manager, we can still post that back here.
