### ISSUE TITLE
Warn when `programs.zsh` is enabled system-wide

### ISSUE THREAD

**Issue by lovesegfault** [nix-community/home-manager#910]
Whenever you have zsh plugins in home-manager _and_ `programs.zsh` enabled system-wide, you run into a cache-invalidation issue that makes the shell start dramatically slower. I lost my benchmark results but they were all in the 1.6-2.0s range.

Disabling `programs.zsh` in the global config makes things work beautifully:
```
❯ for i in $(seq 1 10); do time zsh -i -c exit; done
zsh -i -c exit  0.06s user 0.03s system 103% cpu 0.079 total
zsh -i -c exit  0.06s user 0.02s system 104% cpu 0.078 total
zsh -i -c exit  0.05s user 0.03s system 103% cpu 0.078 total
zsh -i -c exit  0.06s user 0.02s system 103% cpu 0.079 total
zsh -i -c exit  0.06s user 0.02s system 103% cpu 0.079 total
zsh -i -c exit  0.05s user 0.03s system 103% cpu 0.079 total
zsh -i -c exit  0.06s user 0.03s system 103% cpu 0.081 total
zsh -i -c exit  0.06s user 0.02s system 103% cpu 0.083 total
zsh -i -c exit  0.06s user 0.02s system 103% cpu 0.081 total
zsh -i -c exit  0.05s user 0.03s system 103% cpu 0.081 total
```

I think solving this proper is a hard problem, and was previously discussed in #108, so in lieu of fixing it proper I wonder whether it's something we could warn against at generation-time?

**Comment by lovesegfault** [comment]
CC. @uvNikita who seems to have his hand in zsh stuff

**Comment by rycee** [comment]
Just wanted to chime in to say that HM cannot reliably tell whether a configuration is being generated for a NixOS system or some other Linux system. Maybe it might be possible to detect this issue and print a warning at activation time?

**Comment by peterhoeg** [comment]
Source `/etc/os-release` and `[ "$ID" == "nixos" ]` ?

**Comment by lovesegfault** [comment]
To add to @peterhoeg's proposal there is also `/etc/os-release` which for NixOS looks like this:
```
NAME=NixOS
ID=nixos
VERSION="20.03pre209091.100012e55bc (Markhor)"
VERSION_CODENAME=markhor
VERSION_ID="20.03pre209091.100012e55bc"
PRETTY_NAME="NixOS 20.03 (Markhor)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/nixos/manual/index.html"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```
