### ISSUE TITLE
zsh: PATH in non-interactive shell

### ISSUE THREAD

**Issue by wedens** [nix-community/home-manager#915]
I use zsh configured via home-manager as a nixos module.

The problem is that when I try to  use machine as a remote builder, it fails with "zsh:1: command not found: nix-store".

And indeed `ssh user@host "nix-store --version"` fails with the same error.  

`ssh user@host "echo \$PATH"` results in: `/usr/bin:/bin:/usr/sbin:/sbin:/nix/store/gjdvdr56japvy6237rigkfvia1q0gyaa-openssh-7.9p1/bin`.

I think setting PATH should be moved to zshenv which is read by both interactive and non-interactive shells.

**Comment by wedens** [comment]
zsh configured via nixos module does [this](https://github.com/NixOS/nixpkgs/blob/076860e0340a5e4a909b9a710e186508b14d1c90/nixos/modules/programs/zsh/zsh.nix#L147).

On nixos, am I expected to enable zsh nixos module in addition to HM zsh module?

**Comment by uvNikita** [comment]
This would be nice to solve, but I'm not sure how... The PATH for the login shell is set by /etc/profile which is not sourced by a non-interactive shell. You can check this by comparing the output from `$ zsh -xc 'exit'` and `$ zsh -xlc 'exit'`.

`config.system.build.setEnvironment` which is also used in `/etc/profile` is nixos option, so we can't use it in home-manager.

**Comment by uvNikita** [comment]
That said, we could define path as a set type in zshenv and add at least paths we know there. I can try to experiment with it.

**Comment by onsails** [comment]
issue is still actual
