### ISSUE TITLE
Support `programs.bash.promptInit`

### ISSUE THREAD

**Issue by epage** [nix-community/home-manager#917]
NixOS provides `programs.bash.promptInit` which just gets put in the interactive shell

See https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/modules/programs/bash/bash.nix#L153

This has the advantage of being able to be compose with other bash configuration because of the implicit set merging.  In contrast, I can't have two files that populate `programs.bash.initExtra`.

**Comment by epage** [comment]
I'm willing to implement this but first I wanted to check on an idea I had for implementing this.

I want to first refactor home-manager to structurally mirror `nixpkgs/nixos` so we can easily diff the two repos.  I'd then migrate configuration options over from `nixpkgs/nixos`, maintaining `home-manager`s defaults if they differ.  I then assume in `unstable` (and a 20.x), we could change the defaults to match `nixpkgs/nixos`.

**Comment by rycee** [comment]
I have nothing in particular against `programs.bash.promptInit` so if you make a PR to introduce it that would be fine. Although I don't particularly see any strong need for it since people can just put their configuration in `programs.bash.initExtra` (which should merge just fine across files).

I would be more skeptical about a large scale restructuring of the project. If it is with the intent of unifying modules across NixOS and HM then perhaps. But I'd like a more elaborate plan and some analysis of how badly compatibility will be broken…

**Comment by epage** [comment]
> Although I don't particularly see any strong need for it since people can just put their configuration in programs.bash.initExtra (which should merge just fine across files).

So I'm still new to Nix.  I knew it could merge sets and lists.  It can also merge strings?

> I would be more skeptical about a large scale restructuring of the project. If it is with the intent of unifying modules across NixOS and HM then perhaps. But I'd like a more elaborate plan and some analysis of how badly compatibility will be broken…

Step 1: Make repo layout the same.  This shouldn't break compat.  This is mostly doing things like taking taking `modules/bash.nix` and making it `modules/bash/bash.nix`

Step 2: Copy extra settings over from NixOS.  For anything that was previously hard coded, make the default to what was hard coded.  For anything that doesn't come over cleanly, leave that to Step 3 for evaluation.

Step 3: Change defaults.

With this plan, compatibility will only be broken by Step 3.  The PR for it will be relatively minimal (setting changes), so we can evaluate how bad compatibility is broken and can decide from there what the plan is moving forward, including not doing it.  Personally, I feel its healthier for the ecosystem if we are able to unify NixOS and home-manager for the sake of reducing gotchas people might run into.

**Comment by epage** [comment]
>  If it is with the intent of unifying modules across NixOS and HM then perhaps. 

Also, I used this missing config as a conversation opener.  In general, I feel that unifying will mean that (1) I'll be less likely to run into problems when moving things between `configuration.nix` and `home.nix` and (2) it'll be easier bring in those features in the future.
