### ISSUE TITLE
Make home.keyboard a normal module

### ISSUE THREAD

**Issue by leotaku** [nix-community/home-manager#931]
Nearly all NixOS and home-manager modules offer an `enable` option that allows the user to turn them on or off. The `home.keyboard` module instead has to be set to `null` to disable it.

Would you be willing to convert the `home.keyboard` module into a "normal" module, or are there some other factors that prevent this change? I also believe this change could be made in a largely backwards-compatible manner, if this concerns you.

**Comment by rycee** [comment]
Yes, I think this might be a good idea, I'll ponder a bit on it.
