### ISSUE TITLE
 proposition: Have an XDG configuration setting

### ISSUE THREAD

**Issue by teto** [nix-community/home-manager#95]
This is a copy of my initial post in https://github.com/NixOS/nixpkgs/issues/29945 as home-manager might be a better place to deal with this kind of behavior.

I like to sync my dotfiles across machines in a repository. It's easier to do with programs that comply with XDG specs as there is a clean separation between cache files and config ($XDG_CACHE_HOME)/$XDG_CONFIG_HOME. Some programs don't follow XDG but their behavior can still be changed (via environment variables) to mimic XDG. For instance for zsh one can set ZDOTDIR="$XDG_CONFIG_HOME/zsh".
A list of such software is available
https://wiki.archlinux.org/index.php/XDG_Base_Directory_support

I wonder if this could be generalized via some nixos option, i.e., autoexport some variables (or wrap programs to use command line flags towards the config path) so that program behaves more XDG-like.

Might be problematic and more of a toy-thing but I would fancy sthg like that xD (and can contribute to it

**Comment by rycee** [comment]
For syncing purposes I would suggest putting the dotfiles in a repo together with your HM config and let HM put them in place :-) For example, from my config:

```nix
{
  home.file.".XCompose".source = dotfiles/xcompose;
  home.file.".config/mpv/input.conf".source = dotfiles/mpv-input.conf;
  home.file.".config/mpv/mpv.conf".source = dotfiles/mpv-mpv.conf;
  home.file.".mailcap".source = dotfiles/mailcap;
}
```

That said. I think this is a good idea to honor XDG more in HM and to make programs prefer XDG. My current idea is to add an `xdg` module with some options, for example, `xdg.configDir` whose default value is `"${config.home.homeDirectory}/.config"` (see #86), `xdg.cacheDir`, `xdg.dataDir`, etc. There would also be `xdg.downloadDir`, `xdg.musicDir`, etc. although I don't know precisely how to handle those currently as they are subject to i18n.

Further, I'm thinking that we either are opinionated and always prefer using the XDG directories and configure programs accordingly or to have a Boolean option like `xdg.preferXdg` that a user can enable to indicate that they would prefer XDG whenever possible.

**Comment by teto** [comment]
I do sthg similar though I use stow to symlink my files rather than home-manager. Can you do sthg similar but with folders ? like `home.folder.".config/mpv".source = "dotfiles/mpv"` (or some recursive copy instruction ? )

I would be fond of an xdg.preferXdg setting (that could be overriden on a per module basis). The only opiniated config then are the defaults for the different modules. for instance what to choose for  LESSHISTFILE ? (I have to $XDG_CACHE_HOME/less_historyfile) for instance.

**Comment by rycee** [comment]
@teto Try `home.folder.".config/mpv".source = dotfiles/mpv;` 🙂

**Comment by teto** [comment]
can i do sthg similar now with xdg ? this failed w/o "folder". Tried to look at the code but I don't the datatype that accepts "folder"
```
  xdg = {
    enable = true;
    configHome.folder."nvim/toto".text = ''
      hello world
      '';
  };

```

Btw the xdg stuff is cool :)

**Comment by rycee** [comment]
Hmm, you want to create a file `$XDG_CONFIG_HOME/nvim/toto` containing the text "hello world"? If so then you need the `xdg.configFile` option. I.e., try
```
xdg.configFile."nvim/toto".text = ''
  hello world
'';
```

**Comment by teto** [comment]
great thanks ! I was looking to use the vim module for nvim but found out
it was simpler in my case to just generate the nvim files.

2017-10-31 21:32 GMT+09:00 Robert Helgesson <notifications@github.com>:

**Comment by teto** [comment]
Going back to the initial issue. I don't get your answer
`or to have a Boolean option like xdg.preferXdg that a user can enable to indicate that they would prefer XDG whenever possible.`
What I propose is more of a `fakeXdg` or `partialXdg` boolean so that hm can generate this kind of export (when a the module in enabled in hm ofc).
```
    MUTT="$XDG_CONFIG_HOME/mutt";
    WEECHAT_HOME="$XDG_CONFIG_HOME/weechat";
    TIGRC_USER="$XDG_CONFIG_HOME/tig/tigrc";
    LESSHISTFILE="$XDG_CACHE_HOME/less/history";
    NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/notmuchrc";
    INPUTRC="$XDG_CONFIG_HOME/inputrc";
    IPYTHONDIR="$XDG_CONFIG_HOME/ipython";
    JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter";
```
I suppose such module would have a fakeXdg variable too to override the global config such that `mutt.fakeXdg = if cfg.fakeXdg != null then cfg.fakeXdg else global_config.fakeXdg`
So for instance it would look
```
xdg.fakeXdg=true;
programs.mutt {
  enable = true;
  fakeXdg = false; // option 1 -> do nothing
  // without local fakeXdg or if set to true, HM exports the variable MUTT="$XDG_CONFIG_HOME/mutt";
}; 

```
NB on a sidenote I tried your tip to symlink dotfiles but it fails for filenames starting with a '.' for instance `home.file.".wgetrc".source = dotfiles/home/.wgetrc;` fails. Seems it 's not allowed. Anyway to bypass ?

**Comment by rycee** [comment]
Yeah, I imagined something like your `fakeXdg`. But I'd rather not just stuff tons of environment variables in the user environment, in particular for packages that the user don't even have installed. Another issue is that some program would need extra help creating directories, etc.

I'm wondering whether it wouldn't be best to have an `nixpkgs-xdg-overlay.nix` or something that overrides or wraps packages in Nixpkgs to make them XDG aware. E.g., for less can have
```
wrapProgram bin/less \
  --set LESSHISTFILE="''${XDG_CACHE_HOME:-$HOME/.cache}/less/history" \
  --run "mkdir -p $LESSHISTFILE"
```
Problem is to avoid having to do lots of rebuilds…

W.r.t. source path whose filename starts with dot, this is an intentional restriction Nix makes for security reasons. As far as I know the workaround is not to use such filenames. E.g., to have `home.file.".wgetrc".source = dotfiles/home/dotwgetrc;` instead.

**Comment by Infinisil** [comment]
I actually started working on an xdg wrapper overlay type thing! I'm gonna polish it up a bit and then share it here (in a few hours probably)

**Comment by Infinisil** [comment]
It took quiet a while, but I polished it up decently enough to share: https://github.com/Infinisil/nix-xdg

With this you can XDG wrap packages with an attrset like this:

```nix
{
  wget.flags = { cache }: "--hsts-file=${cache}/hsts";
  less.env.ZDOTDIR = { config }: config;
}
```

See the Readme for a thorough walk-through.

**Comment by rycee** [comment]
That is quite nice! I'm not entirely certain how to best integrate with Home Manager. Maybe simply an `xdg.enableOverlay` option?

**Comment by teto** [comment]
@Infinisil I like the wrapper approach, it broadens the scope for programs that propose only a flag and not the environment variable.

**Comment by onsails** [comment]
> Hmm, you want to create a file `$XDG_CONFIG_HOME/nvim/toto` containing the text "hello world"? If so then you need the `xdg.configFile` option. I.e., try
> 
> ```
> xdg.configFile."nvim/toto".text = ''
>   hello world
> '';
> ```

is there any way to do so with dirs? like
```nix
xdg.configDir."nvim/filetypes".source = ./home-neovim/config/filetypes;
```

**Comment by berbiche** [comment]
@onsails Please open a new issue next time.

> 
> is there any way to do so with dirs? like
> 
> ```nix
> xdg.configDir."nvim/filetypes".source = ./home-neovim/config/filetypes;
> ```

`xdg.configFiles` supports both "files" and "directories".

See:
https://nix-community.github.io/home-manager/options.html#opt-xdg.configFile
https://nix-community.github.io/home-manager/options.html#opt-xdg.configFile._name_.recursive

**Comment by berbiche** [comment]
The xdg module is now pretty substantial. If anything is missing or would need improvement, please open a new issue. 😁
