### ISSUE TITLE
Closure size: ruby adds GCC into runtime path

### ISSUE THREAD

**Issue by danbst** [nix-community/home-manager#959]
I was wondering why is GCC in my `home-manager-generation`:
```
/nix/store/76yrl5azs0qdyd0a6g4sgqj8w7lipbz5-home-manager-generation
╚═══activate: …ATH=/bin:$PATH \.    /nix/store/hjhfvxg80gif0xz1hyac975qanzvkd2j-ruby-2.6.5/bin/ruby /nix/store/…
    => /nix/store/hjhfvxg80gif0xz1hyac975qanzvkd2j-ruby-2.6.5
    ╚═══lib/libruby_v2_6_5.so.2.6.5: …or a client wakeup.../nix/store/47hi526v96skkwgdj7d9c31ccd1xivrx-gcc-wrapper-8.3.0/bin/gcc...Non…
        => /nix/store/47hi526v96skkwgdj7d9c31ccd1xivrx-gcc-wrapper-8.3.0
        ╚═══bin/cpp: …k disable=SC2193.[[ "/nix/store/c6jvs50xrcy2m1nbrmpjwad51f62fcrx-gcc-8.3.0/bin/cpp" = *++ ]] && …
            => /nix/store/c6jvs50xrcy2m1nbrmpjwad51f62fcrx-gcc-8.3.0
```
I don't know about ruby, but home-manager shouldn't itself require GCC, right?

**Comment by rycee** [comment]
Yeah, it's a bit unfortunate. We have an optional dependency on Ruby for the systemd service restart script and for whatever reason Ruby needs the gcc runtime. There is a `rubyMinimal` package in Nixpkgs master that probably could be used but it doesn't seem to build clearly. I've added a comment here: https://github.com/NixOS/nixpkgs/commit/7d4c1ae7f11b72ced45fb686fa21a9c9ae1e0588#commitcomment-36600908
